### ISSUE TITLE
When will it be released BambuStudio

### ISSUE THREAD

**Issue by mdapang** [bambulab/BambuStudio#1]
Hello, hello, I have been waiting for a day, may I ask when BambuStudio will be released

**Comment by looxonline** [comment]
Wow bro...you made an issue for this. Come on.

**Comment by Moorviper** [comment]
The source code is here so it is released.

**Comment by critchie** [comment]
When can we expect downloads to be available on the Releases page? Some of us don’t have the means to compile the code.

**Comment by SuddenImpact58** [comment]
July 22

**Comment by lanewei120** [comment]
you can find the answer at https://blog.bambulab.com/the-plan-for-the-coming-weeks
the formal release will be ready on July 22.
