### ISSUE TITLE
Add warning if time-lapse is enabled but no time lapse wipe tower present

### ISSUE THREAD

**Issue by LegacyOfBob** [bambulab/BambuStudio#100]
Add a warning at slicing time / sending to printer if you've enabled time-lapse but haven't added the wipe tower. I know there is already a warning when you enable the time-lapse, but going from print to print you might be leaving time-lapse enabled but not re-adding the prime tower each time.

**Comment by YifanWuBambu** [comment]
@LegacyOfBob 
wipe tower will be automatically added if timelapse is enabled in next release
