### ISSUE TITLE
Screen stuck at "Connecting to server" but i can hit "send"

### ISSUE THREAD

**Issue by pitops** [bambulab/BambuStudio#101]
Hey so i think this counts as a bug. In the picture below you can see that it says `Connecting to server` but in reality i can send the model over and starts printing.

![Screenshot 2022-08-07 at 1 11 28 PM](https://user-images.githubusercontent.com/9624361/183286004-1d95dac2-4020-426f-886a-bfb68542bc75.png)

However, I get no info from the printer on the device screen but if i hit the play button to see the camera, again it works. This stopped working like 2 weeks ago second day i received the printer.

Any clues?

**Comment by pitops** [comment]
Hey all after updating to v1.1.1.1 i don't have this issue, yet. Do what you will with this information ;p

**Comment by YifanWuBambu** [comment]
Hi @pitops 
We optimized the network connection in v1.1.1.1.
Have you still met this issue recently?

**Comment by pitops** [comment]
Hi @YifanWuBambu i think its fixed, no issues so far
