### ISSUE TITLE
Cant use the full bed cause it "needs" that section for the cutter? lower the bed....

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#1013]
its honestly dumb that it needs that bed section for filament cutting, it could just lower the bed cut it then raise the bed back up, this would only become an issue when the bed is near the bottom, cut it out then

**Comment by Benderrodrigu3z** [comment]
also where is the default use all bed profile with key override?

**Comment by Benderrodrigu3z** [comment]
so like dropping the bed 10mm but think about it while its purging drop the bed, after it cuts while its purging raise the bed
0 time loss

**Comment by Benderrodrigu3z** [comment]
lower the bed then move it to the cutter, thats the only time lost, please give us this as an option

**Comment by Sirwill1968** [comment]
Feature: Lower enough to cut without hitting model. Go purge.  While purging bring back up to print height the print bed saving time.  Make it so this only takes place if object placed in exclusion zone.  Then exclusion zone only truly applies for top XXmm of the Z height.

**Comment by Benderrodrigu3z** [comment]
doing this you would still not be able to use the entire bed because if it moves there it cuts it but this would make it so you could cut the white section in half as half of it doesn't hit the cutter on movements

**Comment by RobinWhitfield** [comment]
Whether you lower the bed or not, the cutter lever would still be hit by the toolhead.

The model being printed is always lower than the nozzle anyway.

**Comment by SaltWei** [comment]
It's impossible to solve the problem by lower bed. This is mechanical limitation. Please see this wiki.
https://wiki.bambulab.com/en/knowledge-sharing/print-volume-limitations.
