### ISSUE TITLE
[BUG] [MacOS] Can't scroll down the options to save gcode files, plates, slices... 

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#1014]
**Describe the bug**
https://m.facebook.com/groups/bambulabofficialusers/permalink/930213347922685/ 

**To Reproduce**
MacStudio M1 running latest MacOS Ventura update and latest BLStudio software. 

Just trying to save file gcode or do anything other than Print Plate.... 

**Expected behavior**
The options to be usable.

**Comment by lanewei120** [comment]
what is your studio version number?
1.4.0 or 1.4.1?

we have fixed a similiar issue in 1.4.1
if you are using 1.4.0, please have a try for 1.4.1 here: https://github.com/bambulab/BambuStudio/releases/tag/v01.04.01.52

**Comment by bolsoncerrado** [comment]
1.4.0.18

So I have to update manually? OK I'll do and report back.

**Comment by bolsoncerrado** [comment]
OK "Check for updates" was not detecting it so I manually installed it and yes, problem is gone.

It only  has a visual glitch with the mouseover you may want to fix at a later moment...


https://user-images.githubusercontent.com/10992914/210732842-e1732220-b6fc-461e-a844-d35982356816.mp4

**Comment by Benderrodrigu3z** [comment]
you don't save the profiles there, see below pics
@bolsoncerrado 
![Screen Shot 2023-01-05 at 10 12 47 AM](https://user-images.githubusercontent.com/48887257/210828504-85cf5dd6-a8ce-4021-8efd-e1b3a03d83ae.png)
![Screen Shot 2023-01-05 at 10 12 55 AM](https://user-images.githubusercontent.com/48887257/210828511-40896b14-d938-4781-9246-833d19cedfb0.png)
![Screen Shot 2023-01-05 at 10 13 04 AM](https://user-images.githubusercontent.com/48887257/210828515-5890cc81-2377-411b-bc5f-9ee57d93b3cd.png)

**Comment by bolsoncerrado** [comment]
> you don't save the profiles there, see below pics @bolsoncerrado ![Screen Shot 2023-01-05 at 10 12 47 AM](https://user-images.githubusercontent.com/48887257/210828504-85cf5dd6-a8ce-4021-8efd-e1b3a03d83ae.png) ![Screen Shot 2023-01-05 at 10 12 55 AM](https://user-images.githubusercontent.com/48887257/210828511-40896b14-d938-4781-9246-833d19cedfb0.png) ![Screen Shot 2023-01-05 at 10 13 04 AM](https://user-images.githubusercontent.com/48887257/210828515-5890cc81-2377-411b-bc5f-9ee57d93b3cd.png)

So what? It was solved already on 1.4.1

Nothing to do with unsaved profiles...

**Comment by Benderrodrigu3z** [comment]
okay so I think what your asking for is to save the stl file with all this information correct? if yes that means that you need to do a File->Export->Generic 3MF

**Comment by bolsoncerrado** [comment]
No, my issue was already resolved (GUI GLTICH)
