### ISSUE TITLE
Scrolling can cause values in input with arrows to change

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1016]
**Describe the bug**
When scrolling if the mouse pointer stops above an input with arrows, next scrolling changes the value instead of scrolling.

This happens when you are scrolling and need to re-adjust the finger to scroll some more.

**3mf File for This Bug**
No need

**To Reproduce**
1. Place a mouse pointer so when you scroll you hover over inputs.
2. Begin the scroll.
3. Stop scrolling over an input with arrows.
4. Scroll some more.

**Expected behavior**
The scrolling continues, no value is changed.

**Screenshots**
![bambu-studio scroll-bug](https://user-images.githubusercontent.com/1620004/210711245-248b7d02-b4d3-4549-8c71-7d5cb07b2842.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.1
- Bambu Studio v1.4.1.52

**Comment by bambu123** [comment]
Yes, the scrolling should be disabled in the SpinCtrls here.

**Comment by SaltWei** [comment]
Available in v1.5.0 public beta
