### ISSUE TITLE
Rectilinear Grid Pattern for Interface Pattern.

### ISSUE THREAD

**Issue by wirlybird** [bambulab/BambuStudio#1018]
When the interface extrusions all run in the same direction for multiple layers they tend to start to curl at the edges.
If they curl enough the nozzle can catch on them.
Having the layers run perpendicular helps to prevent this.

**Comment by SaltWei** [comment]
Could you give more explanation about this by some pictures？

**Comment by tangketan** [comment]
Hi @wirlybird , sorry that I can't find any picture attached. But there is another issue about this. See #1221 .
I give an example of "Grid" interface pattern. Is it what you want?

**Comment by wirlybird** [comment]
From my experience I think rectilinear would be best rather than “Grid” pattern.

**Comment by tangketan** [comment]
Do you mean an alternative perpendicular linear pattern? Eg. 1st layer is all horizontal lines, then 2nd layer is all vertical lines?

**Comment by wirlybird** [comment]
Basic rectilinear pattern.  See pictures.
One layer is at a 45 to the X,Y axis, picture 1, then the next layer of the dense support is 90 degrees from the previous layer, picture 2.

In the example I have dense support set to 100% so it is solid.  Works best for me.

**Comment by tangketan** [comment]
I still can't see your pictures... But I think I've got your point. Basically you want the existing rectilinear pattern, but with perpendicular angles at neighboring layers, right?
![20230321-140721](https://user-images.githubusercontent.com/13730459/226530191-ea1efd39-04bb-4f4c-a9e2-f6e8d4af43f6.gif)

**Comment by wirlybird** [comment]
Yes, I think that is it.
My pictures are attachments to my email.

**Comment by wirlybird** [comment]
Here it is again.  Pictures in email.

 

Basic rectilinear pattern.  See pictures.
One layer is at a 45 to the X,Y axis, picture 1, then the next layer of the dense support is 90 degrees from the previous layer, picture 2.

In the example I have dense support set to 100% so it is solid.  Works best for me.

**Comment by wirlybird** [comment]
Here is a good example of needing to be able to set the “angle” of the infill pattern.

In this case, on two sides of the print, the dense infill is at 90 degrees to the layer above but on the other two sides, red arrow, the last layer of dense infill runs parallel to the layer above.  This can cause the layer to bond more aggressively to the support than when the support layer is not parallel to the layer above it.

**Comment by tangketan** [comment]
Email reply of github doesn't seem to work correctly. I didn't see any picture in any of your email replies.
Anyway, I've added the new interface pattern and pattern angle.

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65 

can probably be closed now.
