### ISSUE TITLE
Auto arrange ignores available area

### ISSUE THREAD

**Issue by pitops** [bambulab/BambuStudio#102]
Below is how i actually placed the tiles to print them

![Screenshot 2022-08-07 at 1 13 33 PM](https://user-images.githubusercontent.com/9624361/183286060-9efe4c36-6879-4ad9-afc3-8079b05d14b3.png)

However, if i hit 'auto arrange' it does this (played with almost all variations of settings)

![Screenshot 2022-08-07 at 1 14 09 PM](https://user-images.githubusercontent.com/9624361/183286076-45e53235-ad3b-4442-8b75-b538b829994a.png)

Result of above settings

![Screenshot 2022-08-07 at 1 14 28 PM](https://user-images.githubusercontent.com/9624361/183286083-676032d7-fddd-4ba1-b17b-df4e4f74d57a.png)

The setting that did work are only the following

![Screenshot 2022-08-07 at 1 15 13 PM](https://user-images.githubusercontent.com/9624361/183286108-2f84ee16-9427-4a7a-9723-132f47b8291e.png)

![Screenshot 2022-08-07 at 1 15 04 PM](https://user-images.githubusercontent.com/9624361/183286103-9ff2ea0a-135e-42ee-8a11-f76e1bcc2db3.png)

In my opinion it should be able to arrive in this kind of setup with any setting in there. There is plenty of space to arrange the objects

**Comment by tangketan** [comment]
Can't reproduce the bug on version 1.1.1.1 (the latest). Would you please try this version, and kindly provide the 3mf file if the bug is still there?

**Comment by Allram** [comment]
It's the same on 1.1.1.1, attached the .3mf file. It covers the "unprintable" area when using autoarrange.
![image](https://user-images.githubusercontent.com/5573149/184300884-43e91268-534a-4945-a0fe-9874731cdeb7.png)

.3mf file: https://www.transfernow.net/dl/20220812bcaSxHBO

**Comment by tangketan** [comment]
The file can't be downloaded. This issue should have been solved, I can't reproduce it with similar models on 1.1.1.4.
