### ISSUE TITLE
[BUG / 01.01.00.14 / Windows] Support filament disappear when Layer Height 0.2mm and Top Z distance is set to 0mm

### ISSUE THREAD

**Issue by thrutheframe** [bambulab/BambuStudio#103]
Layer height is set to 0.2mm and Top Z distance is set to 0mm for support filament, the support layer disappears. See images. 

It happens to all the layer heights when Top Z distance is set to zero. 

With 0.2mm Top Z distance:
![image](https://user-images.githubusercontent.com/68491566/183435009-9a2270f8-e46f-43e2-9cba-8a674b64a45f.png)

With 0.0mm Top Z distance:
![image](https://user-images.githubusercontent.com/68491566/183435270-5475d5a8-cdd7-416f-b491-2c704f84a658.png)

**Comment by thrutheframe** [comment]
@YifanWuBambu I also checked with the newer ver 1.1.1.1. Issue still persist. thanks

**Comment by YifanWuBambu** [comment]
@thrutheframe 
The color scheme is set to Filament if more thant one filament is used in selected plate.
Please change the color scheme to Line Type to see the support feature more clearly.
![image](https://user-images.githubusercontent.com/110661856/183688551-bfc9cae5-7cc8-4bf9-b683-b62dff191a97.png)
