### ISSUE TITLE
Broken dark/light theme when mac is woken up

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1030]
**Describe the bug**
I was working in BambuStudio at night and sleeped my Macbook. When I woke the mac up, the theme is broken and I dont see a way to fix it (other that restart the program).

EDIT: Found a way - if I go to macOS settings and set the the theme to dark -> automatic, BambuStudio applies correct theme.

**3mf File for This Bug**
--

**To Reproduce**
1. Set dark mode to automatic (in macOS)
2. Open it at night.
3. Sleep the mac.
4. Wake it "non-night" time.

**Expected behavior**
It can apply correct theme.

**Screenshots**
<img width="1624" alt="Snímek obrazovky 2023-01-08 v 9 10 17" src="https://user-images.githubusercontent.com/1620004/211186784-1879a855-ccc2-43e1-ae85-3295fd0c8f14.png">

**Desktop (please complete the following information):**
- OS: macOS
- Version: 13.1
- Bambu Studio v1.4.1.52

**Comment by SaltWei** [comment]
@bambu123 Please help to check and follow this ticket. Thanks!

**Comment by pdelvo** [comment]
Mine looked the same at some point on Windows. But I was not able to reproduce it so I dont know what caused it. Enabling dark mode in the settings fixed it though without restarting

**Comment by VACIndustries** [comment]
Also seeing this on Windows when I remote desktop into the machine.  You have to check the box again to "turn on" dark mode again.

**Comment by bambu123** [comment]
Some log was added for this issue. I'm sorry for not getting any more progress.

**Comment by SaltWei** [comment]
More logs have been added into v1.5.0 beta version to help to reproduce and analyse.
Please let us known when it reproduce again and we will reopen this issue.
