### ISSUE TITLE
Dark mode for Bambu Handy

### ISSUE THREAD

**Issue by FreeManFreeThinker** [bambulab/BambuStudio#1034]
The dark mode on Bambu Studio, in my opinion, was a game changer. Having this on mobile would also be really nice. The X1C UI has a dark mode and Bambu Studio has dark mode.

Im not a software engineer but I can't imagine this would be very difficult to implement! I could be wrong tho.

**Comment by SaltWei** [comment]
This is not slicer issue, and please turn to https://github.com/bambulab/Bambu-Handy to report issues related to app
