### ISSUE TITLE
Feature request: Remember setting from last print

### ISSUE THREAD

**Issue by jchu1988** [bambulab/BambuStudio#1035]
Some form of memory or option to remember last print settings so that I don't have constant untick the unneccessary ones.

![image](https://user-images.githubusercontent.com/66695017/211222657-442b5db4-069f-418f-aa8f-1a4b13f20d4a.png)

**Comment by psy0rz** [comment]
closed in 1.6.0

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.
