### ISSUE TITLE
Windows: move mouse to top right corner to close

### ISSUE THREAD

**Issue by f4bii98** [bambulab/BambuStudio#1039]
**Describe the bug**
Using the Windows BambuStudio it seems that the control buttons on the right top corner (in the programs title bar) dont reach all the way in the corner/to the top of the screen. Its annoying to for example to close the program with a quick mouse movement all the way in the right corner, but not beeing able to hit the X button. You need to directly hover about the X to be able to click the button.
This happens also for the Minimize/Maximize buttons.

**To Reproduce**
Just using the Bambulab Studio software, move mouse to the top richt window controls

**Expected behavior**
Close the program with a quick mouse movement all the way in the right corner, then the X button shoul be clickable. Also relevant for  Minimize/Maximize buttons.

**Screenshots**
![1](https://user-images.githubusercontent.com/65556423/211373207-aa03197e-72cf-41be-b4f5-65ef51da7be5.JPEG)
![2](https://user-images.githubusercontent.com/65556423/211373225-d3cfe38a-619e-4375-b7ce-23a9118da066.JPEG)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v01.04.01.52

**Comment by SaltWei** [comment]
v1.5.0 beta has been released
