### ISSUE TITLE
Set/get colour RGB values

### ISSUE THREAD

**Issue by rkarlsba** [bambulab/BambuStudio#1040]
When choosing a colour with the colour picker, you can get a very precise colour match, which is fine. Hoever, if I want to set two slots to the same custom colour, there's no way to get/set the RGB value of this so even though autochange is enablied, I can only guess it won't work, since the colours have different values. Could you add RGB values (#2040ff etc) to the colour selector in BambuSlicer, please?

**Comment by Benderrodrigu3z** [comment]
its there on Mac, just under a different tab
![Screen Shot 2023-01-09 at 12 08 08 PM](https://user-images.githubusercontent.com/48887257/211378124-2ee37dd2-f0e4-4fca-be0e-cdc90e76f6b8.png)

**Comment by rkarlsba** [comment]
ah - there it is! My fault. Please close this.
