### ISSUE TITLE
Separate x axis y axis offsets

### ISSUE THREAD

**Issue by Anothermbdusted** [bambulab/BambuStudio#1056]
Would like to see separate x axis and y axis offsets instead of them being tied together as sometimes your one axis might be.off but the other is perfect.

**Comment by YifanWuBambu** [comment]
@Anothermbdusted 
Do you mean the extruder x/y offset? It is seperated already.
![image](https://user-images.githubusercontent.com/110661856/222311325-b3259c95-43ea-4ac0-ba82-c88893077a8e.png)

If you mean the other one, please let me know. Thanks!

**Comment by Anothermbdusted** [comment]
no i mean as for the xy offset for a print. like if a printed part is say .4 off in the x axis and .9 off in the y axis you can adjust them separately accordingly. currently it has to be together no matter what but would is it even possible to separate them?

**Comment by YifanWuBambu** [comment]
@Anothermbdusted 
By offset, you mean shrinking or expanding in X/Y axis?
![image](https://user-images.githubusercontent.com/110661856/222312808-74e8cea2-1e50-4bd8-8f26-148fd4006849.png)

If it is still not the setting you mean, please help take a picture and mark it. Thanks!

**Comment by Anothermbdusted** [comment]
correct but separating the x and y so you can adjust them individually instead of together. so you have a 
x hole compensation
y hole compensation

x contour compensation
y contour compensation

not x-y hole
not x-y contour

**Comment by YifanWuBambu** [comment]
It is hard to do this for now. The clipper library used in the slicing process only support uniform offset.

**Comment by Anothermbdusted** [comment]
It was a thought and tyvm for your time I appreciate it a bunch..

**Comment by YifanWuBambu** [comment]
Thanks for your understanding : )
