### ISSUE TITLE
[Feature Request] Cut tool fix/enhancement

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1057]
This is to resubmit a request that was sent in earlier since I was told the request was too long and couldn't be processed. 

Currently when the user rotates the Cut tool plane by entering a value (such as 90 degrees) in the X axis, what BS considers the upper and lower parts are the opposite of what the user sees. When entering a value (such as 90 degrees) in the Y axis,  the two parts are side by side but the menu still asks the user to pick between the upper and the lower side.

Some suggestions: 1) label the two sides of the cut plane with a non-directional terms such as 'A' and 'B' and show the label to the user, or 2)  when user enters a positive X axis value, rotate the cut plane counterclockwise so that what the user sees is what the BS sees; when user enters a value in the Y axis, change the options to 'Left' and 'Right' parts, instead of the upper and lower parts, or 3) rotates the plate accordingly (such as via some formula) so user's view matches that of the BS.

**Comment by sickerin** [comment]
Just wanted to add other enhancement suggestions to the cut tool. Prusa Slicer 2.6.0 did a pretty good job on this. https://youtu.be/ZP2_Asz7xK8?t=570

**Comment by psy0rz** [comment]
closed in 1.6.0

**Comment by zhimin-zeng-bambulab** [comment]
The cut tool has been improved, you can have a try in the latest version
