### ISSUE TITLE
LAN only mode for P1P

### ISSUE THREAD

**Issue by stewartoallen** [bambulab/BambuStudio#1059]
**Is your feature request related to a problem? Please describe.**
How do I enable LAN only mode for P1P?

**Describe the solution you'd like**
An interface option for enable LAN only mode

**Describe alternatives you've considered**
I can find no other way to send files to the P1P over the local network

**Additional context**
clearly the printer is accessible over the network. but it seems via the cloud only. I would not have purchased this printer if I had known it only worked through the cloud.

<img width="1392" alt="Screen Shot 2023-01-11 at 11 14 54 PM" src="https://user-images.githubusercontent.com/554275/211977378-9628151e-d7e2-4dba-86c5-80a6c64156f6.png">
<img width="1392" alt="Screen Shot 2023-01-11 at 11 14 47 PM" src="https://user-images.githubusercontent.com/554275/211977380-81d5f6b6-f1d8-49ad-b520-fa742920ed4f.png">

**Comment by Pmant** [comment]
On the X1(C) you have to put it into LAN-Mode on the printer screen. Bambu Studio is then able to find the printer via LAN.

**Comment by stewartoallen** [comment]
this is on the P1P. there is no setting on the screen for this.

**Comment by Pmant** [comment]
Just wanted to point out that this feature seams to be missing on the P1P firmware not Bambu Studio. You might have more luck requesting this on the [firmware forum](https://forum.bambulab.com/c/bambu-lab-software/bambu-firmware/13) or the [feature request forum](https://forum.bambulab.com/c/bambu-lab-software/feature-requests/100). This repository is dedicated to the Bambu Studio Software.

**Comment by stewartoallen** [comment]
support asked me to post here

**Comment by SaltWei** [comment]
Lan mode will be added at printer firmware side in the future, but I can't promise the time for firmware.

**Comment by SaltWei** [comment]
Has transferred this request to firmware team.

**Comment by stewartoallen** [comment]
any way to track the request? any updates on this?

**Comment by suit** [comment]
Updates on this one yet?

**Comment by SaltWei** [comment]
The fiamware will come soon. Under internal test

**Comment by Schokobecher** [comment]
It's out.

**Comment by SimonP1P** [comment]
Dont work verry well... Now i can turn on Lan Only but my Computer can not connect to the P1P.

![Fail](https://user-images.githubusercontent.com/126918171/222832162-1c869aa8-b76e-41ec-bac2-03418fdd9853.png)

**Comment by stewartoallen** [comment]
Now I can "send" to the printer's SD card, but cannot see SD files remotely or start a print job from SD remotely. So not terribly useful.

**Comment by Schokobecher** [comment]
> Now I can "send" to the printer's SD card, but cannot see SD files remotely or start a print job from SD remotely. So not terribly useful.

That is how the current implementation works - no matter if P1P or X1. A future update to LAN mode might change that, but is unrelated to this issue

**Comment by Mycahya** [comment]
Over here on the Bambu labs forum they have shown how to use the FTP access on the X1C, so likely will work on P1P, may try later today: https://forum.bambulab.com/t/lan-only-mode/3123/15

**Comment by aw-jansen** [comment]
Any updates on this? And has anyone tried the ftp solution suggested by @Mycahya?
