### ISSUE TITLE
Perimeters end too early causing a large seam

### ISSUE THREAD

**Issue by npoulos** [bambulab/BambuStudio#1063]
It seems to me like there is a hard-coded “coasting” applied to each perimeter as the seams always leave such a huge gap between the start and end of a perimeter. 

I’ve messed with the wipe settings quite a lot to see if this gap can be wiped closed but it’s just not possible. 

When you look at the generated line in the viewer there’s a very noticeable gap where the seam is which is almost exactly what is reproduced in the print. 

Is it possible to look into if the line is actually closing a perimeter, or add a coast setting so this can be controlled manually. 

[testring-CURA-onelayer.txt](https://github.com/bambulab/BambuStudio/files/10400961/testring-CURA-onelayer.txt)
[testring-BL-onelayer.txt](https://github.com/bambulab/BambuStudio/files/10400963/testring-BL-onelayer.txt)

If you look at the two test files above, they are a slice of a 1 layer high, .4mm 1 line circle. I've annotated how Cura treats it vs BS.

It looks like BS ends the extrusion path nowhere near the start point of the line, whereas Cura ends up almost exactly where it started.

**Comment by npoulos** [comment]
If you paste both attached codes into https://nraynaud.github.io/webgcode/ - (removing my comments + the part after the end code in BS) you'll visually see a tiny black void at the end of the round path. I believe this is what's causing the gap.

I've attempted tests with turning off Arachne & without arcs as well (as there is arc code at the end of the BS code) and it still produces the same output.

**Comment by CCS86** [comment]
I am also noticing seam gaps. 

A user configurable setting for this (like Superslicer has), would be great:

![image](https://user-images.githubusercontent.com/12439543/212131912-9c09b9e6-c99c-4594-b5dc-d1ef52ebe94c.png)

**Comment by npoulos** [comment]
@CCS86 Yes! I did some searching and found that's from SuperSlicer. I found mentioned that there is a 15% gap added and extrapolated that it was put there back when LA/PA wasn't a real thing so the gap was to allow for ooze. This was likely added back in Slic3r days or whatever Prusa fork everyone started from.

I've also seen this mentioned on Prusa forums a few times and it's always swept under the rug with comments like "it's probably your retraction/wipe/LA/PA" or "it's just the visual renderer making sure you can see where the seam starts and ends" - It's 100% not. 

A fix to this would solve soooo many of the comments I see of people complaining about the seam or about the gaps they see. It's commented on so much I'm surprised no one has gone in to look yet.

**Comment by CCS86** [comment]
Absolutely. It's really a holdover from pre-PA / LA times. 

You can see that I run this zeroed out on my other printer. No bulging seams.

**Comment by npoulos** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/58903683/212222702-da4aac9f-de25-4e67-aefb-31b7e44e2cdd.png">

In libslic3r.h

**Comment by QingZhangBambu** [comment]
> 

i set this setting to 0, and compare it with the original setting. they look totally the same.
![perimeter end too early](https://user-images.githubusercontent.com/112676417/212646086-3ef0a78c-089e-446f-bdf0-edb653a97319.jpg)

**Comment by npoulos** [comment]
definitely not the same. Slow down your travel acceleration and travel speed. Acceleration to say 200 and speed to 180. Try with the 0.15 and without 0.15 at slower speeds and then you'll see how much of a difference that gap makes.

**Comment by QingZhangBambu** [comment]
the upper is the loop without clipping. (LOOP_CLIPPING_LENGTH_OVER_NOZZLE_DIAMETER=0.0)
the lower is original.

**Comment by QingZhangBambu** [comment]
We open the "Seam gap" parameter recently, you can edit it when you open the develop mode
![image](https://github.com/bambulab/BambuStudio/assets/112676417/0e82c77c-7cf7-4ef3-b191-c943a1b682f4)

**Comment by SaltWei** [comment]
Support seam gap setting on BambuStudio as well. Close this ticket
