### ISSUE TITLE
[FR] Layer Time Color Scheme Display

### ISSUE THREAD

**Issue by CCS86** [bambulab/BambuStudio#1064]
Please give us a "Layer Time", or better yet "Log Layer Time" to the preview display color schemes. Superslicer has this function and it is incredibly useful.

![image](https://user-images.githubusercontent.com/12439543/212131482-d7736269-7f95-4868-aa8b-44025ef312b3.png)

**Comment by SaltWei** [comment]
Will be added in next release which will come soon！

**Comment by CCS86** [comment]
Excellent!

Having both normal and logarithmic layer times would be fine with me. But, if you lean towards only one for simplicity, please make it the log version. Look at how much more telling it is:

![image](https://user-images.githubusercontent.com/12439543/212360588-d02b057c-ff66-4544-881b-406e9e5f2926.png)

**Comment by SaltWei** [comment]
> please make it the log version

OK

**Comment by lanewei120** [comment]
already in v1.5 on github
