### ISSUE TITLE
Filenames on Printer vs Bambu Studio

### ISSUE THREAD

**Issue by DarumasLegs** [bambulab/BambuStudio#1065]
When creating a project with multiple 3mf/stl's on a build plate, I typically save this project on my computer and name it some useful name (like "Motor mount parts"), then after slicing it and hitting the "send" button to send it to the printer, the dialog presented in Bambu Studio shows that the project will be sent to the printer using the name of the project that I saved on my computer. However, after sending the file, the resulting filename on the printer is usually different than the project name. Sometimes it displays the name of the first object on the build plate, but sometimes it also just picks a name of a previously printed project randomly.

Here is a screenshot of the Bambu Studio send dialog box:
![image](https://user-images.githubusercontent.com/19391027/212142941-af6392d5-f753-43db-b2c0-f49f6e7b01e7.png)

And here is a photo of the printer's LCD display showing the name of a previously printed file:
![IMG_3339](https://user-images.githubusercontent.com/19391027/212143253-ca244e60-a3f7-4a1b-8669-bd8cd5b7400a.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.0.1
 - Bambu Studio 1.4.1.52

**Comment by walterwongbbl** [comment]
Hi. In the send print dialog,  the displayed name is the file name. like  "PLACF_Gearbox_plate_1".
but printer's LCD displayed name is model name. 
if you want to change the model name.
![image](https://user-images.githubusercontent.com/120699126/215310055-4d3164c1-4a33-44f7-bc8f-8b6136e2a7c1.png)

**Comment by DarumasLegs** [comment]
Thank you. That isn’t very intuitive, by the way - why not show the model
name in the send print dialog, or have the printer’s LCD displayed name as
the filename? It think it just makes more sense if the send print dialogue
shows the same name as the printer’s LCD display.

**Comment by walterwongbbl** [comment]
Yes, good idel. we will synchronously display both sides as filename.

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
