### ISSUE TITLE
Auto arrange broken when print sequence "by object" selected

### ISSUE THREAD

**Issue by Jarred-Sutherland** [bambulab/BambuStudio#1066]
**Describe the bug**
Setting the Print sequence (Others -> Special mode -> Print Sequence) to "By Object" and using the auto arrange function causes the objects to be stacked on top of one another and placed off the build plate. 

**3mf File for This Bug**
This happens with any model I have used (10-20 so far). Download a 3mf or stl. 

**To Reproduce**
1. Go to Others "tab" -> print sequence, select "by layer"
2. Click on auto arrange, leave default values, click apply.
3. View build plate, the model will be off of the build plate.

**Expected behavior**
Models should be arranged on the build plate following the space needed for the print head to not collide with the printed objects.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Ventura 13.1
<img width="1764" alt="Screenshot 2023-01-12 at 5 26 34 PM" src="https://user-images.githubusercontent.com/122574442/212194399-794c62e6-5d9a-4819-91f5-6d6482bee4d1.png">
<img width="404" alt="Screenshot 2023-01-12 
<img width="1338" alt="Screenshot 2023-01-12 at 5 26 51 PM" src="https://user-images.githubusercontent.com/122574442/212194410-abcddd4b-f8dc-4396-a4fc-f0b2d8b0176d.png">
at 5 26 42 PM" src="https://user-images.githubusercontent.com/122574442/212194408-134af7fa-6db0-4bb6-9133-5081d11e2e7c.png">

**Comment by tangketan** [comment]
Did you forget attach the files?
I guess it's because your plate is Textured PEI and your filament is PLA. In previous versions we didn't allow printing PLA on Textured PEI plate because the bed temperature is higher than PLA's vitrifiction temperature. New versions have removed this logic.

**Comment by Jarred-Sutherland** [comment]
I did not forget to attach, this happens with any STL/3MF. Download a random STL/3MF from printables.com and you will see this behavior, the file doesn't matter.

I am running the latest version of Bambu Studio, I received my printer yesterday and downloaded yesterday. Checking for updates results in "this is the newest version"

**Comment by tangketan** [comment]
Yes, it's not right forbidding PLA on PEI plates. Previously we only have X1 series, which has closed chamber, and printing PLA on PEI plates can cause clog. Now we have P1P and we realize it's OK to print PLA on PEI, as long as the chamber is not closed. 
This issue has already been fixed. Try this version: https://github.com/bambulab/BambuStudio/releases/tag/v01.04.01.52

**Comment by Jarred-Sutherland** [comment]
> Yes, it's not right forbidding PLA on PEI plates. Previously we only have X1 series, which has closed chamber, and printing PLA on PEI plates can cause clog. Now we have P1P and we realize it's OK to print PLA on PEI, as long as the chamber is not closed.
> This issue has already been fixed. Try this version: https://github.com/bambulab/BambuStudio/releases/tag/v01.04.01.52

I can confirm the beta version is fixed, thank you very much!
