### ISSUE TITLE
Wall loops not changable

### ISSUE THREAD

**Issue by melfahn** [bambulab/BambuStudio#107]
No matter what I set Wall loops to it stays at three when sliced. I want to increase it for strength, I usually go up to six for that, but nothing changes in the visual when sliced or when printed. 
![1](https://user-images.githubusercontent.com/5402008/183552341-d5767f72-e112-45eb-92cb-467011e0c8d5.png)
![2](https://user-images.githubusercontent.com/5402008/183552342-567cf7de-debc-419e-b6a6-914b56a3a282.png)

**Comment by YifanWuBambu** [comment]
@melfahn 
I tested the case but cannot reproduce the issue.
![image](https://user-images.githubusercontent.com/110661856/183569997-98f32225-9056-4372-8ce0-07d0f2759a2a.png)


Please check whether it has object settings, which will override the global settings.
![image](https://user-images.githubusercontent.com/110661856/183570136-62f02b04-9792-4888-8114-57b7b864a87d.png)

If it still does not work, please share the 3mf. Thanks!

**Comment by melfahn** [comment]
thank you, that was the issue.  I'm going to share another my original project with you where I tried to  print part of the part with a 100% modifier.  in all of my tests trying to do this this leaves the outside layer a mess

**Comment by melfahn** [comment]
closing
