### ISSUE TITLE
Slicer hang, cannot be interrupted

### ISSUE THREAD

**Issue by ahoy-jon** [bambulab/BambuStudio#1070]
**Describe the bug**
When slicing, with advanced settings (like archimedian top) on certain STL, the slicer hang. 

**3mf File for This Bug**

**To Reproduce**
![image](https://user-images.githubusercontent.com/83247/212429238-d61f8eae-b429-4df7-88b1-55c1e7b4df7c.png)

When slicing this file https://www.thingiverse.com/thing:3477876/files.

**Expected behaviour**
* The slicer should not hang
* The slicer *should be able to be interrupted* (so we can go back).

**Screenshots**
![image](https://user-images.githubusercontent.com/83247/212429552-27eba20b-2512-452d-ae5a-0790a4979064.png)

**Desktop:**
 - OS: Mac
 - Version: 1.4.0.17

**Comment by SaltWei** [comment]
A basic library issue from clipper and prusa also can reproduce same issue.
![image](https://user-images.githubusercontent.com/110660407/212621040-1dd3cccc-9769-41ed-b68e-4b3814f27f79.png)
![image](https://user-images.githubusercontent.com/110660407/212621106-216e9b34-246f-47f6-a38d-5184d6f3c1d3.png)
Will investigate further.

**Comment by ahoy-jon** [comment]
Thanks a lot! if you could prioritize slicer interruption, that would be great. 

(I think we can understand the slicer cannot solve a certain path, if we could cancel the slicer, that would help in this case).

**Comment by SaltWei** [comment]
Fixed. And the fix will be included in next 1.6 version

**Comment by SaltWei** [comment]
[V1.6](https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65) has been published
