### ISSUE TITLE
Wipe doesn't happen if retract before wipe is set to 100%

### ISSUE THREAD

**Issue by npoulos** [bambulab/BambuStudio#1072]
**Describe the bug**
If you set the retract before wipe to 100% then the wipe move doesn't happen.

**To Reproduce**
set retract before wipe to 100%
set wipe to 2mm or something
slice
turn on wipe viewer. no wipe moves.

**Expected behavior**
should still move the wipe distance 

**Desktop (please complete the following information):**
MacOS latest

**Comment by SaltWei** [comment]
Has been fixed in 1.4.2.
