### ISSUE TITLE
Bambu Studio should remember last profile used when starting

### ISSUE THREAD

**Issue by Ruiaxe** [bambulab/BambuStudio#1073]
**Is your feature request related to a problem? Please describe.**
I'm using a custom profile and not the one provided with BambuStudio. Every time I close the software and start again my profile is not selected by default. This can let to errors in prints if I forget to make the change.

**Describe the solution you'd like**
The ability to remember the last profile used and select it by default.

**Describe alternatives you've considered**
As a workaround I have to remember to make the change manually. Not ideal.

**Additional context**
https://youtu.be/TZPLeQl-8Wo

**Comment by Manfredo1952** [comment]
I would setup Studio as desired and then store this setup with a name corresponding to what it reflects. It does not require any object to be placed there. You can open this stored project and Studio will come up with the stored settings, incl AMS filament settings.

**Comment by morikostyles** [comment]
I just submitted a very similar feature request related to filament profiles
https://github.com/bambulab/BambuStudio/issues/1113

**Comment by lanewei120** [comment]
it should be a bug not a feature
we will check it

**Comment by Ruiaxe** [comment]
This issue is fixed in the latest build of Bambu Studio, thanks.
