### ISSUE TITLE
Only one perimeter on first layer

### ISSUE THREAD

**Issue by defcrash** [bambulab/BambuStudio#1076]
The slicer already has the "Only one wall on top surfaces", but a feature that i miss that i use alot on Superslicer is the one wall on first layer, it leaves a way more aesthetical print when using multiple walls.

Could you please add it too? Its the only thing right now that makes me going back to superslicer.

Thanks in advance.

**Comment by QingZhangBambu** [comment]
we've added that feature to version 1.7.  you can update your software to get full functionality.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/100ea033-0333-4e31-8640-9f19ad0a1057)
