### ISSUE TITLE
Document Custom Variables and Commands

### ISSUE THREAD

**Issue by enewun** [bambulab/BambuStudio#1088]
When creating custom start/end/layer change g-code it would be nice if we could reference Bambu's custom commands and g-codes so that we can write our own code to better suit our needs.

For example, someone documented some of the custom commands here: https://forum.bambulab.com/t/bambu-lab-x1-specific-g-code/666

And how Prusa documents their variables here: https://help.prusa3d.com/article/list-of-placeholders_205643#custom-g-code-specific-placeholders

It would be nice if Bambu had these sort of documentation to so that users can be better supported in editing various g-code templates.

**Comment by QingZhangBambu** [comment]
https://wiki.bambulab.com/en/software/bambu-studio/placeholder-list 
you can get the information you want here
