### ISSUE TITLE
Density for Polyterra PLA profile does not match official datasheet 

### ISSUE THREAD

**Issue by joshkentYT** [bambulab/BambuStudio#1089]
The default "Polyterra PLA" profile has the density as 1.24 mg g/cm3. 

According to the Polyterra ["Technical Specifications" document](https://cdn.shopify.com/s/files/1/0548/7299/7945/files/PolyTerra_PLA_TDS_V5.1.pdf?v=1640828799) the density is 1.31 g/cm3

Is there a reason the density in the slicer is set to 1.24 instead of the officially provided number?

**Comment by SaltWei** [comment]
Just data mistake, will update.
