### ISSUE TITLE
Where filament calibration data are stored ? when calibration is required ?

### ISSUE THREAD

**Issue by DzzD** [bambulab/BambuStudio#1090]
AMS can handle 4 filaments, but only one filament is calibrated, I dont understand where the calibration result is stored ?

Let's say this scenario : 
- I print an object with first filament with filament calibration
- I print an object with second filament with filament calibration

Then, If I want to print again another object with first filament, do I need to redo a new calibration even if I did not remove it from the AMS between my prints ?

Does calibration data are store per slot ? per filament preset ? and what about multi-color printing, only one filament is calibrated ??

I am lost about this calibration stuff, I think it would require more information so people would know exacly when filament calibration have to be done. Best would be those data retained per slot until filament is removed from AMS. **Even better would be those calibration should be retained in filament preset.**

**Comment by jwise** [comment]
I have also wondered this.  The SoftFever branch has calibration tools to do pressure advance override per filament and to find the best flow rate; for my third-party filament, I dialed that one in carefully and I get somewhat better surface finish now.  I think it would be a really good enhancement to, at least, integrate the per-filament flow rate and pressure advance manual calibration tests into upstream -- and I suspect it would be particularly useful for P1P users that do not have LIDAR.

(For X1 users that do have LIDAR this could still be useful to have per-filament calibration stored in the slicer, with calibrations computed by the printer's lidar.  I could imagine printing a plate that is a more detailed version of the automatic flow calibration, and having that plate printed with multiple filaments at once, and then downloading the computed calibration from the printer for each filament and storing that to the filament profile.)
