### ISSUE TITLE
Numbers do not fit within settings boxes on Windows (10/11)

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#11]
Issue present on both 01.00.10.03 and 01.00.10.05

**Quality**, **Strength**, **Speed**, **Support**, and **Others** all show this issue. Non numeric settings appear to be OK.

![image](https://user-images.githubusercontent.com/63362209/179355313-f5d28368-d661-4400-9d4b-6062c55db004.png)

Tested on:
Windows 11 Pro
21H2
22000.675

other users have reported this issue on Windows 10 (unknown build)

This does not appear to be an issue on macOS.

**Comment by SoftFever** [comment]
I can confirm this issue happens on my Windows 11 machine as well.

**Comment by CptHungarian** [comment]
I don't have this problem and I also use Windows 11 (21H2).
I think the problem might be the custom font type the slicer uses (HarmonyOS Sans).
Just out of curiosity, what happens if you manually install the fonts from here: \resources\fonts?

**Comment by SoftFever** [comment]
> 

I can confirm that installing those fonts fixed this issue.
![image](https://user-images.githubusercontent.com/103989404/179364108-16e20ac6-5773-46a1-bba0-ad73be14e9a5.png)

**Comment by RobinWhitfield** [comment]
> I don't have this problem and I also use Windows 11 (21H2).

What was your build process? Anything out of the ordinary?

**Comment by CptHungarian** [comment]
> > I don't have this problem and I also use Windows 11 (21H2).
> 
> What was your build process? Anything out of the ordinary?
> 
> I'm guessing you didn't just manually install those fonts

I used the prebuilt version (1.00.10.03) that is available on the Discord server and I didn't have to install the fonts manually.

**Comment by RobinWhitfield** [comment]
This may be a build process issue.

Closing for now as the issue is not present on the pre-built pre-release installer version of 01.00.10.05

**Comment by RobinWhitfield** [comment]
Reopening this as although it's better with the pre-release build from the installer, it's clear it's still not quite right.

It looks OK until you highlight something, then it becomes clear that the numbers still don't quite fit

![image](https://user-images.githubusercontent.com/63362209/179417790-36f943a2-5f44-4350-9be2-6332fce97220.png)

**Comment by RobinWhitfield** [comment]
Just noting that this issue is still present in the release 01.01.00.13

**Comment by RobinWhitfield** [comment]
Can this non-default font just be changed?

Some users will not have the ability to install custom fonts or applications, so will always have the above font issues when running the "portable" non-install version of Bambu Studio.

The font does not seem sufficiently different to many other fonts available as default on Windows (and other operating systems), to be worth installing it.

**Comment by RobinWhitfield** [comment]
This issue was fixed in 01.01.01.01
