### ISSUE TITLE
spool slot issues.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#110]
When a print finishes and asks if you want to reprint, it does not print from the same spool, it defaults back to the first spool. It should use the same spool, or even better ask you what spool you would like to use so you could print multiples of different colors.

Along the same lines, the spool slot is not saved in the Gcode file when using the SD Card. At a minimum it should use the currently loaded slot.

**Comment by YifanWuBambu** [comment]
Thanks for the suggestion. We will refine the reprint logics in recent firmware release.

**Comment by randyre** [comment]
The reprint appears to work now.
