### ISSUE TITLE
Spiral Z-hop causes flexible blobs.. no way to switch to classic and fix them.

### ISSUE THREAD

**Issue by psiberfunk** [bambulab/BambuStudio#1100]
The spiral Z-hop the slicer implements is generally great... except for flexible filaments.. where it often makes nasty external artifacts (see attached picture).  This can be fixed by switching back to the "classic" z-hop (verified using the SoftFever Fork).  Bambu should fix this defect by allowing the user to make per-filament overrides to the Z-hop type, and set the default TPU profile to "Classic" behavior, so that everyone can have improved TPU prints.

![TPUZhopBlobs](https://user-images.githubusercontent.com/19777571/212970490-fee5112c-4328-4906-9a4d-ac3164e950a7.png)

**Comment by YifanWuBambu** [comment]
We will make the lift type an option and may be different for filament types.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/222115505-ffbb871f-f144-491d-bc40-6add61c05f99.png)
Available in v1.5.0 Public beta

**Comment by SaltWei** [comment]
> Bambu should fix this defect by allowing the user to make per-filament overrides to the Z-hop type, and set the default TPU profile to "Classic" behavior, so that everyone can have improved TPU prints.

Can be set in filament setting as well. But we recommand using "Slope" for TPU.

**Comment by psiberfunk** [comment]
@SaltWei  is slope's behavior described anywhere ?

**Comment by SaltWei** [comment]
> @SaltWei is slope's behavior described anywhere ?

Just make the spairl lift to be straight slope but with same angle.

**Comment by psiberfunk** [comment]
And why is this better than traditional for TPU?
