### ISSUE TITLE
Can't reprint from History to specific printer 

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#1104]
**Describe the bug**
Can't reprint from History to specific printer On a multiple printer setup.

**3mf File for This Bug**
Happens with any file. 

**To Reproduce**
Unsure fully how to reproduce. 

I open the Handy app on Android OS. One of 3 printers available. I click on History, a print job, then try to Reprint but I can't choose the available printer. Instead I get a busy printer listed and no option to choose any other. 

**Expected behavior**
An actual list of available printers to choose a reprint to. 

**Screenshots**

![Screenshot_20230117-204229_Bambu Handy](https://user-images.githubusercontent.com/10992914/213023100-4f87c3b8-5112-4002-b581-f9db50284da4.jpg)
![Screenshot_20230117-204257_Bambu Handy](https://user-images.githubusercontent.com/10992914/213023105-677e265e-18a0-49c6-b335-3836b6f6f1e3.jpg)

**Desktop (please complete the following information):**
 - OS: Android OS 
 - Version latest

**Comment by bolsoncerrado** [comment]
First screenshot shows alpha and beta printing, while gamma is available and idle.

Second screenshot shows i try to resend/reprint a file from History menu, but gamma is not listed, while beta is busy it is shown as available. 


Originally this print job was sent to beta thru the cloud. 
I was able to send it to alpha somehow, but unable to send it to gamma.

I tried to unlink and relink gamma to the cloud account but no change.

**Comment by SaltWei** [comment]
This is not slicer issue. Please trun to https://github.com/bambulab/Bambu-Handy to report app issue.

**Comment by bolsoncerrado** [comment]
Sorry you're right!

**Comment by bolsoncerrado** [comment]
Reported

**Comment by SaltWei** [comment]
> Reported

Thanks! I also had transmitted this tickets to app team internally.
