### ISSUE TITLE
Blank Confirmation Warning

### ISSUE THREAD

**Issue by CCS86** [bambulab/BambuStudio#1106]
Trying to initiate a print and am given this blank confirmation:

![image](https://user-images.githubusercontent.com/12439543/213234601-9221f000-efb5-4690-8849-1115c355e3d1.png)

**Comment by StoneLiBambulab** [comment]
Hi @CCS86 ，
This is a bug of studio, i fixed and maybe the warning msg  is "The nozzle hardness required by the filament is higher than the default nozzle hardness of the printer. Please replace the hardened nozzle or filament, otherwise, the nozzle will be attrited or damaged."


Thanks!

Stone Li

**Comment by CCS86** [comment]
Yikes, I wish I knew that because I completed that print

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
