### ISSUE TITLE
Chamber Fan Setting during Slice is not effeting the print

### ISSUE THREAD

**Issue by the0bone** [bambulab/BambuStudio#1110]
**Describe the bug**
I slice a model and set the value for the Chamber Fan to 0.
But it is not executed during the print. During startup process it is 70% and for the print it starts go to up to 100%.

**3mf File for This Bug**
Independent of any file.

**To Reproduce**
Edit Filament Settings -> cooling -> last item for additional_cooling_fan_spped

**Expected behavior**
Set at least the speed to the value that is entered After the startup procedure.

**Screenshots**
![1](https://user-images.githubusercontent.com/24297832/213412900-f0ed65a8-29d2-44ba-9490-1fe8aeb4bf8e.jpg)
![2](https://user-images.githubusercontent.com/24297832/213412932-3b53774c-f9dc-487d-b0d7-e4555ed0b849.jpg)
![3](https://user-images.githubusercontent.com/24297832/213412953-878e7bab-a186-41dc-a75d-a01e1de46edd.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Bambu Studio 1.4.1.52

**Comment by the0bone** [comment]
ok, it makes sense to call the fan below the Chamber Fan the Aux Fan...
![image](https://user-images.githubusercontent.com/24297832/213446996-954cfc2b-5e58-44b5-90cf-9ab8734421c7.png)

**Comment by LuxemGamer** [comment]
You have to go to Filament Start G-Code and edit the value S255 to something between 0-255.

It checks if the bed temperature is above 45C and sets the speed of the chamber fan that way.

The Aux fan and the part cooling fan can be set in the filament settings.

![image](https://user-images.githubusercontent.com/44650410/215336111-30dd5044-ca7f-4f8d-905c-5ca9372a2f2c.png)
