### ISSUE TITLE
Filament calibration dialog combobox is empty when using only external filament

### ISSUE THREAD

**Issue by asierralozano** [bambulab/BambuStudio#1112]
**Describe the bug**
I have a P1P printer WITHOUT the AMS unit. If I try to follow the steps decribed [here](https://wiki.bambulab.com/en/software/bambu-studio/extrusion-calibration), using the external filament is supported.

When I click on the `cali` button, the filament combobox is not listing any filament.

![NoFilament](https://user-images.githubusercontent.com/12841237/213441736-39d0848e-e385-4f24-8d3b-92b532cc1f39.JPG)

**3mf File for This Bug**

If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Follow the Calibration guide on the wiki

**Expected behavior**
Have filaments to choose

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BambuSlicer version: 1.4.2.13

**Comment by Noskowitch** [comment]
I have the same problem with this feature. I completely reinstalled bambu studio but it didn't help.

**Comment by asierralozano** [comment]
> I have the same problem with this feature. I completely reinstalled bambu studio but it didn't help.

Yep. I've tried reinstalling it, and even removing the local data folder, and same result, still no filament.

**Comment by StoneLiBambulab** [comment]
Hi @asierralozano ,
I  reproduce the issue. and found the nozzle value is convert to wrong value in French.

![screenshot-20230120-143453](https://user-images.githubusercontent.com/108911794/213632637-58d60dd8-9805-45bd-968b-da2e17502891.png)

I will change another way to do this convertion to avoid this issue.

Please change to language English to do extrusion calibration currently.

Thanks!

Stone Li

**Comment by StoneLiBambulab** [comment]
Hi,
    For the expression for 0.4 is "0,4" in french, so the convertion is failed. i will fixed it.

Thanks！

Stone Li

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
