### ISSUE TITLE
 涂红不需要生成支撑的地方依旧会生成支撑 

### ISSUE THREAD

**Issue by q1067972249** [bambulab/BambuStudio#1114]
涂红不需要生成支撑的地方依旧会生成支撑 
模型文件：[123.zip](https://github.com/bambulab/BambuStudio/files/10458502/123.zip)
操作视频：https://user-images.githubusercontent.com/39196539/213497109-47bbbab6-55b5-4e20-96db-3290dd828479.mp4
使用1.3.1.1的版本不会出现这个问题，最新的1.4.2和1.4都会出现这个问题

**Comment by MusangKingBambulab** [comment]
@q1067972249 您好. 我已经复现了你的问题,目前怀疑是圆圈涂抹小工具出了bug. 不介意的话,请您选择第三个,填充(fill)悬垂面涂抹工具,右键涂抹来屏蔽支撑. 圆圈涂抹bug我正在着手解决,谢谢您的反馈.

**Comment by MusangKingBambulab** [comment]
@q1067972249 该bug已修复，会跟随下个release版本发布。

**Comment by SaltWei** [comment]
1.5.0 Public beta has been released on github
