### ISSUE TITLE
Spelling Error In Error Dialog

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1116]
**Describe the bug**
The button to clear an error says "Clean". I assume it should say "Clear"

**3mf File for This Bug**
NA

**To Reproduce**
NA

**Expected behavior**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/96731892/213547071-e5eb6421-de3f-4b5a-b78e-129319223b80.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by lanewei120** [comment]
thanks for reporting this issue

we will fix it in next version

**Comment by lanewei120** [comment]
already in v1.5 just released
