### ISSUE TITLE
Wrong layer count on slice when printing object in vase mode

### ISSUE THREAD

**Issue by brianiup** [bambulab/BambuStudio#1119]
**Describe the bug**
When trying to print the STL which can be downloaded at https://www.printables.com/model/131488-spiral-vase-rose/files file name VaseRose_FullSize.stl upon slicing the slicer states there is 82893 layers, but the toast notification box on the bottom right of the slicer when generating G-Code only generates for 418 layers, which is the correct number (418).

![image](https://user-images.githubusercontent.com/73668489/213551077-cc576980-cea3-4b74-817b-c41638c76829.png)

**3mf File for This Bug**
3MF file is too large to upload to github even when zipped, please download the specified STL above

**To Reproduce**
1. Go to https://www.printables.com/model/131488-spiral-vase-rose/files and download the STL for VaseRose_FullSize.stl
2. Create a new project in Bambu Slicer
3. Add the VaseRose_FullSize.stl file to the 1st plate
4. Change to spiral vase mode
5. Click Yes to change the settings needed to enable spiral vase mode in the message box that opens up
6. Slice the file with a 0.4mm nozzle setting and the high temp plate 

**Expected behavior**
Upon slicking the model should have 418 total layers and for the slicer preview window to show 418 as the last top layer not 82893

**Screenshots**
![image](https://user-images.githubusercontent.com/73668489/213552030-0efbd1b9-3125-4877-bdab-45dc535ef95e.png)
Slicing shows the right number of layers 418

![image](https://user-images.githubusercontent.com/73668489/213552065-26101fe6-6519-4945-b1a0-a2367bc72cde.png)
Slice viewer shows 82893 layers which is way off

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 22H2
 - Bambu Studio v01.04.02.13

**Comment by QingZhangBambu** [comment]
> **Describe the bug** When trying to print the STL which can be downloaded at https://www.printables.com/model/131488-spiral-vase-rose/files file name VaseRose_FullSize.stl upon slicing the slicer states there is 82893 layers, but the toast notification box on the bottom right of the slicer when generating G-Code only generates for 418 layers, which is the correct number (418).
> 
> ![image](https://user-images.githubusercontent.com/73668489/213551077-cc576980-cea3-4b74-817b-c41638c76829.png)
> 
> **3mf File for This Bug** 3MF file is too large to upload to github even when zipped, please download the specified STL above
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to https://www.printables.com/model/131488-spiral-vase-rose/files and download the STL for VaseRose_FullSize.stl
> 2. Create a new project in Bambu Slicer
> 3. Add the VaseRose_FullSize.stl file to the 1st plate
> 4. Change to spiral vase mode
> 5. Click Yes to change the settings needed to enable spiral vase mode in the message box that opens up
> 6. Slice the file with a 0.4mm nozzle setting and the high temp plate
> 
> **Expected behavior** Upon slicking the model should have 418 total layers and for the slicer preview window to show 418 as the last top layer not 82893
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/73668489/213552030-0efbd1b9-3125-4877-bdab-45dc535ef95e.png) Slicing shows the right number of layers 418
> 
> ![image](https://user-images.githubusercontent.com/73668489/213552065-26101fe6-6519-4945-b1a0-a2367bc72cde.png) Slice viewer shows 82893 layers which is way off
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10 x64 22H2
> * Bambu Studio v01.04.02.13

Could you provide 3mf file? I use v01.04.02.13 version and the layer count is right .
![wrong layer](https://user-images.githubusercontent.com/112676417/213642519-5f0ca31d-be94-4a6e-a774-3706c945e2ac.png)

**Comment by QingZhangBambu** [comment]
we've fixed it. please will for next version.

**Comment by TheCableGuy99** [comment]
@QingZhangBambu I've just comes across this in non-vase made, could you confirm your fix covers non-vase mode?

**Comment by LiZ-Li-BBL** [comment]
We optimized the layers display, it shall be the same as it does in notification box. Please wait for next release.

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
