### ISSUE TITLE
Feature request: a ruler in the prepare tab

### ISSUE THREAD

**Issue by flames** [bambulab/BambuStudio#112]
A ruler measurement of distance between point A and point B snapped/clicked on the object, show distance line between those two points in mm or the unit set in config.
Especially useful, when scaling an object to fit a specific detail measure of that object.
There is a popup bottom-right, that shows overall size of the object, which is good enough with simple objects. With a ruler could be saved a lot of time (to avoid editing STL in a CAD software, just to scale it and remake the STL).
Thanks in advance

**Comment by sickerin** [comment]
I think overall, making it easier to write extensions. Similar to what Cura has, would open a lot of opportunities

**Comment by Hologos** [comment]
Can we get the ruler function once PrusaSlicer v2.6 get released? They did really amazing job.

**Comment by zhimin-zeng-bambulab** [comment]
The latest version(v01.09.03.50) already includes this feature.
