### ISSUE TITLE
Slim supports mid-air

### ISSUE THREAD

**Issue by OmiCron07** [bambulab/BambuStudio#1123]
v1.4.2.13

![image](https://user-images.githubusercontent.com/31325575/213614965-67625567-9eec-4098-afb9-cf03d441d11a.png)
[Xenomorph - Bug - Mid air.zip](https://github.com/bambulab/BambuStudio/files/10463070/Xenomorph.-.Bug.-.Mid.air.zip)

**Comment by tangketan** [comment]
Thanks for reporting the bug. We are working on it.

**Comment by SaltWei** [comment]
Please use v1.5.0 public beta to check
