### ISSUE TITLE
Feature Request: Axis labels and colors

### ISSUE THREAD

**Issue by sleeper-seth** [bambulab/BambuStudio#113]
Other slicers helpfully color code the X | Y | Z labels to make it immediately obvious what coordinate is represented in the model view.

Current Bambu:
![Screen Shot 2022-08-09 at 3 27 51 PM](https://user-images.githubusercontent.com/56604494/183772869-d955d310-35d9-49a2-bbda-34e821f1dc04.png)

Cura Example:
![Screen Shot 2022-08-09 at 3 29 55 PM](https://user-images.githubusercontent.com/56604494/183772986-f9949227-193c-4add-b5d3-6fcd7c3a1cec.png)

Another small quality of life upgrade would be to label the X,Y,Z axis indicator when in the Move state (or maybe always?)

![Screen Shot 2022-08-09 at 3 23 42 PM](https://user-images.githubusercontent.com/56604494/183772416-6db1e07b-513a-4049-96a1-ab43fee145be.png)

**Comment by YifanWuBambu** [comment]
Thanks for the suggestion. We will optimize it in recent release.

**Comment by YifanWuBambu** [comment]
It is in v1.2 version.

**Comment by aa755** [comment]
the same could be done for the mirror tool:
![image](https://github.com/user-attachments/assets/5dd884ff-d3eb-43a6-9f68-0659f53d056d)
