### ISSUE TITLE
[Feature Request] Please add the option to select "not connected" on the sparse infill.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1131]
I am trying to print a set of the Head(amame) headphone cones and need the ability to select that the infill in not connected to perimeters. In Super Slicer this option is under "print settings" tab and under the "infill" selection on the "Sparse" properties.

**Comment by littleferris** [comment]
I think the setting you are referring to is infill anchor, which indeed is not in bambustudio but is the setting needing to adjust for the headamame.

**Comment by SaltWei** [comment]
> but is the setting needing to adjust for the headamame.

@QingZhangBambu Please evaluate whether this setting is necessary

**Comment by millpreet** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/136 same as this issue posted in orca slicer. any work around to add it into profile without putting in gui temporarily @QingZhangBambu ? I tried this in the process JSON, 
![image](https://user-images.githubusercontent.com/16529173/232631764-d9bb2c02-17d8-4109-b8a7-53fa2568d219.png)
no luck.

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/ed658574-6790-4379-83a4-33c2402dd9cb)
Add back in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53
