### ISSUE TITLE
Bambu Studio sends GCode only for 75% to Cloud - nothing is printed.

### ISSUE THREAD

**Issue by theogott** [bambulab/BambuStudio#1133]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Goto:
https://bambulab.com/en/my/support/tickets/US230120922001

Watch the video. I have uploaded it there because it is too large for Github.
But you need to see the recorded video, it shows the problem.

**Expected behavior**
Would be that the Object would be printed.

Instead the NEW updated Bambu Studio 1.4.2.13 takes the GCode and sends here only 75% of it to the Cloud.
The switches to the Camera view and shows THE OLD PROJECT FROM BEFORE.

Also got this:
![image](https://user-images.githubusercontent.com/68653812/213816335-fdfb1309-6726-4053-b879-c96e3680643a.png)

PLEASE Watch the video, to see the problem. Its not so easy to explain.
https://bambulab.com/en/my/support/tickets/US230120922001

OS is: Windows 11

[Better Vented Parametric Funnel.zip](https://github.com/bambulab/BambuStudio/files/10470627/Better.Vented.Parametric.Funnel.zip)

**Comment by kartoffelfighter** [comment]
Seems to be a problem with the bambu servers - i fixed it by changing the printer to LAN only mode, reconnect to Bambu Studio with the shown password and it works like a charm again.

**Comment by theogott** [comment]
Work today, so Ticket can be CLOSED.

**Comment by lanewei120** [comment]
yes, it is a cloud issue

sorry for the inconvenience
