### ISSUE TITLE
Frozen AMS info 1.4.2

### ISSUE THREAD

**Issue by fi0** [bambulab/BambuStudio#1135]
OS: macOS 
Bambu Studio Version: 1.4.2

Bambu studio is frozen when it tries to retrieve AMS info from printers on LAN mode.
Reverting back to 1.4.1 doesnt have this issue.

**Comment by bambu123** [comment]
Can you help to supply a picture to show what was happening?

**Comment by fi0** [comment]
<img width="432" alt="Screen Shot 2023-01-29 at 10 49 17 AM" src="https://user-images.githubusercontent.com/25412990/215301694-0692ad63-fdf6-4b09-a422-38f59d2d8565.png">

**Comment by bambu123** [comment]
We use TSL to connect the printer to the LAN network from version 1.4.2.
If your printer hasn't updated, connecting with TSL will fail by timeout, and Studio will downgrade to the non-TSL method.
The duration before the timeout is a bit long. (about 10 seconds)

Suggest updating the printer or not using LAN-Only mode.

**Comment by bambu123** [comment]
@fi0 Please confirm: 
1、Is the printer in LAN-Only mode？
2、Does the connecting always wait (more than 20 seconds)?

**Comment by fi0** [comment]
1. Yes
2. Yes. And the connection fails on 1.4.2. But it works on 1.4.1. I've tried clearing the settings.

**Comment by fi0** [comment]
So, it seems that the fallback didnt work.

**Comment by fi0** [comment]
The printer firmware is 01.03.00.00

**Comment by bambu123** [comment]
Please send us the logs which can be found in the configuration folder.
The configuration folder can be opened by clicking the menu "Help > Configuration Folder'.

**Comment by bambu123** [comment]
@fi0 Please update the printer to use the TLS secure connection in the LAN-Only mode.
