### ISSUE TITLE
Printing Generic ABS

### ISSUE THREAD

**Issue by SWXTools** [bambulab/BambuStudio#1136]
**Describe the bug**
If i try to print ABS the Bambu Studio want to select the Engineering Plate, on the Spring Steel plate ABS is written on the Cool Plate Side.

**Comment by MadMax389** [comment]
The recommendation changed. The cool plate is no longer recommended for ABS even though it is printed on the cool plate sticker. Perhaps new batches of cool plate stickers will not indicate ABS.

**Comment by YifanWuBambu** [comment]
@SWXTools 
Yes. Just as @MadMax389 said, we changed the recommended plate type for ABS.
If you still want to print ABS on the cool plate, you can change the bed temperature to a non-zero value.
![Uploading image.png…]()
