### ISSUE TITLE
Does flow calibration and Lidar really make something ?

### ISSUE THREAD

**Issue by DzzD** [bambulab/BambuStudio#1139]
I had some few cases where calibration lines was not sticking and was not properly lined and the calibration did not popup any warning and continue printing without any issue... So I wonder if it really change something.

It would be nice to have a visual information of the result of calibration somewhere on the GUI ?

**Comment by Benderrodrigu3z** [comment]
In my opinion its a full gimmick that the Lidar code is even doing anything, I removed the house from the plate and it just kept scanning and then went and printed, no errors, plate was a Bambu High Temp sheet. The code has not been turned on properly to calibrate.

**Comment by DzzD** [comment]
> I am Convinced that the Lidar code is a full gimmick

So I am ;)

**Comment by RobinWhitfield** [comment]
If it fails to scan correctly it fails silently and sets the K value to 0.02. With some reading of MQTT data you can get the value that the LiDAR cal produced, and I can assure you that it does indeed change as you'd expect.

Now should it silently fail to calibrate? I'm not sure about that one. It certainly makes it harder to determine whether or not it's worked.

**Comment by DzzD** [comment]
Ok, that's probably why I got 0.2 default value when I use SoftFeaver fork for the first time. 

At least a popup warning, not stopping the print but asking for, would be a nice addition.

**Comment by DzzD** [comment]
(Sorry closed by error)

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/b782d77f-1e8c-45e8-baf7-bc8b73f62edd)
X1C can use lader to do pa calibration, and the result can be seen when finished
