### ISSUE TITLE
P1p flow calibration does not work with German language. If you switch to English it works.

### ISSUE THREAD

**Issue by n4mb3r0n3** [bambulab/BambuStudio#1142]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by theogott** [comment]
You mean we should just switch printer to english and all works fine?
Maybe i should also do that.

**Comment by lanewei120** [comment]
thanks for reporting this issue

we have fixed it in local , and it will be ready in next version

currently please switch to English for calibration if needed,
and switch back, then input the k value got from calibration in English

Sorry for the inconvenience

**Comment by holidaay** [comment]
Same problem with swedish. Works with english but not in swedish.

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
