### ISSUE TITLE
Filament changes on single layers occurs globally across all plates instead of just that plate

### ISSUE THREAD

**Issue by sisuwest** [bambulab/BambuStudio#1145]
**Is your feature request related to a problem? Please describe.**
yes. changing filament by right clicking on the slider and choosing a new filament on a layer happens to all models on all plates globally. 

**Describe the solution you'd like**
This single layer filament change should only affect the highlighted plate and not all plates. 

**Describe alternatives you've considered**
I can paint a model to have multiple colors, but sometimes single layer color changes are faster and cheaper. 

**Additional context**
Here is a video showing what I'm talking about to another user. https://youtu.be/97ZZ5lvRf0U

**Comment by lanewei120** [comment]
already in v1.5 just released, please have a try
