### ISSUE TITLE
P1P (01.01.01.00) ignores seam placement and sets to random after slicing and sending to printer

### ISSUE THREAD

**Issue by sisuwest** [bambulab/BambuStudio#1147]
**Describe the bug**
Regardless of the seam placement I set in the slicer (aligned) the printer ignores that changes it to random. It doesn't show that in the slicer preview, but upon printing multiple zits are shown across a random seam. 

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
![IMG_1726](https://user-images.githubusercontent.com/65087400/213899742-0af779d3-3ae0-4057-82b0-3be5cc43f2fd.jpg)
![IMG_1728](https://user-images.githubusercontent.com/65087400/213899743-1b500c71-e2da-4e3c-a37f-393e97113859.jpg)

 - OS: macOS 
 - Version 13.1

**Comment by RobinWhitfield** [comment]
It is impossible for the printer to change the location of the seam, so if there is indeed an issue with the seam selection being ignored, it's a slicer issue.

**Comment by QingZhangBambu** [comment]
could you provide the 3mf file? I'm trying to reproduce that.

**Comment by QingZhangBambu** [comment]
Some guys reproduced that, and we found that the calibration did not work well, PA and flow ratio were not right. 
This issue be close for no responsed
