### ISSUE TITLE
Option to send to X1 or SD card in X1

### ISSUE THREAD

**Issue by VACIndustries** [bambulab/BambuStudio#115]
While the printer is busy, or even if it is not; there should be an option to send the sliced file to the printer or SD card instead of only the two options to export or immediately print.

**Comment by Allram** [comment]
That would be a great feature!

**Comment by dereknheiley** [comment]
agreed, i use this all the time in klipper! to queue up the next couple of prints i want to slice after the current job is done

**Comment by dereknheiley** [comment]
this seems related, or duplicates https://github.com/bambulab/BambuStudio/issues/61

**Comment by YifanWuBambu** [comment]
It is a good idea. We have added it to your plan list.

**Comment by Sir-Gavin** [comment]
this would be great

**Comment by jl-p** [comment]
Agree. or just like my ultimaker queue it and let me press a button when i removed the current parts and start printing again.

And an option to print all buildplates in one project. with the same button to continue when the parts are removed.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
