### ISSUE TITLE
X-Y hole/contour compensation ignored for painted objects

### ISSUE THREAD

**Issue by rehmi** [bambulab/BambuStudio#1151]
1. Unzip and open [hole compensation test.3mf.zip](https://github.com/bambulab/BambuStudio/files/10475228/hole.compensation.test.3mf.zip). Switch to the Prepare tab and zoom into the center of the build plate, where you should find three instances of the test object ([hole compensation test 5x5mm, 2mm diam.stl.zip](https://github.com/bambulab/BambuStudio/files/10475306/hole.compensation.test.5x5mm.2mm.diam.stl.zip)) as seen below:
![Screenshot 2023-01-22 at 11 06 26 AM](https://user-images.githubusercontent.com/90555/213935005-07538043-103e-4103-9e73-52a8382e09da.png)

2. Switch to the Preview tab or press the Slice button to view the sliced results:
![Screenshot 2023-01-22 at 11 07 18 AM](https://user-images.githubusercontent.com/90555/213935773-125a2641-4b09-4270-ab96-1edb8d6705d8.png)

The expected behavior would be for the toolpath of the painted, compensated object to resemble the unpainted, compensated object; instead, it resembles the unpainted, uncompensated object.

Tested with BambuStudio version 1.4.2.13 on macOS Ventura 13.1 (arm64).

**Comment by SaltWei** [comment]
Thank you very much. We will have a check.

**Comment by zhimin-zeng-bambulab** [comment]
The XY size compensation cannot be combined with multi-material painting, we will add a warning to prompt the user.
It is the same for Prusa.

**Comment by rehmi** [comment]
Thank you for looking into this and planning to add a warning. Before closing this issue, could you say a bit more about the blocker? Presumably this is a limitation imposed by the current slicer architecture that you learned by exploring the matter in some depth; it would benefit future generations if you could share your discoveries before moving on to other matters.

**Comment by zhimin-zeng-bambulab** [comment]
The current software framework does not support it.
In short, the coloring information is recorded on the object before size compensation, and it cannot be found after size compensation.
