### ISSUE TITLE
Using Negative Objects and Letters in Bambu-Studio should be also exported as STL

### ISSUE THREAD

**Issue by theogott** [bambulab/BambuStudio#1156]
**Is your feature request related to a problem? Please describe.**
Assume i make an Object like the one attached.
I can make nice modifications in bambu-Studio, for example i can use Writings or negative Objects.
BUT the result can not be exported as STL-File.
If I do EXPORT STL i will just get the original Object without the modifications.

**Describe the solution you'd like**
The solution would be to EXPORT WHAT IS SELECTED.
If the Original Object is selected then EXPORT ONLY THE OBJECT. If the Object PLUS the modification Object (negative Object) ist BOTH selected then Export the result Object.

**Describe alternatives you've considered**
Generally Exporting the result Object would be better then exporting the Original Object.

**Additional context**

[Offener Trichter.zip](https://github.com/bambulab/BambuStudio/files/10479033/Offener.Trichter.zip)
![Sample Bambu](https://user-images.githubusercontent.com/68653812/214025194-c51c614f-88b4-43b2-91fd-c147d6392862.jpg)

**Comment by lanewei120** [comment]
it is indeed a mesh boolean which is not supported in current design
as it is not an easy feature
we add it into our long plan

**Comment by theogott** [comment]
Means, you can print it as GCODE but not export as STL?
Is there no way to convert the GCODE to STL?

**Comment by lanewei120** [comment]
the negative object logic is processed in 2D space，we can compute the combined area by using polygon intersecting
and then into gcode
however we can not convert them into stl as 3d triangles

to achieve this, we need to integrate the mesh boolean functions which is doing in the 3D space

**Comment by theogott** [comment]
Ok, do as you wish, means. Put it on long term list and close the case for now.

**Comment by albertnev** [comment]
Is there any update on this, or an estimated time to fix it? It's still happening with the latest versions, and right now there is no workaround (exporting, saving as 3mf and converting to STL with external tools... everything ends up with the same results).

**Comment by lanewei120** [comment]
we have added mesh boolean functions in previous versions
you can have a try in two ways:
![image](https://github.com/bambulab/BambuStudio/assets/106916061/0690ac28-1afb-4ed7-9c45-a91507e6c95d)

or

![image](https://github.com/bambulab/BambuStudio/assets/106916061/06972f59-35b6-4cbf-a5cb-8ad493a0dc8a)

**Comment by lanewei120** [comment]
this should satisfy this requirement now

**Comment by theogott** [comment]
Thanks!

 

Von: Lane.Wei ***@***.***> 
Gesendet: Freitag, 1. September 2023 13:39
An: bambulab/BambuStudio ***@***.***>
Cc: Theo Gottwald ***@***.***>; Author ***@***.***>
Betreff: Re: [bambulab/BambuStudio] Using Negative Objects and Letters in Bambu-Studio should be also exported as STL (Issue #1156)

 

we have added mesh boolean functions in previous versions
you can have a try in two ways:
 <https://user-images.githubusercontent.com/106916061/265009900-0690ac28-1afb-4ed7-9c45-a91507e6c95d.png> 

or

 <https://user-images.githubusercontent.com/106916061/265010024-06972f59-35b6-4cbf-a5cb-8ad493a0dc8a.png>

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/4650c6ce-ea4b-4c9d-af78-5975caab3d25)
Already supported when export stl with negative part
