### ISSUE TITLE
Flush into object should be restricted when using Support-W

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#1161]
**Describe the bug**
Flush into material is selected and when using support materials this causes a structurally weak or failed part.

**To Reproduce**
1. Print object with support-w enabled as support material or support interface.
2. Complete print and print will have bad structural integrity or problems with layer adhesion.

**Expected behavior**
Multi material prints should either not allow flush in infill when support-w is used or not allow support-w to flush while allowing other materials to flush.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version ALL

**Comment by Benderrodrigu3z** [comment]
How do you still have Support W ? that's been out of stock in the store forever

**Comment by randyre** [comment]
> How do you still have Support W ? that's been out of stock in the store forever
@Benderrodrigu3z 
One came with X1C from Kickstarter and bought another when they came back in stock, and then use it **VERY** sparingly, mainly for things that either need a near perfect surface when supports are removed, or where it's really hard to remove the support. :)

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta
