### ISSUE TITLE
Build plate cannot be send to the printer (Exception:std:bad_alloc)

### ISSUE THREAD

**Issue by ekatus** [bambulab/BambuStudio#1162]
**Describe the bug**
Error upon sending build plate to the P1P printer - 

**To Reproduce**
1. slice model
2. print plate
3. confirm pop up and hit send

**Expected behavior**
send 3mf to the cloud and initiate print

**Screenshots**
![image](https://user-images.githubusercontent.com/32845922/214240296-12a2df36-9c79-49d9-bcb6-1bf239f03f38.png)
![image](https://user-images.githubusercontent.com/32845922/214240354-82fb1ff0-3234-4dfb-a8c6-3e16517c0f23.png)

**Desktop (please complete the following information):**
 - Ubuntu 22.04 on Intel Nuc 8 i5 16GB

**Comment by lanewei120** [comment]
> **Describe the bug** Error upon sending build plate to the P1P printer -
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. slice model
> 2. print plate
> 3. confirm pop up and hit send
> 4. See error
> 
> **Expected behavior** send 3mf to the cloud and initiate print
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/32845922/214240296-12a2df36-9c79-49d9-bcb6-1bf239f03f38.png) ![image](https://user-images.githubusercontent.com/32845922/214240354-82fb1ff0-3234-4dfb-a8c6-3e16517c0f23.png)
> 
> **Desktop (please complete the following information):**
> 
> * Ubuntu 22.04 on Intel Nuc 8 i5 16GB

@ekatus 

thanks for reporting this  issue

it should be the same with https://github.com/bambulab/BambuStudio/issues/760#issuecomment-1397374901
could you check the details in that issue for the solution?

**Comment by lanewei120** [comment]
already in v1.5 just released
