### ISSUE TITLE
Spiral Vase Mode Unhandle Exception Client Crash

### ISSUE THREAD

**Issue by brbubba** [bambulab/BambuStudio#1165]
**Describe the bug**
No matter what model I use the Windows client 1.4.2.13 will crash when doing the following:
Open any model
Disable Prime Tower option under OTHERS menu
Enable "Spiral Vase" mode under OTHERS menu
Client crashes with following messages:
"Unhandled unknown exception; terminating the application"
"BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost:any_cast"

**3mf File for This Bug**
Applies to all/any model.

**To Reproduce**
1. Open any model
2. Disable Prime Tower option under OTHERS menu
3. Enable Spiral Vase mode under OTHERS menu
4. "Unhandled unknown exception; terminating the application"
"BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost:any_cast"

**Expected behavior**
Client should not crash or throw up a warning.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Comment by xcschultzx** [comment]
I get the same trying to enable vase mode

![image](https://user-images.githubusercontent.com/27920005/214634518-f28704ef-8f2c-4f46-9da2-8d71e3ca8396.png)

**Comment by lanewei120** [comment]
thanks very much for reporting this issue

we have fixed it locally, and the codes have been submitted to the branch v1.4.2

it will be ready in next release

**Comment by Highlander-bdj** [comment]
To work around this, I downloaded an older version, ran it, created and saved a printer profile with base mode. Then I removed and opened the new version. I can select the profile and it does not crash.

**Comment by lanewei120** [comment]
> To work around this, I downloaded an older version, ran it, created and saved a printer profile with base mode. Then I removed and opened the new version. I can select the profile and it does not crash.

another method to work around:
always turn on wipe tower before turn on spiral mode

currently it only happens when wipe tower off

**Comment by lanewei120** [comment]
already in v1.5 just released
