### ISSUE TITLE
Video Quality in Bambu Studio

### ISSUE THREAD

**Issue by CCS86** [bambulab/BambuStudio#1168]
I posted this issue on the user forum 2 weeks ago and have not gotten a response:

https://forum.bambulab.com/t/video-quality-bambu-studio-vs-bambu-handy/3135

Basically the video in Bambu Studio is far too dark and has very choppy motion. More details, photos and videos in that thread.

**Comment by bambu123** [comment]
We use your system's direct-show video decoder, which may be different from others.
Some Media software may also provide other decoders.

**Comment by CCS86** [comment]
> We use your system's direct-show video decoder, which may be different from others. Some Media software may also provide other decoders.


What is the solution then? There is a very big difference between BS and BH.

I even tried putting black vinyl along the back wall to help the camera auto exposure brighten the image. Still, Bambu Studio is too dark:

![image](https://user-images.githubusercontent.com/12439543/215533802-09a944b2-20e3-49ac-8ba2-480d364f45a6.png)

**Comment by CCS86** [comment]
Once it starts printing I can't see much at all:

![image](https://user-images.githubusercontent.com/12439543/215614800-f171b595-e098-4024-9878-877311c62b3f.png)

**Comment by bambu123** [comment]
@CCS86 
If you like, please contact me with discord, my account is chunmao.guo#3806.
I need to debug something with your help.

**Comment by bambu123** [comment]
After some debugging with the help of @CCS86, we got the same result with the same URL.
The mobile phone may have a video effect filter supplied by the system media player, making the video sharper and brighter.
Currently, we have no custom video effects in the studio or handy.
So to fix this issue, I suggest you guys give your printers a brighter environment.

**Comment by CCS86** [comment]
I'm not sure how this is complete. 

The light was already on inside the printer. The glass is tinted, so environmental light has almost no impact.

I really think you guys should consider finding a way to increase brightness or gamma in BS.

Plus, there is the issue of video stuttering in BS, which is not present in BH. These are both ongoing issues.

**Comment by mdeeter** [comment]
I agree that this is an issue.    The printer camera really needs a manual exposure setting.

**Comment by CCS86** [comment]
Even with additional interior lights added, exposure control just hammers it dark. 

Here is the view from outside the printer:

![image](https://github.com/bambulab/BambuStudio/assets/12439543/70614e0a-0d55-4481-84fa-66798c4b935a)


And here is what the camera sees in the same moment:

![image](https://github.com/bambulab/BambuStudio/assets/12439543/bbe61a4f-46a9-4766-be20-9b813b41423d)


Histogram of the first image:

![image](https://github.com/bambulab/BambuStudio/assets/12439543/f55a92da-da53-4e20-8ed7-9dd1f824acaa)



And the second one:

![image](https://github.com/bambulab/BambuStudio/assets/12439543/339e36c6-08eb-4903-89f4-de6fdb3c8bff)



Even with a black build plate and the interior walls blacked out, trying to get auto-exposure to push the brightness up:

![image](https://github.com/bambulab/BambuStudio/assets/12439543/6f19abdf-efdd-4c65-b472-54ade844ac4c)
