### ISSUE TITLE
Use STL or build plate + Project name in 3mf filename when exporting or printing

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/BambuStudio#117]
Currently if you have multiple build plates in a project, they all get sent to the printer as the same file name in the UI on the printer. Same problem if you "Export sliced file". You have to manually rename the file instead of having the default be STL or build plate + project name
![filename_slicer_prepare](https://user-images.githubusercontent.com/3382160/184414654-fe5910c0-ec74-41fe-a5a3-47d65ac514d5.jpg)
![filename_printer_view](https://user-images.githubusercontent.com/3382160/184414658-b2a67a9e-1fa0-4a6a-a777-b621a374bc67.jpg)
.

**Comment by YifanWuBambu** [comment]
We will optimize that in recent release.

**Comment by dereknheiley** [comment]
Here are a few more.examples from slice files ok n the SD card, at least there is a preview picture 😄 
![1BD595DC-F15B-4EE6-8652-36772DFC4BBB](https://user-images.githubusercontent.com/3382160/184794536-123b2e05-c378-4406-9287-c7aae4388b58.jpeg)
![20717D4E-D7F6-49BC-9BD3-03780C6F6E5E](https://user-images.githubusercontent.com/3382160/184794545-efdbc3bc-068e-47e5-a65c-b6ca9a55312a.jpeg)

**Comment by YifanWuBambu** [comment]
Thanks for the examples.

**Comment by YifanWuBambu** [comment]
It is implemented in v1.2.
