### ISSUE TITLE
[*Feature Request*] Ability to change Jerk value

### ISSUE THREAD

**Issue by SeaStorm00** [bambulab/BambuStudio#1175]
Add ability to change Jerk value.  Currently the Jery value is locked at 9 which is good for high speed applications but for slow detailed prints a higher value is desired.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/215265452-d52b41e6-54f1-474e-8d70-66eec16c5a0d.png)
Will make these options editable.

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta
