### ISSUE TITLE
Make sidebar movable or wider or dynamic.

### ISSUE THREAD

**Issue by M-Stege** [bambulab/BambuStudio#1176]
**Describe the bug**
In the German language version you can't select the Compare presets

**To Reproduce**
1. In Prederences -->Language -->Deutsch
2. Restart BS
3.  you can see the icon only minimally

**Expected behavior**
I would have expected that you can change the width of the sidebar or that it is wide enough by default or that it adapts dynamically.
In the German language version you can't select the Compare presets(only with a lot of luck).

**Screenshots**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/84290446/214520997-4c16aef1-97f2-40fe-b29b-d473b109b72e.png">
![image](https://user-images.githubusercontent.com/84290446/214521126-6bea22be-729a-4425-a11c-77c368e29a34.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - BS Version 1.4.2.13

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
