### ISSUE TITLE
Slicer ignores first color in first layer with dual color prints.

### ISSUE THREAD

**Issue by n4mb3r0n3** [bambulab/BambuStudio#1182]
I did design a creditcard with some text on it. 

The text is printed fine but the slicer ignored that there is text and filled the whole first layer with the second color. 

It did print and ignore the first color and did fill the second color completely. 

The second color should not overprint the first color. 

Slicer version : 1.4.2.13
Windows 11 

![image](https://user-images.githubusercontent.com/61233309/214844656-22cded80-c312-4918-b6f8-537d08aebe54.jpeg)

**Comment by SaltWei** [comment]
Thank you for reporting issue！
Could you share 3MF file as zip to us to debug？

**Comment by n4mb3r0n3** [comment]
> Thank you for reporting issue！
> 
> Could you share 3MF file as zip to us to debug？

Yes I will do in a few hours when I am back at the computer.

**Comment by n4mb3r0n3** [comment]
@SaltWei 
please remove ".zip" from file 
3mf is not supported in github

[example.3mf.zip](https://github.com/bambulab/BambuStudio/files/10527644/example.3mf.zip)

**Comment by zhimin-zeng-bambulab** [comment]
You could try the following way to avoid this problem.
Select all objects -> right click -> choose "Assemble" -> click "Slice" , then view the slice results.

**Comment by n4mb3r0n3** [comment]
I'll try today.

But seems to be a bug if the slicer ignores the printed parts and prints over it.

**Comment by zhimin-zeng-bambulab** [comment]
At present, we only have a warning prompt for overlapping traces,  but it still can be sliced ​​and printed.
We will optimize the overlapping detection of traces in the future.

**Comment by zhimin-zeng-bambulab** [comment]
We have planned this feature, you can track it through issue #1264.
