### ISSUE TITLE
[Issue] Wrong color layer

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1195]
nullsee Ticket No: US230126703001
The model has been colored with the fill method, adjusting the "smart fill angle".
When slicing a colored model, some layers appear with the wrong color (some lines at different layers).

**Comment by SaltWei** [comment]
>nullsee Ticket No: US230126703001

Thank you very much!
Please follow the format of github issue. Don't know what this is.
Could you also share 3MF for easy debugging?

**Comment by SaltWei** [comment]
Close for no response for a long time.
Please let us known if it still exists on v1.5.0 public beta.
