### ISSUE TITLE
Allow change of filament color printing order, especially on the first layer.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#1199]
Allow change of filament color printing order, especially on the first layer.

**Describe the solution you'd like**
Allow the user to define which color prints first. 

**Describe alternatives you've considered**
None.

I currently have a two-color print and the lighter color prints first, but as the second color prints, the nozzle barely touches the light color and it then streaks onto the darker color. Especially silk colors are very prone to this.

![2023-01-28](https://user-images.githubusercontent.com/60475095/215274757-b68998f6-4f69-4d8a-98ea-1fbed3daedc3.png)

**Comment by randyre** [comment]
Any way to fool the software to print one object before the other? this project is on hold until I can print the darker color first.

**Comment by javawizard** [comment]
This would be a fantastic addition. I'm printing some parts that are 98% water soluble support on the first layer and 2% actual part and the actual part filament prints first, and the small features in said part don't turn out nearly as well as I imagine they would if they were surrounded by support filament when they were printed.

**Comment by mike-serinus** [comment]
I second this issue. It is a major problem, particularly with narrow objects such as text on the first layer. If the text is not printed first, the surrounding color tends to spread into the text zone, making the text thinner than it should be. Compensating with line width does not help

**Comment by darrenph1** [comment]
+1 We should be able to choose the color order of the layer. The definitely effects the outcome of the layer.

**Comment by zhimin-zeng-bambulab** [comment]
It has been added in  1.7.4(https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52), you can have a try.
