### ISSUE TITLE
Filament Flushing Volume menu button is not clear.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#120]
The icon to load the filament flushing volume menu is really unclear.
![image](https://user-images.githubusercontent.com/63362209/184451645-c5871f5d-ea1f-4eae-afb7-3ebe0dd3fab1.png)

Firstly it's not clear that it's a button so many people miss that it even exists

Secondly it's unclear what the icon represents.

I'm not totally convinced that this is the right way to go design wise, but here's a free suggestion:

![image](https://user-images.githubusercontent.com/63362209/184453459-be0ce43d-d2cb-4ba3-8041-18cd6dfdea46.png)

**Comment by YifanWuBambu** [comment]
Thanks. We will optimize this in the next release.

**Comment by RobinWhitfield** [comment]
They went super simple. I like it

![image](https://user-images.githubusercontent.com/63362209/189423592-c9ae41a0-3504-4c77-87e6-9455fa76ed72.png)
