### ISSUE TITLE
Master Branch missing commit from v1.4.2

### ISSUE THREAD

**Issue by candreacchio** [bambulab/BambuStudio#1206]
Master branch is missing this commit from branch v1.4.2
https://github.com/bambulab/BambuStudio/commit/40ee2698e7129de2a0262e827bcacb70eaa5b12e

Thanks!

**Comment by jwise** [comment]
In general, I'm a little curious what the relationship is between master and 1.4.2 branches :) I have a few more things I want to look at to get Linux on par with Windows, and I wonder which branch I should be working from.

**Comment by lanewei120** [comment]
yes, currently please use v1.4.2

we will sync the codes later

**Comment by lanewei120** [comment]
already synced codes to master
master has the newest codes now
