### ISSUE TITLE
Exporting STL makes negative parts solid

### ISSUE THREAD

**Issue by chuckkay** [bambulab/BambuStudio#1216]
If you edit a model by adding a negative part, and the export it to an STL the negative part becomes solid.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/216489122-b0312141-bf26-473e-a964-ebc12bcf0b9b.png)
Do you mean that negetive part is missing after exporting and reloading？

**Comment by chuckkay** [comment]
No im mean it makes it solid and if the original negative was half in half sticking out from the part, then the exported stl no longer has the correct shape its fused with actual part and negative part as one solid.

**Comment by zhimin-zeng-bambulab** [comment]
Could you provide your 3mf file and your software version, it will help us to solve this problem.

**Comment by chuckkay** [comment]
see attached files
i deleted the version i was talking about, with crazy results where the exported stl file had the long negative cylinder part as a solid sticking out the bottom.  now i just have what [SaltWei](https://github.com/SaltWei) gave as an example above [last week](https://github.com/bambulab/BambuStudio/issues/1216#issuecomment-1414588006)

now its just a solid but doesn't stick out.
[Export 3mf models with negative parts to stl.zip](https://github.com/bambulab/BambuStudio/files/10693809/Export.3mf.models.with.negative.parts.to.stl.zip)
this is probably Probably normal. and just need to use cad instead of bambu studio to modify parts

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://user-images.githubusercontent.com/120697589/217737884-b95d4259-fe1a-4571-97a3-08b633c616b7.png)

I tried to reproduce the problem that you discrible, but I found that the negative part was not exported, it was not exported as a solid like you said.
Could you reproduce your problem with the version 1.4.2.13?

Currently the software does not support the export of negative parts, we plan to support it in the future.

**Comment by chuckkay** [comment]
Yes thats what im getting now, i can live with it, luckily I haven’t noticed the other problem lately, and i am pleased to hear Bambu will be working on a fix regarding preserving negative parts.

**Comment by zhimin-zeng-bambulab** [comment]
Thank you so much for providing this issue!

**Comment by zhimin-zeng-bambulab** [comment]
use  #1265 to track this problem.

**Comment by theogott** [comment]
Somehow we may have found the same problem, see here:
[https://github.com/bambulab/BambuStudio/issues/1156](https://github.com/bambulab/BambuStudio/issues/1156)

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/user-attachments/assets/cbca8a96-7d28-457b-b2d0-dcac3eb8dc02)
You can execute meshboolean and then export to stl.
