### ISSUE TITLE
Add a gcode section executed for each layers

### ISSUE THREAD

**Issue by DzzD** [bambulab/BambuStudio#1217]
For now, we can add gcode manually for a layer after slicing, it would be great and very usefull to be able to set a gcode that would be added/executed for each layer. 

Could help to make calibration towers : temps/PA,speed as well as many other usefull stuffs.

By using conditional operators based on layer height or index, it would then be possible to make very usefull little programs.

**Comment by DzzD** [comment]
ho ! great is that new or do I missed this ?

**Comment by EukaDesigns** [comment]
I'm not sure if it was always available or not. 

Where would you prefer it to be? I thought this worked out nicely since you can save multiple sets of printer settings in case you wanted to save multiple g-code settings.

**Comment by DzzD** [comment]
I would prefer to be able to define it by part or plate, but it seems that the very latest release of Bambustudio update enable to make it per plate (at least it is on the release notes, did not tried it yet)

**Comment by SaltWei** [comment]
> at least it is on the release notes

No. The release note says supporting different custom gcode inserted in preview page for different plate, rather than machine preset

**Comment by DzzD** [comment]
![image](https://user-images.githubusercontent.com/12198339/224284717-100db44f-c7a6-48ac-b180-c1b9bfed0560.png)

**Comment by FlowForm** [comment]
Yes I'm also missing the "SpeedTower" scripts from Cura....

Could anyone make a script/code for changing speed at different layers, so I could insert it in the "machine gcode" section? (10mm/s increments for each 10 layer would be very useful)
