### ISSUE TITLE
zoom with the many to the cam on bambu handy

### ISSUE THREAD

**Issue by Looker1981** [bambulab/BambuStudio#1219]
in my opinion if you make sure that you can zoom with the many to the cam on bambu handy it's a spectacular thing.  in addition, in my opinion you must also make sure that from bambu handy you can choose and print the files that are inside internal and inside sd

**Comment by SaltWei** [comment]
This is not slicer issue.

For bambu Handy issue, please move to https://github.com/bambulab/Bambu-Handy

**Comment by Looker1981** [comment]
I understand but in any case I ask this to ensure that it is updated if you can send this communication to improve

**Comment by SaltWei** [comment]
Have transferred this ticket to APP team internally

**Comment by Looker1981** [comment]
thanks anyway I hope you make the Italian version we are a group of about 500 members of an Italian channel that we have the bambulab please make a language also in Italian of the slicer and printer

**Comment by SaltWei** [comment]
Italian is in our plan（studio） now.

**Comment by Looker1981** [comment]
I don’t see Italian language … where can I find it Italian?

**Comment by SaltWei** [comment]
Just plan of studio

**Comment by Looker1981** [comment]
when did you update?

**Comment by SaltWei** [comment]
No exact time. We are finding translator.
Will update as soon as possible when ready

**Comment by Looker1981** [comment]
please tell him to do it in italian also for the printer and bambu handy
