### ISSUE TITLE
Add "GRID" option to Support Interface Pattern.

### ISSUE THREAD

**Issue by SeaStorm00** [bambulab/BambuStudio#1221]
I would like to be able to change the Support interface pattern to "GRID."

I believe this will provide a cleaner finished surface on the model after support is removed.

**Comment by tangketan** [comment]
Is this what you want? 
![image](https://user-images.githubusercontent.com/13730459/226314351-bc26c020-c757-467d-ae60-a7d27aca522a.png)

**Comment by SeaStorm00** [comment]
Yes!! That is what we need.

**Comment by tangketan** [comment]
OK then. I'll try to add this pattern in the next release.

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.
