### ISSUE TITLE
Different color first-layer text fails

### ISSUE THREAD

**Issue by holla2040** [bambulab/BambuStudio#1222]
Added a single layer text in a different color to the base layer. Text prints first slowly, filament changed to print remaining first layer. Second color doesn't print slowing, even though its one the first later. Second color doesn't adhere to bed.

**3mf File for This Bug**
Attached

**To Reproduce**
Open attached 3MF file. Print in 2 colors.

**Expected behavior**
When the second color starts printing, it never adheres to the plate.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 19045.2486
- Bambu Studio 1.4.2.13

![image](https://user-images.githubusercontent.com/1024542/215687583-b15a300a-a5df-4bb8-b60a-644e7debabc1.png)
![image](https://user-images.githubusercontent.com/1024542/215687689-c07fde66-f2b2-4122-bb74-c7b6a905f6c7.png)

[snifferTop.zip](https://github.com/bambulab/BambuStudio/files/10543601/snifferTop.zip)

**Comment by morgano86** [comment]
I just loaded your file and I note your numbers aren't flush with the first layer. They are projecting outwards - at least according to the slicer. Therefore the first layer printed is the numbers and the 2nd layer is on top of the numbers, therefore, floating in the air. I think you need to adjust the model so the numbers are flush.

**Comment by holla2040** [comment]
That makes sense, I tried to get them flush. Apparently, I need to work on that. I'll start first thing this morning. If I'm successful, I'll close this issue.
Thanks for your fast reply.

**Comment by holla2040** [comment]
@morgano86 You were correct, I got it working after tweaking the z positions. Thanks.

**Comment by holla2040** [comment]
![20230131_101430](https://user-images.githubusercontent.com/1024542/215834641-3519c8bf-8322-4cb8-8e78-cf87972ce05c.jpg)
