### ISSUE TITLE
Ams wrong filament types

### ISSUE THREAD

**Issue by chuckkay** [bambulab/BambuStudio#1226]
i have 4 AMS Units 16 filaments, all labeled correctly on printer control screen.

when i sync on bambu studio, everything shows up correctly, i save 3mf and even save profile.  When i reopen Bambu studio, the filament colors are correct but filament types are wrong.

![7BFA006C-B7AE-4470-9DE6-D328A3C6C3AE](https://user-images.githubusercontent.com/10617746/215829920-39dcde30-df2a-4a11-bcf5-f42528d46e25.jpeg)
![BF9BDD7D-8CD7-4F0C-9419-BEC3B6D1DE9C](https://user-images.githubusercontent.com/10617746/215829925-b0716da4-7fce-46da-990e-8f7b3b38af28.jpeg)

Latest versions of Windows, Bambu studio and firmware

**Comment by bambu123** [comment]
Surprise! It behaves like this every time.
Does the old version have the same issue in you memory?

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta

**Comment by TheCableGuy99** [comment]
Doesn't work across multiple printers.

**Comment by bambu123** [comment]
Some filaments are not compatible with something printers.
Please provide details for the new issue.

**Comment by TheCableGuy99** [comment]
I believe it's the same issue as I raised here and is supposed to be sorted. I've updated my own thread... if it is the same issue maybe these should be collated into a single issue? https://github.com/bambulab/BambuStudio/issues/1122#issuecomment-1451095316
