### ISSUE TITLE
We Need from cura the "slicing tolerance> exclusive" Option. Its neccesary for printing screws and threads

### ISSUE THREAD

**Issue by Bangwa88** [bambulab/BambuStudio#1227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SaltWei** [comment]
@QingZhangBambu Please evaluate this feature request and see whether it is necessary

**Comment by QingZhangBambu** [comment]
I think the function is similiar to xy-hole-compensation & xy-contour-compensation.
![image](https://user-images.githubusercontent.com/112676417/233539668-0c4f0093-8f04-4a1d-865b-c651bdc83130.png)
