### ISSUE TITLE
Some color painted areas not correct color after slicing

### ISSUE THREAD

**Issue by CameronBigger** [bambulab/BambuStudio#1233]
**Describe the bug**
In a model rocket model, all of the fins tips were 'painted' black, mainly using the fill tool. As you can see in the 'prepare' shots, all four wing tips are showing black. However, after slicing, the preview shows some of the wingtips are partially white, which is incorrect. Have repainted the area using the fill tool as well as the 'gap' tool but subsequent slices still coming out partially white.

**3mf File for This Bug**
Attached.

**To Reproduce**
1. Open the attached 3MF file featuring manually painted colors
2. Notice the color of all four wingtips should be solid black
3. Slice the model (I used 15% infill, grid and 0.20 layer height)

**Expected behavior**
All four wingtips would be solid black

**Actual results**
Some wingtips are partially white which is unexpected. Re-painted them several times but they always remain partially white after slicing.

**Screenshots**
Attached

**Desktop (please complete the following information):**
Mac OS Ventura (13.1)
Bambu Studio 1.4.2.13

[MercuryRedstone-bug report.3mf.zip](https://github.com/bambulab/BambuStudio/files/10561888/MercuryRedstone-bug.report.3mf.zip)
![Bambu Studio Slicing Bug with Color Painting](https://user-images.githubusercontent.com/4701465/216173943-84ccd01a-1666-4beb-8c24-de699ea60d15.jpg)

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/216488019-b9dd7b0c-22aa-4cd6-9140-50c4aadb49c0.png)
That's seam preview

**Comment by Lesani** [comment]
@CameronBigger Seams are where the printer starts and stops its loop with the black filament, this will not be white when printed

**Comment by CameronBigger** [comment]
Thanks @Lesani. Gotcha. I almost wish the seam would be rendered in a very different color (maybe blue or orange or something in my model) than the filaments in use to make it more obvious this is the seam. 

I know about seams and usually put them on the "back" of objects like this rocket. But in this case, I didn't notice it. You are right: as soon as turned off seam visualization, I could see the wing tips were solid black.

Closing this as user misunderstanding :-)
