### ISSUE TITLE
Missing object in 0.4 0.6 0.8 nozzle but OK in 0.2

### ISSUE THREAD

**Issue by Fyr42** [bambulab/BambuStudio#1236]
Dear Bambulab,

Some straight fine objects are missing after slicing and in printed part (only printed with 0.4 nozzle) at different nozzle size : 04, 0.6 and 0.8 but visible at 0.2

The general link for the models are : https://www.thingiverse.com/thing:3546935

The file concerned is Duplo_track__switch_BETA.stl (zipped to attach it)
[Duplo_track__switch_BETA.stl.zip](https://github.com/bambulab/BambuStudio/files/10566349/Duplo_track__switch_BETA.stl.zip)

In Prepare section the tracks for the train line visible 
<img width="1728" alt="Screenshot 2023-02-02 at 08 41 39" src="https://user-images.githubusercontent.com/119723794/216262228-204c5116-78df-49f5-8b41-750f53ef64fd.png">

When sliced for a 0.4 nozzle (iden for 0.6 and 0.8 nozzle) these tracks vanish but some remain.
<img width="1728" alt="Screenshot 2023-02-02 at 08 45 36" src="https://user-images.githubusercontent.com/119723794/216263323-d4c7f04b-b8d0-4be5-ac7f-6c61f9d9228b.png">

and absent in printed part 
![IMG_3781](https://user-images.githubusercontent.com/119723794/216263700-7763d948-c988-47c8-b61b-fa99cd150861.jpeg)

But in 0.2 nozzle it's fine.
<img width="1728" alt="Screenshot 2023-02-02 at 08 52 25" src="https://user-images.githubusercontent.com/119723794/216264091-4df680e7-e870-474f-8fb3-f2cc5ab54683.png">

Please help kids to play with their printed Duplo Train

Kind Tchoo tchoo

**Comment by SaltWei** [comment]
Not a bug, this is thin wall. 
Enable thin wall.
![image](https://user-images.githubusercontent.com/110660407/216486685-c81242f8-611f-4fdd-9d00-3c7f0a61ee9d.png)
Or use arachne.
![image](https://user-images.githubusercontent.com/110660407/216486797-b29e6934-8ed8-425d-89df-8fdebbe720b8.png)
