### ISSUE TITLE
Only one wall on top surfaces setting is ignored

### ISSUE THREAD

**Issue by espressomaster** [bambulab/BambuStudio#124]
Seems where walls are thin, only one perimeter is generated regardless of this setting:

![image](https://user-images.githubusercontent.com/111176984/184477972-ad1c7624-22a2-49d0-aba4-8cdfba0cc8f0.png)

whereas I would expect this top surface to essentially be only perimeter (3 wall loops selected), like the layer below:

![image](https://user-images.githubusercontent.com/111176984/184478004-426f4c22-879b-47a3-bae5-9a6397a3ca8d.png)

**Comment by SaltWei** [comment]
The topmost surface is always one wall as designed currently for better surface quality.
And it can't be influenced by the option "only_one_wall_top".

**Comment by espressomaster** [comment]
> The topmost surface is always one wall as designed currently for better surface quality and no influence on strength.
> And it can't be controlled by the option "only_one_wall_top".

**Comment by SaltWei** [comment]
Accept, will make the topmost surface also be controlled by the option "only_one_wall_top"
