### ISSUE TITLE
Incomplete Bridging (wrong angle)

### ISSUE THREAD

**Issue by Lesani** [bambulab/BambuStudio#1240]
**Describe the bug**
Bridge angle is the same as other solid layers, instead of 90° to the bridge
Corners are not bridged correctly because they have no 2nd side to connect to yet, (or only a single strand of perimeter)

![image](https://user-images.githubusercontent.com/5182104/216553517-de50a83e-ec8f-40bb-a587-99203edde67c.png)

Prusaslicer for this reason (and maybe others) switches to 90° instead of 45° for the first bridge layer

![image](https://user-images.githubusercontent.com/5182104/216552956-3c1c9e7e-7225-44fe-8119-9e5ef58ac37c.png)

**3mf File for This Bug**
[file.zip](https://github.com/bambulab/BambuStudio/files/10577157/file.zip)

**To Reproduce**
1. Slice

**Expected behavior**
complete bridge layer

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/5182104/216553764-01f18214-b571-4191-be4a-62ef8f8c3143.png)

**Comment by SaltWei** [comment]
Will be included in next release

**Comment by SaltWei** [comment]
Included in 1.5.0 Public beta
