### ISSUE TITLE
Feature request - HEX Color in Colorpicker

### ISSUE THREAD

**Issue by djalexz** [bambulab/BambuStudio#1241]
HEX Color in Colorpicker

It would be great if you could also enter the HEX value of the color when creating a custom filament.
Currently I help myself by manually editing the JSON file of the profile and entering the HEX value of the color there.

![image](https://user-images.githubusercontent.com/11389551/216576703-9dfc82be-1fac-4500-8cd6-2eaac87311f4.png)

**Comment by CameronBigger** [comment]
FYI: Maybe this is lacking in the Windows version, but there is an equivalent to this already available on the Mac version of Bambu Studio through the RGB Picker option.

<img width="231" alt="Mac Bambu Studio RGB Picker" src="https://user-images.githubusercontent.com/4701465/216697309-e5084a7f-2105-42c5-b953-5fd7f0011dc5.png">

**Comment by djalexz** [comment]
Hi, Thank you for your answer.
I have this Problem with the Windows Version of Bambu Studio.
It would be great if the Windows Version has the Same color picker.

**Comment by djalexz** [comment]
+1

**Comment by CameronBigger** [comment]
+1. @iandouglas if nobody already has, perhaps you should post this "custom color picker on printer touchscreen" as a separate suggestion?

**Comment by walterwongbbl** [comment]
Hi.
We will provide some preset color choices.
and no longer allow users to edit custom colors.

**Comment by Merlwynd** [comment]
No, do not take away the ability for users to edit custom colors! The original request was simply to allow users to enter a HEX value in the Windows version of Bambu.....

**Comment by walterwongbbl** [comment]
> 不，不要剥夺用户编辑自定义颜色的能力！最初的请求只是允许用户在Windows版本的Bambu中输入十六进制值。

Sorry. my description is incomplete
we just don't support users editing custom colors for filaments with in AMS

**Comment by walterwongbbl** [comment]
Please update the latest studio version.
we support user-defined color selectors

**Comment by nihilisticzebra** [comment]
months later still no fix common bambu
