### ISSUE TITLE
Seam improvement like in the Softfiver fork

### ISSUE THREAD

**Issue by Itebayo** [bambulab/BambuStudio#1247]
Seams are looking pretty bad even with the right pressure advance and flow value, especially on round objects.
In the Softfiver fork there are several options to improve the seam which help quite a lot.
I really think this should get more attention as more and more people are not satisfied with the seam quality and this is mostly a software issue.

The seam alignment on round object is also very poor.
For commercial use bad looking seams are quite the issue.

**Comment by SaltWei** [comment]
> In the Softfiver fork there are several options to improve the seam which help quite a lot.

Could you share what options can help? Thank you very much!

**Comment by Itebayo** [comment]
Sure!
The option "Seam gap" seems to help quite a bit, if you reduce it form 15% to 1%.
Going all the way to 0% introduces weird travel moves all over the place, which seems to be a bug.

Additionally "wipe on loops" can be turned on and reducing wipe speed to 10% also makes a difference.

All of this was tested with PLA and the Softfiver version 1.4.4 with the bambulab X1.

I have owend quite a few printers and used a lot of slicer software, the seams with the Cura slicer were always the best, so maybe look into what they are doing too. I think the addition of a "coasting feature" would reduce the bulge at the end of a travel move/seam even more.

**Comment by CCS86** [comment]
> Sure! The option "Seam gap" seems to help quite a bit, if you reduce it form 15% to 1%. Going all the way to 0% introduces weird travel moves all over the place, which seems to be a bug.
> 
> Additionally "wipe on loops" can be turned on and reducing wipe speed to 10% also makes a difference.
> 
> All of this was tested with PLA and the Softfiver version 1.4.4 with the bambulab X1.
> 
> I have owend quite a few printers and used a lot of slicer software, the seams with the Cura slicer were always the best, so maybe look into what they are doing too. I think the addition of a "coasting feature" would reduce the bulge at the end of a travel move/seam even more.



Seam gap is the equivalent of coasting.

**Comment by Itebayo** [comment]
From my understanding it is not.
Coasting stops the extrusion near the end of the travel path.
Seam gap leaves a travel gap between the start and endpoint of the seam.

**Comment by CCS86** [comment]
> From my understanding it is not. Coasting stops the extrusion near the end of the travel path. Seam gap leaves a travel gap between the start and endpoint of the seam.

In SuperSlicer the extrusion is stopped, but a travel move continues to the original end point (ie coasting). Here is a 300% seam gap:

![image](https://user-images.githubusercontent.com/12439543/217956725-e5e78ec6-c45f-43bb-b001-ca82cc76e9ab.png)

**Comment by Itebayo** [comment]
Ok looks like my understanding was wrong, is it the same for cura?

**Comment by CCS86** [comment]
Yes, Cura stops extrusion but completes the path as well.

**Comment by npoulos** [comment]
Coasting in Cura can be controlled and turned off. Seam gap cannot be turned off unless using Orca Slicer.

Given proper PA and LA tuning, the seam gap (and coasting) cause a much bigger gap than would be produced without it.

Please incorporate the seam settings that Orca slicer has. It is the main reason I am not using BambuStudio.

Turning off "Wipe on loops" in orca slicer also greatly improved seams.

All my tests are with a 0.2 nozzle which show great improvement!

**Comment by npoulos** [comment]
Also to add - In Cura, you can control coasting amount, speed and minimum extrusion before it coasts. The intent of coasting originally was to control pressure in the nozzle to stop over extrusion at the end of a loop.

The seam gap in BS is a hard-coded 5% gap. It uses the travel speed once it stops extruding and has no rule around when to, and not to add the gap in. It was originally added in Slic3r as a hard-coded coast move but since LA and PA exists it no longer is relevant and causes more issues.

The seam gap also clashes with the wipe move if turned on.

**Comment by QingZhangBambu** [comment]
@Itebayo if you don't mind, could provide the stl and 3mf you used? I am testing these features. And has no improvement.

**Comment by QingZhangBambu** [comment]
And about "wipe on loop", We've moved that travel path from the 1.4 version.

**Comment by QingZhangBambu** [comment]
About "wipe on loop", the path of travel has been moved since version 1.4.

**Comment by QingZhangBambu** [comment]
https://github.com/bambulab/BambuStudio/commit/a7266286579a4a81f83f8a3fd47524892c4fe645

**Comment by QingZhangBambu** [comment]
There are results of 0.4 nozzle and 0.2 nozzle, sliced by Orca, Printed by Bambu X1C. @Itebayo 
![飞书20230424-091158](https://user-images.githubusercontent.com/112676417/233880079-f249382b-1302-4b87-a348-1cd8558fc8e4.jpg)
![飞书20230423-155148](https://user-images.githubusercontent.com/112676417/233880081-54ada945-b597-4429-bf9d-d4bdbbbe4eed.jpg)

**Comment by arroyoDev** [comment]
im printing coasters (100mm round objects).   set seam gap to random to hid the ugly line, but still got lots of ugly extrusions where each seam started.   I used Orca (softfiver fork) and reduced the seam gap to 5% with great results.   will work on the perfect % without hitting zero (per comments above).  
<img width="406" alt="image" src="https://github.com/bambulab/BambuStudio/assets/699333/fdc81e5e-2cf8-454d-a482-d9cba8a552ec">

**Comment by QingZhangBambu** [comment]
Anyway, we provided those parameters on version 1.7.

**Comment by maurice-lef** [comment]
> There are results of 0.4 nozzle and 0.2 nozzle, sliced by Orca, Printed by Bambu X1C. @Itebayo ![飞书20230424-091158](https://user-images.githubusercontent.com/112676417/233880079-f249382b-1302-4b87-a348-1cd8558fc8e4.jpg) ![飞书20230423-155148](https://user-images.githubusercontent.com/112676417/233880081-54ada945-b597-4429-bf9d-d4bdbbbe4eed.jpg)

@QingZhangBambu 

how have you done that, that you change the settings at specific points. As far as I know there is no possibility to do so in the OrcaSlicer. I am trying to do something similar but it always takes me a long time as I manually have the rewrite the gcode.

Would be very grateful if you could share your workflow/ strategy.

Thanks in advance. :)

**Comment by QingZhangBambu** [comment]
@maurice-lef i change the code, apply it to region parameter, so it can be edit by modifier. it is a method to do quick test. but not suit for you.
