### ISSUE TITLE
Active sensor door

### ISSUE THREAD

**Issue by Looker1981** [bambulab/BambuStudio#1249]
Hi please active sensor door

**Comment by SaltWei** [comment]
Not slicer issue.

I have transfered this ticket to printer team.

For issue about firmware and printer, please move to https://forum.bambulab.com/ or BanbuHandy APP to report ticket (https://wiki.bambulab.com/en/x1/troubleshooting/upload-log) for better support. Thanks!

**Comment by StoneLiBambulab** [comment]
Not slicer issue.

Thanks!
Stone Li
