### ISSUE TITLE
Missing ability to see Printer Build-volume Boundaries 

### ISSUE THREAD

**Issue by UncleJessy** [bambulab/BambuStudio#125]
Most slicers will visually show you if an object is outside of the buildvolume of the printer. This is helpful for the user especially when working with multiple files on the buildplate and knowing which files are too tall to fit the print bed. 

Prusa Slicer <a href="https://imgur.com/XfLd2rW"><img src="https://i.imgur.com/XfLd2rW.jpg" title="source: imgur.com" /></a>
Cura Slicer <a href="https://imgur.com/RVlI7ws"><img src="https://i.imgur.com/RVlI7ws.jpg" title="source: imgur.com" /></a>
Simplify3D <a href="https://imgur.com/T424YPF"><img src="https://i.imgur.com/T424YPF.jpg" title="source: imgur.com" /></a>
Bambu Studio <a href="https://imgur.com/HokGm5w"><img src="https://i.imgur.com/HokGm5w.jpg" title="source: imgur.com" /></a>

**Comment by YifanWuBambu** [comment]
We will optimize it in the next release.

**Comment by lanewei120** [comment]
already added this logic in the newest released version v1.2.0
