### ISSUE TITLE
Brim changing for worse when XY contour compensation values are added

### ISSUE THREAD

**Issue by tinymachines3d** [bambulab/BambuStudio#1251]
**Describe the bug**
No matter the brim width, the brim is altered and at low values (.1-.3) center of the brim is a gap when XY contour compensations over 0 are used. 

**3mf File for This Bug**
[Spacer for acrylic cover.zip](https://github.com/bambulab/BambuStudio/files/10668970/Spacer.for.acrylic.cover.zip)

**To Reproduce**
1. slice with compensation values to all 0
2. slice with compensation values needed to correct model dimenstions
3. slice with compensation values to all 0

**Expected behavior**
skirt to be unaffected by compensation values

![image](https://user-images.githubusercontent.com/28379694/217078669-351612f6-4156-47d7-ac1f-057a36f74d68.png)
![image](https://user-images.githubusercontent.com/28379694/217078752-446f7e48-b181-4784-8e7e-a588c21dc3ef.png)

**Desktop (please complete the following information):**
 - Windows
 - Version 1.4.2.13

**Comment by SaltWei** [comment]
Please check with v1.5.0 Public beta and let us known if still has problem. Thnaks!
