### ISSUE TITLE
Reload Disk loses local coordinates and messed up model

### ISSUE THREAD

**Issue by pennystockss** [bambulab/BambuStudio#1254]
**Describe the bug**
When reloading from disk on a multi part object, all the parts fall apart and lose their local coordinates. Requires reimporting object again.

**3mf File for This Bug**
Hard to attach 3mf file, needs original STL files.

**To Reproduce**
1. Load a multi part object (by dragging 2+ parts to the build plate and hit Yes for multi part object)
2. Right click multi part object on the build plate and hit reload from disk.

**Expected behavior**
To reload from disk properly.

**Screenshots**
![1 Good Model](https://user-images.githubusercontent.com/60720749/217118735-a25ec10f-97a4-4f28-ad6a-671991e1268f.jpg)
![2 Right Click](https://user-images.githubusercontent.com/60720749/217118744-8def9000-a646-4ef4-b90f-3797a0796116.jpg)
![3 After Reloaded from Disk](https://user-images.githubusercontent.com/60720749/217118751-31f84fa4-f825-46de-87bb-889fe71fba01.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.2.13

**Comment by zhimin-zeng-bambulab** [comment]
Could you provide the original stl files, it can help us better reproduce the problem, Thanks!

**Comment by zhimin-zeng-bambulab** [comment]
I tried to reproduce this problem with combined stl files, but it failed to reproduce. Could you provide the original stl files?

**Comment by pennystockss** [comment]
Here try this one for a test, random multipart object:
https://www.thingiverse.com/thing:2485063

All I do is drop all the STL's on the bed.
Hit yes to "Single object with multiple parts"
Then right click and "Reload from disk"

![FirstLoaded](https://user-images.githubusercontent.com/60720749/220238460-fdaa547b-57b4-4b64-b6e5-6248889ff4e6.jpg)
![ReloadFromDisk](https://user-images.githubusercontent.com/60720749/220238466-42e2d72e-7aec-4f47-a48c-5456f6f97f25.jpg)
[Multi-Color_Cell_Model_2485063.zip](https://github.com/bambulab/BambuStudio/files/10789233/Multi-Color_Cell_Model_2485063.zip)

**Comment by SaltWei** [comment]
Fix is included on v1.5.0 Public beta
