### ISSUE TITLE
incorrectly generated supports - Tree(auto) -> Tree Slim

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#1257]
incorrectly generated supports 
Type: tree (auto)
Style: tree slim
"only on construction plate" activated

 - OS: Mac os Ventura 13.1
 - Version bambu studio 1.4.2.13

https://user-images.githubusercontent.com/4783556/217346954-2b96f580-8209-4893-8ac6-59bd77f1a090.mov

![IMG_3733](https://user-images.githubusercontent.com/4783556/217346624-67029f92-1dcb-43a4-a69e-c71af566be08.jpg)

![IMG_3734](https://user-images.githubusercontent.com/4783556/217346665-4c0a254a-536d-4a4e-88d2-290f9520b8b8.jpg)

![IMG_3736](https://user-images.githubusercontent.com/4783556/217346686-b957f8b6-9700-4ce5-b24b-a88a3048b70c.jpg)

**Comment by Kwintyy** [comment]
Similar issue here,

<img width="2056" alt="Scherm­afbeelding 2023-02-07 om 21 41 07" src="https://user-images.githubusercontent.com/55090000/217360926-d67331a1-6e1b-43e5-a139-a0b498259586.png">

[Untitled_plate_1.gcode.3mf.zip](https://github.com/bambulab/BambuStudio/files/10679246/Untitled_plate_1.gcode.3mf.zip)

**Comment by tangketan** [comment]
Would you please share the 3mf? gcode.3mf doesn't contain the model so it's not suitable for diagnosis.

**Comment by tangketan** [comment]
I confirmed that the "build plat only" option was broken in the current public version, which will be fixed in the next release.

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta
