### ISSUE TITLE
Easy improvment on AMS :)

### ISSUE THREAD

**Issue by DzzD** [bambulab/BambuStudio#1267]
![image](https://user-images.githubusercontent.com/12198339/217902109-6233d405-a1cd-478c-bb76-07c7ddf0aa66.png)

Please make the humidity sensor bars "Green" ! 

After a month, I just realized that the humidity bars was grey, until now I was sure to have only 0 bars even if my digital humidity sensor was 12%. And this is just that because I did not realize the bar was light grey on white, original choice :)

**Comment by Ali229** [comment]
Something like if
4 or 5 - green
2 or 3 - yellow
1 - red

**Comment by walterwongbbl** [comment]
HI.
we will redesign the humidity icon.
