### ISSUE TITLE
Arrange All Objects - Selected Plate Only

### ISSUE THREAD

**Issue by olsonjj** [bambulab/BambuStudio#1269]
**Is your feature request related to a problem? Please describe.**
Currently when using the Arrange All Objects feature, it will maximize placement across all plates, consolidating plates if it can.  As a user, using multiple plates is about organization as well.  Placing certain parts together on one plate vs another plate.  I use multiple plates for organizing parts into logical prints, but also for color changes in my non-AMS setup.  

**Describe the solution you'd like**
A checkbox in the UI under Arrange All Objects to limit the optimization only to the currently active plate. 

**Describe alternatives you've considered**
The workout is to use a AMS feature and apply different materials to the objects on the different plates so Bambu Studio won't move objects from one plate to another. This works, but takes extra time and seems unnecessary. 

**Additional context**

**Comment by tangketan** [comment]
We already have this feature. You can use the context menu or icon next to the plates.
![image](https://github.com/bambulab/BambuStudio/assets/13730459/4d63e3d8-da9e-425f-a5ac-224d522cc53b)
