### ISSUE TITLE
Bambu Studio - Linux - Cannot send to print

### ISSUE THREAD

**Issue by candreacchio** [bambulab/BambuStudio#1275]
**Describe the bug**
After slicing, and pressing the send to print option, a window appears, then when sending the print it comes up with an error " Exception: std::bad_alloc

**To Reproduce**
1. Open Bambu studio on linux (latest github code)
2. slice any model
3. send to print
4. hit send
5. Crash

**Expected behavior**
Bambu Studio does not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/10248246/218290117-e2ff0625-324a-4cd3-b96d-50b2bd06dda7.png)

**Desktop (please complete the following information):**
 - OS: Kubunutu 22.10

**Comment by spuiuk** [comment]
This has already been fixed
Please take a look at the comment 
https://github.com/bambulab/BambuStudio/issues/760#issuecomment-1398086890

**Comment by spuiuk** [comment]
I think the fix is in the dev branch though ie. v1.4.2 and haven't been merged with the master branch yet.

**Comment by lanewei120** [comment]
yes, @spuiuk  is correct

please use branch v1.4.2 currently

**Comment by deftdawg** [comment]
Hopefully the fix gets merged soon.

@zhaofengli's [NixOS Bambu Studio package repo](https://github.com/zhaofengli/nixpkgs/tree/bambu-studio) is also impacted by this bug.

**Comment by lanewei120** [comment]
already merged to master
now master should work fine now

**Comment by lanewei120** [comment]
already in v1.5 just released
