### ISSUE TITLE
User defined Filament Preset can't be used in AMS (Dynamic Flow Calibration)

### ISSUE THREAD

**Issue by Laserstrahl** [bambulab/BambuStudio#1277]
**Describe the bug**
When you create a new preset (user defined preset) for a filament it is saved and can be accessed from the drop-down menu under "prepare" tab. When you add an AMS to the system, go to "device" tab, load a filament into the AMS, and click the Icon under the "K" to open up the select filament menu. There you can't see custom filaments, only the system pre-defined ones.

**3mf File for This Bug**
Doesn't matter which 3mf file

**To Reproduce**
see above

**Expected behavior**
For my understanding the user defined filament presets should be available within the AMS Menu to load a user preset to a filament slot of the AMS.

**Screenshots**
Showing user-defined presets
![grafik](https://user-images.githubusercontent.com/59196077/218308168-ece30d31-c3a0-4bb3-acc3-a5544d821e13.png)
Not showing up in AMS Filament selection menu
![grafik](https://user-images.githubusercontent.com/59196077/218308794-a5113f3a-5fcc-44bc-8c0f-eddb9ad82d9c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BambuStudio v. 1.4.2.13

**Comment by SaltWei** [comment]
@bambu123 Please help to check whether this is a bug. I think this is a feature request, rather than bug, right?

**Comment by bambu123** [comment]
Not support custom filament id in AMS.
And not support setting id in AMS.
Here the filament id is different from the setting id.
Custom presets add a setting id, not a filament id.

By the way:
Set to AMS has less effect than selecting in preparing the preset.
So what do you think about respecting?

**Comment by BastiPy** [comment]
I would like to add that it is also not possible to use the Dynamic Flow Calibration with User Defined Presets.  @bambu123 @StoneLiBambulab Should I open a new Issue for this?

**Comment by Laserstrahl** [comment]
> Not support custom filament id in AMS. And not support setting id in AMS. Here the filament id is different from the setting id. Custom presets add a setting id, not a filament id.
> 
> By the way: Set to AMS has less effect than selecting in preparing the preset. So what do you think about respecting?

Anyway also If I use BambuLab Original Filament (which is impossible to order in europe currently) it is not taking the changes over. Please fix this bug in on of the next releases. :)

**Comment by bambu123** [comment]
Dynamic Flow Calibration may be another issue, I'll confirm it.

**Comment by zviratko** [comment]
@bambu123 > So what do you think about respecting?

i.e. When using a filament with very low temperature requirements (Fillamentum NonOilen is what I used that prints between 175-190ºC and must not be heated above 210ºC), not having "custom" material in the AMS/Printer itself still uses the generic PLA temperatures that might be too high.

There are other materials, where setting temperatures used for loading/purging or other operations might be needed. It would be great to be able to import temperatures and other properties from the slicer and have the printer respect them.

**Comment by StoneLiBambulab** [comment]
included in version 1.6, Custom filament presets should be selectable in Dynamic Flow Calibration.
Closed.

Stone Li

**Comment by ArnonAfriat** [comment]
@StoneLiBambulab 
This issue still reproduces in Bambulab 1.7.7.89 on Windows.
