### ISSUE TITLE
Wrong layer count on print completion

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#1286]
**Describe the bug**
A print job just completed but the layer count seems incorrect.

**To Reproduce**
1. Launch a print from BStudio
2. Let it print.
3. From BStudio, once the job is finished, layer count is incorrectly displayed.

**Expected behavior**
To display correct layer count.

**Screenshots**
<img width="789" alt="Captura de pantalla 2023-02-15 a las 19 33 27" src="https://user-images.githubusercontent.com/10992914/219121359-e6e47ae9-0b54-4474-b2b5-3865f64e83ea.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Mac M1
 - BStudio for Mac 1.4.2.xxx

**Comment by SaltWei** [comment]
This is a known issue of studio and have been fixed in internal version.
The user version will be released soon.

**Comment by cameo69** [comment]
Will the fix also include the case that the actual count is greater than the total count?
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/44269764/221440775-c32236af-ff9b-4009-aa15-9fa79729739a.png">

**Comment by SaltWei** [comment]
> Will the fix also include the case that the actual count is greater than the total count?

We only met the case the actual count is smaller than the total count.
Could you share this case by 3MF file to us? We will have a test and check.
Thank you very much!

**Comment by SaltWei** [comment]
Included in v1.5.0 Public Beta
