### ISSUE TITLE
please enable "Save AS" for .3mf files

### ISSUE THREAD

**Issue by ImagineerNL** [bambulab/BambuStudio#1288]
**Is your feature request related to a problem? Please describe.**
I have most of my 3D files as .3mf; I have had this since way before using bambu, as this enables better resolution exports compared to .stl files.
However, when I open .3mf files in the bambu slicer, it says it ; cant load the project, want to import instead?' Sure, as i know it isnt a bambu project file.
However, now, when i want to save, bambu studio automatically overwrites the current 3mf file, which WASNT A BAMBU PROJECT FILE.

**Describe the solution you'd like**
When i start a new project and use .stl files, i can save a project and set the name.
Please enable an option to 'save as ...' where you can set a (new) project file name for your .3mf file

**Describe alternatives you've considered**

**Additional context**

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/220545138-35da7f8d-fc5d-4569-9d3e-efdcef35ac12.png)
Here it is
