### ISSUE TITLE
Control speed slider becomes frozen on top of all applications

### ISSUE THREAD

**Issue by Somerandomgithugguy** [bambulab/BambuStudio#1291]
**Describe the bug**
When clicking the +quick speed" bar to change from 100% to 50% this causes the bar to remains frozen on-screen on top of all other applications and it will only disappear when the Bambu Studio application is closed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a print
2. Go to 'Control' tab and select speed slider and change from 100% to 50%.

**Desktop (please complete the following information):**
 - Windows 10
 - Latest version
 - Bambu Studio 4.2.13

**Comment by lanewei120** [comment]
@Somerandomgithugguy 
Hello

thanks for reporting this issue

is it a 100% reproducible issue or not?
could you give a picture of it?

**Comment by Somerandomgithugguy** [comment]
Hi Lane Wei,

Yes, it is 100% repeatable and I just this moment did it on demand for you. I repeat it by starting a print and then, while the print is processing, I click the speed slider and change from 100% to 50%. Sometimes it freezes immediately on the first click, or sometimes it takes 2-3 repetitions of clicking between 100% a and 50% and then it freezes. 100% repeatable on my system. The only way to get rid of it is to close the Bambu Studio app using the X button within the application, then it disappears. I am on version 1.4.2.13 and I already tried reinstalling and it still happens.

Screenshots attached showing the speed bar frozen over all desktop apps:

Regards,

Random
.
![Bambufreeze1](https://user-images.githubusercontent.com/125633615/220411572-5e237161-cf6a-4922-a616-dede5975bc5d.png)
![Bambufreeze2](https://us
![Bambufreeze3](https://user-images.githubusercontent.com/125633615/220411595-cbe79877-cfbe-4430-ba2b-dbeb76c33a44.png)
er-images.githubusercontent.com/125633615/220411584-7ebf94ac-c4fb-432a-abb9-df7449b9cb61.png)

**Comment by walterwongbbl** [comment]
Hi.
We will fix this issue in the next release version.

**Comment by Somerandomgithugguy** [comment]
Great thanks! :D

**Comment by walterwongbbl** [comment]
Please use the latest version of Bambu Studio
