### ISSUE TITLE
Black not black in AMS menu causing auto spool change to fail

### ISSUE THREAD

**Issue by 3dprintandpaint** [bambulab/BambuStudio#1307]
**Describe the bug**
AMS colour choice on the printer menu isn't black, although it appears to be.  When synced in Studio, the colour is actually dark grey.  This causes issues when a spool ends and you expect it to move across to the same filament on another AMS slot, which may have been assigned black in Studio.  

**3mf File for This Bug**
N/A

**To Reproduce**
Steps to reproduce the behaviour:
1. Select Black via the AMS option on the printer menu.
2. Go to Bambu Studio and sync the AMS with studio
3. Colour shown is very dark grey, not black
4. Filament option used to replicate - Bambu PLA basic

**Expected behaviour**
Choosing black on the screen should be black in the slicer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 11

**Comment by bambu123** [comment]
![image](https://user-images.githubusercontent.com/112537880/222321624-2be3dfde-47be-4ac5-b8e2-772106866ffd.png)

Are you mean this black color? It displays such as on my computer.

![image](https://user-images.githubusercontent.com/112537880/222321694-5c4c3642-fcbd-44f0-8ef1-dddaccd74c57.png)

**Comment by bambu123** [comment]
It is really RGB #161616.

**Comment by bambu123** [comment]
#1170

**Comment by 3dprintandpaint** [comment]
Yes, that's the colour 👍

![Untitled](https://user-images.githubusercontent.com/113126939/222349217-a588b6af-5a5c-4473-96d3-eed8b463a2e9.png)

**Comment by bambu123** [comment]
I think it should be modified on the Printer to use the real black color.
I shall send the issue to the printer team.

**Comment by bambu123** [comment]
@3dprintandpaint
What is the color of your new filament? 
Did you assign the color to it from the touch screen of the printer?

**Comment by 3dprintandpaint** [comment]
I put a roll of black filament into the AMS and assign it black via the touch screen.  When syncing in Studio, it isn't black it is grey.  The colour on the printer screen may well represent grey, which if it does, a black colour option is necessary next to the grey.

**Comment by bambu123** [comment]
AMS auto spool change requires the same colors between the new and old trays, If you assign them the same color, then it should work.
I posted the issue to our printer team, who may answer the problem.

**Comment by 3dprintandpaint** [comment]
I think the original message is getting lost and I'm not sure how else the phrase this.  I am fully aware of how the AMS works. 

It may be better if I rephrase this -

Please ADD a black to dot colour option to the AMS menu.  When you press this BLACK dot, the spool colour is black, not grey.

**Comment by bambu123** [comment]
I think you are requesting more color options on the Printer touchscreen and Bambu Handy App, right?

**Comment by 3dprintandpaint** [comment]
I guess if the current dot, which I assumed was black, is in fact grey, then yes there needs to be a black option.  Currently, because of the dot size, it can easily be mistaken as black when in fact it's grey.  Black is a very popular colour and yet it is missing from the menu.

Adding black to the menu will negate the risk of people thinking (like me and #1170) that the current grey dot is black.

**Comment by bambu123** [comment]
Fixed in version 1.6, please have a try.

Fixed by add AMS filament color for selecting.
