### ISSUE TITLE
Missing Layers in Vase Mode

### ISSUE THREAD

**Issue by laisch-at** [bambulab/BambuStudio#1310]
When Slicing the added Model in Vase Mode, I always get missing layers at about 23.8/ 54.0 and 84mm

Looks like the missing layers are always on the height where the inside has the same shape.

G-Code and STL provided in the ZIP
[wing_test_files.zip](https://github.com/bambulab/BambuStudio/files/10777488/wing_test_files.zip)

Bambu Studio V 1.4.2.13

**Comment by SaltWei** [comment]
This is special 3D printed airplane model and should not use vase mode directly. This is not a bug.
Should use settings as following.
![image](https://user-images.githubusercontent.com/110660407/220353670-6dc06281-a108-4310-aa83-81131f19baed.png)
![image](https://user-images.githubusercontent.com/110660407/220353722-6b236bb7-7801-4521-8c95-85cf958ccac6.png)

**Comment by laisch-at** [comment]
Your provided settings are working fine thx for that.

But my primary intention when making this wing design for testing, was to print it in vase mode, like I did with Cura and my older printer.
In Cura this technique worked totally fine on airplane wing models I designed myself using this technique 
Attached screenshots for comparison: On Bambuslicer you see the shift in Z - direction.

![spiral_cura](https://user-images.githubusercontent.com/125820392/220401383-41140aa8-e24b-4828-b4c9-fdee0976623d.png)
![spiral_bl](https://user-images.githubusercontent.com/125820392/220401403-adfb2155-3213-49a4-b502-02062b38b933.png)

**Comment by SaltWei** [comment]
This is not a bug, just setting difference. If you still want to use vase mode for this model, please set this setting to be 0 as well.
![image](https://user-images.githubusercontent.com/110660407/220490115-95ff90ff-9f90-40d4-9216-7a4bb9883977.png)
BUT, for more other airplane model, we recomand using even-odd mode and settings as I provided in previous comment.

**Comment by andershedberg** [comment]
I also thing there is a bug in the vase-mode. Some things are simply missing in the preview and later prints, and the top and bottom layer are not done at all so the holes for rods are completely missing. I got the impression that the vase mode was to keep the printhead moving in a constant speed to avoid stringing and "jumps", but here it sort of misses other things and part of the wing profile... (I used the vase mode settings from the bambu wiki page, and I think it affected that model as well as it had no "top" cover, but maybe it should have...)

**Comment by P3skyBee** [comment]
> This is not a bug, just setting difference. If you still want to use vase mode for this model, please set this setting to be 0 as well. ![image](https://user-images.githubusercontent.com/110660407/220490115-95ff90ff-9f90-40d4-9216-7a4bb9883977.png) BUT, for more other airplane model, we recomand using even-odd mode and settings as I provided in previous comment.

Wanted to let you know that this has fixed the same issue for me after days of struggling with everything I could think of to fix it. Thank you so much
