### ISSUE TITLE
If Download directory is renamed, Bambu Studio will not start

### ISSUE THREAD

**Issue by TheyWho** [bambulab/BambuStudio#1313]
**Describe the bug**
Bambu Studio [1.4.2.13] SETTINGS saves a default location for DOWNLOADS.
If this download directory is renamed or deleted [outside of the program], then the next time you try to start Bambu Studio, it will show an error that the path cannot be found and exit out.  The ONLY solution is to recreate the missing path.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Go to 'Preferences'
2. Go to 'Downloads'
3. Click on [Browse]
4. Set to a temporary directory
5. Exit Bambu Studio
6. Rename the directory or any directory higher in the path
7. Try to restart Bambu Studio Ver 1.4.2.13
8. Nope, you can't get in. (Windows 10).

**Expected behavior**
I would expect the program to start and allow you to choose another directory.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.4.2.13
 - 
**Screenshots**
![PXL_20230220_041917905 MP_2 (1)](https://user-images.githubusercontent.com/42091622/220011465-9c5cf874-ca23-4d68-9ec1-b70aed42364c.jpg)
![PXL_20230220_041520635 MP_exported_923](https://user-images.githubusercontent.com/42091622/220011485-61112349-bbe6-4783-a85d-265d3aab6290.jpg)

**Comment by SaltWei** [comment]
@walterwongbbl Please check this issue

**Comment by walterwongbbl** [comment]
Hi.
we will fix this issue in the next release version.

**Comment by lanewei120** [comment]
already fixed in v1.5

**Comment by joseRey** [comment]
I had the same issue just now.  I created a new directory and moved the file to it and Babu Studio will not re-start.

**Comment by lanewei120** [comment]
> I had the same issue just now. I created a new directory and moved the file to it and Babu Studio will not re-start.

@joseRey 
could you provide the version info and logs just as described in 
https://github.com/bambulab/BambuStudio/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Comment by walterwongbbl** [comment]
Hi.
Could you please provide detailed step-by-step instructions?

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
