### ISSUE TITLE
Could NOT find wxWidgets

### ISSUE THREAD

**Issue by dovebman** [bambulab/BambuStudio#1317]
When I want to run this command : `cmake ../ -DDESTDIR="/home/doveb/BambuStudio/deps" -DCMAKE_BUILD_TYPE=Release -DDEP_WX_GTK3=1` I get the following error:

```
Make Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  src/CMakeLists.txt:46 (find_package)

```
```
- SLIC3R_ASAN: OFF
-- SLIC3R_BUILD_SANDBOXES: OFF
-- SLIC3R_BUILD_TESTS: OFF
-- SLIC3R_DESKTOP_INTEGRATION: ON
-- SLIC3R_ENC_CHECK: ON
-- SLIC3R_FHS: OFF
-- SLIC3R_GTK: 2
-- SLIC3R_GUI: ON
-- SLIC3R_MSVC_COMPILE_PARALLEL: ON
-- SLIC3R_MSVC_PDB: ON
-- SLIC3R_PCH: ON
-- SLIC3R_PERL_XS: OFF
-- SLIC3R_PROFILE: OFF
-- SLIC3R_STATIC: OFF
-- SLIC3R_WX_STABLE: OFF
-- SLIC3R_STATIC: OFF
-- CMAKE_PREFIX_PATH: (default)
-- PROJECT_SOURCE_DIR: /home/doveb/github_codes/BambuStudio
-- CMAKE_MODULE_PATH: /home/doveb/github_codes/BambuStudio/cmake/modules/
-- LIBDIR: /home/doveb/github_codes/BambuStudio/src
-- LIBDIR_BIN: /home/doveb/github_codes/BambuStudio/build/src
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.66.0") found components: system filesystem thread log locale regex chrono atomic date_time iostreams 
-- Boost::boost exists
CMake Error at cmake/modules/FindTBB.cmake.in:198 (file):
  file failed to open for reading (No such file or directory):

    /usr/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  cmake/modules/FindTBB.cmake:29 (include)
  CMakeLists.txt:397 (find_package)


--   TBB_FOUND               = TRUE
--   TBB_INCLUDE_DIRS        = /usr/include
--   TBB_DEFINITIONS         = 
--   TBB_LIBRARIES           = /usr/lib/x86_64-linux-gnu/libtbb.so
--   TBB_DEFINITIONS_DEBUG   = TBB_USE_DEBUG=1
--   TBB_LIBRARIES_DEBUG     = 
--   TBB_DEFINITIONS_RELEASE = 
--   TBB_LIBRARIES_RELEASE   = /usr/lib/x86_64-linux-gnu/libtbb.so
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "3.3")
-- Found NLopt in '/usr/lib/x86_64-linux-gnu'.
-- Using NLopt include directory '/usr/include'.
-- Using NLopt library '/usr/lib/x86_64-linux-gnu/libnlopt.so'.
CMake Warning at cmake/modules/OpenVDBUtils.cmake:129 (message):
  vdb_print not found! OPENVDB_PRINT-NOTFOUND
Call Stack (most recent call first):
  cmake/modules/FindOpenVDB.cmake:317 (OPENVDB_ABI_VERSION_FROM_PRINT)
  CMakeLists.txt:544 (find_package)


CMake Warning at cmake/modules/FindOpenVDB.cmake:324 (message):
  Unable to determine OpenVDB ABI version from OpenVDB installation.  The
  library major version "8" will be inferred.  If this is not correct, use
  add_definitions(-DOPENVDB_ABI_VERSION_NUMBER=N)
Call Stack (most recent call first):
  CMakeLists.txt:544 (find_package)


-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: iostreams system 
-- OpenVDB libraries: /usr/lib/x86_64-linux-gnu/libopenvdb.so
CMake Deprecation Warning at src/minilzo/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Minilzo using bundled version...
CMake Deprecation Warning at src/qhull/CMakeLists.txt:31 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- qhull Version: 7.2.0 (static linking)
-- IGL NOT found, using bundled version...
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:92 (message):
  CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
  default value of CGAL::data_file_path()
Call Stack (most recent call first):
  src/libslic3r/CMakeLists.txt:395 (find_package)


-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- Adding precompiled header pchheader.hpp to target libslic3r.
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  src/CMakeLists.txt:46 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/doveb/github_codes/BambuStudio/build/CMakeFiles/CMakeOutput.log".
See also "/home/doveb/github_codes/BambuStudio/build/CMakeFiles/CMakeError.log".

```
```
wx-config --version 3.3.0
```

Ubuntu 22.04.2 LTS

**Comment by lanewei120** [comment]
> When I want to run this command : `cmake ../ -DDESTDIR="/home/doveb/BambuStudio/deps" -DCMAKE_BUILD_TYPE=Release -DDEP_WX_GTK3=1` I get the following error:
> 
> ```
> Make Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
>   wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.22/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
>   src/CMakeLists.txt:46 (find_package)
> ```
> 
> ```
> - SLIC3R_ASAN: OFF
> -- SLIC3R_BUILD_SANDBOXES: OFF
> -- SLIC3R_BUILD_TESTS: OFF
> -- SLIC3R_DESKTOP_INTEGRATION: ON
> -- SLIC3R_ENC_CHECK: ON
> -- SLIC3R_FHS: OFF
> -- SLIC3R_GTK: 2
> -- SLIC3R_GUI: ON
> -- SLIC3R_MSVC_COMPILE_PARALLEL: ON
> -- SLIC3R_MSVC_PDB: ON
> -- SLIC3R_PCH: ON
> -- SLIC3R_PERL_XS: OFF
> -- SLIC3R_PROFILE: OFF
> -- SLIC3R_STATIC: OFF
> -- SLIC3R_WX_STABLE: OFF
> -- SLIC3R_STATIC: OFF
> -- CMAKE_PREFIX_PATH: (default)
> -- PROJECT_SOURCE_DIR: /home/doveb/github_codes/BambuStudio
> -- CMAKE_MODULE_PATH: /home/doveb/github_codes/BambuStudio/cmake/modules/
> -- LIBDIR: /home/doveb/github_codes/BambuStudio/src
> -- LIBDIR_BIN: /home/doveb/github_codes/BambuStudio/build/src
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.66.0") found components: system filesystem thread log locale regex chrono atomic date_time iostreams 
> -- Boost::boost exists
> CMake Error at cmake/modules/FindTBB.cmake.in:198 (file):
>   file failed to open for reading (No such file or directory):
> 
>     /usr/include/tbb/tbb_stddef.h
> Call Stack (most recent call first):
>   cmake/modules/FindTBB.cmake:29 (include)
>   CMakeLists.txt:397 (find_package)
> 
> 
> --   TBB_FOUND               = TRUE
> --   TBB_INCLUDE_DIRS        = /usr/include
> --   TBB_DEFINITIONS         = 
> --   TBB_LIBRARIES           = /usr/lib/x86_64-linux-gnu/libtbb.so
> --   TBB_DEFINITIONS_DEBUG   = TBB_USE_DEBUG=1
> --   TBB_LIBRARIES_DEBUG     = 
> --   TBB_DEFINITIONS_RELEASE = 
> --   TBB_LIBRARIES_RELEASE   = /usr/lib/x86_64-linux-gnu/libtbb.so
> -- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "3.3")
> -- Found NLopt in '/usr/lib/x86_64-linux-gnu'.
> -- Using NLopt include directory '/usr/include'.
> -- Using NLopt library '/usr/lib/x86_64-linux-gnu/libnlopt.so'.
> CMake Warning at cmake/modules/OpenVDBUtils.cmake:129 (message):
>   vdb_print not found! OPENVDB_PRINT-NOTFOUND
> Call Stack (most recent call first):
>   cmake/modules/FindOpenVDB.cmake:317 (OPENVDB_ABI_VERSION_FROM_PRINT)
>   CMakeLists.txt:544 (find_package)
> 
> 
> CMake Warning at cmake/modules/FindOpenVDB.cmake:324 (message):
>   Unable to determine OpenVDB ABI version from OpenVDB installation.  The
>   library major version "8" will be inferred.  If this is not correct, use
>   add_definitions(-DOPENVDB_ABI_VERSION_NUMBER=N)
> Call Stack (most recent call first):
>   CMakeLists.txt:544 (find_package)
> 
> 
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: iostreams system 
> -- OpenVDB libraries: /usr/lib/x86_64-linux-gnu/libopenvdb.so
> CMake Deprecation Warning at src/minilzo/CMakeLists.txt:2 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- Minilzo using bundled version...
> CMake Deprecation Warning at src/qhull/CMakeLists.txt:31 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- qhull Version: 7.2.0 (static linking)
> -- IGL NOT found, using bundled version...
> CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:92 (message):
>   CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
>   default value of CGAL::data_file_path()
> Call Stack (most recent call first):
>   src/libslic3r/CMakeLists.txt:395 (find_package)
> 
> 
> -- Using header-only CGAL
> -- Targetting Unix Makefiles
> -- Using /usr/bin/c++ compiler.
> -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")  
> -- Boost include dirs: /usr/include
> -- Boost libraries:    
> -- Using gcc version 4 or later. Adding -frounding-math
> -- Adding precompiled header pchheader.hpp to target libslic3r.
> CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
>   wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
> Call Stack (most recent call first):
>   /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   /usr/share/cmake-3.22/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
>   src/CMakeLists.txt:46 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/doveb/github_codes/BambuStudio/build/CMakeFiles/CMakeOutput.log".
> See also "/home/doveb/github_codes/BambuStudio/build/CMakeFiles/CMakeError.log".
> ```
> 
> ```
> wx-config --version 3.3.0
> ```
> 
> Ubuntu 22.04.2 LTS

this command is used to build deps
you need to execute it in deps/build
![image](https://user-images.githubusercontent.com/106916061/220361523-62aa3114-49ec-405f-8463-ffb99865a307.png)

**Comment by dovebman** [comment]
yes, I know that :) . But after I execute it, I get an error that i wrote earlier

**Comment by dovebman** [comment]
And it is working now. Thank you so much, I'm lost in a world of folders and paths. I've been trying to get it working for 2 full days.
