### ISSUE TITLE
Disable GapFill

### ISSUE THREAD

**Issue by PowerChaos** [bambulab/BambuStudio#132]
hi,
i like to ask to enable a option to disable gapfill
in some cases it is usefull but in most cases it is not
it create a lot of retraction and small infills ( thats why it is gap infill ) on places it can just ignore
as you see the image , the gapfil alone takes longer then the innner walls , 

in prusaslicer it get disabled by puttin the speed on 0 , in bambuslicer it falls back to default speed

Thank you
Greetings from PowerChaos

<img width="552" alt="image" src="https://user-images.githubusercontent.com/7650333/184535751-ad1c94e1-c611-46a1-b379-5cb0c03447c3.png">

<img width="706" alt="image" src="https://user-images.githubusercontent.com/7650333/184535952-d2083d62-7d98-4578-bf57-5a78fade2b0c.png">

**Comment by SaltWei** [comment]
Could you show the printing case that gap infill has bed influence?

**Comment by PowerChaos** [comment]
> But you opinion that gap infill causes more retraction and travel is right. For time saving, gap infill should be reduced, and currently we are evaluating “Arachne Engine” and variable line width.

based on my prusa and my 2 years playing around with the prusa slicer dit gap fill provide me a lot of trouble with certain prints ( default disabled in my prusa slicer ) 
i also got some prints where i need to enable it or the prints i made are useless ( no wall strength , mechanical prints ) 

i agree on technical stand point , if you print mechanical parts ( like holders ) then gap fill is needed to increase strength
if you print just funny objects ( a wobbly snake, a benchy ...  ) then gap fill is a waste of time as those do not even need any strength 
 
 same counts for the new "Arachne Engine"
 based on what i saw , it eliminate gap fill as it use fixed line instead, so it eliminate retraction/clogs and makes a variable line width, just like it can do for the Z height but then to eliminate gaps

 example of where it is needed
 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/7650333/184615198-449ae13a-fb71-417a-9066-42a3abb6fd66.png">

 example of wasted gapfill ( red is top solid infill  , purple is solid infill ) 
 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/7650333/184613265-1d34fce7-6e5d-473b-9965-eeebf9e9a9cf.png">
<img width="401" alt="image" src="https://user-images.githubusercontent.com/7650333/184613306-26389f6f-f050-4329-959d-4318bc7e6938.png">
it apply gap fill to bridge the top layer ?
<img width="352" alt="image" src="https://user-images.githubusercontent.com/7650333/184613515-5a6e4ae1-11ff-4f7a-aa50-4e5abc18e4be.png">

sidenote , just checked again with prusa slicer , they improved gap fill to, where bambu does gap infill prusa just put normal solid infill.
it is disabled by me as default.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/7650333/184614173-c17594f6-25f1-4c90-8c4b-281c1f20a6c2.png">

**Comment by SaltWei** [comment]
Could you share this model stl file so that we can check in detail? Thanks!

**Comment by PowerChaos** [comment]
[laptop.zip](https://github.com/bambulab/BambuStudio/files/9336585/laptop.zip)
this zip contains the example files , the "neusje" is the one on top , the "laptop 0-3" is multi color and 'laptop single" is single color

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/184620638-d44b7644-6270-4a3f-81e7-ff43d271c3d8.png)
The left is prusa 2.5, default setting and disable the option of gap infill.

**Comment by PowerChaos** [comment]
[AMC_Moon.zip](https://vpsdata.be/bambu/AMC_Moon.zip) is a other example of wasted gapfill ( 10% in that case ) with a lot of retractions
<img width="488" alt="image" src="https://user-images.githubusercontent.com/7650333/184622919-7ff0d273-8fc1-4246-89f6-7c2a56d9e584.png">

compared to what prusa does ( if gapfill  is enabled ) 
<img width="526" alt="image" src="https://user-images.githubusercontent.com/7650333/184623118-ad2496fb-b618-4d05-90f9-df24d6982fba.png">

the problem are all those tiny dots that cause massive retraction and caused clogs for me in the past
so forced gap fill when gaps are XX size would be a nice solution , then it wont slow down or jump like crazy
also based on personal experience ( prusa ) it just does not fill up tiny dots anyway, it is to less material to fill up anything

sidenote, i also print at 0.16 layer height , first layer is 0.2 and then 0.16 for all other layers.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/184787344-62917b8f-759a-4757-815f-6585f8880428.png)

The left is the latest released 01.01.01.01 BambuStudio. The right is latest internal BambuStudio which hasn't been released but will coming soon. The right uses arachne engine for internal narrow solid infill to replace ConcentricWithGapInfill pattern.

Gap percentage can be reduced, but solid infill increases.
No obvious time saving as long as the area should be fully filled to be solid.

But I still prefer the right one. Will coming soon.

**Comment by PowerChaos** [comment]
To prevent confusion. This is all I can share as it is a prototype and not from me 
Pictures are taken when printed
When done on prusa they are smooth ( 100mm/s ) but that is with gap-fill disabled 
Maybe the new replacement will eliminate the need to disable gap-fill but as of today it still mess up some complicated prints 

Also as Sidenote. Gap-fill is taking 22% of the print and supports take 28%
![image](https://user-images.githubusercontent.com/7650333/184914466-2e097791-768b-424b-941c-f54535cc6d70.jpeg)

![image](https://user-images.githubusercontent.com/7650333/184912901-9e458884-6061-4612-8a7b-0b23aee74824.jpeg)
![image](https://user-images.githubusercontent.com/7650333/184913392-ab70ceb1-b833-4e95-bc8f-f77ea6e4f271.jpeg)
![image](https://user-images.githubusercontent.com/7650333/184913488-d357a55e-1a44-49cd-a8d3-6fa479413815.jpeg)
![image](https://user-images.githubusercontent.com/7650333/184913598-b1696925-d83c-445e-9a8a-14d577ebbb29.jpeg)

**Comment by SaltWei** [comment]
What's the model? Is this the model you shared in [AMC_Moon.zip](https://vpsdata.be/bambu/AMC_Moon.zip)?
I can print in Bambu Lab X1 Carbon to check whether to be such bad.

**Comment by PowerChaos** [comment]
> What's the model? Is this the model you shared in [AMC_Moon.zip](https://vpsdata.be/bambu/AMC_Moon.zip)? I can print in Bambu Lab X1 Carbon to check whether to be such bad.

the files from the latest pictures are not shared on here , i can send it to you on discord ( or to @sirwill ) as i got permission to share it to you and him only for this purpose.

**Comment by SaltWei** [comment]
> > What's the model? Is this the model you shared in [AMC_Moon.zip](https://vpsdata.be/bambu/AMC_Moon.zip)? I can print in Bambu Lab X1 Carbon to check whether to be such bad.
> 
> the files from the latest pictures are not shared on here , i can send it to you on discord ( or to SirWill on discordl ) as i got permission to share it to you and him only for this purpose.

Hi PowerChaos, SirWill shared the file to me yesterday. I sliced the model with 0.20mm Standard profile and Bambu PLA basic filament, and printed it on two Bambu Lab X1 Carbon machine. The quality is perfect for me. Pictures are shown below.


![飞书20220819-083631](https://user-images.githubusercontent.com/110660407/185517949-cb007e88-a8c2-4220-82c0-7e6cf2226a29.jpg)

![飞书20220819-083619](https://user-images.githubusercontent.com/110660407/185517962-75ccbc7d-4d6d-4e72-bb04-2f3e9ef07f43.jpg)


So I can't reproduce this issue. Is it possible to be caused by filament rather than slicing?

**Comment by PowerChaos** [comment]
Thank you ,
They indeed looks nice.
i tried this with Esun ABS and with MakerFill ASA ( sliced on 0.16 ) 
both works great on the Prusa, 
but it is possible that the slicing is changed between different versions as when i put it in the slicer now i get again other value's then the screenshot i provided ( better value's ) 

i guess i going wait for the latest release and see how things go on from there
The main point of the gap fill remove was to reduce time as it fills in spaces it should not fill in
to prevent certain clogs ( the file that caused a lot of clogs was the laptop one, massive gap fill on the keyboards but seems fixed now ) or just because the gap fill takes as much time as the print itself ( 20%+ of time just to fill useless space ) 

in the end , if you can save 20% of print time or reduce it , then it is worth to disable it ( at least for me  ) 
Same as infill combination can be disabled or enabled to decrease print time 
even adaptive layer height can help in some cases to decrease print time

**Comment by SaltWei** [comment]
Thank you.I will check again with ABS again. My Studio version is

**Comment by hutje** [comment]
I do not see the need for this much gap fill and internal solid infill...
I have attached the 3mf file to check...
[BalloonDog.zip](https://github.com/bambulab/BambuStudio/files/9483230/BalloonDog.zip)


<img src=https://user-images.githubusercontent.com/15308350/188284742-da55a5fd-91f0-4175-91dc-0b37549b9a6e.png width=200>
<img src=https://user-images.githubusercontent.com/15308350/188284752-b91c05ad-1d28-42ac-95dc-58fcdd4688b7.png width=200>
<img src=https://user-images.githubusercontent.com/15308350/188284755-a28257a9-61e3-43f3-8fb1-baa7cc62cc42.png width=200>
<img src=https://user-images.githubusercontent.com/15308350/188284769-68d1585b-e9e5-49c2-8896-3747f1e70c63.png width=200>

**Comment by Bpositivedotdk** [comment]
I would also very much like to have the option to remove Gap infill. In many cases it adds a lot of print time....
On this lamp, its over 5h of 23h total. 

![Skærmbillede 2022-10-31 132153](https://user-images.githubusercontent.com/84511476/199006749-5c60caca-fef6-488f-9551-55c36f24cf20.png)

**Comment by CNCXPROUK** [comment]
It may also be a good idea to have the option to disable it for the first couple of layers.  I’ve had issues where on small prints the speed of the printer doing a gap fill drags the part off the plate because the surface area of the part isn’t enough to keep it bonded.

**Comment by ab3dgeek** [comment]
I would also love to have the option to turn off gap infill pls!
I print tiny objects sometimes and it's totally not needed, it is a lot of extra time, a ton of extra retraction, creates stringing and all the extra movement knocks delicate parts over causing hours of printing to fail.

**Comment by hutje** [comment]
> I would also love to have the option to turn off gap infill pls! I print tiny objects sometimes and it's totally not needed, it is a lot of extra time, a ton of extra retraction, creates stringing and all the extra movement knocks delicate parts over causing hours of printing to fail.

The fork of SoftFever does allow to disable the gap infill. And you can specify the threshold of the length to ignore smaller gaps.

**Comment by ab3dgeek** [comment]
> > I would also love to have the option to turn off gap infill pls! I print tiny objects sometimes and it's totally not needed, it is a lot of extra time, a ton of extra retraction, creates stringing and all the extra movement knocks delicate parts over causing hours of printing to fail.
> 
> The fork of SoftFever does allow to disable the gap infill. And you can specify the threshold of the length to ignore smaller gaps but keep the necessary gap fills

thanks for the tip, I know and use it ;)
but for example last weekend it just stopped working on my m1 macbook as it is not signed and this time malware protection just straight killed it, so as much as I like softfever and I do, I can't rely on it (this is my business as well as my hobby).

**Comment by hutje** [comment]
Apple make life unnecessarily difficult for developers. For end-users it is a blessing, for the developers a curse...

**Comment by LidorBaum** [comment]
Is it planned to be added to the slicer? I think it's important for some situations.

**Comment by QingZhangBambu** [comment]
In classic mode, you can filter the small gaps by using Filter out tiny gaps. To use that parameter, you need to open develop mode. Hope that will be helpful.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/a7f80e58-6bc8-4cab-b70d-d9b9f3d0f68a)

![image](https://github.com/bambulab/BambuStudio/assets/112676417/01062ec3-e3fd-47f1-9ea8-8b5aa4b75755)

![image](https://github.com/bambulab/BambuStudio/assets/112676417/445f694a-5d24-4623-abae-07d79385ff1b)

**Comment by QingZhangBambu** [comment]
This function is added on version 1.7, you can update your software to get that.
