### ISSUE TITLE
Split by Part + X-Y Hole Compensation causes jagged edges

### ISSUE THREAD

**Issue by ctadlock** [bambulab/BambuStudio#1320]
Also posted on SoftFever: https://github.com/SoftFever/BambuStudio-SoftFever/issues/342

If a multi-solid model is imported and it is split by part and "X-Y hole compensation" is non-zero, the resulting slicing has small holes in it. This does not happen if the model is split by object or if the xy hole compensation is 0. 

This is not model related and can be reproduced with any multi-solid model.

**To Reproduce**
1. Import a multi-solid model (use attached as an example)
2. Set "X-Y hole compensation" to 0.1
3. Split by part
4. Slicer

[box.zip](https://github.com/bambulab/BambuStudio/files/10801408/box.zip)

**Expected behavior**
The slicing is clean.

- Windows 11
- 1.4.2.13
- Also happens with Softfever

**Screenshots**

Difference between split by object and part (two examples)
![image](https://user-images.githubusercontent.com/1539397/220561227-72f131b3-8f11-41d9-809e-8a48e740d71e.png)

![image](https://user-images.githubusercontent.com/1539397/220560790-71c03da0-dc4a-4e16-9373-5633f0e81c0f.png)

Poor quality result
![image](https://user-images.githubusercontent.com/1539397/220560929-e15bb889-68da-4e32-94b5-8c619df4da1c.png)

High quality result when split by object (two examples)
![image](https://user-images.githubusercontent.com/1539397/220561460-613260b9-4453-4d7e-b109-e966661eadaf.png)
![image](https://user-images.githubusercontent.com/1539397/220560995-f0f54c2b-2b85-499f-9147-3ca3463475de.png)

**Comment by ctadlock** [comment]
SuperSlicer has this same issue. I think everyone just copied the same code/bug:

![image](https://user-images.githubusercontent.com/1539397/220562964-43771912-7f9a-48eb-b36e-d662ed377b7c.png)

**Comment by QingZhangBambu** [comment]
the color object should better not use X-Y hole compensation, we will add a warning msg

**Comment by QingZhangBambu** [comment]
we will fix it as fast as possible

**Comment by QingZhangBambu** [comment]
you can set the resolution to 0.0 which could fix that

**Comment by ctadlock** [comment]
> you can set the resolution to 0.0 which could fix that

This did not fix the issue

![Image](https://github.com/user-attachments/assets/ec966ceb-73d3-4822-84db-0e439893bdfe)

**Comment by ctadlock** [comment]
@QingZhangBambu this should be reopened
