### ISSUE TITLE
[Feature Request] Centre while zooming in

### ISSUE THREAD

**Issue by ACJUK** [bambulab/BambuStudio#1321]
In Bambu Studio, when you zoom in, it zooms in on the centre of the screen.  So you have to move everything to get the item you want to zoom in on in the centre of the screen and bthen zoom.

It would be better if it zoomed in on the point where the mouse pointer is.

**Comment by TheyWho** [comment]
Upvote,

**Comment by julie777** [comment]
Upvote.

**Comment by elementalbeast** [comment]
i want this too. sketchup has it and i just always assume that bambu will do it when i try to zoom

**Comment by guillaumemolter** [comment]
+1

**Comment by LiZ-Li-BBL** [comment]
Thank you for your suggestion, we will consider this in the near future.

**Comment by LiZ-Li-BBL** [comment]
You can choose a zoom mode in Preferences in new release v1.6.0 Public Beta.
