### ISSUE TITLE
Better Highlighting Of Selected Object On The Object Tab In Dark Mode

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1324]
**Is your feature request related to a problem? Please describe.**
In a large project with multiple plates (in dark mode), it is very hard to see which object is selected in the object list. The background color of the selected object is only slightly different than the dialog background. (It's easily visible if not in dark mode).
![image](https://user-images.githubusercontent.com/96731892/220651036-695993fa-8a22-4090-a5da-f77bbfafe9e4.png)

**Describe the solution you'd like**
Change the background of the selected object to one that works in dark mode and light mode, green or red, for example. Optionally, change the text color.

**Describe alternatives you've considered**
None, really. Hunt down the part on the plate or don't use dark mode.

**Additional context**
Example of highlighted text...
![image](https://user-images.githubusercontent.com/96731892/220652657-befeada3-bc2a-4778-bfd3-d26c65dd39bd.png)

**Comment by bambu123** [comment]
Mac or Windows?

**Comment by MadMax389** [comment]
Windows 11. My apologies, I should have have specified in the original post.

**Comment by bambu123** [comment]
I think it is the background color of the selected item should be changed.
Text color is static in both dark and light modes and does not need to be modified.

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.

**Comment by bambu123** [comment]
Yes, it's fixed in version 1.6, though not pretty.
