### ISSUE TITLE
Icon wrong size for Mac OS

### ISSUE THREAD

**Issue by moebis** [bambulab/BambuStudio#1328]
Screenshot shows it all, but basically the SoftFever version of the logo/icon doesn't conform to the standard Mac OS size for these icons, it's too large: [https://imgur.com/a/lw1BLOl](https://imgur.com/a/lw1BLOl)

Installed latest 1.4.5 version too.

**Comment by SaltWei** [comment]
Not issue on BambuStudio official version. Close

**Comment by moebis** [comment]
Sorry, I opened this bug in the wrong repo. Moved to SoftFever.
