### ISSUE TITLE
[Feature Request] Define Print by Object Order

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1333]
It looks like when I try to print by object it does the shortest piece first, I would like to be able to define the print order of my objects. (example printing using rainbow filament and wanting rainbow to follow specific part order)

**Comment by lanewei120** [comment]
you can change the print order by moving the object up and down in the lift object-list

for the details
you can refer to https://wiki.bambulab.com/en/software/bambu-studio/sequent-print
