### ISSUE TITLE
[*Issue* Bambu Studio Crashes when loading STL] Bambu Studio crashing upon loading a STL File

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1334]
Trying to load a specific STL file and bambu studio crashes with no error message. Happens everytime on a specific STL file.

**Comment by lanewei120** [comment]
could you share the stl file to us for a debug?

**Comment by TopNerdJR** [comment]
https://www.thingiverse.com/thing:5889636

Uploaded the stl file to thingiverse. Ive also tried loading the same file as a 3mf and it starts trying to load the file into the slicer then automatically closes Bambu Studio. Ive also updated to a beta version to test (Both 1.4 and 1.5) and I still get the same result. File is created in fusion360

**Comment by lanewei120** [comment]
already fixed, can load it successfully now
![image](https://github.com/bambulab/BambuStudio/assets/106916061/379f1ea6-6d88-4951-b603-b2bdc1f51b8d)
