### ISSUE TITLE
Markers and arrows size

### ISSUE THREAD

**Issue by suchabadperson** [bambulab/BambuStudio#1336]
The behavior of markers and arrows in Bambu Slicer is not ideal, especially on high resolution screens.

In PrusaSlicer markers are larger, and they grow or shrink as you move closer or further away from the object.
On the contrary, in BambuSlicer they always have the same size, quite small and sometimes it makes difficult to select or modify the object.

<img width="1728" alt="Untitled-1" src="https://user-images.githubusercontent.com/65729856/221362564-a84cd774-84a5-490b-8c94-b113e485a925.png">

**Comment by kertgartner** [comment]
Thank you! Hopefully they'll fix it.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
