### ISSUE TITLE
[Issue] Parameter Field Focus

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1339]
This is a *VERY* annoying bug.  After clicking in a field in Bambu Studio, focus should NOT be taken away from that field without a CLICK.  

Existing behavior:  Moving your mouse cursor away from a text/parameter field causes that field to lose focus.

**Comment by bambu123** [comment]
The 3D canvas takes the focus if you move the mouse there.

**Comment by bambu123** [comment]
@LiZ-Li-BBL Can the 3D canvas not auto-take focus?

**Comment by LiZ-Li-BBL** [comment]
In order to use the toolbar functions properly, the focus need to be set to the canvas. It is not an expected behavior that focus be taken away from a field without a mouse click. We will fix it in the near future.

**Comment by LiZ-Li-BBL** [comment]
In order to use the toolbar functions properly, the focus need to be set to the canvas. It is not an expected behavior that focus be taken away from a field without a mouse click. We will fix it in the near future.

**Comment by LiZ-Li-BBL** [comment]
In order to use the toolbar functions properly, the focus need to be set to the canvas. It is not an expected behavior that focus be taken away from a field without a mouse click. We will fix it in the near future.

**Comment by LiZ-Li-BBL** [comment]
Fixed it in new release v1.6.0 Public Beta.
