### ISSUE TITLE
Feature Request. More options for first and last layer

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#134]
More options; like in Cura for first and last layers. Lines not just Zig Zag, and the ability to change line direction in degrees compared to the x,y orientation of the part.

look at Cura for examples.

**Comment by SaltWei** [comment]
> look at Cura for examples.

Not really understand after see cura. Could you show a example of cura?

**Comment by randyre** [comment]
We can close this, it has since been fixed and even made better than cura.  Thanks
