### ISSUE TITLE
[Issue] slicer doesnt combine two intersecting parts correctly

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1341]
when outting teo parts that (purposefully)  intersect, the combined tool paths are not correct.  put two parts on top of each other anx print it, youll find it outs wxtra walls and features, and then also lays down things like tops/bottom OVER thosw walls, soubling up on filamwnt applied on the layer.

**Comment by MadMax389** [comment]
You need to assemble to the objects to make them one object. Shift-select both objects. Right-click -> Assemble.

**Comment by SaltWei** [comment]
Seem not a bug. Close
