### ISSUE TITLE
Print finish with one missing layer

### ISSUE THREAD

**Issue by b-reich** [bambulab/BambuStudio#1353]
**Describe the bug**
I successful print finish with 30/31 Layer.
Not sure if the last Layer is missing or it is just a ui error.

**3mf File for This Bug**
[Clips.zip](https://github.com/bambulab/BambuStudio/files/10834697/Clips.zip)

**To Reproduce**
1. Print Project
2. Device --> Print Progress
3. Wait until Print finish
4. End with 30/31 Layers

**Expected behavior**
Print should finish with 31/31 Layers

**Screenshots**
![SCR-20230226-sucg](https://user-images.githubusercontent.com/1573025/221436327-7faac8e7-e227-4971-a17b-cfa721212519.png)
![grafik](https://user-images.githubusercontent.com/1573025/221436391-fa1cda67-2565-4de9-8813-faf8313a842c.png)

**Desktop (please complete the following information):**
 - OS: iOS (1.0.11) and MacOS (1.4.2.13)
 - Printer FW: 01.04.00.00 / AMS: 00.00.05.96

**Comment by SaltWei** [comment]
This is known issue that total layer number is wrong.
Has been fixed in internal version and will be released soon.

**Comment by SaltWei** [comment]
Fixed in 1.5.0 Public beta version
