### ISSUE TITLE
FEATURE REQUEST: "Select All" for media browser items

### ISSUE THREAD

**Issue by Photogad** [bambulab/BambuStudio#1354]
**Is your feature request related to a problem? Please describe.**
I have like over 9000 time-lapse videos on my printer's SD card that I would like to delete. I cannot believe in the media browser there is no "select all". You can presently multiple select, but you have to select one at a time, but that would take way too long. So the only way I could delete them is formatting the SD card which is not a smart or convenient way of deleting the timelapses. Plus, there are about 10 timelapses I want to keep!

**Describe the solution you'd like**
A button to put checkmarks in all of the media items.

**Describe alternatives you've considered**
Formatting the SD card to delete many timelapses, which is annoying and won't let me keep some of them.

**Additional context**
![sa](https://user-images.githubusercontent.com/18505956/221439049-09b42fc3-ff40-40c8-a547-df5c07c17b88.jpg)

**Comment by bambu123** [comment]
Perhaps we should provide a selection of year/month groups, selecting all files is dangerous because everything is selected.

**Comment by Photogad** [comment]
> Perhaps we should provide a selection of year/month groups, selecting all files is dangerous because everything is selected.

That would be better than nothing. Some way to mass-delete videos

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.
