### ISSUE TITLE
Unable to copy or paste text on Text Shape tool on macOS

### ISSUE THREAD

**Issue by suchabadperson** [bambulab/BambuStudio#1356]
It is not possible to copy or paste text into the text fields of the Text Shape [T] tool on Bambu Slicer for macOS. Instead, it copies or pastes the 3d model you previously selected. On the Windows version seems to work fine.

![SCR-20230227-lx5](https://user-images.githubusercontent.com/65729856/221595135-af939fd1-89d9-4bb1-bdcf-5c8d66142922.png)

**Comment by SaltWei** [comment]
Please check whether the shortcut key is normal on macOS @LiZ-Li-BBL

**Comment by LiZ-Li-BBL** [comment]
Some keyboard shortcuts seem to work conflictly on macOS, I'm checking this issue and we will fix it in the near future.

**Comment by LiZ-Li-BBL** [comment]
Some keyboard shortcuts seem to work conflictly on macOS, I'm checking this issue and we will fix it in the near future.

**Comment by LiZ-Li-BBL** [comment]
Fixed it in the new release v1.6.0 Public Beta.
