### ISSUE TITLE
Feature request- Part fan speed and aux fan speed control in Bambu studio

### ISSUE THREAD

**Issue by Randy1727** [bambulab/BambuStudio#137]
Currently there is no control for fan speed % in the studio printer control. I clicked aux fan during a print thinking a control would pop up for speed but it only turns it off and on and if you turn it off and then back on it goes on at 100% even if slicer settings are lower. Caused print warping.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/185143696-d4d55346-7e3f-4183-824e-621ab16b2414.png)
The default aux fan speed is set in filament setting，and should not be 100%. What filament are used in your printing?

**Comment by SaltWei** [comment]
Already been handled
