### ISSUE TITLE
Clean RTSP feed on LAN + Upgrade firmware via SD card

### ISSUE THREAD

**Issue by user897943** [bambulab/BambuStudio#1372]
**Is your feature request related to a problem? Please describe.**
I want an unrestricted RTSP feed from the built-in webcam on my LAN at all times so I can add this to Home Assistant to monitor my prints. Currently it's possible to get some sensors and even control some things like the LED light via MQTT but the video stream is still not accessible unless Studio is running and only through a plugin for OBS. I want a normal stream URL directly from the printer, such as: rtsp://10.0.0.69/api/video/mainstream.m3u or such like. Then I can create a generic camera entity on Home Assistant or use whichever stream solution I choose. There's really no good reason not to do this over the LAN if the user chooses. Place a privacy option to toggle on or off in the printer firmware if there's any privacy concerns. The local stream should not affect the ability to do cloud streaming from Studio or Handy.

In addition to the above, I also want a way to upgrade the printer firmware using the SD card. If I don't want to ever connect the printer to the cloud to maintain privacy I should still be able to get improvements delivered to the device. Issue opened here, please go here too and +1: https://github.com/bambulab/BambuStudio/issues/1525

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bambu123** [comment]
VOD is not supported. We only push the stream to a UDP address where you can receive the stream if your software doesn't support RTP/UDP, please update it.
To configure the UDP address, edit the file 'ffmpeg.cfg' in the directory 'cameratool', then kill the bambusource.exe process and restart the 'Go Live'.

**Comment by user897943** [comment]
Not sure if you understood.

I want an always-on rtsp/udp stream from the webcam. The printer is connected and has an IP, why can't you or won't you just give an endpoint for the webcam that's simple to use? Let's take a Hikvision IP camera, if I type this into VLC it will let me stream the video from the cam without modding anything: "	rtsp://192.168.10/Streaming/Channels/101" It's as simple as that. I don't want to modify anything and have to run your .exe file to spin up a stream, that is completely ridiculous.

On my £300 printer running Klipper (working behind me) I have a Logitech C920 and all I have to do is put this into VLC to get the MJPEG stream:
"http://192.168.1.10/webcam/?action=stream"

And my almost £2K printer the X1C with all the accessories and AMS can't do it? It's really ridiculous. I just want to be able to use a clean MJPEG or RTSP stream without fuss, so I can use it as an IP cam on any software.

**Comment by bambu123** [comment]
OK, but this is a printer-side feature request.
I shall be helping transfer to the printer team.

**Comment by user897943** [comment]
Thank you!

**Comment by sprior** [comment]
I agree that a video stream that does not require the Bambu Studio desktop to be involved is highly desirable.

**Comment by sodachen22** [comment]
@user897943 @sprior Thanks for the suggestion. The video through RTSP is not encrypted, and they may cause some compatible problems for RTSPS. What do you think about the security issue?

**Comment by user897943** [comment]
> @user897943 @sprior Thanks for the suggestion. The video through RTSP is not encrypted, and they may cause some compatible problems for RTSPS. What do you think about the security issue?

I don't care about encryption on the local network... It's a webcam inside a printer not a spy camera in the bedroom... Local IP access is enough for me. I can always use a reverse proxy if I want secure internet access (which I do). And a toggle to turn it on or off just like LAN mode would allow the user to choose if they want local unrestricted streaming via URL or encrypted cloud streaming the way it currently works.

**Comment by sprior** [comment]
I agree, I don't personally care about encryption on the local network and don't require the stream to be accessible outside of my LAN.

**Comment by sodachen22** [comment]
Thanks for the feedback. The requirement is recorded internally, we will define the priority and schedule based on feedback from more users.

**Comment by gmartinez3** [comment]
Agreed, Enterprise grade Cameras on the local network routinely use RTSP with plain text credentials, it makes it easy to ingest into existing software.  A future enhancement could be to SSL Encrypt RTSP for public internet traversal, but that's not important for a first round.
I've had a request to ingest a Bambu stream into an Ava Video Management System and pure RTSP would do the trick.  It's not typical, but enables a whole world of integrations.

**Comment by RyanEwen** [comment]
This would be amazing

**Comment by sodachen22** [comment]
Which are the popular Home Assistant or Video Management System? Is there any other popular protocol besides RTSP suported by these systems? If there is, we can consider  to support a more secure protocol.

**Comment by user897943** [comment]
Look, I totally understand as a business that security is extremely important and I know because of online tech blogs you are under a lot of pressure to secure everything but this is way overkill. Just put a switch on the printer settings to turn LAN streaming on/off and explain that it's unencrypted to allow integration into any software. Imagine if you were asking someone to encrypt their Hikvision camera or asking VLC to introduce encryption just for your implementation. It's not required. The cloud streaming is already encrypted, people can use that on the app. If you want, you can implement a limit on the number of connections, for example "allow X number of streams", so that if more than X number of connections are made it's not allowed past that number. Example: Allow 2 simultaneous streams. Then if a 3rd person tries to stream from the local URL on the LAN only, then they can't because the printer will deny it. But that's overthinking. This is a webcam inside a printer, gosh, let's not make a storm in a teacup, it's not a baby monitor inside a child's room. It's a camera in a printer and there's no microphone. The likelihood that someone will hack and use to spy is so low unless someone can prove it otherwise. We are not talking about a security camera here, let's not exaggerate the level of security required. A on/off toggle saying "stream over LAN (unencrypted)" is more than adequate. Keep the cloud streaming as-is so the slicer and phone app continue to work the way they currently do. The LAN stream should be in addition to what we already have, not as a replacement.

**Comment by WolfwithSword** [comment]
+1 to opening up the RTSP camera stream direct from the printer on a lan network without needing bambu studio or the bambu cameratools as a middleman. This allows for any personal use-case to view the camera with a simple URL essentially, for example if a user is with a device without bambu studio or the handy app, and/or the app is not currently working. Additionally, we can then add the camera feed to our own personal monitoring systems.

**Comment by gmartinez3** [comment]
@user897943 's point is exactly right.  There is not a more secure streaming method that is widely adopted, the highest grade Security Cameras stream with RTSP, and they're in schools.  This is a webcam in a printer, there's not danger of someone getting in, they'd need to already be on the local network and by that time you've got bigger problems.  Them simply seeing the stream or credentials, causes no lasting harm.
I'm the CTO for a Security company, and have to say I initially felt the same way, but the industry doesn't have an encrypted standard.  FFMPEG likely wouldn't even handle SSL encrypted RTSP, which is the only other step.  But you shrink integrations to less than 1%.
Take a look at streaming by Unifi, Verkada, Meraki, Ava, Avigilon, Milestone - they're RTSP.

**Comment by RyanEwen** [comment]
RTSP and RTMP are where it's at. Disabled by-default (opt-in) is a fine compromise, if there needs to be one.

**Comment by user897943** [comment]
Here's how to "secure" the unencrypted traffic: add a token to the end of the streaming url. Show the token on the printer LCD just like you are doing for the LAN mode authorization code. Let's assume as an example that the LCD on the printer had RTSP LAN streaming enabled by the on/off toggle, under that show a token such as "hkR47Fy4763gjEr". Assuming the LAN IP of the printer is 10.0.0.10 and the streaming URL is rtsp://10.0.0.10/cam/stream then to gain access the user would enter the following on their video software to access the RTSP on the LAN: rtsp://10.0.0.10/cam/stream?hkR47Fy4763gjEr and voila problem solved. Now only someone with direct access to the printer can get the token and form a valid URL. Using an incomplete URL or invalid token denies access to the stream. That's the "security" for LAN webcam access sorted. Send me a free X1C with AMS for the idea.

**Comment by sprior** [comment]
Totally agreed with @user897943.  The only thing I'd ask while you're doing any of this is to provide a URL for a still image capture as well (this is extremely common on security cams) - not all usecases even need streaming video.

**Comment by Kaloszer** [comment]
+1 for p1p

**Comment by Crazyairborne** [comment]
+1 for RTSP stream. would be super useful for existing integrations

**Comment by AdrianGarside** [comment]
+1 for this. It's my top desired feature by far.

**Comment by djalexz** [comment]
+1 for RTSP stream

**Comment by ltoolio** [comment]
+1 because of everything said before this reply.

**Comment by PHIL-IP** [comment]
+1 for a rstp stream in local network

**Comment by sodachen22** [comment]
Thanks for the feedback, an internal request bbl001-5087 is created, it will be evaluated and planned.

**Comment by user897943** [comment]
Should be available in the next firmware update for sure.

**Comment by cmeans** [comment]
+1 for a RSTP stream in local network.

**Comment by maziggy** [comment]
+1 for a RSTP stream in local network.

**Comment by Nerdiyde** [comment]
+1 for a RSTP stream in local network. :)

**Comment by jumski** [comment]
+1 for RTSP stream!

**Comment by jngmrks** [comment]
+1 for RTSP stream without need of a Cloud!

**Comment by bastiedotorg** [comment]
+1 for a RSTP stream in local network.

**Comment by Cobra-421** [comment]
+1 for RTSP stream without need of a Cloud!

**Comment by uSyzex** [comment]
+1 for a RSTP stream in LAN.

**Comment by greenhawk89** [comment]
+1 for RTSP stream accessible by Home Assistant or VLC. This is a must-resolve IMO and is pretty basic functionality.

**Comment by scorfman** [comment]
+1 for RTSP. Thank you!

**Comment by andreifinski** [comment]
+1
go rtsp, go!
I have to wire up my WYZE camera instead. people have already created mounts for it on thingverse.

**Comment by felinh** [comment]
+1 for a RSTP stream in LAN.

**Comment by LayerCakeMakes** [comment]
+1 would love to see this for home assistant integration, as well as camera support in bambu studio when not using the bambu cloud in lan mode.

**Comment by Worren** [comment]
+1 for a RSTP stream

**Comment by Flight777** [comment]
+1 Really a must have for Home Automation geeks :)

**Comment by sprior** [comment]
For all the Home Automation geeks who want the clean RTSP feed, check out this suggestion to add more automation friendly MQTT topics: [https://forum.bambulab.com/t/recommendation-user-friendly-mqtt-options/2410/4?u=sprior](url)
I submit this as a feature on BambuStudio on github because this is a firmware feature not BS, but then I suppose neither is the clean RTSP feed.

**Comment by user897943** [comment]
> For all the Home Automation geeks who want the clean RTSP feed, check out this suggestion to add more automation friendly MQTT topics: https://forum.bambulab.com/t/recommendation-user-friendly-mqtt-options/2410/4 I submit this as a feature on BambuStudio on github because this is a firmware feature not BS, but then I suppose neither is the clean RTSP feed.

The RTSP feed is absolutely firmware. I meant it must come from the camera and am confident everyone +1 this request feels the same. I don't wanna run a PC for a video feed. It's gonna cost a ton of money, it's inefficient to transcode when the printer board can do that all by itself using much less energy.

Definitely has to be on the printer firmware with no need to open the slicer or an app on a PC or mobile. Must be a straight URL from the printer.

**Comment by user897943** [comment]
I suggest to also open the issue HERE on GitHub rather than the forum.

**Comment by sprior** [comment]
OK, I just opened it here. I would think that a lot of the people interested in the RTSP feed would also want to support this request.  
https://github.com/bambulab/BambuStudio/issues/1504

**Comment by Ali229** [comment]
+1 for a RSTP stream

**Comment by frakki1986** [comment]
+1 for a RSTP stream

**Comment by maniusman085** [comment]
+1 for a RSTP stream

**Comment by FlyingHippo** [comment]
+1 for a RSTP stream in LAN.

**Comment by ice-brainvoid** [comment]
+1 for a RSTP stream

**Comment by HennieLP** [comment]
+1 for a RSTP stream in LAN.

**Comment by MiezLisa** [comment]
+1 for a RSTP stream in local network (LAN).

**Comment by franklinvv** [comment]
+1 For me, this is the biggest shortcoming of these printers.

**Comment by RyanWor** [comment]
+1 for RTSP access

**Comment by azure93** [comment]
+1 for RTSP. Need it !!

**Comment by Photogad** [comment]
+1 for TRSP

**Comment by jan1409** [comment]
+1 for RTSP access !!

**Comment by KyleTeal** [comment]
+1 for RTSP

**Comment by WolfwithSword** [comment]
Noticed the issue name changed to include an irrelevant issue, should be taken out and kept to just LAN video / RTSP stream. Firmware updating has several other duplicates and is unrelated to the camera stream, risks this issue being closed as a duplicate and lose progress on camera streaming.

**Comment by user897943** [comment]
It won't be closed. This is a highly requested issue.

**Comment by AdrianGarside** [comment]
You are just creating confusion and reducing the chance of either by lumping two unrelated issues together. That's now how issue tracking works.

They don't need each other. I am perfectly fine with connecting to bambu cloud whenever they release a new firmware update. That doesn't mean I don't want to be able to do that by sd card as well but it is wholly unrelated to a local video feed by by RTSP which is also wholly unrelated to LAN mode in the first place - I (and I suspect many people) want that even if not using LAN mode because I can then add it in other places (like my home assistant dashboard).

**Comment by WolfwithSword** [comment]
Except there are already other feature requests for the firmware upgrading, and I see you actually have another issue/feature request opened for the same thing (https://github.com/bambulab/BambuStudio/issues/1525) , and then changed this one to also have it...

You may require it, but this feature for the camera stream accessibility is *anything except* pointless with or without the firmware option.

**Comment by user897943** [comment]
We'll see what happens. You'll get your RTSP regardless. It is already in their pipeline.

**Comment by user897943** [comment]
People can be such assholes. I basically got the company to give what everyone wanted and two assholes give me a thumbs down because they don't get their way? I should close the issue, but I won't, because I'm nice. Actually I'm not nice. So I hope there's no further irritation, or I WILL close it.

**Comment by WolfwithSword** [comment]
You made a separate issue for it, and it's still up then you hijacked your own unrelated issue to fit it in because it had more support? You're just being rude and muddying the feature request issue. It's just nicer to keep unrelated feature requests separate when you already had them up (along with others who made them, so dupes). Literally no reason to then modify your older one when you had just made another for the same thing... that's kinda basic common sense.

**Comment by user897943** [comment]
Enjoy.

**Comment by sprior** [comment]
So you think they're not going to do it now that you closed this issue?

**Comment by user897943** [comment]
> So you think they're not going to do it now that you closed this issue?

They will. And every time you launch the cam you'll know ir was because of me, and you'll feel my d*ck going deep down your throat.

**Comment by user897943** [comment]
I love knowing I just made every single person on this issue have to go and +1 the other. And people think they're winning against me.... Lol

**Comment by sprior** [comment]
Sorry, didn't realize you were a twelve year old and that taking your marbles and going home is appropriate for you.  In any case your little temper tantrum doesn't matter since Bambu seems inclined to add this feature.

The people who are winning against you are the ones who have now blocked you as I did.

**Comment by user897943** [comment]
> Sorry, didn't realize you were a twelve year old and that taking your marbles and going home is appropriate for you. In any case your little temper tantrum doesn't matter since Bambu seems inclined to add this feature.
> 
> The people who are winning against you are the ones who have now blocked you as I did.

Congratulations, the more the merrier. If I was 12 that's a pretty great achievement, make a company do a feature I specifically asked FOR ME. Keep the ad hominem coming because that's the best you've got.

**Comment by WolfwithSword** [comment]
This feature request was asked many times even before you made it this particular issue number. Yours just got traction since you posted it everywhere else where people were already discussing it. Then hijacked it for another, unrelated issue. This is why we can't have nice things.

**Comment by AdrianGarside** [comment]
Opened a new feature request with a link to this one for some upvote history:
#1537

**Comment by user897943** [comment]
> This feature request was asked many times even before you made it this particular issue number. Yours just got traction since you posted it everywhere else where people were already discussing it. Then hijacked it for another, unrelated issue. This is why we can't have nice things.

We can't have nice things because I used my time to get this feature on the spotlight then got bullied because people wanted my issue their way and I won't budge. In the end I get the feature and make everyone do extra work. Now what, everyone's gonna raise their RTSP issue just to prove me wrong? Brilliant. They do it even faster. I will win regardless.

**Comment by user897943** [comment]
@WolfwithSword I will personally say thanks to you for working on the NodeRed stuff. You have my respect. Everyone else can kiss my ass and know I win this regardless.

**Comment by Ali229** [comment]
I don't see where in these comments are you being "bullied" or "disrespected", anyone with programming background or general QA, or even common sense on GitHub understands that you have two issues that you want solved, which is totally fine but they are TWO issues and need to be separated. If I was working on this issue with a + I would tell them to open seperate issues for each problem that they are facing.

After being in the wrong you tell people to lick this, feel that and talk about respect. Grow up. Btw just because as issue is opened by you, doesn't mean others can't peacefully reopen it when you throw a fit, you did not do any work, you just opened an issue, stop making it look like you should credited for it.

**Comment by user897943** [comment]
> I don't see where in these comments are you being "bullied" or "disrespected", anyone with programming background or general QA, or even common sense on GitHub understands that you have two issues that you want solved, which is totally fine but they are TWO issues and need to be separated. If I was working on this issue with a + I would tell them to open seperate issues for each problem that they are facing.
> 
> After being in the wrong you tell people to lick this, feel that and talk about respect. Grow up. Btw just because as issue is opened by you, doesn't mean others can't peacefully reopen it when you throw a fit, you did not do any work, you just opened an issue, stop making it look like you should credited for it.

I didn't ask nor do I need someone, especially with a Middle Eastern name where women are treated like trash, to yell me how I should feel. I said I felt bullied and that's all there is to it and if you can't respect that then I can't respect you. How I react is also my prerogative.

**Comment by mike391** [comment]
> > I don't see where in these comments are you being "bullied" or "disrespected", anyone with programming background or general QA, or even common sense on GitHub understands that you have two issues that you want solved, which is totally fine but they are TWO issues and need to be separated. If I was working on this issue with a + I would tell them to open seperate issues for each problem that they are facing.
> > After being in the wrong you tell people to lick this, feel that and talk about respect. Grow up. Btw just because as issue is opened by you, doesn't mean others can't peacefully reopen it when you throw a fit, you did not do any work, you just opened an issue, stop making it look like you should credited for it.
> 
> I didn't ask nor do I need someone, especially with a Middle Eastern name where women are treated like trash, to yell me how I should feel. I said I felt bullied and that's all there is to it and if you can't respect that then I can't respect you. How I react is also my prerogative.

"Ali" the nickname for Alice? I didn't realize the name Alice was middle eastern in origin.

**Comment by RyanEwen** [comment]
I have never seen such an immature (and frankly stupid) reaction to something on GitHub. For starters it's supposed to be one issue per issue (hence the name). Developers hate it when people put multiple issues into one and will generally close the issue until each are opened separately. Secondly, why would you try to sneak in a second issue _after the fact_, anyway? Do you think they'd be suddenly committed to fixing both if you snuck it in after they recognized the first? That's not how it works. There's also no winning or losing and you didn't win any fame for being the OP in the first place. 

This issue was ruined before you edited it to be nothing. Fortunately it's a very common feature request. Thanks to the others for opening a new one.

**Comment by RyanWor** [comment]
This is gotta be the most childish crap I've seen on a GitHub issue. @user897943 the fact that you think any of this has to do with "winning" just proves to everyone else how immature you are. Blocked and unsubscribed.
