### ISSUE TITLE
Make bed type selectable like you select printers, filaments and nozzles

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1379]
**Is your feature request related to a problem? Please describe.**
A P1P user is usually expected to own the Textured PEI-Sheet but not the 3 other build plates - so it makes no sense to make them selectable. if a used owns more then just one build plate, then it should be selectable which build plates are in the selection

**Describe the solution you'd like**
add 4 checkboxes to the printer selection where you can check which build plates you own and want to be shown in the drop down

**Comment by lanewei120** [comment]
![image](https://user-images.githubusercontent.com/106916061/222612526-badbdad4-1f78-4ccc-a873-8173cf899596.png)
bed type is selectable in the left area
do you mean this one?

**Comment by suit** [comment]
Yes, this is exactly what i meant
