### ISSUE TITLE
[BUG] mac Bambu Studio v01.01.01.01 crashes when WAN network changes to offline 

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/BambuStudio#138]
how to reproduce on intel based mac OSX Monterey 12.3

1. start mac Bambu Studio v01.01.01.01
2. click Device tab at top
3. click play in camera pane
4. observe video displays
5. turn off WAN cable internet modem, keep LAN wifi router on
6. observe can still communicate with LAN devices like klipper UI & klipper camera in fluidd/mainsail
7. observe bambu studio crashes with OSX dialog showing stack trace & repoen application
Expected: bambu studio should communicate with camera over LAN, or turn off camera feed without crashing

**Comment by StoneLiBambulab** [comment]
We tried to reproduce it and it didn't happen, please help  upload the crash report when it appears again.

**Comment by SaltWei** [comment]
Please let us known if still exist on v1.5.0 public beta.
