### ISSUE TITLE
AMS Filament Backup missing in v1.5 public beta on P1P

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1386]
**Describe the bug**
Even though release notes mention that P1P now supports AMS Filament Backup Feature, I am not able to find it in the slicer nor in Bambu Handy (all latest firmware (slicer, mobile app, ams, p1p)).

If I click on AMS settings icon in the slicer, I get an error "Current AMS settings does not support using an external spool."

**Screenshots**
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1620004/222562466-cc2b088c-bab1-4166-8070-b70c6c84fc18.png">
<img height="800" alt="image" src="https://user-images.githubusercontent.com/1620004/222562532-d1f6b581-e376-47db-ac7d-8efa52a983c0.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.3

**Comment by Hologos** [comment]
Once I added the same color to a slot, I was able to open AMS settings in the Slicer on desktop. But Bambu Handy still doesn't show this option.

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1620004/222565158-41183862-bdac-4470-af12-a6f17750415d.png">

**Comment by StoneLiBambulab** [comment]
Hi @Hologos ，
    Select any AMS slot to view the ams setting. If the ext. spool is selected, then cliking the ams setting icon, it will pop up this error message. The AMS auto switch filament is the same option as AMS filament backup, i will refine the description. And the feature will be supported in recent printer firmware version, please wait for the printer firmware and upgrade it.

Thanks!

Stone Li

**Comment by Hologos** [comment]
> Select any AMS slot to view the ams setting. If the ext. spool is selected, then cliking the ams setting icon, it will pop up this error message.

I managed to fix that as mentioned in 2nd comment. It would be great if the AMS setting could be opened regardless of selected spool. Or at least to get error message saying the reason.

> The AMS auto switch filament is the same option as AMS filament backup, i will refine the description. And the feature will be supported in recent printer firmware version, please wait for the printer firmware and upgrade it.

As mention, I was on latest firmware on all devices (printer, Bambu Studio and Bambu Handy). The AMS filament backup feature was added in the latest release of Bambu Handy which was released 3 days ago.

**Comment by StoneLiBambulab** [comment]
Hi @Hologos,
    ok. the selection logic is designed for multi AMSs, and it can be optimized if only one AMS exists.  i will refine the logic.

Thanks!

Stone Li

**Comment by Hologos** [comment]
@StoneLiBambulab This can be closed I guess.
