### ISSUE TITLE
When printing a second item, the item name in the Devices page Print Progress was not updated.

### ISSUE THREAD

**Issue by qmc365** [bambulab/BambuStudio#1388]
**Describe the bug**
1. On the "Device" page, after printing a project, when creating a new project for printing, the project name in the print progress bar is not updated, and the displayed project name is still the first printed project name after starting the software, which is different from the project name in the title bar. Project names are out of sync.
2. The prompt text of the filament part in the "Equipment" page is not displayed correctly.(This issue has nothing to do with printing, it is displayed incorrectly after launching the software.)

**To Reproduce**
After starting the software to print the project, check the project name on the device page when creating a new project on the home page and printing it.

**Expected behavior**
1、The print item name on the device page should be updated with the new item name being printed.
2、The prompt text of the filament part should be displayed in a new line.

**Screenshots**

<img width="1904" alt="截屏2023-03-03 03 40 35" src="https://user-images.githubusercontent.com/11454291/222619242-04540ee1-8f94-4caf-90de-2760991a4153.png">

**Desktop (please complete the following information):**
 - OS: [macOS 13.2.1]
 - Version [BambuStudio 1.5.0.59]
 - Version [P1P 01.02.01.00]

**Comment by walterwongbbl** [comment]
Hi.
The name of the title bar is the current project name. So it won't change.
