### ISSUE TITLE
[feature request] Paint mouse/brim ears aka anti warping tab 

### ISSUE THREAD

**Issue by guillaumemolter** [bambulab/BambuStudio#1393]
**Is your feature request related to a problem? Please describe.**
Brims, waste a lot of filaments and are annoying to cleanup. Mouse ears are very commonly viewed as a better alternative to brims. Right now to add mouse ears you need to either [import some additional STL](https://www.printables.com/model/282822-mouse-ears-dissected/) and spend a lot of time placing them, or by adding a primitive cylinder and a negative cube to achieve a proper mouse ear without messing up the walls of the actual model.

![image](https://user-images.githubusercontent.com/1478527/222777241-20ecdd79-2f00-48e0-8824-1f5283ee9fce.png)

**Describe the solution you'd like**
Similar to support painting, I want a mouse ears painting tool that allows me to place mouse ears with one click. This is the plugin I was using with Cura and does exactly what I want: https://github.com/5axes/TabAntiWarping

**Describe alternatives you've considered**
Alternatively you could add a right click option "add brim ear" that would drop the correct shape on the bed and let you place it. Really not ideal but better than nothing.

**Additional context**
https://www.youtube.com/watch?v=MCcFMDv_4eo

**Comment by mlhilljr** [comment]
I would like to second this request. The Brim Ears in Super Slicer is a feature I use on every print. The ease of use and removal is simply amazing!

**Comment by Fredyy90** [comment]
Please add this feature soon, I used it all the time in Cura, and now I really got issues printing some of my models on my x1c. As I don't want to go to a full brim

**Comment by Fredyy90** [comment]
Any Updates on this feature?

**Comment by Fredyy90** [comment]
@StoneLiBambulab did you already discuss this? I could use this feature every day, right now, and avoid countless failed prints.

**Comment by Btamasb** [comment]
We wait for the "mouse ear" function, there is some news from him?

**Comment by StoneLiBambulab** [comment]
I'm sorry. We have some higher priority issues to deal with after discussion for next version (1.7)

Thanks!

Stone Li （旺仔）

**Comment by Calzune** [comment]
Big +1 on mouse ear funktion

**Comment by gitagogaming** [comment]
+1 for mouse ears...

**Comment by niklasdevries** [comment]
+1 for this!

**Comment by CumpsD** [comment]
No idea if this is the same feature, but it would be nice to draw on brim locations. I have parts of my model which really need a brim for the small details, but the rest of the model doesn't need it, and even suffers from a brim.

**Comment by josefdahari** [comment]
Funny I was just looking for this option or feature in Studio and realized it's not available +1 for this as well.  Can come in handy for sure !

Thank you

**Comment by mendylivium** [comment]
I really need this.

**Comment by voglster** [comment]
Just adding my +1

**Comment by DavidCaliri** [comment]
This is the only reason why it's so difficult to leave SuperSlicer.  I use this feature on every print with sharp corners!

**Comment by SaltWei** [comment]
We have add initial version of brim ear in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52 by using feature 2 and feature 3 together. One important thing is that brim ear can use different filament for example support for PLA.
Similar feature request in https://github.com/bambulab/BambuStudio/issues/689

Of course, this is not the best interactive mode. We will try to allow user to use mouse left click to pick which corner needs brim ear or pick corner by angle threshold(may not accurate when model is complex). 

We will keep improving this function.

**Comment by the-robo** [comment]
Please keep working on this feature!

**Comment by tomparvin** [comment]
Would also like to see this feature added! Big time!

**Comment by visualdensity** [comment]
Me too!! Would deeply appreciate being able to paint mouse ears or brim. Thank you!

**Comment by IanAlbinson** [comment]
I'd love to see "Mouse ear" brim type ported over from Orca Slicer 1.7.0. It's so incredibly useful!

**Comment by KeithinPHX** [comment]
Mouse ears please!

**Comment by fangly** [comment]
[V1.7.6](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.06.92) (feature 3) introduced the disc primitive, which serves as a poor man's brim ear.
Looking forward to future developments.

**Comment by Geekmommy4** [comment]
> [V1.7.6](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.06.92) (feature 3) introduced the disc primitive, which serves as a poor man's brim ear. Looking forward to future developments.

Could you get that to work? I couldn't get it to print the disc when I sliced it.

**Comment by Fredyy90** [comment]
> Could you get that to work? I couldn't get it to print the disc when I sliced it.

It's possible to get the disc printed, but it'll always merge the discs into the models, so the outer walls are not nice and clean as they are with a brim or as they should be with brim ears.

I always get them printed like on the left, when it should be like on the right.
![image](https://github.com/bambulab/BambuStudio/assets/1572327/36e043a1-9740-41f0-9936-05a374d25797)

**Comment by Geekmommy4** [comment]
> > Could you get that to work? I couldn't get it to print the disc when I sliced it.
> 
> It's possible to get the disc printed, but it'll always merge the discs into the models, so the outer walls are not nice and clean as they are with a brim or as they should be with brim ears.
> 
> I always get them printed like on the left, when it should be like on the right. ![image](https://user-images.githubusercontent.com/1572327/278089350-8d16625b-1754-4e16-b289-481a10d54228.png)

Makes sense...thanks!

**Comment by PhilBaz** [comment]
Yes, this is a critical feature that is missing. One of the best features of Cura. Its called tab anti-warping. Its very important for us ABS users.

**Comment by SR-G** [comment]
Any progress on this ?
Regarding my personal needs, this is one of the top-most missing features at this time in Bamby Studio ...

**Comment by KiLLie2k** [comment]
+1 back in cura for tab anti warping for a specific piece of a model, would love to stay in orca as this specific printer is well configured for it.

**Comment by lorenzofanchi** [comment]
+1 would be amazing to see brim ears soon!!

**Comment by tauceti82** [comment]
+1 I also highly need this! Don't want don't want to use orca slicer

**Comment by SaltWei** [comment]
We are working on it at the moment.
Not just copy from superslicer, but different function which can paint brim ear.
Highest priority for next big version.

**Comment by CraigHutchinson** [comment]
If we could add this as a `Modifier` volume would be amazing as a UX feature to solve all/any use-case imho. Adding a Cyl;inder to turn on Brim where needed or for parts of a model would be perfect.

**Comment by TheRealHotFix** [comment]
+1 for this request. I almost installed Orca Slicer several times just to get this feature, but I keep coming back to Bambu Studio.

**Comment by IanAlbinson** [comment]
@Dan Just instal it. It’s great and the mouse ears are amazing.

**Comment by MackBambu** [comment]
https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.74
Brim ear has been added.

**Comment by visualdensity** [comment]
Thank you!!!

**Comment by PhilBaz** [comment]
@MackBambu Amazing! Thank you!

**Comment by Geekmommy4** [comment]
Thank you so much!!

**Comment by TheRealHotFix** [comment]
> https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.74 Brim ear has been added.

Thank you VERY VERY VERY much!
