### ISSUE TITLE
Solid Infill Pattern option is missing 

### ISSUE THREAD

**Issue by fredenigma** [bambulab/BambuStudio#1394]
At the moment it is possible to choose infill pattern for top and bottom surfaces as well as for the sparse infill. 
for the other layers filled with a solid infill i.e. if you set to have 6 top layers, the 5 below the topmost surface, the slicer automatically sets the rectilinear infill and there is no way to switch to another pattern.

It can be useful to choose different patterns for solid layers infill, also because the strength of the parts may vary when changing the infill pattern of the outer shell (entirely, not only the cosmetic inside and outside).

It is an option explicitely present in PrusaSlicer, so it should be very easy to port it to BambuStudio, only a "Solid Infill Pattern" item in the slicing option would be required.

**Comment by SaltWei** [comment]
> It is an option explicitely present in PrusaSlicer

Could you figure out which one is in PrusaSlicer？
![image](https://user-images.githubusercontent.com/110660407/223345937-4178f8a6-fb90-4f83-9af0-a48334e13e85.png)

**Comment by fredenigma** [comment]
![image](https://user-images.githubusercontent.com/47599517/223368667-545bfe00-dd08-4a99-8b13-eb70ecc23e1e.png)
It was in Super Slicer (First line, solid) not PrusaSlicer, sorry.

**Comment by SaltWei** [comment]
same with https://github.com/bambulab/BambuStudio/issues/1019

**Comment by QingZhangBambu** [comment]
we've added that on version 1.7.  You can update your software to get that.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/0dd83a3d-c4c3-49c0-8e83-10403f394778)
