### ISSUE TITLE
[Mac/Intel] Text in Project tab changes size

### ISSUE THREAD

**Issue by moebis** [bambulab/BambuStudio#14]
When clicking on the sections in the "Project Tab" on Mac, the large fonts turn small and stay that way until the application is relaunched: https://imgur.com/a/sdY4dQc

**Comment by wuyifanfancy** [comment]
The issue was not reproduced on the formal version Bambu Studio 01.01.00.13.
Please update to this version and try again.
![origin_img_v2_695e9ed2-72ab-4394-bbb8-cd0ee98843dg](https://user-images.githubusercontent.com/73487021/180484541-157a0ea9-8392-4a24-afe5-372737264149.png)
