### ISSUE TITLE
Seam gap & acceleration controls

### ISSUE THREAD

**Issue by npoulos** [bambulab/BambuStudio#1405]
**Describe the bug**
Can you please port over the seam gap enhancement from softfever. I reported this previously and the developer said it showed no difference in the seam when changing to 0 but it actually does and many people have found it useful. It's such a simple fix and already done in softfever so just because your one developer couldnt find use for it doesnt mean it's not useful.

The seam gap also works really well with the ability to limit the acceleration of travel moves so please also port over the extra acceleration controls. 

**Screenshots**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/58903683/222947131-7f29d70e-59e5-4762-bd94-d4ce8688cb55.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/58903683/222947149-928222f9-960d-490e-ae53-974827f808cf.png">

**Desktop (please complete the following information):**
macOS

**Comment by npoulos** [comment]
https://github.com/SoftFever/BambuStudio-SoftFever/issues/166

**Comment by npoulos** [comment]
https://github.com/bambulab/BambuStudio/issues/1063 issue where dev decided not to implement without discussing it further.

**Comment by QingZhangBambu** [comment]
#1247

**Comment by QingZhangBambu** [comment]
What machine did you use? i test that in Bambu X1C. The result is no difference

**Comment by npoulos** [comment]
Tested on both X1C and P1P using 0.2 nozzle. 

You may not be testing with properly tuned K value.

**Comment by QingZhangBambu** [comment]
I will try that with 0.2 nozzle. I used 0.4 nozzles before.

**Comment by QingZhangBambu** [comment]
Plus, there is the test result of 0.4 nozzle
![飞书20230423-155148](https://user-images.githubusercontent.com/112676417/233827079-72e60a6f-be7f-414f-a88f-1d7a51652aa5.jpg)

**Comment by QingZhangBambu** [comment]
There is the result of 0.2 nozzles. PS: I used Orca and apply the parameters you provided. The result still not good
![飞书20230424-091158](https://user-images.githubusercontent.com/112676417/233878326-e9fb7cc2-20b7-4288-b9e7-c72bf1004eba.jpg)

**Comment by QingZhangBambu** [comment]
Could you provide your result and 3mf files?

**Comment by QingZhangBambu** [comment]
we open "seam gap" for develop mode, hope that would be helpful.
