### ISSUE TITLE
Incorrect link in Tip of the Day: Stacking objects

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1406]
**Describe the bug**
Link leads to edit page of Stacking Objects `https://wiki.bambulab.com/e/en/software/bambu-studio/stacking-objects` instead of `https://wiki.bambulab.com/en/software/bambu-studio/stacking-objects`.

**Screenshots**

<img width="415" alt="Snímek obrazovky 2023-03-05 v 10 55 15" src="https://user-images.githubusercontent.com/1620004/222953663-8d70bcb6-9b9a-4a7e-9c2f-2c15f367e789.png">

<img width="1624" alt="Snímek obrazovky 2023-03-05 v 10 55 37" src="https://user-images.githubusercontent.com/1620004/222953666-b7ee5d36-e0f1-47af-aec5-9b22ffa07ddf.png">

<img width="1624" alt="Snímek obrazovky 2023-03-05 v 10 55 45" src="https://user-images.githubusercontent.com/1620004/222953669-12e0936c-3060-4092-87ec-2829e7104182.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.2
 - Version: Bambu Studio 1.5.0.59

**Comment by LiZ-Li-BBL** [comment]
Yes, that's a mistake. It has been fixed and will work normal in the next version.

**Comment by LiZ-Li-BBL** [comment]
Fixed
