### ISSUE TITLE
Ability to center an object

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#141]
Right click context menu item to center an object. Needed especially when adding multi part objects, the ability to center the object to get them to line up.

**Comment by YifanWuBambu** [comment]
@randyre 
When loading multi-parts object, please drag them into Bambu Studio together then it will popup a dialog for importing them as a whole object.
![image](https://user-images.githubusercontent.com/110661856/185553876-6788a11c-dacf-4c08-b98a-f0c6408b00d0.png)

If it still solve your problem, please help share your model to us. Thanks!

**Comment by randyre** [comment]
If I drag and drop and it aligns the parts then later I move a part, how do I get them to line back up again without either centering tools or merge tools or something like that.?

**Comment by klawrow** [comment]
@randyre have you tried using the "Arrange all objects" button?

![Screen Shot 2022-08-20 at 8 50 26 PM](https://user-images.githubusercontent.com/6843695/185771930-84c3ecbd-b396-40a8-a1f8-5fce958ab203.png)

**Comment by UncleJessy** [comment]
> @randyre have you tried using the "Arrange all objects" button?
> 
> ![Screen Shot 2022-08-20 at 8 50 26 PM](https://user-images.githubusercontent.com/6843695/185771930-84c3ecbd-b396-40a8-a1f8-5fce958ab203.png)

That does not reliably work
I have a large object that fits within the buildvolume of the printer
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/73964437/188250675-9339f519-a8a1-4028-9b7a-b863406b7b69.png">
When I use the Arrange function it moves it off the buildplate and I have to manually move it to the center
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/73964437/188250686-33d7b01f-ce3c-4898-8695-95e6f8cdeda8.png">

**Comment by tangketan** [comment]
Try set "brim type" to "no-brim" and see if the object is arranged correctly.

**Comment by klawrow** [comment]
Hmm interesting. I'll have to try a bigger model.

**Comment by UncleJessy** [comment]
> Try set "brim type" to "no-brim" and see if the object is arranged correctly.

Yeah that actually worked. I'd still like the option to center my print regardless of the object size in relation to the buildplate like in other slicers

**Comment by YifanWuBambu** [comment]
@randyre @UncleJessy 
Yes. We may add that feature.

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.
