### ISSUE TITLE
Slicer issues overhang warning for model with no overhang

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1413]
**Describe the bug**

I think the image has all the details. The two holes are thru holes with no dimension changes and no hidden overhangs.

![image](https://user-images.githubusercontent.com/5090005/223000263-a720230e-d599-4f80-a533-3456b5037ed2.png)

**3mf File for This Bug**

[Winder_hand_crank.zip](https://github.com/bambulab/BambuStudio/files/10893621/Winder_hand_crank.zip)

**To Reproduce**

1. Load the model
2. slice it
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.4.2.13

**Comment by tangketan** [comment]
Around z=6.8mm there are overhangs.
![image](https://user-images.githubusercontent.com/13730459/224536947-7cecec05-41ce-462e-8b66-a6bcf562e904.png)

**Comment by julie777** [comment]
Thanks. I didn't see that.
