### ISSUE TITLE
Bambu Studio 1.5 Parameters not restored

### ISSUE THREAD

**Issue by PHIL-IP** [bambulab/BambuStudio#1414]
**Describe the bug**
Settings like last used filaments and last used profile are not reloaded
Only the last plate is saved/restored.

**To Reproduce**
With X1C ON.
Just open Bambu Studio, make changes in the filament AMS list and profiles, close Bambu Studio and re-open it. Filaments and profile are the basics settings.

**Expected behavior**
When we open Bambu Studio reload the last filaments used and reload the last profile used (not the basic 0.20mm standard @BBL X1C profile)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version of Bambu Studio : 1.5.0
 - Firmware version of the X1C : the last one.

Sorry for my english...

**Comment by lanewei120** [comment]
could you give a gif or a short video to show the detailed steps?
we should load the profiles used last time when re-launch slicer

**Comment by Ali229** [comment]
Also having the issue GIF and log attached:
![Animation](https://user-images.githubusercontent.com/11164440/223129240-d2255944-2909-490c-9d33-e80d8be24800.gif)

[debug_Mon_Mar_06_08_48_42_18240.log.zip](https://github.com/bambulab/BambuStudio/files/10898854/debug_Mon_Mar_06_08_48_42_18240.log.zip)

**Comment by PHIL-IP** [comment]
GIF and log file : 
![20230306_202138](https://user-images.githubusercontent.com/26251016/223211354-f1c2ac19-af73-4987-89d3-abc5563916d0.gif)
[debug_Mon_Mar_06_20_22_40_5872.log](https://github.com/bambulab/BambuStudio/files/10902132/debug_Mon_Mar_06_20_22_40_5872.log)

**Comment by bambu123** [comment]
Please also help private the BambuStudio.conf file. Be sure to select some preset and close BambuStudio before sending the file.

**Comment by PHIL-IP** [comment]
Hi, my settings just before closing Bambu Studio :
![2-IMAGE](https://user-images.githubusercontent.com/26251016/223338601-aff38653-0a0c-4d4b-b42b-67169cc842d8.JPG)
... and my BambuStudiuo.conf file :
[BambuStudio.zip](https://github.com/bambulab/BambuStudio/files/10906088/BambuStudio.zip)

**Comment by bambu123** [comment]
Will be fixed in the 1.5 patch version.

**Comment by PHIL-IP** [comment]
Good news.
Thank you
