### ISSUE TITLE
Printing order optimization within a single object

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#142]
Some objects when printed can focus on a single area and then move to another if it's far enough away that the print head won't collide with the object. This is kind of like per object printing. After most of the first layer is complete. this will reduce movement and retractions making the print time less.

In the included picture 
![Skeleton](https://user-images.githubusercontent.com/60475095/185306780-d997a177-bef5-4597-9df6-87a65c6582d2.jpg)
as an example, after a good portion of the body is done, the feet alone could be completed before moving to the head area, saving a bunch of travel time.

**Comment by YifanWuBambu** [comment]
Hi @randyre ,
There may be two problems if we do so.
1. The print speed will be limited to for enough cooling
![image](https://user-images.githubusercontent.com/110661856/185554800-173af1a7-abba-4de6-b9cc-df3013fe117f.png)

2. There will be a visible horizontal grain at each layer where area switching happens.
