### ISSUE TITLE
Device/Print Options has poor wording

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1423]
**Describe the bug**
I believe that the checkbox label should read "auto-recover from step loss" and not "recovery".

![image](https://user-images.githubusercontent.com/5090005/223544845-890a49c7-1404-4c98-b3f0-c599a8c2eef6.png)

Also, it would be nice if there was a tooltip or some kind of explanation about it.
Because I don't completely understand it, I don't know if the button should be enabled when printing or when not printing. Currently it is always enabled.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by StoneLiBambulab** [comment]
Hi @julie777 ,
    i will be fixed in next version.


Thanks!

Stone Li

**Comment by StoneLiBambulab** [comment]
![image](https://user-images.githubusercontent.com/108911794/233878705-2bba8e3f-aaab-46c0-9b00-73fa7fc133c9.png)

included in 1.6.0, closed.
