### ISSUE TITLE
Name of item being printed is truncated

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1425]
**Describe the bug**

The actual name show in the Bambu Studio Title bar is "Print plate Winder and Carriage" but the printing status cuts of part of the title. I don't know if it is based on length or number of characters.

![image](https://user-images.githubusercontent.com/5090005/223546359-3583dcdb-5b60-4bf4-add8-1f2ce03e6742.png)

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by walterwongbbl** [comment]
Hi.
Please confirm if the name on the printer is correct

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
