### ISSUE TITLE
Linux: Live Stream Video Playback fails without ALSA present

### ISSUE THREAD

**Issue by norpol** [bambulab/BambuStudio#1426]
**Describe the bug**

Without ALSA, hitting play at the the Live Stream yields to a popup `Media playback error: Could not open audio device for playback.` and no video starting.

**To Reproduce**

1. Use Pulseaudio or pipewire without ALSA compatibility enabled (or run desktop without audio stack)
2. Click on Video Playback
3. See error

**Expected behavior**

Gstreamer should only playback a video stream and never try to access audio. At the moment, when you're clicking playback of the live stream, gstreamer tries to access several alsa configuration files and ultimately fails if no alsa device is present.

Playing the video shows that gstreamer doesn't need to initialize the audio playback in first place, as no audio is playing.

**Screenshots**

![Media playback error: Could not open audio device for playback.](https://user-images.githubusercontent.com/2230917/223550614-b265a76d-fd11-4d51-89d9-300f4a47b784.png)

**Desktop (please complete the following information):**
 - OS: Linux, Wayland, SwayWM, PipeWire
 - Version: 1.4, 1.5, ..

**Comment by bambu123** [comment]
Thank you for your report!

**Comment by bambu123** [comment]
@norpol
I have a patch, can you help test it?
Do you build the app image by yourself?
[a65ecc8.diff.zip](https://github.com/bambulab/BambuStudio/files/11663690/a65ecc8.diff.zip)

**Comment by norpol** [comment]
Hey @bambu123 Yes I'm building myself with NixOS. I'll test it asap. Thank you a ton for the change already! :)

**Comment by bambu123** [comment]
> Hey @bambu123 Yes I'm building myself with NixOS. I'll test it asap. Thank you a ton for the change already! :)

Thank you for your cooperation!

**Comment by norpol** [comment]
@bambu123 I'll give it a shot, takes a while to build but I think it might be blocked to test it right now because of https://github.com/bambulab/BambuStudio/issues/1843 but I'll give it a try.

**Comment by bambu123** [comment]
> Well done @bambu123, your patch applied to `v01.05.00.61` fixes the problem. I've verified by disabling pipewire-alsa and starting the previous build today video playback would still fail, applying the patch the new one displays the video correctly with no error. Thank you.

Great! Thank you a lot.
