### ISSUE TITLE
Bambu Lab PETG-CF is not supported but Bambu Lab is selling it.

### ISSUE THREAD

**Issue by timmcfadden** [bambulab/BambuStudio#1427]
**Describe the bug**
Bambulab is selling PETG-CF but is is not listed as a option on the printer or in Bambu Studio

<img width="236" alt="Pet-G" src="https://user-images.githubusercontent.com/5409336/223570584-1dbd0373-da3b-42ec-804e-fcc66e29cd39.png">

**Comment by SaltWei** [comment]
https://github.com/bambulab/BambuStudio/releases/tag/v01.05.00.60
