### ISSUE TITLE
Minor grammar correction for new layer display in Bambu Studio device screen

### ISSUE THREAD

**Issue by sprior** [bambulab/BambuStudio#1428]
**Describe the bug**
Recently you added the requested feature to display the current layer/total number of layers.  I would suggest that instead of the message being "Layers: 2/44" it would be more correct to have "Layer: 2/44" because you are effectively saying the printer is on layer 2 of 44, so Layer should be singular not plural.

**Comment by walterwongbbl** [comment]
We will fix this issue in the next release version.

**Comment by sprior** [comment]
I see it's fixed.
