### ISSUE TITLE
(Feature Request)  Bambu Studio Access to video files stored on SD Card

### ISSUE THREAD

**Issue by bluecobras09** [bambulab/BambuStudio#143]
It would be nice if users could download video files from the SD card to their PC.  Instead of having to go to printer, grab SD card, take it back to PC, move file and take the SD card back to printer.  Maybe even extend it to allowing users to copy files to and from the SD card from the PC.

**Comment by YifanWuBambu** [comment]
Yes. We will add this feature in recent release.

**Comment by YifanWuBambu** [comment]
@bluecobras09 
Please update to v1.3.0.12.

**Comment by mattiacolombomc** [comment]
I'm not able to download media from Bambu Studio on my P1P. Are there any possible solution? Already tried to update my Access Code.
Bambu Studio and P1P's firmware are both on latest version.

![image](https://user-images.githubusercontent.com/55593934/233793019-1184d49a-563d-4c37-b7dd-c860f1005a2c.png)

![image](https://user-images.githubusercontent.com/55593934/233793021-f28f0f51-88f5-4667-8ce9-0550358d82d5.png)

**Comment by bambu123** [comment]
P1P does not support sdcard view until now.

**Comment by sodachen22** [comment]
I will be supported in the future.
