### ISSUE TITLE
Bambu Studio Translate error (a menu appear twice in contextual menu of the object)

### ISSUE THREAD

**Issue by PHIL-IP** [bambulab/BambuStudio#1436]
**Describe the bug**
**In French translation**, in the contextual menu of the object (right clic on the object), support blocker and support enforcer has the same translation and so the menu apprear twxice.

**3mf File for This Bug**
No need 3mf file too see the menu in Bambu Studio.

**To Reproduce**
1. Put Bambu Studio in French
2. clic right on an object and take a look on the contextual menu.

**Expected behavior**
I expect a good translation of the contextual menu.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 updated with last updates
 - Version of Bambu Studio 1.5.0.59 build time 20230301-140813

Two files attached, one with Bambu Studio in English and one with Bambu Studio in French

![4-IMAGE](https://user-images.githubusercontent.com/26251016/223954787-218d49de-204c-44b0-b3d5-f016dd72ebc1.JPG)

In this picture you can see where translate is abnormal and where translate is missing.
![10-IMAGE](https://user-images.githubusercontent.com/26251016/223954802-77b03644-f2bc-4f10-bdf9-9be8664c1a5e.JPG)

**Comment by LiZ-Li-BBL** [comment]
Fixed it in the new release v1.6.0 Public Beta.
