### ISSUE TITLE
Monotonic vs monotonic line wrong icon

### ISSUE THREAD

**Issue by nikbyte** [bambulab/BambuStudio#1437]
Issue: Monotonic and monotonic line have icons in slicer which don't fit to result.
What to do: Icons should be swapped between monotonic and monotonic line.
Version: 1.4.2.13

<img width="203" alt="3" src="https://user-images.githubusercontent.com/948963/223973998-d73f53dd-17b0-4a7b-bba5-a98ca5604422.png">

<img width="792" alt="1" src="https://user-images.githubusercontent.com/948963/223974037-61df65f5-d12b-4ae9-bfdf-019a3a7772ac.png">

<img width="730" alt="2" src="https://user-images.githubusercontent.com/948963/223974072-cda4e03c-9e3a-48a3-9252-c7b429dc50c2.png">

**Comment by bambu123** [comment]
Fixed in version 1.6, please check.
