### ISSUE TITLE
Imported models are not centered

### ISSUE THREAD

**Issue by jonfairbanks** [bambulab/BambuStudio#1448]
![Screenshot_1](https://user-images.githubusercontent.com/1957806/224156203-9a804455-1e67-4a4d-a0b0-868c625a8a38.png)
**Describe the bug**
Upon importing any model, the object is not centered on the build plate.

**To Reproduce**
1. Open Bambu Studio (any version)
2. Click on `Add` in the top menu bar
3. Import your model (stl, 3mf, etc.)
4. The model is not centered. Users must right click the model and press Center

**Expected behavior**
Upon importing onto a fresh build plate, the software should automatically center the object. Users should not be required to manually center objects after import.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.5.0.60

**Comment by SaltWei** [comment]
@Haidiye00 Please follow this issue.
@jonfairbanks Thank you very much for siggestion! And also sorry for seeing this much later

**Comment by Haidiye00** [comment]
This issue has been resolved, please wait for version 1.9. thanks.
@SaltWei

**Comment by SaltWei** [comment]
@Haidiye00 Please don't close issue before user can get the fixed version!

**Comment by Haidiye00** [comment]
The latest version has fixed this issue, please try again. thanks

**Comment by jonfairbanks** [comment]
Thanks for the fix!
