### ISSUE TITLE
[Improvement] Camera feed should remain connected when switching away from Device pane

### ISSUE THREAD

**Issue by chendo** [bambulab/BambuStudio#145]
In v01.01.01.01, switching away from the Device pane while the feed is active stops the feed, so when switching back to Device, the camera feed has stopped.

It would be better if the camera feed remained connected, ideally in a picture-in-picture type view, however I will still be happy if the feed just remained active when switching away and back to the Device pane.

**Comment by YifanWuBambu** [comment]
@chendo 
The video feed will auto resume after switch back to device panel in the next release.

**Comment by YifanWuBambu** [comment]
Optimized in v1.2.
