### ISSUE TITLE
Poop shoot to model then back to purge tower 

### ISSUE THREAD

**Issue by nickbert01** [bambulab/BambuStudio#1454]
![43B774F6-18B2-4D6D-A3BB-649D0B9D3F04](https://user-images.githubusercontent.com/59313002/224341779-837da7c2-84bd-42c5-bfa2-46d21aff23cb.jpeg)

when printing multi colours with ams I am getting blobs on 1 model. 
after colour change hotend dosnt go to purge tower but flys over to the model before going back to purge tower which is causing the issue. 

I have tried many models and happens with them all. 
if I print 1 model or multiple on the build plate at once it still happens.

**Comment by zhimin-zeng-bambulab** [comment]
This issue has been improved, you can have a try in the lastest version.
