### ISSUE TITLE
german translation: "preferences"

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1455]
**Describe the bug**
A small language oddity - the preferences is translated with "Vorlieben" - this is literally the right translation, but the in computing context it is best practice to translate differently

**To Reproduce**
1. click on the downward arrow next to "Datei"
2. be confused by not finding the settings/preferences :)

**Expected behavior**
It should be labelled "Einstellungen" instead of "Vorlieben"

**Comment by StoneLiBambulab** [comment]
included in version 1.6.0, closed.

![image](https://user-images.githubusercontent.com/108911794/233878475-14e0bbbe-3860-4afb-80c9-832c684a0ff5.png)
