### ISSUE TITLE
german translation: Ctrl should be "Strg"

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1456]
**Describe the bug**
the shortcuts in the menu of the german version are translated with "Ctrl" but on german computer keyboards there is no Ctrl-Button

**Expected behavior**
The shortcuts should be given the Label "Strg" - if the locale is de_DE or de_AT, on the de_CH locale "Ctrl" would be correct

**Comment by LiZ-Li-BBL** [comment]
Fixed it in the new release v1.6.0 Public Beta.
