### ISSUE TITLE
german translation: Del should be "Entf

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1457]
**Describe the bug**
There is no Del-Key on a german keyboard layout, therefore the shortcut using this button should be renamed

**Expected behavior**
Shortcuts should use "Entf" instead of "Del" - for example "Bearbeiten" -> "Ausgewählte löschen    Entf"

**Comment by LiZ-Li-BBL** [comment]
Fixed it in the new release v1.6.0 Public Beta.
