### ISSUE TITLE
german translation: Shift should be "Umschalt"

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1458]
**Describe the bug**
there is no key with the label "Shift" on a german layout keyboard, the button should be renamed to follow best practices

**Expected behavior**
The button should be given the label "Umschalt" instead of Shift - for example in "Datei" -> "Projekt speichern als Strg+Umschalt+S"

See also ticket #1456

**Comment by LiZ-Li-BBL** [comment]
Fixed it in the new release v1.6.0 Public Beta.
