### ISSUE TITLE
german translation: unit selection uses the wrong wording/typos

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1459]
**Describe the bug**
In preferences you can select the unit system (metric/imperial) - imperial is translated with "Impirisch", which is not even a word 

**Expected behavior**
call them in a sensible manner with correct spelling

the label is debateable, since it is solved differently in different products and not even the folks using those arbitrary rollercoaster units know how to call them properly - officially the are called "United States customary system") - usually you find them with the label imperial  / englische Norm / angloamerikanisch etc.

suggestion solution would be (lowercase))

- metrisch (mm, g)
- imperial (in, oz)

![image](https://user-images.githubusercontent.com/597111/224488945-e6ac2031-ccbd-4e58-8d53-3e6c8ef3d7f0.png)

**Comment by walterwongbbl** [comment]
Hello.
we will bring this change into the next version.

**Comment by StoneLiBambulab** [comment]
![image](https://user-images.githubusercontent.com/108911794/233878553-5b9d87b7-f209-47e9-826b-97764550a540.png)


included in 1.6.0, closed.
