### ISSUE TITLE
[Feature Request] Have button to display filament vs. build plate guide in slicer

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/BambuStudio#146]
I know this seems trivial, but for anyone who's just getting into printing, or using a different filament for the first time, NOT having to go and find the chart of what build plate will work better/worse for your filament would really go a long way.

![image](https://user-images.githubusercontent.com/3382160/185674592-ab7913fd-91e8-477a-abcd-fe57d08ac8ea.png)

Yes, i know there is an error dialog when something isn't supported. However; for example PLA works better on the cool plate - according to the chart.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3382160/185675213-7a39c64c-5ad3-460e-851f-8fcba663ce42.png">

**Comment by YifanWuBambu** [comment]
@dereknheiley That's a good idea. We will add a link to at the "Bed type" text. Clicking it will jump to the bed type intro web.

**Comment by ptyork** [comment]
I'll just add to this a suggestion that having a checklist (ensure proper build plate, open glass top, open door, ensure glue stick, etc.) could be added to the final print dialog.

**Comment by YifanWuBambu** [comment]
Added in v1.2.
![image](https://user-images.githubusercontent.com/110661856/190086628-24c75a99-2ca8-4e54-938c-4a22262470ea.png)
![image](https://user-images.githubusercontent.com/110661856/190086665-adbffdcd-94b1-427b-a7f9-868b9422c165.png)
