### ISSUE TITLE
Ironing

### ISSUE THREAD

**Issue by ver151set** [bambulab/BambuStudio#1460]
Add pattern options like concentric for ironing to improve quality on certain prints. Zigzag doesnt work well for things like small lettering and leaves noticeable imperfections around the edge, Cura offers pattern options

**Comment by SaltWei** [comment]
@QingZhangBambu Please evaluate and have a check

**Comment by QingZhangBambu** [comment]
Good point! I tested the concentric ironing pattern and got better surface quality. 
![20230424-095702](https://user-images.githubusercontent.com/112676417/233882330-6544cf46-9cf6-4b0e-9f21-99aca358bc92.jpg)

**Comment by TestApp90** [comment]
@QingZhangBambu : Could you please share the settings? Using the default profile, I'm getting an ironing layer with small holes in it.

**Comment by QingZhangBambu** [comment]
@ver151set concentric pattern had been added on version 1.7.  You can get that by updating your software version.
