### ISSUE TITLE
3D connexion Spacemouse no function in Bambulab studio on Mac

### ISSUE THREAD

**Issue by Enderglueck** [bambulab/BambuStudio#1462]

**Comment by stefanvaduva** [comment]
There is a Cura plugin that may be a good starting point for solving this issue: https://github.com/smartavionics/RawMouse I'm also interested to be able to use SpaceMouse in BambuStudio.

**Comment by pandel** [comment]
+1 I am so used to my 3D mouse in SuperSlicer, especially for positioning support blockers and such... so please fix it!

**Comment by jetmansion** [comment]
Note also that there is a keyboard shortcut for related settings (Command-M), but that keyboard shortcut is the 'minimise' command by default in MacOS. Therefore using that shortcut would just minimise BambuStudio.

**Comment by leandrolima-nyc** [comment]
+1 Unfortunately, I was unable to achieve success with BambuStudio. 

However, I can confirm that the desired functionality works flawlessly on OrcaSlicer. Specifically, I utilized the Pro version and successfully incorporated custom commands accordingly, along with increasing the speed of the up, down, right, and left axis movements.

![System Settings 2023-06-01 at 12 41 46AM@2x](https://github.com/bambulab/BambuStudio/assets/70433062/484fc94e-3901-47a2-b4a1-b63c89ec9c6f)

**Comment by pandel** [comment]
Any news on this? I am slicing a dozen parts, which have to be positioned in rather complex ways and normal mouse navigation is a absolutely aweful in this regard! Please, please fix this asap!

**Comment by jetmansion** [comment]
I took some time looking in to this and it looks like the problem is caused by the code-signing of the application. The 3Dconnexion drivers is a third party library that needs to be loaded and BambuStudio doesn’t seem to have the correct entitlement set.

The actual code used in OrcaSlicer is identical as that in BambuStudio (at least as far as I can tell through github). But OrcaSlicer is not signed and therefore is not limited by that.

The correct entitlement is actually available in a file in Github (src/platform/osx/entitlements.plist) but maybe this isn't correctly set when code-signing the application?

**Comment by pandel** [comment]
@jetmansion YES! You got it! I compiled BambuStudio myself and now my spacemouse is working without issues. So, this is an easy fix. Wait for a new release, compile and be good to go. Many thanks!

**Comment by jetmansion** [comment]
@pandel Thanks! Your comment motivated me to do my own build as well. Works great!

**Comment by Fast-T** [comment]
1.7 Beta 2 still not working. Please fix this

**Comment by stefanvaduva** [comment]
Both PrusaSlicer and OrcaSLicer now have this working. Is there anything else that the community can do to have this working in BambuLab as well? @LiZ-Li-BBL @lanewei120 ?

**Comment by lanewei120** [comment]
> @jetmansion YES! You got it! I compiled BambuStudio myself and now my spacemouse is working without issues. So, this is an easy fix. Wait for a new release, compile and be good to go. Many thanks!

we have confirmed if not sign BambuStudio.dmg, it can work(just the same case as built by self)
or if sign the driver with the same codesign, it will also work

but it won't work if using the original driver(unsigned) with the signed BambuStudio

we are still digging into it

**Comment by lanewei120** [comment]
already supported in v1.7.2.51, please have a try

**Comment by stefanvaduva** [comment]
Everything is fine on my end, good job and thank you!

**Comment by jetmansion** [comment]
Can confirm that the issue has been resolved. Thanks!

**Comment by pandel** [comment]
Works perfectly well :-)! Many thanks!
