### ISSUE TITLE
Textbox loses focus if you move mouse over 3d viewer

### ISSUE THREAD

**Issue by TennisRunner** [bambulab/BambuStudio#1465]
**Describe the bug**
When trying to set the layer height. If I select the text and then move my mouse away (over the 3d viewer). The textbox automatically deselects. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.4.2.13

**Expected behavior**
Should stay focused

**Screenshots**
http://i.imgur.com/Ta97XCe.gifv

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by adamfilip** [comment]
+1 this is a huge pain. please fix.

**Comment by LiZ-Li-BBL** [comment]
Same problem with #1339. We plan to fix this in the next release.

**Comment by LiZ-Li-BBL** [comment]
Fixed it in new release v1.6.0 Public Beta.
