### ISSUE TITLE
PA-CF Filament Profile is missing as a default system present when adding .6 nozzle via setup tool

### ISSUE THREAD

**Issue by accetturo** [bambulab/BambuStudio#147]
The PA-CF Filament Profile is missing as well as many others, but Bambu labs should cover this as it's a manufactured filament and you recommend a .6 nozzle on the sales page. Can anyone share it and can we get it added to an update?

The reason that Bambu X1C is such an amazing printer is it just works when using all Bambu parts and filaments, so having the right profiles for the various nozzle sizes, especially if it's your recommendation, is critical to user success.

**Comment by YifanWuBambu** [comment]
The PA-CF filament preset for 0.6mm nozzle will be in the next release.

**Comment by accetturo** [comment]
Thank you, Can we get the rest of the profiles included as well, especially the supports?

**Comment by YifanWuBambu** [comment]
Absolutely!

**Comment by SaltWei** [comment]
Has been included in latest version 1.2.0.9
