### ISSUE TITLE
Cutting an object at a 45 degrees Breaks Dimensions with FIX ANSWER

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#1470]
So I raised the green cut out up, rotated it 45 Degrees to plane cut off the corners, rotate it back lower it down and this happens, there is actually a fix, you have to cut it again at a straight line it then resets it back so the 45 degree cut is changing the rotation and scale direction of the object

![Screen Shot 2023-03-12 at 2 11 57 PM](https://user-images.githubusercontent.com/48887257/224567488-f31efb73-eea4-458c-883b-53556a3862d1.png)

**Comment by Benderrodrigu3z** [comment]
Cut the Green object at a flat plane height and see what happens to the scale of the object
[AMS Cable Release V2 Cut.3mf.zip](https://github.com/bambulab/BambuStudio/files/10951796/AMS.Cable.Release.V2.Cut.3mf.zip)

**Comment by zhimin-zeng-bambulab** [comment]
It has been improved, you can have a try in the latest version(such as V1.7.7).
