### ISSUE TITLE
Incorrect layer progress being reported

### ISSUE THREAD

**Issue by ACJUK** [bambulab/BambuStudio#1471]
On the display, the layer progress is incorrect.  It'll say things like 300/200 making it look like it's on layer 300 out of 200

**Comment by SaltWei** [comment]
What version are you using?
And please also share the 3MF for reproducing.
Thank you very much!

**Comment by SaltWei** [comment]
> What version are you using?
> And please also share the 3MF for reproducing.
> Thank you very much!

@ACJUK

**Comment by SaltWei** [comment]
Can't reproduce this issue on latest version and also no response about environment.
Close at the moment.
Please reopen if it appears again. Thanks
