### ISSUE TITLE
Deficiencies of Arrangement Function 

### ISSUE THREAD

**Issue by KarelBarrel** [bambulab/BambuStudio#1472]
**Describe the bug**
Instead of arranging the objects in a regular grid, one object is offset or jumps to an unexpected position. Could you please fix the function to behave predictably?

This may seem like a trivial request, but it can often result in confusion, especially when dealing with multiple objects.

**3mf File for This Bug**
There is a picture of what I mean. I am clicking arrange and one object stands out.
![image](https://user-images.githubusercontent.com/110020840/224577056-366003be-8056-4601-9c2a-85a1a712d4d8.png)

**To Reproduce**
1. Use 3mf 
[Cube_Arrange.zip](https://github.com/bambulab/BambuStudio/files/10952220/Cube_Arrange.zip)

2. Drag the object wherever you want 
3. Press arrange function
4. See: one object stands out

**Expected behavior**
As I have mentioned before - arrange in a regular grid, when it is possible

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Version 1.5.0.60

**Comment by tangketan** [comment]
It's because the occlusion region of the cutter and difficult to fix. And it doesn't affect the printing.

**Comment by tangketan** [comment]
Our team has managed to solve this problem. Will be in the next release.

**Comment by tangketan** [comment]
Solved in latest Studio 1.7.
