### ISSUE TITLE
Add possibility to rename plate

### ISSUE THREAD

**Issue by kozakm00** [bambulab/BambuStudio#1474]
I'd like to have possibility to rename each plate when using multiple plates.

Expected result:
* right click on plate -> Rename plate
![image](https://user-images.githubusercontent.com/112867011/224681255-e25728a8-10cf-4ca9-a8d5-d62eee615b75.png)

**Comment by stonexx1234** [comment]
+1

**Comment by lanewei120** [comment]
thanks for the suggestion
we will add this feature in recent versions

**Comment by lanewei120** [comment]
already added in v1.7.2.51
