### ISSUE TITLE
"File > New Window" launches the SoftFever fork

### ISSUE THREAD

**Issue by Elbau** [bambulab/BambuStudio#1478]
Since the 1.5 update when I select File > New Window, the application launches the SoftFever fork of the software that I have installed on the machine, instead of creating a new instance of the BambuLab software.

I'm on MacOS 13.2.1 (22D68)
running BambuStudio 1.5.0.60

**Comment by cmguo** [comment]
It opens BambuStudio.app with the exact name.

**Comment by bambu123** [comment]
Fixed in version 1.6, please have a try.
