### ISSUE TITLE
"Export plate sliced file" exports a 3MF file with the extension ".gcode.3mf"

### ISSUE THREAD

**Issue by Elbau** [bambulab/BambuStudio#1479]
The file selection dialog automatically appends the .gcode extension. The file that is actually exported is a binary 3mf file with the extension '.gcode.3mf'

Additionally, the language is unclear -- as I would expect any "sliced" file to be gcode. Perhaps "export individual plate as project" would be more clear, if the feature is intended only for splitting a multi-plate projects into single plate .3mf files.

MacOS 13.2.1 (22D68)
BambuStudio 1.5.0.60

**Comment by lanewei120** [comment]
hello, the .gcode.3mf includes not only gcode, but also some thumbnails&&settings, which are necessary for printing
however, to save the file size, it doesn't include the geometry data
so it is not a project file for individual plate
but a print file for individual plate
