### ISSUE TITLE
"Random" seam position missing

### ISSUE THREAD

**Issue by tokamac** [bambulab/BambuStudio#148]
In PrusaSlicer, there are 4 settings for the seam position:
- **Random**
- **Nearest**
- **Aligned**
- **Rear**

But in BambuStudio, there are only 3 settings:
- **Nearest**
- **Aligned**
- **Back**

So **Random** has disappeared.

I do not consider this a "feature" but a bug. Random seam position can led to a fuzzy surface in some occasions, but for specific models that have no back vs front face and no edge (an object with rotational symmetry for example) that can be manipulated and looked from any angle, random dots are sometimes preferable over an unsightly very visible line.

Please consider bringing this feature back into BambuStudio.

**Comment by YifanWuBambu** [comment]
Okay, we will add it in the next release.

**Comment by SaltWei** [comment]
Done.
