### ISSUE TITLE
Ää Üü Öö ß -  German Umlaut's not usable (3D Text Tool)

### ISSUE THREAD

**Issue by Popoboxxo** [bambulab/BambuStudio#1488]
**Describe the bug**
It is not currently possible to use "umlauts" - Ää Üü Öö ..." -in the 3d text tool..
[https://en.wikipedia.org/wiki/Umlaut_(diacritic)

And the German spare is unfortunately full of them.

**3mf File for This Bug**

All 3mf Files

**To Reproduce**

1: Start Bambu-Studio
2: Add an random 3D-Object
3: Use the 3D text tool
4: Type some "normal" letters
5: Now try to add german "umlauts"
6: ( if umlauts are used, the text can also no longer be moved )

**Expected behavior**
Text's like "test ä # text" can be generated
Text's like "test Ä # text" can be generated
Text's like "test ö # text" can be generated
Text's like "test Ö # text" can be generated
Text's like "test ü # text" can be generated
Text's like "test Ü # text" can be generated
Text's like "test ß # text" can be generated (also an special "character)

**Screenshots**

![2023-03-14 20_05_20-Unbenannt](https://user-images.githubusercontent.com/11631395/225111893-d0cf28f8-90e6-4a9a-bd60-1f364d20b554.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 Build 22621.1265
 - Version: 1.5.0.61

**Comment by ChrMaass** [comment]
That's exactly what I was about to report. Annoying, because I also have an umlaut in the name and just wanted to print a few sachen 😅

**Comment by Popoboxxo** [comment]
Worst Case :D

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v1.6 released on github.
