### ISSUE TITLE
Max fan speed threshold for Layer Time of 8 for Bambu PLA-CF is causing issue with print quality in version 1.5x

### ISSUE THREAD

**Issue by timmcfadden** [bambulab/BambuStudio#1492]
**Describe the bug**
Under Cooling:  Max fan speed threshold for Layer Time of 8 for Bambu PLA-CF is causing issue with print quality.  In version 1.4 Max fan speed thershold for Layer Time was 2 and printed better.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**
Set the default layer Time for Max fan speed threshold back to 2

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Windows
![Bambu2](https://user-images.githubusercontent.com/5409336/225172023-265fbb72-1265-4bb8-87d0-b554e8156624.png)
<img width="1107" alt="Bambu3" src="https://user-images.githubusercontent.com/5409336/225172032-150b902e-fa7b-43ba-8c3c-4edb07871d70.png">

 - Version 1.5x

**Comment by QingZhangBambu** [comment]
If the layer time is less than 8 seconds, the cooling strategy will be turned on. So the outer walls may have different velocities, resulting in an uneven appearance. You can slow down the outer wall speed to improve that. If the layer time is less than 8s, some features may fail during the printing.
