### ISSUE TITLE
Multiple Text Fails on the Newest Update 1.5.0.61

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#1499]
Nan? how is an object I just created at Nan when I clicked on the surface?

![Screen Shot 2023-03-15 at 2 03 07 PM](https://user-images.githubusercontent.com/48887257/225417353-22cdc2dc-3f86-4d75-a7d5-156ef0f7f267.png)

[Screen Recording 2023-03-15 at 2.04.41 PM.mov.zip](https://github.com/bambulab/BambuStudio/files/10983800/Screen.Recording.2023-03-15.at.2.04.41.PM.mov.zip)

https://user-images.githubusercontent.com/48887257/225417391-3bc8edb9-a92e-47b6-b4a3-d69382466c2e.mov

**Comment by Benderrodrigu3z** [comment]
another issue in the Screen Recording ZIP, its a Zip cause the video is 28mb

**Comment by Benderrodrigu3z** [comment]
Object Gets NAN how here:

Uploading Screen Recording 2023-03-15 at 2.21.15 PM.mov…

**Comment by Benderrodrigu3z** [comment]
How to Nan an Object:

https://user-images.githubusercontent.com/48887257/225420213-88c2cf1a-c1d7-4130-988f-cfadcb30f041.mov

**Comment by Benderrodrigu3z** [comment]
right when you click bam NAN, can you at least make it use a different filament color so we can see that its laying the object?

https://user-images.githubusercontent.com/48887257/225421047-0c9028c5-474e-4ff0-890c-c035d9c71e56.mov

**Comment by Benderrodrigu3z** [comment]
https://user-images.githubusercontent.com/48887257/225423299-56d549eb-8062-4fe7-852d-0187437ebddb.mov

**Comment by zhimin-zeng-bambulab** [comment]
@Benderrodrigu3z  Could you share your 3mf file, it will help us to solve this problem, thanks.

**Comment by Benderrodrigu3z** [comment]
[Slot_BLANK.3mf.zip](https://github.com/bambulab/BambuStudio/files/10991841/Slot_BLANK.3mf.zip)

**Comment by zhimin-zeng-bambulab** [comment]
Thanks, I can reproduce this problem, we will fix it in the next version.

**Comment by Benderrodrigu3z** [comment]
Sounds great thanksSincerely,Shane FSent from my iPhone13On Mar 17, 2023, at 4:00 AM, zhimin-zeng-bambulab ***@***.***> wrote:﻿
Thanks, I can reproduce this problem, we will fix it in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v1.6 released on github.
