### ISSUE TITLE
[FEATURE REQUEST] gcode preview mode

### ISSUE THREAD

**Issue by moebis** [bambulab/BambuStudio#15]
In an earlier version there was a dev mode that allowed previewing of the gcode. Some of us find this super useful and would like the option to preview and even edit the gcode from the slicer.

**Comment by RobinWhitfield** [comment]
For clarity, this functionality was available in 01.00.10.03, and is not available in 01.00.10.05

**Comment by RobinWhitfield** [comment]
#8 removed this functionality.

**Comment by VACIndustries** [comment]
Any plans to bring this back into the fold?

**Comment by RobinWhitfield** [comment]
@wuyifanfancy, any updates as to when/if this might be re-added? One or two versions down the line? Never?

**Comment by SaltWei** [comment]
Hhas been included in https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65
