### ISSUE TITLE
Filament profiles deleted after update :(((

### ISSUE THREAD

**Issue by MartinM8266** [bambulab/BambuStudio#1501]
The update of the last bugfix deletes the custom-filament profiles!

is this really neccessary???? EXTREMLY annoying!
Any way to recover them at least??

thanks for at least replying 👎

**Comment by MartinM8266** [comment]
Filament profiles are stored in C:\Users\XXXX\AppData\Roaming\BambuStudio\user\XXXX.
These are inherited profiles from the standard profiles. Only changes in comparison to the standard profiles are beeing stoered in the json-files.
Managed to recover the filament profiles, but there should be any kind of warning or automatic reimport at least.

**Comment by Benderrodrigu3z** [comment]
More like try to delete them and they keep redownloading from the backup, they won't deleted

**Comment by cmguo** [comment]
Please turn on 'Sync user presets'.

**Comment by Benderrodrigu3z** [comment]
Where is this setting on Mac?Sincerely,Shane FSent from my iPhone13On Mar 16, 2023, at 8:40 PM, cmguo ***@***.***> wrote:﻿
Please turn on 'Sync user presets'.

**Comment by bambu123** [comment]
![image](https://user-images.githubusercontent.com/112537880/225816454-91b7846b-9f83-48e7-bc04-835296122c03.png)

**Comment by Benderrodrigu3z** [comment]
So mine is missing the Associate file types on Mac, also mine was set to 30sec which was causing my issue cause I was closing without waiting, you can close this cause once I waited longer it workedSincerely,Shane FSent from my iPhone13On Mar 16, 2023, at 11:58 PM, cmguo ***@***.***> wrote:﻿

**Comment by bambu123** [comment]
My picture is from the Windows system. I only mean the ‘Auto sync user presets'.
@MartinM8266 Had you turned on the switch?

**Comment by MartinM8266** [comment]
yes.sure.

______
Martin Mostböck / +43 6991 3415453 / ***@***.***
von Android gesendet.
Am 21. März 2023 02:58:19 schrieb cmguo ***@***.***>:

**Comment by bambu123** [comment]
> Filament profiles are stored in C:\Users\XXXX\AppData\Roaming\BambuStudio\user\XXXX. These are inherited profiles from the standard profiles. Only changes in comparison to the standard profiles are beeing stored in the json-files. Managed to recover the filament profiles, but there should be any kind of warning or automatic reimport at least.

So what did you do to recover the filament profiles? Were the files under the 'user' directory lost?

**Comment by dkern** [comment]
I had the same issue after update, all my custom profiles are missing now. I have found the files in my profile folder, but I have no idea how to restore them.

**Comment by bambu123** [comment]
@dkern Turn off and then on 'Sync user presets'.

**Comment by bambu123** [comment]
It occurs after updating the network plugin after updating BambuStudio. Restarting BambuStudio may help.

**Comment by bambu123** [comment]
Fixed in version 1.6, please have a try.
