### ISSUE TITLE
Change printorder per plate

### ISSUE THREAD

**Issue by ChrMaass** [bambulab/BambuStudio#1502]
I try to optimize my prints and print as many parts at once. Sometimes it makes sense to print multicolored parts in order by object, but for other parts of the same color it makes more sense to print by layer, because then you can make the plate fuller.

It would be great if you could select the print order depending on the print plate and not only globally for the whole project. Or at least override it for individual plates.

**Comment by lanewei120** [comment]
we have already provided this option for each plate

could you try it
![image](https://user-images.githubusercontent.com/106916061/225801811-f5c2d913-252b-42ab-954b-5f721b447a84.png)

**Comment by ChrMaass** [comment]
Thanks a lot, I have overseen it.
