### ISSUE TITLE
Why can't Studio jump to the device page immediately after print is sent?

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1509]
**Is your feature request related to a problem? Please describe.**
I hate waiting. Also, this delays the turn on of the camera.

**Describe the solution you'd like**
Jump to the device page as soon as the send is completed successfully.

**Describe alternatives you've considered**

**Additional context**

**Comment by Merlwynd** [comment]
Mine does....After I send the file to print, Bambu Studio automatically goes to the device page and then I start the camera (doesn't start automatically unless I have already sent a print earlier in that instance of Bamby Studio).....Maybe there is a setting involved?...although I don't remember one...

**Comment by julie777** [comment]
Mine does a 3 second count down before switching.

**Comment by StoneLiBambulab** [comment]
Hi @julie777 , 
just give the users a moment to confirm that the task has been sent.

Thanks!

Stone Li

**Comment by bolsoncerrado** [comment]
@StoneLiBambu  did you close this because "Print file" already does this or you added the behaviour to "SEND TO PRINTER" too?

I ask to avoid opening a new FEATURE REQUEST duplicate.

**Comment by StoneLiBambu** [comment]
"Print plate" will send the current plate printing job to printer and start to print and "Send" will only send the xxx.gcode.3mf to printer, you can start the print job on printer screen or MicroSD card on device Page.
![image](https://github.com/bambulab/BambuStudio/assets/156414594/0d2ba2e5-8dd4-4451-9607-bfd98d696ffb)

![image](https://github.com/bambulab/BambuStudio/assets/156414594/6630d3b6-7cf7-4e3d-9c60-6bfa96b3dba1)


Thanks!
Stone Li（旺仔）
