### ISSUE TITLE
[FEATURE REQUEST] Increase more "Recent models" perhaps tied to Settings/Preferences option?

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#1512]
**Is your feature request related to a problem? Please describe.**
I find it handy to  have MORE recent models listed to choose from when I want to start a new print. Specially useful for repetitive models in a Farm environment.

**Describe the solution you'd like**
Increase more "Recent models" perhaps tied to Settings/Preferences option?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by StoneLiBambulab** [comment]
Hi @bolsoncerrado ,
    it is a const value in the code, Consider that very few users will use this feature, maby we can provide a way to modify the config file to support this.

Thanks!

Stone Li

**Comment by bolsoncerrado** [comment]
OK thanks.

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.

**Comment by StoneLiBambulab** [comment]
closed.
