### ISSUE TITLE
Add Custom G-code on layer show the last custom gcode on every layer

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1513]
**Describe the bug**
I added 2 different custom g-codes on 2 different layers. If I check the custom g-code on both layer, the UI show the last custom g-code even though the correct custom g-code is present in generated g-code.

**3mf File for This Bug**
[at-at_plate_1.gcode.3mf.zip](https://github.com/bambulab/BambuStudio/files/11009512/at-at_plate_1.gcode.3mf.zip)

**To Reproduce**
1. Add custom g-code on one layer.
2. Add custom g-code on different layer.
3. See custom g-code on both layers.
4. Export g-code and check in generated g-code.

**Expected behavior**
Correct custom g-code is shown in the UI.

**Screenshots**
<img width="839" alt="Snímek obrazovky 2023-03-18 v 21 25 32" src="https://user-images.githubusercontent.com/1620004/226136991-971d1d0a-e9d1-41be-a402-dfc70aec993d.png">
<img width="871" alt="Snímek obrazovky 2023-03-18 v 21 25 42" src="https://user-images.githubusercontent.com/1620004/226137005-e5e479d5-2a92-4d94-8c97-fc4973bd68c9.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Bambu Studio 1.5.0.61

**Comment by LiZ-Li-BBL** [comment]
It's a flaw. Actually you cannot check the added custom g-code. We will add viewing function later. Appreciate your feedback.

**Comment by LiZ-Li-BBL** [comment]
In the new release v1.6.0 Public Beta. You can edit the added custom gcode in the layer, or when adding a new custom gcode the inputbox will be empty by default. And also, a gcode-window has been added so that you can view and check the actual inserted gcode.
