### ISSUE TITLE
'large overhang' warning in Bambu Studio is worse than useless

### ISSUE THREAD

**Issue by AdrianGarside** [bambulab/BambuStudio#1519]
It pops on almost every single object I slide. Including those that have zero overhangs:
![image](https://user-images.githubusercontent.com/26147576/226196172-2bb1e36c-3fc5-47c0-a4d3-a138d59597f8.png)
![image](https://user-images.githubusercontent.com/26147576/226196182-255ccc76-665d-4a46-a2da-c31bd48484ec.png)

That makes it worse than useless as you are training me to always dismiss it immediately. Until it doesn't have a near 100% false positive rate I suggest you turn it off.

**Comment by Merlwynd** [comment]
I also see large need for improvement on this issue. Have not tested if changing the threshold angle under 'Supports" impacts the message coming up.....although Supports in slicer are normally turned off anyway...

**Comment by suit** [comment]
Additionally it pops up on items where it can bridge perfectly fine - like the on the benchy - there should be a bit less of a threshold for bridges/overhangs to trigger the warning

**Comment by AdrianGarside** [comment]
@tangketan https://github.com/SoftFever/OrcaSlicer/blob/main/resources/calib/vfa/VFA.stl

**Comment by ZInventor** [comment]
I've had this warning pop up on nearly every print - enough that I just ignore it now and even if there were an actual problematic overhang I wouldn't even notice due to the warning being so useless.

**Comment by tangketan** [comment]
Thanks for reporting the issue. I've upgraded the algorithm. The VFA model you provided, including all the other models I have on hand, are OK without false alarm. Please wait for the next release.

**Comment by AdrianGarside** [comment]
Awesome! I'm looking forward to that popup being useful to alert me when I should really be adding supports.

**Comment by psy0rz** [comment]
check out https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65

can probably be closed now.
