### ISSUE TITLE
Firmware upgrade via SD card

### ISSUE THREAD

**Issue by user897943** [bambulab/BambuStudio#1525]
**Is your feature request related to a problem? Please describe.**

 I want a way to upgrade the printer firmware using the SD card. If I don't want to ever connect the printer to the cloud to maintain privacy I should still be able to get improvements delivered to the device.

There is no reason why this cannot be done, if you have LAN mode.

**Comment by Hologos** [comment]
How is this BambuStudio related feature?

**Comment by user897943** [comment]
> > Mind ya business.
> 
> It is our business when you bother developers with your printer requests in Slicer issue tracker. Instead of them focusing on fixing bugs and bringing new features, they have to spend time to process this. ;)
> 
> Duplicate #887

I repeat what I said.
