### ISSUE TITLE
[*Issue*] Text Items Don't follow object

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1526]
1. Create a solid
2. Place text on the solid using the tool.
3. Transform the solid (the text follows, good).  [rotate it 180 degrees, flip it upside down.]
4. click the generated "text_shape" in the objects tree.
5. Click the Text Tool bar button to edit the text item.
6. Exit the text editor.

Expected Result: The text object would be changed, in place, following the transformation of the solid it was attached to.

Actual Result: The Text object is edited but remains in its original position, prior to transforming the solid.

**Comment by zhimin-zeng-bambulab** [comment]
The text tool has been improved, you can have a try in the latest version.
