### ISSUE TITLE
Lan mode on P1P is unusable for anything other than simple models

### ISSUE THREAD

**Issue by AdrianGarside** [bambulab/BambuStudio#1538]
I was using lan mode and other than some minor annoyances like the frequent resyncs bambu studio was doing and how much time that added for things like changing AMS filament settings, it was working.

Tried to print a complex model that was 26Mb. I tried 3 times and bambu studio never successfully completed the copy to the printer. The upload count went in fits and starts and always eventually errored out. Example error (did not check if they were all the same):
![image](https://user-images.githubusercontent.com/26147576/226198291-e02f2dc2-6adb-4805-b505-5c3fe5d41713.png)

**Comment by walterwongbbl** [comment]
Hi.
Have you checked the network status?

**Comment by AdrianGarside** [comment]
I have a prosumer network setup and zero networking issues with any other device if that's what you're asking. I haven't re-tested with the newest firmware that just dropped but I can say the prior firmware dropped mqtt connections *a lot* where the one before that had much more reliable mqtt connections.

**Comment by walterwongbbl** [comment]
Hi.
Please use the newest firmware, and a new studio version is also coming soon.

**Comment by AdrianGarside** [comment]
Upload to the printer seems more reliable now - it's still not a great transfer - averaging about 115kb/s and appears to still stop/start a little. But it succeeded for a 5Mb file. Haven't yet tried with any larger models.

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
