### ISSUE TITLE
"An error occurred. The system may have run out of memory, or a bug may have occurred. bad allocation" during slicing

### ISSUE THREAD

**Issue by MIKEPASQ** [bambulab/BambuStudio#1544]
**Describe the bug**
"An error occurred. The system may have run out of memory, or a bug may have occurred.
bad allocation". Happens on a very specific model. I have 80% free RAM during slicing so it isn't my system memory issue. 

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Go to 'slice plate'

**Expected behavior**
Sliced model so I can print. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14248721/228116906-582e6601-cc17-41f8-afd3-c63271016862.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
[Cloak Back Split 1 parts B.zip](https://github.com/bambulab/BambuStudio/files/11084800/Cloak.Back.Split.1.parts.B.zip)

**Comment by QingZhangBambu** [comment]
We've fixed it. You can get it in next version

**Comment by NemoPS** [comment]
This is till happening in 2.0.1.50

![Image](https://github.com/user-attachments/assets/7e0583b0-476d-4a08-8fe8-52343833e1c5)
