### ISSUE TITLE
Main window with black text on dark background

### ISSUE THREAD

**Issue by haegar33** [bambulab/BambuStudio#1546]
**Describe the bug**
The main windows changes text color from white to black after loading an .STL file or open a new project

**To Reproduce**
1. Open Bambu Studio Version 1.5.0.61  on MacBook Pro
2. Program starts, Window is ok
3. Open an .stl file or start a new project
4. text in input boxes of settings tabs changes to black

MacOs Appearance mode is in "Auto". Actually when **manually** switching between light and dark theme Bambu Studio follows correctly.

**Expected behavior**
When setting MacBook to Auto theme the app should follow and not display a dark theme with black text

**Screenshots**
<img width="658" alt="bambu_studio_window" src="https://user-images.githubusercontent.com/22793462/228250475-95327351-b7fe-46b0-9d2d-d1330b254ff4.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.6.1
 - MacBook Pro 2021 with M1 chip
- Studio Version 1.5.0.51

**Comment by bambu123** [comment]
I can not reproduce it.

**Comment by haegar33** [comment]
Actually yes the error is random. 3 times launching and closing the app gives 2 times the correct window colors. Workaround is to change the appearance theme one or two times. Bambu Studio windows color change accordingly and are persistent.

Probably hard to trace but maybe you find a slight bug in the initialization phase of the software ;)

**Comment by bambu123** [comment]
@walterwongbbl Please try to reproduce.

**Comment by walterwongbbl** [comment]
Hi.
Have you set the macos appearance mode to dark or light? Does it look correct

**Comment by haegar33** [comment]
ok there is a pattern now:
- with a **fresh** start of  MacOS Bambu Studio shows the dark text on dark background
- when actively change MacOS appearance BS window is in correct dark or light mode
- BS exhibit correct colors, even when terminating the app and restart
- my default MacOS appearance is "Auto" mode

**Comment by walterwongbbl** [comment]
Hi.
Very sorry, we have tried the method you provided many times, but it cannot be reproduced
