### ISSUE TITLE
Make an option to generally disable the flushing volumes

### ISSUE THREAD

**Issue by suit** [bambulab/BambuStudio#1547]
**Describe the solution you'd like**
Add an option to disable the flushing volume - i'm aware that you can minimzie it, flush it into infill an objects etc.  but there is no way to disable the flushing volumes at all

**Additional context**
the P1P and X1 poops a lot after every filament change, then you flush additional material into a flushing volume with a forced amount, that you cant reduce below a certain treshold?

simply make an option at the filament settings "disable flushing volumes" - done

if you currently want to change the filament without a flushing volume you need to change it to the same filament, then the volume does not get created

**Comment by zhimin-zeng-bambulab** [comment]
If you want to disable the flushing volumes, you can set the  flushing volumes to 0. You can have a try in the latest version.

**Comment by dimitarsp** [comment]
> If you want to disable the flushing volumes, you can set the flushing volumes to 0. You can have a try in the latest version.

I have A1 with AMS with Bambu Studio 1.10, and all flushing volumes are set to 0, yet the printer still produces residue between filament change
