### ISSUE TITLE
Import SVG as line extrudes instead of solids

### ISSUE THREAD

**Issue by ptsao88** [bambulab/BambuStudio#1548]
Hi Bambu Team!

I have some line art that I wanted to import into Bambu Studio and line extrude over a flat surface.

I imported the picture and exported it as an SVG file (see attached).

![3DPrint_Printer](https://user-images.githubusercontent.com/62680638/228633894-568751d6-f108-470c-9b16-9c9d8141f0eb.svg)

I then imported this into Bambu Studio and this is the result. It looks like Bambu Studio is turning every layer of the line art into a solid. Is there a way to only have extrudes along the line paths as opposed to converting the whole thing into a solid?

![image](https://user-images.githubusercontent.com/62680638/228633998-f299098e-4ce4-4f78-8eb2-261795863302.png)
![image](https://user-images.githubusercontent.com/62680638/228634086-e10251dd-0c40-42fb-8762-60b9bbf82c78.png)

If this isn't possible currently, I would like to request it as a feature if possible.

Thanks.

**Comment by lanewei120** [comment]
I am afraid currently not supported
Iit seems you want to generate a "Three-dimensional" model from the svg?

**Comment by ptsao88** [comment]
Hi @lanewei120,

Yes, to get a 3D model from the SVG upon import. See picture below.

To do this, I had to trace the artwork and then export as an SVG. Then import the SVG into Solidworks, extrude it, and then save it as a STEP before importing into Bambulab.

It would be great if Bambulab could import the traced SVG and then just extrude it in the slicer.

![image](https://user-images.githubusercontent.com/62680638/229574830-7e79e41e-8b56-4a6a-b698-196fb1ce1d6b.png)

**Comment by lanewei120** [comment]
> Hi @lanewei120,
> 
> Yes, to get a 3D model from the SVG upon import. See picture below.
> 
> To do this, I had to trace the artwork and then export as an SVG. Then import the SVG into Solidworks, extrude it, and then save it as a STEP before importing into Bambulab.
> 
> It would be great if Bambulab could import the traced SVG and then just extrude it in the slicer.
> 
> ![image](https://user-images.githubusercontent.com/62680638/229574830-7e79e41e-8b56-4a6a-b698-196fb1ce1d6b.png)

for the above picture, it is possible to send the step file generated by solidworks here?
then I can understand this requirement more clearly

thanks

**Comment by ptsao88** [comment]
Yes, see attached for the original artwork, the SVG that was converted from the artwork in Lightburn, and the STEP generated in Solidworks.

[3DPrint_Printer.zip](https://github.com/bambulab/BambuStudio/files/11201930/3DPrint_Printer.zip)

**Comment by zhimin-zeng-bambulab** [comment]
This problem will be fixed in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://user-images.githubusercontent.com/120697589/231325753-0141caba-4afd-4440-9ebd-3efafd86029b.png)

The picture above shows the effect of importing svg in the current internal version. Does it meets your needs?
By the way, the import process may take some time.

**Comment by ptsao88** [comment]
@zhimin-zeng-bambulab - are you able to provide a copy of the internal version so I can test this out?

At first glance this looks like it may do what I want.

The time for importing is OK - it currently takes a long time to convert in Solidworks anyway.

**Comment by zhimin-zeng-bambulab** [comment]
I am sorry that we can not provide a copy of the internal version.  We will release a version this month, you could verify it later. Thanks!

**Comment by lanewei120** [comment]
v1.6 published on github, please have a try

**Comment by ptsao88** [comment]
@lanewei120 sorry for the delay in testing.

This doesn't work as expected. It seems to trace the lines but doesn't "fill" it in like in the actual picture. Below is the artwork.

![image](https://user-images.githubusercontent.com/62680638/236686943-65fd4290-2ff4-4139-b3ee-12efc521cea3.png)

Here is a comparison of what it should look like (top) and what the native SVG import is going (bottom).

![image](https://user-images.githubusercontent.com/62680638/236686860-9607a455-8580-4f86-98ab-203b75ad973c.png)

If I try to print/slice with the native import (bottom), it gives a bunch of errors. This is presumably because the line widths are too small.

![image](https://user-images.githubusercontent.com/62680638/236687107-e346ac6d-8609-4958-b5f7-cedcfb3345d2.png)

**Comment by zhimin-zeng-bambulab** [comment]
@ptsao88 
You are right, this is because the line widths are too small. You can modify the "Wall generator" to "Arachne" as show below.
![image](https://user-images.githubusercontent.com/120697589/236714326-84a683ec-2d29-40be-8ffa-ea26908824da.png)

**Comment by ptsao88** [comment]
Ah perfect - thanks! This seems to work.


Cheers.

*Philip Tsao*
*BASc, Electrical Engineering*

***@***.***    |    philiptsao.com    |    *emberprototypes.com
<http://emberprototypes.com>*
