### ISSUE TITLE
Tree Supports Colliding With Other Objects

### ISSUE THREAD

**Issue by DrakeLewis** [bambulab/BambuStudio#155]
I have not tested this with all supports, but this has been verified when using hybrid (auto). When the tree supports are generated they will collide with other object on the build plate. My initial assumption was that the tree support was forming around the other object, but after printing the support was going directly through the object on every layer.

My thoughts is that after generating supports there should at the least be an error presented, but ideally it should prevent you from sending to the printer or automatically move objects around the print bed to prevent this from happening
![Screenshot 2022-08-22 220645](https://user-images.githubusercontent.com/52681897/186060775-1aa0f66f-5568-4614-863d-338d8d8d4bb2.png)
![Screenshot 2022-08-22 220706](https://user-images.githubusercontent.com/52681897/186060777-d6b9b504-135d-4d79-a295-decb39d9acf9.png)
![Screenshot 2022-08-22 220739](https://user-images.githubusercontent.com/52681897/186060779-e2859e4d-36e4-4e50-aff8-9001d0041ca5.png)
.

**Comment by YifanWuBambu** [comment]
The detection of extrusion collision is in out plan list.
