### ISSUE TITLE
No BambuStudio in Application Support (Mac)

### ISSUE THREAD

**Issue by inspectorgrowadmin** [bambulab/BambuStudio#1556]
As above. I installed the 'Virtual Camera Tools' after clicking Go Live and it can view the video feed inside BambuStudio but I cannot locate where BambuStudio is? I Checked in the default place as mentioned here: https://wiki.bambulab.com/en/software/bambu-studio/virtual-camera

 - MacOS Ventura 13.2
 - V13.2

**Comment by bambu123** [comment]
It should be there instead of anywhere else.
You can locate the folder from the menu "Help > Configuration Folder".

**Comment by bambu123** [comment]
@inspectorgrowtemp What else can you find in the Configuration Folder?

**Comment by bambu123** [comment]
Closed as no response for a long time.
