### ISSUE TITLE
Non-Default Support Interface not working

### ISSUE THREAD

**Issue by MwC-Trexx** [bambulab/BambuStudio#1558]
**Describe the bug**
When specifying a non-default support interface (Support-W), the specified interface is not being used when the file is sliced.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

[support_interface_issue.3mf.zip](https://github.com/bambulab/BambuStudio/files/11127882/support_interface_issue.3mf.zip)

**To Reproduce**
1. Go to Support option
2. Change Support Interface to Non-Default Value
3. Slice File
4. Support Interface is not respected

**Expected behavior**
Slicer should be using Support Interface

**Screenshots**
Support Setting (with custom interface)

<img width="1223" alt="Screenshot 2023-03-31 at 6 24 32 PM" src="https://user-images.githubusercontent.com/7128246/229249866-4e4be2d8-b8d9-42d4-8061-fd1b802ddb8b.png">

Slicer 
<img width="1546" alt="Screenshot 2023-03-31 at 6 25 12 PM" src="https://user-images.githubusercontent.com/7128246/229249860-c41b8009-3c2b-4178-8c25-8f406b98e838.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX 13.3
 - Version 1.5.0.61

**Comment by MwC-Trexx** [comment]
In experimenting with settings some more, it appears that the value for Support Base is being propagated to Support Interface and not treated as discreet values by the slicer.   

If I set Support Base to Default (AMS #3) and Support Interface to AMS Slot 4 (Support-W), the slicer will set support to default (AMS #3) for both Base & Interface.  

If I set Support Base to AMS #4 (Support-W) and leave Support Interface at default (AMS #3), the slicer sets both base & interface to AMS #4

**Comment by lanewei120** [comment]
hello, thanks for reporting this issue
I just use your 3mf, and confirmed that
if set Support Base to Default (AMS 3) and Support Interface to AMS Slot 4 (Support-W)
the support interface is already set to Support-w(the white filament)

![image](https://user-images.githubusercontent.com/106916061/229333549-53113220-e8b1-44f2-9953-ce663f87c95b.png)
![image](https://user-images.githubusercontent.com/106916061/229333579-998c2a1a-5bf5-4ea0-b698-50e5903bbe90.png)

do you mean anything else?

**Comment by MwC-Trexx** [comment]
It looks like there has been a change in behavior then that isn't really obvious.   

Previously the support interface encompassed all of the support trees, except the base, when the support interface was set to non-default.   

Now it appears that the support interface is ONLY attaching at the the very top connection points of the support tree (at the connection point).  

Is that correct?

**Comment by tangketan** [comment]
I don't quite understand what you mean. By definition, the support interface should only be generated at the top of the tree branches. Would you give an example of "support interface encompassed all of the support trees"?

**Comment by tangketan** [comment]
No reply for a long time. Issued closed.
