### ISSUE TITLE
How to make a mirror model

### ISSUE THREAD

**Issue by DarkDeddok** [bambulab/BambuStudio#1560]
hello friends, I need to make the model a mirror image of the original. tell me how to do it?

**Comment by lanewei120** [comment]
you can find it in the right-click menu

![image](https://user-images.githubusercontent.com/106916061/229333056-8f78b117-b99e-44fe-be6f-867f20a3bab1.png)

**Comment by DarkDeddok** [comment]
oh, thank`s
