### ISSUE TITLE
[Issue - UI, Win 11, 01.01.01.01] - Minor text display issue on "Print Options"

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#157]
When spaghetti detection is not enabled, the greyed out "stop printing..." option has a slight display issue and becomes weirdly pixelated.

![image](https://user-images.githubusercontent.com/63362209/186115247-e7e76e62-8195-42e5-8e5d-833721910b41.png)

When enabled:
![image](https://user-images.githubusercontent.com/63362209/186116654-1533a171-fb54-4b84-9bf6-cff9e0d5d185.png)

**Comment by YifanWuBambu** [comment]
Thanks for report that issue. We will fix it.

**Comment by RobinWhitfield** [comment]
Still present in 01.02.00.04

**Comment by SaltWei** [comment]
Can't see on 1.4 version now
