### ISSUE TITLE
Support only on enforcers not possible

### ISSUE THREAD

**Issue by mrcg** [bambulab/BambuStudio#1575]
**Describe the bug**
With 1.5.0.61 it is not possible to place support material only on position where support enforcers have been painted.
When selecting Support/Type/normal(Manual) the support only on support enhancer should be created.
Independent from auto/manual selection support material is created everywhere which seem to be a bug.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Create support enhancer by "Support Painting" tool.
2. Select Support/Type/normal(manual)
3. Push "Slice aöö"
4. See error: Support material created everywhere but should be only on place with enforcers.

**Expected behavior**
When selecting "Support/Type/normal(Manual)" support material should be only created on enforcer.

**Screenshots**

**Desktop (please complete the following information):**
 - Win11 64bit
 - Version 1.5.0.61

![grafik](https://user-images.githubusercontent.com/4404991/229818202-c0625069-630b-4bd0-99ee-a22ff97ee720.png)
![grafik](https://user-images.githubusercontent.com/4404991/229818432-eb7d33dc-d442-46fc-afa9-c4555eab313a.png)

**Comment by tangketan** [comment]
@mrcg 3mf file please.

**Comment by mrcg** [comment]
After re-installation and resetting all parameters to default the problem is gone.
No idea what was the reason.
I am closing the issue now. Thanks for support.

**Comment by T3chC0wb0y** [comment]
This is still broken on Mac.  As you can see from the image attached, the support enhancer is there but when sliced there is no support.
![Screenshot 2024-01-15 at 11 15 28 PM](https://github.com/bambulab/BambuStudio/assets/68530847/75aeaf3a-f32d-4ec1-ae4f-b0ce1f1196c4)
![Screenshot 2024-01-15 at 11 15 40 PM](https://github.com/bambulab/BambuStudio/assets/68530847/2e3c6a94-abd6-4864-8d4b-2332c0a8d2d0)
![Screenshot 2024-01-15 at 11 16 32 PM](https://github.com/bambulab/BambuStudio/assets/68530847/b5d796a0-4b39-4789-a8b0-e9e33cb3cd36)
