### ISSUE TITLE
Strong Tree supports not working

### ISSUE THREAD

**Issue by seanb9387** [bambulab/BambuStudio#1579]
**Describe the bug**
On the latest release v1.5 the strong tree supports don't appear to do anything, I have had to revert to v1.4.2.
Using the strong tree supports it used to give many more branches and be thicker but now i think nothing happens and just stays as the default tree.

**To Reproduce**
1. Go to support
2. Click on enable support
3. Click on Type
4. Change to Tree(Auto)
5. Click no on the slim message
6. Click on Style
7. Click on Tree Strong
8. Slice

**Expected behavior**
Strong thick supports should show like in the image below

**Screenshots**

V1.4.2
![v1 4 2](https://user-images.githubusercontent.com/129954549/230072199-fdc7b53a-5bbb-412b-bfb6-18286e4ff26e.PNG)

V1.5 Strong Tree
![v1 5 strong tree](https://user-images.githubusercontent.com/129954549/230072191-ec0edd66-c178-4b92-9f03-8d0c72edc7d1.PNG)

V1.5 Defaut tree
![v1 5 tree default](https://user-images.githubusercontent.com/129954549/230072198-680a361f-3999-4758-938e-db747504c176.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by tangketan** [comment]
You are right, the current version makes the two styles very similar. The max radii are different though. We were not sure how people like the strong tree style, and did test it enough. We'll fix it in the next version.

**Comment by seanb9387** [comment]
Thank you. 
 I only use the strong one as every time i use the normal or slim tree it always falls over and fails.
