### ISSUE TITLE
Negative Part Infill FAIL

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#1583]
Im telling the negative part to cut out a section and coloring the bump up section black with another part cause there is no other way to color it and it doesnt see the part
![Screen Shot 2023-04-05 at 5 51 03 PM](https://user-images.githubusercontent.com/48887257/230229158-372d3f66-6474-41ae-9724-f5a2d41cc629.png)
![Screen Shot 2023-04-05 at 5 50 56 PM](https://user-images.githubusercontent.com/48887257/230229167-4d8bc91f-04a8-4406-8bf2-c4ec1458aa8b.png)
[Negative Fail.3mf.zip](https://github.com/bambulab/BambuStudio/files/11163826/Negative.Fail.3mf.zip)

**Comment by lanewei120** [comment]
how about change the black one's type into "modifier" from "part"
and increase the depth of it

**Comment by Benderrodrigu3z** [comment]
so issue found, the slicer doesn't see the black part if the section height is lower then 0.2 on a .4 nozzle, it looks like the Layer height plays a role here, currently set to 0.2
if I lower the layer height to 0.1 then a 0.1 black object prints

**Comment by Benderrodrigu3z** [comment]
![Screen Shot 2023-04-07 at 10 09 32 AM](https://user-images.githubusercontent.com/48887257/230632187-211cd596-75f2-4ac2-a881-c87615250c91.png)


> how about change the black one's type into "modifier" from "part"
> and increase the depth of it

So modifier doesn't work but when the part is set to the same height as the nozzle layer height the part infilled works
![Screen Shot 2023-04-07 at 10 09 32 AM](https://user-images.githubusercontent.com/48887257/230632360-2fcad2db-5c21-4689-9037-24e826456646.png)
