### ISSUE TITLE
Feature: Leave LCD on

### ISSUE THREAD

**Issue by infamous-panda** [bambulab/BambuStudio#159]
Option to leave LCD always on or at least on while printing.  So you can easily see status when your working nearby but can't reach.

**Comment by sodachen22** [comment]
@infamous-panda We have the auto-sleep/auto-turnoff feature extend the lifecycle of LCD. The LCD may be damaged if it displayed the same pattern for a long time.

**Comment by SaltWei** [comment]
> Option to leave LCD always on or at least on while printing

Evaluate to be won't doing. This will shortened lifespan of screen.
