### ISSUE TITLE
Color change not saved 

### ISSUE THREAD

**Issue by dvd77** [bambulab/BambuStudio#1590]
**Describe the bug**
Color / layer changes not saved in project file 

**To Reproduce**
Load STL file.
Click "+" to add a second filament.
Assign filament 1 to an AMS slot
Assign filament 2 to a different AMS slot
Slice
Scroll to layer chosen
Right click on the layer indicator and choose "Change filament" and select filament 2.
Slice again and verify the preview shows 2 colors.
Click "Print plate."
Observe that only one color is visible and available in the preview window, and you cannot assign 2 different AMS slots here.
(If printed, it comes out single-color).
Safe the project file. Then close BS.
When reopening project file the layer information is gone. 

Don't know if this has to do something with this behaviour: when opening a multi color 3mf file in prusa all info is there. When opening this exact same file in BS the information about multicolor/layer change is not there

**Expected behavior**
Layer/color information should be shown  when slicing 

**Desktop (please complete the following information):**
 - OS: MAC
 - Version 1.5.0.61

**Comment by StoneLiBambulab** [comment]
Close this issue as fixed, open a new one if there is any problem.

Thanks!

Stone Li
