### ISSUE TITLE
[Feature Request] 'c' shortcut to be reinstated as per PrusaSlicer/SuperSlicer default to launch the cut tool

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#16]
In PrusaSlicer and SuperSlicer you can use the "c" key as a shortcut to launch the cut option.
In Bambu Studio this option has to be manually selected using the mouse - the shortcut key does not work.

**Comment by wuyifanfancy** [comment]
Thanks for the suggestion. We will add the shortcut key in the recent release.

**Comment by YifanWuBambu** [comment]
It is added in the latest version.
