### ISSUE TITLE
[Feature request] Raft layers

### ISSUE THREAD

**Issue by reify3d** [bambulab/BambuStudio#160]
Please consider to implement a raft layer feature in BambuStudio. This increases the probability of success for prints that have multiple small footprints all over the bed. A brim would not work because:

1. The total surface area covered by the brim is much less compared to a raft
2. The post-processing needed to clean up each individual brim is much higher than just peeling the print off the raft layer

**Comment by YifanWuBambu** [comment]
@reify3d 
Could you share me your model?

**Comment by reify3d** [comment]
The KS backer who experienced this issue is on the Discord, and has been notified.

**Comment by wuyifanfancy** [comment]
Thanks for the information. If possible, please share us the STL or 3MF.
We will add raft feature in the plan list.

**Comment by RobinWhitfield** [comment]
I would also be interested in a raft feature, for very warpy filaments that don't have good bed surface adhesion (specifically POM). 

Combined with the ability to pause and load new filament it would permit say a PLA raft to be used for POM to be printed on top of.

**Comment by finsdotsurf** [comment]
With a raft option I can fit my large fin prints next to each other. Raising the middle object in this screenshot by about 15 layers is all I need. For now, gonna see if I can export a rafted version of it from PrusaSlicer.
<img width="1234" alt="Screen Shot 2022-09-18 at 1 32 23 PM" src="https://user-images.githubusercontent.com/94315133/190927181-05e5120b-12c3-451c-b9ba-91521afb6b6c.png">

**Comment by BATEMAN87** [comment]
I would much like the raft option as it will be best suited for engineering parts. With a raft, elephants foot would be completely eliminated and surface finish would be ideal as opposed to textured build plates

**Comment by YifanWuBambu** [comment]
Raft will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
