### ISSUE TITLE
[Feature request] Manual Layer Height Adjustment

### ISSUE THREAD

**Issue by nhguy2257** [bambulab/BambuStudio#161]
While Adapted Layer Height it great and does the calculations fairly well. I would also enjoy having the option to adjust manually. So the whole print is .2 but layer after a certain height would be .08 for better finish.

**Comment by accetturo** [comment]
Simply3d has an option like this I believe, would be useful for sure

**Comment by nhguy2257** [comment]
> Simply3d has an option like this I believe, would be useful for sure

You can also do it in PrusaSlicer which Bambu is based off off... So hopefully an easy integration.

**Comment by cdsmakestuff** [comment]
I just added another "feature request" for the same idea but a little more descriptive and how it is implemented in PS and SS...
https://github.com/bambulab/BambuStudio/issues/258

**Comment by SaltWei** [comment]
Already support height range. Thanks for suggestions
