### ISSUE TITLE
1st layer Support Object XY Distance not correct

### ISSUE THREAD

**Issue by verityworks** [bambulab/BambuStudio#1610]
When using support, the option for Support/Object XY distance is only respected from the 2nd layer up. Not the first layer.
This results in supports clinging to material it shouldn't be attached on.

Instead of fixing this for the 1st layer, so that all layers are effected by this value, I would add an option to set a different value in the 1st layer.

![image](https://user-images.githubusercontent.com/123553299/232008656-b5abac89-430f-4953-b94f-19890031efcb.png)

**Comment by tangketan** [comment]
Use brim-object gap to control the first layer gap.
![image](https://user-images.githubusercontent.com/13730459/232404888-d3246c02-f66e-48d7-9f5c-1b44983a1d46.png)
