### ISSUE TITLE
Setting Z-Hop to zero or low values causes slicers bugs when used with color changes

### ISSUE THREAD

**Issue by Launert** [bambulab/BambuStudio#1611]
**Describe the bug**
When you set z-hop in spiral mode to <= 0.0001 or in normal mode to zero, the models do not get sliced correctly any longer.
It does not matter if you set it on the printer settings or if you overwrite it in the filament settings.

**3mf File for This Bug**
https://www.thingiverse.com/thing:763622
[3DBenchy.zip](https://github.com/bambulab/BambuStudio/files/11232802/3DBenchy.zip)

**To Reproduce**
1. Go to Printer and nozzle settings
2. Click on Extruder Tab
3. Scroll down to "Z-Hop when retracting"
4. Set Value to 0 in normal mode or <= 0.0001 in spiral mode
5. Go to the color tool and paint the chimney in a different color
6. Slice the model

**Expected behavior**
The model should slice normally without layers hanging in the air and parts of the model missing

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47757241/232046133-863b2f80-962e-4d94-aea3-1c49c369146e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2
 - Bambu Studio: 1.5.0.61

**Comment by DzzD** [comment]
Until they correct this, if you want a workaround, I have used 0.001 with success.

![image](https://user-images.githubusercontent.com/12198339/232300315-f174372b-767a-4651-820a-2ed7fa881ffc.png)

**Comment by SaltWei** [comment]
Already fixed in internal version. And it will be published soon

**Comment by SaltWei** [comment]
v1.6.0 Public Beta has been published
