### ISSUE TITLE
[Feature] Zoom AMS Humidty Indicator

### ISSUE THREAD

**Issue by frasier2k** [bambulab/BambuStudio#1614]
Please show the AMS humdity indicator also in the tool tip window or at least increase the size. There is enough space. The icon is very hard to view.

![AMS Humdity Indicator](https://user-images.githubusercontent.com/74290784/232190023-ef484c5b-f58e-479b-802f-207e3bf12d5f.png)

**Comment by walterwongbbl** [comment]
Hi.
A new version is about to be released, and we have optimized the humidity icon.

**Comment by ArmedLeftist** [comment]
+1

**Comment by gitX14N** [comment]
I really, really want this... my eyesight isn't what it once was, and my printer room has an average humidity in the mid 60s. Staying on top of desiccant in the AMS is important. 

I see that this feature was commented as being "about to be released" on Apr 16th. It's July... any chance you can bump this into the next build? Thanks all.

**Comment by ArmedLeftist** [comment]
Again, yes, I too would (still) really appreciate that. Then I wouldn’t have to leave my 5x magnifying glasses that I use for tying fishing-flies hanging next to my printer. Thank you!
