### ISSUE TITLE
Changing filament is not possible when the support interface is selected

### ISSUE THREAD

**Issue by DokuKaefer** [bambulab/BambuStudio#1615]
As soon as you select something in the support interface, it is no longer possible to change the filament above a certain layer height.

In my opinion, only the layer height in which the support interface is used should be blocked.

![image](https://user-images.githubusercontent.com/11537653/232253377-483f263f-7687-45cc-9d49-5a92c4b45a4f.png)

 - OS: Windows 11
 - Bambu Lab Version 1.5.0.61

**Comment by LiZ-Li-BBL** [comment]
This is a mistake, we're about to fix it

**Comment by PixelKaje** [comment]
Is there an update with this issue? It's still occurring, and prevents me from using any kind of supports on all of my multi-filament prints. Thanks!

**Comment by LiZ-Li-BBL** [comment]
This issue has been fixed, please update your version of BambuStudio to this :
https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.65
