### ISSUE TITLE
[Feature request] Time lapse video suggestion

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1618]
after finishing recording the timelapse, maybe have the print bed rise back up so the camera can capture the entire finished print(or as much as possible)  for an extended period (10 seconds maybe?) currently the recorded video ends too abruptly and you can barely view the completed print. Thanks for listening!

**Comment by randyre** [comment]
This is connected to #1105

**Comment by tangketan** [comment]
We have extended the period of the last frame a bit (3 secs for now) before the bed is lowered down. This will save the video from ending too suddenly. Please wait for the next firmware release.

**Comment by tangketan** [comment]
We have extended the period of the last frame in the latest firmware 1.6. Please take a look.
