### ISSUE TITLE
Adaptive Layer Height doesn't scale Tree support options

### ISSUE THREAD

**Issue by nhguy2257** [bambulab/BambuStudio#162]
While having Adaptive Layer Height enabled, Tree supports will not scale so they fuse with the part and is impossible to remove.

**Comment by tangketan** [comment]
Would you please share the 3mf?

**Comment by nhguy2257** [comment]
[Deathstroke.txt](https://github.com/bambulab/BambuStudio/files/9433080/Deathstroke.txt)


Just rename .3mf

**Comment by tangketan** [comment]
It's a bug in old version. Try the latest version 1.1.1.4, it's fine on my side.

**Comment by nhguy2257** [comment]
> It's a bug in old version. Try the latest version 1.1.1.4, it's fine on my side.

Ok, great... Where is the latest 1.1.1.4? I can not find it anywhere.

**Comment by tangketan** [comment]
@nhguy2257 Sorry for the late reply... I meant the bug was fixed 1.1.1.4, so any version greater than that should be fine.  Try the current latest release （1.3.1.1）.
