### ISSUE TITLE
Support Blocker not working for mirrored .STEP files

### ISSUE THREAD

**Issue by cedmo8** [bambulab/BambuStudio#1621]
If you mirror a step file, neither the support blocker modifier or the support painter work

[Support Issue.zip](https://github.com/bambulab/BambuStudio/files/11245407/Support.Issue.zip)

1. Open .STEP file
2. Mirror it
3. Enable Supports
4. Paint support blocker where there are some auto generated supports
5. Slice

**Expected behavior**
No supports where blocked

**Desktop:**
 - OS: Windows
 - Version 1.5.0.61

**Comment by zhichangxuexi** [comment]
The reason has been found, as shown in the figure, which is the shoe in the left-hand coordinate system
![Uploading image.png…]()
