### ISSUE TITLE
1.6 Beta - Height Range Modifier

### ISSUE THREAD

**Issue by ECKEROTH** [bambulab/BambuStudio#1627]
**Describe the bug**
When adding a Height Range Modifier, it default to filament in slot 1

**To Reproduce**
1. Make a cube with color in slot 2
2. Add height range modifier to cube
3. New height range color is now based on slot 1 instead of inherit from object in slot 2.

**Expected behavior**
Expected new height modifier object to inherit color from object in slot 2.

![image](https://user-images.githubusercontent.com/10584519/232490845-1fc822e6-2fbe-4337-8094-e2d8ece74ab4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Public Beta 1.6.0

**Comment by StoneLiBambulab** [comment]
Hi @ECKEROTH 
Yes, it will be modifed.

Thanks!
Stone Li

**Comment by LiZ-Li-BBL** [comment]
Have been optimized. Height range color has a "default" color based on the object.
