### ISSUE TITLE
vector finesse open back head amame needs maximum length of infill anchor to be set to 0 

### ISSUE THREAD

**Issue by millpreet** [bambulab/BambuStudio#1631]
my post about it.
https://forum.bambulab.com/t/maximum-length-of-infill-anchor/10179/1
![image](https://user-images.githubusercontent.com/16529173/232632764-6982e76d-7d46-47f4-8132-9340cee9e1a9.png)

need maximum length of infill anchor, and other infill anchor feature ideally under advanced setting to properly print open gyroid type prints. prominent example is here.

If not fixed eventually may use my prusa, however prefer to use AMS for multi color, my prusa is single color.

same as this issue in orca issues linked below:
https://github.com/SoftFever/OrcaSlicer/issues/136

**Comment by millpreet** [comment]
![image](https://user-images.githubusercontent.com/16529173/232635451-6e7d9c8c-2d8a-4e0c-99d7-f00f52c292f9.png)
looks like it should be possible, code to implement is still present.

**Comment by SaltWei** [comment]
Reasonable and accept

**Comment by QingZhangBambu** [comment]
we will open that set soon

**Comment by SaltWei** [comment]
Add back from prusa. And avaliable in [v1.7 now](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53) now.
Thank you very much for suggestions!
