### ISSUE TITLE
[v1.6.0 Public Beta BUG] - No more space on SD Card

### ISSUE THREAD

**Issue by Obicom** [bambulab/BambuStudio#1634]
**Describe the bug**
I tried the latest Bambu Studio Public Beta (1.6.0.65) and if I try to send a file to the printer (send to SD card) I get the error message (see attachment) "not enough space on SD card. It is a 512GB SD card and more then 400GB are free. I deleted a lot of files and videos but still the same error message.

**Expected behavior**
I expect that Bambu Studio is able to send a plate to the scard without an error if the sd card has more then 400 GB free space.

**Screenshots**
![image](https://user-images.githubusercontent.com/25134482/232798892-61c6b869-3567-40ac-9b77-a9b2f192a6c4.png)

![image](https://user-images.githubusercontent.com/25134482/232811952-2ce41438-36c4-4d3d-bc37-73a1908d01da.png)

BTW: I exported the 3mf file from bambu Studio and opened with Orca slicer. From Orca Slicer (also 1.6 Beta) no problem to send the same file.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by walterwongbbl** [comment]
Hi. 
Please provide the Studio LOG file when the error occurred.
I will analyze this issue.

**Comment by walterwongbbl** [comment]
Hi.
We found that the error prompt in Studio is not accurate and we optimized the description of printing errors.
This will be greatly improved in the next version
