### ISSUE TITLE
[v1.6.0 Public Beta BUG] - Last button is cut off on Filament/AMS view

### ISSUE THREAD

**Issue by Obicom** [bambulab/BambuStudio#1635]
**Describe the bug**
Last button is cut off on Filament/AMS view (German Language)

**Expected behavior**
All buttons should be full visible

**Screenshots**
![image](https://user-images.githubusercontent.com/25134482/232806082-d394ce11-e239-466d-8793-f68e1be3f4ee.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by Guilouz** [comment]
How do you obtain Ext Spool, my X1C is updated to latest version and latest Bambu Studio too and I don't have it (tested on macOS and Windows).

**Comment by walterwongbbl** [comment]
> How do you obtain Ext Spool? My X1C is updated to latest version and latest Bambu Studio too and I don't have it (tested on macOS and Windows).

![image](https://user-images.githubusercontent.com/120699126/233236575-e0163c48-cda8-47b1-b2ab-9c39a2f2723a.png)
![image](https://user-images.githubusercontent.com/120699126/233236627-2ae0de74-f27f-4c0b-872e-fd2bc012348d.png)

Hi.
Please check your config files and uninstall the old Bambu Studio before installation

**Comment by Guilouz** [comment]
@walterwongbbl Yes it's enabled for my X1C : 

<img width="562" alt="Capture d’écran 2023-04-20 à 11 24 44" src="https://user-images.githubusercontent.com/12702322/233322359-d47c0551-9b76-4b4c-92c9-9e5f5705ffa6.png">

But External spool doesn't appear. I have tested on macOS et on Windows.

**Comment by Guilouz** [comment]
@walterwongbbl I have tried many things, with or without AMS, complete uninstallation of BambuStudio and reinstall without reloading my cloud configuration and same issue, ext spool doesn't appear.

**Comment by walterwongbbl** [comment]
Hi.
Please check the printer screen.  Is there an ext spool present.On the control page of AMS

**Comment by Guilouz** [comment]
@walterwongbbl No i don’t have it and my bambulab is up to date.

**Comment by walterwongbbl** [comment]
Hi.
Does this issue still exist

**Comment by Obicom** [comment]
> Hi. Does this issue still exist

It is still the same ... (1.6.0 Beta 2)
![image](https://github.com/bambulab/BambuStudio/assets/25134482/3bd9a9bd-38dc-44ae-b3ea-21a7ebc5cdd3)

**Comment by walterwongbbl** [comment]
Hi.
We will fix the UI display issues in the German language environment.
This fix will be included in the next version.

**Comment by Guilouz** [comment]
@walterwongbbl This happens with french language too.

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
