### ISSUE TITLE
Login in screen is blank....nowhere to enter credentials...Occurred after latest windows insider preview

### ISSUE THREAD

**Issue by managerman** [bambulab/BambuStudio#1641]
When trying to login, a blank login screen is shown with no place to enter credentials

1. Click on login/Register
2. Blank login screen shows

![IMG_0392](https://user-images.githubusercontent.com/81714048/233058239-503c44d9-9d5c-4a22-8b52-4d91fc7b63fd.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Version 22H2 22624.1610

**Comment by lanewei120** [comment]
sorry for the late reply
we just missed this issue

it should be a network related issue, 
is this issue still there?

**Comment by lanewei120** [comment]
should be network related issue
close it currently
if still has this issue, let's reopen it
