### ISSUE TITLE
live video failing to load on desktop after update to 1.06

### ISSUE THREAD

**Issue by dabido3** [bambulab/BambuStudio#1643]
**Describe the bug**
live video fails to load with [-13] error

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
start print via studio, try to load video

**Expected behavior**
camera should be visible. (it still loads on mobile app)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Version Bambu Studio public beta 1.06.00.65

**Comment by Guilouz** [comment]
Working fine for me on macOS 13.4 Beta 2.

<img width="2560" alt="Capture d’écran 2023-04-19 à 23 01 44" src="https://user-images.githubusercontent.com/12702322/233199227-4a86c3e1-fafc-4b15-a4f6-9dd95faff8ad.png">

**Comment by dabido3** [comment]
something must've just been up on my setup. it resolved itself after a few prints. working fine now
