### ISSUE TITLE
Advanced Connector Cut - Dowel And Hole Size Mismatched If Object Is Scaled Before Cutting (BS 1.6 PB)

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1646]
**Describe the bug**
If an object is scaled before applying the connectors and cutting, the negative hole volume scales with the object, but the dowel does not scale.

**To Reproduce**
1. Add a cylinder primitive to the plate
2. Scale it 150%
3. Apply the dowel modifier to one side of the object
4. Cut the object and notice that the hole is scaled at 150%, but the dowel is still at 100%

**Expected behavior**
Hole and dowel should be the same size

**Screenshots**
Scale a cylinder to 150%
![image](https://user-images.githubusercontent.com/96731892/233398816-2590f370-24e5-4a4f-88db-ac55999de171.png)

Add a 10mm dowel
![image](https://user-images.githubusercontent.com/96731892/233399575-4eb941f7-4128-47d9-b3d4-0cd1185fcc91.png)

Notice the diameter difference between the hole and the dowel
![image](https://user-images.githubusercontent.com/96731892/233400020-75a957c9-adbd-4663-9229-3f6b0dd8b1fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by zhimin-zeng-bambulab** [comment]
It will be fixed in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
You can have a try in the latest version.
