### ISSUE TITLE
Advanced Connector Cut - Rotating An Object Before Cutting Does Not Rotate The Hole Negative Volume (BS 1.6 PB)

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1647]
**Describe the bug**
Rotating an object before placing the connector dowel does not rotate the hole for the dowel.

**To Reproduce**
1. Place a cylinder on the plate and rotate it 90 degrees
2. Place a dowel on the cut surface
3. Perform cut and notice the negative volume for the dowel did not rotate with the object

**Expected behavior**
Hole should conform to the cut surface

**Screenshots**
Place cylinder and rotate it 90 degrees
![image](https://user-images.githubusercontent.com/96731892/233402021-9c169cf1-3f7b-4c6f-958b-9aa3ef4ff3ff.png)

Place a dowel on the cut surface
![image](https://user-images.githubusercontent.com/96731892/233402946-7e6dc014-e54d-4265-8b97-a77fad7c1342.png)

Notice the hole for the dowel is horizontal instead of vertical
![image](https://user-images.githubusercontent.com/96731892/233403824-ed1fa02b-3482-4436-8429-eead05ee942e.png)

![image](https://user-images.githubusercontent.com/96731892/233404181-d7f1bc12-9c38-4b35-a2df-edb43fc53c95.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Bambu Studio 1.6 Public Beta

**Comment by zhimin-zeng-bambulab** [comment]
It will be fixed in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
You can have a tay in the latest version
