### ISSUE TITLE
Bumps on 10-20 degree gentle slopes 

### ISSUE THREAD

**Issue by adrianke77** [bambulab/BambuStudio#1653]
Describe the bug
I was getting bumps on slopes on prints about 10-20 degrees from horizontal, on default 0.08m print settings.

To Reproduce
Print using default settings on a slope about 10 degrees from horizontal, with 15% grid infill.

Expected behavior
No bumps on 10-20 degree from horizontal slopes.

Screenshots
From what I observe, the bumps are due to printing the internal solid infill over the sparse infill (this occurs when printing the internals underneath a gentle slope, and the solid infill edge on every layer is being printed over the edge of the sparse area) and the edge of the solid infill was going 350mm/s over the sparse infill and producing lumps as at this speed the bridging was tattered and broken up.

![229735215-c080bd60-524c-4136-bb3c-07551600c73e](https://user-images.githubusercontent.com/14866712/233764917-b776476c-99a7-4bae-9e85-da66c5bf2625.png)

![229731897-e4417743-8d66-4930-af9f-242b723a14e5](https://user-images.githubusercontent.com/14866712/233764936-d75006a4-dcd5-4b8d-9204-5e7f2126523b.png)

The above photo shows the same 10 degree slope with varying internal solid infill speeds from 175 to 275 mm/s. At 225 and above, the edge of solid infill becoming tattered over the sparse infill produces large clumps that the layers over it (9 layers from profile defaults) fails to cover it. A workaround to avoid the bumps is to set internal solid infill speed to 175mm/s or below, but IMHO the proper fix would be for the slice to recognise the edge of the solid infill over the sparse infill is a bridging situation and should use the bridging speed variable instead.

Printer model
Bambu X1C

Desktop (please complete the following information):
Windows 10

**Comment by QingZhangBambu** [comment]
It is normal for small layer height, you can increase the top shell layers to reduce bumps
