### ISSUE TITLE
Wrong layer number showed on second layer

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#1654]
**Describe the bug**
Small thing but the layer counter in BS and on screen at the second layer says layer 3 instead of 2. Could be a FW issue, also Beta.
...And on the next print it works as it should. Difference between the first and second is the support in the first, what is probably the reason.

 - Windows 11
 - Bambu Studio Beta 1.6.0.65
 - FW printer 1.04.01.14

**Comment by walterwongbbl** [comment]
Hi.
Can you provide relevant screenshots? I don't know which interface displays the layer number.

**Comment by walterwongbbl** [comment]
Hi.
Can you provide 3mf files with incorrect layer numbers.
