### ISSUE TITLE
Setting negative thickness value on text tool crashes Bambu Studio

### ISSUE THREAD

**Issue by totally-tim** [bambulab/BambuStudio#1656]
https://user-images.githubusercontent.com/45621281/233793629-17bc813a-d18d-471b-a5f4-574928ff4939.mp4

As recorded, if you set a negative thickness value and click on a part to attach it, crashes the app.

**Comment by zhimin-zeng-bambulab** [comment]
It will be fixed in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in [V1.7.4](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52)
