### ISSUE TITLE
Beta 1.6: Height range modifier not saved in project / 3mf

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#1657]
**Describe the bug**
When setting the height range modifier and you save the project, the HRM is not saved and disappeared from the object list

**3mf File for This Bug**
added as zip
[kuifjeraket_3mf.zip](https://github.com/bambulab/BambuStudio/files/11302271/kuifjeraket_3mf.zip)

**To Reproduce**
1. set the HRM for the Red_bottom2 from 0 to 7.5 or 8 and the layer height to 0.12
2. save the project
3. new project following by opening the saved project
4. Modifier is gone

**Expected behavior**
Modifier is still there :)

**Screenshots**
HRM is set to the following
![image](https://user-images.githubusercontent.com/53837649/233806605-e8b51e75-0870-4e3f-a9bb-d1efb87a7f73.png)

**Desktop (please complete
e the following information):**
 - Windows 11
 - BS 1.6.0.65

**Comment by StoneLiBambulab** [comment]
fixed in 1.7.2
