### ISSUE TITLE
Beta 1.6: No numbers can be entered

### ISSUE THREAD

**Issue by jngmrks** [bambulab/BambuStudio#1658]
**Describe the bug**
If you try to type numbers while scaling or moving, the view will change according to the hotkeys instead of typing. This affects the numbers 0-6.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 13.3.1 (22E261)

**Comment by LiZ-Li-BBL** [comment]
Fixed this issue. Same as https://github.com/bambulab/BambuStudio/issues/1659
