### ISSUE TITLE
macos key shortcuts going mad

### ISSUE THREAD

**Issue by mifamac** [bambulab/BambuStudio#1659]
Something is wrong with the macOS shortcuts. Its nearly impossible to enter any values in the slicer. If I want to enter 0.4, the slicer switches to the standard view, etc.

German Layout.

macOS 12.6.3
BambuStudio 1.6.0.65

**Comment by LiZ-Li-BBL** [comment]
Thank you for pointing this out. It's certainly a mistake. We're working on it and it will be fixed soon.

**Comment by mct83** [comment]
Here the same Issue. Can't change the color with 1,2,3,4 only with fn key.

Mac M1  macOS 12.6.4
Bambu Beta 1.6.0.65

**Comment by jngmrks** [comment]
Same as #1658

**Comment by LiZ-Li-BBL** [comment]
Fixed this issue.
