### ISSUE TITLE
Fahrenheit options in the Printer and Slicer

### ISSUE THREAD

**Issue by accetturo** [bambulab/BambuStudio#166]
It would be nice to have the ability to change to see fahrenheit on the printer for things like temp controls, chamber temp, bed, etc. I haven't checked the slicer, but it would be nice to have it in slicer as well

**Comment by dereknheiley** [comment]
> It would be nice to have the ability to change to see fahrenheit on the printer for things like temp controls, chamber temp, bed, etc. I haven't checked the slicer, but it would be nice to have it in slicer as well

Honestly curious: does any filament manufacturer provide specs only in fahrenheit?

**Comment by psiberfunk** [comment]
I’m in the USA , and I have never ever thought about printing in Fahrenheit .  I’m not sure what the value of this is ? 3D printing temperatures are always in degrees Celsius

**Comment by SaltWei** [comment]
Evaluated to be won't doing. Please let us known if still necessary.
