### ISSUE TITLE
The desktop is displayed on the right side of the maximized window

### ISSUE THREAD

**Issue by iBral** [bambulab/BambuStudio#1668]
look picture, when you maximized the BambuStudio window, you can see 1 px desktop at the right.

![2023-04-24_210917](https://user-images.githubusercontent.com/44106523/234005904-4dbd93b4-39e2-4e89-9fa6-206582d0c28e.png)

red line is my desktop color

**Comment by bambu123** [comment]
Which platform? Linux?

**Comment by iBral** [comment]
win10

**Comment by bambu123** [comment]
@iBral We can't reproduce it. Is it reproducible on your computer?

**Comment by iBral** [comment]
> @iBral We can't reproduce it. Is it reproducible on your computer?

yes, win10/win11 reproduce it. 
![微信截图_20230512100509](https://github.com/bambulab/BambuStudio/assets/44106523/9872dee4-2047-45c6-a72d-259fa7dfa2c3)

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
