### ISSUE TITLE
Cannot change color of filament in 1.6.0.65 beta, can only use predefined colors (in Device page, AMS spools)

### ISSUE THREAD

**Issue by Majestic7979** [bambulab/BambuStudio#1676]
**Describe the bug**
I am running the 1.6.0.65 and quite upset that you removed the ability to set any RGB color for the filament I am using and sync back to AMS. This is anticonsumerist. You are starting to show your plans to lock down the AMS only to your own filament because you are predetermining the colors that the user can choose and it looks like these colors are all related to your filament. Bambu Lab, this is a 3D printer (shocker!) it's not an Apple laptop. Stop locking it down so much. You already have monopoly on the parts because you can't get proprietary replacement parts except in your store. Sure people can mod nozzles etc but I'd argue most users want to use the original parts and only in your store it's possible to get it. Stop messing with filaments! I want to be able to even use the RFID in the AMS with any NFC tag so I can stick one in every spool and save filament settings to it directly from the AMS. It's really user-unfriendly to remove features that were previously available. So give back the ability to edit the exact color on the Device page for all spools.

**Comment by walterwongbbl** [comment]
Please download and use the latest version of Studio
