### ISSUE TITLE
Bug or by design? Raft by default on some parts on the build plate

### ISSUE THREAD

**Issue by PBZTWS** [bambulab/BambuStudio#1680]
**Describe the bug**
Not sure if this is a bug or by design but regardless when I place objects on the build plate of bamboo studio slicer some have a items have a raft and some do not and there is no way to turn it off for the ones that have one?

It looks like this being done by default but I have to way to turn it off. Anyone seen this? Thanks guys!

**Comment by PBZTWS** [comment]
That fixed it. Thank you!

**Comment by bambu123** [comment]
That's it. Thanks to Jaerin. I will close this issue.
