### ISSUE TITLE
 new version v01.06.00.65-20230417141721 no support is generated at a height of 1 mm

### ISSUE THREAD

**Issue by ctiemann** [bambulab/BambuStudio#1681]
With the new version v01.06.00.65-20230417141721, unfortunately, no support is generated with a height of 1mm.
I print a ring that has a smaller ring of 1mm height inside to glue a small disc there. This support is no longer made and from layer 5 it prints in blank.
The version v01.05.00.61-20230314200047 works fine.
I added an image of v01.05.00.61, for an image with the error of version v01.06.00.65-20230417141721 I would have to reinstall it.

![Screenshot 2023-04-25 163314](https://user-images.githubusercontent.com/61083725/234312335-1114fb1f-10d6-455f-9ea2-4719d1bfd691.png)

![Screenshot 2023-04-25 164146](https://user-images.githubusercontent.com/61083725/234313183-debd1ea3-a11d-4f1b-816b-9609f83ea7ce.png)

**Comment by tangketan** [comment]
Would you please share the 3mf file? I can't reproduce the issue. It seems fine with ordinary 1mm overhangs.
![image](https://user-images.githubusercontent.com/13730459/234520822-a38c8380-a977-4aa3-86cd-41a56be47f66.png)

**Comment by ctiemann** [comment]
Hello Tangketan,
here as requested 3mf-file. On the photo you can see: slict with v01.06.00.65-20230417141721 and support dialed.
The project file and STL file under v01.06.00.65-20230417141721 saved in 3D-Druck.zip also the attachment. Thanks

![Screenshot 2023-04-26 110556](https://user-images.githubusercontent.com/61083725/234527152-7bbbcfe2-e521-46f7-80ed-0902d8e741e0.jpg)

![Screenshot 2023-04-26 110617](https://user-images.githubusercontent.com/61083725/234527162-ae9c759c-1e62-449d-a1a1-f5d71239d61f.jpg)

[3D-Druck.zip](https://github.com/bambulab/BambuStudio/files/11331041/3D-Druck.zip)

**Comment by tangketan** [comment]
Thanks for your sharing. This is caused by the false detection of small overhangs: the ring of overhang is detected as a small overhang and no support is generated. I'll tighten the threshold to fix it.

**Comment by ctiemann** [comment]
Perfect! In version 1.6.2.4 it works fine. Thanks very much!

![Screenshot 2023-05-01 103625](https://user-images.githubusercontent.com/61083725/235429978-9f74c0f9-acc9-4094-a20f-34bd4829064a.png)

**Comment by tangketan** [comment]
Did you use the latest version? It's fine on 1.6.2.4:
![image](https://user-images.githubusercontent.com/13730459/236614581-f797191e-c9cc-42ea-aeb2-8b47f4f82bba.png)

**Comment by tangketan** [comment]
Yes, Lampenfassung_V9.stl is still not right with V1.6.2. I've got a tighter normal support for the next version. Tree supports are better.
![image](https://user-images.githubusercontent.com/13730459/236615157-f8caf978-1ebe-45f2-a700-8ea5b0769f21.png)
![image](https://user-images.githubusercontent.com/13730459/236615209-384311f5-298b-4801-a31b-cb9c4065c528.png)

**Comment by tangketan** [comment]
Both models work on Studio 1.7. Issue closed.
