### ISSUE TITLE
Height Range Modifiers Not Saved in 3mf

### ISSUE THREAD

**Issue by kgearhardt** [bambulab/BambuStudio#1685]
**Describe the bug**
Height Range Modifier settings are not saved in the 3mf file.

**3mf File for This Bug**
File attached for testing 
[test-height-range-modifier.3mf.zip](https://github.com/bambulab/BambuStudio/files/11326967/test-height-range-modifier.3mf.zip)

**To Reproduce**
Select the object and create a Height Range Modifier for a range from 1 to 2mm.  Change the layer height in that range to 0.1mm.  
Save the project.

**Expected behavior**
Restart Bambu Studio and open the previously saved 3mf file.  The Height Range Modifier settings will be gone.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1
 - Bambu Studio 1.6.0.65

**Comment by bolsoncerrado** [comment]
Did you test this in the new 1.6.0 Beta?

**Comment by LiZ-Li-BBL** [comment]
We've fixed this issue.

**Comment by kgearhardt** [comment]
Thank you!Sent from my iPhoneOn May 7, 2023, at 8:23 PM, LiZ-Li-BBL ***@***.***> wrote:﻿
We've fixed this issue.
