### ISSUE TITLE
v1.6.0 Public Beta AMS selection wont let me select generic Silk PLA

### ISSUE THREAD

**Issue by cobyn** [bambulab/BambuStudio#1688]
**Describe the bug**
Generic Silk PLA is no longer an option in AMS filament options

**To Reproduce**
1. Go to 'Device'
2. Click on an AMS Slot
3. Click on Filament DropDown
5. See that there is no option for silk pla filament

**Expected behavior**

**Screenshots**

v1.5.0 Hotfix1
![image](https://user-images.githubusercontent.com/2914460/234594458-08370f51-dc65-4ac6-82f8-bdc3b54cf8e2.png)

v1.6.0 Public Beta
![image](https://user-images.githubusercontent.com/2914460/234593901-877871dd-88ba-4a63-a212-204bd4e27615.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v1.6.0 Public Beta

**Comment by bambu123** [comment]
![image](https://user-images.githubusercontent.com/112537880/235032532-ec0fbe17-9463-488f-9de4-b2c41f002771.png)

Have you selected it here.

**Comment by cobyn** [comment]
> ![image](https://user-images.githubusercontent.com/112537880/235032532-ec0fbe17-9463-488f-9de4-b2c41f002771.png)
> 
> Have you selected it here.

Yes this only effected filament selection of the slicing setting not the AMS

**Comment by bambu123** [comment]
@cobyn Does it exists in filament presets list?
![image](https://user-images.githubusercontent.com/112537880/236720022-b361c636-e68e-473d-b198-3ac6ee9fe576.png)

**Comment by cobyn** [comment]
Yes it shows up in filament section of the slicer, but it not available in the AMS filament type selection. It was available in v1.5

**Comment by StoneLiBambulab** [comment]
this is a bug, the filament preset "Bambu PLA Silk" has the same filament_id with "General PLA Sillk".
the filament_id is the unique id for a filament preset, we will change a filament_did for General PLA Silk.

Thanks！

Stone Li

**Comment by QingZhangBambu** [comment]
we will fix it soon

**Comment by QingZhangBambu** [comment]
That has been fixed on version 1.7, you can update your software to get full functionality.
