### ISSUE TITLE
compiling bambustudio

### ISSUE THREAD

**Issue by JamesCordell** [bambulab/BambuStudio#1696]
I get this error when building the docker image. Not a git repo see last line.

./DockerBuild.sh 
++ id -u
++ id -g
+ docker build -t bambustudio --build-arg USER=user --build-arg UID=1000 --build-arg GID=1000 /home/user/Downloads/BambuStudio-01.06.00.65
Sending build context to Docker daemon    140MB
Step 1/21 : FROM docker.io/ubuntu:20.04
 ---> 88bd68917189
Step 2/21 : LABEL maintainer "DeftDawg "
 ---> Using cache
 ---> 5cfd3e3c4fd4
Step 3/21 : RUN apt-get update &&     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
 ---> Using cache
 ---> 754c0c9b02ca
Step 4/21 : RUN echo deb-src http://archive.ubuntu.com/ubuntu     $(cat /etc/*release | grep VERSION_CODENAME | cut -d= -f2) main universe>> /etc/apt/sources.list
 ---> Using cache
 ---> 60d9716d5b4c
Step 5/21 : RUN apt-get update && apt-get install  -y     autoconf     build-essential     cmake     curl     eglexternalplatform-dev     extra-cmake-modules     file     git     libcairo2-dev     libcurl4-openssl-dev     libdbus-1-dev     libglew-dev     libglu1-mesa-dev     libglu1-mesa-dev     libgstreamer1.0-dev     libgstreamerd-3-dev     libgstreamer-plugins-base1.0-dev     libgstreamer-plugins-good1.0-dev     libgtk-3-dev     libgtk-3-dev     libmspack-dev     libosmesa6-dev     libsecret-1-dev     libsoup2.4-dev     libssl-dev     libudev-dev     libwayland-dev     libwebkit2gtk-4.0-dev     libxkbcommon-dev     locales     locales-all     m4     pkgconf     sudo     wayland-protocols     wget
 ---> Using cache
 ---> 5b57dd3b0413
Step 6/21 : ENV LC_ALL=en_US.utf8
 ---> Using cache
 ---> 6ec224302db0
Step 7/21 : RUN locale-gen $LC_ALL
 ---> Using cache
 ---> c888eb5af999
Step 8/21 : ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
 ---> Using cache
 ---> dc26de6ea73b
Step 9/21 : COPY ./ BambuStudio
 ---> Using cache
 ---> 120ac1fbc4c8
Step 10/21 : WORKDIR BambuStudio
 ---> Using cache
 ---> fd141abdb40f
Step 11/21 : RUN ./BuildLinux.sh -u
 ---> Using cache
 ---> c1bb17d19adc
Step 12/21 : RUN ./BuildLinux.sh -d
 ---> Running in 5d5692f4d11f
FOUND_GTK2=un  libgtk2.0-bin                          (no description available))
[1/9] Updating submodules...
/BambuStudio/resources/profiles /BambuStudio
fatal: not a git repository (or any of the parent directories): .git
The command '/bin/sh -c ./BuildLinux.sh -d' returned a non-zero code: 128

**Desktop (please complete the following information):**
 - OS: debian 11.6

**Comment by lanewei120** [comment]
docker build is provided by [calh](https://github.com/calh) previously

maybe we can require help from [calh](https://github.com/calh)
and also we will check it

**Comment by ghadjig** [comment]
@JamesCordell Had the same issue while trying to build the docker image from the source tar. If you clone the repo everything works fine

```
git clone https://github.com/bambulab/BambuStudio.git
git checkout v01.06.02.04 -b 1.06
./DockerBuild.sh
```

**Comment by lanewei120** [comment]
> I get this error when building the docker image. Not a git repo see last line.
> 
> ./DockerBuild.sh ++ id -u ++ id -g
> 
> * docker build -t bambustudio --build-arg USER=user --build-arg UID=1000 --build-arg GID=1000 /home/user/Downloads/BambuStudio-01.06.00.65
>   Sending build context to Docker daemon    140MB
>   Step 1/21 : FROM docker.io/ubuntu:20.04
>   ---> 88bd68917189
>   Step 2/21 : LABEL maintainer "DeftDawg "
>   ---> Using cache
>   ---> 5cfd3e3c4fd4
>   Step 3/21 : RUN apt-get update &&     echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
>   ---> Using cache
>   ---> 754c0c9b02ca
>   Step 4/21 : RUN echo deb-src http://archive.ubuntu.com/ubuntu     $(cat /etc/*release | grep VERSION_CODENAME | cut -d= -f2) main universe>> /etc/apt/sources.list
>   ---> Using cache
>   ---> 60d9716d5b4c
>   Step 5/21 : RUN apt-get update && apt-get install  -y     autoconf     build-essential     cmake     curl     eglexternalplatform-dev     extra-cmake-modules     file     git     libcairo2-dev     libcurl4-openssl-dev     libdbus-1-dev     libglew-dev     libglu1-mesa-dev     libglu1-mesa-dev     libgstreamer1.0-dev     libgstreamerd-3-dev     libgstreamer-plugins-base1.0-dev     libgstreamer-plugins-good1.0-dev     libgtk-3-dev     libgtk-3-dev     libmspack-dev     libosmesa6-dev     libsecret-1-dev     libsoup2.4-dev     libssl-dev     libudev-dev     libwayland-dev     libwebkit2gtk-4.0-dev     libxkbcommon-dev     locales     locales-all     m4     pkgconf     sudo     wayland-protocols     wget
>   ---> Using cache
>   ---> 5b57dd3b0413
>   Step 6/21 : ENV LC_ALL=en_US.utf8
>   ---> Using cache
>   ---> 6ec224302db0
>   Step 7/21 : RUN locale-gen $LC_ALL
>   ---> Using cache
>   ---> c888eb5af999
>   Step 8/21 : ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
>   ---> Using cache
>   ---> dc26de6ea73b
>   Step 9/21 : COPY ./ BambuStudio
>   ---> Using cache
>   ---> 120ac1fbc4c8
>   Step 10/21 : WORKDIR BambuStudio
>   ---> Using cache
>   ---> fd141abdb40f
>   Step 11/21 : RUN ./BuildLinux.sh -u
>   ---> Using cache
>   ---> c1bb17d19adc
>   Step 12/21 : RUN ./BuildLinux.sh -d
>   ---> Running in 5d5692f4d11f
>   FOUND_GTK2=un  libgtk2.0-bin                          (no description available))
>   [1/9] Updating submodules...
>   /BambuStudio/resources/profiles /BambuStudio
>   fatal: not a git repository (or any of the parent directories): .git
>   The command '/bin/sh -c ./BuildLinux.sh -d' returned a non-zero code: 128
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: debian 11.6

sorry for the late reply

we can also build successfully here
could you also try the linux build commands "./BuildLinux.sh -d" and  check the result?

**Comment by lanewei120** [comment]
@JamesCordell do you still have this issue

**Comment by lanewei120** [comment]
close this issue
if we still have building issue, let's reopen it
