### ISSUE TITLE
Login/register button

### ISSUE THREAD

**Issue by Deymos42** [bambulab/BambuStudio#17]
When i try to login in the home menu for setting up my printer, I only get this pop up:

![image](https://user-images.githubusercontent.com/51133816/179394155-88fcc19d-45d6-4019-814c-26263ba75025.png)

And nothing happend, Someone else happens?

**Comment by RobinWhitfield** [comment]
Have you also installed the plugin from here: https://github.com/bambulab/BambuStudio/releases/tag/v1.0.10 ?

**Comment by wuyifanfancy** [comment]
Just as @RobinWhitfield  said, seems the plugin has not been installed.

**Comment by RobinWhitfield** [comment]
@wuyifanfancy, would it be possible for the software to give a helpful error message to inform the user that the plugin is required, rather than just giving a white box?
