### ISSUE TITLE
Loading .3mf files locks filament colors

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#170]
Load a previously saved project and it won't let me change the filament slots in the AMS to what's currently in the device, just what was loaded when the project was saved.

The expected behavior would be to allow modifications, or even better to ask when loading the project if you want to load the original AMS filament slots (then you could go into the AMS and insert the proper colors) or to ask if you want to use the currently loaded slots.

**Comment by YifanWuBambu** [comment]
@randyre 
Do you mean in the device page or "Send print" dialog? I tried both but did not reproduce this issue.
![image](https://user-images.githubusercontent.com/110661856/187054494-e8d78b6c-5a8f-4611-9b3b-548c543e4c3a.png)
![image](https://user-images.githubusercontent.com/110661856/187054506-fda02d2a-bf0a-4cf0-b843-fd904cf3d0c4.png)

Could you share me your 3mf and give a screenshot where the problem happened? Thanks!

**Comment by randyre** [comment]
The problem appears to be from loading a .3mf file that was saved in another slicer, and it only sees it as Gcode, not as a project file, there is no way to go back to the prepare tab to change things. I must have thought it was a bambu file.
