### ISSUE TITLE
Multi material support layer shift problem

### ISSUE THREAD

**Issue by ByTechLab** [bambulab/BambuStudio#1705]
**Describe the bug**
After switching the "Support interface" to a different material than the "Support base" stragne things happen - missing layers, shifted layers and mirrored layers (see screens below).

**3mf File for This Bug**
[Fan_Stator_Casing_and_Support_With_Supports.zip](https://github.com/bambulab/BambuStudio/files/11359081/Fan_Stator_Casing_and_Support_With_Supports.zip)
[HP_Core_Casing.zip](https://github.com/bambulab/BambuStudio/files/11359069/HP_Core_Casing.zip)

**To Reproduce**
Slice with the same filament for the support base and interface and with different filaments:
![image](https://user-images.githubusercontent.com/15329784/235301255-82930acb-962f-40d3-9a99-a3137ebd286f.png)

**Expected behavior**
The interface material should be placed between the support base and the model. and there should be no gaps in the layers.

**Screenshots**
The same filament for support base and interface:
![image](https://user-images.githubusercontent.com/15329784/235300995-40908542-094f-4fa3-a88c-8b7c5b9032cd.png)

Different filaments:
![image](https://user-images.githubusercontent.com/15329784/235301056-9530f3a8-187d-4210-bba0-25eb479893cd.png)
![image](https://user-images.githubusercontent.com/15329784/235301085-10281667-6714-419f-85fe-5c07fc6b502c.png)
![image](https://user-images.githubusercontent.com/15329784/235301099-15f6af07-ebaf-4d8d-877c-2ce17f8252de.png)

![image](https://user-images.githubusercontent.com/15329784/235301317-a6527bc3-fc4a-4d72-ac26-c32172fda991.png)
![image](https://user-images.githubusercontent.com/15329784/235301349-d4f013f7-b849-4413-9484-4d242bf39032.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
![image](https://user-images.githubusercontent.com/15329784/235301157-3008f9d5-768e-487d-aa31-9458b239b9fa.png)
![image](https://user-images.githubusercontent.com/15329784/235301459-d5c34176-dc1c-4c45-90dd-61c1980d187f.png)

**Comment by ByTechLab** [comment]
It seems to be connected with the "Z hop when retracting" variable.
When set to 0 I have all of the issues described above.
When set to anything else > 0 all issues disappear.

**Comment by tangketan** [comment]
The shifted support interfaced is a fixed bug. Please try the latest version 1.6.2 from the official site. 
The last picture you gave indicates that the thin walls are not sliced correctly. You could try Arachne
![image](https://user-images.githubusercontent.com/13730459/236367694-c02d7b49-d189-4e8d-b547-5ec31630981b.png)
