### ISSUE TITLE
Rotated Text problems at 180deg

### ISSUE THREAD

**Issue by ArmedLeftist** [bambulab/BambuStudio#1706]
**Describe the bug**
嗨 
Painted text applied with Bambu Studio, then rotated to exactly 180deg. That rotation also rotated/flipped some individual letters within the text. All letters as should be at 0 to179 and 181 to 359. Appears to occur with all fonts.

多谢!

**3mf File for This Bug**

![Ride Hard](https://user-images.githubusercontent.com/59338756/235305705-9d35bbdc-05a2-4de4-b692-b9da717b0451.gif)

(replace ".gif" with .".3mf" in file above)

**To Reproduce**
Add text to surface of model
Paint text
Rotate text to 180deg
Do not notice individual letters had "flipped"
Print
Laugh out loud

**Expected behavior**
All letters should maintain proper orientation within rotated text string

**Screenshots**
<img width="523" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/59338756/235305770-78148162-5936-401c-94f9-31b0230c24b9.png">
<img width="929" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/59338756/235305772-6c3b83ea-4b3b-4c5e-a14d-aabcebf7f1dd.png">
<img width="486" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/59338756/235305773-aa66ab70-c37a-475b-a14b-f88f41162589.png">

**Desktop (please complete the following information):**
Mac MiniStudio (Apple Silicon) MacOS 13.3.1
Bambu Studio 1,5,0,61

**Comment by zhimin-zeng-bambulab** [comment]
@ArmedLeftist  Thank you for reporting this issue, we will fix it in the next version.
