### ISSUE TITLE
Too close warning is useless and counter-productive due to constant false positives

### ISSUE THREAD

**Issue by AdrianGarside** [bambulab/BambuStudio#1718]
**Describe the bug**
Get useless warning triggered whenever printing multiple objects. It is doubly useless because it fires when printing multiple objects 'by layer' when there is zero chance of collision. And in this particular case it's triply wrong because the second object is so short there's zero chance of collisions with the print head/rods even if I were printing in 'by object' mode. Given this warning always fires, all it means is that I am being trained to ignore it. So when it could be useful to me, I'll likely miss it.

![image](https://user-images.githubusercontent.com/26147576/235320931-e4ba9227-610e-452c-b09d-8ad5b7d54742.png)
https://www.printables.com/model/404447-flying-night-dragon

**Comment by bambu123** [comment]
You may merge the parts into one object.

**Comment by AdrianGarside** [comment]
> You may merge the parts into one object.

That’s missing the point. I get this error seemingly almost every time I print multiple objects when there is no issue and nothing needs to be changed. So I’m being trained by the software to ignore the error because it’s, in my experience, always wrong.

**Comment by Sangra6969** [comment]
It's a stupid issue and I am getting the same problem. I have an IDEX and it is quite annoying.
