### ISSUE TITLE
Ironing Bug

### ISSUE THREAD

**Issue by moebis** [bambulab/BambuStudio#172]
Ironing simply doesn't work. Either top most or all top surfaces is sporadic. It does some sections and not others. Even tried copying the PS settings at 15% flow rate and 0.1 spacing. See example here: [https://imgur.com/7Mk5Pbx](https://imgur.com/7Mk5Pbx)

**Comment by Cosmo991119** [comment]
could you provide your model?

**Comment by moebis** [comment]
> could you provide your model?

https://www.printables.com/model/51074-fast-operation-vise

**Comment by QingZhangBambu** [comment]
> > could you provide your model?
> 
> https://www.printables.com/model/51074-fast-operation-vise
> 
> also this bug was found on the Mac version.

the problem is solved and would be updated in the next release

**Comment by SaltWei** [comment]
Just bug of gcode viewer. Fixed
