### ISSUE TITLE
Height Range Modifier Layer Indicators Persist Between Project Loads

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1722]
**Describe the bug**
If a height range modifier is applied in a project, the layer indicators persist when creating a new project, or when opening an existing project with no layer height modifers applied. The modifier is not actually applied to the model and clicking on the plate removes the layer plane indicators. It's just a little confusing.

**3mf File for This Bug**
N/A

**To Reproduce**
1. Create a new project and add a cube primitive
2. Apply a height range modifier
3. Now create a new project (don't save existing) and add a cylinder primitive
4. The height range layer planes are applied to the cylinder primitive (although there is no modifier present and the model is not affected).

**Expected behavior**
Height range indicators do not persist between project loads

**Screenshots**
Create a new project, add a primitive and add a height range modifier

![image](https://user-images.githubusercontent.com/96731892/235356841-7e13579f-afc3-4498-854a-0bf29978da2a.png)

Create another new project, (not saving the existing project) and add a cylinder primitive. Layer planes from the previous project show up on the new primitive

![image](https://user-images.githubusercontent.com/96731892/235356970-d5daa461-aa83-4b7c-8eb7-da6a97f43e1d.png)

They also show up on any existing project

![image](https://user-images.githubusercontent.com/96731892/235357111-4141a8eb-e218-41e8-9898-eea485c89c2a.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - 1.6.2.4 Beta 2

**Comment by LiZ-Li-BBL** [comment]
It will behave normally in the next version.
