### ISSUE TITLE
  How Do We Add Information To The Project Screen Now? 1.6.2.4 PB 2

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1723]
**Describe the bug**
You used to be able to add photos, set the cover photo, add pdf’s and links. I don’t see any dialog to add information and dragging photos onto the screen doesn’t do anything.

**To Reproduce**
1. Go to project screen
2. Now what?

**Expected behavior**
Ability to add information

**Screenshots**
![image](https://user-images.githubusercontent.com/96731892/235361305-3377e41e-3aae-42d4-8fd9-b7f5e4087a65.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - 1.6.2.4

**Comment by sisuwest** [comment]
Same issue here on macOS. Worked on previous builds to add photos and instructions.

**Comment by walterwongbbl** [comment]
Hello.
the functions in the project module need to be redesigned and are temporarily unavailable for use.

**Comment by MadMax389** [comment]
Thanks for the update!

**Comment by sisuwest** [comment]
You closed this out, but it's not fixed. Even if they need to be redesigned, there was no need to remove them in this build. You should have kept that functionality in the latest build and then released the new one with another update. I use the Project function quite often and share those files accordingly. Heck, even your winter cabin file from Bambu was done that way a few months ago.

**Comment by sisuwest** [comment]
This is marked as fixed on version 1.7 and yet I still can't use the Project screen. "No Model Information"
