### ISSUE TITLE
Base of support managed by brim settings, not support settings

### ISSUE THREAD

**Issue by bdebyl** [bambulab/BambuStudio#1724]
**Describe the bug**
Adjusting base of supports to object gap has no distinct setting, however is affected by the brim-to-object gap setting though it is not a brim.

**3mf File for This Bug**
Not applicable

**To Reproduce**
1. Import an object that requires supports near it's base
2. Slice (with supports)
3. Adjust brim-to-object gap in **Other** tab
4. Slice and observe change from brim-to-object gap

**Expected behavior**
There should be a specific setting for **support** base to object gap (there is already an xy distance to object setting but this does not change the **base** of the support.

**Screenshots**
![image](https://user-images.githubusercontent.com/7431524/235368302-35ac8abf-a7df-4e95-bfb1-79765ddf9ce8.png)
![image](https://user-images.githubusercontent.com/7431524/235368306-bac2a0c1-0cac-4e64-8080-bf8109af39ec.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Version 1.5.0.60 (or latest)

**Comment by tangketan** [comment]
It's not a bug, but a designed feature. The first layer of the supports are treated as brim, so affected by the brim settings. Can you give an example where this design fails?

**Comment by tangketan** [comment]
No reply in a long time. Closed.
