### ISSUE TITLE
Setting Z-Hop to 0 in either nozzle settings or filament setting override causes mid-air printing 1.5.0.61

### ISSUE THREAD

**Issue by megamaniac** [bambulab/BambuStudio#1725]
To reproduce:

Set Zhop to 0 in nozzle settings
Create primitive on bed with colour - for example colour/filament 1
paint a different colour on the bottom of the primitive in the centre of the bottom not touching edges.
Slice model
Observe second layer of model, it should show layers from both the model and prime tower printing in mid-air.

**Comment by SaltWei** [comment]
Already been fixed in https://github.com/bambulab/BambuStudio/releases/tag/v01.06.02.04.
The OTA version will be released soon as well.

**Comment by SaltWei** [comment]
Please use the latest release
