### ISSUE TITLE
Difference between Release 'Win' vs 'Win Public'

### ISSUE THREAD

**Issue by WanaGo** [bambulab/BambuStudio#1726]
Not a bug, but unsure where else to ask.

What is the diferenece betwen the Win version of the release, vs the Win Public version? Why are there 2 different versions when other OS's only have 1. I cannot find an explanation, and asked on Discord but have received no reply.

Thanks

![image](https://user-images.githubusercontent.com/759846/235391698-cd1ab759-b5cd-4221-810b-524bfbb1c489.png)

**Comment by StoneLiBambulab** [comment]
Hi @WanaGo ,
1. The zip package does not need to be installed and can be run directly, but some features, such as streaming media  may not work well for non-installed versions.
2. The zip package contains symbol files (pdb) that are helpful for debugging some crash problems.

Thanks!
Stone Li
