### ISSUE TITLE
Better shading of pure black filament

### ISSUE THREAD

**Issue by megamaniac** [bambulab/BambuStudio#1727]
When selecting black as filament type, a model becomes very difficult to view, especially when sliced.

It would be great if we could turn the environment lighting up, so that dark filaments are easier to see

Screenshot of black model attached

<img width="742" alt="Screenshot 2023-05-01 at 12 16 11" src="https://user-images.githubusercontent.com/3160986/235444885-50d4b1b0-4d6d-4075-9a88-269ed2574bfc.png">

**Comment by Slimmage** [comment]
I would like to add / comment this becomes especially troublesome when using the write text function - as text displays black as well, and you cannot see it against the surface. white outline on text during placement would solve. thank you

**Comment by Haidiye00** [comment]
Before modification：
![image](https://user-images.githubusercontent.com/132528822/236719186-5eb93367-f090-4ad5-8809-2ec1646caf09.png)
After code modification：
![image](https://user-images.githubusercontent.com/132528822/236719231-330b424a-bce4-4f71-adf7-d1ca1632e6a9.png)

May I ask if you are satisfied with this modification? Looking forward to a reply

**Comment by Haidiye00** [comment]
Please click on the image to open it

**Comment by Haidiye00** [comment]
Version 1.8 will fix this issue
