### ISSUE TITLE
Bambu Studio is not loading any of my custom profiles

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1728]
**Describe the bug**

After upgrading to the latest version, when I open Bambu Studio and select any of the profile lists (filament, print, process) none of the profiles that I created show in the list.

When I use the help menu to open the config directory my profiles are there under user/default just as they should be.

I looked in the debug log and cannot find any entries associated with loading custom profiles.

I would like to know what to try next.

(I also found a couple other issues in the log that I will create separate issues for.)

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by julie777** [comment]
I just had an idea and ran the setup wizard, even though it has been setup for months. Now all my custom profiles are visible again.

Should running the setup wizard be required after every update?

**Comment by MadMax389** [comment]
Usually you just have to log out of Studio, then log back in. As long as auto-sync is selected you should get them back.

![image](https://user-images.githubusercontent.com/96731892/235700956-cbcc2063-17a0-4880-920b-fe53af804f82.png)

**Comment by bambu123** [comment]
From this version, it does not load the default user presets and the login user presets together.

**Comment by bambu123** [comment]
#1840

**Comment by julie777** [comment]
It seems to have been fixed.

**Comment by bambu123** [comment]
OK, thanks.

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
