### ISSUE TITLE
Missing project files remain in the MRU list when not found

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1729]
**Describe the bug**

Bambu Studio tries to open all of the recent projects during startup. 
1. this is not a normal part of startup for an application.
2. I am guessing it is to get the icons to show on the home page. If that is the reason then the icons should be cached along with other such information.

I found this by looking at the log trying to determine the cause of another problem. In addition to the above, when Studio fails to find a recent project it does not remove it from the list. This means that it will try to open the same files and fail every time it is started until every one of those projects has been replaced in the MRU list by another one.

I would expect that you will at least remove files from the MRU list if they cannot be found.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by bambu123** [comment]
Yes, you can remove them manually. But they are kept in case of reattaching removable storage.
