### ISSUE TITLE
Camera misspelled on Device Tab

### ISSUE THREAD

**Issue by Gramps50** [bambulab/BambuStudio#1732]
This is a cosmetic bug and I don't believe it effects he operation of BS.

On the Device Tab at the top of the window that shows live video of the current print job, the upper left hand corner shows
Camer: 
I believe it should read
Camera:

Desktop (please complete the following information):
 - OS: Linux Mint 
 - Version: 21.1 MATE
 - Bambu Studio Version: 1.6.2 beta

**Comment by walterwongbbl** [comment]
Hi.
What language environment is Studio?
Please confirm with the latest version. If the issue still persists, please provide a screenshot.

**Comment by walterwongbbl** [comment]
Hi.
Please use the latest version of Bambus Studio
