### ISSUE TITLE
Non-fatal errors on launch (Linux beta)

### ISSUE THREAD

**Issue by jcorbin** [bambulab/BambuStudio#1735]
Using 1.6.2 (beta 2) fedora app image on arch, but same has been present in earlier betas, and even when I took the time to build my own appimage from git.

The first one is a rather generic "Error running JavaScript: Unsupported result type" alert dialog; console output doesn't seem to have any additional info:
![image](https://user-images.githubusercontent.com/49715/235700074-8b205fb3-e2a7-4fdd-a869-7ef5212e8d80.png)

After dismissing the first one, a second instance presents:
![image](https://user-images.githubusercontent.com/49715/235700470-368ff4f8-e44e-4bfe-90e8-caa2da0e71a4.png)

I'll also sometimes get a "Can't find variable: wxOut0" error, but not on every launch:
![image](https://user-images.githubusercontent.com/49715/235701157-0bd68cb6-792f-4152-9419-752e8e66b8a7.png)

At any rate, bambu studio continues to function correctly after dismissing these errors, so I'm not sure how important they are, or if I'll find something not working eventually

**Comment by bambu123** [comment]
#1701

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
