### ISSUE TITLE
Settings for the height modifier are not saved in the project.

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1741]
**Describe the bug**

When I open a project that had a height modifier set on an object, there is no longer a height modifier.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Select and object and add a height modifier
2. save the project
3. open the project
4. height modifier is gone

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by lanewei120** [comment]
which version are you used when saving the "Height Range"
we just released a new version before ("https://github.com/bambulab/BambuStudio/releases/tag/v01.06.02.04"?)
it should fixed this issue

**Comment by julie777** [comment]
@lanewei120 I was probably still using 1.6.0.65
