### ISSUE TITLE
[Left Clicking OFF Model Exits Paint Mode ALSO Changing Settings Inadvertently Exits Paint Mode because of this.] Exiting Paint Mode Accidentally and Often

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#1747]
In the newest 1.6.2.4, the program now inadvertently and often exits paint mode when the user single left clicks off the model OR due to this new behavior, changing settings sliders seems to read a click or mouseup off the model as well, and Exit the user from paint mode inadvertently as well. I have only been painting for a few minutes and I've been kicked out of paint mode at least 10 times. The old behavior was better, where escape exiting paint mode, or add a button to exit.

**Comment by Haidiye00** [comment]
The latest version V1.9 Beta 3 has resolved this issue. Please download and use it,thanks
