### ISSUE TITLE
[Feature Request] Implement interface shells option 

### ISSUE THREAD

**Issue by GuyH77** [bambulab/BambuStudio#175]
Please implement the interface shells option as found in Prusaslicer. This option ensures a smooth top interface layer, which improves print quality and also strength. This setting is used when printing multi-colour. 

![image](https://user-images.githubusercontent.com/106596720/187067972-72af69ce-90cf-4d6c-a511-c221d559213e.png)

In this example. A door sign. The top layer would benefit massively from a single monotonic layer and not lots of regions.
![image](https://user-images.githubusercontent.com/106596720/187068042-345d2af2-2452-4091-b0b9-6ce1c1acbe73.png)
next layer
![image](https://user-images.githubusercontent.com/106596720/187068057-697c1725-6920-401e-88c8-c96187ad760a.png)

Here is a recent print showing the issue I hope to remove with this feature request. The 'scars' on the top surface detract from the quality of the print/sign.

![image](https://user-images.githubusercontent.com/106596720/189713562-c1f99077-ce47-427e-bfee-553cc0797985.jpeg)

![image](https://user-images.githubusercontent.com/106596720/189713660-5a11fed1-29a4-4982-beba-aca444098cdf.jpeg)

**Comment by GuyH77** [comment]
This really needs adding, this is a simple QR sign and the base should just be an easy print. It doesn't need this interface layer.

![image](https://user-images.githubusercontent.com/106596720/190501786-7d7fe397-c4e3-4f25-ae19-c3e14a27454a.png)

**Comment by GuyH77** [comment]
@YifanWuBambu any chance of this been added? Prusaslicer has this function and it makes such a difference to surface quality. Another example. This top layer doesn't need the gaps, it degrades the surface finish and I'm sure is slower. Any filament saved it negligible. I just need the option to ensure the best quality possible. 

![image](https://github.com/bambulab/BambuStudio/assets/106596720/e6b74833-51c9-4b9f-b49e-413226be1d73)
![image](https://github.com/bambulab/BambuStudio/assets/106596720/cfdf72e8-8d28-4c95-84de-3a98e8d1e7b7)

**Comment by SaltWei** [comment]
@BambooBugFixer Please add back this option in 1.8 version

**Comment by GuyH77** [comment]
@SaltWei I don't see this in the new 1.8 beta? Please, this function will make my signs look so much better.

**Comment by SaltWei** [comment]
@QingZhangBambu Please keep following this ticket

**Comment by GuyH77** [comment]
Will this make it in to 1.8? It's not in Beta 3. I really need this functionality. Also, now you have the makerworld signs addon it will be better with this function. Please let me know if I can help test. Thanks.

**Comment by GuyH77** [comment]
Still not fixed in 1.9 Beta.

**Comment by SaltWei** [comment]
@QingZhangBambu @XunZhangBambu Please don't forget to add this in next beta

**Comment by XunZhangBambu** [comment]
this option has been implemented , discussion under #2906
