### ISSUE TITLE
GCode Path Error because of Collision

### ISSUE THREAD

**Issue by Nosnbora** [bambulab/BambuStudio#1760]
Because Bambu Studio has no Option for Support Brim I used a flat Cylinder on which the Tree Support is printed. 
This is technically a collision because the Support is printed inside the cylinder, but in real life, it works fine. 

Now with the new version of Bambu, you took that option from me because I get the Error "Conflicts of gcode paths have been found at layer 0" and I can't print it. And also you still didn't add the support brim feature. Like WTF Bambu Lab? Are you working against the Customer?

Please fix this mess. Don't try to make everything too safe... it makes things worse sometimes. 
<img width="1488" alt="bug" src="https://user-images.githubusercontent.com/130871163/236558049-c6c6ea5a-b0bb-4f2b-9516-ff2f324691a8.PNG">

**Comment by nahashrishon** [comment]
I'm also having this issue with my files. Keep getting the conflict at layer 0 z height 0.00mm.

reduced it down to the first layer and everything seems fine 
![image](https://user-images.githubusercontent.com/66189281/236982074-87988154-2899-41e2-89ab-9b164aa40cab.png)

if I delete all the objects but one and then slice it, still gives me the above error but allows me to print

![image](https://user-images.githubusercontent.com/66189281/236982209-c68ffbdb-e935-4223-a1d5-e1abd45bc712.png)

faulty file is attached 
[unchecked.zip](https://github.com/bambulab/BambuStudio/files/11426773/unchecked.zip)

**Comment by pstagman** [comment]
I'm getting this same ERROR from a file that's been working perfectly for months. Ince upgrading to Studio V 1.6.2.4

![Clipboard01](https://github.com/bambulab/BambuStudio/assets/84526537/3c843687-e3a5-405c-9d56-6aa349fd0be1)

**Comment by tangketan** [comment]
@nahashrishon If you look closely you'll see there are indeed path conflicts for multiple copies. If you remove all except one, the conflicts are gone, and you may notice the "Print Plate" button is back. It's just the message didn't disappear, which is a bug and we'll fix it in the next version.
![image](https://github.com/bambulab/BambuStudio/assets/13730459/7e275f28-c55c-4318-932a-055a661d9720)

Besides, I agree that the conflicts of support paths aren't as severe as that of object paths. In the next version, we have increased the threshold to allow a larger amount of support path conflicts.

**Comment by tangketan** [comment]
@Nosnbora @pstagman Please share your 3mf files so I can tell if it's a bug or not. Most of the time there are indeed path conflicts, maybe too small to notice.

**Comment by magic-happenz** [comment]
@tangketan its actually quite simple to reproduce. Simply make a cube with cylinders at the corners and you will see. I would also love to share a 3mf file with the same which ultimately fails to slice in a way you can print it but you can not share files here. If you can not reproduce please propose a way to share the file.
![image](https://github.com/bambulab/BambuStudio/assets/63111919/acf35ef9-1aba-4b32-aa0d-96954bf4c31b)

I remember in an earlier version it sliced it like in [this](https://github.com/bambulab/BambuStudio/issues/1393) feature request.
If the request is not going to worked on soon it would be great to at least allow again to print these overlaps.

**Comment by clowrey** [comment]
There NEEDS to be an override for this "error" or just convert it back to a warning!!! I cannot print a model that has overlaps on purpose with another model - it prints fine and is intentional!! - I have to revert to the previous version to print this file! please either provide an over-ride check box somewhere in the settings or just make this a warning instead of hard error that prevents printing! 
Thanks :)

**Comment by tangketan** [comment]
We understand your needs and have changed the error to a strong warning in the latest Studio 1.7. 
![image](https://github.com/bambulab/BambuStudio/assets/13730459/8eafa993-26a1-49c7-8f03-5f8d366ff510)

**Comment by terryb58** [comment]
This is not true for 1.7.7.89. As a matter of fact, it is much worse now. Printing flat objects that the hot end would not collide with still need a wide margin. See images. 
![BambuPic1](https://github.com/bambulab/BambuStudio/assets/9091131/c8c58ef2-9eb6-4f8e-9eb0-c3ac132afb09)
![BambuPic2](https://github.com/bambulab/BambuStudio/assets/9091131/0760fd3e-d802-41fc-a8b5-269a2b84879a)

It should be possible to print them this close and still be in no danger of the hot end colliding with the models.
![BambuPic3](https://github.com/bambulab/BambuStudio/assets/9091131/3ec8cb09-8f88-4398-803d-38738f625636)
