### ISSUE TITLE
Bambu Studio doesn't actually reach edges of the screen

### ISSUE THREAD

**Issue by zswickliffe** [bambulab/BambuStudio#1761]
**Describe the bug**
When in full screen, the program leaves gaps around the edges where the desktop is clearly visible.

**3mf File for This Bug**
N/A

**To Reproduce**
1. Open Bambu Studio
2. Click "maximize window"
3. See the gaps surrounding the program window

**Expected behavior**
I would expect the program to reach the extents of windows when maximized.

**Screenshots**
On my main monitor, there are gaps on all sides: 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/109188401/236558053-2b5fda52-8a5c-4223-b713-39f7d9a0a60a.png">

On my secondary monitor, it only gaps on the right side (the shared side between the monitors):
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/109188401/236558687-681df46c-1bf8-4c38-b3c9-a147a6cba887.png">

My monitor configuration:
Main monitor: 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/109188401/236558588-ed21cb3d-9ef4-4dae-a523-4bd02ac51b9f.png">
Secondary monitor:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/109188401/236558620-b3705d55-ebb1-4c7b-91f1-d94105d9085d.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Dual monitor setup, the main monitor is 3840 x 2160, the secondary monitor is 2560 x 1440. Screenshots of their configuration above.
 - Version	10.0.22621 Build 22621

**Comment by bambu123** [comment]
#1668

**Comment by cmguo** [comment]
@zswickliffe
We can't reproduce it here.
Could you please show me the window size value in the config file?
The config file can be located from the menu "Help > Show Configuration folder".
Make sure to minimax the window and close Bambu Studio before reading values from the config file.

![image](https://github.com/bambulab/BambuStudio/assets/46235824/85099a31-183e-4b04-bf8b-1604ec9fc59f)

**Comment by bambu123** [comment]
@zswickliffe
We can't reproduce it here.
Could you please show me the window size value in the config file?
The config file can be located from the menu "Help > Show Configuration folder".
Make sure to minimax the window and close Bambu Studio before reading values from the config file.

[image](https://user-images.githubusercontent.com/46235824/238252731-85099a31-183e-4b04-bf8b-1604ec9fc59f.png)

**Comment by zswickliffe** [comment]
@bambu123 sure thing:

On my main monitor (4k):
<img width="274" alt="image" src="https://github.com/bambulab/BambuStudio/assets/109188401/4ec9b7c6-6fc9-453b-aa10-7d800d880d31">

On my secondary monitor (1440p):
<img width="291" alt="image" src="https://github.com/bambulab/BambuStudio/assets/109188401/00181284-ad53-4230-a59f-4c867bcaa0b4">

**Comment by zswickliffe** [comment]
@bambu123 need anything else from me?

**Comment by bambu123** [comment]
No, thank you. We will fix it in the next version.

**Comment by only1chip** [comment]
I have a related problem.  When I launch Bambu Studio on my triple-monitor setup (all screens are portrait (@ 1080 wide) - the max width to which the BStudio window will stretch is 1080px.  Changes to the "window_mainframe" values in conf file don't seem to have any effect.  The only solution I've found is temporarily setting one of my screens to landscape while I launch BS.  Then I can revert my monitor settings for portrait, and the BS window will scale to a more convenient size (ie a size where all the window components are visible without horizontal scrolling).  Running BS ver 1.8.4.51 on Win 10 Pro 10.0.1.19045
