### ISSUE TITLE
Cubic infill have layer gaps

### ISSUE THREAD

**Issue by DzzD** [bambulab/BambuStudio#1768]
It seems that now, maybe due to latest release of the studio, there is empty line, at least on cubic infill.

Here are screenshot of cubic inifill : 

![image](https://user-images.githubusercontent.com/12198339/236668717-ea1d2119-fa7f-4859-b4df-051b8a792798.png)

**To reproduce :** 
On Bambu Studio, add primitive cube, set its infill to cubic 20%

**Comment by QingZhangBambu** [comment]
It concerned how  GCodeviewer draw the shape of the line. The printing artifact is fine.
![20230609-162345](https://github.com/bambulab/BambuStudio/assets/112676417/8e4a8ab2-b100-4022-b8f1-4ee5a6ef6adf)

**Comment by DzzD** [comment]
Ok I ll check that, but why it happen only for cubic infill and why now ?

**Comment by DzzD** [comment]
I can confirm that the print is ok, but still disappointing that the preview is not as good as for other infill
