### ISSUE TITLE
Bambu studio 16.2.4 broke Support Tree hybrid option

### ISSUE THREAD

**Issue by AlxSZP** [bambulab/BambuStudio#1769]
**Describe the bug**
When selecting the option to add supports. Either Tree (Auto) -> Default or Tree (Auto) -> Tree Hybrid and proceed to slice the model, the output will have "Normal" supports vs tree supports.

Other options like tree slim and tree strong work as expected 

**3mf File for This Bug**
Attached the file tested
[Controller Tower Tall.zip](https://github.com/bambulab/BambuStudio/files/11415561/Controller.Tower.Tall.zip)

**To Reproduce**
1. Go to 'Supports'
2. Click on 'tree (auto)'
3. Scroll down to 'Style'
4. Leave the Default option or select Tree Hybrid
5. The sliced model will have normal supports instead of tree supports

**Expected behavior**
Tree Hybrid supports should be displayed on the preview screen after the model's been sliced

**Screenshots**
![Screenshot 2023-05-07 at 12 33 24 PM](https://user-images.githubusercontent.com/76796365/236690740-1dc6539c-0d6e-40f0-83b8-21c22f048b99.png)

**Desktop (please complete the following information):**
- System: Apple Mac mini - Apple M2 Pro | 32GB
 - OS: [macOS]
 - Version [Ventura 13.3.1 (a)]

**Comment by tangketan** [comment]
This is tree hybrid, which has normal nodes under large flat overhang surfaces. You can check our [wiki page](https://wiki.bambulab.com/en/software/bambu-studio/support) for details.
