### ISSUE TITLE
Use Purge Tower for Time Lapses

### ISSUE THREAD

**Issue by kritoke** [bambulab/BambuStudio#178]
If doing multi-material printing, the time lapse tower shouldn't be needed since you already have a tower moving the print head away for the purge tower (if enabled).  If need be, even have it auto orientate itself to where the time lapse tower would have been.  Seems to be a bit of a waste of filament in its current state.

**Comment by YifanWuBambu** [comment]
Yes. We have optimize this and it will be our next release.

**Comment by YifanWuBambu** [comment]
Optimized in v1.2.
