### ISSUE TITLE
Error message on Ubuntu 23.04: Error running JavaScript: Unsupported result type

### ISSUE THREAD

**Issue by mzanetti** [bambulab/BambuStudio#1782]
Ever since I've upgraded to Ubuntu 23.04, launching Bambu Studio produces a popup with this error message twice:

Error running JavaScript: Unsupported result type

It doesn't seem to actually break anything tho, at least I haven't come across something related yet.

**To Reproduce**
1. Install Ubuntu 23.04
2. Download latest Bambu Studio Ubuntu AppImage
3. Make executable and launch

**Screenshots**
![image](https://user-images.githubusercontent.com/102573/237041961-695b1e6c-1660-47d8-8f6f-242abc4c46d8.png)

**Desktop:**
 - OS: Ubuntu
 - 23.04 lunar

**Comment by bambu123** [comment]
Same As #1701

**Comment by mzanetti** [comment]
Fwiw, this seems to have gone with the latest public beta version. There's only a fedora AppImage, but it runs fine on Ubuntu 23.04 and this error message is gone.

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
