### ISSUE TITLE
Sync AMS Settings via cloud

### ISSUE THREAD

**Issue by Lesani** [bambulab/BambuStudio#1784]
**Is your feature request related to a problem? Please describe.**
My printer lives on a different LAN than the PC I work from. I can print directly via the cloud service, but when I prepare a file I cannot sync my AMS settings, as this only works when the printer has a direct IP connection on the same network. The Live-Camera DOES work via the cloud, so I think syncing AMS should not be that difficult?

![image](https://user-images.githubusercontent.com/5182104/237046076-77bfbe43-10b4-41cf-a0d2-890d144f11b3.png)
![image](https://user-images.githubusercontent.com/5182104/237046383-e4919e89-2e40-4c87-90e3-6af60a9c50f2.png)

**Describe the solution you'd like**
Enable syncing AMS settings when not on same LAN

**Describe alternatives you've considered**
I have no alternative, I cannot get on the same LAN (large industrial company, not home user)

**Additional context**

**Comment by Lesani** [comment]
since it contains machine and personal identification data, I have sent the file to the e-mail address in your profile @bambu123

**Comment by bambu123** [comment]
Got it, thank you!

**Comment by walterwongbbl** [comment]
Hi.
Will the studio continue to be unable to connect to the server.
In non-LAN mode, printer data is transmitted through the cloud. If prompted as failed to connect to the server. Unable to retrieve printer data.

**Comment by walterwongbbl** [comment]
Hi.
How has the recent usage been? Is everything running smoothly?

**Comment by walterwongbbl** [comment]
Please use the latest version of Bambu Studio.
