### ISSUE TITLE
Bambu Studio crash when using raft with small rounded surfaces

### ISSUE THREAD

**Issue by pedro-pedrosa** [bambulab/BambuStudio#1786]
**Describe the bug**
When using a raft with 0.08mm default preset and a small model with rounded bottom surface, bambu studio crashes on the slicing operation.

**To Reproduce**
1. Select 0.08mm default preset
2. Add a cylinder or shpere primitive
3. Scale object down to 5x5x5
4. Add raft of 1 layer
5. Slice

**Expected behavior**
Expected to slide successfully. Instead, I get either a "bad alloc" error or the program completely crashes.

**Desktop (please complete the following information):**
 - Ubuntu 22.04.2 LTS

**Comment by tangketan** [comment]
Thanks for reporting the bug. I'll fix it in the next version.

**Comment by KiwiDamo** [comment]
Can confirm this problem also exists in the Windows version.

**Comment by Laess3r** [comment]
Also confirm this crash on Windows version. Very annoying, as tiny objects must be print using raft - which is not possible 👎🏻

**Comment by NicGibbens** [comment]
Also happens with Mac version.

**Comment by pedro-pedrosa** [comment]
apparently a work around is to add normal(manual) supports to the object. this prevents the crash

**Comment by tangketan** [comment]
The latest beta should have fixed this issue. Please take a try.

**Comment by NicGibbens** [comment]
Now working on Mac using the latest Beta - many thanks!!
