### ISSUE TITLE
Slicer Crash without saving cant restore

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#1789]
get any object
turn off cut to parts, turn off upper part, turn cut to parts back on, perform cut, and crash
bug report pops up on Mac but no restore option

**Comment by Benderrodrigu3z** [comment]
cut to parts needs to override the After Cut parts field not just gray it out, its still active in the foreground if I can make this image, or auto recheck them when you click Cut to Parts

![Screen Shot 2023-05-10 at 10 51 34 AM](https://github.com/bambulab/BambuStudio/assets/48887257/23198fad-429c-40d5-b0d4-8b81bdf2ad2b)

**Comment by zhimin-zeng-bambulab** [comment]
Thanks! we will fix it the next version.

**Comment by zhimin-zeng-bambulab** [comment]
[V1.7.4](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52)
