### ISSUE TITLE
P1P Network Connectivity...

### ISSUE THREAD

**Issue by rashuge** [bambulab/BambuStudio#1795]
I have been using my P1P for about a month now.  My home network is a Eero Pro 6e+ and my network is very stable.  I do monitor on many points and with many capabilities.  I have a DHCP reservation currently setup for P1P on my network.  I am constantly losing connectivity with my machines accessing the printer from Bambu Studio. Bambu Handy doesn't seem to be an issue.  I often times have to close down the studio app and reopen it to re-establish a connection. I am running the newest available firmware (01.02.03.00) on the printer and am running studio version 1.6.2.4.  The device isn't losing connectivity to the network, it is the studio.  I get the not connected dialog that comes up asking to verify the password and the passcode.

**Comment by walterwongbbl** [comment]
Hi.
Please use the latest version of Bambu Studio.
