### ISSUE TITLE
Bambu Studio 1.6.2.4 not launching after update

### ISSUE THREAD

**Issue by jimi0303** [bambulab/BambuStudio#1799]
Hello!

I got a prompt to update the Bambu Studio software on my Windows 11 computer. The update completed successfully, but since then the program won't start. It just hangs on a grey screen with a white top bar, with the windows mouse loading icon circling forever, until I force close it.

Here is what is displays:

![image](https://github.com/bambulab/BambuStudio/assets/54041410/38dfb809-f3d2-4a02-98c6-1da34830d585)

I don't know if it's related, but it also can't display the launch screen properly, most of the bottom text is missing:

![image](https://github.com/bambulab/BambuStudio/assets/54041410/030847c2-685b-4c95-b142-ae93b1db4cd5)

Rebooting the computer didn't do anything. [I've seen one other issue just like this on GitHub already](https://github.com/bambulab/BambuStudio/issues/1770), so I went and renamed the BambuStudio folder in AppData, which also didn't help.

I use this machine for work, so I'd really like to get it working again. Any help is appreciated.

**Comment by bambu123** [comment]
Please send us the logs from “%APPDATA%/BambuStudio".

Whenever it is locking, please use the Windows Task Manager to create the minidump of BambuStudio, the dump is useful to analyze the hung problem and please send it to us.

**Comment by bambu123** [comment]
You can create minidump with the following steps:

Open the Windows Task Manager
Find and select the Bambu Studio process in it
Right click the process and choose the 'Create Minidump File' menu item
Select a folder to save the file

**Comment by bambu123** [comment]
@jimi0303 Are you still facing this issue? Please help make a minidump if yes.

**Comment by Bukaro21** [comment]
@bambu123 I have the exact same issue with bambu studio opening but staying white and getting a "BambuStudio is not responding" message from Windows until I force close it. I created a minidump and uploaded it to WeTransfer as it was too big to attach here: https://we.tl/t-uU9fRJ3KDe

**Comment by bambu123** [comment]
> @bambu123 I have the exact same issue with bambu studio opening but staying white and getting a "BambuStudio is not responding" message from Windows until I force close it. I created a minidump and uploaded it to WeTransfer as it was too big to attach here: https://we.tl/t-uU9fRJ3KDe

Great thanks. I will check it.

**Comment by bambu123** [comment]
> @bambu123 I have the exact same issue with bambu studio opening but staying white and getting a "BambuStudio is not responding" message from Windows until I force close it. I created a minidump and uploaded it to WeTransfer as it was too big to attach here: https://we.tl/t-uU9fRJ3KDe

Are you openning a 3mf file or starting Bambu Studio directly without 3mf file?
Please provide the app logs to us, which can be found from the menu "Help > Open Configuration Folder".

**Comment by Bukaro21** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/137054589/9657b746-7b65-4688-bfbc-67ca2abd9b80)
![image](https://github.com/bambulab/BambuStudio/assets/137054589/575e769e-036e-42cb-b7a6-af3e7444cb34)
![image](https://github.com/bambulab/BambuStudio/assets/137054589/45d19f3a-1eae-44ab-a31d-15c8b18a93d6)

[log.zip](https://github.com/bambulab/BambuStudio/files/11787046/log.zip)

Here are screenshots and a zip of all logfiles I have. I am trying to open Bambu Studio directly without a 3mf file

**Comment by Bukaro21** [comment]
@bambu123 It seems to have to do with multi monitors. Once I disabled my other monitors Bambu Studio started fine

**Comment by Braindea7** [comment]
> @bambu123 It seems to have to do with multi monitors. Once I disabled my other monitors Bambu Studio started fine

I can confirm this. It seems like the problem arises when the program crashes or the internet connection gets lost on a display other than the main display.

Disconnected the non main displays, start the studio and reconnect the displays. Everything fine again.

**Comment by Gili-Omri** [comment]
@bambu21 

Good call

Same issue, on Windows 10, worked fine yesterday, problem started today
disconnecting all displays but main , solves the issue

any idea how will the fix take?

**Comment by bambu123** [comment]
> Whenever it is locking, please use the Windows Task Manager to create the minidump of BambuStudio, the dump is useful to analyze the hung problem and please send it to us.

Whenever it is locking, please use the Windows Task Manager to create the minidump of BambuStudio, the dump is useful to analyze the hung problem and please send it to us.

You can create minidump with the following steps:

Open the Windows Task Manager
Find and select the Bambu Studio process in it
Right click the process and choose the 'Create Minidump File' menu item
Select a folder to save the file

**Comment by bambu123** [comment]
> @bambu21
> 
> Good call
> 
> Same issue, on Windows 10, worked fine yesterday, problem started today disconnecting all displays but main , solves the issue
> 
> any idea how will the fix take?

Your two screens may have different scale ratios. We found it relevant to scale change.
We are trying to fix it. Setting the same scale ratio may avoid this issue currently.

**Comment by bambu123** [comment]
@jimi0303
The new version 1.7 was released. 
Please help to see if this problem is solved.

**Comment by jimi0303** [comment]
Hello @bambu123 !

Thank you for the follow-up. After my initial report I deleted everything related to Bambu Studio on my computer and reinstalled it from scratch. This solved the issue for me and the problem hasn't resurfaced since.

**Comment by cmguo** [comment]
@Gili-Omri @Braindea7 @Bukaro21 
Please help to see if this problem is solved in the new version 1.7.

**Comment by bambu123** [comment]
@Gili-Omri @Braindea7 @Bukaro21
Please help to see if this problem is solved in the new version 1.7.

**Comment by Alamin-sajib** [comment]
> @Gili-Omri @Braindea7 @Bukaro21 Please help to see if this problem is solved in the new version 1.7.

Same issue in latest v1.7 release.

**Comment by bambu123** [comment]
> > @Gili-Omri @Braindea7 @Bukaro21 Please help to see if this problem is solved in the new version 1.7.
> 
> Same issue in latest v1.7 release.

Please provide all the logs.

**Comment by mverch67** [comment]
This issue happens also in version 1.7.6.

When the window size on the second monitor is bigger than on the main monitor is will crash, e.g. when doing a maximize window or resizing and exceeding resolution of the main monitor.

**Comment by DanBao-Bambu** [comment]
@mverch67 @Alamin-sajib 
I need your log and minidump files. Additionally, I can try to see if v1.8 has resolved this issue. The v1.8 log and minidump files are user-friendly for my debugging.

>You can create minidump with the following steps:

>Open the Windows Task Manager
Find and select the Bambu Studio process in it
Right click the process and choose the 'Create Minidump File' menu item
Select a folder to save the file

Thank you very much

**Comment by mverch67** [comment]
> @mverch67 @Alamin-sajib I need your log and minidump files. Additionally, I can try to see if v1.8 has resolved this issue. The v1.8 log and minidump files are user-friendly for my debugging.
> 
> > You can create minidump with the following steps:
> 
> > Open the Windows Task Manager
> > Find and select the Bambu Studio process in it
> > Right click the process and choose the 'Create Minidump File' menu item
> > Select a folder to save the file
> 
> Thank you very much

Yes, this issue is resolved in v1.8, no more problems, thanks!
