### ISSUE TITLE
[Bug] Unable to "detect thin walls" when wall continuity is broken. 

### ISSUE THREAD

**Issue by thrutheframe** [bambulab/BambuStudio#18]
Version: Pre-release Windows 01.00.10.05

Settings: 
Printer - Bambu Lab X1 Carbon 0.4 nozzle
Process - 0.20mm Standard @BBL X1C
Walls - Wall loops =3 and "Detect thin walls" enabled

Issue: when slicing an object with non-continuous thin wall under 2mm. it will produce a single wall with infill. (see image). Both enabling and disabling "Detect thin walls" yield the same results. 

![image](https://user-images.githubusercontent.com/68491566/179395506-577c78ff-2ed4-4b29-b597-bcf6149614c4.png)

**Comment by Cosmo991119** [comment]
Could you provide your model of this issue?

**Comment by thrutheframe** [comment]
[wall_test.zip](https://github.com/bambulab/BambuStudio/files/9137330/wall_test.zip)
@Cosmo991119 attached in the zip file is the the stl and 3mf file. It occur when I use 3 wall loops.

**Comment by whutwei** [comment]
Wait next release and try again. Thanks

**Comment by thrutheframe** [comment]
Issue resolved with the recent update of Bambu Lab Slicer v01.01.00.13. Thanks

The option for "Detect thin wall" is also removed.

Will close this issue. 

![image](https://user-images.githubusercontent.com/68491566/180588086-c00eacdb-91f5-4da7-85e0-01b6a9b693c5.png)
