### ISSUE TITLE
Connect Calibration and Purge Lines for easier removal from bed

### ISSUE THREAD

**Issue by Photogad** [bambulab/BambuStudio#1805]
**Is your feature request related to a problem? Please describe.**
All of the calibration lines and purge lines don't connect, so you have to remove them in multiple steps and also it can make a mess as you drop them on your carpet and your pet cat or dog can find and eat them creating a safety issues.

**Describe the solution you'd like**
Connect all the calibration lines and purge lines together at the ends so they can be removed as one piece. Possibly, both Firmware AND Slicer will need to be updated to achieve this and the calibration camera algorithm tuned?

**Describe alternatives you've considered**
Pouring hydrochloric acid on the bed to dissolve the calibration and purge lines.

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/6b44db5a-f2a8-4c43-bd00-dc8858375b9a)
New pattern is included in V1.7 beta version
