### ISSUE TITLE
Arrow keys don't work in Custom G-Code textarea

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#1808]
**Describe the bug**
I am not able to use arrow keys to move the cursor in text area of Custom G-Code window.

**3mf File for This Bug**
_not relevant_

**To Reproduce**
1. Select layer.
2. Add custom g-code.
3. Try to move the cursor with arrow keys.

**Expected behavior**
Ability to move the cursor.

**Screenshots**
_not relevant_

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (a)
 - Version: BambuStudio 1.6.2.4

**Comment by LiZ-Li-BBL** [comment]
This issue has been fixed, you can use it normally in the next release.
