### ISSUE TITLE
Incorrect imperial weight displayed after slicing

### ISSUE THREAD

**Issue by toddanglin** [bambulab/BambuStudio#1809]
When Bambu Studio is configured to show imperial units (in, oz), it forgets to convert the "filament" weight value to ounces after slicing in the "Preview" view.

**Steps to reproduce the behavior:**
1. Open Bambu Studio and make sure units are set to Imperial in "Settings..."
2. Add a model (any model) to the project and slice
3. In the "Color Scheme" overlay, choose "Filament" and note the imperial weight value in ounces
4. Now, go to "Settings..." and change Bambu Studio to metric units
5. Note the new (correct!) metric value displayed for weight in grams
6. As you can see, Bambu Studio shows the same numeric value for grams and ounces and does not properly convert between units. Ounces should be a smaller number than grams.

**Screenshots**
_Metric units (correct)_
<img width="271" alt="Monosnap xBloom-DripPad-TPU 2023-05-14 23-14-08" src="https://github.com/bambulab/BambuStudio/assets/647319/4fb7d948-f3f3-4b74-a0b5-eeb8a2d6a568">

_Values after changing settings to Imperial units_
<img width="298" alt="Monosnap xBloom-DripPad-TPU 2023-05-14 23-21-10" src="https://github.com/bambulab/BambuStudio/assets/647319/2e70ed31-0624-4aa2-8b3b-5588b5ebf2b9">

In this example, ounces should be shown as 0.94 instead of 26.55. Meanwhile, the conversion between meters and inches is correct.

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Bambu Studio Version: 1.6.2.4

**Comment by LiZ-Li-BBL** [comment]
We'll check this issue.

**Comment by LiZ-Li-BBL** [comment]
This issue has been fixed. Please update your version of BambuStudio to this : https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.65
