### ISSUE TITLE
Request - Timelapse "with" toolhead option.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#181]
It's super simple to add the code for this into the layer change g-code so that it just takes a photo and doesn't move the printhead, but it would be great to have an option in the slicer to make it easy for users to enable/disable it.

A formalised version of the else code, with a selection option:
_{if timelapse_no_toolhead}
G92 E0
G1 E-[retraction_length] F1800
G1 X65 Y245 F12000 ; move to safe pos
G1 Y265 F3000
M400 P100
M971 S11 C10 O0
G92 E0
G1 E[retraction_length] F300
G1 X100 F5000
G1 Y255
{else}
M971 S11 C10 O0
{endif}_

**Comment by Sirwill1968** [comment]
I agree, timelapse with toolhead by not adding additional time, or wipes or timelapse tower would be great.  Zero impact to print quality, and no increased time.  Or bangs to clean the nozzle.

**Comment by YifanWuBambu** [comment]
We will schedule this in recent release.

**Comment by RobinWhitfield** [comment]
This is now present as "traditional" timelapse mode in the latest 01.02.00.04
