### ISSUE TITLE
Auto Support Failed to Generate with Sharp Overhang

### ISSUE THREAD

**Issue by BREACHER556** [bambulab/BambuStudio#1810]
Hi All,

Somehow the slicer cannot generate auto support with sharp overhang (Pic 1 & 2).

I tried to change the design to give it less chamfer / top chamfer only  / bottom chamfer only. Finally able to generate support when the chamfer is 1mm or less or no top chamfer(see pic 3, 4 & 5)

Any idea why? (Sure I can change the design or add support manually, but I want to know if is there a parameter I need to follow to get auto support)

Also, auto support can be generated when the Threshold Angle = 45°, but it doesn't make sense.

Thank you!

**3mf File for This Bug**
[Chamfer Support Test.zip](https://github.com/bambulab/BambuStudio/files/11474656/Chamfer.Support.Test.zip)

**To Reproduce**
1. open the 3mf file
2. Slice it
3. See the error
4. To get auto support works for all, the angle needs to be at least 45°

**Expected behavior**
As above

**Screenshots**
See attached Zip file

**Desktop (please complete the following information):**
 - Window 11
 - Version 1.6.2.4

**Comment by tangketan** [comment]
Thanks for reporting the issue. It's caused by the "small overhang removal" function. We'll try to fix it in the next version.

**Comment by tangketan** [comment]
I've added an option to let you disable the function "small overhang removal".
But the gap between the object the supports are still too large as the blade is too sharp. I'm not sure how useful it is.
![image](https://github.com/bambulab/BambuStudio/assets/13730459/49812391-85dc-4389-a0a0-02e5c589e8c3)
