### ISSUE TITLE
Z Seem in Spiral Vase Mode

### ISSUE THREAD

**Issue by gmoissey** [bambulab/BambuStudio#1811]
**Describe the bug**
There appears to be a z seem in spiral vase mode. When analyzing gcode it looks like this happens due to some tasks that the printer has to perform between switching to the next layer.
I tried slicing the same model in PrusaSlicer using Vase Mode and it has no z-seem.

**3mf File for This Bug**
[Vase.3mf.zip](https://github.com/bambulab/BambuStudio/files/11480136/Vase.3mf.zip)

**To Reproduce**
1. Go to 'Others'
2. Click on 'Spiral Vase'
3. Slice
4. You can find a z seem

**Expected behavior**
There should be no z seem or other artifacts in spiral vase mode.

**Screenshots**
<img width="1307" alt="Screenshot 2023-05-15 at 11 54 49 AM" src="https://github.com/bambulab/BambuStudio/assets/69596008/b01f7502-a23c-40da-ae3c-fccdcc210186">
<img width="1727" alt="Screenshot 2023-05-15 at 11 53 14 AM" src="https://github.com/bambulab/BambuStudio/assets/69596008/00122828-c0d1-4eea-b194-abc67a1cdcfd">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.6.2.4

**Comment by SaltWei** [comment]
> I tried slicing the same model in PrusaSlicer using Vase Mode and it has no z-seem.

![image](https://github.com/bambulab/BambuStudio/assets/110660407/b3356659-d719-4a5c-b065-bf8db68f8a92)
