### ISSUE TITLE
Adding option of number of slow layers.

### ISSUE THREAD

**Issue by werewolfenn** [bambulab/BambuStudio#1818]
On some filaments, I am keeping my prints running at 50% for a number of layers before switching back to 100% speed.  I know I can edit the first layer speed and first infill to whatever speeds I want, but I'd also like to choose how many additional layers to go that speed.

**Comment by bambu123** [comment]
You can use modifiers to fulfill this requirement.

https://help.prusa3d.com/article/modifiers_1767#height-range-modifier

**Comment by werewolfenn** [comment]
> You can use modifiers to fulfill this requirement.
> 
> https://help.prusa3d.com/article/modifiers_1767#height-range-modifier

Perfect!   Not where I was thinking, but will certainly do the trick.  Thank you!

**Comment by bambu123** [comment]
Glad to hear that!

**Comment by werewolfenn** [comment]
The given option is really helpful, but thinking it over, it's not 100% ideal.  If I wish to do this with everything I print, I'd have to do this process every time.  A box I can check off, or something I could save as a preference in a saved profile would be best (for me).

**Comment by man55** [comment]
One setting is missing a lot: the number of slow layers. I like to put 2 layers in most cases, like for example in Cura Slicer. Using modifiers every time is very inconvenient.
The fan by default turns on only from 4 layers. As a result, the 2nd and 3rd layers break, the speed is already too high, and there is no cooling yet. And it's too early to turn on the fan already on the second layer.
Damaged second layer in the photo. PETG.
![IMG_7271](https://github.com/bambulab/BambuStudio/assets/30772900/940d492a-0c73-4fe1-b48d-6630d8b1dce1)
