### ISSUE TITLE
Plate 12 Overlap Issues

### ISSUE THREAD

**Issue by FurysSIN** [bambulab/BambuStudio#1821]
**Describe the bug**
When slicing a plate with several "flexible" files and a brim (any type), some sections will have the brim and the bottom layers overlap, causing the object to print incorrectly. I have checked that the file is completely flat by cutting off 0.2mm, reloading the file, and/or separating the object out to print individually. The only thing that has corrected the problem is not using that plate as I have noticed that it's strictly on Plate 12

**3mf File for This Bug**
Paid-for files have been cut to respect designers' IP. Cut does not affect issue. 
[Google Drive 3mf](https://drive.google.com/file/d/1jbGdM0djwhUvb03nInvEDHx8jnCQQTN-/view?usp=sharing)

**To Reproduce**
Load multi-part objects (as single objects) on Plate 12. Seems to need more than 5 parts to display the issue. Moving the object can cause the issue to not fully be apparent.

**Expected behavior**
The brim should not be under bottom layers...

**Screenshots**
Images will show one file, however I have had this issue with several different files. The only commonality is Plate 12.

Image showing the sliced preview. Back and front have the brim overlapped.
![image](https://github.com/SoftFever/OrcaSlicer/assets/133971941/93bc2328-052d-492d-8b02-80eeb341cde9)

Image showing that the bottom layers are slicing as bottom layers and not large overhangs
![image](https://github.com/SoftFever/OrcaSlicer/assets/133971941/9573196b-7246-4e0d-926b-be0ea8797a1c)

Single Object on Plate 12
![image](https://github.com/SoftFever/OrcaSlicer/assets/133971941/3b721c61-7c49-4a6f-b76d-d5af2c64e196)

Object cloned and sliced correctly as a single item on plate 13
![image](https://github.com/SoftFever/OrcaSlicer/assets/133971941/4fc33302-2111-44bf-adea-c2f851164420)

Bad slice as printed
![image](https://cdn.discordapp.com/attachments/1061800290266927104/1108716727866507334/20230518_072405.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 10.0.19044

**Comment by FurysSIN** [comment]
Plate 16 is also seeming to repeat the behavior of overlapping the brim and bottom layers. After more checking, if you have enough plates to for Bambu Studios to put 4 or 5 plates in a row, the 4th plate in the row is exhibiting the overlap behavior.

**Comment by tangketan** [comment]
Thanks for reporting the issue. I've confirmed this is a bug with brim shifting. We'll fix it in the next version.

**Comment by SaltWei** [comment]
Fixed in internal version already. Will be included in next user release! Thnaks

**Comment by tangketan** [comment]
The latest Studio 1.7 has fixed this bug. Please take a look.
