### ISSUE TITLE
The cut object interface does not handle normal field selection correctly

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1823]
**Describe the bug**

After selecting cut, I enter a value for rotation into a field and tab to the next field and the value is discarded and rotation does not happen. This is not standard, and not the way any other field in the application works. I always tab between settings fields and they work correctly.

Because of this issue I have been using the drag handles to rotate the plane. This also does not work well because there is no snapping to common angles, like there is in other applications doing this. The drag is almost impossible to make stop at 90 degrees. 

I did find that `<enter>` will perform the rotation so at least I have a way to rotate exactly 90 degrees. It leaves the dialog with no field focused, and performs no default button actions as I would expect. 

Normally there would be a default button that `<enter>` would "press". In this instance it might be the "perform cut" button.

**To Reproduce**
1. Open Bambu Studio and select an object on a plate
2. 'c' to open the cut dialog
3. enter 90 in the rotation Y field
4. hit `<tab>`
5. There are multiple errors
    6. the value entered in the field is discarded
    7. instead of moving to the following field (Z), the cursor returns to the first field (X rotation)
    8. the plane for the cut is not changed

**Expected behavior**

In form type applications the `<tab>` should always move to the next field in tab order. This works correctly in other places in Studio. If I change the layer height and `<tab>` the cursor moves to "first layer height" and the slicing is reset because changing a setting requires re-slicing.

I expect that using the steps above that the plane would rotate 90 degrees around the y axis and the cursor would move to the Z field.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by LiZ-Li-BBL** [comment]
Have been fixed
