### ISSUE TITLE
Drag and drop 3MF or STL to main screen, not only the prepare screen

### ISSUE THREAD

**Issue by Photogad** [bambulab/BambuStudio#1826]
**Is your feature request related to a problem? Please describe.**
I like to drag-and-drop (windows) 3MF or STL file from my desktop into Bambu Studio. However, it only allows drag-and-drop when you are on the "prepare" screen. I think it would be better if you also allowed drag and drop on the "main" screen that opens when bambu studio opens. This would save an extra step and be more quicker for user. And, sometimes I forget to change to "prepare" screen before drag and drop, and this can be annoying.

**Describe the solution you'd like**
Allow user to drag-and-drop 3MF or STL/STEP file into the program no matter which screen is open in the program.

**Describe alternatives you've considered**
No alternative

**Additional context**

SHOULD BE ABLE TO DRAG AND DROP FILES HERE:
![Screenshot 2023-05-19 113316](https://github.com/bambulab/BambuStudio/assets/18505956/8dde32b3-3f24-4192-b28b-e79e577c000e)

BUT CAN CURRENTLY ONLY DRAG AND DROP FILES HERE:

![Screenshot 2023-05-19 113335](https://github.com/bambulab/BambuStudio/assets/18505956/441e22ac-d74d-459c-b84e-f22701db92a5)

**Comment by lanewei120** [comment]
already supported on homepage
