### ISSUE TITLE
Prime Tower Not showing up with Single Colour change

### ISSUE THREAD

**Issue by adamfilip** [bambulab/BambuStudio#1830]
Printing White and black petg using AMS
Starts white then at range of 1mm height switches to Black

Prime tower does not get generated (when enabled) printed with only a single filament change (white -> black)
when adding a 3rd change the prime tower appears

![image](https://github.com/bambulab/BambuStudio/assets/10480179/22ff4ff1-03d1-498a-aecb-8f962c5ffedb)

using BS 1.6.2.4
X1C 1.5 and X1 1.5
[24Tags May20 v11 tower test.zip](https://github.com/bambulab/BambuStudio/files/11522954/24Tags.May20.v11.tower.test.zip)

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed, you can have a try in the latest version
