### ISSUE TITLE
Issues with slicer 

### ISSUE THREAD

**Issue by ksv1986voss** [bambulab/BambuStudio#1831]
Hello 
Since the new release of Bambu slicer I have a problem with my slicer can you help me 
Thanks 
![IMG_3720](https://github.com/bambulab/BambuStudio/assets/67060546/4c995462-b026-4cd6-90c6-a78f95a8d740)
![IMG_3721](https://github.com/bambulab/BambuStudio/assets/67060546/da52446a-2059-4e04-9b5d-f5b5bd793756)

**Comment by SaltWei** [comment]
3MF file please

**Comment by SaltWei** [comment]
Hello, could you share your problem 3mf file so we can try to reproduce this issue?

**Comment by SaltWei** [comment]
Still can't reproduce this issue. Close.
If has some new information about this issue, please reopen. Thanks!
