### ISSUE TITLE
DLLs and system profiles are updated with no notification

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1833]
**Describe the bug**

I just happened to be looking at the debug log to diagnose a problem and I noticed entries about updating system profiles. It seems that when system profiles are updated that they also get copied to the AppData directory replacing those already there.

Knowing when something is being updated is important. It helps to determine the cause for changes in operation, or bugs that appear.

It is even more important if the update is related to a firmware update and it changes the user customizable G code sections. It is possible that this kind of change could cause damage to the printer, if the user had no notice and the G code interpretation changed.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows]
 - Version 1.6.2.4

**Comment by lanewei120** [comment]
hello

the system profiles currently is updated with the BambuStudio together
if the version of Bambu Studio changes from v1.5 to v1.6
then the system profiles will also be updated to v1.6, and will be copied to app data

and the system profiles is consistent with bambustudio in the same version
we will make sure the system profile correct when published

and we can find the system profile difference between these two version on github's commit history

**Comment by julie777** [comment]
Regarding the system profiles, I think what made me think they had been updated was a combination of log entries that were about updating profiles, and sycing, and the timestamps on the system profile files in the AppData/Roaming/BambuStudio/system directory. My last update of Bambu Studio was 2023-04-26, but I have many system profiles that were copied to the AppData directory dated 2023-05-04.

I know that I saw this copying in the log file, so maybe that is part of my misunderstanding.

The DLL updates are a different issue and they have been updated without any notification. During install there is a notification, but in normal use when the DLLs are updated I do not recall seeing any notification.

**Comment by lanewei120** [comment]
> ue and they have been updated without any notification. During install there is a notification, but in normal use when the DLLs are updated I do not recall seeing any notification.

the dll updating also has logs in the log file,
to improve the user experience, we don't want to popup a notification to let the user do more confirm

**Comment by lanewei120** [comment]
there is a popup window when updating the network plugins at the bootup
![image](https://github.com/bambulab/BambuStudio/assets/106916061/d1fa01f9-9cad-4840-afd7-e239f1e2d8fe)

**Comment by lanewei120** [comment]
close this issue as above comment
