### ISSUE TITLE
Filament change with multiple plates doesn't work

### ISSUE THREAD

**Issue by drumbo** [bambulab/BambuStudio#184]
I have a project with 3 plates using my X1CC and PETG loaded into slots 2 & 3 on the AMS, each plate contains a single object. If I select the object on plate one, go to the layer height where I want to change filament, right click, change to filament 3 (object is set to use filament 2) I can see the little grey line appear on the height bar (indicating the filament change), the filament change times increments from 0 to 1. When  I reslice the file I don't see the colour change in the object in the preview window and if I export the file to gcode I don't see any M600 change. If I search for the z height where I made the change - I can see no indicator for a filament change. Printing the file results in no filament change. Here is the first bit of g-code where the layer height changes  to 5.2 (where I made the filament change in the slicer) (bold bit is my addition). Note that if I add a filament change on any of the plates - the slicer indicates that it is done, but the preview shows no colour change. Nor does the file print with any layer change. See image for example:

I have also noticed that a filament change at a set height seems to affect all plates - not just the currently selected on. Not sure if this is meant to happen, and possibly could be the cause for the issue above.

<img width="1278" alt="Screenshot 2022-08-30 at 16 46 04" src="https://user-images.githubusercontent.com/2462871/187482520-23a21cda-43f5-4caa-a179-391cfa1018ba.png">

<added comments> I actually notice that Filament change times registers as 1 just because I am using filament 2 as a starting filament as opposed to 1. Therefore it seems that although the grey line on the layer height bar appears after I have added the filament change - the actual filament change doesn't occur. If I start a new project, add just one object to 1 plate - the layer change feature works ok

G1 E-.56 F1800
; WIPE_START
G1 F23040
G1 X138.919 Y58.638 E-.06227
G1 X138.483 Y58.75 E-.05141
G1 X138.046 Y58.774 E-.04987
G1 X137.609 Y58.701 E-.05048
G1 X137.499 Y58.648 E-.01397
; WIPE_END
G1 E-.012 F1800

G17
G3 Z5.4 I-.697 J-.997 P1  F28800
G1 X65.845 Y108.738 Z5.4
**G1 Z5.2**
G1 E.8 F1800
; FEATURE: Inner wall
G1 F7369.565
G1 X65.466 Y110.132 E.04646
G2 X190.366 Y142.537 I62.536 J15.871 E6.49574
G1 X190.366 Y142.537 E0

**Comment by YifanWuBambu** [comment]
@drumbo 
This bug is fixed and will be in next release.
