### ISSUE TITLE
The new issue submission for does not work correctly

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1848]
### Description of the bug

I like the use of a form for input. 

Instead of putting the environment information at the top as I suggested you made it a mandatory field. That works, sort-of.

The problem is that instead of using fields for individual items, some of the fields are really a set of fields in one. For example, looking at system information there is only one entry field, but it has four items in it as indication of what to add. The problem is that as soon as I start to type in that field all of the information about what should be input disappears. They should be separate fields in the Environment or System information section. The order is also strange because Studio version is first, but model and where I got Studio is after system information.

I have not set up forms yet, but I would expect there to be a way to use drop-downs to select version for example. In addition to being easier for the user, having a preset list of choices allows them to be uniform and useful for categorization/search. If every user types the same information in a different way then it only helps when looking at a single issue. I would think you would have saved searches to see all the bugs marked P1P or all the bugs on MacOS.

Defaults would be nice. For example, I am always running the latest version of BS. It is filled in as an example, but I have to type over it to actually set that version.

Project file upload is part of the same field as steps to reproduce. This doesn't make sense. And again, as soon as I touch that field the comment disappears and I am left with a blank field. A better implementation would be to have the field for steps to reproduce look like
```
Steps to reproduce:
1. click here and start typing
```
and when I click the hint disappears, but the 1. that starts the list stays and what I type becomes step 1. and I am in list mode so auto number happens every time I hit enter.

### Project file & How to reproduce

Open issue

### Version

1.6.2.4

### System Information

Windows 10

### Printer model

P1P

### Where is the application from?

BBL website

**Comment by lanewei120** [comment]
thanks for the suggestions

for the version selection, as there will be lots of new versions in the feature, the dropdown selection need to be updated too often, and from the github releases, the versions count is too big as the selection items
so we keep it as an input

for other items, we have improve them
please have a try
