### ISSUE TITLE
Wrong plate is selected when Bambu Studio is started for P1P

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1850]
### Description of the bug

When I start Bambu Studio it creates a new (blank) project. 
The print profile is set correctly to "Bambu Lab P1P 0.4 nozzle"
The plate is set to "Engineering plate" which is not what ships with the P1P.

### Project file & How to reproduce

Open Bambu Studio and see if the correct plate is selected.
It should be the default plate for that print profile.

### Version

1.6.2.4

### System Information

Windows 10

### Printer model

P1P

### Where is the application from?

BBL

**Comment by lanewei120** [comment]
the same as https://github.com/bambulab/BambuStudio/issues/1847
