### ISSUE TITLE
256X256X256 full size print layers not slicing the print correctly 

### ISSUE THREAD

**Issue by vzb007** [bambulab/BambuStudio#1855]
### Bambu Studio Version

1.6.24

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

i7 32gb ram 1tb Hp dragonfly

### Printer

Bambu labs X1C

### How to reproduce

put a 256X256X256 cube to print select center by right clicking 

once postioned select .24 or .28 layer draft and extra draft it will give a error "a g-code path goes beyond plate boundaries"
by try the same print with .20 layer layer it works. all other layer heights done work

![image](https://github.com/bambulab/BambuStudio/assets/33681172/d6befc6d-b1e0-4781-bbcc-37a9a6bcf8dc)
![image](https://github.com/bambulab/BambuStudio/assets/33681172/fd8f0324-b6a2-4523-9526-20ba06b91e65)

two images attached for reference 

### Actual results

there is a error when selecting .20 layer and .24 layer

### Expected results

there should be no error

### Project file & Debug log uploads

the siles are supplied to the support team too

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/b7352540-cead-45e7-ac6a-ea6029f226f4)
The model is 256mm, and sliced with fixed layer height 0.24.
Finally, the layer number is round up to 1067. And height is 1066*0.24 + initial layer 0.2 = 256.04mm, which is mostly close to the real height of model.

**Comment by SaltWei** [comment]
> a g-code path goes beyond plate boundaries

In this case, the message should be "the gcode path goes beyond printable height"
This should be modified.

**Comment by vzb007** [comment]
Thanks for this. So the slicer will not make a adjustment to fit the last layer within the size. Could there be a better explanation and option to assist people. You have very helpful thank you.

Have a another issue with the walls on the same print not sticking together properly. I am attaching a image for reference 
![20230528_232317](https://github.com/bambulab/BambuStudio/assets/33681172/2b010391-455e-464c-bd68-73c1814b2084)
![20230528_232323](https://github.com/bambulab/BambuStudio/assets/33681172/409fc972-5dff-4330-86c2-e527a592fb66)
![CAP5022378229034417611](https://github.com/bambulab/BambuStudio/assets/33681172/b3a05ffe-3bf1-4d66-bd3d-146797554028)

**Comment by SaltWei** [comment]
Could you share gcode file so we can check and reprint as well ?

**Comment by SaltWei** [comment]
No response for a long time. Close.
Reopen if has new update
