### ISSUE TITLE
Loading a project selects all objects

### ISSUE THREAD

**Issue by julie777** [bambulab/BambuStudio#1856]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

P1P

### How to reproduce

Open an existing project

### Actual results

The project opens to the prepare page and all objects are selected.

### Expected results

Nothing should be selected.

### Project file & Debug log uploads

not necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bambu123** [comment]
Thank for your report. We'll check the intention here.

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
