### ISSUE TITLE
Auto Arrange In Multiplate Project Causes Some Items To Indicate Unprintable

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1858]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

Core i5 10th gen 32GB RAM
Nvidia 3060

### Printer

X1 Carbon Combo

### How to reproduce

1. Open uploaded project. Project contains some objects set to unprintable on plate 5
2. Click auto arrange on plate 4

### Actual results

The project contains some objects set to unprintable on plate 5
![image](https://github.com/bambulab/BambuStudio/assets/96731892/f86be5da-d45c-4d90-9bce-5132c1511a12)

After selecting auto arrange on plate 4, several items are now showing unprintable on plates 2 and 3 and several items that were previously unprintable are now indicating printable on plate 5.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/cca1046b-593c-4973-962c-71459b41ac59)

However, the item still indicates printable in the context menu and it does slice correctly.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/485e8905-0e13-4540-9d2d-e191c1db449f)

Conversely, the items that were previously unprintable (that now indicate printable) are shown correctly in the context menu as unprintable. Again, it slices correctly.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/87768bc4-98c0-4d7d-beff-0d639d85e767)

Selecting auto arrange on other plates causes different objects to indicate incorrectly.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/273b494c-1178-40f0-93a9-2c4a2c7b7ead)

### Expected results

Expect no change in the printable status on any plate after using auto arrange.

### Project file & Debug log uploads

Project file was too big to upload here. Please follow [link](https://drive.google.com/file/d/1qxPXtZYY5Tkie9ANVsCq-SKV4iR0Gfn2/view?usp=sharing) 

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by tangketan** [comment]
Thanks for reporting the bug. We are investigating it.

**Comment by lanewei120** [comment]
already fixed in previous versions
