### ISSUE TITLE
First print after starting bambu studio has option to enable AMS on device that doesn't support AMS

### ISSUE THREAD

**Issue by TennisRunner** [bambulab/BambuStudio#1863]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

p1p

### How to reproduce

Boot up bambu studio.
Load any file.
Click print plate.

### Actual results

A checkbox with Enable AMS appears and is always checked on.
![Untitled](https://github.com/bambulab/BambuStudio/assets/59356546/81611a91-30cc-4e85-b6f6-912bbb50cb9b)

### Expected results

Enable AMS shouldn't even appear since p1p doesn't support AMS.
It disappears after the finishes syncing in about 20 seconds.

### Project file & Debug log uploads

[foo.3mf.zip](https://github.com/bambulab/BambuStudio/files/11578682/foo.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.
You do not have an AMS device. Is that right？

**Comment by TennisRunner** [comment]
> Hi. You do not have an AMS device. Is that right？

Correct

**Comment by walterwongbbl** [comment]
Thank you. We will fix this issue

**Comment by walterwongbbl** [comment]
Hi.
Can you upload the studio log file

**Comment by walterwongbbl** [comment]
Hi.
Can you upload the studio log file

**Comment by walterwongbbl** [comment]
Hi.
We have fixed this issue and will include it in the next version
