### ISSUE TITLE
Bug with prime tower when print sequence is set to “by object”

### ISSUE THREAD

**Issue by nkacena** [bambulab/BambuStudio#1876]
### Bambu Studio Version

1.5.0.61

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

x1c

### How to reproduce

add multiple objects to plate (each object has 2 or more colors, AMS enabled)
select print by object
ensure prime tower is enabled
slice

prime tower is missing. 

### Actual results

prime tower is missing after executing above steps

### Expected results

prime tower (or multiple prime towers) should be created when printing multiple multi-color objects and print sequence is set to "by object"

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@nkacena 
If  is print "by object", a prime tower will only be generated when there is only one object. If there are multiple objects, no prime will be generated.

**Comment by nkacena** [comment]
@zhimin-zeng-bambulab could you add the option to add a prime tower when printing multiple multi-color objects? I routinely print multiple multi-color prints but without a prime tower they're usually not as crisp on the transitions so I'm then forced to print one by one, taking much more time.

**Comment by zhimin-zeng-bambulab** [comment]
Due to the code framework, printing multiple objects with multiple colors "by object" is not supported currently.  You could print multiple objects with multiple colors  "by layer".

**Comment by x-caliper** [comment]
I would find this extremely useful as well.

**Comment by vanowm** [comment]
Currently a work around is to create a small `cube` for each color and merge them with the part that uses multiple colors. Make sure these cubes are on top of the assembly list. This way after each color change it will start printing these cubes first.
The downside of this method is it requires manually adjusting the size of the cubes and will increase the required boundaries per part.

![Image](https://github.com/user-attachments/assets/ca6c8b48-7f9d-4cae-b0f0-341557b06cc0)

**Comment by Acorn9443** [comment]
> Currently a work around is to create a small `cube` for each color and merge them with the part that uses multiple colors. Make sure these cubes are on top of the assembly list. This way after each color change it will start printing these cubes first. The downside of this method is it requires manually adjusting the size of the cubes and will increase the required boundaries per part.
> 

This works for me! Thanks for the tip.

In my case I want a prime tower when I'm printing sequentially and each object is a different colour. 

Normally, printing another object directly after colour change can sometimes start with an inconsistent first few lines, this pseudo prime tower allows me to still prime between object changes with different colours to make sure those first couple lines are going down proper. 

<img width="417" height="188" alt="Image" src="https://github.com/user-attachments/assets/c5efbbb3-02f1-400c-95a6-560e1aa53cac" />

<img width="1264" height="1018" alt="Image" src="https://github.com/user-attachments/assets/19145022-9e62-448e-a98c-887f2c1f338f" />
