### ISSUE TITLE
Dark mode resets after RDP session to computer with Bambu running

### ISSUE THREAD

**Issue by tangcla** [bambulab/BambuStudio#1889]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

Start Bambu Lab on computer (in dark mode)
Connect to computer via remote desktop (over network)

### Actual results

Dark mode checkbox is unticked.
![Screenshot 2023-06-03 100540](https://github.com/bambulab/BambuStudio/assets/8278114/2edff9a5-bf5a-4e0a-bef5-7e09432cc86b)

### Expected results

Dark mode should remain as this is not configured by system settings.

### Project file & Debug log uploads

This bug is not project specific.
[log.zip](https://github.com/bambulab/BambuStudio/files/11640009/log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.
Is this problem reproducible every time?

**Comment by tangcla** [comment]
> Hi. Is this problem reproducible every time?

Yes, each time after I remote desktop into my PC, it reverts back to the light theme.

**Comment by TackleBerryCrash** [comment]
I can also confirm this happening every time. I was wondering why studio color scheme was behaving wildly but it was not random after all. Thanks for solving this mystery...
Closing the app and opening solves the UI problem but it reverts to the light mode.

**Comment by DMFirmy** [comment]
I too confirm this issue. You can go directly into the settings and re-apply dark mode without having to first close and re-open the application, but as noted, light mode gets set after connecting via RDP, and until reset or closed the application goes all wonky with its coloring.

**Comment by walterwongbbl** [comment]
Hi.
We have optimized the dark mode in the next version.

**Comment by tangcla** [comment]
Note that this also happens when another user signs into the computer (and then returning back to original user).

**Comment by walterwongbbl** [comment]
Hi.
Please use the latest version of Bambus Studio
