### ISSUE TITLE
Request - Bambu Studio reload capability

### ISSUE THREAD

**Issue by Vmtr** [bambulab/BambuStudio#189]
In Bambu Studio, add either an ability to detect change in an STL file and prompt to reload, or to right-click a model in a project and select a "reload model" option. This would be helpful when re-printing a model as its design is evolving.

**Comment by YifanWuBambu** [comment]
@Vmtr 
This is in our plan. We will add "reload" feature in recent release.

**Comment by DzzD** [comment]
Hi, this issue should not have been closed, I think OP (as I would like to) was thinking more of an automatic detection, not a manual reload.

When a source file stl is modified a popup should ask to reload, reload should apply all transformation made in Bambu studio (obviously when applicable, not painting or other unrecomputable features)

**Comment by samy** [comment]
I agree with @DzzD : this feature exists in Cura and other software and is very useful. You export your STL file on the same file and the slicer should offer auto detection of changes
