### ISSUE TITLE
Slicing times the wrong vector, on the macOS

### ISSUE THREAD

**Issue by vv298** [bambulab/BambuStudio#1895]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

macOS Ventura 13.3

### Additional system information

CPU: 2.4 GHz 8 core Intel Core i9
Memory: 64 GB 2667 MHz DDR4
Display card: AMD Radeon Pro 5500M 8 GB & Intel UHD Graphics 630 1536 MB

### Printer

Bambu Lab X1 series

### How to reproduce

1.Open the project of BambuStudio 
2.Click Slice plat

### Actual results

3.The process a stops or an error message is displayed
![err tips](https://github.com/bambulab/BambuStudio/assets/89661378/8ad12766-03aa-402d-9aab-89c6c0c75b3d)

### Expected results

show slice preview

### Project file & Debug log uploads

[project.zip](https://github.com/bambulab/BambuStudio/files/11646651/project.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/11646652/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
