### ISSUE TITLE
No Ability To Adjust Print Order Within An Assembly

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#1896]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

Win11

### Additional system information

CPU 10th gen Core i5

### Printer

X1 Carbon Combo

### How to reproduce

In Prusa Slicer, I am able to adjust the print order within a merged group or assembly so that one object can be printed before another object. I use this ability to be able to print targeted brims using support W when the standard brim is difficult to remove. Within an assembly, Bambu Studio does not have the capability to rearrange the print order, sometimes causing the brim object to occlude the part object. To reproduce:

1. Use the uploaded .3mf or:
2. Create a 10mm cylinder primitive (part)
3. Create a cube primitive .2mm high (brim) 
4. Clone the brim, and then clone the part.
5. Create two assemblies, one with the brim first, then the part and another with the part first, then the brim.
6. Slice the plate and look at the first layer. The assembly with the brim first prints around the part (desired) while the assembly with the part first prints around the brim.
7. 
![image](https://github.com/bambulab/BambuStudio/assets/96731892/dad6ee9c-d0bc-4dbe-89a9-23159cda1cbd)

### Actual results

There is no ability to change the print order within an assembly. In Prusa Slicer, you are able to adjust the print order simply by clicking the part and dragging with the mouse. 
![image](https://github.com/bambulab/BambuStudio/assets/96731892/bd93da57-a5af-4393-b528-2570fa1ce1c7)

![image](https://github.com/bambulab/BambuStudio/assets/96731892/4025e41d-900a-4528-81c3-d414f85b7ca8)

### Expected results

Be able to change the order of one or more parts within an assembly. The current work around is to add the parts to the plate in the proper order. This can be more complex than necessary on complicated prints.

### Project file & Debug log uploads

[Bambu Print Order Demonstration.zip](https://github.com/bambulab/BambuStudio/files/11653142/Bambu.Print.Order.Demonstration.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
> In Prusa Slicer, you are able to adjust the print order simply by clicking the part and dragging with the mouse.

I tried these operation on prusa slicer 2.6. But I can't control the print order, but only can control the clipping order of multi part.
![prusa](https://github.com/bambulab/BambuStudio/assets/110660407/d4a29425-381e-4f9a-9e8e-2fde7e688d20)

**Comment by SaltWei** [comment]
Is there any other situation that we need to change the print order?
If only "brim ear" case, I think developing a regular brim ear function is more perfect!

**Comment by MadMax389** [comment]
Perhaps "print order" is not the right term in favor of clipping order. There are other use cases where arranging the order will be beneficial. In my text example, you can see that the order of the items in the assembly affects whether the text prints or not.

![image](https://github.com/bambulab/BambuStudio/assets/96731892/5d30dfa4-e37e-46bd-b743-8d8ced2a4352)
![image](https://github.com/bambulab/BambuStudio/assets/96731892/3b3996f8-8513-43b0-bbe0-91fdb7c1986a)

I use the clipping order to make multi-layer targeted brims. In the spider example, it would be nice to be able to drag the spider to the bottom of the list. My current workaround is to copy and paste the object to create a copy at the end of the list, then delete the first one.
 
![image](https://github.com/bambulab/BambuStudio/assets/96731892/fc3efc07-5fdf-441c-a0ab-23c309bc07b3)
![image](https://github.com/bambulab/BambuStudio/assets/96731892/cc44d61d-59ac-40c9-99b3-64476b44f92e)
![image](https://github.com/bambulab/BambuStudio/assets/96731892/b4e80259-0fde-465c-9299-df2dcbebd653)

**Comment by SaltWei** [comment]
If my understanding is wrong, please don't hesitate to point out.
Actually, this feature request can be devided into two features.
1 user define the clip order of multi-parts model. User can adjust the part order in the list, and the bottom one has highest priority to clip other part to remain its area. By this feature, user can add "brim part" for model and merged with model together, while keeping the whole part of original model.

2 Add one way for user to define the filament print order of first layer. So the "brim part"  which usually uses support filament can be printed first to help the attachment of original model part

**Comment by MadMax389** [comment]
@SaltWei 
Yes for item 1. Just the ability to change the order of the objects in an assembly list (like Prusa Slicer) would be very convenient.

For item 2, I think just the ability to specify a different brim material (like can currently be done with support and support interface) would be a nice feature. This would allow us to specify Support W as a brim material. Also, adding the brim function as a modifier would allow targeted brims in certain areas without having to brim the whole object. (This does not exist in Prusa Slicer).

**Comment by SaltWei** [comment]
Be handled in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52
