### ISSUE TITLE
Slicer is not printing coloring correctly

### ISSUE THREAD

**Issue by Tricky12321** [bambulab/BambuStudio#1901]
### Bambu Studio Version

1.6.2.4 ([Bambu_Studio_linux_fedora_v01.06.02.04-20230427094209.AppImage](https://github.com/bambulab/BambuStudio/releases/download/v01.06.02.04/Bambu_Studio_linux_fedora_v01.06.02.04-20230427094209.AppImage))

### Where is the application from?

Bambu Lab github releases

### OS version

Linux PC 6.3.3-1-MANJARO x86

### Additional system information

AMD Ryzen 7 5800X 8-Core Processor
Ram: 32 GB
GPU: AMD Radeon RX 6700 XT

### Printer

Bambulab X1C (AMS)

### How to reproduce

1. Load the following STL [Bambu Lab Scraper - No Magnetic.stl](https://files.printables.com/media/prints/453705/stls/3952030_36758608-207b-487b-b555-42541a3ddb14/bambu-lab-scraper-no-magnetic.stl) (Also in attached file below)
2. Paint the Bambulab Logo using a different color then the rest
3. Slice using default profiles
4. Watch the gcode preview that the letters are not printed according to the coloring done:

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/10461592/0db8ada1-4fb7-446f-8e47-01ef2dbc5820)
![image](https://github.com/bambulab/BambuStudio/assets/10461592/823fd5f7-0084-4cb3-a91b-287d98814b35)
![image](https://github.com/bambulab/BambuStudio/assets/10461592/1aa4f522-bdad-451a-be82-8c20b03606e4)

Preview before black color added:
![image](https://github.com/bambulab/BambuStudio/assets/10461592/f6255cdf-0714-4146-9e44-72b3590b9541)
Midway printing black: 
![image](https://github.com/bambulab/BambuStudio/assets/10461592/53f7c15c-2826-43ab-a05d-1e773d71cea7)

### Expected results

The letters should be printed entirely in the correct color, and not first the white, then the black on top of it

### Project file & Debug log uploads

m3f file and STL: 
[Bambu Lab Scraper - No Magnetic.zip](https://github.com/bambulab/BambuStudio/files/11667913/Bambu.Lab.Scraper.-.No.Magnetic.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by wuyifankuang1985** [comment]
@Tricky12321 
It is actually a bug.
There is a method to walkaround this. Just specify the object as a white color(currently it is selected as blue and painted as white) and then paint text.

**Comment by Tricky12321** [comment]
> @Tricky12321 It is actually a bug. There is a method to walkaround this. Just specify the object as a white color(currently it is selected as blue and painted as white) and then paint text.

Your workaround work, but there is still some bugs in the gcode.

Look at the following: 
Layer 59:
![image](https://github.com/bambulab/BambuStudio/assets/10461592/589f247f-c6d4-4bd6-a6e2-d4596bd56416)
Layer 60:
![image](https://github.com/bambulab/BambuStudio/assets/10461592/810bfefc-e318-4d2f-a52f-b05eb65902f9)
Layer 61:
![image](https://github.com/bambulab/BambuStudio/assets/10461592/8fcc65c0-7581-4323-9c17-c53de59ce22a)
Layer 62:
![image](https://github.com/bambulab/BambuStudio/assets/10461592/eb77a64d-1ae7-4495-8a8f-3476d94ca9c7)

As can be seen Layer 59 contains the black color, but layer 60 is for some reason totally white?

**Comment by zhimin-zeng-bambulab** [comment]
Thank you for reporting this issue, it is a studio BUG, ​​we will fix it in the next version.

**Comment by Tricky12321** [comment]
> Thank you for reporting this issue, it is a studio BUG, ​​we will fix it in the next version.

I have just checked out the new beta, but the bug with layering coloring still happens:
https://github.com/bambulab/BambuStudio/issues/1901#issuecomment-1581274720

**Comment by Tricky12321** [comment]
> Thank you for reporting this issue, it is a studio BUG, ​​we will fix it in the next version.
@zhimin-zeng-bambulab 
The layering problem i described above has not been fixed in the latest beta version.
https://github.com/bambulab/BambuStudio/issues/1901#issuecomment-1581274720

[Bambu Lab Scraper - No Magnetic - still bugged-again.zip](https://github.com/bambulab/BambuStudio/files/12047128/Bambu.Lab.Scraper.-.No.Magnetic.-.still.bugged-again.zip)

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed, you can have a try in the latest version.
