### ISSUE TITLE
Static Access Code

### ISSUE THREAD

**Issue by aminoginji** [bambulab/BambuStudio#1902]
**Is your feature request related to a problem? Please describe.**
The access code changes when the device is powered off and on.

**Describe the solution you'd like**
A static access code that dosent change when powered on or off that can be set in the SD card.

**Describe alternatives you've considered**
Not turning off the machine

**Additional context**
Its a waste of power to leave the machine on when its idle

**Comment by sodachen22** [comment]
The access code shall be remembered in power off/on, it is changed when the user refreshes on the screen. Which printer does this issue happen on, X1 or P1P? If the firmware is not latest, can you please have an update and test again?

**Comment by sodachen22** [comment]
Yes, there is a bug fixing.
