### ISSUE TITLE
File .3mf corrupted when using "&" symbol in text fields

### ISSUE THREAD

**Issue by jmorda** [bambulab/BambuStudio#1903]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Printer

Bambu Labs X1C with AMS

### How to reproduce

1. New project
2. Add primitive (cube for example)
3. Add text on cube with "&" symbol ( example : Essai& )
4. Save
5. Reload -> Fail

![2023-06-07 19_35_29-Window](https://github.com/bambulab/BambuStudio/assets/586351/1c269e7d-ccae-4941-81a4-3b0e7e9efc28)

### Actual results

Load of .3mf file fail
![2023-06-07 19_36_12-Window](https://github.com/bambulab/BambuStudio/assets/586351/ed307e07-8914-4724-84c1-b57c970e5db9)

### Expected results

Loading the project without error

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/11680446/log.zip)
[Essai.zip](https://github.com/bambulab/BambuStudio/files/11680451/Essai.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Thank you for reporting this issue, it is a studio BUG, ​​we will fix it in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in [V1.7.4](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52)
