### ISSUE TITLE
Multiple height range modifier

### ISSUE THREAD

**Issue by eddydas** [bambulab/BambuStudio#1907]
**Is your feature request related to a problem? Please describe.**
It looks like we can add only 1 heigh range modifier now. It would be great if we can add multiple height range modifiers, best if they can overlap.

**Describe the solution you'd like**
Allow us to right click an object, then "Add Height Range Modifier" and it will create new height range modifiers. And I can repeat that to add multiple height range modifier.

**Describe alternatives you've considered**
N/A

**Additional context**
I know Bambu Studio supports height range modifiers today - but it supports only 1 range. Hope you can support multiple!

**Comment by liftbag** [comment]
By clicking on the + button you can add as many height range modifiers as you like.

<img width="416" alt="Screenshot 2023-06-08 alle 09 30 34" src="https://github.com/bambulab/BambuStudio/assets/14921654/081c3c2a-2401-4a61-8813-bd341b292d31">

**Comment by freeformz** [comment]
What version is that?
