### ISSUE TITLE
Tool head hits objects on the plate if time lapse and sequential printing are enabled

### ISSUE THREAD

**Issue by CptHungarian** [bambulab/BambuStudio#191]
There are actually two separate bugs in this case:
1. If time lapse and sequential printing are both enabled, the tool head hits the previously printed objects on its way to the excess chute (to take the photo for the time lapse video).
2. The slicer suggests to add time lapse wipe tower to the plate, but in sequential print order the tower is printed out separately.
![Screenshot 2022-09-01 223525](https://user-images.githubusercontent.com/47260714/188017308-d7ffcb3b-8782-491a-9dbe-64ce5762db4c.png)

![Screenshot 2022-09-01 224015](https://user-images.githubusercontent.com/47260714/188017983-5f2dcfc5-5305-4015-b021-b0eb4ee87259.png)

**Comment by YifanWuBambu** [comment]
@CptHungarian 
This bug has been fixed.
In sequential printing, prime tower will be disabled.

**Comment by RobinWhitfield** [comment]
@YifanWuBambu, does that mean that timelapse without toolhead has also been disabled for object-by-object printing, or can it now calculate a path to avoid previously printed objects/print them in an order front-back?

**Comment by YifanWuBambu** [comment]
> @YifanWuBambu, does that mean that timelapse without toolhead has also been disabled for object-by-object printing, or can it now calculate a path to avoid previously printed objects/print them in an order front-back?

1. Does that mean that timelapse without toolhead has also been disabled for object-by-object printing?
Yes. And we will add another timelapse type (snape a picture after a fixed interval), which can be used in the by-object printing.

2. Can it now calculate a path to avoid previously printed objects/print them in an order front-back?
In by-object print, if we still use "timelapse without toolhea", each object needs an individual prime tower.
That will take a lot of area of the build plate, and the video effect may not be very good.

**Comment by YifanWuBambu** [comment]
Fixed in v1.2.
