### ISSUE TITLE
Total print hours on printer

### ISSUE THREAD

**Issue by bl4ckm0onk3y** [bambulab/BambuStudio#1912]
**Is your feature request related to a problem? Please describe.**

P1P Printer does not have total hours printed information in printer settings, to ensure correct servicing of the printer (for example each 500 hours of  print time etc) users need to check the total print time. 

**Describe the solution you'd like**
Please add an information in the LCD Panel on the device that contains total hours printed.

**Comment by sodachen22** [comment]
Total print hours are shown in X1, there is a plan to support it in P1P.

**Comment by Hologos** [comment]
> Total print hours are shown in X1, there is a plan to support it in P1P.

@sodachen22 Is it still planned?

**Comment by bl4ckm0onk3y** [comment]
feature was added within the "input shaping firmware update"
