### ISSUE TITLE
Adjusting print speeds doesn't work.

### ISSUE THREAD

**Issue by CSWP-Spark** [bambulab/BambuStudio#1916]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS 11.6.2

### Printer

X1C

### How to reproduce

Start a new project. Load a model, pick a preset, and adjust print speed. Slice. Print.

### Actual results

Print speed does not change from the preset speeds.

### Expected results

Print speeds should be adjusted based on user input.

### Project file & Debug log uploads

[BLADE.zip](https://github.com/bambulab/BambuStudio/files/11711451/BLADE.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by bambu123** [comment]
Which parameter did you change?
![image](https://github.com/bambulab/BambuStudio/assets/112537880/f964c9eb-1108-4522-b6d5-5a52c955e1d7)

**Comment by SaltWei** [comment]
The printing speed is too high and already reachedc the max volumetric speed in filament setting.
This is not a bug.

**Comment by SaltWei** [comment]
By the way, the cooling logic also make speed lower than settings for small layer.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/84ef3309-2e16-4d1b-bad0-57dde9d092b1)

**Comment by CSWP-Spark** [comment]
I slowed the print speeds down. The printer did not slow down. This is a bug.On Jun 14, 2023, at 7:58 PM, SaltWei ***@***.***> wrote:﻿
By the way, the cooling logic also make speed lower than settings for small layer.

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/8c9f3873-afd3-49e4-bc97-e094896c14b3)
Speed is normal in my slicing.

**Comment by CSWP-Spark** [comment]
If I load the provided .3MF the following speeds have been altered: Outer wall to 40, Inner wall to 50, and Internal solid infill to 50.If I run with those settings, the machine reverts to the default speeds of 120, 150, and 150, respectively.On Jun 14, 2023, at 8:20 PM, SaltWei ***@***.***> wrote:﻿

Speed is normal in my slicing.

**Comment by SaltWei** [comment]
> the machine reverts to the default speeds of 120, 150, and 150

The speed in gcode is still 40, 50, 50， right？

**Comment by SaltWei** [comment]
I don't understand how machine reverts the speed. Do you means that the real running speed of printer is measured to be 120,150,150?

**Comment by CSWP-Spark** [comment]
Yes. I change the speed in the slicer, but the program runs at the default speed from the profile.In order to run this at the speed I wanted, I had to use OrcaSlicer.On Jun 14, 2023, at 9:13 PM, SaltWei ***@***.***> wrote:﻿
I don't understand how machine reverts the speed. Do you means that the real running speed of printer is measured to be 120,150,150?

**Comment by SaltWei** [comment]
Could you share one sliced gcode so I can run it on my printer?
If the speed is 40, 50, 50 in gcode, then it should not be slicer issue.

**Comment by CSWP-Spark** [comment]
I’m out of town for a week. I’ll post one when I’m back.On Jun 14, 2023, at 9:25 PM, SaltWei ***@***.***> wrote:﻿
Could you share one sliced gcode so I can run it on my printer?
If the speed is 40, 50, 50 in gcode, then it should not be slicer issue.
