### ISSUE TITLE
Win版本深色模式bug

### ISSUE THREAD

**Issue by Hotinosin** [bambulab/BambuStudio#1921]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

P1P

### How to reproduce

1.打开软件
2.把系统主题改成深色模式

### Actual results

打开软件的情况下，切换Windows 11 的深色或者浅色模式hui会成这样

![屏幕截图 2023-06-11 202529](https://github.com/bambulab/BambuStudio/assets/87741985/a77ba0a2-6de5-48a1-b03c-14e124478698)

### Expected results

应该全部界面随着主题改变而改变

### Project file & Debug log uploads

NO File

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
你好，
下个版本中将会优化，在win11系统上，将不会再收到系统主题影响，而是由偏好设置中的深色模式开关决定。

**Comment by walterwongbbl** [comment]
Hi.
Please use the latest version of Bambus Studio
