### ISSUE TITLE
cs_CZ translation

### ISSUE THREAD

**Issue by renemosner** [bambulab/BambuStudio#1926]
I have a translation to cs_CZ Czech for BambuStudio.
In the attachment I am sending the necessary files with translation, there is also a translation of the text.json file for cs_CZ for the web interface which belongs here https://github.com/bambulab/BambuStudio/blob/master/resources/web/data/text.js
it just needs to be inserted.

I am also attaching a photo.

I did the same procedure with the translation of OrcaSlicer and SuperSlicer, everything works as it should.

Thank you for your work.

![Snímek obrazovky 2023-06-13 175709](https://github.com/bambulab/BambuStudio/assets/99507763/f7fb4375-3f08-4d67-a362-e69c7f654ada)
![Snímek obrazovky 2023-06-13 175816](https://github.com/bambulab/BambuStudio/assets/99507763/b0439295-118d-4f7f-88d7-18dc6106a823)
![Snímek obrazovky 2023-06-13 175901](https://github.com/bambulab/BambuStudio/assets/99507763/b2e44ec9-9266-48c8-9f13-aa120cdeba7e)
![Snímek obrazovky 2023-06-13 180048](https://github.com/bambulab/BambuStudio/assets/99507763/bee7365d-b26e-46e4-b239-482b2bbac75a)
![Snímek obrazovky 2023-06-13 180113](https://github.com/bambulab/BambuStudio/assets/99507763/31cc172d-f00e-4bb8-9c41-21aff7703d10)
![Snímek obrazovky 2023-06-13 180239](https://github.com/bambulab/BambuStudio/assets/99507763/19bed3ad-a70d-4fb0-ac6f-369e4d7a582f)
![Snímek obrazovky 2023-06-13 180346](https://github.com/bambulab/BambuStudio/assets/99507763/533381e8-1c06-4698-8f3a-98f2e21cdf56)

**Comment by VentyCZ** [comment]
A similar work to the one in #1523
