### ISSUE TITLE
Tree supports generated sometimes misses one layer

### ISSUE THREAD

**Issue by tangcla** [bambulab/BambuStudio#1927]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

Slice project with tree supports. This only seems to occur sometimes, on certain projects.

### Actual results

When slicing the project, one layer of tree supports is either missing, or shifted to the side . This causes the print to fail in higher up layers.
Below are screenshots to show the same project, sliced differently (different tree style supports). Rotating the project does not seem to help. Changing the support style sometimes helps (ie. hybrid or strong MAY fix the problem) but doesn't always. In this project, it just causes the missing/misaligned layer to be at a different layer height.

 ![Screenshot 2023-06-14 081804](https://github.com/bambulab/BambuStudio/assets/8278114/7fc0e210-7621-4f6f-9e22-0e7abe8d117e)
![Screenshot 2023-06-14 081843](https://github.com/bambulab/BambuStudio/assets/8278114/2c895967-43bd-453c-ad0d-d3d0a928a565)
![Screenshot 2023-06-14 082201](https://github.com/bambulab/BambuStudio/assets/8278114/122940d1-469b-4599-afa1-603770ca864f)

### Expected results

The tree support 'trunks' should be printed with every layer intact.

### Project file & Debug log uploads

[DryPod with Hygrometer v8.zip](https://github.com/bambulab/BambuStudio/files/11739937/DryPod.with.Hygrometer.v8.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/11740012/log.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by Majestic7979** [comment]
I wonder if this is the same problem I had when I reported this issue: https://github.com/bambulab/BambuStudio/issues/1677

**Comment by pb4ugoout** [comment]
I ran into this same issue on the same model. I googled "x1c tree support shifted in middle" and ran across this git issue. 

Really just chiming in to mention that I'm using MacOS 13.5 with Bambu Studio 1.6.2.4 and I have the same artifact in the same location with the same model. I'm using a 2021 M1 Pro 14" Macbook Pro. Seems platform agnostic though.

I wonder if there's something odd about this particular model that is causing it since I haven't had the issue crop up with tree supports on any other model.

**Comment by tangketan** [comment]
This bug has been reported before and already fixed. Please wait for our new version which should be very soon.

**Comment by KPuzaks** [comment]
Hello. The issue is present again. Furthermore tree supports are generated through a model. S
![floating tree support1](https://github.com/bambulab/BambuStudio/assets/174014683/db111642-7473-47e7-b5cd-da55e0afa06f)
![floating tree support2](https://github.com/bambulab/BambuStudio/assets/174014683/af316791-3334-4cb7-9e8d-61fe278519ba)
![tree support through model](https://github.com/bambulab/BambuStudio/assets/174014683/3ea247db-cb8e-40d5-8535-ed39eb537396)
ee pictures attached.

**Comment by Majestic7979** [comment]
> Hello. The issue is present again. Furthermore tree supports are generated through a model. S ![floating tree support1](https://private-user-images.githubusercontent.com/174014683/343752695-db111642-7473-47e7-b5cd-da55e0afa06f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTcyMjYsIm5iZiI6MTcxOTUxNjkyNiwicGF0aCI6Ii8xNzQwMTQ2ODMvMzQzNzUyNjk1LWRiMTExNjQyLTc0NzMtNDdlNy1iNWNkLWRhNTVlMGFmYTA2Zi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxOTM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjY2Mzc0MzMzN2JkYmZiYTk3NWNmNThmYWYyYmIxMjNiYTU0OGY5ZDllMzg4N2RlYjE5MWIwOTA1YzRmMmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AQA8E9FC57BbjsaH_Iy0fzqVDrre3GyVzNnyZeBsxiA) ![floating tree support2](https://private-user-images.githubusercontent.com/174014683/343752707-af316791-3334-4cb7-9e8d-61fe278519ba.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTcyMjYsIm5iZiI6MTcxOTUxNjkyNiwicGF0aCI6Ii8xNzQwMTQ2ODMvMzQzNzUyNzA3LWFmMzE2NzkxLTMzMzQtNGNiNy05ZThkLTYxZmUyNzg1MTliYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxOTM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWY4ZGJkNGUwZTljMmYzNjRlOWNiNDFjZGI1MjA5NzUzMzMwZjc4NzM2M2QwMDU4NzU5NDk0MTdkZmJjMWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CDUJyWWe71ecTJaerMdzGbazSSGYmeEIL2UMdGFyDEY) ![tree support through model](https://private-user-images.githubusercontent.com/174014683/343752715-3ea247db-cb8e-40d5-8535-ed39eb537396.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTcyMjYsIm5iZiI6MTcxOTUxNjkyNiwicGF0aCI6Ii8xNzQwMTQ2ODMvMzQzNzUyNzE1LTNlYTI0N2RiLWNiOGUtNDBkNS04NTM1LWVkMzllYjUzNzM5Ni5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxOTM1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTkzOWE1OTY3MmM3MjZjYmQwNzA4ZWZhNTliMjRjMTNiNTkyMjk0ZmZhOTgwNWY1YTczYzBmYmEzYTA4NjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YMMtimU9h7R27Q2FnYC7Ixr7mfEVR6RfbQDAYQ4SCXs) ee pictures attached.

I think you must open a new issue. You can reference this. But because you're not OP you cannot reopen directly and because it's closed there is no guarantee that BL will see your report or act on it, please open new issue, reference this one if you want.
