### ISSUE TITLE
Touch controls moves bed/printed object the other way

### ISSUE THREAD

**Issue by tomas-cs** [bambulab/BambuStudio#1943]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

1. Open any stl (or other geometry file) in Bambu Studio
2. On touch screen, use 2 fingers to move the bed around.

### Actual results

When you move your fingers to left, bed with object to print moves to right. When you move fingers up, bed moves down. This is complete oposite of what is expected. For example Fusion 360 works right - fingers moved right, object moves right. Can you please fix it so it works the same way?

### Expected results

Bed and sliced object moves in the direction where I move fingers, not the oposite side.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/11796607/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
