### ISSUE TITLE
BambuStudio got an unhandled exception: Calling AppConfig::save() from a worker thread

### ISSUE THREAD

**Issue by ferenj-gs** [bambulab/BambuStudio#1944]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Processor	12th Gen Intel(R) Core(TM) i7-1260P, 2100 Mhz, 12 Core(s), 16 Logical Processor(s)
Installed Physical Memory (RAM)	32,0 GB
Adapter Type	NVIDIA T550 Laptop GPU, NVIDIA compatible
Adapter Type	Intel(R) Iris(R) Xe Graphics Family, Intel Corporation compatible

### Printer

X1-Carbon

### How to reproduce

1. Create App profile under windows Graphics settings for bambu studio to use the dedicated T550 GPU
2. Start Bambu Studio

### Actual results

 Crash happens immediately
<img width="473" alt="image" src="https://github.com/bambulab/BambuStudio/assets/134397015/4b53ed37-eddb-4dd3-96b4-40e67e6d4aff">

after hitting ok:

<img width="512" alt="image" src="https://github.com/bambulab/BambuStudio/assets/134397015/f2cfaad1-8335-4209-b85b-1e4b9ed2a641">

### Expected results

Bambu studio should start normally.

### Project file & Debug log uploads

[debug_network_Tue_Jun_20_10_58_31.zip](https://github.com/bambulab/BambuStudio/files/11798118/debug_network_Tue_Jun_20_10_58_31.zip)

FYI: 0 byte logfile is generated, most probably as this is a startup issue

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112537880/39ff08d5-d8dd-4ead-94f4-45a519115365)

Please create a minidump when this dialog show.
You can create minidump with the following steps:
* Open the Windows Task Manager
* Find and select the Bambu Studio process in it
* Right click the process and choose the 'Create Minidump File' menu item
* Select a folder to save the file

**Comment by lanewei120** [comment]
@ferenj-gs 
thanks for reporting this issue

is this issue reproducible?

from log
![image](https://github.com/bambulab/BambuStudio/assets/106916061/54e9d415-c41e-4bf0-ae8a-2a52ac305d14)
it seems the thread_name of BambuStudio is wrong in your environment
it cause the context check failed

and what does this mean "Create App profile under windows Graphics settings for bambu studio to use the dedicated T550 GPU"

**Comment by lanewei120** [comment]
> is this issue reproducible?

@CrashTestCoder 

is this issue 100% reproducible?

**Comment by CrashTestCoder** [comment]
Will verify when I get back to my computer in the morning. But it persisted through reinstalling the software and multiple reboots. 

Disabling the manual gpu selection fixed it immediately

**Comment by CrashTestCoder** [comment]
I just tested on my old personal laptop and it is not reproducible with a Nvidia 940mx. So maybe its just a problem with quadros? Will report back in the morning

**Comment by CrashTestCoder** [comment]
Can confirm. 100% reproducible. 
![image](https://github.com/bambulab/BambuStudio/assets/11007649/3e1f623b-8d95-46e6-bbad-fbbec9b3c003)
![image](https://github.com/bambulab/BambuStudio/assets/11007649/ddd06144-02bf-4f79-8aaf-92be26a24e0e)
![image](https://github.com/bambulab/BambuStudio/assets/11007649/ee5a4819-01d1-4973-9817-b11afa074cea)

[debug_network_Thu_Jul_27_07_19_04.log](https://github.com/bambulab/BambuStudio/files/12182679/debug_network_Thu_Jul_27_07_19_04.log)

### PC Hardware:
Device name	<REDACTED>
Full device name	<REDACTED>
Processor	11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Device ID	<REDACTED>
Product ID	<REDACTED>
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

![image](https://github.com/bambulab/BambuStudio/assets/11007649/fcf8f4da-1129-411f-84f8-4d0602ccdc35)
![image](https://github.com/bambulab/BambuStudio/assets/11007649/f33647b4-63a6-4f42-9d0c-bf54fa9bb192)

**Comment by lanewei120** [comment]
thanks very much
it should be a similiar issue as https://github.com/prusa3d/PrusaSlicer/issues/9420
we will fix it soon

thanks

**Comment by lanewei120** [comment]
already fixed in v1.7.2.51 hotfix version
