### ISSUE TITLE
Print Sequence by Object + Height Range Modifier (+Colors) = Error/Crash

### ISSUE THREAD

**Issue by lmnx** [bambulab/BambuStudio#1947]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 (x86-64), MacOS Ventura (arm64)

### Printer

X1C + AMS

### How to reproduce

1. Print Sequence: "By object"
2. Add 2 objects
3. Create height range modifiers for one object and modify color once at any layer
5. Slice
6. Get error message or crash

### Actual results

Crash or get error message:

"A fatal error occurred: "Access violation"
Please save your project and restart the application."

### Expected results

Slice normally

### Project file & Debug log uploads

[debug_Fri_Jun_23_14_04_37_1532.zip](https://github.com/bambulab/BambuStudio/files/11845771/debug_Fri_Jun_23_14_04_37_1532.zip)
[Cube.zip](https://github.com/bambulab/BambuStudio/files/11845772/Cube.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
I have tested with latest code base. The UI can't change color, and also has some other abnormal behaviour. Shown as gif below.
![height range颜色问题](https://github.com/bambulab/BambuStudio/assets/110660407/f7f0411d-da84-4756-adbf-f4174733c1c7)
@bambu123 Please have a check and fix the UI issue first and we will check whether still has crash.

**Comment by SaltWei** [comment]
Fixed in internal version. Will be included in next user release version

**Comment by lmnx** [comment]
@SaltWei awesome! Waiting to test and will mark this issue as done.

**Comment by jaddel** [comment]
Please also have a look a this one, I guess it's directly related.

https://github.com/SoftFever/OrcaSlicer/issues/1272

**Comment by SaltWei** [comment]
> Fixed in internal version. Will be included in next user release version

Has be included in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53. And slicing is normal in my environment.

Could someone help to double check?

**Comment by lmnx** [comment]
Thanks, everyone. Looks fixed.

**Comment by lmnx** [comment]
Thanks, everyone. Looks fixed.
