### ISSUE TITLE
[Feature Request] wrapping a vector graphic over a stl object and apply different colors to the design

### ISSUE THREAD

**Issue by thrutheframe** [bambulab/BambuStudio#196]
It would be cool if users can "wrap" a vector graphic /dxg/etc over an object and apply different colors to the design. Something like a coloring book approach. It would set BL Studio apart from the other slicers.

**Comment by YifanWuBambu** [comment]
Hi @thrutheframe ,
This feature is in our plan, maybe not in recent release.
Thanks a lot for the suggestion!

**Comment by thrutheframe** [comment]
thanks
