### ISSUE TITLE
Add Russian language

### ISSUE THREAD

**Issue by stasyan68** [bambulab/BambuStudio#1960]
[ru.zip](https://github.com/bambulab/BambuStudio/files/11860828/ru.zip)

**Comment by AndylgTom** [comment]
@stasyan68 
1. First they must fix the text display problem https://github.com/bambulab/BambuStudio/issues/1707 .
2. The translation that you posted is is very bad, better delete it and take it from the topic that I posted above. It is a test, not final.

1. Сначала они должны пофиксить проблему отображения текста, что описана здесь https://github.com/bambulab/BambuStudio/issues/1707 .
2. Перевод что вы выложили, очень кривой, лучше удали его и возьми из той темы что выше я выкладывал. Он тестовый, не окончательный.

**Comment by iStarComLab** [comment]
> @stasyan68
> 
> 1. First they must fix the text display problem [Wrong encoding - cyrillic #1707](https://github.com/bambulab/BambuStudio/issues/1707) .
> 2. The translation that you posted is is very bad, better delete it and take it from the topic that I posted above. It is a test, not final.
> 
> на русском
> 
> 1. Сначала они должны пофиксить проблему отображения текста, что описана здесь [Wrong encoding - cyrillic #1707](https://github.com/bambulab/BambuStudio/issues/1707) .
> 2. Перевод что вы выложили, очень кривой, лучше удали его и возьми из той темы что выше я выкладывал. Он тестовый, не окончательный.

Проверил твой перевод))) От стасяна68 точнее и аккуратнее, свой не показывай ни кому лучше!

**Comment by AndylgTom** [comment]
> > @stasyan68
> > 
> > 1. First they must fix the text display problem [Wrong encoding - cyrillic #1707](https://github.com/bambulab/BambuStudio/issues/1707) .
> > 2. The translation that you posted is is very bad, better delete it and take it from the topic that I posted above. It is a test, not final.
> > 
> > на русском
> > 
> > 1. Сначала они должны пофиксить проблему отображения текста, что описана здесь [Wrong encoding - cyrillic #1707](https://github.com/bambulab/BambuStudio/issues/1707) .
> > 2. Перевод что вы выложили, очень кривой, лучше удали его и возьми из той темы что выше я выкладывал. Он тестовый, не окончательный.
> 
> Проверил твой перевод))) От стасяна68 точнее и аккуратнее, свой не показывай ни кому лучше!

Ну-ну... не понятно кто говорит. Ты наверно попутал. Вот скрин примера сравнение перевода, то что нашел за минуту. И как такое? 
![111](https://github.com/bambulab/BambuStudio/assets/20997012/4f2363bb-2629-49a8-81e6-e2320b0577f4)


Во первых, перевод не окончателен как я и написал, ибо проверить всё не представляется возможности из-за глюка в кодировке. 
Во вторых, видно что он подглядывал в перевод Пруши, основным автором которого являюсь я, но это ему не очень помогло.

**Comment by iStarComLab** [comment]
>>>перевод Пруши, основным автором которого являюсь я, но это ему не очень помогло.
Это хорошо что Вы автор, но баг известный https://github.com/SoftFever/OrcaSlicer/issues/757
И походу пока разработчик не исправит кодировку - перевод будет кастрированный.
Я дико извиняюсь что мог задеть Вас но не в коем случае не подумайте ничего нехорошего, просто в таком виде переводы не выкладывают от сюда и такая реакция была с моей стороны. Допилите перевод а мы оценим по достоинству!

**Comment by iStarComLab** [comment]
туда же https://github.com/SoftFever/OrcaSlicer/discussions/600

**Comment by lanewei120** [comment]
@StoneLiBambulab please followup this requirement

**Comment by StoneLiBambu** [comment]
added in 1.8， closed
