### ISSUE TITLE
Can't close BambuStudio if I don't want to save the file

### ISSUE THREAD

**Issue by samcooler** [bambulab/BambuStudio#1961]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

macOS latest

### Additional system information

macbook pro M1

### Printer

P1P

### How to reproduce

Make a temporary project in BS. Something I don't care about saving. Have "save without prompting" config set, so there's no popup question. Try to quit BS. Be asked to save the file. But I don't want to. If I hit cancel, it goes back to BS. But I want to quit.

### Actual results

I can't quit if I don't want to make a save file.

### Expected results

There should be a path out of BS for when I don't want to save. Additional button somewhere, or cancel in the dialog takes me to a question dialog that I can reply No Save to.

### Project file & Debug log uploads

not necessary

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bambu123** [comment]
Close as fixed in the 1.7 beta version.
