### ISSUE TITLE
Displayed number of layer count jumping

### ISSUE THREAD

**Issue by Panda631** [bambulab/BambuStudio#1969]
### Bambu Studio Version

1.6.4.2

### Where is the application from?

Bambu Lab Official website

### OS version

Win11

### Additional system information

Ryzen7

### Printer

X1C & 2xAMS

### How to reproduce

1. open attached file
2. Slice the plate.
3. Move the right slider to the most top position. 
4. Layer count is 611
5. Move the slider below layer 590.
6. Layer count jumps to 1147!

![grafik](https://github.com/bambulab/BambuStudio/assets/138193590/b7b98d66-5058-41ed-9753-dfc44bd76cf4)

![grafik](https://github.com/bambulab/BambuStudio/assets/138193590/6aeb3e67-5789-46ff-8b84-d649d80977c8)

### Actual results

Layer count jumps

### Expected results

Layer count should be correct

### Project file & Debug log uploads

[Layer_counter.zip](https://github.com/bambulab/BambuStudio/files/11913592/Layer_counter.zip)

[debug_Fri_Jun_30_07_58_12_11356.log.zip](https://github.com/bambulab/BambuStudio/files/11913658/debug_Fri_Jun_30_07_58_12_11356.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by redsector72** [comment]
This bus still present, fixed in Orca

**Comment by lanewei120** [comment]
@redsector72 @Panda631 

previously we thought it is a same issue with 1967
and we can not reproduce it here 
![image](https://github.com/bambulab/BambuStudio/assets/106916061/a97da0bc-8858-476f-ac95-ea0f1ce9a5cf)
![image](https://github.com/bambulab/BambuStudio/assets/106916061/ac49f75e-8c05-4cf2-81bc-4e5e80af39fa)

are you using the 3mf attached above?
and are you using the newest version of Bambu Studio(v1.7.4)?

**Comment by Panda631** [comment]
This issue seems to be solved in V1.7.4.52.
I can't reproduce any more.

**Comment by SaltWei** [comment]
> This issue seems to be solved in V1.7.4.52.

Thanks for checking!

But actually we do nothing.
Close at the moment. Reopen if can be reproduced again.
