### ISSUE TITLE
Filament calibration dialog is empty and can't set

### ISSUE THREAD

**Issue by michelem09** [bambulab/BambuStudio#1974]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS 13.4.1

### Additional system information

Language is set to English

### Printer

Bambu lab P1P

### How to reproduce

1. Go to device
2. Click "Edit" icon on Ext Pool image
3. Filament select is empty

### Actual results

I can't select any filament

<img width="523" alt="Screenshot 2023-07-05 at 15 13 15" src="https://github.com/bambulab/BambuStudio/assets/439555/fbb93fb5-fb29-4f46-8127-07b51a65e431">

### Expected results

I expect to be able to select a filament

### Project file & Debug log uploads

It's not related to a specific project.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by michelem09** [comment]
Please let me know me if I can help fixing this I'm available for debugging. The 1.7.0 beta does the same.

**Comment by michelem09** [comment]
I just downloaded the 1.7.0 beta2 and it seems to be fixed! Great!
I will do some tests.

<img width="487" alt="Screenshot 2023-07-14 at 07 27 04" src="https://github.com/bambulab/BambuStudio/assets/439555/4512c885-f2fa-4360-a5c9-2e7efbd4b7d2">

**Comment by walterwongbbl** [comment]
it's great.
We are also testing calibration
