### ISSUE TITLE
Cut Tool-  Add Key option

### ISSUE THREAD

**Issue by schreiaj** [bambulab/BambuStudio#198]
When cutting a model allow adding a key feature - a simple cube boolean cut from the model and then a key part added would be nice. You can already do this manually but having an option to just do it automatically and ensure the positioning would be convenient. 
<img width="653" alt="Screenshot 2022-09-02 at 8 32 24 AM" src="https://user-images.githubusercontent.com/329127/188183864-00419f69-4242-444c-9654-4ad4859b246c.png">

**Comment by schreiaj** [comment]
Expanding on the how after a bit of experimentation: 

The intersection of the cut plane and the model will generate a polygon. There's two approaches here - the first one involves simply finding the centroid of the polygon and placing the key there. The other option is computationally more involved but may result in more robust parts - picking a series of points within the bounds of the polygon and finding the top N (where N is configurable) based on some criteria like distance from edge and thickness of part at point.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/b97afe3b-b33b-4036-919f-8e6fed6d5cbf)
It has improved in the latest version, you can have a try.
