### ISSUE TITLE
Add Wall Loop(s) Option to Normal Supports

### ISSUE THREAD

**Issue by djngnear** [bambulab/BambuStudio#1991]
**Is your feature request related to a problem? Please describe.**
Half of the support interface layers have nothing to connect to when using normal supports (mainly snug supports).

**Describe the solution you'd like**
An option to add wall loops around normal (snug and grid) supports. Just like when using tree supports.

**Describe alternatives you've considered**
An alternative is to use hybrid tree supports.

**Normal Supports:**
![BS Support Wall Issue Pic 1](https://github.com/bambulab/BambuStudio/assets/87901234/dbc35794-0dca-4865-b84e-51d9d4f07298)

**Hybrid Tree Supports:**
![BS Support Wall Issue Pic 2](https://github.com/bambulab/BambuStudio/assets/87901234/2fc15f8f-1829-4eeb-9c63-78d9693439f2)

**Comment by tangketan** [comment]
Official 1.8 has been released and this feature is added. Close this issue.
