### ISSUE TITLE
Update on Bambu Cube by thurtheframe

### ISSUE THREAD

**Issue by thrutheframe** [bambulab/BambuStudio#1992]
Thank you for choosing my Bambu Cube design as one of the Benchmark models for the upcoming version of Bambu Slicer 1.7

There was a recent update to the design of the cube, now version 2. You may want to use the updated design as it has additional bridging features. 

STL can be downloaded here. 
https://www.printables.com/model/222285-bambu-lab-xyz-calibration-cube

**Comment by DanBao-Bambu** [comment]
Thank you very much for providing the Bambu Cube V2 model. We have added it as an entire STL to the right-click menu while retaining the original Bambu Cube model. Thank you very much for your contribution and look forward to your valuable feedback again.
