### ISSUE TITLE
v1.7.0 Public Beta, Windows 10, Login impossible Blank login screen

### ISSUE THREAD

**Issue by rainbowat** [bambulab/BambuStudio#1995]
### Bambu Studio Version

1.7.0

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

Bambu Lab X1

### How to reproduce

I just clicked login and Blank login screen

### Actual results

Blank login screen

### Expected results

login screen

### Project file & Debug log uploads

![Bez ](https://github.com/bambulab/BambuStudio/assets/138976202/d58bd543-e2ca-4c21-90be-ed77b88aeb67)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bambu123** [comment]
This maybe a network problem. Please try again some time later.

**Comment by seler** [comment]
I have exactly the same issue in v1.7.0 Public Beta 2. Also, it does not see my printer in LAN (without login).

**Comment by rainbowat** [comment]
After two weeks, no change
It still doesn't work for me.

**Comment by rainbowat** [comment]
> @rainbowat I was able to overcome the problem by downgrading to 1.6, logging in there and then upgrading back to 1.7.

I just started using orca-slicer

**Comment by rnunez24** [comment]
I'have same isue 1.7.1.62 version.

**Comment by bambu123** [comment]
> I'have same isue 1.7.1.62 version.

Please send me the log files.
Remove cache directory %LOCALAPPDATA%\BambuStudio\EBWebView and retry.

**Comment by rnunez24** [comment]
[debug_Fri_Aug_04_11_40_42_3712.log.0.txt](https://github.com/bambulab/BambuStudio/files/12259890/debug_Fri_Aug_04_11_40_42_3712.log.0.txt)
![2023-08-04_12-37](https://github.com/bambulab/BambuStudio/assets/48137270/e2d9f039-2b41-441b-8ee0-e7fe5cee529e)

Cache deleted and retryed. 
Uninstalled and reinstalled tried

**Comment by rnunez24** [comment]
Solved: in preparation view an advertisement of network plugin appears. 

Installed & now the login works.

![2023-08-04_12-45](https://github.com/bambulab/BambuStudio/assets/48137270/c2a23e3b-a2b4-44d6-8bed-cde2555bf5eb)

**Comment by arnrist** [comment]
I experienced the same issue, but different resolution. Placing a comment here in case there is something to do in the application - or other have the same issue.
In my case the network plugin were installed.
First install on a windows 10 PC.
Version 1.7.2.51.

In my case the "Language" was not selected in the General Settings.
After I went to Preferences and selected the language, I was immediately able to get the login screen.

I had tried multiple settings before this, including reinstalling the application, checking the firewall settings, verifying the Network plugin etc.
The language setting fixed it for me.

**Comment by bambu123** [comment]
> I experienced the same issue, but different resolution. Placing a comment here in case there is something to do in the application - or other have the same issue. In my case the network plugin were installed. First install on a windows 10 PC. Version 1.7.2.51.
> 
> In my case the "Language" was not selected in the General Settings. After I went to Preferences and selected the language, I was immediately able to get the login screen.
> 
> I had tried multiple settings before this, including reinstalling the application, checking the firewall settings, verifying the Network plugin etc. The language setting fixed it for me.

@arnrist Thank you for your solution. To fix this problem totally, could you please send me your logs for analyzing?

**Comment by bambu123** [comment]
Fixed in v1.8.2.
