### ISSUE TITLE
Remember open directory when saving project

### ISSUE THREAD

**Issue by cxen** [bambulab/BambuStudio#1996]
**Is your feature request related to a problem? Please describe.**
BambuStudio does not seem to remember the folder directory from which an .stl was opened. This is annoying when saving a project, because the save dialogue opens at the last saved directory, often a completely different project.

**Describe the solution you'd like**
I would like BambuStudio to remember the directory from which an .stl has been opened and offer that directory in the save project dialogue. PrusaSlicer does this already.

**Comment by bambu123** [comment]
This has been fixed in the new 1.7 beta version. Are you using the new version.

**Comment by cxen** [comment]
> This has been fixed in the new 1.7 beta version. Are you using the new version?

I just tried the 1.7 beta and it works, thank you
