### ISSUE TITLE
STL file is not remembered when saving/exporting

### ISSUE THREAD

**Issue by cxen** [bambulab/BambuStudio#1998]
How to reproduce the problem:
1. Open any .stl
2. Do a Save Project/Save project As/Export
3. Check save dialogue window for autofilled file name

The .stl file name is not respected and instead get the results in the attached screenshot.

![image](https://github.com/bambulab/BambuStudio/assets/46993334/2375d1b4-16e9-4c5c-98f2-d2d395059eda)

**Describe the solution you'd like**
Exporting and Saving should respect the original name of the .stl or stl object in the slicer. Check PrusaSlicer for intended behaviour.

**Comment by bambu123** [comment]
This has been fixed in the new beta version.
