### ISSUE TITLE
[Feature Request] Ability to pause the print a given layer

### ISSUE THREAD

**Issue by rwoldberg** [bambulab/BambuStudio#200]
I would like to have the ability to pause the print at a given layer, this would give the ability to drop in parts while printing and have them embedded in the print.

**Comment by ChrisG-hub** [comment]
This already in the software, from the first version. Just right click the green slider after slicing.
you really got to learn your slicer... :-)
![image](https://user-images.githubusercontent.com/74129531/188228593-fe933bbb-50ab-41cb-ba5c-2ae5098b6fe5.png)

**Comment by rwoldberg** [comment]
Nice.  Not intuitive but that works.  Thanks.

**Comment by ChrisG-hub** [comment]
Its been there in Prusa, Bambu, Superslicer and the original source where all these slicers been build on, but i can imagine coming from an other slicer it would be nice to explore and learn the ins and outs. Good luck printing. Its a hell of a machine.

**Comment by rwoldberg** [comment]
I have primarily used Simplify3d.  Regardless of how many slicers it is in, it is still not intuitive.  Slider generally don't have right click functionality.   It is a hidden feature that you would never find unless you randomly start clicking on stuff. But I am glad it is there.
