### ISSUE TITLE
[Issue] & symbol breaks 3mf saves.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#2001]
Problem: Any time you use the & symbol with the built in text shape maker and save the file you will get the error "The file does not contain any geometry data" when reopening the file.

**Comment by bambu123** [comment]
It is fix in the new 1.7 beta version. Are you using the new version?

**Comment by tedtred** [comment]
No i am running the main release version 1.6.2.4. If its been solved in the beta version thank you for already solving the problem.
