### ISSUE TITLE
Rabbit Ears

### ISSUE THREAD

**Issue by schwa** [bambulab/BambuStudio#2002]
Adding a brim around the entirety of an object isn't always necessary for bed adherence. Often it is just the corners of large parts that curl up.

In these cases it's sometimes superior to add "rabbit ear" style brims at just the corners. While we can do this in our CAD software or by adding 0.2mm (or whatever layer height) flat cylinders a the correct locations - these approaches kind of suck.

Neither approach is good at leaving a small gap between the brim and the model. 

So I'd love a tool to add rabbit ears while preparing to print.

**Comment by Linnie73** [comment]
The feature you want is called "mouse ears" and is requested in issue #1393 :)
