### ISSUE TITLE
"Flush into this object" (and other flush options) crashes Bambu Studio

### ISSUE THREAD

**Issue by tangcla** [bambulab/BambuStudio#2007]
### Bambu Studio Version

1.7

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

1. Load two objects
2. Set one of the objects to a different colour
3. Right-click one of the objects --> Flush options --> flush into this object OR flush into objects' infill OR flush into objects' support
![image](https://github.com/bambulab/BambuStudio/assets/8278114/928cbc25-529a-4696-b5ae-66c2609783df)

### Actual results

Mouse cursor turns into hourglass, program crashes

### Expected results

I expected my flush option to be enabled.
I also was unable to find another way to 'flush into this object' in the left-hand pane menu, despite me using the search and it showing as an option.
![image](https://github.com/bambulab/BambuStudio/assets/8278114/5749354e-9914-4b53-a7d5-c62ce1bf9836)

### Project file & Debug log uploads

[flush_test.zip](https://github.com/bambulab/BambuStudio/files/11994975/flush_test.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/11994977/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
Thanks! We will fix asap.

**Comment by jphoke** [comment]
Confirming this also happens on macOS 13.4.1 and current beta Studio

**Comment by LiZ-Li-BBL** [comment]
We fixed this issue on v1.7.0 Public Beta 2 (https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.65)
