### ISSUE TITLE
Embedded depth field in text tool overwrites value field

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#2013]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

10th gen Core i5
32GB RAM
RTX3060

### Printer

NA

### How to reproduce

1. Open new project
2. Place a primitive and select the text tool

### Actual results

Label and value field overlap. I don't recall this behavior in v1.6
![image](https://github.com/bambulab/BambuStudio/assets/96731892/06ca78b9-8125-48e9-93cb-6085a85c6878)

### Expected results

Wider dialog box or multi-line label. 

### Project file & Debug log uploads

Not needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by TicktonFlyer** [comment]
Why has this Bug not been fixed in Version 1.7.4.52

**Comment by LiZ-Li-BBL** [comment]
Hello,
This issue has been fixed. Please update the latest version of BambuStudio.
