### ISSUE TITLE
Flow calibration checkbox unticked status not retained between prints

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#2014]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

10th gen Core i5
32 GB
RTX3060

### Printer

X1C

### How to reproduce

1. Send any print to the printer.
2. Untick Flow Dynamics Calibration checkbox
3. Send print again, observe status of checkbox

### Actual results

Checkbox status is not retained between prints
![image](https://github.com/bambulab/BambuStudio/assets/96731892/bbf2807b-ba02-48f0-900e-a80e1a8b29e1)

### Expected results

This behavior was fixed in v 1.6 but seems to have made its way back in 1.7. 
Item 8 in 1.6 release notes _"Retain the most recent print settings for bed leveling, flow calibration, and timelapse to streamline the user experience https://github.com/bambulab/BambuStudio/issues/487 https://github.com/bambulab/BambuStudio/issues/1035 https://github.com/bambulab/BambuStudio/issues/1081"_

### Project file & Debug log uploads

None required

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. What type of bed do you have PTE?

**Comment by MadMax389** [comment]
I usually use a 3rd party plate with plate detection off. I have modified my PLA filament profile to to use 60C bed temp on all plates so I don't need to think about what plate is selected (except for textured plate which lowers the nozzle a little bit). I normally leave cool plate selected.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/1dd5d602-56b0-4da6-83a1-2b735a8d0e63)

**Comment by walterwongbbl** [comment]
Sorry, this issue does exist and we will fix it

**Comment by walterwongbbl** [comment]
Please update the latest studio version
