### ISSUE TITLE
"Manage Result" in Flow Dynamics calibration shows wrong Filament Preset

### ISSUE THREAD

**Issue by ManfredAdler** [bambulab/BambuStudio#2016]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

X1C

### How to reproduce

1. Go to Flow Dynamics 
2. Click on Auto-Calibration
3. Select User-Defines filament profile ("extrudr PETG" in this case) 
![grafik](https://github.com/bambulab/BambuStudio/assets/60928199/2612b97c-5e9e-4106-8360-4bc19984bc4f)
![grafik](https://github.com/bambulab/BambuStudio/assets/60928199/8affb9bd-f3db-4a56-946f-523d4d736088)
4. Click on Calibrate
5. Calibration runs based on the chosen filament preset (I checked by looking at the temperatures of nozzle and bed)
6. Give the calibration a name and save it to printer
7. Go to Flow Dynamics --> Manage Result and view the results.

### Actual results

1. "Name" and "Factor K" of the saved values are correct, but the "Filament Preset" shown is wrong "extrudr **X**PETG" instead of "extrudr PETG", which is another one of my user-defined profiles, see the list in the first screenshot:
2.  
![grafik](https://github.com/bambulab/BambuStudio/assets/60928199/efe302f4-c7d3-42a5-b784-98ae444e5cef)

3. Did this 2 times with the same result. To make it clear: Calibration is done with the right profile, only the shown reference is wrong.

### Expected results

The correct Filament Preset ("extrudr PETG") is shown in the results view, to remember which filament preset the calibration was done with.

### Project file & Debug log uploads

Project won't help.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Thanks!  It has been fixed in 01.07.00.65
