### ISSUE TITLE
?????? ?????? replacing text

### ISSUE THREAD

**Issue by kolomiecalexa2** [bambulab/BambuStudio#2018]
### Bambu Studio Version

1.7

### Where is the application from?

Bambu Lab github releases

### OS version

Win11

### Additional system information

hello, I have a problem with language files. when installing the Russian language and when slicing instead of text ?????? can you tell me how this can be fixed ? and when will you be able to change the Russian language to the standard settings?(I have attached the translation file if you can add the Russian language, please, without it in any way)

### Printer

bambu Lab X1 Carbon

### How to reproduce

after replacing the language file in the Bambu_Studio_win-v01.07.00.53-20230707211436\resources\i18n folder, everything was transferred perfectly, but in the tips and upper buttons instead of text ?????

### Actual results

![Снимок экрана 2023-07-11 142233](https://github.com/bambulab/BambuStudio/assets/139219424/535e362d-5e80-4b04-b6a7-10f2121646c7)

### Expected results

russian text

### Project file & Debug log uploads

https://github.com/SoftFever/OrcaSlicer/issues/1462  link to the translation file

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by lanewei120** [comment]
Hello, @kolomiecalexa2 

this is just because the Russian language selection missing, which leads to the fonts of Russion not loaded by imgui

we are considering to add Russian support next version

could you update your pot file based on our newest codes and submit it to github?

**Comment by LiZ-Li-BBL** [comment]
You need to select the correct language from the preferences settings so that part of the text which appears as "?" will be loaded properly. Unfortunately this is not working at present.

We plan to add Russian to preferences settings in the future.

**Comment by kolomiecalexa2** [comment]
[BambuStudio_ru.zip](https://github.com/bambulab/BambuStudio/files/12067811/BambuStudio_ru.zip)
g

translated using Poedit by Google Machine translation.

**Comment by iStarComLab** [comment]
та же тема https://github.com/SoftFever/OrcaSlicer/issues/757

**Comment by iStarComLab** [comment]
> You need to select the correct language from the preferences settings so that part of the text which appears as "?" will be loaded properly. Unfortunately this is not working at present.
> 
> We plan to add Russian to preferences settings in the future.

*****************************************************************
Добрый день, когда ждать данное решение?

**Comment by iStarComLab** [comment]
РЕШЕНО!

**Comment by LiZ-Li-BBL** [comment]
We have added support for several new languages including Russian.
