### ISSUE TITLE
Impossible to use Beta 1.7.0.53

### ISSUE THREAD

**Issue by foresta86** [bambulab/BambuStudio#2020]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

Impossible to use the new features of this beta because it says printer is not updated to latest version but there is no newer version than 01.05.02.00

### Actual results

![2023-07-11 16 05 32](https://github.com/bambulab/BambuStudio/assets/25081296/d5a8b6ee-fd70-41ad-ae6b-bd23d3ca338c)

### Expected results

A newer firmware

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12015561/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by intdel** [comment]
The firmware is still in beta.

**Comment by foresta86** [comment]
> The firmware is still in beta.

And is there a way to download it as I did for Bambu Studio beta?

**Comment by intdel** [comment]
No the sign up is already closed:

https://forum.bambulab.com/t/opportunity-to-join-our-x1-firmware-beta-test/8134

**Comment by foresta86** [comment]
Thanks
