### ISSUE TITLE
Remove misleading picture from wiki regarding calibration

### ISSUE THREAD

**Issue by intdel** [bambulab/BambuStudio#2021]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

X1C

### How to reproduce

1. Go to https://wiki.bambulab.com/en/software/bambu-studio/calibration_pa
2. Use (human) eyes to look at picture in step (3) Calibration printing in progress.
3. Use (human) eyes and brain to recognize textured PEI plate in picture

### Actual results

Picture of textured PEI sheet.

### Expected results

Should not show textured PEI plate, because it is not compatible, as mentioned earlier in the wiki.

### Project file & Debug log uploads

[https://wiki.bambulab.com/software/bambu-studio/calibration/pa_auto_cali.jpg](url)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by bambu123** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112537880/3a82dca0-3a37-4092-a34b-7dfe4287252e)

**Comment by zhimin-zeng-bambulab** [comment]
@intdel  Thank you very much for pointing out this issue. We have updated the image on the wiki and will update the software image in the next version.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in the latest version.
