### ISSUE TITLE
Temperature at 140 after failed first layer detection

### ISSUE THREAD

**Issue by PowerChaos** [bambulab/BambuStudio#2022]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Additional system information

I7 7700K and not related to this bug report xD

### Printer

X1C

### How to reproduce

download beta
slice a file
use transparatent  filament
first layer detection found a error
it put it to 140 degree
continue print
it stays at 140 degree

### Actual results

as seen below , it stays at 140 degree and that cause the print to fail

![image](https://github.com/bambulab/BambuStudio/assets/7650333/889b1a2c-6597-4579-862c-adea8dbb6c34)

### Expected results

it should go back to last value ofcourse

<img width="632" alt="image" src="https://github.com/bambulab/BambuStudio/assets/7650333/96210c5c-a2b5-457c-aadc-9b6f5624c376">

### Project file & Debug log uploads

instead of files i going use this part to add some extra info 
as the log files most likely wont add any more ifno , unless i upload the encrypted printer log files

i also use the new matching beta firmware, i can not rule out if it is firmware or slicer
only that it happends with both in use , if i use orca slicer ( 1.6 ) then i do not have that problem

This makes it pôint out to a slicer issue instead of a firmware issue
or a combination of both as the new firmware need the new slicer for certain functions to work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
This should be a printer bug and has already been fixed in the latest firmware.
