### ISSUE TITLE
Some geometry corrupting projects in 1.7.0 beta

### ISSUE THREAD

**Issue by RyanEwen** [bambulab/BambuStudio#2041]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab P1P

### How to reproduce

1. Create a new project.
2. Add the attached STEP file model.
3. Save the project.
4. Close and reopen project.

I am not sure if this is limited to 1.7.0 beta or if it might also affect previous versions.

I have corrupted 2 projects and unsure how to recover them. Any tips would be appreciated.

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/1136808/fef94b07-53ce-44b4-8afb-d17e7200b89a)

### Expected results

Project open as normal.

### Project file & Debug log uploads

[Inner & Outer.zip](https://github.com/bambulab/BambuStudio/files/12042805/Inner.Outer.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by DokuKaefer** [comment]
Problem is the **&** in the **_step_** file.
Remove it, open it, Save the project and it works.

**Comment by RyanEwen** [comment]
Even if it the step file is the root cause, I think the slicer should still be able to reopen the project again, especially since it was able to create the project and print it and save it without issues or errors. Why does it treat it differently only after saving it?

**Comment by DokuKaefer** [comment]
Good question, that must answer us a programmer.

**Comment by bambu123** [comment]
Maybe @DokuKaefer is right. But this shoud be fixed in the 1.7 version. We'll check it again.

**Comment by RyanEwen** [comment]
> Problem is the **&** in the **_step_** file. Workaround: Remove it, open it, Save the project and it works.

I can't seem to find the `&` in the `.step` file when opening it with VS Code. Can you show me where it is?

**Comment by DokuKaefer** [comment]
> > Problem is the **&** in the **_step_** file. Workaround: Remove it, open it, Save the project and it works.
> 
> I can't seem to find the `&` in the `.step` file when opening it with VS Code. Can you show me where it is?

the & in the filename of the step file is the problem. 
Rename it like inner_outer.step

**Comment by RyanEwen** [comment]
Ah I see. Looks like if I just rename it within the slicer by hitting F2 on it, that works as well
![image](https://github.com/bambulab/BambuStudio/assets/1136808/cd49b01a-03b2-4161-93e3-a202bdbf3bfb)

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in the latest version.
If you use the new version of the software to save the model file with & in the name, it can be opened normally with the new version.
