### ISSUE TITLE
Skirt Extending Beyond Plate Boundary

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#2043]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

10th gen Core i5
32GB
RTX3060

### Printer

P1P

### How to reproduce

This project was saved in v1.6 and opened in 1.7.0.65

1. Load uploaded project file
2. Slice any plate except plate 1 (plates 2-10)

### Actual results

Skirt on plate extends off the plate. It looks like the skirt is extending all the way to plate 1
![image](https://github.com/bambulab/BambuStudio/assets/96731892/e96f7bf7-8f6c-4e13-9da0-c504b24679e6)

Troubleshooting:
1. Saved the project with current version 1.7.65 and reopened. Did not work.
2. Cloned one of the objects onto a new plate. Did not work.
3. Added one of the stls's from disk. This did work, skirt was the proper size.

### Expected results

Skirt within plate boundaries

### Project file & Debug log uploads

File too large to upload here. Shared link here https://1drv.ms/u/s!AoYO2Eapmokqirg6e-4wtOb1Qg17uA?e=52EK9h

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
This bug has been reported earlier and already fixed in the latest Studio V1.7. Please have a try.
