### ISSUE TITLE
German text being displayed in Device tab when app is set to english

### ISSUE THREAD

**Issue by npike** [bambulab/BambuStudio#2047]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 10.15.7

### Printer

P1P

### How to reproduce

Start a print on a P1P

### Actual results

Device tab shows what I assume is german, see screenshot outlined in red. 
![Screen Shot 2023-07-13 at 7 20 32 PM](https://github.com/bambulab/BambuStudio/assets/144590/98cdf6c7-6cf2-45de-9b69-38c8e080c074)

### Expected results

English only text should be shown.

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bambu123** [comment]
This is the name of the model work. Can't be translated.
