### ISSUE TITLE
Bambu Studio allows to select Generic Silk PLA, but can't select Generic Silk PLA in Device/filament load.

### ISSUE THREAD

**Issue by DENGkevon** [bambulab/BambuStudio#2048]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1 Carbon

### How to reproduce

Select "Generic PLA Silk" for type of filament on "Prepare" tab of the project.
Go to "Device" tab, try to set filament type in "Ext Spool" or "AMS" for "Generic PLA Silk" is not available.

### Actual results

Printer will not continue with print with mismatch types of filaments chosen. "Generic PLA Silk" is not available to chose from "Device" tab of Bambu Studio.

![image](https://github.com/bambulab/BambuStudio/assets/139532189/7e6e8a55-9d89-4ab8-9e73-dbd02c2439e8)

### Expected results

User needs to be able to select the correct filament (Generic PLA Silk) in "Prepare" settings matching with filament loaded in "Device" tab 

### Project file & Debug log uploads

![image](https://github.com/bambulab/BambuStudio/assets/139532189/4e50bce5-a7e6-421f-81d0-bd4701ac2b58)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by StoneLiBambulab** [comment]
same as https://github.com/bambulab/BambuStudio/issues/1688

fixed in 1.7.0
