### ISSUE TITLE
[Issue] Bambu Studio allows to select Generic Silk PLA, but can't select Generic Silk PLA in Device/filament load.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#2049]
"Generic PLA Silk" is available to be selected while in "Prepare" tab with project but when in "Device" tab, Generica PLA Silk is missing to be selected in "Ext Spool" and "AMS".

**Comment by lanewei120** [comment]
could you give a picture?

I have just checked the device tab
and find "Generic PLA Silk" is also selectable in device tab
![image](https://github.com/bambulab/BambuStudio/assets/106916061/8ba2191d-a186-4823-a46d-d62088cfdc0a)

**Comment by lanewei120** [comment]
should already fixed in 1.7 beta version
