### ISSUE TITLE
Unknown/unused settings are removed from profiles on save

### ISSUE THREAD

**Issue by CoryCharlton** [bambulab/BambuStudio#2053]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

X1C or P1P

### How to reproduce

1. Open Orca Slicer and edit a filament profile to enable pressure advance and set a value
2. Close Orca Slicer to let the profiles sync to the cloud
3. Open Bambu Studio and edit the same filament profile to adjust flow rate (or any other setting)

### Actual results

The "enable_pressure_advance" and "pressure_advance" settings have been removed from the profile.

### Expected results

All settings that were not specifically modified should have the same values they had prior to editing the profile in Bambu Studio.

**Comment by bambu123** [comment]
You can edit these parameters in BambuStudio directly.
You should select a thirdparty filament. Bambu filaments have not these parameters.

![image](https://github.com/bambulab/BambuStudio/assets/112537880/eb606146-4d73-4e24-9374-58345139283d)

**Comment by rfield19** [comment]
The pressure advance option you show above is not available in bambu studio 1.7 b2.  
This is with advanced, and developer mode switched on.  
Doesn't matter if it's a generic profile or not, the option simply does not appear.
<img width="750" alt="SCR-20230720-jabr" src="https://github.com/bambulab/BambuStudio/assets/81954195/0c476101-15ec-4c38-9fa5-4302522d229b">

**Comment by CoryCharlton** [comment]
> You are in BBL P1P. Select a thirdparty printer preset will bring it to front.

Just to be clear. This issue is not about whether the setting appears in the UI or is used during printing.

The issue is that if you follow the steps to reproduce and then open the JSON file stored at `%APPDATA%\Roaming\BambuStudio\user\<USERID>\filament` the setting value has been removed from the profile entirely.

**Comment by bambu123** [comment]
> > You are in BBL P1P. Select a thirdparty printer preset will bring it to front.
> 
> Just to be clear. This issue is not about whether the setting appears in the UI or is used during printing.
> 
> The issue is that if you follow the steps to reproduce and then open the JSON file stored at `%APPDATA%\Roaming\BambuStudio\user\<USERID>\filament` the setting values have been removed from the profile entirely.

I see. Could you please send me the preset file before you edit in BambuStudio.  That is `%APPDATA%\Roaming\BambuStudio\user\<USERID>\filament\xxx.json`. 
One more thing, If the config value is the same as the value in the inherits preset, it is removed from the saved json.

**Comment by CoryCharlton** [comment]
Well I am no longer able to reproduce the issue so I'm going to close this for now.

**Comment by bambu123** [comment]
> Well I am no longer able to reproduce the issue so I'm going to close this for now.

OK. If you have any questions, please continue to contact us.
