### ISSUE TITLE
Currently, there is no option to adjust the first layer flow.

### ISSUE THREAD

**Issue by wonsuhna1** [bambulab/BambuStudio#2057]
There is no option to adjust the first layer flow.
developer mode is a "Bottom surface flow ratio" option, but this is an adjustment option for the first layer "solid infill"
I don't see a first layer wall flow ratio adjustment, can you add one?

This is needed to in "Non bambu printers", adjust the z-axis size of the print. (z axis printing size fine tune.)
When I set the first layer height to 0.2, I really want the first layer to be 0.2mm high.
To do this, I need to be able to adjust the flow ratio of the first layer.

maybe, some people needed in bambu printers.

**Comment by SaltWei** [comment]
@wonsuhna1 Thanks!

@QingZhangBambu this should be wrong code in gcode.cpp. This setting should be applied to initial layer which is contacted with the hot bed, rather than erBottomSurface. erBottomSurface may not be contacted with hot bed.

![image](https://github.com/bambulab/BambuStudio/assets/110660407/05c61b6e-4e4a-47cc-951b-5e9b4e835aca)

**Comment by SaltWei** [comment]
@BambooBugFixer Please fix this issue.
You can ask @QingZhangBambu for more detail about this ticket after you understand user requirement yourself.

**Comment by BambooBugFixer** [comment]
This feature has been available in the newest Studio version.

**Comment by GuzziRaz** [comment]
<img width="434" alt="Screenshot 2023-11-06 at 00 45 30" src="https://github.com/bambulab/BambuStudio/assets/143495653/e59cef6e-1af6-457c-ac7a-f39ef7fe2abd">

@DriftMonkey100 you need to enable Developer Mode in settings.

**Comment by SaltWei** [comment]
Already included in latest version. Thanks for reporting issue to us！
