### ISSUE TITLE
Plate names are lost when using Undo

### ISSUE THREAD

**Issue by RyanEwen** [bambulab/BambuStudio#2061]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab P1P

### How to reproduce

1. Name a plate. 
2. Place a model on the plate.
3. CTRL-Z or click Undo.

Or with an existing project such as the attached project:
1. Move the cube.
2. CTRL-Z or click Undo.

### Actual results

Plate names are erased.

### Expected results

Plate names remain.

### Project file & Debug log uploads

[Cube.zip](https://github.com/bambulab/BambuStudio/files/12061802/Cube.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Thank you for your discovery. It has been fixed. Stay tuned

**Comment by SaltWei** [comment]
Please reopen if still has issue
