### ISSUE TITLE
Bambu studio 1.7.0 Public Beta 2 on macOS 13.4.1, stop to respond after sleep

### ISSUE THREAD

**Issue by Kratak** [bambulab/BambuStudio#2068]
### Bambu Studio Version

v1.7.0 Public Beta 2

### Where is the application from?

Bambu Lab github releases

### OS version

Macos: 13.4.1 (22F82)

### Additional system information

Silicon macbook prop from 2023
Issue occurs on both tested machines.

14" M2 pro with 32 GB RAM
16" M2 max with 96 GB RAM

Both run newest released macos, not beta macos.

### Printer

X1C

### How to reproduce

- Start print
- left bambu studio in background on "Device" page
- sleep machine with bambu studio in background(not minimized)/on other desktop
- next day error occurs(didn't happens on short sleep during day)

### Actual results

Stops to respond, need to force quit and starts again.

I tested this with single stl, and big projects, same  results.

### Expected results

To work like on 16.x was working, bambu studio didn't have this issue on previous([v1.6.2](https://github.com/bambulab/BambuStudio/releases/tag/v01.06.02.04)) version.

### Project file & Debug log uploads

[debug_network_Mon_Jul_17_10_58_02.log](https://github.com/bambulab/BambuStudio/files/12067694/debug_network_Mon_Jul_17_10_58_02.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.
Can you provide a console log.  the studio should have experienced a crash
![img_v2_f1020b33-8ff6-4bc8-81d2-648dc65f856g](https://github.com/bambulab/BambuStudio/assets/120699126/fda14c9b-185f-4fa3-80c6-3315a1b26387)
![img_v2_6391d5a8-9547-45cd-84a4-55d2074fb36g](https://github.com/bambulab/BambuStudio/assets/120699126/0310127a-d74c-47b4-93b3-049f5b130158)

**Comment by jlgeering** [comment]
I experience a similar issue, still present with version 1.7.4.52

No crash report in Console app (@walterwongbbl)

Not 100% sure, but I think that the problem doesn't happen if I do not stay on the "Device" tab.

 
<img width="1071" alt="Screenshot 2023-09-12 at 17 36 04" src="https://github.com/bambulab/BambuStudio/assets/388658/072543da-882c-4d7f-ae02-bb5c85720a10">

I can provide a diagnostic report if that helps.

**Comment by walterwongbbl** [comment]
@jlgeering 
Please download and use the latest version of Studio

**Comment by jlgeering** [comment]
I am on 1.7.7.88 => the issue seems to be fixed

**Comment by walterwongbbl** [comment]
If you have any other questions, please create a new one. The current conversation will be closed.
