### ISSUE TITLE
[Mac] Mac app bundle has no bundle identifier

### ISSUE THREAD

**Issue by chendo** [bambulab/BambuStudio#207]
The Mac app bundle has a blank `CFBundleIdentifier` in the `Info.plist`. This causes odd behaviours on macOS, and I noticed when my Mac thought `BambuStudio.app` and `Valeroni.app` (another app that also erroneously has a blank bundle identifier), was the same app, as bundle identifiers are how macOS uses to differentiate applications.

Something like `com.bambulab.bambu-studio.mac`

**Comment by lanewei120** [comment]
thanks for report this bug

we will fix it in the coming version

**Comment by lanewei120** [comment]
already fixed in the newest released version v1.2.0
