### ISSUE TITLE
Better indicator which AMS Slot is empty

### ISSUE THREAD

**Issue by DokuKaefer** [bambulab/BambuStudio#2070]
Please add a better indicator for empty slot.
White is not so good.
Use white with red X or similar

![image](https://github.com/bambulab/BambuStudio/assets/11537653/b137778a-c9fe-4ccd-80f8-05b1536e19c9)

![image](https://github.com/bambulab/BambuStudio/assets/11537653/5024f2c0-17c8-4c94-9e48-ab4eeb4bf5ee)

**Comment by bam-winterfell** [comment]
Thank you for your suggestion. The corresponding optimization has been made and will be released in the next version. Wishing you a happy life
