### ISSUE TITLE
Crash setting height range modifier larger then object

### ISSUE THREAD

**Issue by edog1973** [bambulab/BambuStudio#2076]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 22.04

### Additional system information

-Computer-
Processor		: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Memory		: 65686MB (19971MB used)
Machine Type		: Notebook
Operating System		: Ubuntu 22.04.2 LTS
User Name		: ericw (Eric Wilkison)
Date/Time		: Tue 18 Jul 2023 08:28:01 AM PDT
-Display-
Resolution		: 5760x2160 pixels
OpenGL Renderer		: (Unknown)
X11 Vendor		: The X.Org Foundation
-Audio Devices-
Audio Adapter		: HDA-Intel - HDA Intel PCH
Audio Adapter		: HDA-Intel - HDA NVidia
Audio Adapter		: USB-Audio - HD Pro Webcam C920
-Input Devices-
 Sleep Button
 Lid Switch
 Power Button
 AT Translated Set 2 keyboard
 SynPS/2 Synaptics TouchPad
 TPPS/2 IBM TrackPoint
 Telink Wireless Receiver Mouse
 Telink Wireless Receiver Consumer Control
 Telink Wireless Receiver System Control
 Telink Wireless Receiver
 MOSART Semi. 2.4G Wireless Mouse
 MOSART Semi. 2.4G Wireless Mouse Consumer Control
 MOSART Semi. 2.4G Wireless Mouse
 HDA NVidia HDMI/DP,pcm:3
 HDA NVidia HDMI/DP,pcm:7
 HDA NVidia HDMI/DP,pcm:8
 HDA NVidia HDMI/DP,pcm:9
 HDA NVidia HDMI/DP,pcm:10
 HDA NVidia HDMI/DP,pcm:11
 ThinkPad Extra Buttons
 Integrated Camera: Integrated C
 HD Pro Webcam C920
 Video Bus
 Video Bus
 HDA Intel PCH Mic
 HDA Intel PCH Dock Mic
 HDA Intel PCH Dock Headphone
 HDA Intel PCH Headphone
 HDA Intel PCH HDMI/DP,pcm:3
 HDA Intel PCH HDMI/DP,pcm:7
 HDA Intel PCH HDMI/DP,pcm:8
 HDA Intel PCH HDMI/DP,pcm:9
 HDA Intel PCH HDMI/DP,pcm:10
-Printers (CUPS)-
Brother_HL-L8360CDW_series		: <i>Default</i>
Brother_HL_L8360CDW_series
HP_LaserJet_MFP_M129-M134
HP_LaserJet_MFP_M130fw_46701C
Rolo_Printer

### Printer

X1 Carbon

### How to reproduce

1. Create new project
2. Add primitive -> Bambu Cube
3. Right click cube and select Height Range Modifier
4. In objects view select Range 
5. Set the 'to" value to 40 and press Enter 
6. Application crashes and closes,  No error is presented.

Note: cube size is 30 mm, any value larger then 30 will cause the crash

![2023-07-18_08-33](https://github.com/bambulab/BambuStudio/assets/5891504/8e69944b-0c6b-4b93-8452-973dd86add43)

### Actual results

Application crashes.

### Expected results

The height range modifier should auto adjust to the model height.  At minimum a warning should be shown that the modifier can not exceed the object height. 

### Project file & Debug log uploads

Project file not needed.  Reproducible using new file with standard object added.

 
[debug_Tue_Jul_18_08_42_32_2744753.log.zip](https://github.com/bambulab/BambuStudio/files/12083166/debug_Tue_Jul_18_08_42_32_2744753.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
should be fixed in the newest 1.7.2.51 hotfix version
