### ISSUE TITLE
Please just release your goddamned 1.06 firmware already and stop removing MQTT data

### ISSUE THREAD

**Issue by Majestic7979** [bambulab/BambuStudio#2077]
### Bambu Studio Version

1.7

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Printer

X1c

### How to reproduce

I know I'm not alone here. Please stop postponing the firmware release and just release the damned thing already. It's stable enough, we all need the area cancellation and the RTSP. Why delay something that's basically ready to go, it's just pointless. Also, I want to complain about your company removing data points from MQTT. Stop doing that. You removed bed levelling data on the 1.05.2 and that is NOT acceptable. Some of us need to use other solutions to monitor the print and removing these data points to further lock down is NOT the right direction to go.

### Actual results

Stop removing MQTT data points. Release firmware updates faster.

### Expected results

Stop removing MQTT data points. Release firmware updates faster.

Hate me I don't care. Just do it.

### Project file & Debug log uploads

Not applicable

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by thewildmage** [comment]
I'm excited for new features, too. Testing takes time though, and I strongly prefer that firmware changes are thoroughly tested before release. Better to wait for new features to be polished than to risk breaking my currently stable printer functionality, I think.

**Comment by Majestic7979** [comment]
> I'm excited for new features, too. Testing takes time though, and I strongly prefer that firmware changes are thoroughly tested before release. Better to wait for new features to be polished than to risk breaking my currently stable printer functionality, I think.

The firmware is ready. They have no reason to postpone the release. They're just waiting to wrap up the slicer beta testing. But the slicer is a completely separate piece and I don't see the point of holding something up because of another. Anyone can disagree, whatever I don't take it personal. There is always a risk with ANY firmware release, just because they release something doesn't mean it is "polished". You are very much mistaken and naive if you think it will guarantee any stability. There is a reason why firmware updates are optional and there is a reason why they offer a downgrade path through Bambu Handy now. So go ahead and refuse the release, or downgrade to the previous one. But making people wait unnecessarily is ridiculous.

**Comment by mpetito** [comment]
Alternatively opting into the firmware beta channel should be an open process instead of invite-only.  This makes it easy for one person to stay on the stable channel, preferring slower releases and more testing, and another person to opt-in to the beta channel if they prefer bleeding edge features.

**Comment by Majestic7979** [comment]
> Alternatively, opting into the firmware beta channel should be an open process instead of invite-only. This makes it easy for one person to stay on the stable channel, preferring slower releases and more testing, and another person to opt-in to the beta channel if they prefer bleeding edge features.

Absolutely. The lady above is PMS-ing probably. She has to absolute thumb down even when she has TWO alternatives. Talk about being a &$#ch. She could refuse the update, she could downgrade. But noooooo it has to be her way, everyone has to wait for it even though the firmware is already done and dusted - I have an insider source and I know this to be the case. Bambu Lab is waiting for no reason. They need to open up the development firmware as an optional sign up to anyone who wants it. They could have a "canary" build for the bleeding edge and bugs, a beta build, and the release. All with the possibility of downgrade. They should make updates and downgrades possible via SD card for recovery purposes.

**Comment by Josh4532** [comment]
> > Alternatively, opting into the firmware beta channel should be an open process instead of invite-only. This makes it easy for one person to stay on the stable channel, preferring slower releases and more testing, and another person to opt-in to the beta channel if they prefer bleeding edge features.
> 
> Absolutely. The lady above is PMS-ing probably. She has to absolute thumb down even when she has TWO alternatives. What a nasty bully. Talk about being a &$#ch. She could refuse the update, she could downgrade. But noooooo it has to be her way, everyone has to wait for it even though the firmware is already done and dusted - I have an insider source and I know this to be the case. Bambu Lab is waiting for no reason. They need to open up the development firmware as an optional sign up to anyone who wants it. They could have a "canary" build for the bleeding edge and bugs, a beta build, and the release. All with the possibility of downgrade. They should make updates and downgrades possible via SD card for recovery purposes. When there is no alternative I really don't mind with people disagreeing with me. But the woman above is just a petty loser.

there is still some small bugs that need to be fixed on it before general release so not sure how it is done and dusted,  Maybe you can offer your hand at being tech support when they get hundreds of people complaining they keep getting "paused" messages when first printing

**Comment by Majestic7979** [comment]
> > > Alternatively, opting into the firmware beta channel should be an open process instead of invite-only. This makes it easy for one person to stay on the stable channel, preferring slower releases and more testing, and another person to opt-in to the beta channel if they prefer bleeding edge features.
> > 
> > 
> > Absolutely. The lady above is PMS-ing probably. She has to absolute thumb down even when she has TWO alternatives. What a nasty bully. Talk about being a &$#ch. She could refuse the update, she could downgrade. But noooooo it has to be her way, everyone has to wait for it even though the firmware is already done and dusted - I have an insider source and I know this to be the case. Bambu Lab is waiting for no reason. They need to open up the development firmware as an optional sign up to anyone who wants it. They could have a "canary" build for the bleeding edge and bugs, a beta build, and the release. All with the possibility of downgrade. They should make updates and downgrades possible via SD card for recovery purposes. When there is no alternative I really don't mind with people disagreeing with me. But the woman above is just a petty loser.
> 
> there is still some small bugs that need to be fixed on it before general release so not sure how it is done and dusted, Maybe you can offer your hand at being tech support when they get hundreds of people complaining they keep getting "paused" messages when first printing

I'll gladly do tech support if I get paid for it. I have an insider. They told me it is done. If they suddenly found a serious bug after I was advised, that's totally fine, bugs happen. But when I posted, it was "ready". The person told me they were waiting to release along with the slicer 1.7 and the slicer is what was holding them back.

**Comment by kylek29** [comment]
Re: MQTT

I just hope they plan to give some way to get the new calibration data so we can plug them into our Filament profiles, or those features won't be nearly as useful. I stopped using the other lidar based calibration methods because I couldn't get the values to plug into my the profiles. It's such a simple, customer friendly, thing to do and doesn't expose or hinder their IP in any way. 

It's also why I think many recommend skipping the models with the Lidar, because it's not that useful if we can't see what values were calculated and we don't want to run a calibration every time we swap filaments.

**Comment by Majestic7979** [comment]
That's what I mean. Bambu Lab makes it unnecessarily complex. They're actually creating extra work for themselves. Make the MQTT data fully available if they have nothing to fear. It's almost starting to feel like they're closed source because some of the expensive bells and whistles are nothing more than snake oil. I would not like to think that way but while there's at least an understandable reason to lock down firmware, it's completely and utterly pointless to hide calibration and other operating info that's on the MQTT stream. It's like Bambu Lab has stuff to hide. I have a very cynical theory - they are being flooded with warped bed support tickets and they think if they remove the calibration data they can just "the bed is fine", it's another story if a customer has the data to prove it, then they have the cost of replacing - but here's the thing if the bed really is warped then Bambu Lab is being completely dishonest. Nobody bought a printer wanting a warped bed. If it is indeed warped, replace it, period. If the company goes out of business, well, then that's just the way it is. That's the risk of releasing a hardware product. They should've QC'd these beds better. I have no sympathy if BL is limiting data points to hide stuff and be dishonest about warranty repairs. We all bought with the promise of receiving warranty repairs if there's an issue. Not honoring that is a great way to shoot themselves in the foot. Nobody will buy a pretty shell full of issues. Not to say it is a horrible printer, far from it. Bed issues or not, the X1C is an incredible printer. Bambu Lab needs to stop these practices before they burn themselves permanently. I want them to suceeed - SO MUCH! But do so HONESTLY.

**Comment by bastus1986** [comment]
> > Alternatively, opting into the firmware beta channel should be an open process instead of invite-only. This makes it easy for one person to stay on the stable channel, preferring slower releases and more testing, and another person to opt-in to the beta channel if they prefer bleeding edge features.
> 
> Absolutely. The lady above is PMS-ing probably. She has to absolute thumb down even when she has TWO alternatives. What a nasty bully. Talk about being a &$#ch. She could refuse the update, she could downgrade. But noooooo it has to be her way, everyone has to wait for it even though the firmware is already done and dusted - I have an insider source and I know this to be the case. Bambu Lab is waiting for no reason. They need to open up the development firmware as an optional sign up to anyone who wants it. They could have a "canary" build for the bleeding edge and bugs, a beta build, and the release. All with the possibility of downgrade. They should make updates and downgrades possible via SD card for recovery purposes. When there is no alternative I really don't mind with people disagreeing with me. But the woman above is just a petty loser.

Figures you'd be an asshole. People like you are bad for communities. Stop whining, you are exactly what you are criticizing here. Or you're a child. Literally a child probably

**Comment by Majestic7979** [comment]
> 

YAWN. Get outta here with your holier than thou attitude, you are literally a nobody on a sea of nobodies. "community bla bla community bla bla". I am a paid customer. In your little universe where everything online is a community I'm a child who can afford a 1.5k printer. Pathetic.

**Comment by Majestic7979** [comment]
Let me make this clear - I am NOT in a "community". I am reporting my issues/gripes to the business I paid to provide me the device and the service. If anybody doesn't like and/or disagree, by all means WASTE TIME attacking me. **I DON'T CARE** - YOU ARE JUST NOISE. I will continue to report as I wish to. And not just that! If anybody is going against what I want for myself I OBVIOUSLY will not be pleasant to them. Get out of my way. I am not here asking for whiners and random weirdos to approve my requests. For all intents and purposes I am talking to Bambu Lab. This is not a democracy. This is not voting. This is NOT a "community". It's a place for customers to tell the company what they want. It is up to the company to agree or disagree.

**Comment by bastus1986** [comment]
> Let me make this clear - I am NOT in a "community". I am reporting my issues/gripes to the business I paid to provide me the device and the service. If anybody doesn't like and/or disagree, by all means WASTE TIME attacking me. **I DON'T CARE** - YOU ARE JUST NOISE. I will continue to report as I wish to. And not just that! If anybody is going against what I want for myself I OBVIOUSLY will not be pleasant to them. Get out of my way. I am not here asking for whiners and random weirdos to approve my requests. For all intents and purposes I am talking to Bambu Lab. This is not a democracy. This is not voting. This is NOT a "community". It's a place for customers to tell the company what they want. It is up to the company to agree or disagree.

I promise I am wasting more of your time than mine, given you are a child, you probably have a lot to waste. Your parents shouldn't have bought such an expensive printer for such an easily agitated little boy. You should have had to learn patience tinkering with some 32 bit marlin board running a shitty delta setup with no support channels for you to whine to the manufacturers that they didn't do something your way. Maybe then you could properly appreciate what you have on your desk.  I will attempt to be more patient with immature bellyachers such as yourself, although it's fun to chime in on these tantrums. The funny part is, I don't disagree with your criticisms, just your absolutely adolescent delivery. If this type of diatribe helps you mentally, then I suppose there is a positive to it all, just understand this attitude and sense of entitled rage you display won't get you anywhere with anyone. For your sake, I hope you grow up just a bit. cheers.

**Comment by Majestic7979** [comment]
> > Let me make this clear - I am NOT in a "community". I am reporting my issues/gripes to the business I paid to provide me the device and the service. If anybody doesn't like and/or disagree, by all means WASTE TIME attacking me. **I DON'T CARE** - YOU ARE JUST NOISE. I will continue to report as I wish to. And not just that! If anybody is going against what I want for myself I OBVIOUSLY will not be pleasant to them. Get out of my way. I am not here asking for whiners and random weirdos to approve my requests. For all intents and purposes I am talking to Bambu Lab. This is not a democracy. This is not voting. This is NOT a "community". It's a place for customers to tell the company what they want. It is up to the company to agree or disagree.
> 
> I promise I am wasting more of your time than mine, given you are a child, you probably have a lot to waste. Your parents shouldn't have bought such an expensive printer for such an easily agitated little boy. You should have had to learn patience tinkering with some 32 bit marlin board running a shitty delta setup with no support channels for you to whine to the manufacturers that they didn't do something your way. Maybe then you could properly appreciate what you have on your desk. I will attempt to be more patient with immature bellyachers such as yourself, although it's fun to chime in on these tantrums. The funny part is, I don't disagree with your criticisms, just your absolutely adolescent delivery. If this type of diatribe helps you mentally, then I suppose there is a positive to it all, just understand this attitude and sense of entitled rage you display won't get you anywhere with anyone. For your sake, I hope you grow up just a bit. cheers.

I didn't read it. I stopped at "I promise I'm wasting more of your time than mine". Absolutely not. You're not me to make that judgment and I can say you're wasting yours because nothing you or anyone says will stop me from being me and saying what I wanna say. I find it very entertaining to tell entitled whiners like yourself trying to tell me what to do with my life that nothing you do or say is ever gonna change who I am 😆 are you from Bambu Lab? No. Then you're completely wasting time here. I didn't read whatever you said and won't. Now that's even more of your time wasted. Congratulations!!!!!

**Comment by bastus1986** [comment]
Oh my god, this is glorious. Thank you

**Comment by Majestic7979** [comment]
> Oh my god, this is glorious. Thank you

Indeed it is. You can refute one single point. It's all personal attacks. So you, I, and everyone knows you've lost the argument and now you're just my pet puppy to have fun with. You're very welcome!

**Comment by bastus1986** [comment]
Yes
