### ISSUE TITLE
filament painting doesnt work properly

### ISSUE THREAD

**Issue by pietervisser05** [bambulab/BambuStudio#2078]
### Bambu Studio Version

1.7.0.53

### Where is the application from?

Bambu Lab github releases

### OS version

macos 13.4.1

### Printer

X1C

### How to reproduce

i paint my model in the prepare tab.
the whole body black, the letters "MW65" on top in yellow. after finishing painting it looks axactly how its supposed to print. however after slicing, the yellow colour disappears and the whole model prints in black

### Actual results

<img width="1440" alt="Scherm­afbeelding 2023-07-18 om 22 07 15" src="https://github.com/bambulab/BambuStudio/assets/139920706/1efb8d3b-ba74-4bdd-9ed2-5dcd57627175">
<img width="1440" alt="Scherm­afbeelding 2023-07-18 om 22 06 48" src="https://github.com/bambulab/BambuStudio/assets/139920706/43a9b4f5-b659-40a8-ac9d-25c1c679cc75">

### Expected results

the letters should print in the colour i paint them

### Project file & Debug log uploads

[testprint.3mf.zip](https://github.com/bambulab/BambuStudio/files/12088671/testprint.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by MadMax389** [comment]
You have several things going on here. 
1) Don't paint the letters, assign them colors instead.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/f21f033c-8d8a-4deb-8b05-396b39ced16f)
2) The text shows up in this case
![image](https://github.com/bambulab/BambuStudio/assets/96731892/09ae8b8e-5877-4cb2-8638-77fbf7b00ca2)
3) But then the text on the side walls doesn't print. They are too thin for the nozzle width at .2mm. You need to make it at least .4mm width, and then make sure they are in the proper order in the assembly. All the text objects must appear after the main object. In the pic below, I made the side wall text .4mm and arranged them to be last in the assembly list.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/03b419a7-b466-4ac7-99e0-28035ae97b30)

**Comment by MadMax389** [comment]
To Bambu Lab: Regarding the order of the components in an assembly, it would be nice to be able to adjust the order by dragging the object in the list (like Prusa Slicer). In the pic below, I have two different assemblies with text flush to the top of the object. The only difference is the order in which they appear in the assembly.

![image](https://github.com/bambulab/BambuStudio/assets/96731892/1dcfec51-e1c9-4cd7-abaf-8df0f2517cdc)

Upon slicing, only the assembly where the text is last in the list slices correctly.

![image](https://github.com/bambulab/BambuStudio/assets/96731892/0ab43c0d-f4c7-43cc-8265-b68aa4de541e)

This is another result of my issue https://github.com/bambulab/BambuStudio/issues/1896

**Comment by pietervisser05** [comment]
> You have several things going on here.
> 
> 1. Don't paint the letters, assign them colors instead.
>    ![image](https://user-images.githubusercontent.com/96731892/254865256-f21f033c-8d8a-4deb-8b05-396b39ced16f.png)
> 2. The text shows up in this case
>    ![image](https://user-images.githubusercontent.com/96731892/254865623-09ae8b8e-5877-4cb2-8638-77fbf7b00ca2.png)
> 3. But then the text on the side walls doesn't print. They are too thin for the nozzle width at .2mm. You need to make it at least .4mm width, and then make sure they are in the proper order in the assembly. All the text objects must appear after the main object. In the pic below, I made the side wall text .4mm and arranged them to be last in the assembly list.
>    ![image](https://user-images.githubusercontent.com/96731892/254866876-03b419a7-b466-4ac7-99e0-28035ae97b30.png)

hello, thanks for helping me! regarding number 3, do you mean i should extrude the texts at least 0.4 mm from the object? or the letters itself should be 0.4 mm wide? i need the text to be flat, so extruding is not an option, i extruded the text now 3 mm into the body. i designed the model again in fusion 360, there in the assembly the solid body is first. however if i export it as step and load it into bambu studio the solid body appears last, so it doesnt slice correctly. do you know how i can change the order somehow?
greets pieter

**Comment by MadMax389** [comment]
Yes, it's fairly simple. Select the text object in the object window and cntrl-c to copy and cntrl-v to paste. A copy will move to the bottom of the list. Delete the original. Repeat until the body is first in the list.

**Comment by pietervisser05** [comment]
thanks a lot, that fixed it for me!
