### ISSUE TITLE
[Feature Request] Device Eject option (Windows)

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#208]
PrusaSlicer provides a nice simple option to eject your storage media after saving to it.

It'd be great to have this option in Bambu Studio too

![image](https://user-images.githubusercontent.com/63362209/188323144-cb02d49e-edc8-455b-bf5e-aba4c1488fe3.png)

**Comment by YifanWuBambu** [comment]
Thanks. It has been added to our plan.

**Comment by RobinWhitfield** [comment]
Added in 01.03
