### ISSUE TITLE
Unable to Select Filament Type for AMS from Bambu Studio

### ISSUE THREAD

**Issue by theChef613** [bambulab/BambuStudio#2082]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu P1S

### How to reproduce

Load filament into AMS
Go to the Device tab
edit the filament information
able to change color, but not able to select filament type

### Actual results

Able to change color but no Filament type dropdown

### Expected results

expected to be able to select filament type. able to do so from Bambu Handy App and then is updated in Bambu Studio

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12092060/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by eastabrooka** [comment]
+1 
![image](https://github.com/bambulab/BambuStudio/assets/11888681/d2e7a3c0-93d7-42ac-ae80-1e9d8064ee53)
I've tried left click, Right Click, Using tab and arrow keys. 

Won't let me select anything.

**Comment by eastabrooka** [comment]
@theChef613 - Your bug stands, But I just downloaded Beta V1.7.0.65 Available from : 
https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.65

Heres the dropdown.  
![image](https://github.com/bambulab/BambuStudio/assets/11888681/ecc3261d-49e3-4438-87db-c67c55998d08)

If you want to get printing with generic filament, that's how I fixed my issue.

**Comment by theChef613** [comment]
@eastabrooka thank you! going to switch to that version now
