### ISSUE TITLE
Apply separate pattern to Topmost layer.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#2092]
Would like to see the ability to apply a surface pattern to the topmost layer separate from whatever the rest of the print has selected

**Describe the solution you'd like**
Provide a selection box or drop-down menu

![Studio Topmost](https://github.com/bambulab/BambuStudio/assets/60475095/4b8e3c65-f683-4a02-ab50-b20a42ae524f)

**Comment by QingZhangBambu** [comment]
you can use a modifier to change the pattern.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/8a08b913-4efa-49a0-8b0c-c0a549418b4f)

**Comment by randyre** [comment]
@QingZhangBambu 

That's great for simple objects, but for complex objects it's hard to do. Plus Cura does it, would be nice not to have to reinvent the wheel

**Comment by QingZhangBambu** [comment]
ok, I would add that to our feature pool. and the concerned staff will discuss that.
