### ISSUE TITLE
Multiple filament slots does not change the actual filament settings

### ISSUE THREAD

**Issue by Naninani** [bambulab/BambuStudio#2098]
### Bambu Studio Version

1.7.0

### Where is the application from?

Bambu Lab github releases

### OS version

macOS Ventura 13.4.1

### Printer

P1P

### How to reproduce

1. Backup all existing profiles.
2. Wipe all profiles.
3. Logout if logged in (issues repo both logged in or out)
4. Uninstall Orca.
5. Install again.
6. Select Generic PETG.
7. Edit the Settings Override of Filament settings.
8. Set Z hop type to Slope
9. Set the Wipe Distance to 10mm
10. Save present to new one with name 1.
11. Add Primitive Cube
12. Add additional filament slot.
13. In slot 1 chose filament 1, in slot 2 chose Generic PETG
14. Slice with 1 and enable the Travel and Wipe to see the lines.
15. Set to slot 2 with the Generic PETG and slice again.
16. What happens is that it does not actually switch to slot 2 settings, but choses the settings from slot 1.
17. This happens only if there are more than 2 added filament slots. If you chose Generic PETG from slot 1, the settings are correctly updated.

### Actual results

<img width="801" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/1a0646a9-cc1e-44e5-9f48-6d8f3d7d496c">
<img width="369" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/29e2e06e-74a2-4fca-abf8-46923e1445b8">
<img width="489" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/ced148c0-7ac4-4537-97e3-9627fd2fd7f6">
<img width="428" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/91fe188c-aed4-434a-a0f1-229c0a9e79fe">
<img width="1372" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/6f91f65d-45a6-4324-9b83-b1a3334f531d">
<img width="1388" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/6ccb42ea-35cf-46de-8f8a-e7ed78f86a1b">
<img width="1386" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/b84c7d66-98c7-429a-995d-1485ef46b132">
<img width="1388" alt="image" src="https://github.com/SoftFever/OrcaSlicer/assets/1681582/16630e97-5593-4ee8-b442-b8b1b65198d4">

### Expected results

It should correctly update the settings for the different filament slots.
This is an extremely nasty bug that I managed to reproduces in both Orca and Bambu slicers. It actually ruined tons of prints for me and I spent countless hours figuring out why my prints are so off when using different filament slots.

### Project file & Debug log uploads

just add simple primitive object to test

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Naninani** [comment]
cross created in Orca as well https://github.com/SoftFever/OrcaSlicer/issues/1570

**Comment by RyanEwen** [comment]
This is a great find and might contribute to a bunch of other issues that people are having (myself included)

**Comment by Naninani** [comment]
> This is a great find and might contribute to a bunch of other issues that people are having (myself included)

@RyanEwen are you able to repo it on your end?
I tested on different machines and 100% repo, but I want to make sure others can repo as well.

**Comment by Naninani** [comment]
@zhimin-zeng-bambulab, any update on this? To me its a critical bug that is causing profiles mixing and alot of print issues.

**Comment by zhimin-zeng-bambulab** [comment]
We are handling BUG on github, we will fix this BUG as soon as possible.

**Comment by Naninani** [comment]
@SaltWei, @zhimin-zeng-bambulab any update on this?

**Comment by zhimin-zeng-bambulab** [comment]
@Naninani  It has been fixed in V1.7.6, you can have a try.
