### ISSUE TITLE
"Slowdown for overhangs" speed overwrites the "Slow printing down for better layer cooling" option

### ISSUE THREAD

**Issue by Erwin-Repolust** [bambulab/BambuStudio#2106]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

P1P

### How to reproduce

In the filament settings on the "cooling" tab, activate the checkbox "Slow printing down for better layer cooling" and set a minimum layer time of 40 seconds and set "Min print speed" to 0.

In the global process settings in the "speed" tab make sure "Slowdown for overhangs" is checked and speed overrides are set to 100mm/s for every angle.

Now slice a basic object like a 3cm sphere.

### Actual results

The minimum layer time specified is overwritten by the 100mm/s. Layers will finish under 40 seconds.

### Expected results

The minimum layer time has priority over the speed specified in "Slowdown for overhangs". Layer time is 40 seconds for the whole object.

### Project file & Debug log uploads

[Sphere.zip](https://github.com/bambulab/BambuStudio/files/12153107/Sphere.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Erwin-Repolust** [comment]
[Sphere.zip](https://github.com/bambulab/BambuStudio/files/12153123/Sphere.zip)

Added the process setting to the project file.

Expected:
![bug2](https://github.com/bambulab/BambuStudio/assets/50101161/2bd51bf1-6957-4355-8652-7ea11aed62d5)


Actual:
![bug1](https://github.com/bambulab/BambuStudio/assets/50101161/2033f4fa-969a-46aa-8f0c-4bb8d79dcd1e)

**Comment by QingZhangBambu** [comment]
I didn't get you. if the part is overhang, a slow speed guarantees the surface quality.

**Comment by Erwin-Repolust** [comment]
As already stated. If I specify a minimum layer time that should have priority over the, in this case speedup that the overhang speed overwrite produces. I can not make it more clear.

**Comment by QingZhangBambu** [comment]
why, these part may fail if the speed is not slowed down?

**Comment by QingZhangBambu** [comment]
if you don't want it, you can unable the overhang option

**Comment by GuzziRaz** [comment]
@QingZhangBambu The point is both settings should be honored. OP states that when slowing down for overhangs, the total layer time is erroneously ignored.

**Comment by Erwin-Repolust** [comment]
@QingZhangBambu In the example I gave above instead of slowing the speed down for overhangs, the feature is actually speeding things up and thereby ignoring the minimum layer time specified elsewhere. Please reattach the bug label and let someone else read through it if u do not understand my writing.

**Comment by Erwin-Repolust** [comment]
> if you don't want it, you can unable the overhang option

this is not a fix or a workaround! Layertime depends on layer surface area. There are models where the overhang speed would be a slowdown and on other models it would be a speed up in the current slicer so the issue persists.

**Comment by QingZhangBambu** [comment]
Actually, it is a feature request. I've added it to our feature pool.

**Comment by QingZhangBambu** [comment]
the concerned staff will evaluate it.

**Comment by MrDulkes** [comment]
Just adding my opinion that this is a bug, not a feature, and should be fixed.

**Comment by QingZhangBambu** [comment]
https://github.com/bambulab/BambuStudio/issues/3657

**Comment by Erwin-Repolust** [comment]
> #3657

Even if this gets implemented which would be good - the bug above still needs to be fixed.
Its one check in the logic of the "Slowdown for overhangs" per layer.

After slicing with "Slowdown for overhangs" check if layertime is below minimum, if yes then disable the logic of "Slowdown for overhangs" for this layer. Easy stuff one would think.

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/18f1f531-79b6-4674-8cc0-324ca361fc13)
@Erwin-Repolust this option could control if the overhang path be cooling

**Comment by Erwin-Repolust** [comment]
@QingZhangBambu I know but I want both features to work simultaneously and not to turn one off cause it behaves erroneously.

**Comment by QingZhangBambu** [comment]
@Erwin-Repolust  it works simultaneously, if the layer time is not satisfied, the overhang speed part will be reduced.

**Comment by Erwin-Repolust** [comment]
@QingZhangBambu Just retested, you are right, it does work in the current version of bambu studio as expected
