### ISSUE TITLE
Adding Creality Cr-6 Se and Max printers Plus Jgmaker Artist D Pro for closable Profiles

### ISSUE THREAD

**Issue by bhast2** [bambulab/BambuStudio#2108]
**Is your feature request related to a problem? Please describe.**
My problem was that I had to switch between slicing software

**Describe the solution you'd like**
Have the printer profiles in the slicing software

**Describe alternatives you've considered**
using a different slicer soft ware

**Additional context**
The profiles are all ready made.
you can get them here just would like to see them added to the code.
Creality CR-6 Se and Max printers https://github.com/bhast2/CR-6Se-Max-OrcaSlicer-profile/tree/v1.6.1
JgMaker Artist D pro printer https://github.com/bhast2/JgMaker-Artist-D-Pro-OrcaSlicer-Profile/releases/tag/v1

**Comment by SaltWei** [comment]
Thanks! We will have a check

**Comment by bhast2** [comment]
awesome. thank you

**Comment by bhast2** [comment]
i released v1.6.1 with a minor update. just a heads up

**Comment by XunZhangBambu** [comment]
Thanks! We will select some typical nozzles

**Comment by bhast2** [comment]
thank you very much I am working on adding a tpu profile
