### ISSUE TITLE
Viewing the mesh in Paint mode

### ISSUE THREAD

**Issue by Kyrian-29** [bambulab/BambuStudio#2109]
[Feature request] When using "Paint" with the "Triangle" tool, have the possibility to visualise the mesh of the part to be coloured.
Trimming with the triangle tool is not easy without being able to clearly see the mesh (the triangles).
![Sans titre 01](https://github.com/bambulab/BambuStudio/assets/126974661/79a1a4cb-8aa0-4ea0-8e3d-a653fa86f4a1)
A view of the mesh like with NetFab for example would be easier to do a perfect trimming.
![Sans titre 02](https://github.com/bambulab/BambuStudio/assets/126974661/ddfefb1a-ccd3-42d0-bc03-81f808ba1748)

**Comment by Haidiye00** [comment]
Okay, thank you for your suggestion. We will consider it soon

**Comment by Haidiye01** [comment]
![Uploading wireframe.gif…]()
The latest version already has this feature, please experience it

**Comment by lanewei120** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/106916061/fd27615b-afc3-40d1-9d81-d9b9c1a2a3aa)
use a shortcur to turn it on/off

**Comment by Kyrian-29** [comment]
TaaaaaDaaaaaaa !!!!!!
Oooohh Yessss !!!!!
Thank's
