### ISSUE TITLE
Tree support bug?

### ISSUE THREAD

**Issue by shawnishihara** [bambulab/BambuStudio#2115]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13

### Printer

Bambu Lab X1C

### How to reproduce

<img width="404" alt="Screenshot 2023-07-27 at 12 56 48 PM" src="https://github.com/bambulab/BambuStudio/assets/82118797/4fc6d097-40b3-4144-9064-2262432521aa">

Support settings

### Actual results

<img width="658" alt="Screenshot 2023-07-27 at 12 57 31 PM" src="https://github.com/bambulab/BambuStudio/assets/82118797/a8550ca0-a7b0-429d-b620-8f7a953f1bbf">

Floating supports inside opening of model. (view from bottom)

### Expected results

Not have floating supports. This does not show up with "normal" support

<img width="694" alt="Screenshot 2023-07-27 at 1 01 02 PM" src="https://github.com/bambulab/BambuStudio/assets/82118797/c5b79481-7a25-4b5a-8b59-4094dfb9b117">

### Project file & Debug log uploads

Have not printed since installing the public beta 1.7.0.65

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
Please upload the 3mf file for diagnosis.

**Comment by shawnishihara** [comment]
[MalteseFalcon.3mf.zip](https://github.com/bambulab/BambuStudio/files/12243789/MalteseFalcon.3mf.zip)

.3mf zipped and uploaded. 

I'm seeing the same bug on different models, not just this one.

**Comment by UndeadKernel** [comment]
I'd like this issue to be solved. I'm therefore also attaching a .3mf file that exhibits problems with floating supports.
This is specially obvious starting around layer 101 (near the legs of the miniature).

[floating_supports.3mf.zip](https://github.com/bambulab/BambuStudio/files/12268125/floating_supports.3mf.zip)

**Comment by gbibgim** [comment]
I can confirm this too, weird floating tree supports. Sometimes it gets stuck while generating them on 65%. BS 1.7.2.51
![Zrzut ekranu 2023-08-06 101840](https://github.com/bambulab/BambuStudio/assets/3314897/602517e0-633a-4fe7-8c69-5f8c47ad8e28)
[entrence_reducer_mount.zip](https://github.com/bambulab/BambuStudio/files/12268948/entrence_reducer_mount.zip)

**Comment by igiannakas** [comment]
Same here. Pretty annoying issue rendering tree supports as useless.

**Comment by jaytigner** [comment]
Same problem. 
![IMG_7919](https://github.com/bambulab/BambuStudio/assets/141784131/0fa5da0e-1038-4054-9a39-41088416bb91)
![IMG_7920](https://github.com/bambulab/BambuStudio/assets/141784131/e29105ab-6f11-4b9c-a1a3-8b4e414b0337)

**Comment by jaytigner** [comment]
The new hot fix did not solve the issue. These pictures are after downloading the newest release. 
![IMG_7920](https://github.com/bambulab/BambuStudio/assets/141784131/cd78ab39-ede9-474f-9c14-dd9c48b485b1)
![IMG_7919](https://github.com/bambulab/BambuStudio/assets/141784131/cfac5420-c399-4dfa-bafa-ff6c998ba7f1)
![F893BD9B-9BFF-45BE-BDFA-0F150B528CC0](https://github.com/bambulab/BambuStudio/assets/141784131/e80038fc-08cf-49fc-9e31-da69b0a9b70a)
![IMG_7914](https://github.com/bambulab/BambuStudio/assets/141784131/a7e78a56-7a46-4d25-ba9c-b13440e3bb1a)

**Comment by tangketan** [comment]
Yes, this is a bug with Linux and Mac on which I didn't test enough. Fix should be released soon.

**Comment by shawnishihara** [comment]
[image: Screenshot 2023-08-09 at 10.41.04 PM.png]

Still a major; work-stop bug after hotfix 1.7.3.50

**Comment by UndeadKernel** [comment]
I see support problems also under Windows. They do seem a bit less "extreme" but there are some issues still with supports and support interfaces appearing out of nowhere.

![image](https://github.com/bambulab/BambuStudio/assets/6165006/d54881e0-72de-4466-b44c-df3f075675d8)

**Comment by tangketan** [comment]
Thanks for reporting the bug. We've found the problem. The solution is on the way.

**Comment by SaltWei** [comment]
Will update new version including fix for this issue soon！

**Comment by gbibgim** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/3314897/dc7757be-beda-4813-b648-1583c07bf516)
Looks good now!

**Comment by SaltWei** [comment]
Included in latest release https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52.

**Comment by sockmonkey0223** [comment]
I'm using v01.07.07.88 and I still see this issue.
