### ISSUE TITLE
Make Plate names longer

### ISSUE THREAD

**Issue by Brock323232** [bambulab/BambuStudio#2119]
the plate names on orca slicer can be as long as you want. at least make the plate names able to go across the entire plate before you hit the charachter limit.

**Comment by Haidiye00** [comment]
The length has been changed to 200+, and this feature will be available in version 1.8

**Comment by SaltWei** [comment]
Included in latest release https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52.
