### ISSUE TITLE
offset bottom Z distance

### ISSUE THREAD

**Issue by GabrieleCast99** [bambulab/BambuStudio#2127]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

windows 11

### Printer

BambuLab P1S

### How to reproduce

Open included 3mf.
Go to Preview.

### Actual results

![Screenshot (144)](https://github.com/bambulab/BambuStudio/assets/122809295/92051453-1953-45ea-92db-ec54adc081ab)
instead of starting from the first layer for the lower distance z, some layers are skipped and, as in the photo, the distance z starts. The first layers like this are too attached to the print, affecting it

### Expected results

I expect the lower z distance to start from the first layer as in the official bambbo studio version downloadable from the site

### Project file & Debug log uploads

[tarian_female.zip](https://github.com/bambulab/BambuStudio/files/12216467/tarian_female.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
Thanks for reporting the bug. I'll look into it.

**Comment by GabrieleCast99** [comment]
news? i can t update the bambu studio in 1.7 version for this bug

**Comment by tangketan** [comment]
Official 1.8 has been released. Close this issue.
