### ISSUE TITLE
High System Load

### ISSUE THREAD

**Issue by twalenzyk** [bambulab/BambuStudio#2128]
### Bambu Studio Version

v1.7.0 Public Beta 2

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10 (22H2)

### Additional system information

CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz   2.69 GHz^
Memory: 16GB
Display Card: Intel HD Graphics 4600

### Printer

Bambu Lab P1P

### How to reproduce

1. Install 1.7.0 Pub Beta 2
2. Print something
3. View live video 

### Actual results

Live video stalls after some time and finally results in black image.
System Load is very high, fan is running full speed.

### Expected results

Live video works uninterrupted.
System load stays normal

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12222793/log.zip)
[Unbenannt.zip](https://github.com/bambulab/BambuStudio/files/12222807/Unbenannt.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bambu123** [comment]
@twalenzyk What about the old 1.6 version?

**Comment by twalenzyk** [comment]
I switched back to 1.6.2.4 an it does not show the same behaviour.

**Comment by bambu123** [comment]
Are you sure it is relating to the live view? Please give me a snapshot video with cpu performance.

**Comment by bambu123** [comment]
@twalenzyk Any news?

**Comment by bambu123** [comment]
Close it first, and reopen it if there is a new example.
