### ISSUE TITLE
Layer shift on exported sliced file multi colour prints

### ISSUE THREAD

**Issue by Learoy1** [bambulab/BambuStudio#213]
![Initial sliced model 2](https://user-images.githubusercontent.com/80989694/188445369-bb5f2c1c-5366-4d6d-bd5c-1cb3e4301bea.png)
![layer shift in exported G-Code 1](https://user-images.githubusercontent.com/80989694/188445378-20bd778d-a84f-415f-a2dc-e930c9612f97.png)
![layer shift in exported G-Code 2 ](https://user-images.githubusercontent.com/80989694/188445383-54d0dc8a-c4bd-478c-8091-55119a406e76.png)
![Initial sliced model 1](https://user-images.githubusercontent.com/80989694/188445387-7cdeb638-f6ea-45e8-8abd-c3a1f952f721.png)

I've sliced and printed the models shown in the pictures and they printed fine but I also exported the G-Code /sliced file for transfer onto SD card and reprint later. 
I've reopened up the sliced files in Bambu slicer and the g code shows a layer shift with different colours.
It only appears to be on models with more than one colour.
I've not test printed the exported files yet to see if it does shift the layers.
Pictures show the shift on exported sliced code but I've also posted pictures of what it should look like/what it initially sliced.

**Comment by YifanWuBambu** [comment]
@Learoy1 
Thanks for reporting this bug. We have reproduced it and will get it fixed.

**Comment by Learoy1** [comment]
> @Learoy1 Thanks for reporting this bug. We have reproduced it and will get it fixed.

You're very welcome.

**Comment by YifanWuBambu** [comment]
Fixed in v1.2.
