### ISSUE TITLE
Failed to Install The Plug-In

### ISSUE THREAD

**Issue by RuiRC** [bambulab/BambuStudio#2135]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

P1P

### How to reproduce

Fresh install of beta software over old main version, automatically let it try to install the network plugin.

### Actual results

The plugin will not install, will ask to check if blocked or deleted fby antivirus which it isn't

### Expected results

Install the plugin

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12234814/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by RuiMarquesCardona** [comment]
Possible Solution: Complete unistall of both Bambu Studio, and Orca Slicer if exists, and delete appdata folder.

**Comment by Absolucy** [comment]
I've found that for some reason, Nvidia Broadcast had one of the DLL files in the `%AppData%/BambuStudio/plugins` folders opened?

**Comment by brunopiovan** [comment]
fix for me was to just just deleted the %AppData%/BambuStudio/plugins folder

**Comment by dagnarf** [comment]
"Intel ARC Control service" on my Samsung Galaxy Book 360 / Intel Xe graphics in Windows 11 Services has the same .dll file open and won't let it be deleted or overwritten - I stopped the service from Windows Services, was able to delete the files (and download the plugin)

**Comment by jammydodger06** [comment]
> I've found that for some reason, Nvidia Broadcast had one of the DLL files in the `%AppData%/BambuStudio/plugins` folders opened?

Thank you!!!

**Comment by StoneLiBambulab** [comment]
please look at this wiki page:
https://wiki.bambulab.com/en/software/bambu-studio/failed-to-get-network-plugin

Thanks!

Stone Li

**Comment by StoneLiBambulab** [comment]
close this issue. open a new one if there is any problem.

Thanks!

Stone Li
