### ISSUE TITLE
Can't switch between plate previews in 1.7

### ISSUE THREAD

**Issue by hho** [bambulab/BambuStudio#2140]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab github releases

### OS version

Kubuntu 22.04.2

### Additional system information

AMD Ryzen 7 PRO 4750U with Radeon Graphics
32GB RAM
no GPU

### Printer

Bambu Lab X1C

### How to reproduce

* Create a project with multiple plates
* Switch to the preview tab, triggering slicing _or_ click "Slice plate" button
* Try to switch to a different plate by clicking one of the thumbnails in the upper left corner of the preview window  

### Actual results

Nothing happens (I _can_ switch to the "Total" stats, but then I can't switch back to any plate)

### Expected results

The preview changes to the selected plate, like it did in 1.6.2

### Project file & Debug log uploads

[project.zip](https://github.com/bambulab/BambuStudio/files/12239845/project.zip)
[debuglogs.zip](https://github.com/bambulab/BambuStudio/files/12239918/debuglogs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lanewei120** [comment]
already fixed in the v1.7.2.51 hotfix version
