### ISSUE TITLE
Automatic Flow Calibration way to high K-Value

### ISSUE THREAD

**Issue by ThoughtfulDev** [bambulab/BambuStudio#2144]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab github releases

### OS version

macOS

### Printer

Bambu Lab X1C

### How to reproduce

1. Do automatic Flow Calibration
2. Calibrate K-Factor automatically with Cold-Plate and Glue

### Actual results

In two cases the K-Factor was way to high

Jayo Black PLA: 0.039
Extrudr Red PLA NX2: 0.042

My manual calibration using Ellis Pattern in OrcaSlicer Main branch (https://github.com/SoftFever/OrcaSlicer/pull/1547) gave me those values:
Jayo Black PLA: 0.02
Extrudr Red PLA NX2: 0.016

Printing a bambu v1 cube with the automatic calibration values results in gabs on top layer (because too high k-value) and "wobbly" corners (see image)

Pictures of Automatic calibration with k-value of 0.039 (you can see the wobbly corners and gaps on top)
![IMG_3757](https://github.com/bambulab/BambuStudio/assets/23433433/f4fa9216-888e-43ea-9f68-6ee4222e590a)

![IMG_3758](https://github.com/bambulab/BambuStudio/assets/23433433/6ff21f2d-ab40-4978-8a76-9d4ab88f1de3)

Pictures of manual calibration with value of 0.02
![IMG_3759](https://github.com/bambulab/BambuStudio/assets/23433433/69f3d358-71dc-4959-a30d-f29d82784176)

![IMG_3760](https://github.com/bambulab/BambuStudio/assets/23433433/c3f1878c-553e-4970-a937-47f8baef405c)

### Expected results

Automatic K-Factor should be somewhere near manual calibration.

### Project file & Debug log uploads

None

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by SaltWei** [comment]
Printer team need log and calibration pattern photos. Maybe the extrusion head is crooked, the external parameter is wrong, and finally the calculation line is wrong.

Could you move to https://forum.bambulab.com/ or BanbuHandy APP to report ticket (https://wiki.bambulab.com/en/x1/troubleshooting/upload-log) including the printer log and calibration pattern photos? Thanks!

**Comment by SaltWei** [comment]
By the way, after uploading the log and pictures, could you share the ticket number so that we can ping the printer team to check asap ? Thanks!

**Comment by igiannakas** [comment]
Same issue here. I value is too high by 40% or so as well.also have over extrusion with the flow rate calibration using the LiDAR (as in the other issue I opened)

**Comment by sanguinaria-canadensis** [comment]
this is a bug that the compensation model in the Studio and the MC (machine controler)  is not the same , so the calibration result Studio sent is not compatible with the MC .
We are now reverting the model used in the MC to the same as Studio to make things work , the new firmware will be ready in a few hours.
T_T.....

**Comment by igiannakas** [comment]
> this is a bug that the compensation model in the Studio and the MC (machine controler) is not the same , so the calibration result Studio sent is not compatible with the MC . We are now reverting the model used in the MC to the same as Studio to make things work , the new firmware will be ready in a few hours. T_T.....

Fantastic thank you!!!

**Comment by sanguinaria-canadensis** [comment]
> > this is a bug that the compensation model in the Studio and the MC (machine controler) is not the same , so the calibration result Studio sent is not compatible with the MC . We are now reverting the model used in the MC to the same as Studio to make things work , the new firmware will be ready in a few hours. T_T.....
> 
> Fantastic thank you!!! Is this also related to #2152 ?

well , #2152 is an other story , the other guy is looking at it ...

**Comment by igiannakas** [comment]
this issue appears fixed in the latest release. k values from the lidar match the manual calibration.

**Comment by ThoughtfulDev** [comment]
I agree. Seems fixed.
