### ISSUE TITLE
The buttons for feeding and returning materials cannot be displayed

### ISSUE THREAD

**Issue by szifan** [bambulab/BambuStudio#2145]
### Bambu Studio Version

01.07.07.62

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

windows 11

### Additional system information

12600kf，rtx3080，32g 6400hz，

### Printer

P1P

### How to reproduce

After updating to the latest version, only one retry button will be displayed on the device page

### Actual results

Unable to feed through the client, the mobile app can operate normally
<img width="1267" alt="屏幕截图 2023-08-03 005647" src="https://github.com/bambulab/BambuStudio/assets/141263501/c57ce7b5-ba02-4379-9570-b805e05fcfe6">

### Expected results

Normal display of all buttons

### Project file & Debug log uploads

nothing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
@szifan 
It looks like you're printing?

**Comment by szifan** [comment]
> @szifan
> It looks like you're printing?

No

**Comment by walterwongbbl** [comment]
@szifan 
Do you only have one printer？

**Comment by walterwongbbl** [comment]
Hi. @szifan 
We will add entrances for load filament/unload filament. Currently, you can use an extruder or use your app for operation.
![image](https://github.com/bambulab/BambuStudio/assets/120699126/4d671d7f-75df-42c1-a31f-498ce0261d28)

**Comment by lanewei120** [comment]
this issue should be fixed on the newest version v1.7.2.51
please have a try
