### ISSUE TITLE
Auto Tree Support Stopped Working

### ISSUE THREAD

**Issue by mcdavidr** [bambulab/BambuStudio#2156]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

import model, in prepare select auto tree support, in preview no support is generated. manual tree still works
I have sliced in 1.6 and last public beta sucessfully
![Screenshot 2023-08-02 194657](https://github.com/bambulab/BambuStudio/assets/141276249/5c8b22b0-cea8-433c-9ffc-c00d284b3e37)

 

### Actual results

no supports generated
![Screenshot 2023-08-02 194657](https://github.com/bambulab/BambuStudio/assets/141276249/1835d51a-873b-47e3-966a-5407d88adb9e)

### Expected results

tree supports generated

### Project file & Debug log uploads

[telaio_in_tubi-TH.zip](https://github.com/bambulab/BambuStudio/files/12245512/telaio_in_tubi-TH.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by mcdavidr** [comment]
I just tried on file that it worked on previously and it works? There must be an issue with the file I uploaded. I printed with manual tree supports, it printed but the support interface did not work correctly.

**Comment by mcdavidr** [comment]
I think it’s a model specific issue

**Comment by tangketan** [comment]
The supports are not generated because you enabled this option "Support critical regions only". Critical regions are sharp tails and long cantilevers for now, which your model doesn't have.
![image](https://github.com/bambulab/BambuStudio/assets/13730459/8cd63aef-a594-43b3-9005-d9363c534de0)

**Comment by mcdavidr** [comment]
Thank you for clarifying this.Ron McDavidOn Aug 7, 2023, at 12:20 AM, tangketan ***@***.***> wrote:﻿
The supports are not generated because you enabled this option "Support critical regions only". Critical regions are sharp tails and long cantilevers for now, which your model doesn't have.
