### ISSUE TITLE
Flow Dynamics Auto Calibration - Invalid nozzle diameter

### ISSUE THREAD

**Issue by MwC-Trexx** [bambulab/BambuStudio#2157]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab github releases

### OS version

Mac OSX 13.5

### Additional system information

N/A

### Printer

Bambu X1 Carbon v1.06.00.00

### How to reproduce

Click on Calibration
Click on Flow Dynamics
Choose Auto-Calibration
Select 0.4 mm Nozzle & Cool Plate
Click Calibrate

### Actual results

https://github.com/bambulab/BambuStudio/assets/7128246/5ed34825-9a59-4920-a180-7aa1d89a9264

Error - Invalid Nozzle Diameter

### Expected results

Auto-Calibration begins

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12246354/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by drewzh** [comment]
I'm also experiencing this with the 0.6mm nozzle.

**Comment by dmacpro91** [comment]
Also experiencing this regardless of what nozzle size I select.

**Comment by MarcelLeon20** [comment]
I have the same issue.

**Comment by paulmaksimovich** [comment]
Just ran into this too, 0.2mm nozzle.

**Comment by MarcelLeon20** [comment]
Hey i think i found a solution. You have to set the right nozzle diameter on the printer display. In my case i have a X1C and there it is under maintenance --> accessoires --> nozzle. I hope i could help.

**Comment by Edzi11** [comment]
Had Same issue when trying a .2 nozzle. had success with .4 nozzle prior to hotfix update

**Comment by zhimin-zeng-bambulab** [comment]
We currently only support 0.4mm nozzle, and we will gradually improve the calibration of other nozzle diameters in the future.

**Comment by mbukosky** [comment]
Thanks for the information, it would be a better user experience if the other nozzle sizes were greyed out and there was a tooltip that said this would be released in a later update.

**Comment by kohones** [comment]
Version 1.7.4.52 - problem still exists.

**Comment by klack** [comment]
The problem still exists

**Comment by zhimin-zeng-bambulab** [comment]
At present, when we calibrate, the nozzle diameter selected by Studio needs to be the same as the nozzle diameter set by the printer.  Is your printer nozzle 0.6 mm?

**Comment by counterdrone** [comment]
How do you mean "set by the printer"? I have a .4 nozzle installed, have selected such in the prep page, and yet when I go to calibrate it defaults to .6 and when I change to .4 get "invalid nozzle diameter." Where does this need to be changed at the printer level? Thanks.

**Comment by MarcelLeon20** [comment]
Hi together. I think you have to set the diameter noozzle on the printer. I have a X1C and there it is under maintenance.

**Comment by counterdrone** [comment]
Yup it's under "accessories" on the printer touchscreen thanks.

**Comment by MwC-Trexx** [comment]
Appears to be fixed in 1.7.4.   You need to make sure the Nozzle size physically configured on the printer matches the nozzle size specified in the calibration screen in the slicer.

 I had forgotten that I had changed it on the printer a while ago for doing some TPU printing at 0.6mm.  After I switched the hotend back to a 0.4mm nozzle, I forgot to set the printer's back configuration accordingly.  

I am not sure what (if any) difference that made as the slicer was set to 0.4mm and seemed to print just fine.  It would be nice if there was an option in the slicer to update/configure the printer's nozzle configuration.

**Comment by zhimin-zeng-bambulab** [comment]
Could you verify if this problem still exists in the latest version(V1.7.4).

**Comment by jaxer** [comment]
I was not able to select nozzle 0.2 on printer as there is no such option there for me (only 0.4, 0.6, 0.8 but not 0.2). and i got this error when trying to calibrate :(

**Comment by zhimin-zeng-bambulab** [comment]
@jaxer  What type of machine is yours and what is the firmware version?

**Comment by jaxer** [comment]
> @jaxer  What type of machine is yours and what is the firmware version?

![image](https://github.com/bambulab/BambuStudio/assets/202096/558cfc11-1a57-4175-a17d-b9374a3c7f32)

Fw 01.06.03.00

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/e0dc58f5-f529-4c14-8342-99f2e28f1afc)

@jaxer  There is no 0.2 for this type of nozzle, you can switch the nozzle type

**Comment by jaxer** [comment]
Thanks @zhimin-zeng-bambulab that makes sense. I wish i understood that both of those are clickable earlier 🤦 
I was able to select correct nozzle there, have not tried calibrating again yet as long job is in progress.

**Comment by dale-in-NM** [comment]
Ok, if Bambu only supports the 0.4 nozzle: does that mean I have to install my 0.4 nozzle, calibrate and then re-install my 0.8 nozzle.  Or, do I calibrate with my 0.8 nozzle as if it was 0.4mm?

**Comment by zhimin-zeng-bambulab** [comment]
The latest firmware version can support nozzles other than 0.4 mm, just make sure that the nozzle installed on the printer is consistent with the diameter of the nozzle selected by Studio.

**Comment by dale-in-NM** [comment]
Sorry, I have tried starting all over, rebooting the system, changing to 0.4 and then back to 0.8, changing filament, tried auto calibrate and manual calibrate but every time I get the “Invalid nozzle diameter” calibration error.

 

Please help.

 

Dale Shell

**Comment by klack** [comment]
This feels like it isn't fixed.  I shouldn't have to set the nozzle in the slicer and on the printer.

**Comment by dale-in-NM** [comment]
My problem ended up being that I selected 0.8 in Studio but didn’t change the selection on the printer. Sent from my iPhoneOn Sep 14, 2023, at 3:34 PM, Richard Layton ***@***.***> wrote:﻿
This feels like it isn't fixed.  I shouldn't have to set the nozzle in the slicer and on the printer.

**Comment by zhimin-zeng-bambulab** [comment]
Could you have a try in Studio V1.7.7 with latest firmware version

**Comment by zhimin-zeng-bambulab** [comment]
This issue can now be verified in V1.8.0.57, just ensure that the nozzle diameters of Studio and printer are consistent.

**Comment by Modusmundi** [comment]
The error messages you get still aren't really helpful and don't really direct you to change nozzle at the physical printer; I guess I know now you need to change it in multiple spots, but the documentation here isn't great and I only found out my issue through Google landing me on this Github issue.  On latest firmware (1,07.01.00) and latest slicer.
