### ISSUE TITLE
Changing infill direction causes other parts to not print some layers

### ISSUE THREAD

**Issue by str8Astud3nt** [bambulab/BambuStudio#216]
While experimenting with changing the infill direction to make the infill lines look nice I noticed that it was causing the other parts of the model to stop printing what appears to be their top and bottom shell layers.

![image](https://user-images.githubusercontent.com/3480148/188509802-17a27c42-5215-4c29-8320-5029ed3e6918.png)

However, this doesn't seem to happen when splitting the model to objects instead of parts.

![image](https://user-images.githubusercontent.com/3480148/188509972-300ab54a-12a6-4944-8430-b44cb900efad.png)

But it does cause some other artifacts in the other objects, but that is unrelated to the infill direction bug.

![image](https://user-images.githubusercontent.com/3480148/188510035-b8beea88-a4ec-4430-b2c5-b1ca712e8b40.png)

**Comment by YifanWuBambu** [comment]
@str8Astud3nt Could you help share your 3mf to us? Thanks!

**Comment by str8Astud3nt** [comment]
Here is a google drive link.
https://drive.google.com/file/d/1V4EsmiAN_y-nu0SOr_osIgC7XOsvt9gZ/view?usp=sharing

Not sure the best way to share 3mf files since github doesn't accept that type automatically.

**Comment by YifanWuBambu** [comment]
Thanks. We have reproduced this bug and will fix it soon.
