### ISSUE TITLE
Default wall loops still 2 not 3

### ISSUE THREAD

**Issue by scottbmc** [bambulab/BambuStudio#2169]
### Bambu Studio Version

1.7.2.51

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

![Screenshot 2023-08-04 174408](https://github.com/bambulab/BambuStudio/assets/53099290/1072a9da-a89a-4b1f-bd99-c191266d18e6)

### Actual results

Wall loop 2 on all profiles except "strenght"

### Expected results

3 wall loops as told in releasenotes for v1.7.0 Public Beta

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12262375/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
yes, we change the default wall to 2 to avoid some print defect
