### ISSUE TITLE
[Feature Request] Lightning Infill

### ISSUE THREAD

**Issue by aquatacizem** [bambulab/BambuStudio#217]
Would be great to have lightning infill as an option, as per PrusaSlicer 2.5. Thanks!

**Comment by seanjhseo** [comment]
Agreed!

**Comment by YifanWuBambu** [comment]
It is added to the plan list.

**Comment by aquatacizem** [comment]
Thank you for your hard work!

**Comment by YifanWuBambu** [comment]
Please update to v1.3.0.12.
