### ISSUE TITLE
Exclude Objects feature - for the P1 series printers. No reason to have this pay-walled. 

### ISSUE THREAD

**Issue by nirurin** [bambulab/BambuStudio#2170]
Is your feature request related to a problem? Please describe.
Having to cancel a really long print that has multiple objects, only because one object failed. This is causing a huge loss of filament, time, electricity, money and frustration.
It's available for the X1 series, but I dislike that it's being pay-walled. 

Describe the solution you'd like
Like klipper and octoprint, allow to cancel a failed object on the build plate, instead of cancelling the entire print. It obviously won't work from the printer controls, but it can be done via bambu handy or bambu studio. 

Describe alternatives you've considered
Using printers that support Klipper or Octoprint "Cancel Object" feature.

Additional context
https://www.klipper3d.org/Exclude_Object.html

**Comment by npoulos** [comment]
Agree this feature needs to be available on the P1 series. It’s a software feature and there are clearly no hardware restraints. Especially since it’s been released after the fact and was never advertised as a coming soon feature for the x1. Feels like you’ve mislead p1 series buyers. 

Please enable this feature for the p1 series asap.

**Comment by Hologos** [comment]
It depends on how they've implemented it. It may be computationally intensive and X1 series as way more powerful CPU. That's the reason for 0.5 FPS camera on P1 instead of 1080p fps camera on X1. If it uses some kind of tags / comments in the gcode to identify the regions to skip the objects, there should not be any reason not to port it for P1 series as well.

**Comment by QingZhangBambu** [comment]
It is not pay-walled. P1serise has that function, but the screen does not support that. so we are figuring out a method to fix that. We will figure out that as fast as possible.

**Comment by nirurin** [comment]
> It is not pay-walled. P1serise has that function, but the screen does not support that. so we are figuring out a method to fix that. We will figure out that as fast as possible.

I thought the X1 series already has a solution for that - you can use the bambu handy app to select objects to exclude. Why would this not work on the P1S?

**Comment by antoan-boss** [comment]
@QingZhangBambu Hopefully it will be soon in Bambu Handy at least for p1 series :)

**Comment by QingZhangBambu** [comment]
@antoan-boss @nirurin I will talk to the concerned staff about that.

**Comment by nirurin** [comment]
> It is not pay-walled. P1serise has that function, but the screen does not support that. so we are figuring out a method to fix that. We will figure out that as fast as possible.

I'm being told (mostly by people who paid for the X1C) that the P1-series doesn't have the processing power to allow the exclude objects feature. Can you at least confirm that it's capable of doing it, and you're just working on the user interface / screen controls?

**Comment by QingZhangBambu** [comment]
@nirurin  I can confirm that. This function will be implemented on P Series later. It has been put in our plan list. I do not responsible for UI, I work on Software main function implementation.

**Comment by jostwald** [comment]
Hi, Is there any update on this? 

Thanks!

**Comment by MDsza** [comment]
Yeah, I just fiddled in my G-Codes-File manually for 1 hour to get the print without 2 warped parts, just to see the nozzle crashing over the partly printed parts after resume ;-) . Just to exclude / skip such parts would be a 'live safe' for all the P1P/P1S 3D enthusiasts, too. So, c'mon bambu heroes: go for it :-)

**Comment by Sn0w3y** [comment]
@QingZhangBambu would be great if you take care of this "Problem" as many users would be glad to have this feature and buy a P1S if it has this option !

**Comment by MonkaKokosowa** [comment]
It seems that the newest firmware has exclude objects feature! It seems to work now as I just tested it on my P1P and it shows it on handy app.
![obraz](https://github.com/bambulab/BambuStudio/assets/117939274/87be5af4-e2ba-445b-8057-a6fe8d732636)

**Comment by Sn0w3y** [comment]
Well it says "does not work on MicroSD or LAN Printing) ? If i start the Print Job from BambuStudio will it work then?

**Comment by MonkaKokosowa** [comment]
You can start a print job from either handy or slicer the important thing is that it goes through the cloud (dunno why tho). Though, at least for now, excluding objects can only be done in handy app (I suppose that will change with the next slicer update).

**Comment by Sn0w3y** [comment]
Thats great News!

Can you start a job via Smartphone now aswell? Like Uploading a file from the Smartphone?

**Comment by MonkaKokosowa** [comment]
No, when I said starting from the phone, I meant the printing history. There's probably some bug tracker issue for that, though I don't, to be honest, really see a use for it anymore after they added makerworld

**Comment by SaltWei** [comment]
Excluding object can be used on P1 series now. Close

**Comment by lin-ycv** [comment]
> Excluding object can be used on P1 series now. Close

Except when in LAN mode... Can we please this feature implemented in BambuStudio, if it can be done thru the handy app, no reason why it can't be done in Studio

**Comment by SaltWei** [comment]
> Except when in LAN mode... Can we please this feature implemented in BambuStudio, if it can be done thru the handy app, no reason why it can't be done in Studio

Because the screen of P1 is too small to implement the function. App is as "screen" of P series printer

**Comment by lin-ycv** [comment]
Bambu studio reports basically all the same info as the handy app? 
Using bambu studio doesn't require interaction with the printer screen.

**Comment by TheDuffman85** [comment]
> > Except when in LAN mode... Can we please this feature implemented in BambuStudio, if it can be done thru the handy app, no reason why it can't be done in Studio
> 
> Because the screen of P1 is too small to implement the function. App is as "screen" of P series printer

How exactly is the screen related to Bambu Studio? I call this BS.
