### ISSUE TITLE
Doc Bug - Linux  RPM Distros (sudo dnf install gtk3-dev webkit2gtk3-devel) change to (sudo dnf install gtk3-devel webkit2gtk3-devel)

### ISSUE THREAD

**Issue by dustash** [bambulab/BambuStudio#2171]
### Bambu Studio Version

1.7.0.65

### Where is the application from?

Bambu Lab github releases

### OS version

Fedora 38

### Additional system information

Bug Doc, Not needed.

### Printer

Bambu Labs P1S with AMS

### How to reproduce

$ sudo dnf install gtk3-dev
Last metadata expiration check: 3:45:29 ago on Fri 04 Aug 2023 08:16:16 AM MST.
No match for argument: gtk3-dev
Error: Unable to find a match: gtk3-dev

### Actual results

Last metadata expiration check: 3:45:29 ago on Fri 04 Aug 2023 08:16:16 AM MST.
No match for argument: gtk3-dev
Error: Unable to find a match: gtk3-dev

### Expected results

Install correctly

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
done, thanks for doing this
