### ISSUE TITLE
Vertical Layer Slider Right Click Menu Does Not Appear

### ISSUE THREAD

**Issue by candera** [bambulab/BambuStudio#2173]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab Official website

### OS version

OS X Ventura 13.4.1 (c)

### Additional system information

2.4 GHz 8-Core Intel Core i9
AMD Radeon Pro 5500M 8 GB
Intel UHD Graphics 630 1536 MB
32 GB 2667 MHz DDR4

### Printer

X1-C

### How to reproduce

Prepare model as usual.
Preview
Attempt to "right click" (two-finger click on a trackpad, actually, since no right mouse button is available)
Observe that the slider scrolls down; no context menu appears.

### Actual results

The slider scrolls down; no context menu appears.

### Expected results

Context menu including "pause at this layer" should appear.

### Project file & Debug log uploads

[project.zip](https://github.com/bambulab/BambuStudio/files/12264014/project.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by lanewei120** [comment]
@candera 
thanks for reporting this issue,
could you give a snapshot of your issue?

**Comment by candera** [comment]
Screen recording [here](https://photos.app.goo.gl/LuceKA5xm5aEWrBw6)

Since a screenshot of something NOT happening on a mouse click seemed less than useful. :)

**Comment by xp-Yang** [comment]
You should right click on the round button so that the context menu will apear.

**Comment by candera** [comment]
> You should right click on the round button so that the context menu will appear.

Aha! That works, thanks. However, it still moves the button. Like, I right-click (really, two-finger click) on it, and both the the button moves down and I get the context menu.

**Comment by Flamenco** [comment]
Hold down SHIFT when using 2-finger click and the button will not move.
