### ISSUE TITLE
第三方打印机，能不能添加修改热床大小的功能，谢谢！！

### ISSUE THREAD

**Issue by hou130425** [bambulab/BambuStudio#2180]
我也有拓竹，另外还台150的tiny-m
现在只能用不同的软件切，因为bambu studio不能修改第三方打印机的热床大小
能否添加下此类功能，orca-slicer是有这个功能的

谢谢

**Comment by SaltWei** [comment]
支持设置热床大小对第三方打印机很合理，毕竟bambu不可能添加完所有的第三方打印机，安排上！
当前你可以修改配置json文件里的字段修改热床大小
![image](https://github.com/bambulab/BambuStudio/assets/110660407/9c04c2ff-a4de-45a9-a13b-63cca9719b5a)
以上面的anker机器的预设为例子

**Comment by SaltWei** [comment]
@QingZhangBambu 帮忙记录到下个版本需求里。后面再安排其他同事搞一下

**Comment by LiZ-Li-BBL** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120457312/76922fa0-659c-4150-9fc9-c55dcde5f6fb)
已经添加到此处，欢迎使用
