### ISSUE TITLE
Send to Printer stating "not same LAN" when printer is in same lan

### ISSUE THREAD

**Issue by NeoTech** [bambulab/BambuStudio#2187]
### Bambu Studio Version

1.7.1.62

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1 Series

### How to reproduce

Change dropdown on preview page to "Send" and click the send button the popup window give you a error about the printer not being on the same LAN. Even if its clearly in the same ip range as my desktop computer. (192.168.x.x range)

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/168627/cbfd9878-a60f-4d23-8258-539283650c6e)

### Expected results

Being able to send files to the device for storage on either SD card or internal storage..

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12268243/log.zip)
[Basegrid.zip](https://github.com/bambulab/BambuStudio/files/12268244/Basegrid.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi.@NeoTech 
This may be due to recording the old IP address.
Please close studio and delete these files before trying again
![image](https://github.com/bambulab/BambuStudio/assets/120699126/46d5204e-4366-42b7-9641-99e12eb16064)

**Comment by ianderl** [comment]
I have the same issue. Where is this folder location you posted a screenshot of?

**Comment by walterwongbbl** [comment]
> I have the same issue. Where is this folder location you posted a screenshot of?

![image](https://github.com/bambulab/BambuStudio/assets/120699126/ab5fc906-de2e-445c-816a-104876727349)

**Comment by walterwongbbl** [comment]
Hi.   @ianderl 
The error message is not accurate. 
When an FTP transmission error occurs, There is a high probability that this information will be prompted. 
You can first check if the printer's network is working properly.
If the printer is too far away from WiFi, it will also prompt this error.
