### ISSUE TITLE
Colored filament is not matched against the same color in AMS slot.

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#2190]
### Bambu Studio Version

1.7.2.51

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

macOS 13.5 (22G74)

### Printer

Bambu Lab P1P + AMS

### How to reproduce

1. Open included project file.
2. Set filament color in AMS slot to red (see screenshots).
3. Set filament color to red (see screenshots).
4. Slice and click print.
5. See that red color is not correctly matched in AMS slot.

### Actual results

Red color is matched to whatever color in other slots. 

### Expected results

Red color correctly matched.

### Project file & Debug log uploads

<img width="1512" alt="filament-color" src="https://github.com/bambulab/BambuStudio/assets/1620004/9d22c835-b623-4e83-90ed-55f930da2633">
<img width="1512" alt="ams-filament-color" src="https://github.com/bambulab/BambuStudio/assets/1620004/89b7ec76-5d95-4a6f-9eaa-0172ae141184">
<img width="1512" alt="print" src="https://github.com/bambulab/BambuStudio/assets/1620004/b661fe10-f409-4473-9d09-b211805d2418">
[Combo case - middle part.3mf.zip](https://github.com/bambulab/BambuStudio/files/12268419/Combo.case.-.middle.part.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Hologos** [comment]
Just did another project and it seems like all custom color are not matched correctly.

**Comment by OzDruiD** [comment]
Following, sometimes see tis isssue as well.

**Comment by SaltWei** [comment]
@MklBambu Please check whether this issue still exist. If not, please close the ticket.

**Comment by Hologos** [comment]
@SaltWei I am using latest version and this issue still persists.

**Comment by SaltWei** [comment]
> @SaltWei I am using latest version and this issue still persists.

Got it. @MklBambu Please follow this issue.

**Comment by Hologos** [comment]
Here is a screen recording. Both slots are set to **Generic PLA** and the color is the same from the macOS color picker.

![ams-matching-colors](https://github.com/bambulab/BambuStudio/assets/1620004/562eea38-811a-479b-9bfd-aacbf507acd4)
