### ISSUE TITLE
优化悬垂切片走线逻辑 Optimize the overhang slice routing logic

### ISSUE THREAD

**Issue by wangkai294** [bambulab/BambuStudio#2191]
### Bambu Studio Version

1.7.2.51

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases, Built from source by yourself or others

### OS version

win10

### Printer

bambu lab p1p

### How to reproduce

![edf7c4b5e474f516e631c84228f6ef9](https://github.com/bambulab/BambuStudio/assets/141534835/d113c1e5-ede4-4c17-bd90-c1f507e6c4ab)
![1c6e44680713a6a434f036c6ec1594e](https://github.com/bambulab/BambuStudio/assets/141534835/4ddae62b-de3b-4a49-a7d7-9f7fd07d077d)
走线逻辑没有老版本好，现在的走线逻辑无法实现无支撑打印
The routing logic is not as good as the old version, and the current routing logic cannot achieve printing without adding support

### Actual results

![1775292b7d333e7a9027e26943812a9](https://github.com/bambulab/BambuStudio/assets/141534835/ced06f40-8b21-4214-b449-bd1d5c6cb35a)
左边是老版本，右边是新版本
On the left is the old version, on the right is the new version

### Expected results

调整走线逻辑
Adjust the cable logic

### Project file & Debug log uploads

[对比.zip](https://github.com/bambulab/BambuStudio/files/12268573/default.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
@QingZhangBambu 请最高优先级处理这个问题，hotfix版本发布后，一大波用户反馈overhang wall算的不对

**Comment by QingZhangBambu** [comment]
the wall order and overhang detection had been fixed. you can get full functionality on version 1.7 hotfix2
