### ISSUE TITLE
切割后连接件和孔洞的匹配问题

### ISSUE THREAD

**Issue by CFSO7322** [bambulab/BambuStudio#2198]
现在切割零件后，连接件和空洞的大小是固定的，无法快捷缩放；对于不同的材料，收缩比例不一样，固定的大小不一定能适配各种材料，可能会出现插不进去的情况。建议可以对连接件进行缩放

**Comment by QingZhangBambu** [comment]
孔洞补偿功能是否能够满足您的需求？此功能可以对外轮廓或是内轮廓进行缩放
![image](https://github.com/bambulab/BambuStudio/assets/112676417/883ba3e4-dbd9-4d03-83c7-a287b5ddad6b)

**Comment by CFSO7322** [comment]
这个功能适用于单独把软件内切割后创建连接件的孔洞缩放吗？
比如一盘上有我自己建模时创建的孔洞，也有拓竹软件创建的孔洞，会都给缩放了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月8日(周二) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bambulab/BambuStudio] 切割后连接件和孔洞的匹配问题 (Issue #2198)




 
孔洞补偿功能是否能够满足您的需求？此功能可以对外轮廓或是内轮廓进行缩放

**Comment by QingZhangBambu** [comment]
这个参数可以单独对单个object 起效。您可以选择在您需要应用的部件上应用。
![image](https://github.com/bambulab/BambuStudio/assets/112676417/e41c41de-4e72-423e-89db-8cfea77404d8)
