### ISSUE TITLE
[Bug, UI] Search box remains on top of other applications when switching with Alt+Tab

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#22]
When clicking the search box...
![image](https://user-images.githubusercontent.com/63362209/179424007-9f419ab4-611f-4ce4-acf2-f5738fc73e2b.png)

and then using Alt+Tab to change to a different application, the search items box remains over the top of the other applications.
![image](https://user-images.githubusercontent.com/63362209/179424002-78b20e1c-372a-488a-9847-3ccbcbdc3d5c.png)

It won't disappear until you return to the application, or click it (which returns you to the application).

Windows 11
21H2
01.00.10.05
Installed from the pre-release Windows installer.

**Comment by wuyifanfancy** [comment]
We will fix the bug in recent release.

**Comment by RobinWhitfield** [comment]
Just noting that this issue is still present in 01.01.01.01

**Comment by RobinWhitfield** [comment]
Still present in 01.02.00.04

**Comment by RobinWhitfield** [comment]
Still present in 01.02.00.09. despite being marked as a fixed bug

![image](https://user-images.githubusercontent.com/63362209/189994616-f643743b-7d6f-4ac6-bc3c-5f2d98a7c161.png)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
