### ISSUE TITLE
No "+" button in height range modifier in Hungarian language

### ISSUE THREAD

**Issue by AndrewTdi** [bambulab/BambuStudio#2203]
### Bambu Studio Version

1.7.2.51

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10 x64

### Printer

X1C+AMS

### How to reproduce

I use the slicer in Hungarian language and there is no + button on the height Range modifier tab. If I set the slicer language to English, I can find it right away.

### Actual results

![heightrange](https://github.com/bambulab/BambuStudio/assets/141583186/319e00ba-66f8-45ed-9427-9cc37f743bf4)

### Expected results

I should see the "+"  button at the height range modifier tab in Hungarian language too

### Project file & Debug log uploads

[gomb.zip](https://github.com/bambulab/BambuStudio/files/12270248/gomb.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/12270249/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
@bambu123 应该是匈牙利语言太长了，顶出去了，帮忙分配一下内部哪位同事帮忙修一下。1.8版本修

**Comment by bambu123** [comment]
@LiZ-Li-BBL help

**Comment by LiZ-Li-BBL** [comment]
Hello,
We've fixed this issue, the button will display normally in the next release.
