### ISSUE TITLE
[Feature Request] Adaptive Layer Height  - Selectable Layer Sections

### ISSUE THREAD

**Issue by seanjhseo** [bambulab/BambuStudio#221]
Prusa Slicer has a feature in it's "Variable Layer Height" where we can select certain layers to have finer layer heights. 
E.g., 0.15 base layer height and selecting the top heights of my parts (dome shape) to gradually print to 0.07mm height. 

I see that BambuStudio has Adaptive Layer Height, but turning this feature on lets the slicer make automatic decisions on the varied layer heights sections. It would be great if we could selectively “paint” sections of our parts to print at a lower layer height, and also have the feature to blend the layer height differences.

I’m used to using Prusa Slicer and seeing how similar Bambu Studio is to PS, I was hoping that it would have this feature or plan to introduce it in the future. 
<img width="1920" alt="1" src="https://user-images.githubusercontent.com/113000026/188783304-6e9388e3-7847-421e-8725-9ed3de7e6f34.png">

**Comment by bani6809** [comment]
This is adjustable layer height feature from prusaslicer. It would be nice to have it in BS.

https://www.youtube.com/watch?v=sLOfYDy3Brk

**Comment by rkarlsba** [comment]
I just stubled over this need - the code is in prusaslicer - could it be added, please?

**Comment by empyrials** [comment]
This is a feature I really need for the products I make. Please add it & allow us to have fine controls over this

**Comment by YifanWuBambu** [comment]
This will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.

**Comment by astrof** [comment]
There used to be an adaptive layer height but I don't see it anymore?

**Comment by YifanWuBambu** [comment]
@astrof 
Moved here
![image](https://user-images.githubusercontent.com/110661856/208222818-a47fb08e-377a-4ef4-9770-75ebcc9926fb.png)

**Comment by astrof** [comment]
But now it's on a per object basis and is not intuitive at all versus before was a global OR per object option (like in Cura or other slicers). I guess I'll have to mess with it more.
