### ISSUE TITLE
2nd AMS with Generic Filament

### ISSUE THREAD

**Issue by DGable** [bambulab/BambuStudio#2213]
### Bambu Studio Version

1.7.2.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Home

### Printer

X1C Carbon

### How to reproduce

1. Open Bambu Studio
2. Select Device
3. Select 2nd AMS Icon
4. Slots B1 & B4 Showing Filament is editable
5. Slots B2 & B3 indicating a RFID Tag present
6. B1 thru B4 loaded with Generic PLA
![Image2](https://github.com/bambulab/BambuStudio/assets/49816001/b221637a-1030-4811-b72d-6ca27a81de63)

### Actual results

Slots B2 & B3 information is not editable. slots B2 & B3 are indicating a RFID tag in use, even though only generic PLA is loadedin slots B1, B2, B3, & B4. 

### Expected results

Should be able to edit each slot indicating what filament is in that particular slot

### Project file & Debug log uploads

[BambuNetworkEngine.zip](https://github.com/bambulab/BambuStudio/files/12281427/BambuNetworkEngine.zip)
[PN Sealing Spool.zip](https://github.com/bambulab/BambuStudio/files/12281432/PN.Sealing.Spool.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MagicMilamber** [comment]
exactly the same Setup und the same Problem

**Comment by QingZhangBambu** [comment]
I am not quite sure what your problem is, for example, do you mean that should show Bambu PLA basic instead of PLA?
![image](https://github.com/bambulab/BambuStudio/assets/112676417/11226cb8-ba95-447e-8055-25b3199841f8)

**Comment by QingZhangBambu** [comment]
we show the filament name on prepare page, the device page only shows the generic category
![image](https://github.com/bambulab/BambuStudio/assets/112676417/ba107d16-6ea3-47fd-b498-b3d1c423b392)

**Comment by QingZhangBambu** [comment]
Closed for no responding

**Comment by SaltWei** [comment]
Why close so rapidly?
