### ISSUE TITLE
Please incorporate Small Perimeter Speed / Threshold

### ISSUE THREAD

**Issue by npoulos** [bambulab/BambuStudio#2221]
Please pull over the small perimeter speed / threshold from OrcaSlicer

Essentially, small perimeters of below Xmm are slowed down by X%

<img width="423" alt="Screenshot 2023-08-08 at 8 42 45 pm" src="https://github.com/bambulab/BambuStudio/assets/58903683/01ef22c9-9566-46f1-b383-d19dd1680d1f">

This makes very small features print so much cleaner

**Comment by man55** [comment]
Very useful feature, please add it.

**Comment by QingZhangBambu** [comment]
yes, we will add it option.

**Comment by npoulos** [comment]
@QingZhangBambu hello any update on this feature being added?

**Comment by QingZhangBambu** [comment]
@npoulos it will be added in version 1.8.
