### ISSUE TITLE
?????? ?????? replacing text

### ISSUE THREAD

**Issue by COOHU-Kr** [bambulab/BambuStudio#2236]
### Bambu Studio Version

1.7

### Where is the application from?

Bambu Lab github releases

### OS version

Win11

### Printer

bambu Lab X1 Carbon

### How to reproduce

Hello, I have a problem with the language file. When installing Korean and when slicing instead of text ?????? Could you please tell me how I can solve this problem and when can I change Korean to standard settings? 

I see it's fixed in OrcaSlicer.
https://github.com/SoftFever/OrcaSlicer/commit/580424701b0e4c724d6724a5bc09ccc3ac5c86a0

### Actual results

Hello, I have a problem with the language file. When installing Korean and when slicing instead of text ?????? Could you please tell me how I can solve this problem and when can I change Korean to standard settings? 

I see it's fixed in OrcaSlicer.
https://github.com/SoftFever/OrcaSlicer/commit/580424701b0e4c724d6724a5bc09ccc3ac5c86a0

### Expected results

Hello, I have a problem with the language file. When installing Korean and when slicing instead of text ?????? Could you please tell me how I can solve this problem and when can I change Korean to standard settings? 

I see it's fixed in OrcaSlicer.
https://github.com/SoftFever/OrcaSlicer/commit/580424701b0e4c724d6724a5bc09ccc3ac5c86a0

### Project file & Debug log uploads

Hello, I have a problem with the language file. When installing Korean and when slicing instead of text ?????? Could you please tell me how I can solve this problem and when can I change Korean to standard settings? 

I see it's fixed in OrcaSlicer.
https://github.com/SoftFever/OrcaSlicer/commit/580424701b0e4c724d6724a5bc09ccc3ac5c86a0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
We have added support for Korean.
