### ISSUE TITLE
problem with login 

### ISSUE THREAD

**Issue by Bjornrongved** [bambulab/BambuStudio#2237]
### Bambu Studio Version

e.g.1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu lab carbon x1

### How to reproduce

1. go to the app on pc
2. try to login 
3. than you see that the window just stay white.

### Actual results

it ' s just loading. i dont get to log in 

### Expected results

log in 

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@Bjornrongved 

could you help to upload the log file?
the guide can be found here: https://wiki.bambulab.com/en/x1/troubleshooting/bambu-studio-log

**Comment by grawsom** [comment]
Don't know if this helps, I had the same problem, no log in user folder.
But under preferences (Ctrl+P)  there was no entry in first point "language", did the drop down and choose "English".
Now I get the login form..

**Comment by Bjornrongved** [comment]
Hey,

Thank you, now it’s working 😊
Fra: Ivan ***@***.***>
Sendt: onsdag 9. august 2023 kl. 18:28
Til: ***@***.***>
Kopi: Bjørn ***@***.***>; ***@***.***>
Emne: Re: [bambulab/BambuStudio] problem with login (Issue #2237)


Don't know if this helps, I had the same problem, no log in user folder.
But under preferences (Ctrl+P) there was no entry in first point "language", did the drop down and choose "English".
Now I get the login form..

**Comment by StoneLiBambulab** [comment]
fixed in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52.

bambu studio loaded an unsupported language, you can change the language to English to avoid the issue.


Thanks!
Stone Li

**Comment by StoneLiBambulab** [comment]
close this issue. open a new one if there is any problem.

Thanks!

Stone Li

**Comment by Krambalkis90** [comment]
whomever will face same issue, use this link. language change did not help me.  needed to reinstall Edge

https://wiki.bambulab.com/en/bambu-studio/troubleshoot/install-issue

**Comment by klindic** [comment]
> [@Bjornrongved](https://github.com/Bjornrongved) Don't know if this helps, I had the same problem, no log in user folder. But under preferences (Ctrl+P) there was no entry in first point "language", did the drop down and choose "English". Now I get the login form..

Thanks, this saved my life!
