### ISSUE TITLE
[Feature Request] Random Z Seam location

### ISSUE THREAD

**Issue by beamonster** [bambulab/BambuStudio#224]
Would be nice, just saying. Thank you

**Comment by YifanWuBambu** [comment]
This feature has been added. Will be in the next release.

**Comment by RobinWhitfield** [comment]
Now included in 01.02.00.04
![image](https://user-images.githubusercontent.com/63362209/189472876-375d7044-d74f-4599-8de6-de22d9088f07.png)

**Comment by tokamac** [comment]
Thank you so much!
