### ISSUE TITLE
Random support lines

### ISSUE THREAD

**Issue by shahbazfazal** [bambulab/BambuStudio#2243]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OSX Ventura 13.4.1

### Additional system information

Mac Mini M2 8GB RAM

### Printer

X1C

### How to reproduce

i slice a model with supports and see the slicer creates supports randomly in areas. seems to be random. only happens on certain models in certain orientations. inhave attached the stl. add file to project and slice at 0.1 layer height with supports. try rotating the nodem in different positions.

![Screenshot 2023-08-09 at 18 04 56](https://github.com/bambulab/BambuStudio/assets/15035717/ef8b370d-577b-4983-8009-155c015d1416)

### Actual results

i slice and see supports at random places

### Expected results

supports should be placed where needed. and not in extra random lplaces

### Project file & Debug log uploads

project file too big to attach. 

attached conf file + stl.

[Archive.zip](https://github.com/bambulab/BambuStudio/files/12305215/Archive.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
Duplicate #2115 . Solution is on the way.
