### ISSUE TITLE
Auto Refill dialog is unreadable with clear PC media

### ISSUE THREAD

**Issue by hhoover1** [bambulab/BambuStudio#2245]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 12.6.8

### Printer

Bambu Lab X1Carbon

### How to reproduce

put 2 rolls PC (clear) in AMS.
Go to Bambulab Studio, Device page, click the Auto Refill, a dialog comes up with the arrows, the center is the dotted grey/white used for clear PC.  The text overprinted is unreadable.
Perhaps use text with an opaque background - simplest would be for everything, better would be for any hard-to-read cases.

### Actual results

Dialog comes up, unreadable so can't confirm which slots are part of the Auto Refill, what order, etc.

### Expected results

Readable text in the dialog

### Project file & Debug log uploads

[PiCase.3mf.zip](https://github.com/bambulab/BambuStudio/files/12307065/PiCase.3mf.zip)
[debug_Wed_Aug_09_08_30_37_32024.log.0.zip](https://github.com/bambulab/BambuStudio/files/12307066/debug_Wed_Aug_09_08_30_37_32024.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi. @hhoover1 
It may be related to transparent materials, and we will optimize it.
