### ISSUE TITLE
Reload From Disk Not Working

### ISSUE THREAD

**Issue by krayvis** [bambulab/BambuStudio#2246]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

X1 Carbon

### How to reproduce

Load a 3mf file.
Overwrite the 3mf file with a new version.
Attempt to use the "Reload from disk" function to load the updated geometry.

### Actual results

3D model does not update.

### Expected results

New geometry should replace old geometry.

### Project file & Debug log uploads

[Board Tester.zip](https://github.com/bambulab/BambuStudio/files/12307120/Board.Tester.zip)
No crash log.

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Hologos** [comment]
Duplicate #2209.

**Comment by DanBao-Bambu** [comment]
Please check if the gif below meets your expectations.

![example](https://github.com/bambulab/BambuStudio/assets/132529350/d43cdc5e-48a5-48e7-95fe-0a9eff9d4628)
