### ISSUE TITLE
Suggestion for "Slow Down for Overhangs" / 对悬垂降速功能的改进建议

### ISSUE THREAD

**Issue by Dong-Tu** [bambulab/BambuStudio#2257]
由于不了解3D打印相关术语的英文，为避免误解所以使用中文进行描述。

**Is your feature request related to a problem? Please describe.**
是，悬垂降速导致的速度变化显著影响打印质量。如以下链接中的两张图片所示。
https://pic.imgdb.cn/item/64d4f3171ddac507cc67e706.png
https://pic.imgdb.cn/item/64d4f32d1ddac507cc6826ce.png

**Describe the solution you'd like**
个人猜测在不同速度之间加入平滑过渡或许可以缓解

**Describe alternatives you've considered**
尝试过关闭悬垂降速并将外层速度设置为很低的值。但似乎会导致悬垂角度过大的区域打印质量下降

**Additional context**
如果已经有解决这个问题的方法，希望告知；如果软件将会有针对这个问题的更新，希望可以尽早见到。无论如何都非常感谢

**Comment by QingZhangBambu** [comment]
是打印速度变化导致的光泽度影响还是两个不同速度之间的明显纹路？
若是第一点，只能进行整体降速来改善表面光泽。
若是第二点，我们确实有在做改善方案，但是不够成熟，所以暂时没有推出。

**Comment by Dong-Tu** [comment]
> 是打印速度变化导致的光泽度影响还是两个不同速度之间的明显纹路？ 若是第一点，只能进行整体降速来改善表面光泽。 若是第二点，我们确实有在做改善方案，但是不够成熟，所以暂时没有推出。

感谢您的回应，问题属于后者，即打印速度不同的区域的交界处的纹路。我尝试了外墙速度20mm/s并悬垂降速关闭，打印效果有很大改善。期待软件正式更新

**Comment by QingZhangBambu** [comment]
@Dong-Tu 感谢您对此问题的报告，后续更新之后会即使在此处告知您。

**Comment by QingZhangBambu** [comment]
你好，最新的1.9 beta 1 版本的classic 模式下做了速度过渡的功能，可以改善零件表面的变速纹。欢迎您的试用。
