### ISSUE TITLE
Developer Mode Resets to “not enabled”

### ISSUE THREAD

**Issue by Merlwynd** [bambulab/BambuStudio#2259]
### Bambu Studio Version

1.7.3

### Where is the application from?

Bambu Lab Official website

### OS version

Win10

### Printer

X1CC

### How to reproduce

Turn Developer Mode on
Close Bambu Studio
Open Bambu Studio

### Actual results

When you open Bambu Studio, Developer Mode has been turned off…even though you enabled it before quitting Bambu Studio.

### Expected results

Developer Mode should stay on when enabled, even though you close/quit Bambu Studio…similar to enabling Advanced Mode.
Not sure if this is a bug or feature request.

### Project file & Debug log uploads

Not required….

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DanBao-Bambu** [comment]
I am very sorry for not incorporating the changes into this release due to my negligence. Sorry again, I will definitely pay attention next time.

**Comment by tsmith35** [comment]
@DanBao-Bambu will this be corrected with the next version? It doesn't work on OrcaSlicer either, but I know you guys share source between slicers. Thanks!

**Comment by DanBao-Bambu** [comment]
Thank you for your attention. In the next version, the Development Model status will be maintained after restarting Studio.
