### ISSUE TITLE
[Feature Request] Improvement on plate name editing workflow

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#2262]
1. When a user clicks at the plate name editing symbol, the cursor should be automatically placed inside the text box when the editing window opens, so user can start typing without having to use the mouse to place the cursor in first. 

2. When user finishes editing the name, hitting the Return key should save the name and exit the editing process, without requiring the user to use the mouse to click at the 'OK' button.

**Comment by SaltWei** [comment]
> 1. When a user clicks at the plate name editing symbol, the cursor should be automatically placed inside the text box when the editing window opens, so user can start typing without having to use the mouse to place the cursor in first.

Good!

**Comment by SaltWei** [comment]
> 2\. When user finishes editing the name, hitting the Return key should save the name and exit the editing process, without requiring the user to use the mouse to click at the 'OK' button.

We will make "enter" bottom as saving and closing

**Comment by Haidiye00** [comment]
Received your request, I will handle it today

**Comment by Haidiye00** [comment]
I have resolved the issue and this function will be released in version 1.8. Thank you
