### ISSUE TITLE
1.7.3.50 shifts first layer, not seeing in 1.7.2.51

### ISSUE THREAD

**Issue by sacherjj** [bambulab/BambuStudio#2266]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

Ryzen 7950X
ProArt X670E-Creator
64 GB RAM
NVidia 3090 Ti

### Printer

X1C + AMS

### How to reproduce

Slice this file on 1.7.3.50 and it looks normal when looking at layers, but when printing on 1.6.1 X1C, I get a first layer that is offset by around 20 mm.  When slicing on 1.7.2.51 and printing, all is fine.

[Gears with weird layer shift - 3mf renamed to zip.zip](https://github.com/bambulab/BambuStudio/files/12321621/Gears.with.weird.layer.shift.-.3mf.renamed.to.zip.zip)

### Actual results

See thread here.  This is not actual file included above, but a second one I tried.  The above file is simpler.

https://www.reddit.com/r/BambuLab/comments/15nvqje/anyone_getting_shifted_first_layers/

### Expected results

Should not shift the first layer.

### Project file & Debug log uploads

[Gears with weird layer shift.zip](https://github.com/bambulab/BambuStudio/files/12321666/Gears.with.weird.layer.shift.zip)
[debug_Thu_Aug_10_09_39_33_8456.log.zip](https://github.com/bambulab/BambuStudio/files/12321686/debug_Thu_Aug_10_09_39_33_8456.log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by sacherjj** [comment]
Confirmed reloading 1.7.2.51 on same machine eliminated the layer shift.

**Comment by lanewei120** [comment]
@sacherjj 
hello, thanks for reporting this issue

is there any offset on the preview page?
could you export these two .gcode.3mf and upload here for a compare?
![image](https://github.com/bambulab/BambuStudio/assets/106916061/8bba7f3f-2980-46bd-9390-6a829bd143ac)

**Comment by lanewei120** [comment]
@sacherjj
we have released v1.7.4
do you still meet this issue?

if yes, could you send the gcode to us for a check?

**Comment by SaltWei** [comment]
No new update and also can not be reproduced on our side. Close.
Reopen if has new update
