### ISSUE TITLE
Flow Dynamics Calibration

### ISSUE THREAD

**Issue by RaffaelGitHub** [bambulab/BambuStudio#2280]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

macOS

### Additional system information

CPU: Apple M1 Pro
macOS: 13.4.1 (22F82)

### Printer

Bambu Lab P1P

### How to reproduce

1. Open Bambu Studio
2. Press "Calibration" tab
3. Press "Manual Calibration"
4. Choose "Plate Type" -> "Textured PEI Plate"
5. Choose the right "Filament For Calibration"
6. Press "Calibrate"

### Actual results

Nothing will happen 

### Expected results

Flow Calibration

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12327938/log.zip)
[HoneyComb Wall inserts_containers_holders.3mf.zip](https://github.com/bambulab/BambuStudio/files/12327941/HoneyComb.Wall.inserts_containers_holders.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by wiz78** [comment]
I have the same problem. Can't start manual calibration...

**Comment by ma-gu-16** [comment]
Same for me on Windows 11 pro

**Comment by zhimin-zeng-bambulab** [comment]
Could you have a try in V1.7.6.  This version has some modifications related to Flow Dynamics Calibration.

**Comment by zhimin-zeng-bambulab** [comment]
@RaffaelGitHub Does this problem still exist?
