### ISSUE TITLE
Build plate disappears 

### ISSUE THREAD

**Issue by ecoughtry** [bambulab/BambuStudio#2282]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Ventura 13.5

### Additional system information

AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB
Memory: 32GB DDR4

### Printer

x1c

### How to reproduce

1. Open app
2. No build plate, even after import or "slice" it will not visualize what should be there

### Actual results

No build plate

### Expected results

Visual build plate displayed

### Project file & Debug log uploads

[Archive.zip](https://github.com/bambulab/BambuStudio/files/12328362/Archive.zip)
<img width="1809" alt="Screenshot 2023-08-12 at 2 51 58 PM" src="https://github.com/bambulab/BambuStudio/assets/55843507/ba2cea05-cbaa-4132-8834-2bd775125635">

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by walterwongbbl** [comment]
Hi. @ecoughtry 
Can't  display the build plate every time？

**Comment by StoneLiBambulab** [comment]
hi @ecoughtry ,

your opengl version is 2.0, please try to upgrade your video driver, update the opengl version to 4.x


Thanks!

Stone Li

**Comment by Haidiye00** [comment]
Hello, have you upgraded the opengl version and resolved your issue ?

**Comment by Haidiye01** [comment]
Hello, have you upgraded the opengl version and resolved your issue ?

**Comment by SaltWei** [comment]
No update from user for a long time. Close.
Reopen if has new response.
