### ISSUE TITLE
Bambu Studio crashes when slicing stl on linux

### ISSUE THREAD

**Issue by Asupkay** [bambulab/BambuStudio#2283]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

Linux Mint 20.1 Cinnamon

### Additional system information

Nvidia 1070 ti
i7 10th gen
32 gb of ddr4 ram

### Printer

Bambu Lab p1s

### How to reproduce

1. Open up bambu labs
2. Import attached model
3. Auto place it so it's flat on the build plate
4. Press slice plate

### Actual results

Crashes to desktop

### Expected results

Finishes slicing

### Project file & Debug log uploads

[debug_Sun_Aug_13_00_20_03_341763.txt](https://github.com/bambulab/BambuStudio/files/12328801/debug_Sun_Aug_13_00_20_03_341763.txt)
[project.zip](https://github.com/bambulab/BambuStudio/files/12328803/project.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lanewei120** [comment]
it can also be reproduced on windows studio
@QingZhangBambu
