### ISSUE TITLE
Slicer states "no layers detected" when i place anything on plate 1 - all parts work on all other plates

### ISSUE THREAD

**Issue by preeny91** [bambulab/BambuStudio#2289]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Printer

bambu lab p1p

### How to reproduce

Move any of the parts to plate 1 and slice, error code then appears

### Actual results

shows error "no layers found"

### Expected results

if the parts are moved to any other plate other than plate one, then they will slice 

### Project file & Debug log uploads

[full mask project bug.zip](https://github.com/bambulab/BambuStudio/files/12330111/full.mask.project.bug.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/12330112/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/1369435d-aced-42a2-abe1-6b7eab4b109d)
what the stl is?

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/c6c8a575-ab6e-479b-96e3-c5d57185ae4d)
this very small part produce empty layer.
