### ISSUE TITLE
[bug, minor, studio/printer] Parts less than 1g show as 0g

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#229]
When a part is calculated to weigh less than 1g, it will report as weighing 0g

If a decimal value is not suitable, perhaps it could show <1g.

![IMG_20220908_141515](https://user-images.githubusercontent.com/63362209/189131462-8ce7e82e-da58-44cc-8ebf-baf898186a37.jpg)

**Comment by SaltWei** [comment]
![img_v2_e3e46ce4-49de-4062-adfc-6dc6b774184g](https://user-images.githubusercontent.com/110660407/222350191-14a1a1f4-ccdc-426d-93a8-39a507fdd4bc.jpg)
Seem to be fixed already in latest firmware.
