### ISSUE TITLE
STEP file import is buggy

### ISSUE THREAD

**Issue by Erin-Mounts** [bambulab/BambuStudio#2290]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Ventura 13.4.1 (c)

### Additional system information

CPU: Apple M2
Memory: 8 GB
Display card: Apple M2

### Printer

Bambu Lab X1 Carbon

### How to reproduce

[Case top.zip](https://github.com/bambulab/BambuStudio/files/12330144/Case.top.zip)

The two attached files were both exported from the same version of the same part, in the same Part Studio, in the same OnShape document, on the same day. One was exported as STEP (AP214*). The other was exported as STL with Fine setting.

1. Import the attached STEP file into Bambu Studio.
2. Import the attached STL file into the same project in Bambu Studio and compare them side-by-side.
3. Just to double-check the OnShape STEP file export to make sure the bug isn't there, open the STEP file in AutoCad Viewer (free online).

* - Originally I saw this problem when exporting as STEP AP242 (the latest/default version). I checked into what STEP version Bambu Studio supports, thinking this might be the issue, and found that the library you use (Open CASCADE) only supports some features of AP242 but claims to fully support AP214, so I re-exported the part as AP214. Unfortunately that had no effect on this issue.

### Actual results

Note that Bambu Studio complains about many non-manifold edges in the STEP file and it appears to be entirely missing a small face in one of the two rectangular wells. Note also that Bambu Studio appears to have no problems with the STL file and it appears to be intact. Finally note that AutoCad Viewer opens the STEP file just fine and renders it correctly with no complaints.

### Expected results

The STEP file should render correctly in Bambu Studio with no missing faces and no non-manifold edges being complained about. The rest of the actual results are as expected.

### Project file & Debug log uploads

[Bambu Studio STEP bug report.3mf.zip](https://github.com/bambulab/BambuStudio/files/12330166/Bambu.Studio.STEP.bug.report.3mf.zip)
[log 2.zip](https://github.com/bambulab/BambuStudio/files/12330170/log.2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
@DanBao-Bambu 得空研究一下OCCT和用户反馈的问题
