### ISSUE TITLE
Slicing Error with AMS: "WipeTowerIntegration::append_tcr was asked to do a toolchange it didn't expect."

### ISSUE THREAD

**Issue by thereseLYR** [bambulab/BambuStudio#2294]
### Bambu Studio Version

1.7.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10 Home 22H2

### Additional system information

CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Memory: 32GB
Graphics Card: NVIDIA GeForce RTX 2060

### Printer

Bambu Lab P1P

### How to reproduce

1. Open 3MF file
2. Slice plate 01 (Volcano Base Main Middle)
3. Error regarding 'WipeTowerIntegration::append_tcr was asked to do a toolchange it didn't expect.' will be thrown

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/47405262/71467488-322b-48a0-b9b1-88fb42659212)
Error is thrown, and slicing is not completed

### Expected results

Expected slicing to be able to complete.

### Project file & Debug log uploads

[Volcano Center Piece_troubleshooting.zip](https://github.com/bambulab/BambuStudio/files/12331091/Volcano.Center.Piece_troubleshooting.zip)
[logs_14Aug.zip](https://github.com/bambulab/BambuStudio/files/12331097/logs_14Aug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by thereseLYR** [comment]
This bug might be related to #1568 and https://github.com/prusa3d/PrusaSlicer/issues/3125, but is still present in the latest release of Bambu Studio (1.7.3.50)

**Comment by zhimin-zeng-bambulab** [comment]
we will fix it in 1.8 beta

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.08.00.57, you can have a try.

**Comment by ash286** [comment]
Has this bug fixed in latest v2.2.0 official? I'm keep encountering with this error of "Error: WipeTowerIntegration::append_tcr was asked to do a toolchange it didn't expect."
