### ISSUE TITLE
print finished but it would not clear the print to allow for another

### ISSUE THREAD

**Issue by zizzof16** [bambulab/BambuStudio#2297]
### Bambu Studio Version

1.7.3

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

P1s

### How to reproduce

Unsure

### Actual results

unsure

### Expected results

unsure

### Project file & Debug log uploads

![image](https://github.com/bambulab/BambuStudio/assets/142251869/06538928-c7ad-4354-b3c4-4134a0d0bf00)
[Bushings.zip](https://github.com/bambulab/BambuStudio/files/12337690/Bushings.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi. @zizzof16 
https://blog.bambulab.com/cloud-temporary-outage-investigation/
Has it returned to normal now

**Comment by walterwongbbl** [comment]
We have applied the latest version, please download the latest version to experience it.
