### ISSUE TITLE
[Bug] Hitting the slice button adjusts the current user view to Top view

### ISSUE THREAD

**Issue by LarryVand** [bambulab/BambuStudio#23]
You are in Preview mode and you pan, zoom, and rotate in a specific area to see your supports how they are sliced. You adjust your support settings and re-slice only to see  the view change again. The view should not change every time you hit the Slice button. And should not change every time you go to Preview mode either. The xyz current user view (Perspective or Orthogonal) should stay the same thru different modes or sliced. It is very visually disturbing and disorienting to the user, not to mention unproductive, in having to adjust the view every time they switch to the Preview mode or every time they slice.

**Comment by wuyifanfancy** [comment]
Thanks for the suggestion. We will optimize the view when switching between Prepare and Preview page, in both single and multiple plates senarios.

**Comment by YifanWuBambu** [comment]
@LarryVand The optimization is in the latest version. Please download and try it.
