### ISSUE TITLE
Can't Close Filament Windows

### ISSUE THREAD

**Issue by mltriebe** [bambulab/BambuStudio#2311]
### Bambu Studio Version

v01.07.04.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Intel HD Graphics 620 GPU, at 1366x768 resolution

### Printer

Bambu Lab X1C

### How to reproduce

1. Open Studio to the Device tab.
2. Click on a filament to select a PA profile or any change.

### Actual results

I can not click on the filament window to close it. Therefore I can not select anything or move the entire window to close it. I have had to use taskmanager 2 times so far to close Bambu Studio.

### Expected results

I should be able to close the filament window to continue in Bambu Studio.

![Screenshot 2023-08-16 165811](https://github.com/bambulab/BambuStudio/assets/132699713/20b17cae-2a64-48f9-afb6-bb5fe554262f)

### Project file & Debug log uploads

There is no log file due to me having to close the program through taskmanager.

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.  @mltriebe 
What is the resolution of your monitor?

**Comment by mltriebe** [comment]
As stated above:

Additional system information
Intel HD Graphics 620 GPU, at 1366x768 resolution

**Comment by walterwongbbl** [comment]
@mltriebe 
Is the maximum resolution you support 1366x768?

**Comment by mltriebe** [comment]
Yes, it is the max.

Mike

**Comment by bam-winterfell** [comment]
Hello, we have adjusted the position of this window and it will be launched in the next version. Please update it promptly.
Wishing you a pleasant life

**Comment by walterwongbbl** [comment]
If you have any other doubts, please create a new issue. The current conversation will be closed.
