### ISSUE TITLE
Linux Mint, program crash whrn playing stream p1p

### ISSUE THREAD

**Issue by Berden2162** [bambulab/BambuStudio#2315]
### Bambu Studio Version

1.7.4

### Where is the application from?

Bambu Lab github releases

### OS version

linux mint 

### Printer

P1S

### How to reproduce

click play icon 

### Actual results

program crash

### Expected results

play stream

### Project file & Debug log uploads

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
are you using the fedora image?

we just uploaded the ubuntu image https://github.com/bambulab/BambuStudio/releases/download/v01.07.04.52/Bambu_Studio_linux_ubuntu-v01.07.04.52.AppImage

how about this one?

**Comment by Berden2162** [comment]
Good, work well, Thank you
