### ISSUE TITLE
Tree supports are generated with a layer shift just before the branch is split for the first time

### ISSUE THREAD

**Issue by Hologos** [bambulab/BambuStudio#2322]
### Bambu Studio Version

1.7.4.51

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13.5 (22G74)

### Printer

Bambu Lab P1P

### How to reproduce

1. Download attached 3mf.
2. Slice it.
3. Check generated supports. There is a layer shift in some of them.

### Actual results

Some supports have a layer shift and it makes them weaker and more prone to breaking. I had failed print because of this.
It seems like the shift occurs when the branch gets split.

Unchecking `independent support layer height` doesn't fix it.

<img width="653" alt="Snímek obrazovky 2023-08-17 v 22 29 14" src="https://github.com/bambulab/BambuStudio/assets/1620004/2a0534d6-adbd-4f38-a809-6435affad3f4">

<img width="552" alt="Snímek obrazovky 2023-08-17 v 22 26 49" src="https://github.com/bambulab/BambuStudio/assets/1620004/e3241bc2-6c1f-454b-b9ab-f0328cf4f492">

<img width="328" alt="image" src="https://github.com/bambulab/BambuStudio/assets/1620004/c5b464af-e430-44bd-9d90-7d9998280339">

![IMG_8221](https://github.com/bambulab/BambuStudio/assets/1620004/b9922274-4b80-43a2-8055-25e263fe62e1)

### Expected results

No layer shift in generated supports.

### Project file & Debug log uploads

[pokemon charizard 0.12mm fixed z-hop.3mf.zip](https://github.com/bambulab/BambuStudio/files/12373327/pokemon.charizard.0.12mm.fixed.z-hop.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Hologos** [comment]
As expected the branch broke.. I had to glue it back.

![IMG_8227](https://github.com/bambulab/BambuStudio/assets/1620004/59018533-54bf-4cec-ad13-e3b56d20da8d)
![IMG_8228](https://github.com/bambulab/BambuStudio/assets/1620004/918c8ff1-3727-4f2b-95ac-55ebbeaf60f1)

**Comment by Hologos** [comment]
@tangketan Hello, is this gonna be fixed in next release or will it take longer to fix? Thank you

**Comment by tangketan** [comment]
@Hologos I'll fix it in the next release.

**Comment by tangketan** [comment]
Offical 1.8 has been released. Close this issue.
