### ISSUE TITLE
Bambu Studio Slicing Issue

### ISSUE THREAD

**Issue by ernestweiss** [bambulab/BambuStudio#2337]
### Bambu Studio Version

1.7.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

10th Gen Intel i7-10700F CPU
32 GB Memory
Nvidia GeForce RTX 2070 Super

### Printer

Bambu Lab P1P

### How to reproduce

1. Upgrade Bambu Studio from 1.7.3.50 to 1.7.4.52.
2. Add a new object to slice.
3. Enable Supports
4. Support Type = tree(auto)
5. Support Style = tree slim
6. Slice plate
7. Print plate

### Actual results

Printer starts printing the object and the print head stops moving in the X and Y directions.  It appears to still be moving in the Z direction as it creates a "nub" on the part.  The printing was stopped manually at this point.

Reverting to Bambu Studio 1.7.3.50 and re-slicing and printing the object again (with the same settings) prints with no issue.

### Expected results

Completed print.

### Project file & Debug log uploads

[CuteDino_ShortLegs.zip](https://github.com/bambulab/BambuStudio/files/12384896/CuteDino_ShortLegs.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
I can't see any problem from the 3mf file. Would you please also provide the video recording?
