### ISSUE TITLE
Split in objects / Split in parts buttons grayed out

### ISSUE THREAD

**Issue by SMT-Gerard** [bambulab/BambuStudio#2345]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Printer

X1C

### How to reproduce

the buttons are always grayed out

### Actual results

-

### Expected results

-

### Project file & Debug log uploads

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
Import a 3mf file with multiple parts/objects, and the split buttons will be enabled
