### ISSUE TITLE
Incorrect button text when loading filament

### ISSUE THREAD

**Issue by gsingh93** [bambulab/BambuStudio#2346]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13.5

### Printer

Bambu Lab P1S

### How to reproduce

1. Go to the Device tab
2. Click Load

### Actual results

The dialog text refers to the "Done" and "Retry" buttons (which appear on the printer display), but the dialog buttons are "Done" and "Confirm":
<img width="402" alt="Screenshot 2023-08-20 at 12 00 31 PM" src="https://github.com/bambulab/BambuStudio/assets/1012677/8d8aa8b2-424d-4602-8eb5-64b319cce839">

### Expected results

The buttons should be "Done" and "Retry", and "Done" should probably be the green one. I wasn't paying attention and just clicked the green button, assuming that would continue the loading process, and I was confused when things didn't work. After trying it a second time I realized I needed to click the other button.

I didn't check any other dialogs for this issue, but they should also probably be checked.

### Project file & Debug log uploads

Not needed for UI issue

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.
We will optimize the highlighting of the buttons

**Comment by walterwongbbl** [comment]
@gsingh93 
Highlighting the "Done" button can reduce misunderstandings. We will optimize it.

**Comment by walterwongbbl** [comment]
@gsingh93 
Please download and use the latest Studio version
