### ISSUE TITLE
Resume button missing after inserting pause in slicer at specific layer

### ISSUE THREAD

**Issue by FyrbyAdditive** [bambulab/BambuStudio#2351]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 13.4.1 (c)

### Additional system information

Apple Silicon, Macbook Pro M1 2021, 32GB RAM

### Printer

Bambu Lab X1CC

### How to reproduce

I have not tested being able to reproduce this repeatedly yet however:

1. Insert a pause at a specific layer, using the slider in the Preview part of Bambu Studio
2. Run print
3. Print stops, it tells me on various interfaces (Bambu Handy, on the printer, in Bambu Studio) that I need to tap resume to continue

### Actual results

There is no resume button available in Bambu Studio, the mobile app or the printer, and none of the workarounds suggested on reddit or elsewhere work in this case. I was able to make the resume button reappear in Bambu Handy by clicking pause in the main window, then pause in the modal, but on hitting resume ......... it did not work.

![C4171752-E47C-48C3-AA21-3A1146390B67_1_105_c](https://github.com/bambulab/BambuStudio/assets/1150419/bd195212-7832-40bd-b590-b830fd7f652b)
![5B558DA7-CB86-427C-8D72-F021CA61E64F_1_105_c](https://github.com/bambulab/BambuStudio/assets/1150419/6b5bb49c-11db-4708-87ab-407c202ca578)
![C02ED4E3-A100-4EB5-8C8E-F61408C2B43B_1_105_c](https://github.com/bambulab/BambuStudio/assets/1150419/69e624c7-0b72-49af-9f85-0b805a3f7fbb)
![A108C6C5-75BC-4563-A86C-FCC52382902F_1_105_c](https://github.com/bambulab/BambuStudio/assets/1150419/cc37ec40-26cf-41e6-8c06-58628bea47b5)

### Expected results

There should be some way to resume the print. There is not. It's in the bin, like the overall quality of my Bambu Labs experience recently.

### Project file & Debug log uploads

The file contains customer intellectual property and will not be provided.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SaltWei** [comment]
Very stupid bug. But not caused by APP and studio, but firmware.
@sodachen22 Please check this issue with high priority. User can not resume the task after pause.

**Comment by sodachen22** [comment]
There is a release of 01.06.03.00, would you please have a test on the latest version?

**Comment by FyrbyAdditive** [comment]
Thank you, this firmware seems to not be available in Bambu Studio for some reason (another bug, or perhaps slow CDN propagation, no idea), however I will return to the printer soon, maybe the firmware update will be there and I will try and recreate it hopefully soon.

**Comment by FyrbyAdditive** [comment]
All updated (via printer interface) - test is running and will report back soon.

**Comment by FyrbyAdditive** [comment]
I am unable to recreate this using the same project and method on 01.06.03.00. Thank you for the quick attention.

**Comment by roblomq** [comment]
A few months later and it seems the bug is still not fixed, screwed up two prints because I couldn't resume the print.
Bug is on a X1C with the latest firmware.
![Screenshot_20240324_195445_bbl intl bambulab com](https://github.com/bambulab/BambuStudio/assets/59142034/a86bff3b-ef9a-4a01-80ce-759a50f6d906)
![IMG_20240324_195637](https://github.com/bambulab/BambuStudio/assets/59142034/4b0fa35f-8ea5-4604-a4bd-e55383bae3df)

**Comment by poldim** [comment]
@XinZhangBambu @ShanCang-BamBu @Bambu-Pomfret 

This is still a problem 3 years later on v2.3.1.51 for my X1E.  


See this thread for many more reports of this problem
https://forum.bambulab.com/t/cannot-resume-a-print/1047/13
