### ISSUE TITLE
[Request] Add Troodon 2.0 to the supported printers list (already in OrcaSlicer)

### ISSUE THREAD

**Issue by nirurin** [bambulab/BambuStudio#2355]
**Is your feature request related to a problem? Please describe.**
No default printer option for Troodon 2.0. 

**Describe the solution you'd like**
Copy it in from Orcaslicer 

**Describe alternatives you've considered**
Using orcaslicer instead at the moment

**Comment by SaltWei** [comment]
@XunZhangBambu Please add it in next version

**Comment by bolsoncerrado** [comment]
I'd like to see Troodon v1.0 added as well.

**Comment by nirurin** [comment]
> @XunZhangBambu Please add it in next version

@SaltWei @XunZhangBambu 

I'm noticing that several/many versions have been released, and the Troodon2 still hasn't been transferred over from orca. Is there some issue, or was it just forgotten about? lol

**Comment by XunZhangBambu** [comment]
In next version ,you will see Troodon 2.0

**Comment by XunZhangBambu** [comment]
In latest version, we have added Troodon 2.0
