### ISSUE TITLE
Update manual 'flow calibration' to the modern method

### ISSUE THREAD

**Issue by nirurin** [bambulab/BambuStudio#2356]
**Is your feature request related to a problem? Please describe.**
The manual 'flow calibration' method on bambu studio is an old and really badly designed method. 

**Describe the solution you'd like**
Update to the newer 'Ellis' method, which Orcaslicer now uses - https://github.com/SoftFever/OrcaSlicer/pull/1547

![258110242-5647113e-f0f4-4b60-91f2-100d28fd0fcf](https://github.com/bambulab/BambuStudio/assets/3751273/847fb98d-9cb0-46cf-8197-6090697c4953)

**Comment by SaltWei** [comment]
Already add it for 3-rd party printer in 1.7.4.
@zhimin-zeng-bambulab Please add it for manual calibration in next version

**Comment by SaltWei** [comment]
![pa-pattern](https://github.co@jwise /bambulab/BambuStudio/assets/110660407/3f62ff9e-33ca-4d22-8f3c-5fcb06d1cf58)
@nirurin In 1.7.4， you can choose 3-rd party printer first, and enable the pa pattern. And then switch to Bambu printer to use it.

We will add the pattern in Calibration page directly in next version.

**Comment by MartynWilliams** [comment]
@zhimin-zeng-bambulab this appears not to be live in version 1.7.6.92, can you please confirm this omission.
