### ISSUE TITLE
Filament setting override to control chamber fan 

### ISSUE THREAD

**Issue by Belowthoc** [bambulab/BambuStudio#2358]
**Is your feature request related to a problem? Please describe.**

 when I print petg I find that cooling and chamber temp are highly important. currently, I cant find an easy way to set chamber fan speed unless altering filament g-code or changing it once the print has started.

**Describe the solution you'd like**

A simple button to activate and deactivate the chamber fan in the filament setting. When activated, you can input a percentage amount of how fast you want it to run.

**Comment by SaltWei** [comment]
> chamber fan

Which fan？ The fan in the back of chamber？

**Comment by Belowthoc** [comment]
Yes. The one that exhausts the chanber.

**Comment by XunZhangBambu** [comment]
Next version we will add the feature

**Comment by bani6809** [comment]
Please add this feature.

I have an external BOFA fume extractor attached to my X1C so I don't need chamber fan interfering with it, I'd like to turn chamber fan OFF.

**Comment by Belowthoc** [comment]
Glad you think its a good idea also. It would he such a simple addition.
And why not give controll over every aspect of the print process. Vent fan
is part of that process.

**Comment by XunZhangBambu** [comment]
![20231010215835_rec_](https://github.com/bambulab/BambuStudio/assets/139755545/4a7d4bc8-7588-40da-a593-0e4c59f946c1)

In the latest version V1.7.7, you can control chamber fan by controlling exhaust fan in Bambu printers . Using exhaust fan to enhance air filtration is a new feature of X1E  and haven't been thoroughly tested in other printers , and currently "support air filtration" is enabled by default only for X1E. So you need to open develop mode and enable "support air filtration" if you want to control exhaust fan in other Bambu printers.
