### ISSUE TITLE
No context in alert window.

### ISSUE THREAD

**Issue by werewolfenn** [bambulab/BambuStudio#2360]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10 pro, 64 bit

### Additional system information

Shouldn't matter for this issue.

### Printer

X1C

### How to reproduce

Be in an open project.    Click to start a NEW project.   This opens up asking if you want to discard or transfer changes made.

### Actual results

Box asking about discarding or transferring changes doesn't tell you what those changes are.   Relatively useless message.

### Expected results

If we are being asked if we wish to save or discard setting changes, we need to know where those changes apply.  
Yes, it shows OTHER, but more context would be more helpful.
![no context](https://github.com/bambulab/BambuStudio/assets/120329025/c268265b-5b74-4938-b6c7-37a0b0a26f04)

### Project file & Debug log uploads

[debug_network_Thu_Aug_17_19_14_41.log](https://github.com/bambulab/BambuStudio/files/12410124/debug_network_Thu_Aug_17_19_14_41.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
@werewolfenn could you shared your project 3mf file with me?

**Comment by bambu123** [comment]
> @werewolfenn could you shared your the failure project 3mf file with me?

**Comment by bambu123** [comment]
Fixed in v1.8.2.
