### ISSUE TITLE
Supports > Tree > Style Default - Is Regular Support, Not a Tree

### ISSUE THREAD

**Issue by jason-e-gross** [bambulab/BambuStudio#2362]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

12th gen I-7
Geforce 3060
64GB RAM
2TB SD

### Printer

p1p

### How to reproduce

Go to Support
Enable Tree (auto)
Default Style

-- its a normal support, not a tree at all.

### Actual results

It's a normal support, not a tree

### Expected results

A tree

### Project file & Debug log uploads

[project-and-screenshots.zip](https://github.com/bambulab/BambuStudio/files/12413650/project-and-screenshots.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by jason-e-gross** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/16501884/ea9594d9-66d8-4b6e-bc9c-f524e680379e)
![image2](https://github.com/bambulab/BambuStudio/assets/16501884/b37c75e1-b8f3-47c3-adfa-6209aa7dd818)

**Comment by jason-e-gross** [comment]
![tree-default](https://github.com/bambulab/BambuStudio/assets/16501884/2a60544d-bdac-4a86-acd0-80a1ba619438)
![tree-slim](https://github.com/bambulab/BambuStudio/assets/16501884/922c525e-df5f-4580-b381-443c53bf01aa)

**Comment by NAM1025** [comment]
This is happening for me as well and I'm on 1.6.2.4. Support critical regions only gets rid of it, but I need the critical regions to be supported as well so it doesn't solve the issue for me.

![image](https://github.com/bambulab/BambuStudio/assets/28747418/427a1b7a-1aa4-4094-a9d1-9c8e7793978b)

**Comment by tangketan** [comment]
Default style of tree support is "tree hybrid", which is the combination of tree and normal supports. When an overhang area is large and flat, normal supports will be generated.
If you don't like the style, just change it to tree slim or tree strong.

**Comment by namarinelli** [comment]
> Default style of tree support is "tree hybrid", which is the combination of tree and normal supports. When an overhang area is large and flat, normal supports will be generated. If you don't like the style, just change it to tree slim or tree strong.

Oh, I didn't realize. I assumed "Tree Hybrid" was a combination of "Tree Slim" and "Tree Strong"

**Comment by jason-e-gross** [comment]
Same -- having "Default" _and_ "Tree Hybrid" in there makes it confusing.   If you choose "Tree (auto)" maybe get rid of "Default" and have it simply default to "Tree Hybrid" with a tool tip that explains the app will choose between normal and tree.

Because now you're _explicitly_ picking "Tree (auto)" and don't expect to see non-tree generation inside it.

I wouldn't agree that this is "Completed", because the UI is misleading and what it says for **Default** is different than what it describes for "Tree Hybrid" (a mix of normal and tree).
