### ISSUE TITLE
Color Painting > Fill: Ignores STL dimensions

### ISSUE THREAD

**Issue by cutmoney** [bambulab/BambuStudio#2363]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS 13.4.1

### Additional system information

MacBook Pro M1 Max 2021

### Printer

Bambu Lab P1P

### How to reproduce

1. Import model with multiple bodies intended for multi-color.
2. Utilize the Color Painting > Fill tool to colorize specific parts of the model.

### Actual results

As is indicated in the attached project file and images, the model has the AB letters that extend 5mm in to the body. Bambu Studio only extends the color .6mm deep, and the outline 1.0mm deep. The actual model has the letters cut 5mm deep. Is this a bug? Is there any way for Bambu Studio to recognize the actual size of the bodies that I want colorized? Or to specify the depth of the color?

<img width="804" alt="Screenshot 2023-08-22 at 7 59 05 PM" src="https://github.com/bambulab/BambuStudio/assets/4040591/51e28a0c-dcd9-4394-9e96-c94de26f35f9">
<img width="1063" alt="Screenshot 2023-08-22 at 7 55 15 PM" src="https://github.com/bambulab/BambuStudio/assets/4040591/8b0739d9-4152-46c8-b489-01deb6187b14">
<img width="1054" alt="Screenshot 2023-08-22 at 7 55 27 PM" src="https://github.com/bambulab/BambuStudio/assets/4040591/2ef4b87e-7c52-43e3-9091-52515eedb16c">
<img width="1050" alt="Screenshot 2023-08-22 at 7 55 47 PM" src="https://github.com/bambulab/BambuStudio/assets/4040591/0d3de1e4-1087-4360-8cc4-d6976f5f530d">
<img width="1059" alt="Screenshot 2023-08-22 at 7 55 37 PM" src="https://github.com/bambulab/BambuStudio/assets/4040591/b03dd5d7-96c8-4f35-8261-d3b97a25d22e">

### Expected results

The color would extend to the entire body depth of the selected feature. In this case, 5mm deep instead of the .6mm deep. Alternatively, there is an option to select how deep the color would go.

### Project file & Debug log uploads

[AB Test.3mf.zip](https://github.com/bambulab/BambuStudio/files/12414137/AB.Test.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@cutmoney  The 3mf file you made only has coloring information, and the 3mf file does not contain the size information of the infill part.

**Comment by cutmoney** [comment]
> @cutmoney The 3mf file you made only has coloring information, and the 3mf file does not contain the size information of the infill part.

That was the Bambu Studio file, and it works identically with any object. Nevertheless, here is an example 3mf...
[test.3mf.zip](https://github.com/bambulab/BambuStudio/files/12458798/test.3mf.zip)

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/20e74950-9eaa-4a25-827d-dfd134bcfa46)

@cutmoney  In this case, you do not need to paint, you can  set  Body2(A) and Body3(B) to white color. 
As shown in FIG.

**Comment by zhimin-zeng-bambulab** [comment]
@cutmoney Do the above steps solve your problem?

**Comment by zhimin-zeng-bambulab** [comment]
If you want the sub-part to display the corresponding color, you should set the default color of the sub-part instead of painting the surface.

**Comment by cutmoney** [comment]
> If you want the sub-part to display the corresponding color, you should set the default color of the sub-part instead of painting the surface.

Being able to colorize individual parts is exactly what I wanted. Thanks. When I export directly from Fusion 360 it comes in as a single body, however when I export and import as a file, it allows for the different parts. Thanks for the info, that's helpful!
