### ISSUE TITLE
Building a Windows environment will always report errors dep_OpenEXR-prefix and dep_wxWidgets-prefix

### ISSUE THREAD

**Issue by ZZQiang-An** [bambulab/BambuStudio#2367]
Can anyone help me look at this???
![微信截图_20230823144354](https://github.com/bambulab/BambuStudio/assets/85558636/8a795c50-73e1-4768-a988-b88ec4d5e0fe)
![微信截图_20230823144252](https://github.com/bambulab/BambuStudio/assets/85558636/348c7f38-a809-4362-91c5-69cbd9880cb7)

**Comment by lanewei120** [comment]
oops, just missed this issue before

do you still have this issue?

it seems the patch stage of wxwidget failed for the second time
you can remove dep_wxWidgets folder and try again

sorry for the late reply

**Comment by ZZQiang-An** [comment]
![微信图片_20230908111839](https://github.com/bambulab/BambuStudio/assets/85558636/23d0cc4f-84f1-40e8-904c-4380d84ca38c)
What about this error?
@lanewei120

**Comment by lanewei120** [comment]
> ![微信图片_20230908111839](https://user-images.githubusercontent.com/85558636/266493313-23d0cc4f-84f1-40e8-904c-4380d84ca38c.png) What about this error? @lanewei120

please send the full log of building error

**Comment by ZZQiang-An** [comment]
> > ![微信图片_20230908111839](https://user-images.githubusercontent.com/85558636/266493313-23d0cc4f-84f1-40e8-904c-4380d84ca38c.png)这个错误呢？
> 
> 请发送完整的建筑错误日志

[build BambuStudio log.txt](https://github.com/bambulab/BambuStudio/files/12556797/build.BambuStudio.log.txt)
![AA2437C5-23FE-496e-B0E4-B366FF50B351](https://github.com/bambulab/BambuStudio/assets/85558636/5876d7c8-de16-42ad-9a38-3e538f27e43b)
![4EA5D5C4-A542-42fe-A26E-0C8EF55E9DCA](https://github.com/bambulab/BambuStudio/assets/85558636/e7bb3bb2-0925-41be-b4ff-a28dd0fba395)
What causes this error to show up when opening? Can you tell me?

**Comment by lanewei120** [comment]
the building error consist of two reasons:
1. wxWidgets patch failed
to fix it, you need to rm C:\Slicer\Bambu\BambuStudio\deps\build\dep_wxWidgets-prefix, and rebuild again
2. networking error
error : RPC failed; curl 18 HTTP/2 stream 5 was reset
as lots of codes are on github, you need to use a better network connection

**Comment by lanewei120** [comment]
> hat causes this error to show up when opening? Can you tell m

@bambu123 could you check the edge related issue

**Comment by bambu123** [comment]
> > > ![微信图片_20230908111839](https://user-images.githubusercontent.com/85558636/266493313-23d0cc4f-84f1-40e8-904c-4380d84ca38c.png)这个错误呢？
> > 
> > 
> > 请发送完整的建筑错误日志
> 
> [build BambuStudio log.txt](https://github.com/bambulab/BambuStudio/files/12556797/build.BambuStudio.log.txt) ![AA2437C5-23FE-496e-B0E4-B366FF50B351](https://user-images.githubusercontent.com/85558636/266536337-5876d7c8-de16-42ad-9a38-3e538f27e43b.png) ![4EA5D5C4-A542-42fe-A26E-0C8EF55E9DCA](https://user-images.githubusercontent.com/85558636/266536354-e7bb3bb2-0925-41be-b4ff-a28dd0fba395.png) What causes this error to show up when opening? Can you tell me?

Install a public version of BambuStudio first.

**Comment by lanewei120** [comment]
we have found a building error of OpenEXR and solved at https://github.com/bambulab/BambuStudio/pull/3188
