### ISSUE TITLE
Crash on Mac when reconnecting to a printer via LAN

### ISSUE THREAD

**Issue by DarrenLynch** [bambulab/BambuStudio#2372]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS Monterey

### Printer

P1S

### How to reproduce

1. Open bambu lab
2. Open a project
3. slice and print
4. After the print starts, close the MacBook
5. Some time later, re-open MacBook
6. Navigate to devices, when your printer (LAN) re-appears, connect
7. Bambu labs crashes
8. When you open it again you are prompted to recover project

### Actual results

Bambu labs crashes

### Expected results

No crash, printer connects and you can see its progress and status as expected

### Project file & Debug log uploads

[Archive.zip](https://github.com/bambulab/BambuStudio/files/12422218/Archive.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.
We will fix this issue

**Comment by walterwongbbl** [comment]
@DarrenLynch  
Can you provide a console log. the studio should have experienced a crash
![image](https://github.com/bambulab/BambuStudio/assets/120699126/dd5f8e1c-c96a-4300-a67c-376a86f0f209)
![image](https://github.com/bambulab/BambuStudio/assets/120699126/b7e546b3-a41d-4538-a350-984a6aa219c2)

**Comment by DarrenLynch** [comment]
@walterwongbbl sure:
[bambuCrashReports.zip](https://github.com/bambulab/BambuStudio/files/12453094/bambuCrashReports.zip)

**Comment by walterwongbbl** [comment]
Hi. @DarrenLynch 
Please download and use the latest Studio version

**Comment by walterwongbbl** [comment]
We have applied the latest version, please download the latest version to experience it.
