### ISSUE TITLE
关于黑色耗材的模型显示优化

### ISSUE THREAD

**Issue by abc77654** [bambulab/BambuStudio#2374]
目前bambu切片一些黑色耗材，默认是纯黑色的，导致看不清模型的结构细节，只能通过改成深灰色才能稍微看清一些。

![image](https://github.com/bambulab/BambuStudio/assets/102788822/8a8205af-5095-4461-b0b1-799fcde09986)

或者能否再黑色耗材模型中增加轮廓线条显示例如：
![image](https://github.com/bambulab/BambuStudio/assets/102788822/90a5e173-eced-4ae3-b6e3-62b30ec6c629)

**Comment by QingZhangBambu** [comment]
这个问题我们以及在改进中，下个正式版本黑色的显示将会改善。感谢您对此问题的关注，更新后我会及时在这里通知您，

**Comment by Haidiye00** [comment]
The issue has been fixed, please use the latest version V1.8
