### ISSUE TITLE
Support Interface - First Layer of interface using wrong material

### ISSUE THREAD

**Issue by jennyy867** [bambulab/BambuStudio#2375]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS Ventura 13.1 

### Additional system information

CPU: 3 GHz 6-Core Intel Core i5
Memory: 8 GB 2667 MHz DDR4
Graphics: Radeon Pro 570X 4 GB

### Printer

BambuLab X1C-Combo

### How to reproduce

1. Using a model that requires support, check on the support function and set your interface to "Support for PLA", leave raft/base set to default or select PLA. 
2. Uncheck "flush into supports". Support Type is Tree Auto, 5.5 branch distance, 3 branch diameter. 2 top interface layers, concentric pattern.
3. Slice the model with a different color PLA from Supports
4. Go to preview and view filament color. Slicing all the way down to the start of the support interface, you'll see a concentric pattern of support in the same PLA color (non support).
5. Switch to Line Type and you can confirm it is a Support line. 

### Actual results

The slicer is placing an "interface layer" made of PLA, not support material, despite the settings. This means the support cannot actually be removed. Compare layer 40, 41 (bad), and 42 in the model.

<img width="2016" alt="Screenshot 2023-08-24 at 7 35 22 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/35630080-7744-424e-b3e3-86b585c4f9bb">
<img width="2016" alt="Screenshot 2023-08-24 at 7 35 25 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/ef433565-3169-46cf-b1cf-c615918c7498">

<img width="489" alt="Screenshot 2023-08-24 at 7 38 51 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/17f8b46a-3cb4-4377-8e9b-625d357ec0a2">
<img width="2016" alt="Screenshot 2023-08-24 at 7 34 40 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/a856b0e3-d1c8-4caa-ba87-94c8985bcbc7">
<img width="2016" alt="Screenshot 2023-08-24 at 7 34 48 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/bfc04db2-6995-45da-8b61-b18d563ca94a">
<img width="2016" alt="Screenshot 2023-08-24 at 7 35 06 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/edc49a71-346c-4b74-b512-92bba62c5dc5">
<img width="2016" alt="Screenshot 2023-08-24 at 7 35 10 AM" src="https://github.com/bambulab/BambuStudio/assets/142698144/5b7b92b8-254c-4475-878a-18a464919caa">

### Expected results

Because "support for PLA" is chosen as the interface material, the part touching the model should be printed with support material, not the model's PLA. 

### Project file & Debug log uploads

[BambuBug-InterfaceIssue.3mf.zip](https://github.com/bambulab/BambuStudio/files/12428987/BambuBug-InterfaceIssue.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
Thanks for reporting. It's a known issue. We have fixed it in our internal version. Please wait for the next release.

**Comment by jennyy867** [comment]
Thank you! Any idea when that might be? I rolled back to an older version but I'd sure like to use the nifty calibration tools in the new one

**Comment by jennyy867** [comment]
@tangketan I just checked and this behavior persists in the newest release from 3 days ago (1.7.6.92).  Do you need a new ticket, or did it just not make it into the release?

**Comment by tangketan** [comment]
Offical 1.8 has been released and this bug is fixed. Close this issue.
