### ISSUE TITLE
In "Send print job to" page, PLA-Aero is recognize as PLA-Basic. So Can't print with PLA-Aero preset

### ISSUE THREAD

**Issue by xuhao1** [bambulab/BambuStudio#2377]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS

### Printer

X1CC

### How to reproduce

1. Slice 3d models with Bambu PLA Aero material
<img width="1854" alt="image" src="https://github.com/bambulab/BambuStudio/assets/5087930/c2f5d06d-5482-417e-9e03-4c8459ca519d">
In fiament dropbox, the PLA-Aero is PLA-Aero, also on machine screen.
<img width="442" alt="Screenshot 2023-08-24 at 22 32 24" src="https://github.com/bambulab/BambuStudio/assets/5087930/26ba29e9-3bd1-4ffc-b517-8e56f5080070">

2. Print

### Actual results

In "send job" page, the PLA-Aero will be recognize as PLA. So I can't print with it.

### Expected results

I want print PLA-Aero with AMS.
I have use FusRock PLA-Aero with AMS, and it is quiet good.

### Project file & Debug log uploads

[Wings.3mf.zip](https://github.com/bambulab/BambuStudio/files/12430556/Wings.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by a1axx** [comment]
Just to add to this.

I have been printing with Bambu PLA-Aero.

1: the work around is to set go to your filament preset for PLA-Aero and change it to PLA, it will then allow you to print from the AMS

2: as the filament isn't correctly supported, K factor has to be manually selected before printing after a power cycle. It 'sticks' for all other Bambu filaments in the AMS

**Comment by xuhao1** [comment]
@a1axx Thanks! It works!

**Comment by StoneLiBambulab** [comment]
Hi, 
the filament type in the filament preset of Bambu Studio and the filament type reading from the real filament did not match. we found a way work around it in release 1.8.

Thanks!

Stone Li

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/131c6ef6-aad7-45f8-9c5b-6f31f29f5109)
It's OK under latest 1.8 version and latest firmware.
Thanks for reporting issue for us.
