### ISSUE TITLE
Bambu Studio on Mac OS Launchs but not window is visible to interact with or use.

### ISSUE THREAD

**Issue by Taproot13** [bambulab/BambuStudio#2382]
### Bambu Studio Version

01.07.04.52

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Version 13.5.1

### Additional system information

M2 Max with 64 Gb ram

### Printer

Bambu Lab X1 Carbon

### How to reproduce

Go to Applications
Click Bambu Labs Icon
Programs opens but no window is visible
The program shows in the doc and I can click on the doc to select program
I can click settings and other menu items at top of screen
But no window to use the software

### Actual results

No window to use the software

### Expected results

Nothing

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12434468/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bambu123** [comment]
@Taproot13 The app may have crashed. Please check if there are crash reports.

On macOS, your crash dumps are automatically handled by Crash Reporter. You can find backtrace files by executing Console and going to the User Diagnostic Reports section (under the 'Diagnostic and Usage Information' group) or you can locate them in ~/Library/Logs/DiagnosticReports.

**Comment by twirler-jousts** [comment]
hey in case you are still having this problem, i ran into the same issue myself.  i think it is something to do with the way mac handles windows and multiple desktops or fullscreens in mission control.  not sure how it happened in the first place.  
Steps to fix:
1) open up bambu studio
2) click view in taskbar
3) click enter fullscreen. you should now see bambuStudio in fullscreen mode
4) open mission control (f3 or swipe up on trackpad with 4 fingers)
5) drag bambuStudio into an existing desktop
6) you should now have bambuStudio as a resizable window like normal. 
good luck!

**Comment by Taproot13** [comment]
Thank You!

This fixed my issue, I appreciate you taking the time to pass along the information. Happy Printing.

**Comment by iroitosheik** [comment]
> hey in case you are still having this problem, i ran into the same issue myself. i think it is something to do with the way mac handles windows and multiple desktops or fullscreens in mission control. not sure how it happened in the first place. Steps to fix:
> 
> 1. open up bambu studio
> 2. click view in taskbar
> 3. click enter fullscreen. you should now see bambuStudio in fullscreen mode
> 4. open mission control (f3 or swipe up on trackpad with 4 fingers)
> 5. drag bambuStudio into an existing desktop
> 6. you should now have bambuStudio as a resizable window like normal.
>    good luck!

It worked perfectly, thanks !

**Comment by mcfets** [comment]
Thanks the solution worked for me too.  So frustrating!

**Comment by GenericArt** [comment]
@twirler-jousts Thanks so much, this saved me!

**Comment by egdavid** [comment]
And if the Bambu Studio window is off-screen after that, you can retrieve it by clicking on Window and then Zoom.
