### ISSUE TITLE
Tree Supports

### ISSUE THREAD

**Issue by Daggers62** [bambulab/BambuStudio#2384]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Labs X1C

### How to reproduce

Using Tree Supports both normal and hybrid they continually fail.
PEI or Cold Plate
Tree (Auto)
Tree Style: Hybrid
Threshold angle: 30
Branch Distance: 5mm
Branch Diameter: 4mm
Branch Angle: 60
Wall Loops: 4
Brim Width: 5mm

### Actual results

The tree supports fail.
I have tried tree supports with various models while using the gold PEI sheet supplied by Bambu Labs as well as using the Cold Plate that comes with the machine. The tree supports fail to stick to the bed and get knocked over as the branches become higher and thinner.
I have increased the branch to four walls, I have tried a 5mm brim, I have tried a 60 degree angle. I have washed and cleaned the build plates with 100% alcohol but the tree supports always get knocked over by the hotend or come loose from the bed.

### Expected results

The tree supports should work.

### Project file & Debug log uploads

[Logs.zip](https://github.com/bambulab/BambuStudio/files/12436909/Logs.zip)
[Dolphin_B.zip](https://github.com/bambulab/BambuStudio/files/12436925/Dolphin_B.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by tangketan** [comment]
The file Dolphin_B.zip seems incomplete. I can't open it. Please re-attach the file.

**Comment by Daggers62** [comment]
[Dolphin_B.zip](https://github.com/bambulab/BambuStudio/files/12485823/Dolphin_B.zip)

**Comment by Daggers62** [comment]
All of these prints have failed because of tree supports coming loose from the bed. I have added a link to my YouTube channel for you to see the Timelapse videos as they are too large to send here.
These are printed in marble and silk filaments which has wasted so much that I think you could now send me replacement filament to compensate.
![20230901_074406](https://github.com/bambulab/BambuStudio/assets/143167892/0dfffde1-15e9-487e-8e80-a49a6bf8043a)

https://youtu.be/GlyUA-g-xM8

**Comment by tangketan** [comment]
I'm sorry for your loss... The file you sent for the second time is still unusable, just like the first one. Can you send it to my email please? tangketan1234 at gmail.com

From the timelapse video, I can see all the supports are knocked off from the build plate except for the first one, which seems to have only one wall loop. This means the adhesion is not strong enough. My suggestion is: 
- check your bed temperature (textured PEI needs at least 55 degrees C).
- further increase the support brim. Make it 10mm, for example.
