### ISSUE TITLE
Calibration/calibrate button on title bar disappears

### ISSUE THREAD

**Issue by Thibo-do-it** [bambulab/BambuStudio#2387]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

windows 11 64 bit

### Printer

X1C

### How to reproduce

1. open bambu studio
2. go to prepare tab
3. sometimes the calibrate/calibration button is in the title bar of the window, and other times it is missing

### Actual results

sometimes the calibrate/calibration button is in the title bar of the window, and other times it is missing

![image](https://github.com/bambulab/BambuStudio/assets/143223684/721b96b9-57fa-450e-8c93-6617ff59776e)

### Expected results

calibration button should always be there

### Project file & Debug log uploads

not sure when it last appeared

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MadMax389** [comment]
Calibration only shows up on the top toolbar when you have a non-Bambu printer selected. 
![image](https://github.com/bambulab/BambuStudio/assets/96731892/9a27b35f-bacf-4a59-8e7b-ba5096bc8147)

**Comment by Thibo-do-it** [comment]
It also shows up sometimes when my X1c is selected. I don't have another
printer setup on bambu studio.

How can I access all the calibrations when the X1c is selected?

Regards,
Caleb Thibodeaux

**Comment by MadMax389** [comment]
It should show up on the lower toolbar next to Project
![image](https://github.com/bambulab/BambuStudio/assets/96731892/5842bec9-0d93-402a-b0a7-ea200e7dd5ae)

**Comment by Thibo-do-it** [comment]
That calibration tab is missing most of the calibration tests such as max
volumetric flow rate and temp tower.

Regards,
Caleb Thibodeaux

**Comment by MadMax389** [comment]
Those particular calibrations are only available in Orca, I believe.

**Comment by Thibo-do-it** [comment]
That's the issue. They are not only in orca. I created the bug because
they're available in bambu studio sometimes.

Regards,
Caleb Thibodeaux

**Comment by MadMax389** [comment]
The only time I have ever seen that calibration tab on the top toolbar is when there is a non-Bambu printer selected. (There is an issue thread on this somewhere in Github. Like https://github.com/bambulab/BambuStudio/issues/2101) Even when it is available, the gcode does not work correctly for the temp tower. The temperatures are too low. My point is it's not a bug, it's just not a supported feature yet.

![image](https://github.com/bambulab/BambuStudio/assets/96731892/a710aaee-e9ef-432c-ab88-033602ea9f7d)

**Comment by Thibo-do-it** [comment]
I see. Thank you for the clarification. That makes sense. My calibration
towers were coming out weird.

Regards,
Caleb Thibodeaux

**Comment by MadMax389** [comment]
I just used Orca to do the temp tower and maximum flow calibrations, which are one-time tests per filament material as far as I'm concerned. The automatic flow ratio and flow dynamic calibrations (k-factor) available in Studio for the X1C are easier and better than the Orca tests in my opinion. I use the values generated on the X1C in my filament profiles for my P1P.

Regards

**Comment by zhimin-zeng-bambulab** [comment]
When you select a non-Bambu preset, the calibration button in the title bar will show, and it will not show in toolbar next to Project. And if you select a Bambu preset, it will show in toolbar next to Project.

At present, there are only "Flow Dynamic" and "Flow Rate" two calibrations for bambu. If there is any need for other calibrations, you can discuss them there(https://github.com/bambulab/BambuStudio/issues/2101).

**Comment by mmmlinux** [comment]
I can repeatedly make this configuration menu appear with a bambu x1c selected if i drag bambu studio from a high dpi display to a lower dpi display, It will cause the config menu to appear. Please make it available with our bambu brand machines!

**Comment by manofpants** [comment]
This is still happening. Newest version of Bambu Studio 1.9.3.50 and I can't see the calibration menu half the time.

**Comment by MULAWI** [comment]
> I can repeatedly make this configuration menu appear with a bambu x1c selected if I drag bambu studio from a high dpi display to a lower dpi display, or the other way. Then the config menu will appear. Please make it available with our bambu brand machines!

Thats true, if I move the Bambu Studio to a less reslution Display it desapears and back again if I move it to a higher resolution Display.

**Comment by Sveeeeeen** [comment]
Why is this still an issue in 2025 and v2.0.2.57?
Please fix it.

**Comment by ryanmiller831** [comment]
I am still getting this bug as well. Can Bambu developers please include the manual calibration feature for advanced settings in Bambu Studio? If it is available for other printers, why can't we use it as well?

**Comment by ITBeee** [comment]
Same Issue. I use the Bambu Studio V 2.1.1.52. The Calibration Tab only shows up if i turn my Monitor off and then on again.

**Comment by andrespsan** [comment]
if you move the window to another monitor, then the menu will appear. It's a bug

![Image](https://github.com/user-attachments/assets/4aa08ac0-4762-4170-a17b-f06a1d713dbd)

**Comment by 1wayjonny** [comment]
**Update The wiki says this if for non-bambu selected printers only. When switching from monitors or sleeping the monitor at times will cause this to show for even Bambu printers.**

Hello - I can make this happen by switch the application from monitor to monitor. When doing so I clicked the menu drop down and it has a host of goodies.

I would say this is official for Bambu because when you click the tutorial link in the drop down to use the tools it directs you to the Bambu wiki here: [https://wiki.bambulab.com/en/bambu-studio/Calibration](https://wiki.bambulab.com/en/bambu-studio/Calibration )

<img width="933" height="466" alt="Image" src="https://github.com/user-attachments/assets/6e0e8897-670b-4991-b3f9-5c39c174bf43" />

**Comment by sakrlog** [comment]
> **Update The wiki says this if for non-bambu selected printers only. When switching from monitors or sleeping the monitor at times will cause this to show for even Bambu printers.**
> 
> Hello - I can make this happen by switch the application from monitor to monitor. When doing so I clicked the menu drop down and it has a host of goodies.
> 
> I would say this is official for Bambu because when you click the tutorial link in the drop down to use the tools it directs you to the Bambu wiki here: https://wiki.bambulab.com/en/bambu-studio/Calibration
> 
> <img alt="Image" width="933" height="466" src="https://private-user-images.githubusercontent.com/39279069/466235166-6e0e8897-670b-4991-b3f9-5c39c174bf43.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ0MjkwMTcsIm5iZiI6MTc3NDQyODcxNywicGF0aCI6Ii8zOTI3OTA2OS80NjYyMzUxNjYtNmUwZTg4OTctNjcwYi00OTkxLWIzZjktNWMzOWMxNzRiZjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzI1VDA4NTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMzdkYzhiODQyOGYxNTQ5Y2EwMDk3ZTNkYjdhY2E3OWY0ZmU0YjY3NmU2YWJhM2QxMzEyNmI0YjVjOTI1YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F9xpLOnVpBo8M91ce1icF2mETceEcja2J4QzyBy-HQM">

That is not accurate tho, my firend got his first Bambu printer (H2C), he is able to see and use the calibration button and it has a ton of features. It's been 3 years since this issue was flagged and still no solution? FYI, I tried everything mentioned here concerning the display resolution, nothing worked.
