### ISSUE TITLE
"Text shape" broken in 1.7.4.52?

### ISSUE THREAD

**Issue by j0nas** [bambulab/BambuStudio#2396]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Testen both Windows 10 & macOS

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. In "Prepare view", click on "EmptyLabel" printable object
2. Click on "Text shape"
3. Enter text in "Input text" field
4. Click somewhere on printable object

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/6001131/64fa1f50-d8ca-4497-a5cc-c70395126898)

A small magenta-colored square appears. Attempting to click on it simply focuses the object.

![image](https://github.com/bambulab/BambuStudio/assets/6001131/a05bd07c-ee64-472d-999a-3f0724415dd2)
After playing around with this a lot more, I found a couple pixels where the text appears. It seems to only want to place the text on the side of the object.

### Expected results

The preview text should appear and be placable no matter which surface I hover.

### Project file & Debug log uploads

[Text bug.zip](https://github.com/bambulab/BambuStudio/files/12447557/Text.bug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by j0nas** [comment]
More context: if I rotate the "EmptyLabel" object so that it is upright, I can place the text. But I cannot do so when the object is lying down. This will likely be very confusing for people who don't know how to work around this. 
![image](https://github.com/bambulab/BambuStudio/assets/6001131/bb6e0693-e854-467d-8c6c-6d72b8476ced)

My best guess is that the "text shape" tool works on the objects **initial** orientation instead of its current orientation; the "EmptyLabel" object was imported upright. 

Placing the text in the initial position and then rotating the object works as a workaround.
![image](https://github.com/bambulab/BambuStudio/assets/6001131/180f01f1-7a09-40ca-b219-58fd498ad602)

**Comment by j0nas** [comment]
Editing the text does not work either, but works again if I rotate the object back to its initial orientation.

**Comment by MadMax389** [comment]
I have also noticed some weirdness around text orientation vs initial model orientation. If you uncheck the "Surface" box, you can lay it flat on the top surface, however.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in V1.7.6
