### ISSUE TITLE
Incorrect Error Message Generated When Using Height Range Modifier

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#2399]
### Bambu Studio Version

1.7.2.54

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

Intel 10th gen Core i5

### Printer

X1C w/AMS

### How to reproduce

If the layer height specified in the height range modifier is less than the minimum height specified in the printer profile, an error is generated with the text "Layer height cannot exceed nozzle diameter". It took me a while to figure out what was going on since the layer height specified in the height range modifier did not exceed the nozzle diameter. I was using a modified printer profile where I had set the minimum layer height to .16mm and tried to specify a .1mm layer height.

To Reproduce:
1. Add any primitive to the plate
2. Change the minimum height in the printer profile to .16mm
![image](https://github.com/bambulab/BambuStudio/assets/96731892/ae2b1796-2cca-4e2b-a9d3-79a564fef293)
3. Add a height range modifier to the primitive and change the layer height for the modifier to .1mm
![image](https://github.com/bambulab/BambuStudio/assets/96731892/85d2f2f8-83d9-4851-b63f-0aa581650c0e)

### Actual results

Message is generated indicating the layer height is greater than the nozzle width.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/23481da9-e2a7-4e81-a348-d71fb96e1be2)

### Expected results

Message should read something like "Layer height cannot be less than minimum layer height in the printer profile"

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
The message and interaction here has been modified.
