### ISSUE TITLE
[Bug] Print>Send print job to dialog is not centered on screen

### ISSUE THREAD

**Issue by LarryVand** [bambulab/BambuStudio#24]
Print>Send print job to dialog is not centered on screen. Send button is not shown till dialog is dragged and moved higher.

**Comment by RobinWhitfield** [comment]
Presuming this is on Windows, what resolution/scaling are you using?

Can you attach a screenshot?

It's pretty centred on a 1080p screen at 100% scaling on Windows 11:
![image](https://user-images.githubusercontent.com/63362209/179468783-fa63f6b4-ed9a-4022-ac09-478e6c757550.png)

**Comment by LarryVand** [comment]
Unfortunately it is not centered on a 1920x1080 at 125% scaling on Window 10 Home Version 10.0.19044
![Studio1](https://user-images.githubusercontent.com/69426512/179471213-e9528df5-5cc9-49a9-8e0e-fb8a0e42e634.JPG)

**Comment by RobinWhitfield** [comment]
As they seem to be hardcoding the application size maximum to your primary monitor (#7), perhaps they're also using that resolution for pop-up window positioning, ignoring scaling.

**Comment by YifanWuBambu** [comment]
Fixed in the latest version.
