### ISSUE TITLE
Arc Welder

### ISSUE THREAD

**Issue by Gahmp** [bambulab/BambuStudio#240]
Please add support for arc welder

**Comment by RobinWhitfield** [comment]
Bambu Studio already supports and creates arcs (which is what arc welder does) so there's no need.

Ensure you use high poly models as much as possible, ideally STEP to get the most out of what the slicer and printer can do with curves.

**Comment by Gahmp** [comment]
Thanks for the information.  I checked the model that I was printing and found what you are describing.

**Comment by Gahmp** [comment]
Why am I not seeing version v1.2.0 listed on github anymore.  When I go to
gethub it's telling me that v1.1.1.1 is the latest version.
