### ISSUE TITLE
Sleep mode MAC, update printing process

### ISSUE THREAD

**Issue by DJ-O** [bambulab/BambuStudio#2402]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

MAC OS 11.7.8

### Additional system information

<img width="540" alt="Schermafbeelding 2023-08-27 om 13 17 07" src="https://github.com/bambulab/BambuStudio/assets/143325424/e5846bfb-ee7d-4ede-bc2c-52803e362769">

### Printer

BL X1C

### How to reproduce

When the printing is finished and my MAC is in "sleeping mode", I can't start a new print job as Bambu Studio is still assuming the printer is still busy. I have to close and then open Bambu lab for the refresh. Very annoying. Older versions it was never a problem.

### Actual results

<img width="906" alt="Schermafbeelding 2023-08-27 om 13 10 18" src="https://github.com/bambulab/BambuStudio/assets/143325424/9a03917c-55e3-4f43-a6fd-d3d6ea539e56">
<img width="668" alt="Schermafbeelding 2023-08-27 om 13 10 33" src="https://github.com/bambulab/BambuStudio/assets/143325424/e7616f19-48f5-4bad-8711-44d6fa302b1a">

### Expected results

The printer needs to send feedback to bambulab studio that the printing job is finished. Or please make a refresh button in the tab "device" or something. 

Thanks 
Brgds Didier

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
@DJ-O 
Hi.
We are trying to solve this issue.

**Comment by walterwongbbl** [comment]
@DJ-O 
Does this issue occur every time your computer wakes up from sleep mode?

**Comment by walterwongbbl** [comment]
@DJ-O 
Does Bambu Studio freeze or crash when your Mac wakes up from sleep mode?

**Comment by DJ-O** [comment]
Hello Walter.

No, Bambu studio never freeze or crash. I can do anything except starting a
print job (via cloud). During printing, BL studio gets feedback from the
printer as you can see at the progress bar. After printing apparently not
anymore and BL studio “things” the printer is still busy. The progress bar
doesn’t go to 100% but stays at a value when the Mac go’s to sleep I guess.
The strange thing is the camera image works live, so printer send data.

Brgds Didier

Met vriendelijke groet, Didier


Op do 7 sep. 2023 om 04:29 schreef walterwongbbl ***@***.***>

**Comment by walterwongbbl** [comment]
Hi. @DJ-O 
Can you provide the log files from when the issue occurs?
![image](https://github.com/bambulab/BambuStudio/assets/120699126/1ebbf7cd-bf4b-4f9c-9e2f-8759bc7a80ab)
![image](https://github.com/bambulab/BambuStudio/assets/120699126/16ef81ae-e652-4be3-95a3-02c939498090)

**Comment by walterwongbbl** [comment]
We have applied the latest version, please download the latest version to experience it.
