### ISSUE TITLE
[Issue] Skip Flow Rate Calibration1 step

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#2416]
I had a flow rate calibration get disconnected from the printer, however the calibration did complete.
Because it disconnected the calibration1 step didn't know where it was at and there's no way to enter the calibration number.
Is there a way to force skip Calibration1 to enter the correct number based on the completed print?

**Comment by zhimin-zeng-bambulab** [comment]
@BambuLabDiscord Do the above suggestions meet your needs?

**Comment by zhimin-zeng-bambulab** [comment]
If encounter similar problems, please refer to the suggestions given above.
