### ISSUE TITLE
List of supported G an M-Codes

### ISSUE THREAD

**Issue by markus512** [bambulab/BambuStudio#2419]
**Is your feature request related to a problem? Please describe.**
This is my only printer which does neither have any list of supported g-codes nor follows an open-source implementations g-codes. Allthough Marlin does fit for some of them there are many G and M-Codes which are undocumented. It's very annoying to work with such device.

**Describe the solution you'd like**
A clear and concise description of all G and M-Codes supported by Bambu-Lab printer.

**Describe alternatives you've considered**
Dumping firmware from a printer and reverse engineer this info which is a pain in the ass and definitely not my preferred way.
I also don't think It's Bambus preferred way as it would show me technical details which I probably should not see.

**Comment by SaltWei** [comment]
@sodachen22 Should be handled by firmware team

**Comment by markus512** [comment]
I'd just like to add that everything you can provide will be helpful to me. 
No matter whether it's a beautiful translated list or just a note written in chinese.

**Comment by markus512** [comment]
I think I'll trash my printer and replace it with a better one (one which has good documentation or is open source)

**Comment by GuzziRaz** [comment]
@sodachen22 please reopen this issue. Redacting  gcode specifications does no good for anyone

**Comment by markaudacity** [comment]
Ridiculous that this still isn't provided, and that this issue was marked as closed when it hasn't been resolved, or even addressed. I opened a new issue about it.

@markus512 , please don't close issues because you flounced. It makes it harder for the problems to be addressed for everyone else.

**Comment by markus512** [comment]
Ok, you're right but I don't own a bambu anymore since I don't like this company which keeps everything closed.
