### ISSUE TITLE
Organic supports from PrusaSlicer (vs Tree supports in BambuStudio)

### ISSUE THREAD

**Issue by Gnof** [bambulab/BambuStudio#2420]
**Is your feature request related to a problem? Please describe.**
The current tree supports aren't as functional as the organic supports that are currently in Prusa slicer.

Specifically, tree supports often overlap with the model and cause scarring / artifacts on the printed model surface:
![Slicer 1](https://github.com/bambulab/BambuStudio/assets/1928442/b602ad98-8bc4-4289-bcbc-f5ed12a8888e)

**Describe the solution you'd like**
This issue does NOT occur on Prusa slicer with the same model with their implementation of tree supports (known as OrganicSupports in their source I believe? https://github.com/prusa3d/PrusaSlicer/blob/c05542590d7c2d73eb69bbf7a82a482a075815c1/src/libslic3r/Support/OrganicSupport.cpp)

Is it possible to port their supports implementation over to Bambu Studio?

**Describe alternatives you've considered**

The following settings have been tested to attempt to remediate the issue: 
(Tested with all tree Styles [Default, hybrid, strong, slim])
- "On build plate only" - turned ON (off puts the supports directly on the model, causing more issues)
- "Support critical regions only" - tested ON and OFF
- "Remove small overhangs" - tested ON and OFF
- "Top Z distance" - set to 0, as well as adjusted +
- "Support / object xy distance" - set to larger numbers (2-3 mm+ to test) this actually results in the following: 
![slice5](https://github.com/bambulab/BambuStudio/assets/1928442/09c556ff-d6b6-4f87-a383-513d9d74b479)

**Additional context**

I'd actually be happy to try and do this myself but I figured I'd put in a feature request in case it's either already on the roadmap or you guys have explored this and there's some reason it can't be done so simply (which would save me the time of trying to port the feature and finding out there's a deeper issue with it)

Thanks guys!

**Comment by Gnof** [comment]
Sharing this comparison of the PrusaSlicer Organic support on the same model
![slice6](https://github.com/bambulab/BambuStudio/assets/1928442/cb4df49e-d37c-4e28-8e53-382cf0b04cbb)

**Comment by Edzi11** [comment]
Would be nice to get an update on the support generation since they arent super good sometimes. I've had instances of support generating mid-air or in areas that had no need for support.

**Comment by Noisyfox** [comment]
https://github.com/SoftFever/OrcaSlicer/pull/1938
Maybe try the latest Action build here.

**Comment by Edzi11** [comment]
> [SoftFever/OrcaSlicer#1938](https://github.com/SoftFever/OrcaSlicer/pull/1938) Maybe try the latest Action build here.

Thanks will give this a try!
