### ISSUE TITLE
Multicolor printing AMS Slot 1 is not considered

### ISSUE THREAD

**Issue by Guenni1975** [bambulab/BambuStudio#2430]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

I have a multicolor print.
Slot 1 Black
Slot 2 White
Slot 3 Cyan

Model was colored manually.

First picture preview how it looks colored!
The black from slot 1 is not taken into account after slicing.
If I take the red from slot 4 it will be considered.

Preview
![vorschau](https://github.com/bambulab/BambuStudio/assets/6686691/c80d9623-0e0a-4c7a-a0bb-7e0737cfbe58)

Color Slot 1
![sliced](https://github.com/bambulab/BambuStudio/assets/6686691/31a896fd-8834-4e1e-af03-9c406408c38d)

Color Slot 2
![sliced2](https://github.com/bambulab/BambuStudio/assets/6686691/05d4cd87-17c2-47c4-966b-6e752f55cba8)

Apparently, the color in AMS slot 1 is currently not taken into account for multicolor printing!
The colors in other slots are considered!

### Actual results

The color in AMS Slot 1 is not taken into account in multicolor printing!

### Expected results

The color in AMS slot 1 would have to be taken into account!

### Project file & Debug log uploads

[beispiel.zip](https://github.com/bambulab/BambuStudio/files/12478621/beispiel.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Guenni1975** [comment]
I have checked it again, with another file the coloring in 3 colors also works with slot 1 without problems. So it seems to be related to the file. I just don't understand why it refuses to colorize only slot 1 with the file, but works with slot 4. In so far, the bug or what it is not so bad for now!

**Comment by Guenni1975** [comment]
The problem also occurs with four-color printing.  However, it cannot be bypassed there because all slots are used.  So it should be fixed soon.

**Comment by zhimin-zeng-bambulab** [comment]
we will fix it in 1.8 beta

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.08.00.57, you can have a try.
