### ISSUE TITLE
I would love the function that unlocks objects from the plate, I would like to create the base and the object separately, then from the slicer I would like to lift the object 1mm and place it under the base. at the moment I am using another slicer to use this function.

### ISSUE THREAD

**Issue by ErredueDidue** [bambulab/BambuStudio#2434]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SaltWei** [comment]
You can merge the base and the object together, then lift the object
