### ISSUE TITLE
System Presets

### ISSUE THREAD

**Issue by mcdavidr** [bambulab/BambuStudio#2435]
### Bambu Studio Version

1.7.452

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu P1S

### How to reproduce

![Screenshot 2023-08-31 163137](https://github.com/bambulab/BambuStudio/assets/141276249/66e84c52-702a-4fd1-9168-8fe8d8b777b9)
There as no presets for P1S, only X1C

### Actual results

Only presets for X1C

### Expected results

P1S presets?

### Project file & Debug log uploads

[example.zip](https://github.com/bambulab/BambuStudio/files/12491618/example.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by XunZhangBambu** [comment]
This preset is also applicable to P1S, so we did not create a separate  preset and name it xxx@P1S.

**Comment by weczi** [comment]
> This preset is also applicable to P1S, so we did not create a separate preset and name it xxx@P1S.

Thats preset dont works for me. every first layer ruined.
