### ISSUE TITLE
Fix the filament selector

### ISSUE THREAD

**Issue by beehphy** [bambulab/BambuStudio#2440]
![BadSelect](https://github.com/bambulab/BambuStudio/assets/4260318/70ca36cc-4d1b-4752-8c90-f7d94acae8b6)
 It is so frustrating to return to a half-print to find that the very last step of sending the job was ruined by the slicer choosing the wrong material just because the same COLOR was used in the picker. Silk, sparkles, translucent, fiber reinforced. there are so many reasons you might have similar colored materials, but NOT want to just interchange then all whillynilly!?! please don't decide something like this for me!

**Comment by beehphy** [comment]
Why do the colors in the slicer use numbers only? 
And not what the machine uses; alpha and numeric?
This is where you are creating the disconnect.

**Comment by QingZhangBambu** [comment]
@beehphy If there are cases of the same color, how about materials with the same ID in the user slicer have priority?

**Comment by beehphy** [comment]
that seems like the proper behavior: 
Do not change away from user selected filaments by default.

**Comment by bam-winterfell** [comment]
@beehphy We have made some modifications in the new version. Please check if the issue has been resolved.
