### ISSUE TITLE
Manual Calibration Bug

### ISSUE THREAD

**Issue by Shreeak** [bambulab/BambuStudio#2441]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Home 22H2

### Additional system information

Gerätename	DESKTOP-IUHF0GD
Prozessor	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
Installierter RAM	16,0 GB
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

### Printer

Bambu Lab P1P

### How to reproduce

Go to Calibration
Manual Calibration
0.4mm Nozzle
Textured Build Plate 
Polylite PETG 
Calibrate 

### Actual results

Printer will freeze
Print status on Bambu Studio is only showing N/A for every entry 

### Expected results

Print the Flow Calibration

### Project file & Debug log uploads

[debug_network_Sat_Sep_02_10_05_35.log](https://github.com/bambulab/BambuStudio/files/12503597/debug_network_Sat_Sep_02_10_05_35.log)
[debug_network_Sat_Sep_02_09_59_23.log](https://github.com/bambulab/BambuStudio/files/12503598/debug_network_Sat_Sep_02_09_59_23.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
This BUG has been fixed in V1.7.6,  you can have a try.
