### ISSUE TITLE
Screen goes white after slice

### ISSUE THREAD

**Issue by mroberts1408** [bambulab/BambuStudio#2444]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz Windows 10 22H2 Home

### Printer

Bambu P1S

### How to reproduce

Import file
click on slice plate

### Actual results

Once you slice, the screen goes white
![image](https://github.com/bambulab/BambuStudio/assets/143953252/08a60bde-9a44-4e3f-9148-c39e6f80269f)

### Expected results

It should show a preview

### Project file & Debug log uploads

[debug_Sun_Sep_03_11_37_21_17380.log.zip](https://github.com/bambulab/BambuStudio/files/12506494/debug_Sun_Sep_03_11_37_21_17380.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
could you provide your 3mf file, i tend to reproduce it.

**Comment by mroberts1408** [comment]
I got it figured out, graphics card hadn’t updated for some reason. I
updated the card and all the issues went away.

**Comment by QingZhangBambu** [comment]
@mroberts1408 OK. I‘m glad to know that.
