### ISSUE TITLE
Im Höhenbereich Modifikator in Deutsch fehlt das + Zeichen

### ISSUE THREAD

**Issue by Zamaris39** [bambulab/BambuStudio#2452]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

BambuLab P1P

### How to reproduce

1. Rechtsklick auf das Modell
2. Höhenbereich einstellen
3. + fehlt
![Höhenbereich-Fehler](https://github.com/bambulab/BambuStudio/assets/143993148/65177676-eeb4-4b4b-9552-e2a4fcbf22b3)

### Actual results

Es ist nur 1 Höhenbereich einstellbar.

### Expected results

Es sollen mehrere Höhenbereiche einstellbar sein.

### Project file & Debug log uploads

Das gilt für alle Modelle mit mehrfarbigen Höhenbereichen.
![Einzelspulen-Box-Etikett-V5](https://github.com/bambulab/BambuStudio/assets/143993148/6814afcf-a6a0-4b1a-8330-475f7ef3f76e)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/dfbaedea-6bae-4a85-825e-c1c79a9cc518)
you can click each height rang tool to set the range you wanted

**Comment by UVM24** [comment]
Habe das selbe Problem. Hast du eine Lösung gefunden? Pro Objekt sollten mehrere Einstellungen möglich sein. Im Web habe ich Bilder gefunden, in welchen das mehrfache Modifikation abbildet. Allerdings nur auf amerikanischen Seiten.
![more range in one layer](https://github.com/bambulab/BambuStudio/assets/151880785/8b82ba80-9840-4b83-b7e5-dff97b8a20e9)
