### ISSUE TITLE
AMS settings button doesn't show clearly in Japanese, macOS.

### ISSUE THREAD

**Issue by lilyharuna** [bambulab/BambuStudio#2457]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

macOS Sonoma 14.0

### Printer

Bambu Lab P1P + AMS

### How to reproduce

1. Install Bambu Studio in macOS.
2. Go to settings(command + ,) turn language to Japanese.
3. Connect AMS in P1P.
4. In the device tab, the 'Retry(再試行)' button will hidden and doesn't show clearly.

### Actual results

The right half of the retry(再試行) button is hidden and cannot be seen. (Also, the right half of the hint is hidden.)

### Expected results

All button is clearly shown.

### Project file & Debug log uploads

![スクリーンショット 2023-09-05 23 52 05](https://github.com/bambulab/BambuStudio/assets/85403524/7811693f-7377-4594-9dbd-c76a7e1da834)
![スクリーンショット 2023-09-05 23 52 05 2](https://github.com/bambulab/BambuStudio/assets/85403524/dc383e23-eed5-4770-93cc-1f00bd1a051e)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @lilyharuna 
we will optimize it

**Comment by walterwongbbl** [comment]
Hi. @lilyharuna 
Please download and use the latest Studio version

**Comment by walterwongbbl** [comment]
If you have any other issues, please create a new issue. The current conversation will be closed.
