### ISSUE TITLE
Calibration errors on Multicolor Filaments

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#2467]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1C and P1S

### How to reproduce

Filaments that have multiple colors within the same filament fail the automated calibration test.
![2023-09-06 (2)](https://github.com/bambulab/BambuStudio/assets/60475095/3be72297-601b-42ca-83be-ae49031738cb)

### Actual results

Calibration Fails.

### Expected results

Calibration should complete

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@randyre 
There is a probability that the printer may fail to calibrate. In this case, you can make several attempts: The calibration line is uneven, 2. The laser radar is blocked. Restart calibration printing to see if the problem still exists.

**Comment by randyre** [comment]
It fails every time on this multicolor filament and 90% of the time on silk filaments, I believe it's a color and reflectivity issue with the  LIDAR camera.

**Comment by xenon2008** [comment]
i also got this error on a normal Black ABS... 
Cleand the lens, restartet the printer ....

But it is the same :(

**Comment by zhimin-zeng-bambulab** [comment]
@randyre Has this issue been improved with the latest firmware version?

**Comment by zhimin-zeng-bambulab** [comment]
Printer calibration success rates have improved, you can update the firmware version to v1.6.6.0 and verify it.
