### ISSUE TITLE
工單號US230904203001

### ISSUE THREAD

**Issue by MizTW** [bambulab/BambuStudio#2473]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

win10 64

### Additional system information

2023-09-06 14:47:58尊敬的拓竹用戶：您好！請問您目前使用的是我們最新版的Studio切片軟件，此問題我們在最新版本中是已經解決的，這邊建議您重新安裝最新版 且 安裝時可以臨時關閉防火墻，以免相關插件被攔截導致使用異常。如果您確保使用的是最新版且重新安裝後仍無效，辛苦您將以下路徑的文件夾上傳至此工單，我這邊為您進一步分析一下的（也勞煩告知一下操作報錯時間，我為您定位一下位置）：C:\Users\用戶名\AppData\Roaming\BambuStudio\log

### Printer

p1s

### How to reproduce

流量校正

### Actual results

![擷取](https://github.com/bambulab/BambuStudio/assets/143287260/76a30510-c505-45dc-b6ce-e81f4a5d8d81)

### Expected results

NO~~~~~

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12543528/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in V1.7.7, you can have a try.
