### ISSUE TITLE
Crash when pressing Enter on height range modifier

### ISSUE THREAD

**Issue by edog1973** [bambulab/BambuStudio#2481]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 22.04

### Additional system information

n/a

### Printer

X1 Carbon

### How to reproduce

- Open a new project
- Insert a Bambu Cube object
- Add a Height Range Modifier
- Select the text box for the upper or lower range of the Height Range Modifier
- Type a number
- Press Enter 
- Application crashes, window closes with no error message,
![2023-09-07_15-29](https://github.com/bambulab/BambuStudio/assets/5891504/90dd0b98-088d-47fa-bb55-0ae5fa658f1c)

WORKAROUND: Instead of pressing Enter click on any other UI element.  The updated value is accepted and the applicaiton does not crash

### Actual results

Application crashes

### Expected results

Application should not crash

### Project file & Debug log uploads

Project File: Not needed.
Debug Log: [debug_Wed_Sep_06_17_05_26_46952.log.zip](https://github.com/bambulab/BambuStudio/files/12553860/debug_Wed_Sep_06_17_05_26_46952.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by xp-Yang** [comment]
We fixed the issue. you can use the height range modifier normally in the next release.

**Comment by LiZ-Li-BBL** [comment]
The issue has been fixed.
