### ISSUE TITLE
First Layer Inspection

### ISSUE THREAD

**Issue by joshuajach** [bambulab/BambuStudio#2492]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Device name	TouchStoneLT
Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Device ID	4390D4EA-3564-4BA2-B0B0-ECDBD3D24D66
Product ID	00342-20906-63667-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Printer

X1 Carbon

### How to reproduce

Happens on all my prints that have first layer inspection turned on. Much more noticeable when using multiple colors on the first layer.

### Actual results

At the end of the first layer the bed does not retract, and the print head drags along the part while oozing some filament.

### Expected results

Bed should retract to give clearance for the print head while traveling to the back.

### Project file & Debug log uploads

[RW Car Case V6.2 - Cover Tests.zip](https://github.com/bambulab/BambuStudio/files/12567640/RW.Car.Case.V6.2.-.Cover.Tests.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
The latest firmware has improved filament oozing (basically we wait a longer time for the nozzle to cool down before scanning). Please update the firmware. If the problem still persists, please share the video of the chamber camera.
