### ISSUE TITLE
Missing `* @BBL X1C 0.6 nozzle` filament profiles

### ISSUE THREAD

**Issue by bbbenji** [bambulab/BambuStudio#2495]
### Bambu Studio Version

≤1.7.4

### How to reproduce

1. Select Bambu Lab X1 Carbon 0.6 nozzle
2. Select Bambu PETG Basic
3. Edit the filament selected above

### Actual results

Bambu Studio selects `* PETG @BBL X1C 0.8 nozzle`

Filament profiles for the 0.6 nozzle are missing. It appears that when using the 0.6mm profile and, for example, PETG or PLA-CF, Bambu Studio selects the 0.8 filament profile.

See: https://github.com/bambulab/BambuStudio/tree/master/resources/profiles/BBL/filament

![image](https://github.com/bambulab/BambuStudio/assets/1678118/bb3af0ca-9c4c-4d38-8f20-17e705373f68)

### Expected results

Bambu Studio *should* select `* PETG @BBL X1C 0.6 nozzle`

**Comment by XunZhangBambu** [comment]
The params with 0.6 nozzle and 0.8 nozzle are the same,so we use the same profile

**Comment by bbbenji** [comment]
In this case, the profiles should be symlinked with the correct nozzle size in the name. The way it is now, causes confusion and uncertainty.

**Comment by GuzziRaz** [comment]
Yeah either that or the name should reflect it, eg `PETG @BBL X1C 0.6/0.8 nozzle`.

**Comment by GuzziRaz** [comment]
BTW isn't at least the max. volumetric flow higher with 0.8 nozzle? Or are we already heater power bound at 0.6?

**Comment by XunZhangBambu** [comment]
Thanks.We will consider the problem when adding profiles later . I prefer to give it a name reflects the shared nozzle. If we directly create a profile with the same params,it will result in profile redundancy
