### ISSUE TITLE
[bug ui / 01.00.10.05 / Win] slow scroll key search

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#25]
When the search button is clicked, the drop-down menu opens.
Scrolling is slow; the sidebar must be used to get to the bottom of the menu.
<img width="180" alt="Schermata 2022-07-18 alle 10 25 29" src="https://user-images.githubusercontent.com/4783556/179473002-917972f6-d9d5-4c1b-b76d-a814d4b8eb87.png">

**Comment by RobinWhitfield** [comment]
Scrolling speed down this list seems OK here. What input device are you using, and how many lines at a time is your computer set to scroll? The default on Windows I believe is 3, which is what mine is set to.

![image](https://user-images.githubusercontent.com/63362209/179478158-4d70a3b7-b640-4407-bfc4-04970ffd4dc6.png)

**Comment by MarcoPiazza83** [comment]
> La velocità di scorrimento verso il basso di questo elenco sembra OK qui. Quale dispositivo di input stai utilizzando e quante righe alla volta è impostato per lo scorrimento del tuo computer? L'impostazione predefinita su Windows credo sia 3, che è ciò su cui è impostato il mio.
> 
> ![Immagine](https://user-images.githubusercontent.com/63362209/179478158-4d70a3b7-b640-4407-bfc4-04970ffd4dc6.png)

3

<img width="367" alt="Schermata 2022-07-18 alle 11 09 44" src="https://user-images.githubusercontent.com/4783556/179479936-d9be1cac-9f05-4884-b71e-1508f7f9b3bd.png">

**Comment by YifanWuBambu** [comment]
Fixed in the latest version.
