### ISSUE TITLE
Auto Populate filament from AMS to slicer.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#250]
Every time I reload/restart the slicer, I have to tell the slicer that there are four slots and then have to pick each one to get them in the right order., It already knows what's there, but it's not automatically populated.  This will only get worse when we add even more AMS units, I would hate to do this for 16 slots every time that I start the slicer.

In the files I uploaded you will notice that the first one only shows a single slot after I start the slicer, the second shows all four slots after I tell the slicer there are four slots, but with random colors, and the third shows that I have to pick slots and the order for all four slots even though all four drop-down menus are correct filament and order as defined in the AMS.

![2022-09-10](https://user-images.githubusercontent.com/60475095/189511344-9b8030d6-fe5f-4434-8dc5-20650ece9ffa.png)
![2022-09-10 (1)](https://user-images.githubusercontent.com/60475095/189511356-8724d0c9-8655-4fcb-aa96-4cd0a9b8862f.png)
![2022-09-10 (2)](https://user-images.githubusercontent.com/60475095/189511359-928093c3-8fa9-45ff-b063-35ba6cd96495.png)

**Comment by YifanWuBambu** [comment]
Maybe we can add a button to read AMS slots and replace the the filament list by filaments in AMS.

**Comment by randyre** [comment]
Thanks. Enhancement label is good until AMS hub is available. If not added by then it should be upgraded.  Also woyld prefer auto population instead of a button, the slots are already read as proof in the pull down menus, not sure why it doesn't  just automatically populate. I don't see the reasoning behind it just sitting there with one slot and the wrong filament. Seems counter intuitive.

**Comment by YifanWuBambu** [comment]
@randyre 
In Bambu Studio, project filaments are independent with AMS spools.
We do this for the following reasons:
1. When loading an existing multi-material 3mf project, its filaments are likely to be different with the spools in the AMS. We want to keep the original filaments used by 3mf project.
2. You may create a project that uses more colors than your AMS slots, and schedule them to serveral plates.

**Comment by warpster** [comment]
So why not load the loaded into the AMS filaments if you are starting a new project? Sure if you load an existing one it should keep what was there but on startup it seems, since it is a new project it should populate.

**Comment by YifanWuBambu** [comment]
@warpster 
We added an button to auto-sync the AMS filaments to current project (especially useful for new project).

**Comment by randyre** [comment]
The newest (1.03.00.12) version has this button. Works great. Thanks.
