### ISSUE TITLE
Cannot start print from SD card through Bambu Studio

### ISSUE THREAD

**Issue by molovan** [bambulab/BambuStudio#2502]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1C

### How to reproduce

1. Computer located NOT on the same LAN as printer
2. In Bambu Studio, go to Device - SD Card - Model
3. Hoover over model and click on print
4. click on send. 

### Actual results

Error messages says: "failed to send print job, please try again". Error code "-4030"
![image](https://github.com/bambulab/BambuStudio/assets/17680184/45f73cab-1695-40ba-9de8-7ca404cbe18b)

### Expected results

job send through to printer

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @molovan 
This error indicates that the current network may not be smooth. Please check the status of the network for both the studio and the printer. You can ping the printer's IP address to see if there is significant packet loss or latency. You may need to adjust the positioning of the printer.

**Comment by walterwongbbl** [comment]
The issue will be closed. If you have any new issues, please create a new issue
