### ISSUE TITLE
Outer and Inner Wall Speeds Not Respected

### ISSUE THREAD

**Issue by jon-whit** [bambulab/BambuStudio#2513]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Big Sur 11.7.8

### Additional system information

<img width="253" alt="Screen Shot 2023-09-15 at 3 14 44 PM" src="https://github.com/bambulab/BambuStudio/assets/2899204/44ed927a-9f03-4e31-925f-6124626d374e">

### Printer

Bambu Lab X1C

### How to reproduce

1. Open a part
2. Change outer wall (or inner wall) speed to a low value (30 mm/s)
3. Slice the part
4. Look at the speed of the rendered slice preview

<img width="1172" alt="Screen Shot 2023-09-14 at 11 21 39 PM" src="https://github.com/bambulab/BambuStudio/assets/2899204/3c038e36-8de6-4044-8c09-4fcaeaf430b2">

No minimum print speed settings are forcing the 59mm/s speed that the slicer preview shows, so there isn't any reason why the slicer should be increasing the print speed erroneously.

### Actual results

The sliced part preview shows a speed much greater than the outer or inner wall setting.

### Expected results

The slice part preview should not be greater than the specified outer wall or inner wall setting.

### Project file & Debug log uploads

[Cube.3mf.zip](https://github.com/bambulab/BambuStudio/files/12623889/Cube.3mf.zip)

No log present after the slice.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by jon-whit** [comment]
Relates to https://github.com/bambulab/BambuStudio/issues/1916

**Comment by LiZ-Li-BBL** [comment]
Use the 3mf file you provided, speed value is normal. Could you provide the 3mf file and gcode file of which shown in your screenshot? Maybe you can check the specific value displayed at the bottom of the screen: 
![image](https://github.com/bambulab/BambuStudio/assets/120457312/0020780c-8870-42da-8344-44eb247601a1)

**Comment by LiZ-Li-BBL** [comment]
Hello,
I think the Options->Travel at the bottom of Speed Color Scheme is checked. If so, you should uncheck it and reslice, and you will get a preivew you expected. It's a bug now, we will fix it as soon as possible.

**Comment by LiZ-Li-BBL** [comment]
> Hello, I think the Options->Travel at the bottom of Speed Color Scheme is checked. If so, you should uncheck it and reslice, and you will get a preivew you expected. It's a bug now, we will fix it as soon as possible.

The problem has been fixed recently. Could you please use our latest verision to check if the issue still exists? 
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.03.89
