### ISSUE TITLE
Raft does not print on first layer with objects that use tree supports

### ISSUE THREAD

**Issue by Logan-Hellbusch** [bambulab/BambuStudio#2514]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

Create an object that uses both a raft and tree supports.

### Actual results

The first layer will not include the raft of any objects using tree supports.
![layer_1](https://github.com/bambulab/BambuStudio/assets/46609423/412a2073-f0e4-44fa-9658-bdbb505bf829)
The raft is then printed on the second layer, higher than the nozzle should be causing failures.
![layer_2](https://github.com/bambulab/BambuStudio/assets/46609423/667eb6ac-f0a2-4d6a-ae7c-a4fa5237f41f)

### Expected results

The raft should be printed for all objects on the first layer.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
Offical 1.8 has been released and this bug is fixed. Close this issue.
