### ISSUE TITLE
Bug on scale ! 

### ISSUE THREAD

**Issue by Witawat** [bambulab/BambuStudio#2526]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab github releases

### OS version

windows 11

### Additional system information

cpu : i9

### Printer

X1C Combo

### How to reproduce

Because the size of the X, Y, and Z axes cannot be adjusted, the work must be scaled only. But there are problems with the workpiece.

Normal 
![image](https://github.com/bambulab/BambuStudio/assets/4926369/43a092e7-b533-401f-9e1d-afc6f9a10ecb)

![image](https://github.com/bambulab/BambuStudio/assets/4926369/8c1c50d6-a0fe-4041-ad48-22cbd6926812)

![image](https://github.com/bambulab/BambuStudio/assets/4926369/e6225a4d-e8b6-4f82-8533-d1f37e650239)

![image](https://github.com/bambulab/BambuStudio/assets/4926369/20848ee6-a098-46ec-85cc-0138c158abac)

### Actual results

scale size 100.66%
![image](https://github.com/bambulab/BambuStudio/assets/4926369/145375fb-d048-41e9-9b55-8a109b0e81de)

![image](https://github.com/bambulab/BambuStudio/assets/4926369/a14aff4c-b2cb-4f51-b8e6-90aa873e38f9)

![image](https://github.com/bambulab/BambuStudio/assets/4926369/d5a41e5e-559d-4658-937d-361934471194)

### Expected results

Want an fw that can adjust the x y z distance or want to fix this problem?

### Project file & Debug log uploads

[New folder (2).zip](https://github.com/bambulab/BambuStudio/files/12644489/New.folder.2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@Witawat  Could you explain your problem in detail and the steps to reproduce it? (For example, what was your expected result, what was the actual result, and how did you encounter this problem?)

**Comment by Witawat** [comment]
> @Witawat Could you explain your problem in detail and the steps to reproduce it? (For example, what was your expected result, what was the actual result, and how did you encounter this problem?)

Problems caused by I can't adjust the size of the piece to fit.
From information from various sources, bambu does not enable commands to adjust estep x y z of the machine.
and recommend methods Scale the work size up To solve this problem

![IMG_20230915_093254](https://github.com/bambulab/BambuStudio/assets/4926369/de882a58-6ec2-414f-a6b6-e1b45d07dd8b)

But I encountered this problem with some files when the size was scaled up. Found a part that shouldn't have been there. with the workpiece as shown in the picture

I have tested with Slicer since prusa supper, no such problems, only Orca and bambu.

![image](https://github.com/bambulab/BambuStudio/assets/4926369/d4fc2bf2-6d90-4a75-a7e2-7fedd2b07a92)

make me insecure Will there be excess problems with other pieces after the workpiece is scaled?

**Comment by zhimin-zeng-bambulab** [comment]
Do you mean that after scaling the object, some redundant parts will appear? Could you have a try in V1.7.6 ?

**Comment by Witawat** [comment]
now i record screen

https://drive.google.com/file/d/1r89ThCDQjg0o-lQ9_2UnCrJBu_O2E-ff/view?usp=sharing

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/cf50880d-f4f6-4c70-b580-7c0f4a5f8375)
Do you mean that when Scale is 100.66%, a sharp corner area will appear on the top?

**Comment by Witawat** [comment]
> ![image](https://user-images.githubusercontent.com/120697589/270357320-cf50880d-f4f6-4c70-b580-7c0f4a5f8375.png) Do you mean that when Scale is 100.66%, a sharp corner area will appear on the top?

yes

**Comment by zhimin-zeng-bambulab** [comment]
Since the top surface of this model has a certain inclination angle, when scaling to a specific size, this situation will occur when the cutting plane of the slice passes through this bevel.
You can cut this model at a height of 15.74, and you will find that there is this triangular area on the top of the model.

![scale_bug](https://github.com/bambulab/BambuStudio/assets/120697589/21b127f6-e20f-49ae-b57d-b2289c9673fa)

**Comment by zhimin-zeng-bambulab** [comment]
This is not a BUG, ​​it is caused by the uneven top surface of the model.
