### ISSUE TITLE
Difference prusaSlicer

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#253]
I don't understand why the slicing algorithm is different.
As you can see in this model, it is not a setting problem for some parameters, but the different calculation of the slicing engine. 

<img width="2170" alt="Schermata 2022-09-08 alle 23 37 49" src="https://user-images.githubusercontent.com/4783556/189546625-3874432d-8569-410e-a030-f9f9477946be.png">

**Comment by RobinWhitfield** [comment]
> I don't understand why the slicing algorithm is different.
Because they're not the same slicer?

If you switch to the same infill type I presume there's no difference?

**Comment by MarcoPiazza83** [comment]
> > Non capisco perché l'algoritmo di affettatura sia diverso.
> 
> Perché non sono gli stessi affettatori?
> 
> Se passi allo stesso tipo di riempimento presumo che non ci sia differenza?

Left bambu studio, right prusaslicer.
No, look at how the geometry of the letters is created, completely different!

**Comment by RobinWhitfield** [comment]
I'm aware - they're not the same slicer, and they do things differently.

It does look like it might be a bug though - can you replicate the issue of these permiters going inside the model in a simpler model?

If you lower the precision in Bambu Studio, does the issue go away?

**Comment by SaltWei** [comment]
Could you share the model for us to check?

**Comment by SaltWei** [comment]
Could you share a 3mf for us to check and compare?

**Comment by SaltWei** [comment]
Close this ticket for no response for long time.
Please report issue ticket if have new issues.
Thank you very much for suggestions
