### ISSUE TITLE
Split parts with different colors of the same filament fail to carry over to the slicer - ie. the slicer just thinks they are all the same filament/color.

### ISSUE THREAD

**Issue by ianhill60** [bambulab/BambuStudio#2532]
### Bambu Studio Version

all versions since around 1.5.0.60

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Mac Ventura 13.5.1 and Windows 11 Pro 22H2

### Printer

Bambu Lab X1 Carbon

### How to reproduce

Export any .stl with multiple bodies, split the object to parts in Bambu Studio, change the filament type of some of the parts (I used two different colors of polycarbonate), they will appear fine in the prepare tab, press slice, navigate to the preview tab. 

### Actual results

The slicer preview fails to differentiate between unique filaments of different parts in the same object. Slices it as one continuous filament. 

### Expected results

The object should be split into regions corresponding to the different filament colors. 

### Project file & Debug log uploads

![Screenshot 2023-09-18 at 6 11 08 PM](https://github.com/bambulab/BambuStudio/assets/71084427/2d4fb23e-726e-4370-8dd6-f581684fc7d1)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@ianhill60  Could you share your 3mf file?

**Comment by ianhill60** [comment]
For sure. Please find attached. 
[InsertPrintSolid.3mf.zip](https://github.com/bambulab/BambuStudio/files/12920725/InsertPrintSolid.3mf.zip)

**Comment by zhimin-zeng-bambulab** [comment]
@ianhill60 
When different parts under the same object overlap each other, the overlapping part will take priority in using the lower part in the objectlist.

So, if you want to display other colors, you can drag the "3DPrintedAntEnclosure.STL_28" part to the front of the objet list. As shown below
![image](https://github.com/bambulab/BambuStudio/assets/120697589/3065070a-2eb0-430a-ae2e-c6d0ad8a2acf)

**Comment by ianhill60** [comment]
Incredibly helpful. Thanks a ton.
