### ISSUE TITLE
Add Aligned Rectilinear Infill (and rename Zig Zag to Rectilinear)

### ISSUE THREAD

**Issue by skysyk** [bambulab/BambuStudio#254]
Please add the Aligned Rectilinear infill option from PrusaSlicer that enables infill lines to be closely matched to each other throughout the sliced model.

This is a useful option for certain 100% infill applications such as printing solid transparent objects.

Also requesting Zig Zag be renamed Rectilinear for consistency, but this is a nitpick.

**Comment by RobinWhitfield** [comment]
I expected this request following the release of a certain transparent object video!

**Comment by SaltWei** [comment]
> Please add the Aligned Rectilinear infill option from PrusaSlicer that enables infill lines to be closely matched to each other throughout the sliced model.
> 
> This is a useful option for certain 100% infill applications such as printing solid transparent objects.
> 
> Also requesting Zig Zag be renamed Rectilinear for consistency, but this is a nitpick.

Done. Please wait for next release.
