### ISSUE TITLE
"Top interface layers"

### ISSUE THREAD

**Issue by DerrillWMS** [bambulab/BambuStudio#2549]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C

### How to reproduce

In Bambu Studio ...

1. Load object that requires support material; and ...
2. Set viewport angle such that both top and a side face can be viewed simultaneously (e.g., looking down at 45°); and ...
3. Set viewport to include area requiring support material; and ...
4. Set zoom close enough to view (detect) individual layers, and include base layer and bottom layer of object where support material is required; and ...
5. Select **Preview** > **Support** ...
      a) ... > **Enable Support** (select checkbox); and ...
      b) ... set > **Base pattern** .and. > **Base pattern spacing** .and. > **Pattern angle** .and. > **Interface pattern spacing** such that viewable difference between Base support material and Interface support material can clearly be distinguished once generated (sliced); and ...
       c) ... set > **Top interface layers** = **1**; and ...
6. Select **Slice plate** to generate all layers; and ...
7. Adjust vertical cutaway slider at right down to display base (1st) layer only; and ...
8. Increment slider upwards one layer at a time until 1st interface layer is displayed, and count total # of interface layers that are displayed until 1) **Top Z distance** layer(s) is(are) displayed, or 2) bottom (1st) layer of object is displayed (if no Z distance set).

### Actual results

Total # of interface layers counted is **2**.

### Expected results

Total # of interface layers counted should be **1**.

Bug: Total # of Interface layers actually created consistently = **Top interface layers** +1.

### Project file & Debug log uploads

(n/a)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
Please upload a picture and a 3mf file for diagnosis.
