### ISSUE TITLE
Make colour change gradual from dark to light (and back)

### ISSUE THREAD

**Issue by mctazman** [bambulab/BambuStudio#255]
When printing in 3 colours (or more), there of course a colour changing algoritm. In my corrent print it's: eSun Bone White (which is yellowish) -> eSun Firetruck Red -> BL White -> eSun Firetruck Red -> eSun Bone White (which is yellowish)

Admittedly, I've got my purhe levels way down, but this order makes sure that all parts have red in them. In this case the best order (based on my colour input on the AMS) should be:

BL White -> eSun Bone White -> eSun Firetruck Red -> eSun Bone White -> BL White

That order minimizes the colour bleed, as it goes from dark to lighter to light to lighter to dark.

**Comment by mctazman** [comment]
![Schermafbeelding 2022-09-12 om 12 30 39](https://user-images.githubusercontent.com/113347370/189632386-1402330a-1760-4210-a6d8-b0a099411665.png)

Here's the current print's colour settings. The White PLA's BambuLab, so that's RFID'd. The Red & Beige are manually set colours. So in this case the best order would be: Slot 1, 3, 2, 3, 1, etc.

**Comment by YifanWuBambu** [comment]
Thanks. That's a good idea.
We will add this optimization in the future release.

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.
