### ISSUE TITLE
"Send print job to" Dialogue Defaults To Incorrect AMS Filament Slots vs Project Settings For Support Interface

### ISSUE THREAD

**Issue by KHeidolph** [bambulab/BambuStudio#2555]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

MS Surface Book 3

### Printer

Bambu Lab X1 Carbon w/ AMS

### How to reproduce

1. Load White PETG into AMS 1 and 2.  Load Black PLA into AMS 3 and 4.
2. Create a project requiring supports.
3. Set project and supports to print from AMS 2 (PETG)
4. Set support interface to print from AMS 4 (PLA)
5. Click on print plate.

### Actual results

"Send print job to" dialogue box indicates AMS 2 (PETG) and AMS 3 (PLA) will be used. 

![Snag_3f1f87d](https://github.com/bambulab/BambuStudio/assets/13023924/fad5f2f6-cc5a-444a-8b3d-ae4278c6409f)

### Expected results

"Send print job to" dialogue box indicates AMS 2 (PETG) and AMS 4 (PLA) will be used. 

***Note that even though AMS 4 (PLA) was selected as the filament to use for support interface in the project configuration, the "Send print job to" dialogue box set it to AMS 3 (PLA).  The "Send print job to" dialogue should use the same filaments indicated in the project settings by default. 

### Project file & Debug log uploads

[Bambu Lab Support Ticket Submission_20230920_1.zip](https://github.com/bambulab/BambuStudio/files/12677549/Bambu.Lab.Support.Ticket.Submission_20230920_1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by bam-winterfell** [comment]
AMS matching will prioritize matching slots with consistent colors and materials. When the materials of the two slots in AMS are the same, the slot with the smaller serial number will be matched. If you want to use materials from another slot, please select it manually.
Wishing you a happy life

**Comment by bam-winterfell** [comment]
Hi. @KHeidolph 
AMS matching will prioritize matching slots with consistent colors and materials. When the materials of the two slots in AMS are the same, the slot with the smaller serial number will be matched. If you want to use materials from another slot, please select it manually.
Wishing you a happy life
