### ISSUE TITLE
no printers and profiles after updating to v1.7.6.91

### ISSUE THREAD

**Issue by 3DAixperts** [bambulab/BambuStudio#2568]
### Bambu Studio Version

1.7.6.91

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 22H2 Build 22621,2359

### Printer

X1C

### How to reproduce

Install the actual update

### Actual results

no printers and profiles are shown
same result when settings folder in AppData is removed

### Expected results

should show my printers and filament profiles

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12700123/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by xdigitalfoto** [comment]
hello, I have the same thing, I only have the default printer and I can't see X1C, nor my profiles for filaments, which I had tried and set to my liking. During one PS resrart, it was possible to display the X1C after the next start without a restart, the default printer again. Every time Bambu Studio starts, it wants to start the setup as if it had never been started. It means that I don't print... the default printer certainly doesn't know the XC1 Gcode settings for start

**Comment by eXenInfo** [comment]
Same Problem with me.
Windows 10 
Bambu P1P with AMS
Uninstall this version and install the 1.7.4.52 the issue is not present.

**Comment by Pecetero** [comment]
El mismo problema.
He tenido que volver a instalar la versión anterior

**Comment by mlp3d** [comment]
Same error after update 1.7.6.91. No profiles loaded. Even after new login and klick on load Profiles from BambuStudio.

**Comment by BambuFri** [comment]
Bei mir auch der Fehler nach Update 1.7.6.91.
Hoffe, das wird bald gelöst...

**Comment by christianpfitzner** [comment]
Same issue with Windows 11: Each time I boot up, Bambu Studio asks for complete setup; afterward, my X1C is not recognized.

**Comment by xXemix** [comment]
Same here in Windows 11, not show profiles and my X1C not recognized, imposible sync with them.

**Comment by davidaberg** [comment]
Same for P1P on MacOS

**Comment by Lerk90** [comment]
I think the problem is the language, try English.

**Comment by BambuFri** [comment]
Ich habe die Sprache geändert und dann neu gestartet und nochmals die Sprache auf meine richtige eingestellt. Keine Ahnung warum, aber es funktioniert... :-)

I changed the language and then restarted and set the language again to my correct one. I don't know why, but it works... :-)

**Comment by Lerk90** [comment]
> Ich habe die Sprache geändert und dann neu gestartet und nochmals die Sprache auf meine richtige eingestellt. Keine Ahnung warum, aber es funktioniert... :-)
> 
> I changed the language and then restarted and set the language again to my correct one. I don't know why, but it works... :-)

but if you restart again with your language, fail again.

**Comment by BambuFri** [comment]
Yes, I just noticed that too :-(

**Comment by nargos** [comment]
gleiches Problem!

**Comment by 12ackcasa** [comment]
Hello, effectivement un changement de langue en anglais et ensuite la langue de base, ça marche !

**Comment by christianpfitzner** [comment]
> Same issue with Windows 11: Each time I boot up, Bambu Studio asks for complete setup; afterward, my X1C is not recognized.

My issue is also solved by changing from German to English.

**Comment by xdigitalfoto** [comment]
the official site no longer offers the new version, but I am exhibiting the Bambu_Studio_win-v01.07.04.52.exe version, error will be bigger than it seems

**Comment by lanewei120** [comment]
we have solved this issue on v1.7.6.92
please have a try
