### ISSUE TITLE
With update to 1.7.6.91 every time welcome screen and no calibration possible

### ISSUE THREAD

**Issue by Obicom** [bambulab/BambuStudio#2569]
### Bambu Studio Version

v1.7.6.91

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. Install new version 1.7.6.91
2. Start Bambu Studio
3. Goto Calibration

### Actual results

- After installing the new release 1.7.6.91 it starts with a welcome screen and base setup. This welcome screen appears every time when I start the new version. 
- Flow calibration shows all filaments as "incompatible". 
- Print plate preview (print plate) is to bright in dark GUI mode. Not really good visible print plate

### Expected results

1. No welcome screen and use the already existing settings
2. Flow calibartion should show the right filaments (not "incompatible)
3. Print plate should have more contrast in dark GUI mode

### Project file & Debug log uploads

no log or project file is needed to reproduce the problem. Did the installation on two different computers with the same outcome.
<img width="1040" alt="Screenshot 2023-09-22 140821" src="https://github.com/bambulab/BambuStudio/assets/25134482/58d0d1de-aea9-4d51-b65e-5b587dea745d">
<img width="872" alt="Screenshot 2023-09-22 140910" src="https://github.com/bambulab/BambuStudio/assets/25134482/c84dbd49-3394-4f45-983e-f12052085b10">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ImYourFather187** [comment]
same problem

**Comment by lanewei120** [comment]
hello @Obicom 
it seems a problem caused by config file loading fail under some language
we have released v1.7.6.92 to solve this issue,

could you have a try for v1.7.6.92?

**Comment by Obicom** [comment]
> hello @Obicom it seems a problem caused by config file loading fail under some language we have released v1.7.6.92 to solve this issue,
> 
> could you have a try for v1.7.6.92?

1.7.6.92 solved my issue.
