### ISSUE TITLE
Bambu Studio crashes upon slicing

### ISSUE THREAD

**Issue by jangledjamie** [bambulab/BambuStudio#257]
Went from V 2.0 back to V01.01.01.01 
Added a new material to the AMS.
Upon trying to slice any .stl and .3mf file Bambu Studio chrashes.
The bug is repeatable. 
[bs_crashreport.txt](https://github.com/bambulab/BambuStudio/files/9549766/bs_crashreport.txt)

**Comment by YifanWuBambu** [comment]
Fixed in v1.2.0.9.
