### ISSUE TITLE
Bambu Studio Calibration does not see the AMS in the english version

### ISSUE THREAD

**Issue by toml899** [bambulab/BambuStudio#2572]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

X1 Carbon

### How to reproduce

Calibration > Flow Dynamics OR Flow Rate > Manual OR Auto-Calibration

AMS filaments are not detected

### Actual results

AMS filaments are not detected

### Expected results

AMS filaments should be detected

### Project file & Debug log uploads

[debug_Fri_Sep_22_12_29_54_3408.log.0.zip](https://github.com/bambulab/BambuStudio/files/12702940/debug_Fri_Sep_22_12_29_54_3408.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@toml899  Could you use a picture to express your problem?

**Comment by toml899** [comment]
Hi, here are two pictures.  1 - is what the AMS has.  2 - Is what Bambu studio has.

Please help me fix.  Grand children are most upset!
![screen 1](https://github.com/bambulab/BambuStudio/assets/59496550/7c5b0f62-8e90-43de-b23f-2c04b5664cdb)
![screen 2](https://github.com/bambulab/BambuStudio/assets/59496550/26f20c24-8c22-4916-934d-da720b1a698f)

**Comment by toml899** [comment]
This worked fine until about a week ago.

**Comment by zhimin-zeng-bambulab** [comment]
@toml899 
From the picture, you are using external material to print. When you use external material, only the external material will be displayed, and AMS will not be displayed. In addition, you need to set the material type of the external material on the device page before you can select and set it on the calibration page.

**Comment by zhimin-zeng-bambulab** [comment]
If you want to use AMS materials for calibration, you can first unload the external material and then use AMS materials for calibration.

**Comment by toml899** [comment]
Thanks.  That fixed the issue
