### ISSUE TITLE
Device tab video width not scaling with window

### ISSUE THREAD

**Issue by LJKraus** [bambulab/BambuStudio#2574]
### Bambu Studio Version

1.7.6.92  

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

WIndows 11 Pro 22H2  build 22621.2283

### Additional system information

32Gb memory, Nvidia GTX1070 8Gb video memory, 4k screen, normal 100% scaling

I found the same behavior using a different PC: Windows 10 Pro, 4Gb RAM, 1920x1080 screen, 100% scaling

### Printer

Bambu Lab X1C

### How to reproduce

Open Studio in a window, switch to Device tab, video monitor area appears with printer controls on the right.
![image](https://github.com/bambulab/BambuStudio/assets/139707784/f99fa41d-63c5-4d62-a165-005bd33b2b6e)

Resize the program window in any amount, in any direction, larger or smaller.

### Actual results
![image](https://github.com/bambulab/BambuStudio/assets/139707784/9f9305d9-af20-4638-acd7-63010ee6116b)
Resize the window by even a pixel or two and the monitor area expands to ~1610 pixels in width, and cannot be narrowed.   No further resizing of the program window will reduce the new width of the video monitor area. 

The only way I've found to restore a properly proportioned video monitor is to restart Studio.  

If the program window is resized _before_ opening the Device tab, the width of the video monitor will adjust as expected.

If Studio was full screen when last shut down, and therefore opens full screen, it can be windowed and resizing the window from the Device tab works as expected.  If Studio  opens windowed and is then resized while on the Device tab, the error occurs.

The issue existed in previous versions of Studio, but I had not taken the time to rule out possible causes in my system (scaling, 4K resolution).  

### Expected results

Video monitor area should resize proportionally with the program window.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12704743/log.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LJKraus** [comment]
Forgot to paste "Actual" example:
![image](https://github.com/bambulab/BambuStudio/assets/139707784/dec3bffa-e7fa-45db-b7f8-53823323b651)

**Comment by bam-winterfell** [comment]
Hi.@LJKraus
This issue will be resolved when the next version is released. Please update it in a timely manner and your issue will be easily resolved.Before that, you can try to use a shorter file name.
Wishing you a happy life

**Comment by bam-winterfell** [comment]
@LJKraus The new version has been released on the release page and has fixed this issue. You can have a try.
