### ISSUE TITLE
[BUG] Maximised window is oversized on multi-monitor system

### ISSUE THREAD

**Issue by CamboG** [bambulab/BambuStudio#259]
On a multi-monitor Windows system when Bambu Studio (1.1.1.1) is maximised rather than filling just a single screen a few pixels of the window expand onto the screen to the left.  This has the secondary effect of opening the File menu on the left screen.

![Dual Screen Max Bug](https://user-images.githubusercontent.com/30010309/189707849-0959a02b-3cb1-4bb0-b0d9-0386cf154c2c.png)

**Comment by SaltWei** [comment]
Could you check this again on version 1.5.0 Public beta， https://github.com/bambulab/BambuStudio/releases/tag/v01.05.00.59

Should be included in this version
