### ISSUE TITLE
Show Black Filament as Dark Gray

### ISSUE THREAD

**Issue by aherta** [bambulab/BambuStudio#2591]
**Is your feature request related to a problem? Please describe.**
It's difficult to see the features of a model when using black filament because it's just solid black.

**Describe the solution you'd like**
Making black a dark gray that allows some definition to be seen would be great.

**Describe alternatives you've considered**
Printing in other colors works much better, but I use a lot of black.

**Additional context**
![image](https://github.com/bambulab/BambuStudio/assets/10685908/ac564f08-23c1-4c7c-b25c-fd7386c903d3)

**Comment by QingZhangBambu** [comment]
#2603

**Comment by Haidiye00** [comment]
Thank you. We have fixed this issue in the upcoming V1.8 version. Stay tuned

**Comment by JakeAi** [comment]
Thank god. Came here to post this same issue.
