### ISSUE TITLE
Auto Refill dialog is not resizable and text is truncated

### ISSUE THREAD

**Issue by gsingh93** [bambulab/BambuStudio#2594]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13.5

### Printer

Bambu Lab P1S

### How to reproduce

1. Go to the device page
2. Click on "Auto Refill" by the AMS settings
3. A non-resizable dialog with the text cutoff is shown

### Actual results

<img width="444" alt="image" src="https://github.com/bambulab/BambuStudio/assets/1012677/9a61c196-bc79-43d4-abaa-d513ee8dc916">

### Expected results

I should be able to read all the text, I'm not sure what this message is trying to say about which spools are compatible.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @gsingh93 
I'm very sorry, we will work on optimizing it.

**Comment by bam-winterfell** [comment]
The optimization has been completed and will be released in the next version. Please update promptly. Wishing you a happy life.
