### ISSUE TITLE
[bug ui / 01.00.10.05 / Win] View all object's setting 

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#26]
the graphic setting of this screen is not optimized.
Long names are cut off, the box is not self-adaptive.
Sometimes it takes one click, sometimes two to select rows.

<img width="1025" alt="Schermata 2022-07-18 alle 10 39 37" src="https://user-images.githubusercontent.com/4783556/179475677-70c5a873-d4d7-4e65-9dea-5e69bd96fe6f.png">

**Comment by IBH7493** [comment]
Very nice work

**Comment by MarcoPiazza83** [comment]
Imac 27", parallels desktop, win 10

<img width="367" alt="Schermata 2022-07-18 alle 11 17 21" src="https://user-images.githubusercontent.com/4783556/179481322-e1d78ee1-4fd5-46d5-a516-2add72b96275.png">



> What resolution and scaling are you using? I suspect this is related to #24
> 
> On 1080p, 100% scaling it looks OK, ![image](https://user-images.githubusercontent.com/63362209/179478598-354561ff-c58b-4e1b-98de-1869b2d38a46.png)
> 
> It _does_ however let you resize the window which isn't very helpful (it doesn't give you a scroll bar) ![image](https://user-images.githubusercontent.com/63362209/179478800-ea91ae09-a1a9-4b4a-a4ab-71be7d479f3c.png)
> 
> And then when you close and re-open it it breaks in weird and wonderful ways ![image](https://user-images.githubusercontent.com/63362209/179479140-46e4b8cf-2b62-4b38-8a17-39f8410ac4a1.png)
> 
> No, you cannot resize that left hand side section, but at least you get a scroll bar at the bottom now! Thankfully this does not persist with a software restart.

**Comment by RobinWhitfield** [comment]
I opened #30 for the related issue that I found, for better visibility, as it's clearly a different issue.

**Comment by wuyifanfancy** [comment]
The part list/settings panel has not been fully developed yet. We will consider your suggestions in the subsequent development process.

**Comment by lanewei120** [comment]
the object table has been released formally in v1.2.0
please have a try and verify

**Comment by RobinWhitfield** [comment]
@MarcoPiazza83, as #24 has been closed, is this one also resolved for you now?

**Comment by YifanWuBambu** [comment]
@MarcoPiazza83 
We close it for now. Please create another issue if you still have this problem.
