### ISSUE TITLE
Black color is accurate but not usefully rendered in Bambu Studio

### ISSUE THREAD

**Issue by sprior** [bambulab/BambuStudio#2603]
![Screenshot 2023-09-24 204247](https://github.com/bambulab/BambuStudio/assets/3361800/b4b07a0e-8c2c-4337-aadf-2c387e5e22ee)

**Is your feature request related to a problem? Please describe.**
While I appreciate that when I configure a black filament in Bambu Studio that you'd like to render it as accurately as possible it comes out almost featureless on the screen and very difficult to see or work with.  I know I can configure any color I want in Bambu Studio itself, but I think a very common usecase is to load filament in the AMS, select black on the printer then sync those colors to Bambu Studio and the screenshot shows how that comes out.

**Describe the solution you'd like**
I think rendering black as a dark grey might be easier to actually work with.

**Describe alternatives you've considered**
Maybe a config switch to adjust colors to show detail (maybe call it HDR mode?) might be a good option.

**Comment by QingZhangBambu** [comment]
we will fix it soon.

**Comment by Haidiye00** [comment]
Thank you. We have fixed this issue in the upcoming V1.8 version. Stay tuned

**Comment by Haidiye00** [comment]
The issue has been fixed, please use the latest version V1.8
