### ISSUE TITLE
Bambustudio failed to connect to the server

### ISSUE THREAD

**Issue by ramujica493** [bambulab/BambuStudio#2604]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Additional system information

Device name	DESKTOP-GCPJ12F
Processor	AMD Ryzen 9 5950X 16-Core Processor               3.40 GHz
Installed RAM	32,0 GB
Device ID	F6069F7E-61DF-45EF-B269-28C64D71CFF9
Product ID	00330-52294-06386-AAOEM
System type	64-bit operating system, x64-based processor

### Printer

P1S

### How to reproduce

open the program
go to device
in the left side says failed to connect to the server

### Actual results

![Screenshot 2023-09-25 041250](https://github.com/bambulab/BambuStudio/assets/145387404/bf1e211d-1aa1-43a6-a7e4-29c58cba921c)

### Expected results

i expected that i can print with the cloud service

### Project file & Debug log uploads

[debug_network_Mon_Sep_25_04_23_07.log](https://github.com/bambulab/BambuStudio/files/12710546/debug_network_Mon_Sep_25_04_23_07.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @ramujica493 
It seems there are some issues accessing our server. Please check if your network is stable and try visiting the following URL.
https://status.bambulab.com/
