### ISSUE TITLE
Issue in "x-y compensation"

### ISSUE THREAD

**Issue by MartinM8266** [bambulab/BambuStudio#2610]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

Windows10

### Printer

BambuLab X1C 01.06.05.01

### How to reproduce

When applying x-y compensation to a hollow geometry (cylinder or hollow cuboid) with a hole in the wall, the slicer will not apply the compensation to the layers that include the hole.

![Screenshot 2023-09-25 230610_nocomp](https://github.com/bambulab/BambuStudio/assets/76632224/e696671f-3444-4300-8a1a-d67ee2e30e82)
![Screenshot 2023-09-25 230540](https://github.com/bambulab/BambuStudio/assets/76632224/7aca7637-869e-460b-bcf8-dd3d4c62929e)
![Screenshot 2023-09-25 230442](https://github.com/bambulab/BambuStudio/assets/76632224/0a4dc35c-a70a-42fb-aeb4-72c3fd4104ba)
![2023-09-25 22 48 48](https://github.com/bambulab/BambuStudio/assets/76632224/fe50194c-4845-4d75-ae0a-a327fa4894f8)

### Actual results

![2023-09-25 22 48 48](https://github.com/bambulab/BambuStudio/assets/76632224/f842b17c-95eb-40f1-9721-dee04bd06219)

### Expected results

the c-y compensation should effect on the whole wall.

### Project file & Debug log uploads

[adapter_1.zip](https://github.com/bambulab/BambuStudio/files/12719384/adapter_1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/7265100d-5095-4d71-baab-e8774004d6fe)

**Comment by MartinM8266** [comment]
thanks for explaining and sorry for late reply!
