### ISSUE TITLE
tree manual support problem

### ISSUE THREAD

**Issue by riccalisci** [bambulab/BambuStudio#2614]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

in manual tree support , slicing is incorrect.

### Actual results

there aren't no supports where it should be.
![Immagine 2023-09-26 093554](https://github.com/bambulab/BambuStudio/assets/78355311/35f7d425-5792-467c-b27d-325136eeab03)

### Expected results

correct support

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12724560/log.zip)
[block.zip](https://github.com/bambulab/BambuStudio/files/12724561/block.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by tangketan** [comment]
Thanks for reporting the issue. We'll fix it in the next version.

**Comment by tangketan** [comment]
Offical 1.8 has been released. Close this issue.
