### ISSUE TITLE
0/no-purge value

### ISSUE THREAD

**Issue by mctazman** [bambulab/BambuStudio#2615]
**Describe the solution you'd like**
When printing multi-colour prints, BS creates quite some waste due to purging. In certain cases, the colour switch doesn't need to be perfect, hence no purging needed. However, currently BS won't allow a value lower than 107. A "no-purge" feature, or 0-value, would be appreciated for these cases.

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/3590cfad-f2a3-42d0-9cc9-4fbbe3f1f685)
it just a warning, you can still use 0 purge

**Comment by mctazman** [comment]
Ah, cool. Thanks. The greyed out "OK" button threw me for a loop.
