### ISSUE TITLE
[FEATURE REQUEST] Edit Text after placement

### ISSUE THREAD

**Issue by rzucco** [bambulab/BambuStudio#262]
The new **add-text** feature is fantastic. However, there is no way to edit the text after you place it on the model.
Changing the characters would be a great time saver, as we could save it as a template instead of having to recreate it every time.

**Comment by GuyH77** [comment]
2nd this. I came to add it myself but pleased someone else sees the value.

**Comment by Manfredo1952** [comment]
Agree.  It is akward to remove and add the new text. Should be able to edit the initial insertion.- Thanks guys

**Comment by mkosmo** [comment]
I'd like to voice my support for this feature request.

**Comment by lemoanth** [comment]
I support the ability to edit text in the slicer

**Comment by managerman** [comment]
Please add this feature!!  Thanks.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/222378752-38996e7a-108f-4a5b-aa34-e26d4299f759.png)
Already available on v1.5.0 public beta.
But please attention that it's can't be edited after save and resave from 3MF again. This is hard to be supported.

**Comment by mkosmo** [comment]
I'd like to voice the opinion that I don't think this is actually resolved until it's editable after save.  This implementation is a stopgap rather than a solution.  I fully understand that you're operating within the confines of the 3MF spec, but there's surely a way to save the same metadata for later reuse after re-open.

**Comment by SaltWei** [comment]
> But please attention that it's can't be edited after save and resave from 3MF again

@zhimin-zeng-bambulab Is this possible to be supported with limited resources?

**Comment by kvnper** [comment]
Firstly, thank you for implementing this!

Secondly, I think that being able to edit after save would be very beneficial! For example, I make name tag keyrings and being able to save the project as a 3mf file and then come back to it later and change the name, would save me a lot of time customising the name if I could simply change the text.

**Comment by sky-andrefaria** [comment]
I'll second @kvnper on this.

Opening up the project and edit the text is a huge time saver! And maybe avoid some manual mistakes on the way.

**Comment by ysu2** [comment]
Another issue here is that the saved object does not carry any information as far as I can tell.
I cannot tell what font face & size was used to generate a text, so...

Yeah.  It would be a very-very well regarded piece of function if it was done. :)
