### ISSUE TITLE
Missing elephant's foot compensation for most Bambu profiles

### ISSUE THREAD

**Issue by belak** [bambulab/BambuStudio#2621]
**Is your feature request related to a problem? Please describe.**
When I swapped to a 0.6mm nozzle a few weeks ago, I started noticing elephant's foot. Originally I thought it was something I did, but looking at the profile, the 0.4mm P1S profile has elephant's foot compensation set to 0.15mm, while the 0.6mm P1S profile has it set to 0.

**Describe the solution you'd like**
Add elephant's foot compensation for other nozzles on Bambu Lab printers.

**Describe alternatives you've considered**
I can definitely set this up in a personal profile, but it seems like it would be useful for everyone.

**Comment by belak** [comment]
I haven't tried too many values yet, but 0.15mm, the default used with the 0.4mm nozzle seems to work well.

**Comment by QingZhangBambu** [comment]
OK, we will test it, and add it later.

**Comment by lukcz** [comment]
Any update here? Seems like everyone would benefit having some default values. Moreover it is missing not only for 0.6mm profil, but for 0.2mm and 0.8mm as well.

**Comment by QingZhangBambu** [comment]
@XunZhangBambu please add it later

**Comment by TinyMito** [comment]
Tested the differences between Default 0.00 and edited 0.15. :)

![20240104_001619](https://github.com/bambulab/BambuStudio/assets/75095713/0a3f31e9-3b3f-4714-9e5f-1d98069ea0fc)
![20240104_001620](https://github.com/bambulab/BambuStudio/assets/75095713/0e9197df-46df-46a2-a1bd-269cef21b7ee)

**Comment by XunZhangBambu** [comment]
@TinyMito  Thanks. You will see it in next version

**Comment by TinyMito** [comment]
@XunZhangBambu I got the latest update 1.8.4.51. I notice all the normal A1 has all the elephant foot added 0.075mm parameters. But for the A1M (A1 mini) profiles are all missing elephant foot.

https://github.com/bambulab/BambuStudio/commit/88e04386387adba709a9ef97d93e7c22f1205ae9

Is this intended for the A1M don't need elephant foot? It's the same extruder head as normal A1?

**Comment by XunZhangBambu** [comment]
@TinyMito  Yes,after testing, no significant elephant foot was observed in the A1 mini. For  A1, the elephant foot is also slightly smaller compared to the X series and P series

**Comment by tristan11232021-design** [comment]
Still a problem. No default elephant for compensation on my A1 mini AND A2L there is no print that doesn't require some elephant foot compensation but you have it set to ZERO. 

Or you brought the problem back with a bad update that ruins everything we try to fix on our own. Just give us the ability to update defaults that can't be over written by poorly executed updates. 

<img width="3000" height="4000" alt="Image" src="https://github.com/user-attachments/assets/c169e45f-604e-483d-af80-862645437d5e" />

**Comment by tristan11232021-design** [comment]
I have never seen a single complaint about "too much" compensation for elephant foot but hundreds of people complaining about all A series printers complaining about the fact that they are set to zero.
