### ISSUE TITLE
Support Cubic infill is generated 2x normal density

### ISSUE THREAD

**Issue by tsmith35** [bambulab/BambuStudio#2627]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

CPU: 13900K
GPU: RTX 4080
RAM: 64 GB

### Printer

Bambu Lab X1C, P1P

### How to reproduce

Create an object with infill. Select "support cubic" for infill type. Slice object and view preview.

### Actual results

Infill generates at 2x the expected density. For example, 20% support cubic infill generates at 40% fill.

### Expected results

Infill should be generated at the expected 20% density. To work around issue, set fill to 1/2 the expected density. i.e., select 10% infill with support cubic to generate the expected 20% density. Only support cubic appears to be affected.

This issue affects both OrcaSlicer and Bambu Studio. Tested against PrusaSlicer 2.6.1 and Cura 5.4.0

Project file & Debug log uploads

### Project file & Debug log uploads

![Wrong Support Cubic Infill](https://github.com/bambulab/BambuStudio/assets/7685333/0c002854-dfde-4c92-b44e-5d344e502020)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
could you provide 3mf file?

**Comment by tsmith35** [comment]
Sure!
[Infill Examples (adaptive & support).zip](https://github.com/bambulab/BambuStudio/files/12745426/Infill.Examples.adaptive.support.zip)

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/ad6f97d5-e277-4a13-9934-5c3b962cc6d4)
i try it, adaptive cubic and support cubic excatly same. what's your steps? i tend to reproduce it.

**Comment by tsmith35** [comment]
> !i try it, adaptive cubic and support cubic excatly same. what's your steps? i tend to reproduce it.

You just did. The support cubic should appear to be twice the scale, but it's not. Support cubic is just like adaptive cubic but is exactly half as dense.

**Comment by QingZhangBambu** [comment]
ok , i will check it

**Comment by QingZhangBambu** [comment]
the density of the support cubic infill relates to the distance to the top. if the height increases, the support cubic density is smaller than the adaptive cubic.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/f1e1aab0-671b-49d5-8cdb-88f2a4e7d483)

**Comment by QingZhangBambu** [comment]
Closed due to no reply
