### ISSUE TITLE
Incorrect wording after load filament selected

### ISSUE THREAD

**Issue by itsonlymedan** [bambulab/BambuStudio#2636]
### Bambu Studio Version

1.7

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

P1 Series

### How to reproduce

After the load filament button is selected and the printer begins the process. 

### Actual results

The Printer asks if the user is Done or if they need to retry. This is correct. 

The Slicer asks if it is Done or Confirm 

### Expected results

The Slicer should ask Done or Retry

### Project file & Debug log uploads

```        if (it_done != message_containing_done.end()) {
            m_print_error_dlg->update_func_btn(_L("Done"));
            m_print_error_dlg->update_title_style(_L("Warning"), SecondaryCheckDialog::ButtonStyle::CONFIRM_AND_FUNC, this);
        }
        else if (it_retry != message_containing_retry.end()) {
            m_print_error_dlg->update_title_style(_L("Warning"), SecondaryCheckDialog::ButtonStyle::CONFIRM_AND_RETRY, this);
        }else {
            m_print_error_dlg->update_title_style(_L("Warning"), SecondaryCheckDialog::ButtonStyle::ONLY_CONFIRM, this);
        }```

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by xperiments** [comment]
Actually the problem is located in the json you are providing at https://e.bambulab.com/query.php?lang=en.
We have only checked EN but may be affecting others also.
The affected data is in device_error "ecode":"07FF8007"

**Comment by fdebeer** [comment]
2nd this. also translation in dutch language is wrong

**Comment by cwr5033** [comment]
New user, this was VERY confusing at first to understand "confirm" means "retry".

**Comment by bam-winterfell** [comment]
The new version has resolved this issue, please update it promptly. Thank you for your feedback. Wishing you a pleasant life
