### ISSUE TITLE
Switching from A1 mini printer to X1 does not correctly place objects when using multiple print plates

### ISSUE THREAD

**Issue by kadrim** [bambulab/BambuStudio#2645]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1 series

### How to reproduce

1. Visit https://makerworld.com/en/models/14265#profileId-14275
2. Open in Bambu Studio
3. The project will be opened in bambu studio with the A1 mini print profile
4. switch to a bigger printer i.e. X1

### Actual results

Opening a file that has been prepared for the A1 mini (with a slightly smaller print area) and with multiple plates involved will not correctly place the objects when switching to a bigger printer like the X1.

The objects will always be placed according to their global coordinates instead of the relative plate coordinates

Screenshot 1 - Opening the file (A1 mini profile):
![image](https://github.com/bambulab/BambuStudio/assets/8304331/2d9895fc-55c0-4885-bd81-b71138db7115)

Screenshot 2 - Switchted to a bigger printer (X1 profile):
![image](https://github.com/bambulab/BambuStudio/assets/8304331/ba63dfb9-add6-471a-a281-5ab9bfa04437)

### Expected results

switching from a smaller printer to a bigger printer with multiple plates involved should place all objects correctly on the bigger print plates

**Comment by lanewei120** [comment]
thanks for this advice, this is reasonbale

we will improve it

**Comment by StoneLiBambulab** [comment]
Hi @kadrim 

it will be added in release 1.8

Thanks!

Stone Li

**Comment by SaltWei** [comment]
Already included 1.8.2 version on github and official website
