### ISSUE TITLE
Excessive bed leveling

### ISSUE THREAD

**Issue by GuzziRaz** [bambulab/BambuStudio#2648]
When flow calibrating many filaments, you really grow tired of the full bed levelling performed each time for no reason. If I didn’t select a different build plate and it did a full mesh 10 minutes ago, why do it again? It should be optional 

See also #2465

**Comment by UnglazedSquash** [comment]
The method they are using to implement bed leveling requires them to do it each time. Just the name of the game. Plus it is the safest option.

**Comment by GuzziRaz** [comment]
Are you saying this somehow can’t be improved on?

**Comment by UnglazedSquash** [comment]
I wouldn't never say you can't. I'm just saying the current time investment to improve on it is probably not justifiable given the results currently being had with the current method. In the future I'm sure it will be improved on. Just maybe not the highest priority item at the moment for them.

**Comment by magnumripper** [comment]
Time investment? BS, it's a trivial fix and it would save me and thousands of other users lots and lots of exactly that: **Time**.

**Comment by GuzziRaz** [comment]
Your comments make no sense and add no value to this issue.

**Comment by SaltWei** [comment]
> If I didn’t select a different build plate and it did a full mesh 10 minutes ago, why do it again?

Since after the hot bed removed from the magnetic plate and then reinstalled, the horizontal state may also change.

**Comment by SaltWei** [comment]
By the way, if you pay attention to the bed level process, you can find that the printer is probed 5 points first to check whether bed level has been changed. If not changed, then it will not do the full bed level.

**Comment by GuzziRaz** [comment]
OK that's obviously acceptable, except my bed seems to do the full program every single time. Between those calibrations, I just carefully scrape the previous calibration off without removing the plate. Does this mean my bed is somehow unstable?

**Comment by GuzziRaz** [comment]
Paying closer attention to the process, you are right it’s not always doing a full ABL. Calibration of 8+ filaments after a nozzle change is still tedious but the main problem could be solved by #2465 so I’m closing this.
