### ISSUE TITLE
[Feature request] Add tooltips for types of infill.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#265]
For a new user, the infill types mean almost nothing.

A tooltip appears currently repeating the name of the type of infill. Could this be used to describe what each type of infill does?

![image](https://user-images.githubusercontent.com/63362209/189995343-f2beee52-761d-4f57-9d58-9051cb9b469c.png)

**Comment by YifanWuBambu** [comment]
@RobinWhitfield 
Thanks for the suggestion. We will add description and a link to related WiKi page for that.

**Comment by lanewei120** [comment]
already added a icon in the left
![image](https://user-images.githubusercontent.com/106916061/222114759-3b86ae19-02bd-4703-a96f-f8a8927ca0cd.png)
