### ISSUE TITLE
History gcode only work with AMS

### ISSUE THREAD

**Issue by foxikos** [bambulab/BambuStudio#2652]
### Bambu Studio Version

1.7.4.52

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 10

### Printer

Bambu P1S

### How to reproduce

1. Go to Bambu Handy
2. go to Me tab
3. go to Printing History
4. Select file
5. for printer with AMS is only AMS available, no other filament - cannot select enable AMS or not

### Actual results

No possibility to print history file without AMS

### Expected results

Possibility to checkin or checkout AMS 

### Project file & Debug log uploads

No project - connected with Bambu Handy app

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
as a banbu-handy issue, please report this issue to https://github.com/bambulab/Bambu-Handy

**Comment by SaltWei** [comment]
Move the ticket to right place. Done
