### ISSUE TITLE
Bambu Studio generating floating support, ignoring tree setting

### ISSUE THREAD

**Issue by JomerDev** [bambulab/BambuStudio#2660]
### Bambu Studio Version

01.07.06.92

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 10

### Additional system information

Display Card: NVIDIA GeForce RTX 3060 Ti

### Printer

Bambu Lab P1S

### How to reproduce

Open up project. Select Plate 3 and slice

### Actual results

You'll see floating supports.
Even weirder, the only way to remove these supports is to disable supports entirely. The supports are supposed to be tree supports, but even setting it to tree(manual) and painting in the supports causes this issue to show up

![image](https://github.com/bambulab/BambuStudio/assets/5282863/c370302f-6045-494c-9a05-6736d37efa24)

### Expected results

The supports should not be floating, nor should it generate normal supports when tree supports are selected

### Project file & Debug log uploads

[BLV - AMS Riser for Bambu Lab X1C v1.3 Issue.zip](https://github.com/bambulab/BambuStudio/files/12797401/BLV.-.AMS.Riser.for.Bambu.Lab.X1C.v1.3.Issue.zip)
I'm not the only one with these issues, multiple pleople in the comments of it (https://makerworld.com/de/models/19535) have the same issue

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
Yes, that's a bug with hybrid support. We'll fix it in the next version.
