### ISSUE TITLE
fatal error, exception catched: invalid string position

### ISSUE THREAD

**Issue by jcasey763** [bambulab/BambuStudio#2665]
### Bambu Studio Version

1.7.6

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Additional system information

amd ryzen 5 3600 6-core processor

### Printer

bambu lab p1p

### How to reproduce

1. download software
2. finish installation
3. attempt to open software

### Actual results

received error code stating "fatal error, exception catched: invalid string position"

### Expected results

after following above steps I should be able to access the software

### Project file & Debug log uploads

system will not let me copy error message direct from box and cannot open application to get files

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SaltWei** [comment]
Could you provided the log file for us to check？We can not reproduce this issue under our PC environment.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/4d58bfdf-5070-426c-8047-fdb9b72efb9c)

**Comment by zk213** [comment]
Hey, i also met this problem just after yesterday's update
[debug_Wed_Oct_11_18_06_10_29456.log.zip](https://github.com/bambulab/BambuStudio/files/12868081/debug_Wed_Oct_11_18_06_10_29456.log.zip)

**Comment by jcasey763** [comment]
It randomly started working after a previous update but I used orcaslicer
in place of it and had no issues with that.

**Comment by Marsian999** [comment]
![Screenshot 2023-03-04 144811](https://github.com/bambulab/BambuStudio/assets/49322933/fd21bab5-d2bf-4988-9f06-7de29d20f44f)
i having that same problem after the lastest update
fatal error, exception catched: invalid string position

**Comment by Marsian999** [comment]
![Screenshot 2024-01-18 141449](https://github.com/bambulab/BambuStudio/assets/49322933/28a5970f-752e-40d6-b44b-43d6ea539943)
sorry wrong pic

**Comment by Marsian999** [comment]
![Screenshot 2024-01-18 141449](https://github.com/bambulab/BambuStudio/assets/49322933/0e200c54-f9e9-4a2c-8f81-b10170a081c9)
i also having the same problem
bambu studio GUI initialization failed
fatal error, exception catched: invalid string position

**Comment by lanewei120** [comment]
> ![Screenshot 2024-01-18 141449](https://private-user-images.githubusercontent.com/49322933/297856245-0e200c54-f9e9-4a2c-8f81-b10170a081c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MjU1MzYsIm5iZiI6MTcwNTYyNTIzNiwicGF0aCI6Ii80OTMyMjkzMy8yOTc4NTYyNDUtMGUyMDBjNTQtZjllOS00YTJjLThmODEtYjEwMTcwYTA4MWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAwNDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjI4ZGZmMTFhOGZkOTMxYTEwNGJmMTViZGQ0MGE4MTgxYzIyYTJlMDI0NTE0ZjhhNTJkOGM4N2VhNWFkYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3QbM11RYRmBtOvj2xoZuU5cgt-4Od6xD_ZQvyLVETkc) i also having the same problem bambu studio GUI initialization failed fatal error, exception catched: invalid string position

usually, you just need to remove BambuStudio.conf and BambuNetworkEngine.conf
and reboot the software

**Comment by ClickDaHouseCat** [comment]
I resolve this problem. I uninstalled with 'Delete user data" and installed again.

**Comment by mccccw** [comment]
nope i did it after restart of bambustudio again this
