### ISSUE TITLE
"Support: On build plate only" option caused strange behavior

### ISSUE THREAD

**Issue by mbbill** [bambulab/BambuStudio#2669]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

Windows11

### Printer

P1P

### How to reproduce

while printing this little hat, there's a overhanging flat surface at the bottom that needs some support.
![image](https://github.com/bambulab/BambuStudio/assets/841602/aa7f322d-8eb1-4db2-a057-0b077046c093)

![image](https://github.com/bambulab/BambuStudio/assets/841602/5a89a7c0-923c-49af-a6b0-d6b06bb1bd34)

Support settings is "tree(auto) + Default + 35 degree threshold angle" and when the "On build plate only" is turned on, it looks like below.:
![image](https://github.com/bambulab/BambuStudio/assets/841602/3db6508d-d31a-4118-aeb4-f9e65a04f9d1)

which is, kinda as expected. Then if I turn the **"On build plate only"** flag off, this happens:

![image](https://github.com/bambulab/BambuStudio/assets/841602/ab35d28b-5860-46e9-aef0-d407c7eb9d01)

It's a mixture of tree and traditional support, and not like the normal support there's a wall around it making it very easy to peel off. This is a behavior I wanted but what I don't understand is that why it can be affected by the "On build plate only" option. IMO it's likely a bug, but I hope you guys keep the second behavior even if it's an unexpected bug or something.

### Actual results

Described above. I'm not sure which result is expected.

### Expected results

Ditto.

### Project file & Debug log uploads

[hat.zip](https://github.com/bambulab/BambuStudio/files/12812940/hat.zip)
[3mf.zip](https://github.com/bambulab/BambuStudio/files/12812950/hat.2.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
The logic is quite complicated. I'll try to explain it a bit:
Tree support has 3 different styles, and the default one is "tree hybrid", which is exactly the mixture of normal and tree nodes as you mentioned.
When it encounters a large flat overhang region, it will generate normal nodes underneath and grow downwards just like normal supports, which means it may touch the object. Therefore, if the user turns on "On build plate only" option, we disable the normal nodes, and generate only tree nodes.
