### ISSUE TITLE
Please add horisontal orientation support in Bambu Handy app for iPadOS

### ISSUE THREAD

**Issue by kennethfinn** [bambulab/BambuStudio#2673]
**Is your feature request related to a problem? Please describe.**
_**I cant use Bambu Handy in horisontal orientation. E.g. when attached to the Magic Keyboard. As it is 98% of all usage.**_

**Describe the solution you'd like**
_**Please add horisontal orientation support in Bambu Handy app for iPadOS, so I can use it when attached to the magic keyboard.**_

**Describe alternatives you've considered**
_**Alternatively add auto rotation based on iPad's orientation.**_

**Additional context**

**Comment by SaltWei** [comment]
Not studio issue
