### ISSUE TITLE
Could you please make the AMS Cabin humidity and Desiccant status indicator a bit bigger?

### ISSUE THREAD

**Issue by kennethfinn** [bambulab/BambuStudio#2678]
**Is your feature request related to a problem? Please describe.**
**_The AMS Cabin humidity and Desiccant status indicator is very very Tiny_**

**Describe the solution you'd like**
_**Can you please make it bigger?**_

**Describe alternatives you've considered**

**Additional context**

**Comment by kennethfinn** [comment]
Duplicate issue. already reported by someone else

**Comment by DanTup** [comment]
I couldn't find a dupe of this except one that was already implemented (https://github.com/bambulab/BambuStudio/issues/1120), but it's still very unreadable IMO. I filed https://github.com/bambulab/BambuStudio/issues/3827 as a request to make it larger and/or include in the popup.
