### ISSUE TITLE
v1.01 style smooth timelapse (non-printed wipe tower)

### ISSUE THREAD

**Issue by DocHogan** [bambulab/BambuStudio#268]
As titled, v1.01 style smooth timelapse with non-printable prime tower. It worked fine. New smooth timelapse wastes waaaaaaaaaaaay too much filament and time. 'Traditional' is not an adequate replacement. Old style should be available as an option in the list.

**Comment by YifanWuBambu** [comment]
We will optimize smooth timelapse's filament and time cost in the next release.

**Comment by MRedmon** [comment]
Yes, please allow the smooth timelapse as it is but without the mandatory tower.  It worked fine before without the tower.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
