### ISSUE TITLE
PA Profile Factor K not shown in German language

### ISSUE THREAD

**Issue by MrTom1** [bambulab/BambuStudio#2689]
### Bambu Studio Version

1.7.7.88

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS Ventura & Sonoma 

### Printer

Bambu Lab X1C

### How to reproduce

Under device - AMS settings, 'Factors of Flow Dynamics Calibration', 'Factor K' is always set to 0,000000 in German language, however works correct in settings for English language

### Actual results

Factor K not useable in German language

### Expected results

Factor K should be set-up as in English language settings

### Project file & Debug log uploads

[debug_Tue_Oct_10_11_39_24_13672.log.0.zip](https://github.com/bambulab/BambuStudio/files/12855720/debug_Tue_Oct_10_11_39_24_13672.log.0.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/787272ed-dba8-4ee2-a7f2-a42c8e21b76b)

Can you see your calibration results under Calibration page in a German environment?

**Comment by MrTom1** [comment]
<img width="712" alt="Ergebnis der Flussdynamik-Kalibrierung 2023-10-12 09-27-57" src="https://github.com/bambulab/BambuStudio/assets/22220221/4a33d846-0f2c-4047-af2b-0e7b6dc909ac">

Results are all set to 0,000!

**Comment by MrTom1** [comment]
Another bug on this:
When I'm in the 'Manage Results' window (as above) and try to 'Edit' the result of filament, I can do it and the changed K Factor is shown in the table. However than I'm stuck on this window, no further 'Edit' or 'Delete' of any filament are possible.
Closing the window and reopening 'Manage Results' are showing 'Faktor K' values back to zero, changes done before are gone.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in V1.7.7.89, you can have a try.

**Comment by MrTom1** [comment]
Confirmed, working fine now!. Bug fixed.
Thanks
