### ISSUE TITLE
Bambu Studio Losing Sync With Printer Status

### ISSUE THREAD

**Issue by UnglazedSquash** [bambulab/BambuStudio#2692]
### Bambu Studio Version

1.7.6.92

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. Start print from windows PC over network
2. Print Completes and you remove print from printer
3. Start to slice something in bambu studio without starting a new project
4. Hit Print Plate and get popup that says the printer is busy and you cannot start the print even though the print has actually completed.
5. Look at device page and it shows the printer status as still printing. AMS graphic still shows filament roting from slot to tool head. Below cam Printing Progress graphic still shows the % complete bar at some percentage, layer number still not 100/100 and time remaining still some number. Buttons still present for pause and stop.
6.You are able to click the Camera play button and see real live video from the camera.
7. Syncing or Resyncing the AMS has no effect.
8. Selecting your printer again in the My Device dropdown does not resolve it. It shows as busy still in the my device dropdown.
9. Bambu Handy app and Print screen both show the print is complete and the printer is not busy.
10. The only way to resolve is closing the Bambu Studio app and opening it again.

### Actual results

Have to restart the bambu studio app to be able to start a print.

### Expected results

Should not show busy when trying to start print.

### Project file & Debug log uploads

not specific to any project. here is an example. I think it is happening mabye 2-3 out of 4 times. Could not find a specific log to the event shown below which was today 2023-10-10. Attached are some previous logs that might be from a similar situation.

![image](https://github.com/bambulab/BambuStudio/assets/139061581/5f39aecb-228d-4515-9e27-abd25a13e87f)
[logs.zip](https://github.com/bambulab/BambuStudio/files/12858241/logs.zip)

![image](https://github.com/bambulab/BambuStudio/assets/139061581/52f452d3-142a-4665-a096-726fbf0022e8)

[Bug Drop Peg Project.zip](https://github.com/bambulab/BambuStudio/files/12858210/Bug.Drop.Peg.Project.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by UnglazedSquash** [comment]
Timeout. Downloading the new version now. I will update this ticket if the issue is still present. Thanks.

**Comment by walterwongbbl** [comment]
Hi @UnglazedSquash 
We have also identified this issue, and it appears to be related to some data transmission problems between the printer and Studio. We are actively searching for a solution.

**Comment by UnglazedSquash** [comment]
@walterwongbbl  After updating to the newest version 1.7.7.88 I have not been able to replicate the issue when before on version 1.7.6.92 I could consistently replicate the bug. Maybe it fixed itself. haha. I will close this ticket for now since I cannot replicate the bug. Thanks.

**Comment by UnglazedSquash** [comment]
@walterwongbbl It appears to be caused by windows 11 sleep/hibernate behavior. I can try replicating it again. After starting a print in bambu studio on windows 11 and some time later during the print putting my laptop into hibernate/sleep. The print finishes. Sometime later I wake my laptop and then bambu studio shows the print still going on like shown above. I think this is the exact same scenario as before I just did not link the two together then.

**Comment by walterwongbbl** [comment]
@UnglazedSquash 
Thank you very much. We may currently not have enough resources to fix the issues caused by sleep mode. Once we have available time, we will address this problem.

**Comment by walterwongbbl** [comment]
This issue will be closed

**Comment by alexcroox** [comment]
Tihs is the same with MacOS, if you have Studio open and close the lid, next time you open it and continue it will be out of sync with the printer and refuses to re-sync, despite the live view showing the printer is idle.
