### ISSUE TITLE
Bambu Studio Doesn't reload model from disk if Studio has been restarted

### ISSUE THREAD

**Issue by project-x51** [bambulab/BambuStudio#2696]
### Bambu Studio Version

1.7.7.88

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

i9 13900K 96GB RAM, 8TB M.2 RAID, RTX4090

### Printer

X1 Carbon Combo

### How to reproduce

1. Add a model to the plate
2. Make a change to the model in CAD and save in the same location with the same filename
3. Click on 'Reload from Disk' and the model reloads as expected.
4. Save the plate as a project
5. Close Bambu Studio
6. Open Bambu Studio
7. Open the previously saved project
8. Make a change to the model in CAD and save in the same location with the same filename
9. Click on 'Reload from Disk'. This time it fails saying "Unable to reload"

![image](https://github.com/bambulab/BambuStudio/assets/40679862/6507ba6a-7ab1-44c0-a1aa-73b025ed7aa7)

### Actual results

Reload fails if model is reloaded from disk once Bambu Studio has been restarted. For any model on any project.

### Expected results

Reload from disk should always work if the model is saved where it always was with the same filename. If it can't be found it should ask to find it. This happens if Bambu Studio hasn't been closed/restarted but not after. 

### Project file & Debug log uploads

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DanBao-Bambu** [comment]
Hello, we have fixed this issue. Please use this feature in the next new version and check if it meets your expectations.
