### ISSUE TITLE
Attention: The current hot bed temperature is relatively high.... (But actuall temp is 23°C)

### ISSUE THREAD

**Issue by TheD0me** [bambulab/BambuStudio#2698]
### Bambu Studio Version

1.7.7.88

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

CPU: Ryzen 5 3600xt
Memory: 32gb
GPU: Nvidia RTX3600

### Printer

BambuLAB P1S COmbo

### How to reproduce

1. Slice a STL (ABS)
2. Hit Print
3. Hit Send

### Actual results

And then come the attention
![Screenshot 2023-10-11 104826](https://github.com/bambulab/BambuStudio/assets/125121017/5b80bf10-fcec-4b12-b1db-89247d03fe67)

The Print is at Room Tempearture (23°C)

I can hit "accept" and then start the print normally

### Expected results

---

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12867357/log.zip)
[Print.zip](https://github.com/bambulab/BambuStudio/files/12867361/Print.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lichao0223** [comment]
I have the same issue

**Comment by floppyhammer** [comment]
I have got a repo too

**Comment by forphuksake** [comment]
same here and i had a home z issue

**Comment by sayunkim** [comment]
I have the same issue with the latest version of Bambulab Studio as well.

**Comment by Canuna** [comment]
Same here, just updated to the latest version and started to get it.

![image](https://github.com/bambulab/BambuStudio/assets/44111871/6cc7c617-7693-4c95-9caa-8f51d1c45290)

**Comment by blue68camaro-git** [comment]
Same issue here with version 1.7.7.88.

**Comment by bpsmicro** [comment]
So I'm super-newbie, having only gotten my P1S yesterday. I'm using all stock profiles everywhere and have tweaked nothing. I'm just looking at a simple STL print and seeing this warning.
I've selected my PLA Basic filament, and I followed the above to export to gcode, and I see this line:
`; temperature_vitrification = 45`

If I look for M140, I indeed see this:
```
;===== heatbed preheat ====================
M1002 gcode_claim_action : 2
M140 S55 ;set bed temp
M190 S55 ;wait for bed temp
```

So, yep, that seems off. I'm using the Textured PEI plate that came with the printer.

So I found where to edit the filament settings, where Textured PEI Plate was indeed set to 55 (first & other layers), and tweaked that down to 45. Saved as a copy, made sure it's selected in Preview. But I *still* got the warning.
Tried again but set the temp to 44, and it worked.

I'm wondering if there's a '<' test somewhere that should be a '<=' test.

**Comment by arekm** [comment]
You don't need to change anything. You just acknowledge slicer warning, open printer doors and print.

"if max temperature that occurs in gcode file (M140 S, M190 S gcodes) is bigger or equal "temperature_vitrification" then bambu slicer will issue mentioned warning", so 45 with warning and 44 with no warning fits that rule correctly.

**Comment by bpsmicro** [comment]
Okay, gotcha. It was where the "or equal" part fit into the equation that I was wondering about. All is clear now. Thanks!

**Comment by XunZhangBambu** [comment]
Sorry,the tip should be "The hot bed temperature in current setting..." rather than "The current hot bed temperature". In latest version , we remove the pop up and add a daily tip for open-door printing

**Comment by arekm** [comment]
@XunZhangBambu Any reason why this issue was left open? 

Also IMO you should activate stale issues management on github to automatically close these with no progress etc (as github is approaching 1.5k open issue which is unmanageable)

(example from prusa repo: https://github.com/prusa3d/Prusa-Firmware/blob/MK3/.github/workflows/stale.yml
