### ISSUE TITLE
[Bug Ux / 01.00.10.05 / Win ] conversion to meters/inches out of bed

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#27]
When converting a model to meters or inches, the model exits the print plane without a warning as in prusaSlicer.

<img width="284" alt="Schermata 2022-07-18 alle 11 03 37" src="https://user-images.githubusercontent.com/4783556/179479156-588d0fd6-d70f-49ec-870b-10996954c571.png">

**Comment by lanewei120** [comment]
already fixed in the newest released version v1.2.0
