### ISSUE TITLE
Dark Mode not avaiable on Mac OS

### ISSUE THREAD

**Issue by mow97** [bambulab/BambuStudio#2700]
### Bambu Studio Version

1.77.88

### Where is the application from?

Bambu Lab Official website

### OS version

MAC OS 14.1 (Sonoma)

### Additional system information

Apple Mac Mini M2
8 Gb RAM

### Printer

BAMBU P1P 3D

### How to reproduce

In Bambu Studio, dark mode not avaiable !

### Actual results

In Bambu Studio, dark mode not avaiable !

### Expected results

In Bambu Studio, dark mode not avaiable !

### Project file & Debug log uploads

In Bambu Studio, dark mode not avaiable !

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @mow97 
It appears that the issue might be related to your system running macOS 14.1, and your software needs to add support for it. We will work on adding support as soon as possible.

**Comment by walterwongbbl** [comment]
@mow97 
Are you the latest updated macOS 14.1?

**Comment by RaySajuuk** [comment]
@mow97 14.1 still in beta, which is not stable and is expected to have issue.

**Comment by GuzziRaz** [comment]
Dark mode works for me using 1.7.7.89 on macOS 14.0 (running intel though). I can't seem to find any setting for it, it just follows the global setting in the OS.

**Comment by mow97** [comment]
I running  macOS 14.0  M2 processor

**Comment by mow97** [comment]
I not found any setting regardles to Dark Mode

**Comment by GuzziRaz** [comment]
> I not found any setting regardles to Dark Mode

System Settings / Appearance

**Comment by mow97** [comment]
It's about Bambu Studio Dark Mode, not Mac OS Dark Mode

**Comment by GuzziRaz** [comment]
> It's about Bambu Studio Dark Mode, not Mac OS Dark Mode

What I'm saying is that you turn it on at OS level, and then it will be effective in Bambu Studio.

**Comment by walterwongbbl** [comment]
Hi @mow97 
In MACOS, the dark mode of Studio will change according to the system settings.

**Comment by walterwongbbl** [comment]
Hi. @GuzziRaz 
How can I upgrade to macOS 14.1.  It seems to require an Apple developer account.

**Comment by GuzziRaz** [comment]
@walterwongbbl it should be a normal upgrade for anyone, released October 25.

**Comment by walterwongbbl** [comment]
@mow97 
Is dark mode still unavailable on your computer?

**Comment by walterwongbbl** [comment]
If you have any other issues, please create a new issue. The current conversation will be closed.
