### ISSUE TITLE
[Issue] Studio asks at every startafter  SSl certificates

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#2711]
The message in starting dialog should only displayed once. 
Seen on Archlinux with KDE

**Comment by bambu123** [comment]
Not sure what you are talking about. Could you please take a screenshot of the dialog?

**Comment by tkrill** [comment]
I most likely also experiencing this while running Ubuntu 22.04. This shows up on every start of Bambu Studio. If i choose No in the dialog the application terminates. (I'm also totally unable login from the app when launched which might be related or not) 

![bambu-cert](https://github.com/bambulab/BambuStudio/assets/4834534/cf706f55-802d-442f-a1dd-e55245499e1d)

**Comment by justpie** [comment]
I am also getting this. Any luck resolving it?

**Comment by tkrill** [comment]
@justpie i managed to login and then i the problem stopped. Unfortunately i don't remember if i did something differently.

**Comment by lanewei120** [comment]
Hello @tkrill 

if click "remmember my choice"
will it still popup when bootup next time?

**Comment by justpie** [comment]
I actually was able to resolve my issue by clicking "remember my choice" and logging in. However, there was a GUI issue where the checkbox label wasn't visible. All I could see was the checkbox so it made it really unclear as to what I was actually clicking on.

**Comment by tkrill** [comment]
@lanewei120 i unfortunately don't remember but an educated guess is that i checked the remember box. (If there is a way to reverse this i can try that. Otherwise @justpie  comment might be enough)

**Comment by lanewei120** [comment]
thanks

we will fix the black  checkbox issue, make it more clear

**Comment by pcairic** [comment]
Still happening.
Not only is the checkbox black, but the text is half hidden and the checkbox doesn't have a legend.
Linux Mint 21.3 Cinnamon

**Comment by YoSTEALTH** [comment]
I was having the same issue, I use manjaro (linux) so solved it by:
`System Settings` -> `Manjaro Settings Manager` -> `Locale Settings` -> `Add` -> select `English` + `United Kingdom` -> `Add`

That should do it, good luck.

**Comment by andrew-4D** [comment]
FYI, black checkbox = "unselected"  white checkbox = "selected"

**Comment by mike-lloyd03** [comment]
Depending on your theme, the checkbox might be completely invisible. I just clicked around to find it.
![image](https://github.com/user-attachments/assets/fdec4d1e-aaa3-46e5-a2b9-9629e49e198d)
![image](https://github.com/user-attachments/assets/f13986f7-c0b2-48ea-afeb-bedc3e475c36)

**Comment by MackBambu** [comment]
fixed
