### ISSUE TITLE
Generic PLA High Speed can no longer be selected in AMS

### ISSUE THREAD

**Issue by LTB3D** [bambulab/BambuStudio#2713]
### Bambu Studio Version

1.7.7.88

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sonoma 14.0

### Printer

X1 Carbon

### How to reproduce

1. Slice Place
2. Print Plate

### Actual results

Generic PLA High Speed now shows up as PLA+ and is no longer selectable in the AMS (only with the Bambu_Studio_mac-v01.07.07.88, it was fine with Bambu_Studio_mac-v01.07.06.92)

![Screenshot 2023-10-12 at 5 26 45 PM](https://github.com/bambulab/BambuStudio/assets/147772051/688b4ed1-15b7-4c89-897d-2cd46285efdf)

### Expected results

![Screenshot 2023-10-12 at 4 55 18 PM](https://github.com/bambulab/BambuStudio/assets/147772051/d5c02a07-93ac-49c0-bcaa-0cb96ef8af3d)

### Project file & Debug log uploads

[Bug.zip](https://github.com/bambulab/BambuStudio/files/12887357/Bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
Generic PLA High Speed is filament profile for PLA. do you mean the filament detect is wrong? PLA be identified as PLA+?

**Comment by LTB3D** [comment]
No, I would not say that it is "detecting" anything. **Generic PLA High Speed** is the profile that I had/have selected for slots A1 & A4. I'm using HS filament from another brand in those slots. 
The upgrade to 1.7.7.88 changed the profile somehow & now it is calling slots A1 & A4 PLA+.

That on i's own would be fine, but it's not allowing me to select slots A1 and /or A4 at all & automatically mapping it to slot A3. Only slots A3 & A2 come up as available. The files/designs were prepared as Filament # 1 (aka A1)
![Screenshot 2023-10-13 at 3 10 35 AM](https://github.com/bambulab/BambuStudio/assets/147772051/ecdea2a7-496e-4fe4-b78c-7054994e5267)

![Screenshot 2023-10-13 at 3 05 16 AM](https://github.com/bambulab/BambuStudio/assets/147772051/acf6a589-4bac-4781-8c85-4964be281a4b)


But when I hit "print plate" it changes it remaps it to Filament # 3 (aka A3)
![Screenshot 2023-10-13 at 3 12 47 AM](https://github.com/bambulab/BambuStudio/assets/147772051/4d28e8be-51f3-4a37-8d00-632f8e9a2a74)

And does not allow me to select slots A1 or A4 at all
![Screenshot 2023-10-12 at 5 26 45 PM](https://github.com/bambulab/BambuStudio/assets/147772051/1360e807-a5f8-4764-b7af-13fabbd10d8c)


I've already hit "sync" and "re-sync", but it didn't help. It's like the Profile for HS PLA was updated in one part of the software (Device tab) but not in the other sections of the software (Prepare & Preview tabs) and now it is confused. 
I'm thinking the "Device" is now calling it PLA+, but "Prepare" is still calling it PLA.

Does that make sense?

**Comment by StoneLiBambulab** [comment]
@sodachen22 

printer AMS push a PLA+ type when select the Generic PLA High Speed, please have a check.

Thanks!

Stone Li（旺仔）

**Comment by sodachen22** [comment]
@LTB3D It looks like there is problem in filament configuration after Studio upgrading from v01.07.06.92 to 01.07.07.88. Would you please share the configuration files in json format in this directory?
![image](https://github.com/bambulab/BambuStudio/assets/112450380/1bea789e-151f-4726-8ae2-2bafa3bb8362)

**Comment by LTB3D** [comment]
[filament.zip](https://github.com/bambulab/BambuStudio/files/12892604/filament.zip)

**Comment by StoneLiBambulab** [comment]
There is a bug when getting the filament type, will be fixed in 1.8.xx

Thanks!
Stone Li

**Comment by StoneLiBambu** [comment]
fixed
