### ISSUE TITLE
"Plate Type" is greyed out for 3rd Party printer and cannot be changed.  

### ISSUE THREAD

**Issue by jonathangregsonrogerscom** [bambulab/BambuStudio#2714]
### Bambu Studio Version

1.7.7.88

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Following Bambu Lab wiki doc I created 3rd party printer. Seems to be working fine except the "Plate Type".  My printer only has a cool plate.  I've reviewed all json files and cannot find a reference setting for plate_type.  As it is, the printer will print but throws a warning mssg indicating that since the printer doesnt have a heated bed all further cmmds re heated bed will be ignored.

### Printer

3rd party printer - XYZ Printer daVinci Mini w+ 

### How to reproduce

1. follow wiki instructions on adding 3rd party printer.
2. launch Bambu Suite and add printer.
3. Try to change Plate Type to "Cool Plate"

### Actual results

Add 3rd party printer using wiki instructions.

### Expected results

When Bambu Suite loads 3rd party printer should have Plate Type not greyed out.

### Project file & Debug log uploads

[daVinci Mini w+.zip](https://github.com/bambulab/BambuStudio/files/12887284/daVinci.Mini.w%2B.zip)
[debug_Thu_Oct_12_16_43_31_10956.log.zip](https://github.com/bambulab/BambuStudio/files/12887366/debug_Thu_Oct_12_16_43_31_10956.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/f10e0a95-8d82-4968-ba77-b5809190dda8)
if the cool_plate_temp be set to 0, means the plate not be used, otherwise, this plate can be used.

**Comment by jonathangregsonrogerscom** [comment]
Thx for the quick reply!! I'll give it a try this morning.

Thx
Jonathan

Sent from Rogers Yahoo Mail on Android 
 
  On Thu., 12 Oct. 2023 at 10:33 p.m., ***@***.***> wrote:   



if the cool_plate_temp be set to 0, means the plate not be used, otherwise, this plate can be used.

**Comment by jonathangregsonrogerscom** [comment]
I checked and there is no Cool Plate temp avail to change (see attached).

![Cool Plate not available to select for 3rd party](https://github.com/bambulab/BambuStudio/assets/142115862/691cb865-2cd1-4112-9251-e0969f3d70b8)

**Comment by QingZhangBambu** [comment]
i checked the code logic, 3d party printers do not distinguish plate type. just modify the plate temp, it can be used as a cool plate.

**Comment by SaltWei** [comment]
For 3rd party printer, directly set the bed temperature. Not a bug
