### ISSUE TITLE
Cannot print after update to Bambu Studio 1.7.7.89

### ISSUE THREAD

**Issue by intrinsic420** [bambulab/BambuStudio#2727]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 13.4.1

### Printer

Bambu Lab X1C

### How to reproduce

This happened directly after updating Bambu Studio.I loaded a STEP file to print using Generic PETG settings on a textured PEI sheet. Supports on base plate only. I send it to the X1C using the AMS slot 4 where PETG is loaded. When the slicer uploads it to my printer, it says "The selected printer is incompatible with the chosen printer presets." I have changed absolutely nothing and literally printed something within the past couple of days with the exact same settings, just the older version of the slicer.

### Actual results

<img width="471" alt="Screenshot 2023-10-13 at 9 10 01 PM" src="https://github.com/bambulab/BambuStudio/assets/147896242/31971902-b1af-42bc-990d-71c86c02982f">
Here's a screenshot of the dialogue box.

### Expected results

It should print like it always did before.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/12902357/log.zip)
[bike grip adapter.3mf.zip](https://github.com/bambulab/BambuStudio/files/12902358/bike.grip.adapter.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by intrinsic420** [comment]
Further testing: attempted print of Bambu Lab's wireless mouse top shell using the presets and raising bed and nozzle temp slightly for silk PLA. Attempted to print on both Cool Plate and Textured PEI sheet. Both say that my printer is not compatible. Loaded file to MicroSD card and printed from there. I am now getting layer shifts in the print. Very inconsistent. The last attempt tried printing a layer about 10cm away from where the print was at about the 10th layer.

I also tried all of this from a PC running the latest Windows updates and the latest slicer version.

Also, since the slicer update my print head BANGS against the stops during the startup procedure. Whenever it homes the head, or goes to the purge slot, it bangs around hard enough now to where the print head cover is coming off. Interestingly, the cover warning hasn't come up at all, even when I took it completely off to reseat the magnets. I did that while the head was moving accidentally. No warning. I want to revert my slicer version but I don't know how :(

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/d40d0479-93c4-4181-b5fa-55794c5cd0ec)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/22a7f17e-8396-4c1c-b2d9-908c91cdf168)

The pinter in 3mf be chosen is A1 mini, it is not compatible  printer of X1C. Because the popup is in the left, it may damage X1C's extrude.

**Comment by QingZhangBambu** [comment]
and it should be pohibited to use A1 mini profile in X1C machine. @sodachen22

**Comment by intrinsic420** [comment]
Thanks Qing! I feel stupid not checking that, but to be fair I only had to set that parameter once on initial install.

**Comment by sodachen22** [comment]
Printer will support the feature that prevent the printing job if the sliced 3MF is not compatible with the printer.
