### ISSUE TITLE
AMS Cabin Humidity indicator for colorblind

### ISSUE THREAD

**Issue by Th3M1k3y** [bambulab/BambuStudio#2728]
**Is your feature request related to a problem? Please describe.**
I am having problems seeing the color on the indicator for AMS Cabin Humidity

**Describe the solution you'd like**
Being able to hover the mouse over the indicator and then get a tooltip with Red/Yellow/Green

**Describe alternatives you've considered**
Adding H for high, M for medium, L for low to the icon.

**Additional context**
![image](https://github.com/bambulab/BambuStudio/assets/29869794/cade1eac-305c-49f0-a34c-26f4900eb675)

**Comment by EStreet706** [comment]
I second this.  Also, selecting videos/models to delete is impossible for colorblind people to see correctly.   That faint garbage is just that.  Don't use it!

**Comment by walterwongbbl** [comment]
Hi. @BlackNet @Th3M1k3y 
We have already provided feedback to the designers regarding this issue.

**Comment by walterwongbbl** [comment]
Hi. @BlackNet @Th3M1k3y 
We have already provided feedback to the designers regarding this issue.

**Comment by BlackNet** [comment]
Well. New version does have changes so kudos for that. Light mode the problem is still there as just a background change is not enough. The icon itself is faint while everything else around it is higher contrast.

**Comment by walterwongbbl** [comment]
We have optimized this issue and it will be closed
