### ISSUE TITLE
Bug: strange gaps with new Arachene engine

### ISSUE THREAD

**Issue by SoftFever** [bambulab/BambuStudio#275]
I noticed there are strange gaps since I upgraded to 1.2.0.9.
![image](https://user-images.githubusercontent.com/103989404/190163691-58e11f42-320f-4646-b2a4-adb879d2ffe6.png)

Project file to reproduce it has been attached.

[bug_gap.zip](https://github.com/bambulab/BambuStudio/files/9566590/bug_gap.zip)

**Comment by SaltWei** [comment]
Arachne engine is not be applied here. This is traditional concentric pattern.
So this should be a feature request to apply arachne for external concentric pattern

**Comment by SaltWei** [comment]
Done. Please wait for the next release.
