### ISSUE TITLE
关于 在1.7.7.89的版本中 X1E 增加腔体温度

### ISSUE THREAD

**Issue by Grayfive** [bambulab/BambuStudio#2750]
在X1E的 在官方耗材中, X1E机型已经开启了, 腔体温度 , 但在第三方的机型 , 并未开启功能(例如:QIDI) , 本身该机型是配备了该功能 , 我更希望把 参数名 写到 提示框 方便VORON 机型的用户 及 带 腔体温度控制的机型 ,

个人还有一点小疑问

X1E 并没有设置ABS腔体温度, 在ABS的中的表现中,打印高度越高,打印件可能拦腰开裂等问题,以及变形问题

**Comment by XunZhangBambu** [comment]
最新的版本已经支持对于第三方机型开启腔温控制功能。打开方式如下：开启开发者选项->打印机参数界面勾选支持腔温->材料参数界面调整温度。对于ABS的腔温，我们经过测试最终选择不设置。
