### ISSUE TITLE
有关bambu lab的黑色渲染问题

### ISSUE THREAD

**Issue by littleball01** [bambulab/BambuStudio#2761]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/bambulab/BambuStudio/assets/45869526/87198dc2-c7c5-4bce-890e-e88cda458df9)
黑色耗材在bambulab下完全看不清细节，非常麻烦

**Describe the solution you'd like**
改变一下渲染的参数是否可行？或者用深灰色代替黑色

**Describe alternatives you've considered**

**Additional context**

**Comment by Haidiye00** [comment]
This issue will be resolved in V1.8 and will be released in the near future

**Comment by arekm** [comment]
![black](https://github.com/bambulab/BambuStudio/assets/50869/e715845e-f643-4452-b51b-8ed3565b11ba)

It's way better in 1.8 beta. Thanks!

**Comment by Haidiye00** [comment]
Thank you for your use and trust. We will continue to work hard
