### ISSUE TITLE
Extra colour layers

### ISSUE THREAD

**Issue by KobaRiley** [bambulab/BambuStudio#2762]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro

### Printer

Bambu X1 Carbon

### How to reproduce

Open attached 3mf file, and colour the cental square a diffent colour from large square. Set layer thickness to 0.2mm. Slice.

### Actual results

The first layer is as expected, the second layer only uses one colour, and the 3rd layer again uses two colours. 
When slicing at other layer heights, there is always a minimum of three layers, even if the small square thickness is less than the layer height. This leads to unncecessary filament changes, wasting filament and time.
![example layer1](https://github.com/bambulab/BambuStudio/assets/148435770/a79b21e6-ca26-4afa-98dd-6bb72842c64a)
![example layer 2](https://github.com/bambulab/BambuStudio/assets/148435770/8813e532-6639-4db4-af43-860c5377f4d3)
![example layer 3](https://github.com/bambulab/BambuStudio/assets/148435770/4ef84d37-43bc-477d-9bba-103ab7f4b0f5)

### Expected results

There should be a single multicolour layer, and then only one colour used afterwards in the case of the attached example.

### Project file & Debug log uploads

There is no error, so not including any log file. 
[Example.zip](https://github.com/bambulab/BambuStudio/files/13039961/Example.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Currently, Studio'rule is that the paint on the top and bottom surfaces will be embedded in the solid fill.
This model has 3 solid layers at the bottom, so the color is embedded in 3 layers. The second layer only displays one color, which is a BUG and is related to the geometric data of the model. We will fix this problem later.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/958b8695-a302-4fba-aa67-70d88e61ce35)
This model is composed of two geometric bodies, as the picture shows.
Studio'rule is that the paint on the top and bottom surfaces will be embedded in the solid fill. This model has 3 solid layers at the bottom, so the color is embedded in 3 layers. 
But if this layer is a surface (top or bottom), the color of the original surface will be displayed first. In this case, the second layer is the bottom surface, and its color is white, so white is displayed first.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/89ba6c2d-9f9c-4aba-b2a4-ec535ae1e394)
![image](https://github.com/bambulab/BambuStudio/assets/120697589/40109fc3-1390-4843-b6fc-b709d338d325)

You can take the following steps to avoid this problem:
1. Split this model into parts
2. Change the filament of Example_2 to 2

**Comment by zhimin-zeng-bambulab** [comment]
@KobaRiley  Does the above methods solve your problem?

**Comment by zhimin-zeng-bambulab** [comment]
A solution was given, and the user did not respond for a long time. Close it.
