### ISSUE TITLE
eSun PLA+ = ABS

### ISSUE THREAD

**Issue by chuk219** [bambulab/BambuStudio#2767]
### Bambu Studio Version

1.7.6.92 and 1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

CPU: Intel i9-13900H
Memory: 32GB 6000MHz LPDDR5
GPU: RTX4070 (mobile)

### Printer

Bambu Lab P1P

### How to reproduce

1. Go to the device tab
2. In the AMS filament selector area, select edit material
3. Select eSun PLA+ in the filament selector drop down
4. Close the edit material window
5. The box for the material will now be labeled ABS

### Actual results

The AMS filament window now shows ABS in the slot where eSun PLA+ was selected.

### Expected results

The AMS filament window used to and should show PLA+ in the slot where eSun PLA+ was selected.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/13049699/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by joshkurtzman** [comment]
I am experiencing the same behavior with Generic PETG. No matter what I do it is showing as ABS once I save.  Bambu Studio Version 1.7.7.89 on MacOS 14.0

**Comment by StoneLiBambulab** [comment]
There is a bug when getting the filament type, will be fixed in 1.8.xx

Thanks!
Stone Li

**Comment by StoneLiBambu** [comment]
fixed.
