### ISSUE TITLE
The source code from the main branch is outdated and doesn't match the one from releases

### ISSUE THREAD

**Issue by astrolemonade** [bambulab/BambuStudio#2770]
### Bambu Studio Version

v01.07.07.89

### Where is the application from?

Bambu Lab github releases

### OS version

Solus 4.4

### Additional system information

Not relevant

### Printer

Bambu A1 Mini

### How to reproduce

The source code from master is outdated and doesn't match the source code from the archives that can be downloaded from the GitHub releases!
Why is that? I would expect the master branch to be the most up to date branch but it isn't. I think it's the https://github.com/bambulab/BambuStudio/tree/v1.7.2_1016 branch that it's receiving the most of the updates.

It's also weird that the branch is not the same with the release: v01.07.07.89 vs v1.7.2_10166

### Actual results

For example:
Inspecting the files from `resources/profiles/BBL/machine` from the github releases archive gives the following:
```
[18:57:37]
[~/.../BBL/machine] $ ls
'Bambu Lab A1 mini 0.2 nozzle.json'  'Bambu Lab X1 0.4 nozzle.json'
'Bambu Lab A1 mini 0.4 nozzle.json'  'Bambu Lab X1 0.6 nozzle.json'
'Bambu Lab A1 mini 0.6 nozzle.json'  'Bambu Lab X1 0.8 nozzle.json'
'Bambu Lab A1 mini 0.8 nozzle.json'  'Bambu Lab X1 Carbon 0.2 nozzle.json'
'Bambu Lab A1 mini.json'             'Bambu Lab X1 Carbon 0.4 nozzle.json'
'Bambu Lab P1P 0.2 nozzle.json'      'Bambu Lab X1 Carbon 0.6 nozzle.json'
'Bambu Lab P1P 0.4 nozzle.json'      'Bambu Lab X1 Carbon 0.8 nozzle.json'
'Bambu Lab P1P 0.6 nozzle.json'      'Bambu Lab X1 Carbon.json'
'Bambu Lab P1P 0.8 nozzle.json'      'Bambu Lab X1E 0.2 nozzle.json'
'Bambu Lab P1P.json'                 'Bambu Lab X1E 0.4 nozzle.json'
'Bambu Lab P1S 0.2 nozzle.json'      'Bambu Lab X1E 0.6 nozzle.json'
'Bambu Lab P1S 0.4 nozzle.json'      'Bambu Lab X1E 0.8 nozzle.json'
'Bambu Lab P1S 0.6 nozzle.json'      'Bambu Lab X1E.json'
'Bambu Lab P1S 0.8 nozzle.json'      'Bambu Lab X1.json'
'Bambu Lab P1S.json'                  fdm_bbl_3dp_001_common.json
'Bambu Lab X1 0.2 nozzle.json'        fdm_machine_common.json
```
and if you look in the repo on the master branch the A1 mini related configs are just missing.
https://github.com/bambulab/BambuStudio/tree/master/resources/profiles/BBL/machine
Also, the source code hasn't been updated since `"01.07.01.62"` as described in
https://github.com/bambulab/BambuStudio/blob/master/version.inc

### Expected results

I would expect the Bambu Labs team to specify where do the GitHub releases come from+share how different are the binaries shipped by them on the GitHub releases, the ones downloaded from their website and the ones we build ourselves(maybe share/describe their CI process that builds those binaries). I am a Linux user and I cannot use something different other than the ones I build myself since the appimages are not working on my machine.

### Project file & Debug log uploads

None

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
Hello @astrolemonade 

the recent releases(v1.7.x) are all based on branch v1.7.2
and the related tags are also on branch v1.7.2

you can use branch v1.7.2 for your own buildings

we will update master branch's codes when next release v1.8 published
