### ISSUE TITLE
Bambu Studio thinks PETG in AMS is PETG-CF

### ISSUE THREAD

**Issue by gfalgiano** [bambulab/BambuStudio#2772]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

WINDOWS 10

### Printer

X1 Carbon

### How to reproduce

Print a PETG model with Generic PETG loaded in AMS. Bambu studio won't let you select the PETG in the AMS as it thinks it is PETG-CF. This is confirmed in the Device tab. If you select Generic PETG, it changes to PETG-CF

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/6590657/92d1ef63-efec-475d-82df-562e06694a6c)
![image](https://github.com/bambulab/BambuStudio/assets/6590657/81ad5283-0d76-4963-9fbf-de56ceebc6c0)
![image](https://github.com/bambulab/BambuStudio/assets/6590657/067da849-8ac6-4945-a671-9307b39eebc7)

### Expected results

I expect the ability to select an AMS slot with PETG loaded.

### Project file & Debug log uploads

[debug_Fri_Oct_20_22_07_18_20504.log.zip](https://github.com/bambulab/BambuStudio/files/13062243/debug_Fri_Oct_20_22_07_18_20504.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
@sodachen22 @StoneLiBambulab please check this issue

**Comment by bam-winterfell** [comment]
Hello @gfalgiano 
The user presets use the basic information of PETG, and the "Type" in "Basic Information" was modified to PETG-CF. This resulted in AMS being unable to distinguish between PETG and PETG-CF materials. The temporary solution is as follows:
1.Delete custom presets related to PETG-CF.
2.Modify the type corresponding to this preset
3.Version 1.8 will incorporate this fix

Wishing you a pleasant life.

**Comment by StoneLiBambulab** [comment]
There is a bug when getting the filament type, will be fixed in 1.8.xx

Thanks!
Stone Li
