### ISSUE TITLE
Skipping objects when using different filaments doesn't change filament

### ISSUE THREAD

**Issue by TheCableGuy99** [bambulab/BambuStudio#2776]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 Pro (all updates installed)

### Additional system information

CPU: i7-10750H
RAM: 32GB
NVM.E Drives

### Printer

Bambu Lab X1C

### How to reproduce

Load the attached 3mf into Bambu Studio
Select the print the 2 back "cage x2.stl" items in PLA
Select to print the others in another material
Select to print by "object"
Start the print
One of the cage's should start to print first
Cancel both the cages from printing when halfway through the first so it should change filament and start printing the axels

### Actual results

It skips the cages and goes to print the axels as it should but it doesn't change the filament.

### Expected results

It should change the filament and start printing the axels in the new filament as they were sliced to print in that different material.

It may also occur when printing by layer (if you can skip objects when printing by layer). I've never skipped objects before so not tested this way.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/13064021/log.zip)
[3mf.zip](https://github.com/bambulab/BambuStudio/files/13064024/3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
that’s been fixed in version 1.8. You can download the latest version for that.
