### ISSUE TITLE
增加支撐線寬參數 (Add support line width parameters)

### ISSUE THREAD

**Issue by Ryou-hakuketsu** [bambulab/BambuStudio#2779]
可以增加更改支撐線寬的設定嗎？
Can add settings to change the support line width?

預設線寬太厚很難移除
The default line width is too thick,they are difficult to remove.
![image](https://github.com/bambulab/BambuStudio/assets/148741350/da589411-29ac-450f-b770-403013c8f8ee)

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/11fdf672-6403-4262-9a9d-8884c0e59889)
打开支撑之后就能看到

**Comment by Ryou-hakuketsu** [comment]
原來在那邊
我一直在支撐那邊找
