### ISSUE TITLE
Upload to Makerworld ONLY option shown for disposition of sliced file

### ISSUE THREAD

**Issue by jcnrbl** [bambulab/BambuStudio#2795]
### Bambu Studio Version

1.7.7.89  1.7.7  1.7.6

### Where is the application from?

Bambu Lab github releases

### OS version

Fedora Linux 38

### Printer

not applicable

### How to reproduce

Run appimage
Import a model
slice plate

### Actual results

Impossible to send print to printer or export file to SD card.

### Expected results

Should see options to print or export sliced file

### Project file & Debug log uploads

Not applicable

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
Hello @jcnrbl 

could you give a snapshot of your issue

**Comment by jcnrbl** [comment]
This issue was due to a user error. Bambu Studio display image was not compatible with the system's display resolution IE: displayed image went beyond sright side of screen so that part of image was not displayed.

Issue closed.

**Comment by jcnrbl** [comment]
Issue closed.
