### ISSUE TITLE
Always Support in Negativ Forms

### ISSUE THREAD

**Issue by ac1dwalk3r** [bambulab/BambuStudio#2797]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Ryzen 9 3950X
32GB RAM
RTX3090

Problem also appears on Small Laptop and Gaming Laptop, all with Ryzen CPU's

### Printer

Bambulab X1 Carbon

### How to reproduce

1. Import a Model with Negativ Forms - Slicer Asks you if you want to import as model with several Parts. (in My case, the negatives were Cylinders with diameter of 6.25mm/height 6.25mm
2. Change Type of the Negativ Form in Object section.
3. Support to Auto(Normal)
4. Activate or Deactivate Bridges - No Difference
5. Duplicate the negative part File and import all 3 files at once. Set one to Negative Part, the Other to Supportblocker. Still Supports it.

### Actual results

Always fills the hole with Supportstructure - Quite Nasty if you want to put Magnets inside.
![grafik](https://github.com/bambulab/BambuStudio/assets/55549798/e29bfae0-1a86-4644-9a67-bd2e021cb48b)

### Expected results

Slicer should exclude negatives from support, or at least recognize that a bridge would be possible.

### Project file & Debug log uploads

[debug_network_Fri_Oct_27_07_14_26.log](https://github.com/bambulab/BambuStudio/files/13187505/debug_network_Fri_Oct_27_07_14_26.log)

project file to big, sorry.

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by tangketan** [comment]
It's difficult to diagnoze without 3mf file. I tried to duplicate your case with no success - the "Don't support bridge" option worked perfectly in my case. Check the attached 3mf.
[supports_in_negative_volume.zip](https://github.com/bambulab/BambuStudio/files/13237404/supports_in_negative_volume.zip)
