### ISSUE TITLE
Mac Bambu Studio - Camera displays frames out of order

### ISSUE THREAD

**Issue by dkuchta5** [bambulab/BambuStudio#2800]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Ventura 13.6

### Additional system information

2017 27” iMac with 4.2GHz Corei7
64GB Ram, 2TB SDD, 58TB external drives

### Printer

Bambu Lap P1S

### How to reproduce

1. Start a print
2. Watch Camera view in Device tab

### Actual results

The camera displays clearly impossible motion.  For example, when the print bed is moving up, one frame will display the bed in an upper position, the next frame shows it a few inches lower, then a few inches higher, then a few inches lower, etc.  It appears that the video stream has been split into two pieces, separated in time, and the frames of the two pieces are being show interleaved.

Note this does NOT happen with the Bambu Handy app, and it does not show up in the recorded Timelapse videos.  So it is clearly a bug in the Bambu Studio app, at least in the Mac version.  I've seen this behavior mentioned by others on the forum so it's not just happening to me.

Also ... I'm including some files because your form requires them.  But it happens with any project so the files don't really matter.

### Expected results

Video frames should appear in order of when they happened in time.

### Project file & Debug log uploads

[debug_Sun_Oct_29_09_47_53_47532.log.0.zip](https://github.com/bambulab/BambuStudio/files/13198334/debug_Sun_Oct_29_09_47_53_47532.log.0.zip)
[Project.3mf.zip](https://github.com/bambulab/BambuStudio/files/13198335/Project.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bambu123** [comment]
Resolved, please follow the prompts on Studio to update the plugin to 01.08.04.05.
