### ISSUE TITLE
Support Critical Regions Only with Raft

### ISSUE THREAD

**Issue by Jester7896** [bambulab/BambuStudio#2811]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1 Series

### How to reproduce

Enable Multiple Raft Layers
Enable Tree Support (Auto)
Check "Support Critical Regions Only"

### Actual results

![WDADesktopService_VAI6Fi5U8j](https://github.com/bambulab/BambuStudio/assets/74986301/2dfbb325-15b8-472c-9f50-b1d26e30afd1)
![WDADesktopService_PL0JG5CfJK](https://github.com/bambulab/BambuStudio/assets/74986301/49cb4360-34c1-4027-9c30-5df2071a500e)

### Expected results

It should slice

### Project file & Debug log uploads

[Blade 1.zip](https://github.com/bambulab/BambuStudio/files/13220736/Blade.1.zip)
[debug_network_Tue_Oct_31_15_31_05.log](https://github.com/bambulab/BambuStudio/files/13220747/debug_network_Tue_Oct_31_15_31_05.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by tangketan** [comment]
We have fixed the bug internally. Will release new version quite soon.

**Comment by tangketan** [comment]
Offical 1.8 has been released. Close this issue.
