### ISSUE TITLE
X1C printing size issue

### ISSUE THREAD

**Issue by Danish-Tool** [bambulab/BambuStudio#2817]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro, Ver. 22H2, Build 22621.2506

### Additional system information

CPU: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz   2.50 GHz
RAM: 16,0 GB

### Printer

Bambu Lab X1C

### How to reproduce

Open STL with drawing with a Z-axis height of more then 250mm

### Actual results

![Bambu - issue with print size](https://github.com/bambulab/BambuStudio/assets/149578901/9fb693c1-38ff-47c1-9afb-490c1c368cac)

### Expected results

Was expecting to be able to print 256mm
![IMG20231101113452](https://github.com/bambulab/BambuStudio/assets/149578901/c031207e-a1a0-4cf2-8047-99d02e84bb0f)

### Project file & Debug log uploads

I don't think log files is needed for this.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Witawat** [comment]
try https://wiki.bambulab.com/en/knowledge-sharing/print-volume-limitations
