### ISSUE TITLE
mac osx Bambu Studio 实时摄像头显示画面有问题

### ISSUE THREAD

**Issue by Fick707** [bambulab/BambuStudio#2818]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

OS:Mac OS 14.2 Beta (23C5030f)

### Printer

Bambu Lab P1S

### How to reproduce

打开Bambu Studio
点击“设备”tab
摄像头点“播放”
页面显示的不是正常画面

但手机端可以正常看到画面。

### Actual results

页面显示的不是正常画面

### Expected results

页面显示摄像头实时画面

### Project file & Debug log uploads

无

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Fick707** [comment]
![Uploading Screenshot 2023-11-01 at 23.35.52.png…]()

**Comment by Fick707** [comment]
![Uploading Screenshot 2023-11-01 at 23.35.52.png…]()

**Comment by bambu123** [comment]
老版本 1.7.3.50 是不是正常呢？[v1.7.3 (v1.7 Hotfix 2)](https://github.com/bambulab/BambuStudio/releases/tag/v01.07.03.50)

#2735

**Comment by bambu123** [comment]
@Fick707 请更新到 v1.8 版本。如果还有问题，请尝试重启打印机，等打印机网络准备好之后，播放，看看还有没有这个现象。

**Comment by bambu123** [comment]
已经解决，请在Studio上按照提示更新插件到 01.08.04.05
