### ISSUE TITLE
Missing "+" Button in German Interface 

### ISSUE THREAD

**Issue by Pledor1988** [bambulab/BambuStudio#2832]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambulab X1C

### How to reproduce

There is a missing "+" Button in Layer Height at the German Interface:
German:
![Screenshot 2023-11-03 175643](https://github.com/bambulab/BambuStudio/assets/149820708/e4fb3ede-89b5-4ca0-8f8a-d8d13683429f)
English:
![Screenshot 2023-11-03 175311](https://github.com/bambulab/BambuStudio/assets/149820708/9fa0c517-732a-4a35-a10e-51f6d18766b0)

### Actual results

Without that button, it is not possible to add some different layer settings in German Interface.

### Expected results

Add the "+" Button in German Interface at Height Modification (Höhenbereich Modifikator)

### Project file & Debug log uploads

Nothing needed. View screenshots

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
Hello,
this issue has been fixed in https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.57
