### ISSUE TITLE
Camera not working - Windows Media Player wants to be enabled, but it is

### ISSUE THREAD

**Issue by Osmodia666** [bambulab/BambuStudio#2839]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 22H2

### Printer

X1 Carbon

### How to reproduce

Open App. go to Camera Tab

### Actual results

Error Message " Windows Media Player is required for this Task!...."

### Expected results

Camera Feed should start

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/13257485/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

It is not possible to get a live stream via BambuStudio, it always shows the Error Message. Windows Media Player is enabled, but doesn't work. Also reinstalling BambuStudio and Windows Media Player doesn't help.

**Comment by Osmodia666** [comment]
![Unbenannt](https://github.com/bambulab/BambuStudio/assets/36590357/c65e9649-d30f-4e8f-a2e2-beaa381def4b)

**Comment by bambu123** [comment]
[Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~~.zip](https://github.com/bambulab/BambuStudio/files/13263733/Microsoft-Windows-MediaPlayer-Package.31bf3856ad364e35.amd64.zip)


The user's system version of MediaPlayer may not work, try this offline package. First delete the system's MediaPlayer, and then install it with the following command.

Dism.exe /Online /Add-Package /PackagePath:C:\Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~~.cab

**Comment by s3ppel** [comment]
Step 1: Type control panel in the Search bar, and then click the best match one to open it.

Step 2: Set View by: Small icons and then click Programs and Features.

Step 3: Click Turn Windows features on or off in the left panel. In the newly pop-out window, expand Media Features and check the box next to Windows Media Player. Read the message, click Yes and OK.

Step 4: Restart your computer

**Comment by Osmodia666** [comment]
> Step 1: Type control panel in the Search bar, and then click the best match one to open it.
> 
> Step 2: Set View by: Small icons and then click Programs and Features.
> 
> Step 3: Click Turn Windows features on or off in the left panel. In the newly pop-out window, expand Media Features and check the box next to Windows Media Player. Read the message, click Yes and OK.
> 
> Step 4: Restart your computer

Thank you, this worked fine.

**Comment by Majestic7979** [comment]
BambuLab, this is garbage. Why don't you fix your software instead of asking people to rely on LEGACY software? You have a state-of-the-art modern printer and you're relying on a no-longer-supported feature of WINDOWS 11!? HELLO! WMP is a relic from a bygone WinXP era. STOP ASKING USERS TO DO SILLY WORKAROUNDS FOR OUTDATED SOFTWARE.

**Comment by XeviaN360** [comment]
> BambuLab, this is garbage. Why don't you fix your software instead of asking people to rely on LEGACY software? You have a state-of-the-art modern printer and you're relying on a no-longer-supported feature of WINDOWS 11!? HELLO! WMP is a relic from a bygone WinXP era. STOP ASKING USERS TO DO SILLY WORKAROUNDS FOR OUTDATED SOFTWARE.

This.

**Comment by tordsta** [comment]
> Step 1: Type control panel in the Search bar, and then click the best match one to open it.
> 
> Step 2: Set View by: Small icons and then click Programs and Features.
> 
> Step 3: Click Turn Windows features on or off in the left panel. In the newly pop-out window, expand Media Features and check the box next to Windows Media Player. Read the message, click Yes and OK.
> 
> Step 4: Restart your computer

This worked for me as well, thanks!

**Comment by julie777** [comment]
I am using Windows 10 22H2 and there is no Windows Media Player. There is only Media features which is turned on.

<img width="406" height="597" alt="Image" src="https://github.com/user-attachments/assets/25a6f77e-1cbe-4f64-b5c2-9e34ae81896e" />

**Comment by bambu123** [comment]
Please use the latest version, which doesn't use WMP any more.
