### ISSUE TITLE
[bug 01.02.00.09] Bug when resetting tick boxes with "reset to saved value"

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#284]
Steps to reproduce:

Open Filament Settings
Change to "Cooling" tab
Untick a box
Change to "Filament" tab
Use main "reset to saved value" option

![image](https://user-images.githubusercontent.com/63362209/190493106-cef09460-9a11-49bf-ba50-90f2fae3c59e.png)

**Comment by YifanWuBambu** [comment]
Fixed in v.1.3.0.12.
