### ISSUE TITLE
After Slicing support interface is floating

### ISSUE THREAD

**Issue by mhwunder** [bambulab/BambuStudio#2851]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Mac 14.1

### Printer

P1P

### How to reproduce

Slice the model and there are floating support interfaces.  Not always but has happened.  I know this was an issue in a previous release that was fixed.

### Actual results

![Support Interface Floating](https://github.com/bambulab/BambuStudio/assets/100529364/b6e02e46-6916-4dee-90e1-a42ffe0b4650)

### Expected results

Support interface only where needed.

### Project file & Debug log uploads

[Floating Support.3mf.zip](https://github.com/bambulab/BambuStudio/files/13290344/Floating.Support.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by cRaZy92** [comment]
I have the same issue I think
![image](https://github.com/bambulab/BambuStudio/assets/33964772/22739941-a4a7-4ee8-bbff-0d79e47ccc5c)

With following support settings
![image](https://github.com/bambulab/BambuStudio/assets/33964772/8de6bc5f-7274-4b2e-aa34-6938ac14f1bf)

**Comment by mhwunder** [comment]
Try this test.  Uncheck "On buld plate only".  When I deslected that.  There were no more floating filament.  However, I also noted that it didn't put support interface in some places.  However, I am looking more into that to make sure it isn't just a branch needed for tree support.

<img width="794" alt="image" src="https://github.com/bambulab/BambuStudio/assets/100529364/4a36eb71-930a-4e83-a93a-40f26621baec">

**Comment by tangketan** [comment]
This bug has been fixed in the latest [1.8 beta](https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.57).

**Comment by tangketan** [comment]
Official 1.8 has been released. Close this issue.
