### ISSUE TITLE
Feature Request - Print with no outer wall / infill only

### ISSUE THREAD

**Issue by KuraiKitsune** [bambulab/BambuStudio#286]
I would like the ability to print spongy TPU structures with the Bambu X1. This is without having an outer wall, so the whole model is printed with just infill structure.

In the purpose case I've seen possible on Prusa's slicer software, an outer wall ideally made of denser infill pattern, with a less dense internal pattern.

Screenshot attached.
![Screenshot 2022-09-16 102135](https://user-images.githubusercontent.com/5255288/190604609-59434c63-73ad-4123-b6f8-bde41fedca0f.jpg)

**Comment by tangketan** [comment]
Seems making min value of wall count to 0 will just do.

**Comment by YifanWuBambu** [comment]
@KuraiKitsune 
The wall count is limited to larger than 1 currently. We will allow it to be 0 in the next release.

**Comment by KuraiKitsune** [comment]
Any idea on printing an outer wall out of more "infill"?
Or maybe the option to have 2 objects with different print settings on a single project?

**Comment by YifanWuBambu** [comment]
> 

@KuraiKitsune 
You may set per-object parameter by switching from "Global" to "Objects" mode on sidebar.
![image](https://user-images.githubusercontent.com/110661856/191395175-7b4eddcf-3450-4d42-91bb-1f13d13d0798.png)

User manul provides detailed introductions.
![image](https://user-images.githubusercontent.com/110661856/191395253-7e40b96c-c439-4e79-a0fd-99cb1c6a4904.png)

**Comment by SaltWei** [comment]
Done. Please wait for the next release

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.

**Comment by hella909** [comment]
> Any idea on printing an outer wall out of more "infill"? Or maybe the option to have 2 objects with different print settings on a single project?

So far, I was able to place slightly overlapping original design modifiers and set significantly denser infill on them. Say, if your design is rectangular, you will have to place 4 modifiers on all 4 sides. Nothing special, just smaller narrow rectangles. For unknown to me reason in my case I was able to produce much denser infill only on 2 out of 4 sides, but for me it was sufficient enough. Hope it'll help!

**Comment by hella909** [comment]
> > Any idea on printing an outer wall out of more "infill"? Or maybe the option to have 2 objects with different print settings on a single project?
> 
> So far, I was able to place slightly overlapping original design modifiers and set significantly denser infill on them. Say, if your design is rectangular, you will have to place 4 modifiers on all 4 sides. Nothing special, just smaller narrow rectangles. For unknown to me reason in my case I was able to produce much denser infill only on 2 out of 4 sides, but for me it was sufficient enough. Hope it'll help!

To be continued... :)
My bad! Just noticed that 2 of the modifiers were floating over the design, it's why I couldn't get all 4 sides print with denser infill. Problem solved! All 4 sides are printed as should, very dense, while the central part's infill is loose.

**Comment by cwale** [comment]
I believe this functionality may now no longer work? I'm trying to use modifiers to create holes in a part, but walls are still generated. Please see attached. I was expecting that I would be able to see holes in the 'Main Body' and directly into the infill, i.e. no wall loop on the modified section.
<img width="1303" alt="Screenshot 2024-01-18 205743" src="https://github.com/bambulab/BambuStudio/assets/30619671/4ef21f01-1d0b-475d-890f-d4441fa5fc1c">
<img width="1441" alt="Screenshot 2024-01-18 205843" src="https://github.com/bambulab/BambuStudio/assets/30619671/c946fed8-9694-46a8-ac45-cab1a768b2ba">

**Comment by BAMBU4U** [comment]
> Seems making min value of wall count to 0 will just do.

YES that works! You also have to ZERO TOP SHELL LAYERS and BOTTOM
![Region_71](https://github.com/user-attachments/assets/7daf586b-653a-4a69-be5c-1a42f5fef332)

**Comment by fuzzybusy** [comment]
Everyone I've asked says it's impossible to print a model with 0 walls (perimeters) using only Gyroid infill. Could you provide some insight on this? Is it actually possible to print it this way?
