### ISSUE TITLE
Annoying slicer tips - no way to close that immediately and most importantly no way to fully disable it 

### ISSUE THREAD

**Issue by arekm** [bambulab/BambuStudio#2861]
### Bambu Studio Version

1.08.00.03

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS 14.1.1

### Printer

Doesn't matter

### How to reproduce

1. Slice anything
2. Annoying things pops up

### Actual results

Big useless (for me) popup that cannot be disabled or even immediately closed. It covers a lot of space, even part of my model. I cannot do anything until timer for it finishes.

![image](https://github.com/bambulab/BambuStudio/assets/50869/ba6ba818-b5b8-4b88-805c-f82ce2e0ad78)

### Expected results

Two things:
1) ability to close that tip immediately
2) ability to turn off these annoying things

### Project file & Debug log uploads

Screenshot attached earlier.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DokuKaefer** [comment]
Same problem

**Comment by lanewei120** [comment]
we will optimize this logic 

currently, you can close this tips when slicing a bigger model, which will be also valid for all models
![image](https://github.com/bambulab/BambuStudio/assets/106916061/9b2f46c2-c5c2-4ec2-8213-2b6cdbbac056)

**Comment by kr0n1k01** [comment]
When will we be able to close these horribly obtrusive tips it stays on screen consistently. Why is there not a option to disable tips I seriously doubt users who are on betas want to see the tips pop up.

**Comment by 0rphon** [comment]
+1 to this. These tips could be useful to some people on their first few times printing, but are incredibly annoying to everyone else.

**Comment by b00lduck** [comment]
Please add an option to disable this permanently. Precious screen space is wasted.

**Comment by icheered** [comment]
These tips are really annoying, is there really no way to turn them off?

**Comment by SaltWei** [comment]
Use latest version and if can be collapsed.

**Comment by kr0n1k01** [comment]
> Use latest version and it can be collapsed.

Sorry this does nothing to address the issue as even collapsing it reappears and takes up screen space. Still don't understand why there is no checkbox to show or hide tips.
