### ISSUE TITLE
1.8.0 Custom filaments not avilable for calibration or in AMS selection

### ISSUE THREAD

**Issue by capsel22** [bambulab/BambuStudio#2862]
### Bambu Studio Version

1.8.0

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS

### Printer

P1S

### How to reproduce

1. Create new custom filament
2. Go to Calibrate and select manual calibration
3. Custom filament not available
4. Go to Device and edit AMS filament
5. Custom filament not available

### Actual results

Created filament using custom filaments 
![image](https://github.com/bambulab/BambuStudio/assets/38831192/2bdec2b1-5f03-4c31-a449-b48d20e099bc)

not available for calibration or AMS
![image](https://github.com/bambulab/BambuStudio/assets/38831192/25ac60af-0b89-4c03-8057-314cdcbe9188)
![image](https://github.com/bambulab/BambuStudio/assets/38831192/8794fe87-e98e-461b-9329-ee0dfbe8523a)

### Expected results

To be able to do the above steps.

If calibration or assigning to AMS is not supported i fail to understand what's the benefit of doing it the Custom Filament way over just saving filament with a different name.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by lanewei120** [comment]
Hello @capsel22 

this also needs a firmware update
the printer team will release a public Beta version soon

**Comment by rashuge** [comment]
Will this also be available for P1P/P1S and AMS?  I have the same issue.  I can create and configure the perfect filament profile but cannot actually calibrate or select in the AMS.  Very frustrating.

**Comment by walterwongbbl** [comment]
@rashuge 
After P1P/P1S support, we will release a new configuration file. With the update, you can use Custom fillments.
