### ISSUE TITLE
Fault when cutting a frame shaped object 90 degrees over X- or Y-axis (1.8.0.57)

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#2870]
### Bambu Studio Version

1.8.0.57

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Additional system information

AMD 5700G
64 GB Mem

### Printer

X1C

### How to reproduce

Load a simple and correct frame shaped object (stl)
Cut it over the X-or Y-axis at 90 or 270 degrees

![ss1](https://github.com/bambulab/BambuStudio/assets/53837649/6d3434fb-e707-4b93-95a5-dd1e4195c145)
![ss2](https://github.com/bambulab/BambuStudio/assets/53837649/c79b9099-09cb-4297-80c7-1d4adeeb746e)
![ss3](https://github.com/bambulab/BambuStudio/assets/53837649/f9164238-a320-4216-9a8c-9ffe1ccab2c0)
![ss4](https://github.com/bambulab/BambuStudio/assets/53837649/4ac6acfe-2ee2-49e3-ac97-6ff4956a56d6)

cutting at a different angle other then square seems to work correctly 

### Actual results

The 2 resulting shapes are faulty (non manifold)
slicing gives a faulty result
repairing the part does not work properly
(Rightclick on a part and "fix model" does work)

### Expected results

Cut correctly

### Project file & Debug log uploads

The project not cut yet
[test_cut_frame.zip](https://github.com/bambulab/BambuStudio/files/13325791/test_cut_frame.zip)
The stl of the simple frame
[testvb_stl.zip](https://github.com/bambulab/BambuStudio/files/13325793/testvb_stl.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by coat64** [comment]
When you move the cut, it seems the problem disappear.

**Comment by Haidiye00** [comment]
Model cutting appears popular edge, please first through this through the model repair, later we will fix the problem
![img_v3_0255_66e678f5-7d3f-4e0a-89ff-6af906e3591g](https://github.com/bambulab/BambuStudio/assets/132528822/53062e1e-39a1-4ca7-9659-7512f0e92184)
