### ISSUE TITLE
Provide option to turn off the tips that show up when slicing a plate in beta 1.8

### ISSUE THREAD

**Issue by sprior** [bambulab/BambuStudio#2875]
**Is your feature request related to a problem? Please describe.**

Pop up tips drive me nuts when I know what I'm doing, I want to turn them off and I don't see an option to do so.

**Describe the solution you'd like**
A checkbox on the pop up tips saying "don't show these again", maybe something in preferences in case someone changes their mind.

**Comment by LiZ-Li-BBL** [comment]
The latest version has added support fot this. https://github.com/bambulab/BambuStudio/releases/tag/v01.08.03.89
