### ISSUE TITLE
Correct the strings

### ISSUE THREAD

**Issue by AndylgTom** [bambulab/BambuStudio#2878]
Bambu Studio_v1.8.0 Beta

Please correct the strings in the screenshots. 
On the first screenshot - The string occurs in two places in different values. It would be more logical to name it "Share" at the top and write "Load" in the table model loading.
On the second screenshot, correct the writing of languages.
Thank you.
![01](https://github.com/bambulab/BambuStudio/assets/20997012/aac7bf86-3a79-449e-abb0-4d027d1e845d)
![02](https://github.com/bambulab/BambuStudio/assets/20997012/77e389c4-b96a-4c8c-a84c-f662c11c2419)

**Comment by DanBao-Bambu** [comment]
May I ask if the spelling of Ukrainian is accurate? The spelling displayed on Google is "Українська".

**Comment by AndylgTom** [comment]
> Українська

Yes, Украї**н**ська is correct
