### ISSUE TITLE
Selecting Generic ASA shows PC on AMS ext spool

### ISSUE THREAD

**Issue by CdRsKuLL** [bambulab/BambuStudio#2881]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

X1 Combo (AMS)

### How to reproduce

Go on device, select Generic ASA from the Ext Spool and it shows PC but if you select Bambu ASA, it shows ASA

### Actual results

Shows PC not ASA

### Expected results

To show ASA

### Project file & Debug log uploads

Nothing to upload

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @CdRsKuLL 
Please use new version.
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62

**Comment by walterwongbbl** [comment]
We have applied the latest version, please download the latest version to experience it.
