### ISSUE TITLE
AMS reads a PLA RFID tag correctly, but Bambu studio shows PETG-CF

### ISSUE THREAD

**Issue by JeffChapman** [bambulab/BambuStudio#2892]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro

### Printer

Bambu X1C

### How to reproduce

1. Load orange PLA-basic in slot 4 (Bought through Bambu)
2. AMS reads it as PLA (color orange) 
![PLA-Basic in slot 4](https://github.com/bambulab/BambuStudio/assets/5579468/8b4060ff-b5ee-46b8-a1fd-a3daf79b5ce3)
![RFID settings loaded for slot 4](https://github.com/bambulab/BambuStudio/assets/5579468/0950382a-bf72-4aba-9b3e-9b991c2d7c34)
3. Resync AMS in Bambu Studio
5. It correctly reads the filament as 'Bambu PLA Basic'
![bambu studio 1](https://github.com/bambulab/BambuStudio/assets/5579468/3bf2ce24-7a0c-4ad6-96f4-551c3acfecbf)
6. Go to print, and I can't select slot 4 as it doesn't match the sliced material
![bambu studio 2](https://github.com/bambulab/BambuStudio/assets/5579468/1ccf249c-8553-46e6-8562-d6a69308a7fe)

Notes: 
1. I have also tried debugging by trying slot 1/2/3, as well as loading a Support-PLA that came with the printer in hopes that it would refresh things somehow
![PLA-Basic in slot 1](https://github.com/bambulab/BambuStudio/assets/5579468/fc665c52-4970-4570-a845-abf5e9449d93)
![bambu studio 3](https://github.com/bambulab/BambuStudio/assets/5579468/c015d370-b889-417f-8631-e7fd3589418b)
![bambu studio 4](https://github.com/bambulab/BambuStudio/assets/5579468/4e33f580-e4b4-4652-a108-2d529045a45a)

2. I have a black PETF-CF loaded in slot 1, but removing it and tried the PLA-Basic in that slot as well to no avail 

### Actual results

Details above as well, but Bambu studio reads PLA-Basic RFID as PETG-CF.

### Expected results

Details above as well, but Bambu studio should be reading PLA-Basic as PLA-Basic so that I can select it when trying to print a PLA sliced model.

### Project file & Debug log uploads

[trays x5 colors project.zip](https://github.com/bambulab/BambuStudio/files/13367574/trays.x5.colors.zip)
[debug_Wed_Nov_15_11_57_18_9180.log.zip](https://github.com/bambulab/BambuStudio/files/13367584/debug_Wed_Nov_15_11_57_18_9180.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi. @JeffChapman 
Please use new version.
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62

**Comment by JeffChapman** [comment]
Latest version of BambuStudio fixes the issue, thanks!
