### ISSUE TITLE
Bambu Studio shows ASA instead of ABS in AMS when attempting to print

### ISSUE THREAD

**Issue by Kiwistylebuild** [bambulab/BambuStudio#2893]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1-C

### How to reproduce

Slot 1 in AMS selected as Generic ABS. 
![IMG_4639](https://github.com/bambulab/BambuStudio/assets/84456466/19f661e7-c615-45be-a7ed-347836abfe89)

Bambu Studio Resunc with AMS. Part selected as slot 1 Generic ABS.  
![IMG_4637](https://github.com/bambulab/BambuStudio/assets/84456466/a52a45b1-39fa-422a-a450-dd37e3cb5a3e)

Slice Plate. 
Print Pate.
![IMG_4636](https://github.com/bambulab/BambuStudio/assets/84456466/6b60b927-2199-4220-bae7-e7ec063d2276)

Shows unable to print due to slot 1 being ASA, not ABS

### Actual results

![IMG_4636](https://github.com/bambulab/BambuStudio/assets/84456466/6b60b927-2199-4220-bae7-e7ec063d2276)

Shows unable to print due to slot 1 being ASA, not ABS

### Expected results

Show ABS in slot 1

### Project file & Debug log uploads

[cap.zip](https://github.com/bambulab/BambuStudio/files/13367902/cap.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/13367915/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Kiwistylebuild** [comment]
I just setup a brand new x1c with two AMS and the same issue has happened.  It has labelled them all as ASA when trying to print.
![IMG_4658](https://github.com/bambulab/BambuStudio/assets/84456466/16ca8710-afa1-4f12-9e95-d2142ee140c2)

**Comment by walterwongbbl** [comment]
Hi.
Please use new version.
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62

**Comment by walterwongbbl** [comment]
We have applied the latest version, please download the latest version to experience it.
