### ISSUE TITLE
[Bug - UI, Win] Hover-over tips have a very small font size

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#29]
When hovering over an item, the text is very small in comparison to the rest of the interface, which isn't very good for accessibility.

![image](https://user-images.githubusercontent.com/63362209/179513627-ce431bb2-1c85-422d-ab87-69997c9ee955.png)

This should probably be the same font size - there's no shortage of space to make them larger.

01.00.10.05
Windows 11
21H2

**Comment by wuyifanfancy** [comment]
We will optimize the font size in recent release.

**Comment by YifanWuBambu** [comment]
Fixed in the latest version.
