### ISSUE TITLE
[v1.8 BETA] Allow conversion of old custom Filaments

### ISSUE THREAD

**Issue by Pmant** [bambulab/BambuStudio#2903]
**Is your feature request related to a problem? Please describe.**
I had a bunch of custom Filaments in Bambu Slicer prior to 1.8.0. I just started with a Generic profile (e.g. Generic TPU) and edited the profile to my needs, changed the Vendor Name. Example:
![grafik](https://github.com/bambulab/BambuStudio/assets/5005155/5afbd064-91bf-4c98-a6d4-843f64fb341c)

These profiles are still available in 1.8.0 but are not recognized as Custom Filaments, furthermore the Vendor is not an editable field anymore. When using the wizard to create new profiles I also cannot use these profiles as source.

**Describe the solution you'd like**
Either automatically convert 1.7.x profiles with custom vendor names to custom profiles in 1.8.0 or allow to convert them manually.

**Comment by QingZhangBambu** [comment]
i will talk to concerned staff about that.

**Comment by DanBao-Bambu** [comment]
Hello.
The Create Filament feature allows for the conversion of previous custom presets to third-party consumable presets.
The steps are as follows:
![image](https://github.com/bambulab/BambuStudio/assets/132529350/37c8d48d-d9fe-4bdb-a038-e23b369176fd)
After filling in the basic information, choose to create based on Filament Preset.
Select a custom configuration file that you want to convert. Click Create to succeed.
Note: Custom presets of the same type can only create one Filament under the same printer. If you have multiple custom presets of the same type, you can enter different serials to distinguish them.

**Comment by Pmant** [comment]
Thank you for the quick response.  This list does not show my old custom filaments:
![grafik](https://github.com/bambulab/BambuStudio/assets/5005155/55c45c25-c6b8-49ab-9c04-1b9152fb6181)

I noticed that beta 1.8.0 has its own settings distinct from 1.7.x and the profiles imported via cloud sync into 1.8.0. Maybe this helps debugging the issue.

**Comment by DanBao-Bambu** [comment]
Sorry, this is a known issue. The current 1.8Beta version relies on names to filter presets, and your preset name does not have a TPU, so it cannot be displayed. The next version will solve your problem. If you are in a hurry, you can first change the name of your preset to include the TPU field.

**Comment by Pmant** [comment]
That solves the issue, thank you.

**Comment by DanBao-Bambu** [comment]
Sorry, this issue is known and will be resolved in the next version.

**Comment by Pmant** [comment]
This is solved now if the old filament does have the filament type in it's name.
