### ISSUE TITLE
BBLStudio creates more layers of text than actually exist

### ISSUE THREAD

**Issue by NVNDO** [bambulab/BambuStudio#2905]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

CPU: Intel i7 7700K
RAM: 16GB DDR4 CL14
GPU: Nvidia RTX 2060

### Printer

Bambulabs P1S

### How to reproduce

1. Create a Coaster with 0.4mm deep text in Fusion 360 -> Import into BambuLabsStudio

![Screenshot (264)](https://github.com/bambulab/BambuStudio/assets/73851760/c143c3e9-b704-403a-8b64-e0069eb7609f)
![Screenshot (274)](https://github.com/bambulab/BambuStudio/assets/73851760/760adc2e-4fa7-4393-bd3a-81784c4aed83)

2. In "Prepare-mode" change color nr. 1 to white to make the entire coaster white. 
- Now paint only the coaster (top/side/bottom) and remaining spots in black with the Fill-tool.
- Go to "Preview"

![Screenshot (281)](https://github.com/bambulab/BambuStudio/assets/73851760/a14f9a78-6aa7-465b-9275-fb7989b2bf33)

### Actual results

In "Preview" 5 layers of text will be shown
![Screenshot (275)](https://github.com/bambulab/BambuStudio/assets/73851760/09514b12-7c7c-4d8d-ba91-1278b7dfc43d)
![Screenshot (276)](https://github.com/bambulab/BambuStudio/assets/73851760/af6b33ef-9f51-40f2-b47b-fe5d49b24b75)
![Screenshot (277)](https://github.com/bambulab/BambuStudio/assets/73851760/e0bb6a45-7c77-4ff9-b33e-616ba2713c0b)
![Screenshot (278)](https://github.com/bambulab/BambuStudio/assets/73851760/fd7c4d7a-b38b-4d38-a6fd-69ff99ae0e1b)
![Screenshot (279)](https://github.com/bambulab/BambuStudio/assets/73851760/dc371363-670b-4d99-ac0a-4eafb8a13add)
![Screenshot (280)](https://github.com/bambulab/BambuStudio/assets/73851760/c00ca0b9-6730-45e3-8a1b-73eaaa83334e)

### Expected results

Only 2 layers of text should be shown in white as the designed text is only 0.4mm high/deep and the layer height is set to 0.2mm (0.2+0.2=0.4 = 2 layer)

### Project file & Debug log uploads

[BBL NOT showing Text.zip](https://github.com/bambulab/BambuStudio/files/13385062/BBL.NOT.showing.Text.zip)
[debug_Fri_Nov_17_00_05_12_22212.log.zip](https://github.com/bambulab/BambuStudio/files/13385063/debug_Fri_Nov_17_00_05_12_22212.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@NVNDO 
After converting to a 3mf file, the text part is converted into coloring information instead of an independent text part.
So the embedded depth of the painted part is determined based on the paint logic.

**Comment by NVNDO** [comment]
Hey @zhimin-zeng-bambulab . going into objects and selecting a different color for each part works much better than painting and has also resolved the problem. 

I future objects that actually require painting, i will have in mind using a 3mf file.
