### ISSUE TITLE
涂色后切片没有颜色，仍显示单色

### ISSUE THREAD

**Issue by Hotinosin** [bambulab/BambuStudio#2909]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 11 23h2

### Additional system information

CPU：AMD 5600
GPU：RX6600

### Printer

P1P+AMS

### How to reproduce

涂色后切片，切片无颜色

### Actual results

<img width="1583" alt="iShot_2023-11-17_11 20 58" src="https://github.com/bambulab/BambuStudio/assets/87741985/e5050819-0787-4e0e-a86d-396a6896b71c">

### Expected results

<img width="1579" alt="iShot_2023-11-17_11 21 53" src="https://github.com/bambulab/BambuStudio/assets/87741985/999eef67-f390-4f75-a1ce-e7d88200804a">

### Project file & Debug log uploads

[bambu_scraper_grip_ams.3mf.zip](https://github.com/bambulab/BambuStudio/files/13386873/bambu_scraper_grip_ams.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Hotinosin** [comment]
上来看，发现1.8.0 Public beta发布了，安装1.8.0后，切片倒是有颜色了

**Comment by zhimin-zeng-bambulab** [comment]
这个BUG已经在 1.8.0 Beta 版本修复了
