### ISSUE TITLE
Change filament option disappeared

### ISSUE THREAD

**Issue by stephanieraymos** [bambulab/BambuStudio#2924]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Sonoma 14

### Additional system information

I was using the previous version of bambu studios on this mac, then updated it. The choose filament option was still there on a right click. But a few days later, it disappeared. That menu option is simply not there anymore. The filament that it defaults to is not the one I want to use for this model. I can't find any other way to change the filament. I have an AMS.

### Printer

X1 Carbon

### How to reproduce

Click into context menu where Choose Filament option is normally found at the bottom.
Notice it's not there..
<img width="758" alt="image" src="https://github.com/bambulab/BambuStudio/assets/58127737/15be8b71-4a65-4607-a132-83bd2b15066f">

### Actual results

No way to change filament

### Expected results

To be able to change filament

### Project file & Debug log uploads

no

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
Hello,
Please make sure the number of filament presets is greater than 1.
![image](https://github.com/bambulab/BambuStudio/assets/120457312/59a51741-b06f-4b16-b8c2-a1039e71462b)
You can directly click the "synchronize filament list from AMS" button.
