### ISSUE TITLE
Copy&Paste not working in text tool text input field

### ISSUE THREAD

**Issue by Geekay1972** [bambulab/BambuStudio#2929]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 14.0

### Printer

P1S

### How to reproduce

Open the text tool in bambu studio
You cannot paste text in the 'Input text' field, neither by shortcut nor from the Paste command in the menu.
<img width="405" alt="Screenshot 2023-11-20 at 21 43 42" src="https://github.com/bambulab/BambuStudio/assets/143263349/bbff1497-1541-424b-ba20-0e60ecb8c805">

### Actual results

simply not working

### Expected results

Should simply work.

BTW, the text alignment of the 'embedded depth' field is also wrong.

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
Have been fixed.
Get the latest version here https://github.com/bambulab/BambuStudio/releases/tag/v01.08.03.89
