### ISSUE TITLE
Invalid map error

### ISSUE THREAD

**Issue by LegacyOfBob** [bambulab/BambuStudio#293]
Sliced a file and this error message popped up:
"invalid map<K, T> key"

Bambu Studio now refuses to slice anything, needs to be restarted to resume working. 

![image](https://user-images.githubusercontent.com/106822310/190910617-3c577fde-9cbc-4727-82b5-025fa24203f1.png)

**Comment by SaltWei** [comment]
Could you please share the 3MF file for us to reproduce and debug ?

**Comment by LegacyOfBob** [comment]
Here is the 3mf file
https://drive.google.com/file/d/1PBbigty6BuD49wXxeE3QZOf6SQxPG-hN/view?usp=sharing

**Comment by ChrisG-hub** [comment]
I got no issues opening the file. Must be a local issue.

![image](https://user-images.githubusercontent.com/74129531/191412059-eb726948-8c5f-406f-ade9-7fee8a67ba70.png)

**Comment by zengzm1212** [comment]
@LegacyOfBob  I open the file and slice successfully. Could you provide your software version uesd to open the file.

**Comment by SaltWei** [comment]
Can't reproduce this issue and keep watching for a long time.
Close.
If it appears again, please report new ticket to us. Thank you very much!
