### ISSUE TITLE
File not slicing properly

### ISSUE THREAD

**Issue by wallymck** [bambulab/BambuStudio#2935]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz
12.0 GB ram
Radeon R550/550 series display adapter

### Printer

Bambu Lab PS1

### How to reproduce

1 Load .stl file
2 Place object on its flat side
3. slice object

### Actual results

Only dots appear in the preview pane.
Object will slice properly in Cura 5

### Expected results

Create printable file

### Project file & Debug log uploads

[bridges--covered-bridge--part1-back.zip](https://github.com/bambulab/BambuStudio/files/13433555/bridges--covered-bridge--part1-back.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by GuzziRaz** [comment]
The object is too thin to be rendered with default wall generator and 0.4 nozzle. If you switch wall generator to Arachne you'll get a perfectly fine slice.

**Comment by wallymck** [comment]
Thank you.
