### ISSUE TITLE
Bambu slicer bug on home screen

### ISSUE THREAD

**Issue by P2012** [bambulab/BambuStudio#294]
![Untitled9](https://user-images.githubusercontent.com/113454568/190910983-c59d5a7f-d325-4174-b0d0-16a1775cd41b.jpg)
On the home screen you see this as pic when i click on anyone of them i have an error message appear error 1155

**Comment by bambu123** [comment]
Can you open urls such as "https://github.com/bambulab/BambuStudio/issues/294" from Windows Startup？
![image](https://user-images.githubusercontent.com/112537880/191403262-9cbd91f2-2373-42ab-827c-1ad47a6a5602.png)

**Comment by P2012** [comment]
![Untitled10](https://user-images.githubusercontent.com/113454568/191480987-d8215496-20e8-4941-aa8c-0f6f9a5c4e0c.jpg)
My startup folder is empty

**Comment by bambu123** [comment]
No, it is not the startup folder.
I mean the Windows Run Dialog as shown previously.
You press Win + R， to invoke this dialog， and then input an HTTP URL to open. Can it be opened?

**Comment by P2012** [comment]
Hi i done this and it just makes the screen bigger.

PAUL DANCE Director
________________________________
www.diamondhlifting.co. <http://www.diamondhlifting.co.uk>uk
0800 022 4475

**Comment by bambu123** [comment]
I think there are no web browsers that can process HTTPS URLs on your computer.
Have you installed chrome?

**Comment by P2012** [comment]
Hi no i am using normal google shall i install chrome?


PAUL DANCE Director
________________________________
www.diamondhlifting.co.uk
0800 022 4475

**Comment by bambu123** [comment]
@P2012 Have the problem been solved?

**Comment by P2012** [comment]
Yes all working

Thanks

PAUL DANCE Director
________________________________
www.diamondhlifting.co.uk
0800 022 4475
