### ISSUE TITLE
Supports working bad on new beta versions 1.8+

### ISSUE THREAD

**Issue by dalet11** [bambulab/BambuStudio#2945]
### Bambu Studio Version

1.8+

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Printer

X1C

### How to reproduce

Im using PLA support for the interface, and the behavior of the support is very different and kinda results in a failure.

See the picture below, the top one is printed with a stable version, second with beta. support interface was impossible to remove, and also looked weird..
![תמונה](https://github.com/bambulab/BambuStudio/assets/519368/e2bf25f8-cd52-4846-b911-b3d925571774)

**_see how it looks on the slicer:_**
NEW 1.8+ line 26+30:
![תמונה](https://github.com/bambulab/BambuStudio/assets/519368/caad383b-ab31-48ae-95e0-0028f0536443)
![תמונה](https://github.com/bambulab/BambuStudio/assets/519368/c6b44a73-199b-4f3d-a7be-4d0a2c337ee5)

**OLD stable  line 26+30:**
![תמונה](https://github.com/bambulab/BambuStudio/assets/519368/e0883354-06ad-48e2-8265-58ebeea19ca2)
![תמונה](https://github.com/bambulab/BambuStudio/assets/519368/4eaeda49-0c83-490b-847c-09605eb35b2a)

It's missing some interface layer between the support and the support PLA material, they also look out of alignment at the new version.

### Actual results

very bad support, causing failure of the print.

### Expected results

I expect the supports to look like on the stable version, or better.

### Project file & Debug log uploads

[support issues.zip](https://github.com/bambulab/BambuStudio/files/13452433/support.issues.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
Yes, it's a bug. Will fix it soon. Thanks for reporting.

**Comment by tangketan** [comment]
Offical 1.8 has been released and this bug is fixed. Close this issue.
