### ISSUE TITLE
IRONING DIRECTION / ANGLE 

### ISSUE THREAD

**Issue by andrei030700** [bambulab/BambuStudio#2950]
**Is your feature request related to a problem? Please describe.**
Ironing direction is not present int the Bambu slicer software. as us can see in the screenshot 
![image](https://github.com/bambulab/BambuStudio/assets/151539503/80ea4466-02f2-4b1c-8f77-59745a976b24)
Also this feature is presented in the Bambu lab wiki as u can see 
![image](https://github.com/bambulab/BambuStudio/assets/151539503/36bba4a1-ed2b-4adc-b38a-916b4c0b1dfd)

**Describe the solution you'd like**
To implement back this feature in the slicer 
**Describe alternatives you've considered**
to be able to set my ironing direction. 

Thank you!

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/17b0bf9b-8a9b-4f2c-9e08-898d44ff5432)
open develop mode then you can see ironing direction

**Comment by andrei030700** [comment]
Hi
I did check the developer mode on, and I saw other functions appearing, but not the IRONING DIRECTION.
Is there something else that i can do?
![image](https://github.com/bambulab/BambuStudio/assets/151539503/be4ca291-2a02-4b66-8677-6b1fe484b9f6)

**Comment by SaltWei** [comment]
> Is there something else that i can do?

Use the latest version on github. It's now included in beta version
