### ISSUE TITLE
Mac Pro 2013 video is blue/green lines or sometimes blinking

### ISSUE THREAD

**Issue by smolz** [bambulab/BambuStudio#296]
Just got my printer and install the slicer on my 2013 Mac Pro. When I go to the device screen and start the video stream I get what is in the [screenshot](https://imgur.com/a/TXCPIar).  If I move the app around the screen the stream will display in quick flashes with it alternating between the lines and the video.  The video seems to also be really sped up.  My installation on a new MacBook Pro with M1 seems to be okay and the Handy app seems ok.
<img width="1977" alt="Screen Shot 2022-09-18 at 1 41 07 PM" src="https://user-images.githubusercontent.com/3820601/190927673-c22262ac-1164-4447-bd15-4360e52edef1.png">

**Comment by bambu123** [comment]
Thank you for your report. I'll find it out.

**Comment by smolz** [comment]
As another data point.  https://www.reddit.com/r/BambuLab/comments/y4wvm5/camera_feed_in_studio_broken/

**Comment by bambu123** [comment]
Have you tried the new version of BambuStudio?

**Comment by smolz** [comment]
Assuming the latest version is 01.02.00.09, then it is the same.
![Screen Shot 2022-10-18 at 8 29 11 AM](https://user-images.githubusercontent.com/3820601/196475671-6ee9d4a9-20a0-46de-9f93-c3bc03d9cd83.png)
<img width="1748" alt="Screen Shot 2022-10-18 at 8 29 26 AM" src="https://user-images.githubusercontent.com/3820601/196475683-917f1a2f-8beb-45db-95e8-2f43aeb02ad2.png">

**Comment by smolz** [comment]
Version 1.03.00.12 works sometimes for several seconds and then either freezes or shows green

**Comment by bambu123** [comment]
What's the OS version? It seems to be the problem with the hardware video decoder. Could you update your macOS?

**Comment by smolz** [comment]
> What's the OS version? It seems to be the problem with the hardware video decoder. Could you update your macOS?

12.6.1 - latest Monterey.  Looks like there was a new release this week of studio (1.03.00.12).  This appears to be much better, then the previous version.  Not perfect but the video appears to be good 90+/- %.  There are now occasional flashes of green or lines, and occasionally frozen video for a second, but is for the part at least useable.

**Comment by bambu123** [comment]
@smolz Does the recent 1.4.2 version has some problem?
If it does, please send some pictures or videos to show the problem.

**Comment by smolz** [comment]
Attached is a quick screen recording. It overall seems better as it is not always as shown.  It comes and goes for whatever reason.
https://user-images.githubusercontent.com/3820601/216916498-9640a823-a48f-4422-bc4b-3b28676bf777.mp4

**Comment by bambu123** [comment]
@smolz Thanks very much. It's helpful.

**Comment by bambu123** [comment]
Resolved, please follow the prompts on Studio to update the plugin to 01.08.04.05.
