### ISSUE TITLE
Fatal Error afer installation Public Beta 2 on Windows 11

### ISSUE THREAD

**Issue by gabber130779** [bambulab/BambuStudio#2983]
### Bambu Studio Version

1.8.0 public beta 2

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Additional system information

Intel core I7 9th Gen

### Printer

P1P

### How to reproduce

Install Public Beta 2 on Windows 11

### Actual results

![Fatal Error](https://github.com/bambulab/BambuStudio/assets/108513101/9f77205a-c57b-4eee-92c0-0c283907f306)

### Expected results

Bambu Studio should run

### Project file & Debug log uploads

di

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@gabber130779 it seems the config files corrupted on your local directory

could you clear these folder and files and retry again
![image](https://github.com/bambulab/BambuStudio/assets/106916061/d491e90a-e5cc-49e3-986a-87da68591e5f)

**Comment by gabber130779** [comment]
Okay, that's it. Thanks.
