### ISSUE TITLE
language help

### ISSUE THREAD

**Issue by osmanoney** [bambulab/BambuStudio#2990]
orca slicerde bu mevcut varken bambu studio türkçe dil desteği ne zaman gelecek ?

**Comment by walterwongbbl** [comment]
@lanewei120

**Comment by lanewei120** [comment]
@osmanoney 

Hi 
I am afraid we have limited resources
maybe we can wait someone from community to help to add this support

the detailed guide can be found here
https://wiki.bambulab.com/en/bambu-studio/contribute-languages

**Comment by lanewei120** [comment]
there are also lots of difference between these two,
we can not use the languange files directly

**Comment by osmanoney** [comment]
> bu ikisi arasında da çok fark var, dil dosyalarını doğrudan kullanamıyoruz

Türkiyede 100 lerce bambu lab kullanıcısı var bu konuyuı hızlı bir şekilde çözümlenirse çok sevinirim. ben bile 1 adet le başladım çoğaltmayı düşünüyorum. dil sorunum var yaş 54 çok zorlamnıyorum.

**Comment by alper38k** [comment]
Türkiyede bambu çok seviliyor yüzlerce değil binlerce kullanıcısı var acilen dil desteği gelmeli hem cihazlarımıza hemde Bambu lab stuio ya Türkçe dil desteği istiyoruz

**Comment by lanewei120** [comment]
just found someone have added it into github
https://github.com/bambulab/BambuStudio/pull/3778

we will follow up

**Comment by fatih5228** [comment]
GitHub'a bir çekme isteği gönderdim ve bunun tamamlanmasını bekliyorum. Dün 01.09.00.60 beta sürümüne güncelledim.

**Comment by fatih5228** [comment]
@alper38k @osmanoney Biraz daha sabır, gereken Türkçeleştirme yapıldı onay bekliyor. Beta sürüme gelmesini çok isteerdim malesef onaylanmadı. Github da işler malesef biraz yavaş ilerliyor

**Comment by lanewei120** [comment]
@StoneLiBambu is processing
it will be in next version

**Comment by osmanoney** [comment]
şimdiden emeği geçen herkese şükranlarımı iletiyorum. Bamnu ailesinde olmaktan keyif alıyorum.
