### ISSUE TITLE
[Bug, UI / Win] Object/part setting can be resized, without scroll bar. Reopening does not correctly revert.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#30]
You can resize the Object/Part window, but no scroll bar appears when you do.
![image](https://user-images.githubusercontent.com/63362209/179515164-41ce92d9-a43f-47e8-9623-b81cb921cb18.png)

After resizing, if you close and re-open it, the content seems to remember your last size in some manner.
![image](https://user-images.githubusercontent.com/63362209/179515201-ca6995e9-be38-4a77-86c3-71c3ad70f872.png)

Restarting the software reverts the content size.

01.00.10.05
Windows 11
21H2

**Comment by wuyifanfancy** [comment]
The Object/Part table has not been developed yet. We will fix the  in the subsequent development process.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/233517351-450cbacd-0bfa-403d-8b4d-024132511399.png)
should be OK one latest 1.6 public beta
