### ISSUE TITLE
[Feature Request] Remember last used build plate

### ISSUE THREAD

**Issue by ptyork** [bambulab/BambuStudio#300]
Currently BambuStudio defaults to the Cool Plate for every new model. It should instead default to the last used build plate. Or at the very least this should be a configurable option (e.g., default build plate: cool / hot / ... / last used). Another potential option would be to allow this default to be set on a material by material basis.

**Comment by YifanWuBambu** [comment]
@ptyork 
Thanks for the suggestion.
We weill change its default value to the last used build plate.

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.
