### ISSUE TITLE
Black filament too dark in slicer.

### ISSUE THREAD

**Issue by MrBanana02** [bambulab/BambuStudio#3003]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Lenovo thinkpad x13s 

### Printer

Bambu Labs X1C w/AMS

### How to reproduce

The issue is that I have yet to be able to see my model when filament selected is black. This appears as one solid black spot on my screen and the other monitors I have tried. I have to change filament to some other color just to see the model, then switch it back. Black needs to be a little less black for visibility, or an option to change lighting, or to highlight edges. 

### Actual results

N/A

### Expected results

N/A

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Gnuclear** [comment]
I usually change the color in the AMS because of this (luminance ~40 at least), because technically you can tell the AMS it's any color you want, it's not like it changes the actual color of the filament.

**Comment by lanewei120** [comment]
@capsel22 @MrBanana02 have you tried the [beta 2 version](https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62)
we should already improved this logic

**Comment by MrBanana02** [comment]
> @capsel22 @MrBanana02 have you tried the [beta 2 version](https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62) we should already improved this logic

I just tested this, and it looks phenomenal! Thank you so much!!!
