### ISSUE TITLE
Cannot print using generic PETG in AMS

### ISSUE THREAD

**Issue by Gnuclear** [bambulab/BambuStudio#3005]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

Ryzen 5950X, Radeon 6900 XT, 128GB RAM

### Printer

Bambu P1S

### How to reproduce

Load PETG filament into AMS
Configure AMS with Generic PETG profile
Select PETG as material in Bambu Studio
Go to slice and print
![petg bug](https://github.com/bambulab/BambuStudio/assets/130479976/fd5bd407-1a36-48a2-8fb6-e2126727d5a2)

### Actual results

Unable to print with PETG in AMS at all

### Expected results

Well, I should be able to actually select and print with PETG

### Project file & Debug log uploads

[Knight.zip](https://github.com/bambulab/BambuStudio/files/13518662/Knight.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi.@Gnuclear 
Please use this version, our official version 1.8 will be released soon.
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.00.62
