### ISSUE TITLE
Collision warning on sunk models 

### ISSUE THREAD

**Issue by TennisRunner** [bambulab/BambuStudio#3007]
### Bambu Studio Version

1.6.2.4

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu p1p

### How to reproduce

I got two long models and sunk them down to the sections I want to print to test if they fit. 

### Actual results

It looks like its calculating the collision detection based on the model's actual height rather than its new recalculated height based on being sunk into the ground. 
![87WOAc7 1](https://github.com/bambulab/BambuStudio/assets/59356546/f2deb325-2c29-4345-b820-0318a3718237)

### Expected results

It should calculate the collision based on the current model position and allow the print to go through.

### Project file & Debug log uploads

[another bug.zip](https://github.com/bambulab/BambuStudio/files/13519604/another.bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lanewei120** [comment]
1.9已经修复
