### ISSUE TITLE
menu device hms every white 

### ISSUE THREAD

**Issue by magicozero** [bambulab/BambuStudio#3009]
### Bambu Studio Version

last official and last beta

### Where is the application from?

Bambu Lab github releases

### OS version

windows 11

### Additional system information

microsoft surface pro 7 

### Printer

bambu lab x1 carbon

### How to reproduce

launch app bambu studio
device menu 
hms menu
white no see nothing

### Actual results

![bambu studio hms every  white bug](https://github.com/bambulab/BambuStudio/assets/79002579/fbe5508f-8ef0-41a4-b53e-ea2c1584f5cb)

### Expected results

no see nothing other function is ok and bambu handy on cellular ams work

### Project file & Debug log uploads

[debug_network_Thu_Nov_30_17_15_24.log](https://github.com/bambulab/BambuStudio/files/13522197/debug_network_Thu_Nov_30_17_15_24.log)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bam-winterfell** [comment]
hi @magicozero 
The HMS page only displays the printer's prompts on the studio. If there is no prompt message from the printer, the HMS page will be blank

**Comment by bam-winterfell** [comment]
@magicozero If you have any other questions, please open a new issue.
