### ISSUE TITLE
[Enhancement] Allow reporting of Incorrect First Layer Scan

### ISSUE THREAD

**Issue by ptyork** [bambulab/BambuStudio#301]
The first layer scan is quite...imprecise. I have experiences numerous false positives and false negatives. Let us help you improve its accuracy. When the print pauses, have three options (something like): Resume No Issues, Resume Despite Issues, Cancel Print. If Resume No Issues is selected, send the scan diagnostic data to Bambu to use as a false positive case. Likewise, when we cancel a print after the first layer scan (especially within the first couple of layers), you could include this scan data along with a phone-home report. Maybe even have a secondary dialog after the "report" button press asking for a reason (unspecified, bad first layer, skipped steps, etc.) and customize the data you receive accordingly.

**Comment by YifanWuBambu** [comment]
@ptyork 
Thanks a lot. It will be supported in the next firmware release.
