### ISSUE TITLE
HMS tab displays blank warnings

### ISSUE THREAD

**Issue by labatt** [bambulab/BambuStudio#302]
In slicer 1.02.00.09, when you go to Device > HMS, the badge is shown but the text is not.

![image](https://user-images.githubusercontent.com/1585224/191171893-6c1d692d-345e-4c3b-9bb0-63942f34f43e.png)

**Comment by StoneLiBambulab** [comment]
Hi labatt,
       Thanks for your feedback. And could you send us the Bambu Studio logs so we can check if there's something wrong there. The files can be accessed on this location:
C:\Users\user.name\AppData\Roaming\BambuStudio\log

BambuLab Studio Team

**Comment by OmiCron07** [comment]
The release notes say that the bug is fixed, but is still there in the latest version:

![image](https://user-images.githubusercontent.com/31325575/197006427-d90ec358-9707-4cbc-b3df-b56e68f4b01a.png)
