### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by Bexxx78** [bambulab/BambuStudio#3031]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab A1 Mini

### How to reproduce

1. I open the Program
2. I would like to log in
3. The  Screen is white
4. The solution with the change of language, not working for me
![screen1](https://github.com/bambulab/BambuStudio/assets/137331240/4ab5c5db-3efb-4a9c-94fb-20499a4d2155)
![screen2](https://github.com/bambulab/BambuStudio/assets/137331240/0fff8c92-758f-491f-bb62-5aa586cf5919)

### Actual results

The  Screen is white, i cant login

### Expected results

...

### Project file & Debug log uploads

[Dateien.zip](https://github.com/bambulab/BambuStudio/files/13550153/Dateien.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
The problem is that the network plugin is not installed. Click on the Device page, follow the prompts to install the plugin, and then try logging in again.

**Comment by Bexxx78** [comment]
Habe jetzt die

**Comment by Bexxx78** [comment]
Actually I installed the plugin...strange.

I installed the other version of the program, this helped

Thanks
