### ISSUE TITLE
Typo in Print Options screen

### ISSUE THREAD

**Issue by thomsonOZ** [bambulab/BambuStudio#3033]
### Bambu Studio Version

1.8.0.57

### Where is the application from?

Bambu Lab github releases

### OS version

WIndows 11

### Printer

A1 Mini

### How to reproduce

Printer Options Screen

It should be Filament Tangle Detect

### Actual results

It shows Fliament Tangle Detect

### Expected results

Filament Tangle Detect

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DanBao-Bambu** [comment]
Thank you for raising the issue, we will fix it as soon as possible.
