### ISSUE TITLE
Auto Arrange Does Not Center Object On Plate With A1 Mini Selected

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#3037]
### Bambu Studio Version

1.8.1.57

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

10th Gen Core i5 32GB

### Printer

A1 Mini

### How to reproduce

Select A1 Mini as printer
Add a cube primitive
Select auto arrange icon on plate

### Actual results

Object moves to x125.6, y90
![image](https://github.com/bambulab/BambuStudio/assets/96731892/675c1f14-9936-41df-865c-96824a48fb14)

### Expected results

Object should move to x90 y90. It looks like it is centering for the X/P series plate.

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
This is a feature. For A1 mini, it is better to put objects near the Z rod (higher stability). You can change the default position
![image](https://github.com/bambulab/BambuStudio/assets/13730459/f6ec7cc3-7333-4b68-beeb-f2905d53a9d5)

**Comment by MadMax389** [comment]
Perfect! Thank you. I had not noticed this setting before. I am closing this issue.
