### ISSUE TITLE
Request to add checkbox to print send screen for time-lapse 

### ISSUE THREAD

**Issue by JPotter73** [bambulab/BambuStudio#304]
Right now I have to turn on time-lapse when slicing. I'd much prefer to decide when printing at the dialog in Studio or on the touchscreen. 

Configuration in Studio is great, but I may want to reprint and not use up limited space on the SD card each reprint.

**Comment by YifanWuBambu** [comment]
@JPotter73 
Thanks for the suggestion.
We will add a print option for each job.

**Comment by JPotter73** [comment]
I see the checkbox on the print screen now! Thanks!
