### ISSUE TITLE
Missing "Brim-object gap" in latest 1.8 beta version?

### ISSUE THREAD

**Issue by charleyzhuyi** [bambulab/BambuStudio#3047]
### Bambu Studio Version

1.8.1.57

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

A1 Mini

### How to reproduce

1. Open Bambu Studio
2. go to "Others" Tab
3. Check out "Bed Adhesion" section

### Actual results

Missing "Brim object Gap" field in 1.8.1.57

<img width="317" alt="Screenshot 2023-12-06 181703" src="https://github.com/bambulab/BambuStudio/assets/2998336/6f86067e-cdbb-4518-82f5-09522182471b">

### Expected results

Should have "Brim-object gap" per https://wiki.bambulab.com/en/software/bambu-studio/auto-brim
<img width="301" alt="Screenshot 2023-12-06 182606" src="https://github.com/bambulab/BambuStudio/assets/2998336/f0a790be-ac9a-4f20-9acc-5d2a92b4ceda">

### Project file & Debug log uploads

[Falcon Heavy Launcher individual(3).zip](https://github.com/bambulab/BambuStudio/files/13594085/Falcon.Heavy.Launcher.individual.3.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
the object gap option is visual on the develop mode
![image](https://github.com/bambulab/BambuStudio/assets/112676417/813e98f6-ea09-4662-b6b1-f604dfcda6a6)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/49e791ae-7c64-4e15-acf4-82853f3be68d)
![image](https://github.com/bambulab/BambuStudio/assets/112676417/a6d39028-02fe-4416-9ec9-002bd372cdb9)

**Comment by QingZhangBambu** [comment]
i check the version 1.8.1.57, the object gap option is visual
![image](https://github.com/bambulab/BambuStudio/assets/112676417/0ed8280f-de79-4d85-9ba6-fffbf783b9e2)
if you don't mind, could you upload log file to help us check what happened?

**Comment by bambu123** [comment]
@charleyzhuyi You need to select "Advanced" mode to see this parameter.
