### ISSUE TITLE
painting tool not available

### ISSUE THREAD

**Issue by waldell** [bambulab/BambuStudio#3049]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sonoma 12.1.1

### Additional system information

MacBook PRO
Apple M1 Max
64 GB memory

### Printer

Bambu Lab X1 Carbon

### How to reproduce

Add a model to plate. 

### Actual results

I should be able to paint the model that is on the plate.

### Expected results

Paint tool not available. Cannot get it to show no matter what I do.

### Project file & Debug log uploads

[Archive.zip](https://github.com/bambulab/BambuStudio/files/13598104/Archive.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file
![Screenshot 2023-12-07 at 10 16 28](https://github.com/bambulab/BambuStudio/assets/10948567/d338cc9c-e1c5-4530-b60f-2f983b827da3)

**Comment by Schokobecher** [comment]
You cannot paint anything if there's only one material loaded/added to your list. Press the **+** next to the _Flushing Volumes_ button.

With multiple filaments:
![CleanShot 2023-12-08 at 04 14 46@2x](https://github.com/bambulab/BambuStudio/assets/1642634/b8a5fdd1-a955-4bf5-a724-b43cafa79b05)

With only one:
![CleanShot 2023-12-08 at 04 16 04@2x](https://github.com/bambulab/BambuStudio/assets/1642634/80763878-cbed-4acb-a850-6104c3c45f0c)

**Comment by waldell** [comment]
You are right, this is working.. my mistake.
