### ISSUE TITLE
[Bug] - Unable to edit Project Specific information anymore

### ISSUE THREAD

**Issue by ondrovic** [bambulab/BambuStudio#3050]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

OS: Windows 11

### Additional system information

![image](https://github.com/bambulab/BambuStudio/assets/3682042/c691ecdd-9b78-4fb2-9830-236b3b1324d6)

### Printer

BambuLab X1C / A1 Mini

### How to reproduce

1. Add files .stl / .3mf into bambu studio
2.  Make your adjustments
3.  Goto Project Tab
     * observe there is no way to add project details
4. Click on save project / save project as
5. save file
6. Re open the project in BambuStudio
7. Goto Project Tab
    * observe there is no usable information present and you cannot add any
    * observer you can also no long even click on the Accessories or Profile information items

![existing project](https://github.com/bambulab/BambuStudio/assets/3682042/b0b2819e-4355-48d5-9c4c-b65183b03d3a)
![new project bs](https://github.com/bambulab/BambuStudio/assets/3682042/f85122ae-b362-4d9b-9a48-6bbf5de973e6)

### Actual results

Unable to add any relevant project information, I know this wasn't the case as you could do it but it seems like the functionality broke some revisions ago. 

### Expected results

Ability to add all relevant model information, accessories and profile information in bambu studio, note these should be used when we upload models to maker world and it should pull / respect the information that is in the project file.

### Project file & Debug log uploads

[Window Buttons.zip](https://github.com/bambulab/BambuStudio/files/13602560/Window.Buttons.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/13602574/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by AxelDreher** [comment]
It´s absolutly anoying that the Projekt Page is broken since v1.6.xx!
I will never upload any Projekt until this is fixed.

**Comment by walterwongbbl** [comment]
Hi. @ondrovic 
Please use our online model store
https://makerworld.com/en

**Comment by walterwongbbl** [comment]
@AxelDreher 
Please use our online model store.
https://makerworld.com/en

**Comment by walterwongbbl** [comment]
there is already another feature that addresses the same content as you mentioned. This issue will be closed.
