### ISSUE TITLE
windows media player required,  but it is installed

### ISSUE THREAD

**Issue by btiplitz** [bambulab/BambuStudio#3059]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windos 11

### Printer

Bamboo Carbon X1

### How to reproduce

On Device page, press the start to play the live camera feed

### Actual results

Prompt appears saying "windows media player is required for this task".  The legacy windows media player is already installed

### Expected results

Should see a vide, but i have the option of OK or cancel

### Project file & Debug log uploads

This is project independent

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by btiplitz** [comment]
I uninstalled and re-installed the legacy media player and it gives the same error

**Comment by bambu123** [comment]
> I uninstalled and re-installed the legacy media player and it gives the same error

Can Windows Media Player play video files?

**Comment by bambu123** [comment]
> > I uninstalled and re-installed the legacy media player and it gives the same error
> 
> Can Windows Media Player in your system play video files?

**Comment by btiplitz** [comment]
did the reinstall again after a reboot.  The installed failed multiple times, but then I used the command prompt to install
dism /online /add-capability /capabilityname:media.WindowsMediaPlayer~~~~0.0.12.0

now it works

**Comment by bambu123** [comment]
> did the reinstall again after a reboot. The installed failed multiple times, but then I used the command prompt to install dism /online /add-capability /capabilityname:media.WindowsMediaPlayer~~~~0.0.12.0
> 
> now it works

Thanks for the feedback!

**Comment by adf1969** [comment]
Do you know how much I HATE having to "reboot" every time I install/uninstall EVERYTHING...WMP was ALREADY installed, so I uninstall, then it says "needs a reboot". Windows is trash.
WHY can't Bambu/Slicer allow us to SELECT the player...obviously you can't rely on WINDOWS to do it...since Windows is incompetent at such tasks...
Pathetic.

**Comment by bambu123** [comment]
The new version of Studio no longer uses WMP.

> From: ***@***.***>
> Date:  Thu, May 1, 2025, 09:34
> Subject:  Re: [bambulab/BambuStudio] windows media player required,  but it is installed (Issue #3059)
> To: ***@***.***>
> Cc: ***@***.***>, ***@***.***>
> [image: https://avatars.githubusercontent.com/u/1043128?s=20&v=4]adf1969 left a comment (bambulab/BambuStudio#3059)<https://github.com/bambulab/BambuStudio/issues/3059#issuecomment-2843880555>
> Do you know how much I HATE having to "reboot" every time I install/uninstall EVERYTHING...WMP was ALREADY installed, so I uninstall, then it says "needs a reboot". Windows is trash.
> 
WHY can't Bambu/Slicer allow us to SELECT the player...obviously you can't rely on WINDOWS to do it...since Windows is incompetent at such tasks...
> 
Pathetic.
