### ISSUE TITLE
openexr corrupt patch

### ISSUE THREAD

**Issue by LaurentBerger** [bambulab/BambuStudio#3064]
### Bambu Studio Version

even with master

### Where is the application from?

Built from source by yourself or others

### OS version

windows 11 vs 2022

### Additional system information

13th Gen Intel(R) Core(TM) i9-13900KF 3.00 GHz NVidia RTX 3090

### Printer

waiting delivery

### How to reproduce

I tried to build dep

```
cmake .. -DDESTDIR=c:/lib/bambustudio_dep -DCMAKE_BUILD_TYPE=Release
cmake --build . --config=release

```

### Actual results

cmake  --build . --config=Release
MSBuild version 17.5.0+6f08c67f3 for .NET Framework

  Checking Build System
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Performing patch step for 'dep_OpenEXR'
CUSTOMBUILD : error : corrupt patch at line 5 [C:\lib\BambuStudio\deps\build\dep_OpenEXR.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066:
 la build personnalisée de 'C:\lib\BambuStudio\deps\build\CMakeFiles\fea2bd8c90cc09515bf127050616dcf7\dep_OpenEXR-patch.rule;C:\lib\
BambuStudio\deps\build\CMakeFiles\fea2bd8c90cc09515bf127050616dcf7\dep_OpenEXR-configure.rule;C:\lib\BambuStudio\deps\build\CMakeFil
es\fea2bd8c90cc09515bf127050616dcf7\dep_OpenEXR-build.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\fea2bd8c90cc09515bf127050616dcf7
\dep_OpenEXR-build_debug.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\fea2bd8c90cc09515bf127050616dcf7\dep_OpenEXR-install.rule;C:\
lib\BambuStudio\deps\build\CMakeFiles\81e85d90e05730ebabef268f74d76fa5\dep_OpenEXR-complete.rule;C:\lib\BambuStudio\deps\build\CMake
Files\b4ed71ba669bc48bb63b6224b78d8f2a\dep_OpenEXR.rule;C:\lib\BambuStudio\deps\CMakeLists.txt' s'est arrêtée. Code 128. [C:\lib\Bam
buStudio\deps\build\dep_OpenEXR.vcxproj]
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Performing update step for 'dep_wxWidgets'
  Building Custom Rule C:/lib/BambuStudio/deps/CMakeLists.txt
  Performing patch step for 'dep_wxWidgets'
  C:/lib/BambuStudio/deps/wxWidgets/0001-wxWidget-fix.patch:42: space before tab in indent.
        , const wxWindow *window = nullptr
  C:/lib/BambuStudio/deps/wxWidgets/0001-wxWidget-fix.patch:44: space before tab in indent.
        );
  C:/lib/BambuStudio/deps/wxWidgets/0001-wxWidget-fix.patch:55: space before tab in indent.
        , const wxWindow *window = nullptr
  C:/lib/BambuStudio/deps/wxWidgets/0001-wxWidget-fix.patch:57: space before tab in indent.
        )
  C:/lib/BambuStudio/deps/wxWidgets/0001-wxWidget-fix.patch:181: trailing whitespace.
          (anchorSideVertical & wxUP) ||
  Checking patch build/cmake/init.cmake...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          else()?
              find_package(OpenGL)?
              if(WXGTK3 AND OpenGL_EGL_FOUND AND wxUSE_GLCANVAS_EGL)?
                  set(OPENGL_LIBRARIES OpenGL::OpenGL OpenGL::EGL)?
                  find_package(WAYLANDEGL)?
                  if(WAYLANDEGL_FOUND AND wxHAVE_GDK_WAYLAND)?
                      list(APPEND OPENGL_LIBRARIES ${WAYLANDEGL_LIBRARIES})?

CUSTOMBUILD : error : patch failed: build/cmake/init.cmake:413 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : build/cmake/init.cmake: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch build/cmake/lib/webview/CMakeLists.txt...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  elseif(WXMSW)?
      if(wxUSE_WEBVIEW_EDGE)?
          # Update the following variables if updating WebView2 SDK?
          set(WEBVIEW2_VERSION "1.0.705.50")?
          set(WEBVIEW2_URL "https://www.nuget.org/api/v2/package/Microsoft.Web.WebView2/${WEBVIEW2_VERSION}")?
          set(WEBVIEW2_SHA256 "6a34bb553e18cfac7297b4031f3eac2558e439f8d16a45945c22945ac404105d")?
  ?

CUSTOMBUILD : error : patch failed: build/cmake/lib/webview/CMakeLists.txt:56 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : build/cmake/lib/webview/CMakeLists.txt: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxp
roj]
  Checking patch include/wx/fontutil.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
      wxFontEncoding GetEncoding() const;?
  ?
      void SetPointSize(int pointsize);?
      void SetFractionalPointSize(double pointsize);?
      void SetPixelSize(const wxSize& pixelSize);?
      void SetStyle(wxFontStyle style);?
      void SetNumericWeight(int weight);?

CUSTOMBUILD : error : patch failed: include/wx/fontutil.h:294 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/fontutil.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch include/wx/gdicmn.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  class WXDLLIMPEXP_FWD_BASE wxString;?
  class WXDLLIMPEXP_FWD_CORE wxIconBundle;?
  class WXDLLIMPEXP_FWD_CORE wxPoint;?
  ?
  // ---------------------------------------------------------------------------?
  // constants?

CUSTOMBUILD : error : patch failed: include/wx/gdicmn.h:38 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/gdicmn.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch include/wx/generic/grid.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
                           wxGridWindow* gridWindow);?
  ?
      // Update the width/height of the column/row being drag-resized.?
      void DoGridDragResize(const wxPoint& position,?
                            const wxGridOperations& oper,?
                            wxGridWindow* gridWindow);?
  ?
      // process different clicks on grid cells?
      void DoGridCellLeftDown(wxMouseEvent& event,?

CUSTOMBUILD : error : patch failed: include/wx/generic/grid.h:2951 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/generic/grid.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch include/wx/msw/font.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
      // ctors and such?
      wxFont() { }?
  ?
      wxFont(const wxFontInfo& info);?
  ?
      wxFont(int size,?
             wxFontFamily family,?

CUSTOMBUILD : error : patch failed: include/wx/msw/font.h:23 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/msw/font.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch include/wx/msw/tooltip.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
      // the one and only one tooltip control we use - never access it directly?
      // but use GetToolTipCtrl() which will create it when needed?
      static WXHWND ms_hwndTT;?
  ?
      // create the tooltip ctrl if it doesn't exist yet and return its HWND?
      static WXHWND GetToolTipCtrl();?
  ?
      // to be used in wxModule for deleting tooltip ctrl window when exiting mainloop?
      static void DeleteToolTipCtrl();?
  ?

CUSTOMBUILD : error : patch failed: include/wx/msw/tooltip.h:91 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/msw/tooltip.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch include/wx/osx/app.h...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  ?
  public:?
      bool                OSXInitWasCalled() { return m_inited; }?
      void                OSXStoreOpenFiles(const wxArrayString &files ) { m_openFiles = files ; }?
      void                OSXStorePrintFiles(const wxArrayString &files ) { m_printFiles = files ; }?
      void                OSXStoreOpenURL(const wxString &url ) { m_getURL = url ; }?
  #endif?

CUSTOMBUILD : error : patch failed: include/wx/osx/app.h:161 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : include/wx/osx/app.h: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/common/combocmn.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          #if !USES_GENERICTLW?
              m_winPopup = new wxComboPopupWindowBase2( this, wxNO_BORDER );?
          #else?
              int tlwFlags = wxNO_BORDER;?
            #ifdef wxCC_GENERIC_TLW_IS_FRAME?
              tlwFlags |= wxFRAME_NO_TASKBAR;?
            #endif?

CUSTOMBUILD : error : patch failed: src/common/combocmn.cpp:2141 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/common/combocmn.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/common/datavcmn.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  ?
      wxDataViewItemArray selections;?
      GetSelections(selections);?
      return selections[0];?
  }?
  ?
  namespace?

CUSTOMBUILD : error : patch failed: src/common/datavcmn.cpp:1322 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/common/datavcmn.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/common/dcbufcmn.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          const double scale = dc ? dc->GetContentScaleFactor() : 1.0;?
          wxBitmap* const buffer = new wxBitmap;?
  ?
          // we must always return a valid bitmap but creating a bitmap of?
          // size 0 would fail, so create a 1*1 bitmap in this case?
          buffer->CreateScaled(wxMax(w, 1), wxMax(h, 1), -1, scale);?
  ?
          return buffer;?
      }?

CUSTOMBUILD : error : patch failed: src/common/dcbufcmn.cpp:82 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/common/dcbufcmn.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/common/gdicmn.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          *height = size.y;?
  }?
  ?
  wxSize wxGetDisplaySize()?
  {?
      return wxDisplay().GetGeometry().GetSize();?
  }?
  ?
  void wxClientDisplayRect(int *x, int *y, int *width, int *height)?
  {?
      const wxRect rect = wxGetClientDisplayRect();?

CUSTOMBUILD : error : patch failed: src/common/gdicmn.cpp:863 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/common/gdicmn.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/common/intl.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
              {?
                  str = buf;?
  ?
                  // As we get our decimal point separator from Win32 and not the?
                  // CRT there is a possibility of mismatch between them and this?
                  // can easily happen if the user code called setlocale()?

CUSTOMBUILD : error : patch failed: src/common/intl.cpp:1628 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/common/intl.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/generic/grid.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
              {?
                  case WXGRID_CURSOR_RESIZE_ROW:?
                  {?
                      DoGridDragResize(event.GetPosition(), wxGridRowOperations(), gridWindow);?
                  }?
                  break;?
  ?

CUSTOMBUILD : error : patch failed: src/generic/grid.cpp:3824 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/generic/grid.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/msw/bmpcbox.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  ?
      wxComboBox::DoClear();?
  ?
      HWND hwnd = GetHwnd();?
      DissociateHandle();?
      ::DestroyWindow(hwnd);?
  ?
      if ( !MSWCreateControl(wxT("COMBOBOX"), wxEmptyString, pos, size) )?
          return;?
  ?
      // initialize the controls contents?
      for ( i = 0; i < numItems; i++ )?
      {?

CUSTOMBUILD : error : patch failed: src/msw/bmpcbox.cpp:156 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/msw/bmpcbox.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/msw/font.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  class WXDLLEXPORT wxFontRefData: public wxGDIRefData?
  {?
  public:?
      wxFontRefData(const wxFontInfo& info = wxFontInfo());?
  ?
      wxFontRefData(const wxNativeFontInfo& info, WXHFONT hFont = 0)?
      {?

CUSTOMBUILD : error : patch failed: src/msw/font.cpp:54 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/msw/font.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/msw/menuitem.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          // native menu uses small top margin for separator?
          if ( SeparatorMargin.cyTopHeight >= 2 )?
              SeparatorMargin.cyTopHeight -= 2;?
      }?
      else?
  #endif // wxUSE_UXTHEME?

CUSTOMBUILD : error : patch failed: src/msw/menuitem.cpp:368 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/msw/menuitem.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/msw/window.cpp...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  }?
  ?
  /*extern*/?
  int wxGetSystemMetrics(int nIndex, const wxWindow* window)?
  {?
  #if wxUSE_DYNLIB_CLASS?
      if ( !window )?
          window = wxApp::GetMainTopWindow();?
  ?
      if ( window )?
      {?
          typedef int (WINAPI * GetSystemMetricsForDpi_t)(int nIndex, UINT dpi);?
          static GetSystemMetricsForDpi_t s_pfnGetSystemMetricsForDpi = NULL;?
          static bool s_initDone = false;?
  ?
          if ( !s_initDone )?
          {?
              wxLoadedDLL dllUser32("user32.dll");?
              wxDL_INIT_FUNC(s_pfn, GetSystemMetricsForDpi, dllUser32);?
              s_initDone = true;?
          }?
  ?
          if ( s_pfnGetSystemMetricsForDpi )?
          {?
              const int dpi = window->GetDPI().y;?
              return s_pfnGetSystemMetricsForDpi(nIndex, (UINT)dpi);?
          }?
      }?
  #else?
      wxUnusedVar(window);?
  #endif // wxUSE_DYNLIB_CLASS?
  ?
      return ::GetSystemMetrics(nIndex);?

CUSTOMBUILD : error : patch failed: src/msw/window.cpp:4773 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/msw/window.cpp: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/osx/cocoa/dataview.mm...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
          if ( !dvc->GetEventHandler()->ProcessEvent(eventDV) )?
              [super keyDown:event];?
      }?
      else?
      {?
          [super keyDown:event];  // all other keys?
      }?
  }?
  ?
  //?
  // contextual menus?
  //?

CUSTOMBUILD : error : patch failed: src/osx/cocoa/dataview.mm:1734 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/osx/cocoa/dataview.mm: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  Checking patch src/osx/cocoa/settings.mm...
CUSTOMBUILD : error : while searching for: [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
  // ----------------------------------------------------------------------------?
  ?
  // Get a system metric, e.g. scrollbar size?
  int wxSystemSettingsNative::GetMetric(wxSystemMetric index, const wxWindow* WXUNUSED(win))?
  {?
      int value;?
  ?

CUSTOMBUILD : error : patch failed: src/osx/cocoa/settings.mm:224 [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
CUSTOMBUILD : error : src/osx/cocoa/settings.mm: patch does not apply [C:\lib\BambuStudio\deps\build\dep_wxWidgets.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066:
 la build personnalisée de 'C:\lib\BambuStudio\deps\build\CMakeFiles\8a4a75bcf26be3a22de1212b2da6d907\dep_wxWidgets-update.rule;C:\l
ib\BambuStudio\deps\build\CMakeFiles\8a4a75bcf26be3a22de1212b2da6d907\dep_wxWidgets-patch.rule;C:\lib\BambuStudio\deps\build\CMakeFi
les\8a4a75bcf26be3a22de1212b2da6d907\dep_wxWidgets-configure.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\8a4a75bcf26be3a22de1212b2
da6d907\dep_wxWidgets-build.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\8a4a75bcf26be3a22de1212b2da6d907\dep_wxWidgets-build_debug
.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\8a4a75bcf26be3a22de1212b2da6d907\dep_wxWidgets-install.rule;C:\lib\BambuStudio\deps\b
uild\CMakeFiles\81e85d90e05730ebabef268f74d76fa5\dep_wxWidgets-complete.rule;C:\lib\BambuStudio\deps\build\CMakeFiles\b4ed71ba669bc4
8bb63b6224b78d8f2a\dep_wxWidgets.rule;C:\lib\BambuStudio\deps\CMakeLists.txt' s'est arrêtée. Code 1. [C:\lib\BambuStudio\deps\build\
dep_wxWidgets.vcxproj]

### Expected results

no error

### Project file & Debug log uploads

[BambuStudio-deps.zip](https://github.com/bambulab/BambuStudio/files/13619429/BambuStudio-deps.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bambu123** [comment]
When compiling again, you need to clear the build directory because patches for some modules cannot be applied twice.

**Comment by LaurentBerger** [comment]
not sure that's the problem. As build process is very verbose it is difficult to get all message.
I delete everything and rebuild. It seems ok for dependency but for bambusudio it's not 👍 
```
C:\lib\BambuStudio\build>cmake .. -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH=C:\lib\bambustudio_dep\usr\local -DCMAKE_INSTALL_PREFIX=c:\install\bambustudio -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0"
-- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.35.32215.0
-- The CXX compiler identification is MSVC 19.35.32215.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SLIC3R_ASAN: OFF
-- SLIC3R_BUILD_SANDBOXES: OFF
-- SLIC3R_BUILD_TESTS: OFF
-- SLIC3R_DESKTOP_INTEGRATION: ON
-- SLIC3R_FHS: OFF
-- SLIC3R_GTK: 2
-- SLIC3R_GUI: ON
-- SLIC3R_MSVC_COMPILE_PARALLEL: ON
-- SLIC3R_MSVC_PDB: ON
-- SLIC3R_PCH: ON
-- SLIC3R_PERL_XS: OFF
-- SLIC3R_PROFILE: OFF
-- SLIC3R_STATIC: ON
-- SLIC3R_WX_STABLE: OFF
-- SLIC3R_STATIC: ON
-- CMAKE_PREFIX_PATH: C:\lib\bambustudio_dep\usr\local (from cache or command line)
-- PROJECT_SOURCE_DIR: C:/lib/BambuStudio
-- CMAKE_MODULE_PATH: C:/lib/BambuStudio/cmake/modules/
Building with Win10 Netfabb STL fixing service support
-- LIBDIR: C:/lib/BambuStudio/src
-- LIBDIR_BIN: C:/lib/BambuStudio/build/src
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Boost toolset is unknown (compiler MSVC 19.35.32215.0)
-- Found Boost: C:/lib/bambustudio_dep/usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.66.0") found components: system filesystem thread log locale regex chrono atomic date_time iostreams
-- Boost::boost exists
-- TBB found in C:/lib/bambustudio_dep/usr/local/lib/cmake/TBB
-- Found OpenSSL: C:/lib/bambustudio_dep/usr/local/lib/libcrypto.lib (found version "3.1.2")
-- Found CURL: C:/lib/bambustudio_dep/usr/local/lib/libcurl.lib (found version "7.75.0-DEV")
-- Found ZLIB: C:/lib/bambustudio_dep/usr/local/lib/zlib.lib (found version "1.2.13")
-- Found EXPAT: C:/lib/bambustudio_dep/usr/local/lib/expat.lib (found version "2.5.0")
-- Found PNG: optimized;C:/lib/bambustudio_dep/usr/local/lib/libpng16_static.lib;debug;C:/lib/bambustudio_dep/usr/local/lib/libpng16_staticd.lib (found version "1.6.35")
-- Found OpenGL: opengl32
-- FindGLEW: did not find GLEW CMake config file. Searching for libraries.
-- FindGLEW: GLEW_USE_STATIC_LIBS: ON.
-- FindGLEW: GLEW_INCLUDE_DIR: C:/lib/bambustudio_dep/usr/local/include
-- FindGLEW: GLEW_INCLUDE_DIRS: C:/lib/bambustudio_dep/usr/local/include
-- FindGLEW: CMAKE_FIND_LIBRARY_SUFFIXES for SHARED: .lib
-- FindGLEW: CMAKE_FIND_LIBRARY_SUFFIXES for STATIC: .lib;.a;.dll.a
-- FindGLEW: GLEW_SHARED_LIBRARY_RELEASE: C:/lib/bambustudio_dep/usr/local/lib/GLEW.lib
-- FindGLEW: GLEW_STATIC_LIBRARY_RELEASE: C:/lib/bambustudio_dep/usr/local/lib/GLEW.lib
-- FindGLEW: GLEW_SHARED_LIBRARY_DEBUG: C:/lib/bambustudio_dep/usr/local/lib/GLEWd.lib
-- FindGLEW: GLEW_STATIC_LIBRARY_DEBUG: C:/lib/bambustudio_dep/usr/local/lib/GLEWd.lib
-- FindGLEW: GLEW_SHARED_LIBRARY: optimized;C:/lib/bambustudio_dep/usr/local/lib/GLEW.lib;debug;C:/lib/bambustudio_dep/usr/local/lib/GLEWd.lib
-- FindGLEW: GLEW_STATIC_LIBRARY: optimized;C:/lib/bambustudio_dep/usr/local/lib/GLEW.lib;debug;C:/lib/bambustudio_dep/usr/local/lib/GLEWd.lib
-- FindGLEW: GLEW_LIBRARIES: optimized;C:/lib/bambustudio_dep/usr/local/lib/GLEW.lib;debug;C:/lib/bambustudio_dep/usr/local/lib/GLEWd.lib
-- FindGLEW: GLEW_VERSION_MAJOR: 2
-- FindGLEW: GLEW_VERSION_MINOR: 2
-- FindGLEW: GLEW_VERSION_MICRO: 0
-- FindGLEW: GLEW_VERSION: 2.2.0
-- Found GLEW: C:/lib/bambustudio_dep/usr/local/include (found version "2.2.0")
-- FindGLEW: Creating GLEW::glew_s imported target.
-- FindGLEW: Creating GLEW::GLEW imported target.
-- Found NLopt in 'C:/lib/bambustudio_dep/usr/local/lib'.
-- Using NLopt include directory 'C:/lib/bambustudio_dep/usr/local/include'.
-- Using NLopt library 'C:/lib/bambustudio_dep/usr/local/lib/nlopt.lib'.
-- Found PkgConfig: C:/install/strawberry-perl/perl/bin/pkg-config.bat (found version "0.26")
-- Could NOT find OpenVDB (missing: OpenVDB_INCLUDE_DIR OpenVDB_LIB_COMPONENTS openvdb) (Required is at least version "5.0")
CMake Warning at cmake/modules/OpenVDBUtils.cmake:129 (message):
  vdb_print not found! OPENVDB_PRINT-NOTFOUND
Call Stack (most recent call first):
  cmake/modules/FindOpenVDB.cmake:317 (OPENVDB_ABI_VERSION_FROM_PRINT)
  CMakeLists.txt:549 (find_package)


CMake Warning at cmake/modules/FindOpenVDB.cmake:324 (message):
  Unable to determine OpenVDB ABI version from OpenVDB installation.  The
  library major version "" will be inferred.  If this is not correct, use
  add_definitions(-DOPENVDB_ABI_VERSION_NUMBER=N)
Call Stack (most recent call first):
  CMakeLists.txt:549 (find_package)


CMake Warning at cmake/modules/FindOpenVDB.cmake:345 (message):
  IlmBase::Half can not be found!
Call Stack (most recent call first):
  cmake/modules/FindOpenVDB.cmake:367 (just_fail)
  CMakeLists.txt:549 (find_package)


CMake Error at CMakeLists.txt:554 (message):
  OpenVDB could not be found with the bundled find module.  You can try to
  specify the find module location of your OpenVDB installation with the
  OPENVDB_FIND_MODULE_PATH cache variable.


-- Configuring incomplete, errors occurred!
```

**Comment by bambu123** [comment]
@lanewei120 有没有遇到过？

**Comment by lanewei120** [comment]
it seems openvdb is not build successfully when building deps

@LaurentBerger 
is there OpenVDB libraries and cmake files included in your C:/lib/bambustudio_dep？

for example
```
$ ls usr/local/lib/cmake/OpenVDB/
FindCppUnit.cmake  FindJemalloc.cmake  FindLog4cplus.cmake  FindOpenVDB.cmake  FindTBB.cmake  OpenVDBGLFW3Setup.cmake  OpenVDBHoudiniSetup.cmake  OpenVDBMayaSetup.cmake  OpenVDBUtils.cmake

$ ls usr/local/lib/libopenvdb*
libopenvdb.lib   libopenvdbd.lib
```

if yes, could you packed these files to us for a check

**Comment by LaurentBerger** [comment]
YES
usr/local/lib/cmake OpenVDB.zip 
[OpenVDB.zip](https://github.com/bambulab/BambuStudio/files/13730073/OpenVDB.zip)
and YES 
lib
[libopenvdbd.zip](https://github.com/bambulab/BambuStudio/files/13730082/libopenvdbd.zip)

**Comment by lanewei120** [comment]
@LaurentBerger 

hi, this issue is caused by deps building of OpenEXR

we have fixed it at https://github.com/bambulab/BambuStudio/pull/3188

please have a try
