### ISSUE TITLE
"Place on cut" feature

### ISSUE THREAD

**Issue by polylawman** [bambulab/BambuStudio#3079]
### Bambu Studio Version

V1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Processor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

### Printer

Bambu Lab X1C

### How to reproduce

Go to "Cut" tab.
Add the size of your cut in the "Height" box
Go to "Add Connectors".
Select "Dowel" "Circle" and configure size of your dowels and Tolerences.
Select "Confirm Connectors".
Verify "Upper Part" and "Lower Part" check boxes are selected as well as "Place on Cut" check box for either Upper or Lower is selected.
Select "Perform Cut"
The issue I am having is that the "Dowel" is not placed on the upper or lower part after performing the cut. The very first time I used the feature "Place on Cut", the dowel was placed on the selected part. Since that first time, the dowels are placed on the bed with the parts. I have tried different ways to get the software to place the dowels on the selected part. but nothing has worked since that first time using the feature.

### Actual results

The dowels are placed on the bed and not on the selected "upper" or "lower" part

### Expected results

The dowels should be placed on the selected "upper" or "lower" part or both.

### Project file & Debug log uploads

[DanielUSBCord.zip](https://github.com/bambulab/BambuStudio/files/13635464/DanielUSBCord.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye01** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/40328051/86224c4f-eac4-4f04-997e-b9db638247b9)
you can use "Plug" to meet your needs.
"Place on Cut" not mean "Dowel" on cut section， it is mean that Diagonal cutting can obtain different placement postures based on different options.Like this , this is Oblique cutting
![image](https://github.com/bambulab/BambuStudio/assets/40328051/b18d3f23-cfb4-49b1-9aa5-2223360828e9)
these are different result.
![image](https://github.com/bambulab/BambuStudio/assets/40328051/e1cfb1ed-501a-4ec5-8fee-1540ea838b8a)
