### ISSUE TITLE
Cannot create filament whose name begins with a number.

### ISSUE THREAD

**Issue by man55** [bambulab/BambuStudio#3082]
### Bambu Studio Version

1.8.0 Public beta 3

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C Carbon Combo

### How to reproduce

Try to create a filament whose name begins with a number.

### Actual results

Cannot create filament whose name begins with a number.

### Expected results

We have a manufacturer called **3Dplast**. We would like to be able to create filament for it.

### Project file & Debug log uploads

<img width="446" alt="Screenshot 2023-12-11 172216" src="https://github.com/bambulab/BambuStudio/assets/30772900/90475dfc-4818-4f22-aa75-bececbd9a2fd">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by berezovskyi-oleksandr** [comment]
Same for me. Please fix, this is the manufacturer I use the most

**Comment by berezovskyi-oleksandr** [comment]
Same for me. Please fix, this is the manufacturer I use the most

@DanBao-Bambu could you take a look?

**Comment by kiddden** [comment]
Same

**Comment by DanBao-Bambu** [comment]
Yes, I know there is this restriction, and I'm sorry. I will check and change the rules, but please note that if all inputs are numbers, they will still not be allowed.
