### ISSUE TITLE
Bambu UI Scaling Error

### ISSUE THREAD

**Issue by coreycoldren** [bambulab/BambuStudio#3086]
### Bambu Studio Version

1.7.7.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. Launch Bambu Studio
2. Connect to device
3. Initiate video of device
4. Resize Bambu Studio window

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/153573187/8c722c69-ef76-4b5c-ba84-a597e76483a4)

![image](https://github.com/bambulab/BambuStudio/assets/153573187/861f3659-07e8-4071-ab94-29ef6e5c2408)

### Expected results

The Camera, Control, and Print in Progress panels should be resized appropriately and proportionately. Instead of the Camera panel sizing *way* too wide and messing with the scaling of the entire window.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LJKraus** [comment]
Sounds similar to https://github.com/bambulab/BambuStudio/issues/2574 which has been fixed in the 1.8 beta.

**Comment by bam-winterfell** [comment]
hi@coreycoldren 
You can try using version 1.8.3 .
This issue should have been resolved already

**Comment by LiZ-Li-BBL** [comment]
Get the latest version here https://github.com/bambulab/BambuStudio/releases/tag/v01.08.03.89
