### ISSUE TITLE
系统配置里还没有X1E

### ISSUE THREAD

**Issue by ccwanggl** [bambulab/BambuStudio#3089]
工艺配置里没有基于 X1E  的，目前都是X1C，是不是说明目前并没有基于X1E 的优化参数。
感觉 X1E 买亏了，参数等都没有相应的优化，固件更新也慢

**Comment by XunZhangBambu** [comment]
相对于X1C，X1E配备了更强大的空气过滤系统，为此我们专门调整了一组排气扇参数。此外，X1E还能主动进行腔温加热与控制，我们在材料配置中也进行了设置，并且我们为X1E添加了高性能材料，如PPS、PPA-CF、PPS-CF等。为了方便软件上的维护，我们沿用了X1C的工艺配置，这些功能需要硬件的支持，并受到机器配置中相关字段的控制。
