### ISSUE TITLE
No 3rd party printers supported!

### ISSUE THREAD

**Issue by valentt** [bambulab/BambuStudio#31]
Bambu Lab is based upon lots of open source code from Slic3r, Prusa slicer and SuperSlicer. All of them support multiple printers.

We would like to have print farm with Bambu Lab machines, but they will never be only machine in our shop. So why would you reduce usage of other 3D printers in Bambu Studio?

We would like to have one single workflow for all our machines.

**Comment by wuyifanfancy** [comment]
Thanks for the suggestion. We are already working on it.
We will update the code and provide a guide when the developing work is done.

**Comment by valentt** [comment]
Good to hear that we will see other printer profiles also, can't wait. Any ideas on the timeline?

**Comment by SaltWei** [comment]
guide to add 3-rd party printer into BambuStudio
https://wiki.bambulab.com/en/software/add-third-party-printer-in-studio

**Comment by SaltWei** [comment]
Already include 3-rd party printer in latest release.
