### ISSUE TITLE
PETG sticks on nozzle during filament load

### ISSUE THREAD

**Issue by odospace** [bambulab/BambuStudio#3102]
### Bambu Studio Version

1.8.0 Public beta 3

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1 Carbon

### How to reproduce

- Start printing with PETG

### Actual results

The purged filament sticks to the nozzle or is thrown onto the plate.

### Expected results

It seems the the nozzle temperature during wipe and shake is too low for PETG (`nozzle_temperature_initial_layer[initial_no_support_extruder]-20`). 
Makes it sense to set the nozzle temperature during wipe and shake to `nozzle_temperature_range_high[initial_no_support_extruder]`?

### Project file & Debug log uploads

Two places within the machine start g-code using this "low" temperature setting
`M109 S{nozzle_temperature_initial_layer[initial_no_support_extruder]-20}`

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Xiuqi-Huang-CN** [comment]
Hello. Have you checked if the nozzle wiper works normally? If it is deformed orbad damaged, the nozzle wiping effect will be so bad that the filament can still stay on the nozzle even after wiping. And you can read this wiki to learn how to check it: [https://wiki.bambulab.com/en/knowledge-sharing/common-print-quality-problem]
![image](https://github.com/bambulab/BambuStudio/assets/141103636/83aa4386-1a5d-4044-a4e4-406047b46640)
Hope this can help you and wait for your further feedback.

**Comment by Xiuqi-Huang-CN** [comment]
@odospace

**Comment by odospace** [comment]
@Xiuqi-Huang-CN Thank you, i checked the nozzle wiper, it has a small pit:
![20231214_151250](https://github.com/bambulab/BambuStudio/assets/34418472/a19d9cea-f66f-4a4f-ba1a-db20c510b579)
