### ISSUE TITLE
Printable Check Mark is inverted

### ISSUE THREAD

**Issue by beowulfkaine** [bambulab/BambuStudio#3115]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu slicer

### How to reproduce

right click object you will see that a printable object is unchecked and vice versa

### Actual results

right click object you will see that a printable object is unchecked and vice versa

### Expected results

reversed

### Project file & Debug log uploads

[printable.zip](https://github.com/bambulab/BambuStudio/files/13678797/printable.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by LiZ-Li-BBL** [comment]
Hello,
This issue has been fixed. Please wait for the next release soon.
