### ISSUE TITLE
prime tower location on buildplate moves to default location after save and reload

### ISSUE THREAD

**Issue by JAJordan2515251** [bambulab/BambuStudio#3125]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

n/a

### Printer

x1c

### How to reproduce

create and multi color model 
move the prime tower on the build plate to a non default location on the build plate.
save and close the project file
open the project file
prime tower location has moved to the default location

### Actual results

prime tower location has moved to the default location

### Expected results

prime tower location should stay in the location it was saved 

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@JAJordan2515251 
Hi,

 I have just tried it on windows 10, and can not reproduce your issue
![20231216183144_rec_](https://github.com/bambulab/BambuStudio/assets/106916061/7f9cc916-35c3-4a40-871d-b2894f330565)

could you give a short gif for how to reproduce?
and also help to upload the log and 3mf for us debugging

thanks

**Comment by zhimin-zeng-bambulab** [comment]
@JAJordan2515251 
I can't reproduce your problem either.  Could you please provide a video of the reproduction?

**Comment by JAJordan2515251** [comment]
I’ll need to close the bug report.  It happened to me for two straight days , lots of testing on two different machines, And then on the 3rd day it stopped and I can’t reproduce it anymore eather.

Sorry for raising an alarm and thank you for looking into it.

Jason
________________________________

**Comment by zhimin-zeng-bambulab** [comment]
It's okay. If you have any problems in the future, please feel free to report them.
