### ISSUE TITLE
unexpected layers in multi color print

### ISSUE THREAD

**Issue by reebgogs** [bambulab/BambuStudio#3131]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

N/A

### Printer

X1C

### How to reproduce

paint colors on a multi object, preview looks as expected
slice and now there are two incorrectly colored layers in between the objects
![correct preview](https://github.com/bambulab/BambuStudio/assets/144286377/bd9a532d-7794-4ed6-9431-96f8a10fab01)

### Actual results

![incorrect after slice](https://github.com/bambulab/BambuStudio/assets/144286377/e973d69c-4d57-4ff1-b065-11d451559322)

### Expected results

![correct preview](https://github.com/bambulab/BambuStudio/assets/144286377/b548414a-d6f7-4b76-9383-4fe64dfaea31)

### Project file & Debug log uploads

I did not include the project file because the model is proprietary. I will provide as much information as possible when requested

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@reebgogs  Could your share your 3mf file?

**Comment by reebgogs** [comment]
@zhimin-zeng-bambulab Is there a way to share it securely? It is a proprietary model

**Comment by zhimin-zeng-bambulab** [comment]
@reebgogs Could you send the model file to me privately? I will only use it for debugging.
This is my email zhimin.zeng@bambulab.com

**Comment by reebgogs** [comment]
Thanks! The model has been shared privately.

Greg Wright
916.221.0016

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.03.50
