### ISSUE TITLE
flush volume multiplier

### ISSUE THREAD

**Issue by 4drienMC** [bambulab/BambuStudio#3146]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

5800x3d 32GB ram 

### Printer

P1P

### How to reproduce

add multiple color in bambu filament tab 
go into flushing volume 
enter a multiplier between 1 and 0 

### Actual results

error sound and all flushing volume at 0

### Expected results

calculate flushing volume normaly

### Project file & Debug log uploads

[Pièce1.zip](https://github.com/bambulab/BambuStudio/files/13695842/Piece1.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MklBambu** [comment]
Sorry, we did not reproduce your question. Could you please upload some operation videos or GIFs?
