### ISSUE TITLE
Painting Edge detection Smart fill angle hotkey

### ISSUE THREAD

**Issue by james7360** [bambulab/BambuStudio#315]
Currently while painting with edge detection the hotkey Ctrl and mouse wheel changes Section view. It would be much better to have a hotkey for Smart fill angle.
In PrusaSlicer Ctrl does Section view and Alt does Smart fill angle.

**Comment by YifanWuBambu** [comment]
@james7360 
Thanks for the suggestion. We will add this to the next release.

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.
![image](https://user-images.githubusercontent.com/110661856/197092418-eb708e0d-50b3-4416-8129-01d694c644c9.png)
