### ISSUE TITLE
Add profile for Anycubic Kobra 2 Max

### ISSUE THREAD

**Issue by Waffull** [bambulab/BambuStudio#3152]
**Is your feature request related to a problem? Please describe.**
There's a profile for Kobra 2 and Kobra Max, but not the Kobra 2 Max

**Describe the solution you'd like**
Would be nice to be able to consolidate and use only one slicer

**Comment by XunZhangBambu** [comment]
Hello, in version 1.8, we have introduced the custom printer feature. You can use this feature to add the printer you need.

![image](https://github.com/bambulab/BambuStudio/assets/139755545/f3097374-3f9e-4882-8f2b-9aae081d58d7)
