### ISSUE TITLE
Repeated Dropdown Menu options when using Flow Dynamics Calibration Tool

### ISSUE THREAD

**Issue by thereseLYR** [bambulab/BambuStudio#3155]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Home 22H2

### Printer

Bambu Lab X1C

### How to reproduce

1) Go to Calibration > Flow Dynamics Calibration.
2) Run auto calibration using LiDAR for multiple AMS slots, e.g. slot 1, 3, and 4
3) On the last step, "Record Factor", access the dropdown menu and check what options are available.

Issue is not specific to 3D model, and no crash occured.

### Actual results

Dropdown menu options are multiplied by the number of AMS slots, e.g. 3 AMS slots used for calibration, means that each unique filament profile appears in the dropdown menu 3 times.
![image](https://github.com/bambulab/BambuStudio/assets/47405262/4147ac12-323d-48b5-8baa-62892e091a90)

For further testing, I also managed to replicate this when 2 AMS slots were used for calibration:
![image](https://github.com/bambulab/BambuStudio/assets/47405262/3723dc1e-72ad-4abe-b73e-8c5469744fee)

### Expected results

Filament profiles should only appear once, regardless of how many AMS slots were used in calibration. Additionally, filament profiles should be sorted alphabetically, instead of by date of creation, for better UX.

### Project file & Debug log uploads

[PlanetaryRingLauncher.zip](https://github.com/bambulab/BambuStudio/files/13698795/PlanetaryRingLauncher.zip)
[BambuLogs-18Dec.zip](https://github.com/bambulab/BambuStudio/files/13698796/BambuLogs-18Dec.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by LiZ-Li-BBL** [comment]
Hi,
This issue has been fixed in the latest version: https://github.com/bambulab/BambuStudio/releases/tag/v01.08.04.51
