### ISSUE TITLE
Adding the translation 'hms_pl' to e.bambulab.com for the Polish language

### ISSUE THREAD

**Issue by KrisMorr** [bambulab/BambuStudio#3167]
Please add the 'hms_pl' file to the Bambulab server. I already have the rest of the translations prepared for this language. Before it is added in its entirety, we would like to test the coherence of the whole with the group.

![screenshots](https://github.com/bambulab/BambuStudio/assets/154343071/83590721-f356-4f59-b1e9-d4c58eb881f9)

**Comment by arekm** [comment]
Pull request is missing.

**Comment by Bartosz2010** [comment]
[pl]
Czy coś się ruszyło w sprawie polskiego tłumaczenia? Jak na razie, nie ma ani pozycji języka polskiego w liście języków, ani pliku BambuStudio_pl.po w folderze bbl/i18n.

[en]
Has anything happened regarding the Polish translation? As of now, there is neither a Polish language entry in the language list nor a BambuStudio_pl.po file in the bbl/i18n folder.
