### ISSUE TITLE
Erroneous Internal Solid Infill Made by Bambu Studio Sliced file

### ISSUE THREAD

**Issue by VACIndustries** [bambulab/BambuStudio#317]
![image](https://user-images.githubusercontent.com/3279061/192070152-e8cd722f-5267-4474-8094-393eaef941de.png)

When slicing this file it adds a bunch of internal solid infill which should not be (see picture)

Attached is both the base.3mf file which was downloaded from here https://www.printables.com/model/239774-modular-desktop-fountain/files

And the Bambu Studio sliced file in the image above (hex_plate_1.gcode.3mf)
[3mffiles.zip](https://github.com/bambulab/BambuStudio/files/9637533/3mffiles.zip)

**Comment by SaltWei** [comment]
Patch has been merged. Please wait the the next release. Will come soon.

**Comment by YifanWuBambu** [comment]
Fixed in v.1.3.0.12.

**Comment by Bpositivedotdk** [comment]
I think it still does this in the latest version. - Adding quite a lot of print time....
![Skærmbillede 2022-10-30 104312](https://user-images.githubusercontent.com/84511476/198872307-b2ea9b3a-4b37-49fa-8652-7f59faa2f49c.png)

**Comment by SaltWei** [comment]
> I think it still does this in the latest version. - Adding quite a lot of print time.... ![Skærmbillede 2022-10-30 104312](https://user-images.githubusercontent.com/84511476/198872307-b2ea9b3a-4b37-49fa-8652-7f59faa2f49c.png)

Please share the model for analyse

**Comment by Bpositivedotdk** [comment]
> > I think it still does this in the latest version. - Adding quite a lot of print time.... ![Skærmbillede 2022-10-30 104312](https://user-images.githubusercontent.com/84511476/198872307-b2ea9b3a-4b37-49fa-8652-7f59faa2f49c.png)
> 
> Please share the model for analyse

Can I send it to you directly? don't want to share this particular model here.

**Comment by SaltWei** [comment]
Yes. My email is salt.wei@bambulab.com
Thank you very much for response!

**Comment by SaltWei** [comment]
Hi @Bpositivedotdk . Thanks for reporting issue.
But this is absolutely differently issue you reported. The extrusion line is not mess with floating line, but still will organized.

For the solid infill you reported, prusa has same behaviour.
![image](https://user-images.githubusercontent.com/110660407/198909761-0116d759-055d-43dd-a371-62813e15026c.png)
Solid indill is added in slope to ensure thickness. And prusa has option "ensure vertical shell thickness" for user to disable but bambu always enable it when slicing.

So for your requirement and case, we will provided option "ensure vertical shell thickness" so you can disable these solid infill.

**Comment by Bpositivedotdk** [comment]
Thanks SaltWei. Yes I see its not the floating line issue, but still a problem with solid infill. 
It would be great to have an option to remove that, so looking forward to that.
... (and in general the option to customize a lot more). Coming from Cura that has a million settings you can tweak, I find Bambu studio very limiting.)
