### ISSUE TITLE
Tree support - problem with wall loops

### ISSUE THREAD

**Issue by mrpiagg** [bambulab/BambuStudio#3182]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1 Carbon

### How to reproduce

Enable support
Select Tree hybrid (or any other)
Tree support wall loops 0 or 1
Slice model

### Actual results

Tree support has two wall loops and ingnores setting,

### Expected results

To have just one wall loop or what is set.

### Project file & Debug log uploads

![tree-support](https://github.com/bambulab/BambuStudio/assets/8761493/a510c3a4-b2e9-4554-8bc2-6ea5abc31ea3)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
This is designed feature - tree supports with "Hollow" infill pattern (which is the default) will decide how many loops to use at different layers. 1 layer is at least. If extra strength is needed, 2 layers will be used.
The wall count setting is only valid when you set an infill pattern other than hollow and lightning.

**Comment by ajgp** [comment]
I would like to add I have this issue as well, currently using version 2.1.0.59 on Windows and same on Version 2.1.1.52 on Linux (Opensuse)
