### ISSUE TITLE
Error Code 5010 when sending jobs

### ISSUE THREAD

**Issue by sawig10** [bambulab/BambuStudio#3190]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1c

### How to reproduce

Send a plate greater then 3.3MBs and at 99% it will fail. 
Have to delete the gcode that appears corrupted now and try again. 

### Actual results

![P_20231220_234846](https://github.com/bambulab/BambuStudio/assets/154494371/a24b70ea-4c1c-420f-a76c-5048099a4bc9)

### Expected results

The sliced job should be sitting on the machine read to print or be selected to print from SD card.

### Project file & Debug log uploads

[log122123_error5010.zip](https://github.com/bambulab/BambuStudio/files/13736780/log122123_error5010.zip)
[AMS Tall Stand V2.zip](https://github.com/bambulab/BambuStudio/files/13736785/AMS.Tall.Stand.V2.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by sawig10** [comment]
I have logged out of both the studio and off the printer.
Reformatted the SD Card.
Factory reset the printer.
Uninstalled and reinstalled Studio. 
Turned firewalls off.
Added an assess point in the network thinking it was low signal. 
Resync server time and changed the time server. 
Note: Handy App has no issues with connection.

**Comment by walterwongbbl** [comment]
Hi. @sawig10 
I successfully attempted to send the file to the printer using the file you provided. Additionally, I reviewed the log files you provided and noticed several timeout records related to FTP operations. Please try placing the printer closer to the Wi-Fi signal and then attempt the send again. FTP has higher requirements for network signal stability.

**Comment by sawig10** [comment]
@walterwongbbl your FTP comment brought to mind that I was previously testing other FTP issues not related to Bambu SW. I turned off/blocked some of those protocols and returning those network settings fixed my problem. I am no longer getting kicked on and off using the Studio.

**Comment by walterwongbbl** [comment]
@sawig10 
Is your issue resolved now?

**Comment by sawig10** [comment]
Yes, looks like issue has been resolved. Thank you!
________________________________

**Comment by sawig10** [comment]
Hey @CCKang886, I found that enabling FTP, TLS, and Samba on my router seemed to resolve my problems. I also changed my DNS settings around the same time so they may have played a factor as well.
________________________________

**Comment by CCKang886** [comment]
Hi @sawig10 , I will try fix following your guidance. Will feedback with result. Thanks !
