### ISSUE TITLE
[REQUEST] Add pause gcode after calibrations

### ISSUE THREAD

**Issue by alexsanchiz** [bambulab/BambuStudio#32]
I would like if you could add a check box which injects a pause gcode after calibrations and just before printing, so we can remove calibration prints and print a full flat plate.

**Comment by tsdexter** [comment]
@wuyifanfancy alternatively, could we move the calibration pattern elsewhere so we can print a large diameter circle with the calibration in the center of the build plate to avoid having to pause and restart the print?

**Comment by YifanWuBambu** [comment]
It is added in v1.2.

**Comment by tsdexter** [comment]
where is this setting located @YifanWuBambu ?

**Comment by YifanWuBambu** [comment]
@tsdexter 
1. slice and model and go to preview page
2. drag the vertical slider bar to the bottom
![image](https://user-images.githubusercontent.com/110661856/207212949-7e18c26b-9639-444e-94bc-87cbaaea24f2.png)
3. insert Pause in the context menu
