### ISSUE TITLE
When printing PETG with multiple colors, the nozzle temperature is set to 255 degrees Celsius. However, during filament purging and material change, the temperature is lowered to 220 degrees Celsius.

### ISSUE THREAD

**Issue by jdnt** [bambulab/BambuStudio#3204]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

The PETG consumables use the same parameters as Bambu PETG Basic. The model can be found at: https://makerworld.com/zh/models/58861#profileId-60690. Please use the author's settings and replace the material with PETG. Set the purge factor to 0.65 to reduce the number of purges.The issue occurs during the material change process. While printing PETG, the temperature is set to 255 degrees, but during the purging phase, it drops to 220 degrees.

### Actual results

The excessively low purging temperature, when the cooling fan is activated, can cause premature cooling and hardening of the waste filament, resulting in a larger occupied space volume and potential blockage of the waste discharge outlet.

### Expected results

During multi-color printing and filament change, the purging temperature should be at least the same as the printing temperature, rather than lower.

### Project file & Debug log uploads
[雪人灯.gcode.zip](https://github.com/bambulab/BambuStudio/files/13758422/gcode.zip)

The second and third images show the filament purging process during a material change, where it can be observed that the system starts purging after lowering the temperature from 255 to 220 degrees. The fourth image represents the temperature during regular printing.
![0](https://github.com/bambulab/BambuStudio/assets/1711790/85d5cfd4-db67-4cb8-b800-149a1986b036)
![1](https://github.com/bambulab/BambuStudio/assets/1711790/29057609-5ff2-4720-a712-9f5c261f4182)
![2](https://github.com/bambulab/BambuStudio/assets/1711790/20192a4c-ae7a-40fb-b7f5-f21b172d2f70)
![3](https://github.com/bambulab/BambuStudio/assets/1711790/bc372613-28f0-479c-ae8b-b7d232a5af21)

Test Project:
![微信截图_20231224140447](https://github.com/bambulab/BambuStudio/assets/1711790/ba1e760e-edc2-449b-b2ab-4a33403c1dd1)
[test_project.zip](https://github.com/bambulab/BambuStudio/files/13761089/test_project.zip)
[test_log.zip](https://github.com/bambulab/BambuStudio/files/13761090/test_log.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by jdnt** [comment]
[雪人灯.gcode.zip](https://github.com/bambulab/BambuStudio/files/13758422/gcode.zip)

**Comment by djngnear** [comment]
I had been wondering about this as well. I hope it gets addressed.

**Comment by jdnt** [comment]
The issue has been resolved, and the service ticket for the China region has provided an explanation.

![image](https://github.com/bambulab/BambuStudio/assets/1711790/34daaa3a-1489-4608-805a-853badf3bd8b)

"The reason for modifying the purge temperature is due to the higher viscosity of PETG. If purged at high temperatures, the ejected waste may stick together and get stuck in the waste bin. Therefore, unlike other materials that use maximum printing temperatures for purging, after testing, a specific purge temperature of 220 degrees Celsius has been set solely for PETG. Feel free to delete or modify the g-code below for adjustments if needed."
