### ISSUE TITLE
Not possible to add diffrent Filament-Material than the listet like ASA, ABS,PLA, TPU, PVA, PA or PC. To add for example BVOH is NOT possible

### ISSUE THREAD

**Issue by LucynaKushinada42** [bambulab/BambuStudio#3205]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro

### Printer

P1S

### How to reproduce

Try to add custom-Material-Typ.
![Screenshot 2023-12-23 094747](https://github.com/bambulab/BambuStudio/assets/154667536/a8dee440-7565-43e1-919e-dba080c8e6c4)
Insert Manufacturer, try to typ in custom Filament-Material-Typ.

### Actual results

Not possible to add for example BVOH. 

### Expected results

Add BVOH as custom Material!

### Project file & Debug log uploads

Not possible

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
#3205

**Comment by SaltWei** [comment]
Thanks. We will add into list

**Comment by XunZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/139755545/dbf4818a-c19a-4996-b628-8f845a49128c)
we have add many other filament types，so i think this issue can be closed now
