### ISSUE TITLE
resize arrows don't match perimiter limit colors

### ISSUE THREAD

**Issue by support27** [bambulab/BambuStudio#3212]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

Carbon x1

### How to reproduce

click to resize an object. 
rotate object by 180 for example
view object perimeter cubes. 

### Actual results

the color of the cubes no longer matches the arrow colors

### Expected results

the color of the cubes should match the directional arrows

### Project file & Debug log uploads

![Screenshot 2023-12-23 121422](https://github.com/bambulab/BambuStudio/assets/48425726/3e7e5737-ea09-4501-a754-986486f74c80)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye01** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/40328051/125a2447-227f-4f2c-bdd6-bc830cc5f477)
Thank you for your discovery. I have identified the cause. Thank you again
