### ISSUE TITLE
Bambu Studio camera shows blue lines

### ISSUE THREAD

**Issue by slevit1md** [bambulab/BambuStudio#3217]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS Sonoma

### Additional system information

CPU 3.7 GHz 6-core Intel Core i5

### Printer

Bambu Lab P1S

### How to reproduce

Click on the play button to turn on the camera in Bambu Studio

### Actual results

Shows mostly blue lines down the screen, occasionally shows the actual view of the camera

### Expected results

show the camera

### Project file & Debug log uploads

[parts.3mf.zip](https://github.com/bambulab/BambuStudio/files/13762746/parts.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by bambu123** [comment]
Please refer to the following wiki for Studio logs to send to us.
https://wiki.bambulab.com/en/x1/troubleshooting/bambu-studio-log

Also, can restarting the printer improve this problem?

**Comment by bambu123** [comment]
@slevit1md 
The printer has new firmware v1.5. Has it been upgraded? Please check if this problem still exists after the upgrade.

**Comment by bambu123** [comment]
@slevit1md 
Is there a normal playback time, such as when the printer is not printing?
Do you have any other MacBook? Is the liveview on it normal?

**Comment by bambu123** [comment]
@slevit1md 
Could you please help debug?
How TO:
1、Replace libBambuSource.dylib with the following， it is located at ~/Library/Application\ Support/BambuStudio/plugins
2、Open libBambuSource.dylib by context menu, click OK on the warning dialog.
3、Open BambuStudio
4、Play liveview
[libBambuSource.dylib.zip](https://github.com/bambulab/BambuStudio/files/14121715/libBambuSource.dylib.zip)

**Comment by bambu123** [comment]
Resolved, please follow the prompts on Studio to update the plugin to 01.08.04.05.
