### ISSUE TITLE
Typo "wrapping" instead of "warping"

### ISSUE THREAD

**Issue by bistory** [bambulab/BambuStudio#3227]
### Bambu Studio Version

1.8.2

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS 14.2.1

### Printer

A1 Mini

### How to reproduce

N/A

### Actual results

N/A

### Expected results

Here is the text : 
"Object will be raised by this number of support layers. Use this function to avoid wrapping when print ABS"

Wrapping should be "warping"

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by DanBao-Bambu** [comment]
Okay, thank you for your reminder. I will check and correct it.
