### ISSUE TITLE
Unable to change filament at layer height when first layer has text with a filament color change.

### ISSUE THREAD

**Issue by mturley777** [bambulab/BambuStudio#3229]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab P1P

### How to reproduce

1.  On any print ready to slice, add text to the bottom of the print (embedded in the first layer).
2.  Change the filament color on the text object created above to another color.
3.  Now slice the model.  Then select a layer in the sliced model using the layer slider.
4.  Now, right click on the selected layer and attempt to change filament at that layer.

### Actual results

When you try to change filament at layer, it is greyed out if you have the text along with a filament change for the text on the first layer.  If you have no text on the first layer, or the text on the first layer does not have a filament color change, then the change filament at layer is not greyed out.

Example - Text on first layer with filament change to color the text:

![Bambu text on first layer](https://github.com/bambulab/BambuStudio/assets/40129547/ec923405-5cab-458e-9898-8185fbfec176)

Then result when trying to add a filament change at layer:

![Bambu filament change by layer](https://github.com/bambulab/BambuStudio/assets/40129547/c2bf1def-0815-45a6-9be7-194995299730)

### Expected results

I expect that I can change filament at any given layer while also having text with a filament color change on the first layer.

### Project file & Debug log uploads

[Filament change at layer broken.zip](https://github.com/bambulab/BambuStudio/files/13775571/Filament.change.at.layer.broken.zip)

[Filament change at layer works fine.zip](https://github.com/bambulab/BambuStudio/files/13775573/Filament.change.at.layer.works.fine.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by LiZ-Li-BBL** [comment]
If you want to change filament at any given layer while also having text with a filament color change on the first layer, you should use Height Range Modifier or Color Painting Tool.

**Comment by LiZ-Li-BBL** [comment]
The "Change Filament" function on the layer slider actually only works if the entire plate has only one color.

**Comment by mturley777** [comment]
Sounds like a great opportunity to enhance the app to be more flexible then!

**Comment by JansenSmith** [comment]
Fixing this issue by having the Change Filament be greyed out if there are multiple colors on nearby layers would be a great improvement to my workflow.
