### ISSUE TITLE
Please add ability to SET DEFAULT BUILD PLATE

### ISSUE THREAD

**Issue by Stewey54** [bambulab/BambuStudio#323]
I have been using the PEI Double Sided Plate a lot and it would be beneficial if I didn't have to re-select it every time I changed models or material.

**Comment by whiiiskyy** [comment]
This would be nice to have.
With my current printer and smooth/textured PEI sheet, I set on the printer which one I am using and unless I change it, the printer  knows and will keep the offset for that sheet.

**Comment by YifanWuBambu** [comment]
The Studio will remember the last used build plate in the next release.

**Comment by Stewey54** [comment]
Excellent!  You guys are doing a great job

**Comment by YifanWuBambu** [comment]
Added in v1.3.0.12.
