### ISSUE TITLE
Bambu Studio Crashes after latest network driver update. 

### ISSUE THREAD

**Issue by justpie** [bambulab/BambuStudio#3234]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu  22.04

### Printer

X1 Carbon

### How to reproduce

Updating to latest network driver causes my BambuStudio to segfault when launching.

### Actual results

When I launch BambuStudio when not logged in works fine, I just can't use remote printer settings. However, when i login to my account bambu studio crashes immediately after launching. Terminal Error reports Seg Fault. 

Edit::: I would like to add that this might not have anything to do with the login. I was doing some testing and I set my printer to LAN only mode. When I tried to add my printer in lan mode, bambustudio crashed. So it appears to be 100% a networking driver issue. 

### Project file & Debug log uploads

Thread 1766 "bambustu_main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff0b1ff640 (LWP 16066)]
0x00007fffd0b407d7 in SSL_get_peer_certificate () from /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#0  0x00007fffd0b407d7 in SSL_get_peer_certificate () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#1  0x00007fffd0b233b4 in servercert () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#2  0x00007fffd0b27778 in ossl_connect_common () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#3  0x00007fffd0affef1 in Curl_ssl_connect_nonblocking () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#4  0x00007fffd0b153ca in https_connecting () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#5  0x00007fffd0ae49d8 in multi_runsingle () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#6  0x00007fffd0ae5dae in curl_multi_perform () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#7  0x00007fffd0ad67fb in curl_easy_perform () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#8  0x00007fffd09a4510 in BBL::Http::priv::http_perform(bool) () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#9  0x00007fffd0a20c4b in BBL::AccountManager::get_track_key(BBL::EncryptKey&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#10 0x00007fffd0a7c3da in BBL::TrackingManager::get_new_encrypt_key() ()
    at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#11 0x00007fffd0a824c5 in boost::detail::thread_data<BBL::TrackingManager::start()::{lambda()#1}>::run() ()
    at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#12 0x00007fffd0cbaacb in thread_proxy () at /home/davey/.config/BambuStudio/plugins/libbambu_networking.so
#13 0x00007fffefa94ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007fffefb26660 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@justpie 

how about using this image https://github.com/bambulab/BambuStudio/actions/runs/7334871417/artifacts/1135915919?

**Comment by justpie** [comment]
This appears to be working. Thank you!
