### ISSUE TITLE
Cut 'snap' connector is not working correctly

### ISSUE THREAD

**Issue by Zulex** [bambulab/BambuStudio#3244]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab A1 mini

### How to reproduce

1. Add object
2. Cut object
3. Add 'snap' connector to object
4. View object, on the 'hole' side you should see a circle carved out with a line masked (which makes sure the snap can clamp)
5. After confirming cut, this line which is masked, is not there anymore and the whole circle is carved out. 

### Actual results

![InCutMode](https://github.com/bambulab/BambuStudio/assets/18424877/aa69d037-83a9-4192-8d37-452bb31b58b2)
![After cut](https://github.com/bambulab/BambuStudio/assets/18424877/f227daed-0963-4416-8505-b947c6ddfa24)

### Expected results

I was expecting to see the masked line also in the final cut. This makes that the snap isn't working correctly to my understanding. 

### Project file & Debug log uploads

[Test.zip](https://github.com/bambulab/BambuStudio/files/13789937/Test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye01** [comment]
Actually, after printing it out, the snap on my end can work.Can you try it?

**Comment by Haidiye01** [comment]
this is the rendering effect is not the final model
![image](https://github.com/bambulab/BambuStudio/assets/40328051/ea90570c-b643-406b-8049-af026d1ca86d)
this is the final cut model
![image](https://github.com/bambulab/BambuStudio/assets/40328051/6dc8ad48-b142-4b09-a26f-bd4400282e74)

**Comment by Zulex** [comment]
The final model does snap a little, but not as much as expected. However, I am not sure what to expect ofcourse. 

But I was wondering if that line over de circle is just for indication, or that it should be printed that way? As it is definitely not printed that way.

**Comment by Haidiye01** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/40328051/047cff00-ff57-428a-94d1-df9bd319b7ce)
Finally, print the 3D model according to this
