### ISSUE TITLE
Printer gone everytime 

### ISSUE THREAD

**Issue by sajungzak** [bambulab/BambuStudio#3248]
### Bambu Studio Version

most recent one

### Where is the application from?

Bambu Lab Official website

### OS version

11

### Printer

p1s

### How to reproduce

open the app

### Actual results

printer is gone everytime

### Expected results

it should save it like it did yesterday

### Project file & Debug log uploads

ffffffff

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
Hi. @sajungzak 
Are you saying that the printer is no longer in your printer list.

**Comment by SaltWei** [comment]
Hi. @sajungzak
Are you saying that the printer is no longer in the printer list of device page of bambu studio?

**Comment by walterwongbbl** [comment]
This issue will be closed. Thank you very much for your feedback.
