### ISSUE TITLE
Text invisible in text tool while editing

### ISSUE THREAD

**Issue by Photogad** [bambulab/BambuStudio#3258]
![Screenshot 2023-12-30 160252](https://github.com/bambulab/BambuStudio/assets/18505956/0726724e-fb58-4f09-84b1-2a78fa3a3e3a)
![Screenshot 2023-12-30 160311](https://github.com/bambulab/BambuStudio/assets/18505956/11e29d0b-5bb9-45db-8825-f0451e800642)

### Bambu 
Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 Pro

### Printer

X1C

### How to reproduce

1. Place text on the bottom of an object (bottom against build plate)
2. While putting the text in and editing it, it's invisible.
3. After exiting the text tool, the text finally shows up.

### Actual results

The text only is visible while NOT in the editor.

### Expected results

The text should be visible while editing it so you can see what the edits are doing.

This bug appeared in latest release -- previously in older versions of Bambu Studio, you could see the text while you are editing it.

This is very inconvenient.

### Project file & Debug log uploads

[fixme.zip](https://github.com/bambulab/BambuStudio/files/13799177/fixme.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Photogad** [comment]
The text should be visible while editing it so you can see what the edits are doing.

This bug appeared in latest release -- previously in older versions of Bambu Studio, you could see the text while you are editing it.

This is very inconvenient.

**Comment by Haidiye01** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/40328051/0ba44644-4080-4a85-8879-fc2829969dab)
![image](https://github.com/bambulab/BambuStudio/assets/40328051/db86b336-2a64-4082-ae6e-275d57d0106d)
It is indeed a problem. We will fix it as soon as possible. At present, you can first access the bottom view through the interface or shortcut keys to view it

**Comment by Haidiye01** [comment]
The problem has been resolved and  you can use it  in version 1.9.thank you~

**Comment by Haidiye01** [comment]
ok,i have received your letter ,thank you!
