### ISSUE TITLE
3DText on object is lost when oject is sliced  

### ISSUE THREAD

**Issue by hugobenji** [bambulab/BambuStudio#3280]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1 carbon

### How to reproduce

1.Create a cube in any filament (let's say color 1) and select it
2.put a 3D text on top flat surface (any thickness, any embedded)
3.change the filament (color 2) for that text
4. select the oentire object and slice it (per default , hoizontally in middle )
5. the obecjt is sliced in 2 pieces, the above part with the 3dtext which is normal,
6. But The 3dtext object (from the left menu) has disappeared, and the text color has turn to the same as the cube (color1) instead of color 2. 

### Actual results

![3DText and slicing Bug](https://github.com/bambulab/BambuStudio/assets/155450323/0d738df5-c057-44e1-86fd-224cfd88eebc)
note in this picture the 2 objects Cube_1 and cube_B ,are the 2 parts after slicing a copy of Cube object

### Expected results

The text on the Cube_A should stay white color. and the object Cube_A should have  attached a text_shape object 

### Project file & Debug log uploads

[3Dtext object sliced.zip](https://github.com/bambulab/BambuStudio/files/13810299/3Dtext.object.sliced.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/13810304/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye01** [comment]
Hello, it's like this. Your expectations are right, but  the development workload of retaining the original color information after cutting is actually quite large, including keep the original data structure, such as retaining textshape. We will consider this in the future. Thank you
