### ISSUE TITLE
Profile keeps being reset.

### ISSUE THREAD

**Issue by AdrianGarside** [bambulab/BambuStudio#3287]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C

### How to reproduce

1. Choose the profile:
![image](https://github.com/bambulab/BambuStudio/assets/26147576/bb0955f9-8ff7-4cec-b458-c6dea412c80e)
![image](https://github.com/bambulab/BambuStudio/assets/26147576/ca80e76c-2252-4e76-bf26-3bd402ce9c2c)
![image](https://github.com/bambulab/BambuStudio/assets/26147576/b3ce0ef2-61d6-4c47-a98b-3af01649ad61)
![image](https://github.com/bambulab/BambuStudio/assets/26147576/6761d76b-0c65-44fe-a963-ae6b1dffbaf4)
2. Switch to prepare tab.
3. Resync filaments
4. Switch back to device tab
BUG: It changed the profile back to the k = 0.5 one. Which means the print quality will be awful since 0.5 is very wrong for this filament.
![image](https://github.com/bambulab/BambuStudio/assets/26147576/fb70fde9-eb63-47af-8d7c-99ddba9941cd)

### Actual results

Wrong k value gets used during the print.

### Expected results

The profile I select shouldn't be reverted.

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi.   @AdrianGarside 
Hello, can you provide the log file of Bambus studio

**Comment by AdrianGarside** [comment]
@walterwongbbl how do I do that? I don't see any option in the UI to save logs.

**Comment by walterwongbbl** [comment]
@AdrianGarside 
![image](https://github.com/bambulab/BambuStudio/assets/120699126/69e1ebe1-903a-42e5-830c-49a54f31dbfc)
![image](https://github.com/bambulab/BambuStudio/assets/120699126/064d26f2-ba4b-40c1-8b44-687b5a424ba6)

**Comment by AdrianGarside** [comment]
I deleted that PA profile to see if that would help and now I cannot select a profile at all!
![image](https://github.com/bambulab/BambuStudio/assets/26147576/7a61ad20-2d8b-435f-b8fd-2d57b5dd33ee)
![image](https://github.com/bambulab/BambuStudio/assets/26147576/aaf85002-f8c1-41eb-9727-1fbf8e3b6378)
![image](https://github.com/bambulab/BambuStudio/assets/26147576/e7c6c19c-8840-4676-81d9-72f1ad64ea95)
But no confirm button:
![image](https://github.com/bambulab/BambuStudio/assets/26147576/3138d439-d57d-47c1-ae4e-c6680c0abd13)
After hitting close as my only option, I'm still in the original no profile state:
![image](https://github.com/bambulab/BambuStudio/assets/26147576/49fbf8a9-dd09-4df0-9a4a-42dca5a4b30d)

**Comment by AdrianGarside** [comment]
And if I reset the filament and start from scratch I can't select *any* filament into that slot!
![image](https://github.com/bambulab/BambuStudio/assets/26147576/b876efe5-b815-4771-9caf-27a8146f86e4)

**Comment by zhimin-zeng-bambulab** [comment]
Could you have a try with firmware 01.05.01, it has improved this kind of problem.

**Comment by AdrianGarside** [comment]
I already have that on my P1P and P1S but this problem is specific to my X1C.

**Comment by AdrianGarside** [comment]
Unless you meant 01.07.01.00? I was running that already with at least the most recent repro and I’m on 01.07.02.00 now. I’ll see if the .2 hotfix helped.

**Comment by zhimin-zeng-bambulab** [comment]
[image]

https://github.com/bambulab/BambuStudio/issues/3287
Sorry, I replied to the wrong email. I will delete these comments that are irrelevant to this subject to avoid misleading others.

Thanks！

**Comment by zhimin-zeng-bambulab** [comment]
![img_v3_0271_782b7253-8974-4479-bb94-f4327a84bc2g](https://github.com/bambulab/BambuStudio/assets/120697589/fab65e47-c68e-4879-a9a2-e124ef2442c0)
![img_v3_0271_16135bb3-c475-48ae-9e07-d010d9e8e9cg](https://github.com/bambulab/BambuStudio/assets/120697589/3198d98a-53c0-4f70-9961-d45c8b406c87)

@AdrianGarside  
Could you reproduce your problem again? 
1. Turn on trace for log (the turning position is as shown above, change the severity_level in BambuStudio.conf to trace)
2. You can delete all the logs in the original log folder to ensure that the log files and your operation matches
3. Record your phenomenon (which slot was modified, what was the original value, what is the newly modified value)

**Comment by AdrianGarside** [comment]
I may not be able to reproduce now since I deleted the specific profile that was involved in the repro to stop it blocking me printing with correct settings.

**Comment by zhimin-zeng-bambulab** [comment]
OK.  If you encounter the same problem again, you can refer to my instructions above to enable trace, collect the logs and upload them here, and we will track the problem again. Thanks!

**Comment by zhimin-zeng-bambulab** [comment]
Close as unable to reproduce

**Comment by 0verEngineer** [comment]
@zhimin-zeng-bambulab https://github.com/bambulab/BambuStudio/issues/3671 Here you go, easily reproducable, the issue is present since well over a year, multiple users frustrated by it
