### ISSUE TITLE
Calibration at P1 broken after Firmware 1.05.00.00

### ISSUE THREAD

**Issue by threadstone83** [bambulab/BambuStudio#3288]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro

### Printer

Bambu Lab P1P with P1S upgrade kit

### How to reproduce

Go to Calibration, choose Flow Dynamics of Flow rate, choose the settings you want and start the Calibration.
The Calibration starts and finishes but it's not possible to click on next to get the next view where you can enter the values.

### Actual results

It's not possible to enter the values you get from the calibration. So the calibration can not be finished.
![Screenshot 2024-01-03 114933](https://github.com/bambulab/BambuStudio/assets/113909880/f08692db-6477-4f87-94b3-c940798a04e5)

### Expected results

Normally you will se the view where you can input the values you get from the calibration pattern and the values will be saved.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/13818135/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by Svanto1963** [comment]
Bambu studio : 1.8.2.56
Firmware P1S : 01.05.00.00 (20240102)
AMS1 : 00.00.06.40		


Calibration does not work.

Folw Dynamics
Flow Rate 
I can't press next when printing is done.

**Comment by Solomon828** [comment]
Bambu studio : 1.8.2.56
Firmware P1S : 01.05.00.00 (20240102)
AMS1 : 00.00.06.40

Calibration does not work.

Folw Dynamics
Flow Rate
I can't press next when printing is done.

**Comment by SleeperXr** [comment]
Bambu studio : 1.8.2.56
Firmware P1P : 01.05.00.00 (20240102)

Calibration does not work.

Folw Dynamics
Flow Rate
I can't press next when printing is done.

**Comment by capsel22** [comment]
Same here

**Comment by laccevil** [comment]
same here

**Comment by MarvAhl** [comment]
Same error with P1S and also with Flow Dynamics. In Bambu Lab Studio the progress is not displayed and it does not continue.

**Comment by LucasBro21** [comment]
Bambu studio : 1.8.2.56
Firmware P1S : 01.05.00.00

Calibration does not work.

Flow Dynamics
Flow Rate
I can't press next when printing is done.

**Comment by Orochium** [comment]
> Slicer 1.8.2.56, P1P firmware Firmware P1P : 01.05.00.00
> 
> Flow Calibration and Flow Dynamics Calibration cannot be completed. "Next" Button cannot be clicked to move to next part of process.

Appears resolved with 01.05.01.00 Beta firmware offer

**Comment by threadstone83** [comment]
I got the 01.05.01.00 officially and already tried it. Now Flow Dynamics works. Flow Rate I can test later.

**Comment by threadstone83** [comment]
Flow rate still doesn't work for me.

**Comment by threadstone83** [comment]
I have to take back what I said yesterday. After a complete power cycle Flow Rata Calibration works now.

**Comment by threadstone83** [comment]
Problem solved with firmware update to 01.05.01.00
