### ISSUE TITLE
[Bug UI/ 01.00.10.05/Win] "Send print job to" dialog box only 2 options vs 4 available on the touch screen

### ISSUE THREAD

**Issue by thrutheframe** [bambulab/BambuStudio#33]
Version: 
Pre-release Windows 01.00.10.05

Issue: 
When clicked Print, a dialog box "Sent print job to" appears, there is only **Bed Leveling** and **Flow calibration** options to enable/disable. It is missing **Vibration calibration** and **Scan first layer** options. 

On the printer's touch screen, the UI allows users to enable/disable all 4 options.

![BLS print options](https://user-images.githubusercontent.com/68491566/179663304-8e2686c1-96df-4fa0-b340-6983f7807535.jpg)

**Comment by wuyifanfancy** [comment]
"Vibration calibration" is removed. It is contained in device calibration (Device Page => Start Calibration).
"Scan first layer" is also removed. We will add it as a device setting in the Device Page.
