### ISSUE TITLE
[Bug] After Firmware update not new timelapse 

### ISSUE THREAD

**Issue by hutje** [bambulab/BambuStudio#332]
After doing the firmware update, there are no new timelapses visible in BambuHandy and BambuStudio. Only the old ones are visible.
The new BambuHandy app was working correctly before doing the firmware update on the printer.
The new timelapses are being captured and stored in SD card, but not visible inside the app of BambuStudio.

**Comment by YifanWuBambu** [comment]
@hutje 
Timelapse is currently enabled in Studio.
![image](https://user-images.githubusercontent.com/110661856/192775104-1869efd7-fcd5-46a1-8fa5-1c9377a516a1.png)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
