### ISSUE TITLE
Add "filter out tiny gaps" in the strength/infil section like orcaslicer.

### ISSUE THREAD

**Issue by djmarkino94** [bambulab/BambuStudio#3326]
Is it possible to add the "filter out tiny gaps" function in the strength/infil section like in orcaslicer? very useful for removing that annoying last step to plug the holes.

**Comment by djngnear** [comment]
Can you post pictures of examples please?

**Comment by djmarkino94** [comment]
> Can you post pictures of examples please?

![image](https://github.com/bambulab/BambuStudio/assets/111192738/5b56e589-3872-40b4-a6b7-c4b9890c8dd8)

**Comment by djmarkino94** [comment]
???? Its ok?

**Comment by djngnear** [comment]
It already has it. Just checked. But i meant examples of how it helps in the slicing view

**Comment by djmarkino94** [comment]
> It already has it. Just checked. But i meant examples of how it helps in the slicing view

Could you tell me what it's called and where it's located?

**Comment by djngnear** [comment]
Yeah, it's under the Strength/Sparse Infill section. I'm using the latest version 1.8.3.89. You probably don't have Develop Mode on. Open up the preferences and it's at the bottom.

**Comment by djmarkino94** [comment]
> Yeah, it's under the Strength/Sparse Infill section. I'm using the latest version 1.8.3.89. You probably don't have Develop Mode on. Open up the preferences and it's at the bottom.

Thank's so much mate

**Comment by djmarkino94** [comment]
I have try, but on bambustudio don't work🥶.i mean this: this is bambustudio https://github.com/bambulab/BambuStudio/assets/111192738/991fcc63-29d5-446d-b720-a2b71de7ce76

This is orcaslicer with tiny gala activated at value 100.

https://github.com/bambulab/BambuStudio/assets/111192738/7cf2150d-5a23-4bb3-8208-74c9ebd0db91

**Comment by djngnear** [comment]
I see what you mean. It doesn't work the same between the 2 slicers.

**Comment by djmarkino94** [comment]
> I see what you mean. It doesn't work the same between the 2 slicers.

Ok its possible to fix or to Add as orcaslicer ?

**Comment by djngnear** [comment]
> > I see what you mean. It doesn't work the same between the 2 slicers.
> 
> Ok its possible to fix or to Add as orcaslicer ?

I would assume so. Hopefully they'll put it on their to-do list
