### ISSUE TITLE
Purge into ______ checkmarks missing after newest update

### ISSUE THREAD

**Issue by she2dancer** [bambulab/BambuStudio#3327]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 12.6.4

### Printer

Bambu X-1C

### How to reproduce

Everytime I purge into an object the checkmarks are missing- as seen in pic
![IMG_5951](https://github.com/bambulab/BambuStudio/assets/155902093/1445e019-d4bb-456f-8bc9-3657aae9b633)

This is what it used to look like - 
![IMG_5944](https://github.com/bambulab/BambuStudio/assets/155902093/7fa01f9c-b21c-42d0-9dea-deef17f5c545)

### Actual results

![IMG_5951](https://github.com/bambulab/BambuStudio/assets/155902093/2530308d-62a5-457e-8a9f-2c11a6bb7920)

### Expected results

The checkmarks should show up when selected (or disappear when unselected). Right now purging into an object is a blind guess until you slice. 

### Project file & Debug log uploads

I don't have this. 
![IMG_5951](https://github.com/bambulab/BambuStudio/assets/155902093/d188a0b7-7f59-44c4-8277-1d0a3efabf5e)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
it been fixed , and you will get it in the next version.

**Comment by LiZ-Li-BBL** [comment]
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.03.89
Get the latest version here.
