### ISSUE TITLE
Support Angle will not allow a change to be made and is greyed out 

### ISSUE THREAD

**Issue by fastmike14** [bambulab/BambuStudio#3336]
### Bambu Studio Version

01.08.00.13      latest version no updates showing 

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10 home

### Printer

P1S and P1P

### How to reproduce

click on manual supports, manual, paint on support or even just checking enable supports. The angle threshold is stuck on 30 Deg and will not allow me to change the angle. I have tried various thing and will not allow angle change. 

### Actual results

The degree angle stays at 30 degrees no matter what setting are changed. I found online that was a fix in 1.8 release which I am currently running. 

### Expected results

angle stays as 30 Deg and is greyed out and will not allow a change of support angle. 

### Project file & Debug log uploads

![Ender_6_Linear_Rail_X-Axis_Mount_v2_Reinforced_VampyreX13](https://github.com/bambulab/BambuStudio/assets/130314584/2904ba09-eb5b-45cc-b5f5-4c3fd9cbf867)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
The option "support angle" is only used for auto support. For manual support you'll have to manually paint the areas to be supported.
