### ISSUE TITLE
filament numbers do not match AMS slots

### ISSUE THREAD

**Issue by bradanlane** [bambulab/BambuStudio#3341]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 14.2.1

### Printer

X1C

### How to reproduce

remove filament from AMS slot 1 (aka "A1")
resync AMS in Bambu Studio
Filament "1" in Bambu Studio is "A2" in AMS

### Actual results

Filament "1" in Bambu Studio is "A2" in AMS

### Expected results

Filament "1" should be empty and 
"2" in Bambu Studio should be "A2" in AMS

Note: this mismatch also breaks ".3mf" files as the file used the Bambu Studio number and not the AMS position for filament mapping to models.

### Project file & Debug log uploads

[camera_stand_left.3mf.zip](https://github.com/bambulab/BambuStudio/files/13876173/camera_stand_left.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
@bradanlane 
The current design is as such. Could you propose a new feature for us.   We will conduct a review rather than considering it a bug.

**Comment by walterwongbbl** [comment]
@bradanlane 
There is already a similar feature, so this issue will be closed.

**Comment by bradanlane** [comment]
If there is a similar issue open, please link it here so I can find it. Thank you.
