### ISSUE TITLE
Linux build fails due to undefined reference to symbol '_ZNK6icu_7211Formattable7getLongER10UErrorCode'

### ISSUE THREAD

**Issue by caco3** [bambulab/BambuStudio#3349]
### Bambu Studio Version

master (aee2df69)

### Where is the application from?

Built from source by yourself or others

### OS version

Ubuntu 23.10

### How to reproduce

I try to build master with the guide from 
On the cmd `cmake --build . --target install --config Release -j` fails with:
```bash
100%] Linking CXX executable bambu-studio
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_locale.a(formatter.o): undefined reference to symbol '_ZNK6icu_7211Formattable7getLongER10UErrorCode'
/usr/bin/ld: /lib/x86_64-linux-gnu/libicui18n.so.72: Fehler beim Hinzufügen von Symbolen: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/CMakeFiles/BambuStudio.dir/build.make:203: src/bambu-studio] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:540: src/CMakeFiles/BambuStudio.dir/all] Fehler 2
gmake: *** [Makefile:166: all] Fehler 2

```

### Actual results

fails to build

### Expected results

it builds :)

**Comment by lanewei120** [comment]
Sorry, I missed this issue before

did you build the dependence by your self?
could you show your full building steps

from your log, it seems bambu-studio is linked to the boost on your system
but our building process will link it to the one built by yourself
