### ISSUE TITLE
Printer Firmware Release Note contains incorrect spelling

### ISSUE THREAD

**Issue by utsxumiao** [bambulab/BambuStudio#3358]
### Bambu Studio Version

01.07.01.00

### Where is the application from?

Bambu Lab github releases

### OS version

Windows

### Printer

X1C

### How to reproduce

Go to device update tab and click on the Release Note link
![image](https://github.com/bambulab/BambuStudio/assets/1480980/dd9334f8-682f-495a-a70d-0c9d63f4f56b)

### Actual results

scren

### Expected results

screen

### Project file & Debug log uploads

Not relevant

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
@utsxumiao Thank you very much! We will strengthen copy checking
