### ISSUE TITLE
Flatpak: Flushing Volumes Dialog not displayed correctly

### ISSUE THREAD

**Issue by kadrim** [bambulab/BambuStudio#3373]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Built from source by yourself or others

### OS version

Ubuntu 22.04

### Printer

Bambu Lab X1C

### How to reproduce

1. Install Bambu Studio from Flatpak
2. Start Bambu Studio
3. Switch to Tab "Prepare"
4. Add some Filaments
5. Click on "Flushing Volumes"

### Actual results

The Dialog is not displayed correctly:

![grafik](https://github.com/bambulab/BambuStudio/assets/8304331/74d1bc25-7423-43fd-97a6-4f1a85c12b94)

### Expected results

Full Dialog Displayed, i.e.:

![grafik](https://github.com/bambulab/BambuStudio/assets/8304331/b02cacaf-69c1-45b0-8ba8-855b614c6307)

### Project file & Debug log uploads

no logs / project files needed to reproduce

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by kadrim** [comment]
I first came across this issue on my steam deck (steam os / arch linux) and wanted to give the new flatpak version of bambu studio a try.

Afterwards i tried to find out if it was related to the flatpak build by using my ubuntu 22.04 machine as reference. On ubuntu the AppImage build is displaying the "flushing volumes" correctly. Then i installed the flatpak version also on my ubuntu22.04 and there the dialog is broken so most probably only related to the flatpak build.

as i am not sure if this should be a bug report in this repo, could @hadess also have look please?

**Comment by kadrim** [comment]
if anything further is required, please let me know

**Comment by hadess** [comment]
> as i am not sure if this should be a bug report in this repo, could @hadess also have look please?

Please report Flatpak specific bugs at https://github.com/flathub/com.bambulab.BambuStudio/issues

**Comment by kadrim** [comment]
issue recreated here: https://github.com/flathub/com.bambulab.BambuStudio/issues/1

so closing this one
