### ISSUE TITLE
拓竹能否给出手动退料/进料的GCODE

### ISSUE THREAD

**Issue by LittleOAndLittleQ** [bambulab/BambuStudio#3385]
拓竹能否给出在打印机屏幕或studio、handy上点击退料/进料的GCODE？
我要的不是AMS进料退料的GCODE。感谢！
![image](https://github.com/bambulab/BambuStudio/assets/81701534/580f9ef8-50e4-4559-8cf2-b20ca19fe870)
![image](https://github.com/bambulab/BambuStudio/assets/81701534/cc7fc666-3df0-4352-9985-bc989b610f94)

**Comment by walterwongbbl** [comment]
@LittleOAndLittleQ 
https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/StatusPanel.cpp
代码在on_ams_load_curr的相关实现中

GCODE代码看文件
![image](https://github.com/bambulab/BambuStudio/assets/120699126/424f7362-f1a4-42ba-9961-658345fafb38)

**Comment by LittleOAndLittleQ** [comment]
您好，我看了您给出的这两段代码，ams_unload代码中似乎没有切刀切断耗材和控制挤出电机的部分，这段代码是否有缺失？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bambulab/BambuStudio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月16日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bambulab/BambuStudio] 拓竹能否给出手动退料/进料的GCODE (Issue #3385)





 
@LittleOAndLittleQ
 https://github.com/bambulab/BambuStudio/blob/master/src/slic3r/GUI/StatusPanel.cpp
 代码在on_ams_load_curr的相关实现中
 
GCODE代码看文件
 image.png (view on web)

**Comment by walterwongbbl** [comment]
@LittleOAndLittleQ 一部分操作不是由Studio发送G代码完成的，而是打印机的行为。
