### ISSUE TITLE
Update automatically enabled "Join Customer Experience Improvement Program"

### ISSUE THREAD

**Issue by vordenken** [bambulab/BambuStudio#3388]
### Bambu Studio Version

1.8.3.89

### Where is the application from?

Bambu Lab github releases

### OS version

macOS Sonoma

### Additional system information

MacBook Air m2

### Printer

BambuLab P1S

### How to reproduce

1. Update to 1.8.3.89
2. Open Settings
3. Take a look at option "Join Customer Experience Improvement Program"

### Actual results

The checkbox is checked
<img width="597" alt="image" src="https://github.com/bambulab/BambuStudio/assets/62395860/e940f914-cbd5-4840-b102-b3b370a9f976">

### Expected results

This checkbox should not be checked UNLESS the user is asked to allow it.

Checking this box without asking the user sounds like something illegal in the EU btw.

### Project file & Debug log uploads

[tutk_log_avapi_49019.txt](https://github.com/bambulab/BambuStudio/files/13950134/tutk_log_avapi_49019.txt)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@vordenken 

thanks for reporting this
we have already changed the GUI to following in this version
![image](https://github.com/bambulab/BambuStudio/assets/106916061/4f4411c7-21d3-46ce-a825-34981da59c02)

and you can disable it in the preference dialog
![image](https://github.com/bambulab/BambuStudio/assets/106916061/e1009e3d-ad69-485d-a4d5-38455c935d9a)

from your case, maybe it is selected before at the first setup?

**Comment by vordenken** [comment]
No I definitely did not agree to something like this.

**Comment by lanewei120** [comment]
> No I definitely did not agree to something like this.

@vordenken 

Please note that this checkmark might have been selected before by mistake? 
Either way, we will make ensure the selection works as expected. 

In your particular case, please disable it as mentioned before. 
If you wish, we can also assist you in deleting all the previous data. 
Please send us an email where you ask for the data to be deleted to our privacy email ([privacy@bambulab.com](mailto:privacy@bambulab.com)) and our team will assist you in solving this ASAP.

**Comment by austinwright** [comment]
This is still an issue. The box becomes re-checked after Bambu Studio is updated to a new version. @lanewei120 / @MklBambu FYI.

**Comment by BoBoYu-1** [comment]
@austinwright 
Thank you for your feedback;
After conducting several scenarios of tests on our side, the conclusion we reached is as follows: When installing, if the option of joining the plan is not selected, the preference settings will not be synchronized and automatically checked. 
For instance, if the option of joining the plan was not selected during the installation of the previous official version, or if the preference settings were not manually checked to join the plan, and then the V1.10.2.76 version was installed overwriting the previous one, the option of joining the plan in the preference settings will not be automatically checked. 
You can try again on your end. If you encounter any problems, please feel free to give us timely feedback.

**Comment by lanewei120** [comment]
Hello @austinwright 

we have confirmed again
after re-install the new version of Bambu Studio
the behavior of joining the plan or not keeps the same

that is to say
if you didn't join the plan in your previous version
after you re-install the new version
you still not joins the plan in the new version

**Comment by SRANCD** [comment]
> Hello [@austinwright](https://github.com/austinwright)
> 
> we have confirmed again after re-install the new version of Bambu Studio the behavior of joining the plan or not keeps the same
> 
> that is to say if you didn't join the plan in your previous version after you re-install the new version you still not joins the plan in the new version

Good morning, 

this issue is definetly not solved. 
I am on Bambu Studio 1.10.2.76 and the checkbox activated itself the 2nd time now. At first I wasn't sure whether I had clicked the checkbox by mistake, but after reading about the behaviour of automatically activating the checkbox for participation in the Customer Experience Program in various Internet articles I was aware and observed the status of the checkbox regularly. 
Now yesterday out of nowhere the checkbox was activated again and this time I was sure it was not checked by mistake. 

@lanewei120 @MklBambu @BoBoYu-1

**Comment by lanewei120** [comment]
> after reading about the behaviour of automatically activating the checkbox for participation in the Customer Experience Program in various Internet articles I was aware and observed the status of the checkbox regularly.
> Now yesterday out of nowhere the checkbox was activated again and this time I was sure it was not checked by mistake.

Hello @SRANCD 

do you mean the checkbox activated somewhere?
![Image](https://github.com/user-attachments/assets/3174ef85-2d2c-4005-9925-986ac80583fd)

we are not sure whether there is some bug or not
but from our local tests, we didn't meet this issue

have you deleted your BambuStudio.conf before?
or have you run the setup wizzard before?

could you help to give more clues to help us to find and solve this issue

thanks

**Comment by SRANCD** [comment]
> > after reading about the behaviour of automatically activating the checkbox for participation in the Customer Experience Program in various Internet articles I was aware and observed the status of the checkbox regularly.
> > Now yesterday out of nowhere the checkbox was activated again and this time I was sure it was not checked by mistake.
> 
> Hello [@SRANCD](https://github.com/SRANCD)
> 
> do you mean the checkbox activated somewhere? ![Image](https://github.com/user-attachments/assets/3174ef85-2d2c-4005-9925-986ac80583fd)
> 
> we are not sure whether there is some bug or not but from our local tests, we didn't meet this issue
> 
> have you deleted your BambuStudio.conf before? or have you run the setup wizzard before?
> 
> could you help to give more clues to help us to find and solve this issue
> 
> thanks

Hi @lanewei120 , 

yes - I am reffering to exactly this checkbox. 

I do **not** have deleted the BambuStudio.conf before. 
I have **not** run the setup wizzard before.

the time however since it lastly activated itself was weeks ago... since then I just worked with BambuStudio and frequently checked in the settings the status of this checkbox... yesterday it was out of nowhere activated again. 

Kind regards
