### ISSUE TITLE
Calibration Flow UI incorrect

### ISSUE THREAD

**Issue by designgears** [bambulab/BambuStudio#3392]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

1. Go to Device tab
2. Click on Calibration button
3. Run calibration
4. At `Sweeping XY mech mode` and `Motor noise calibration` step, notice they're inverted.

### Actual results

Incorrect step is show in the app and on the printer display.

`Sweeping XY mech mode` is highlighted when doing `Motor noise calibration`
`Motor noise calibration` is highlighted when doing `Sweeping XY mech mode`

![image](https://github.com/bambulab/BambuStudio/assets/799451/5c9a0961-7d40-401d-92b7-bab76540e66e)
![image](https://github.com/bambulab/BambuStudio/assets/799451/8cf350e8-0226-4305-983c-66381101d8bb)

### Expected results

The correct step should be highlighted for what is physically happening on the printer.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/13955305/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bam-winterfell** [comment]
hi@designgears 
Thank you for raising the question. I will try to reproduce this issue

**Comment by walterwongbbl** [comment]
Please use our latest 1.9.1 version
