### ISSUE TITLE
Text modifier does not slice correctly when using German Umlaut Ü

### ISSUE THREAD

**Issue by elsni** [bambulab/BambuStudio#3394]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

AMD Ryzen 7 3700X 8-Core
32GB RAM

### Printer

Bambu Lab A1

### How to reproduce

Open attached project
Move camera so that you look at the model (poker chip) from the bottom
click preview

![bambubug](https://github.com/bambulab/BambuStudio/assets/1834504/cb8b4dd6-d053-425f-a24d-41998dac3f45)

### Actual results

One of the dots of the Ü character is missing

### Expected results

Text is complete

### Project file & Debug log uploads

[bambubug.zip](https://github.com/bambulab/BambuStudio/files/13959997/bambubug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by elsni** [comment]
Fun fact: When I do mesh repair on the model, both Ü dots are missing.

**Comment by zhimin-zeng-bambulab** [comment]
@elsni  Could you scale this model larger? Because the area of ​​the Ü dots is too small so that it cannot be extruded normally.

**Comment by elsni** [comment]
I already found a workaround.. BUT:  Extruding one dot and leaving a hole where the other dot should be is unexpected behavior and should definitly be worth an investigation. Maybe the problem is the model - I was not able to reproduce it on a simple cube.
But the question is: WHY?

**Comment by zhimin-zeng-bambulab** [comment]
@QingZhangBambu  Please explain why two dots of similar size, one can be extruded, and the other cannot be extruded?

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/341b257e-97bb-4886-83b6-26a6c45037fe)
you can adjust min line width to get wall, for the left part area just smaller than the threshold
