### ISSUE TITLE
Non-standard Windows UI

### ISSUE THREAD

**Issue by chopsywa** [bambulab/BambuStudio#34]
The UI, whilst pretty, does not conform to Windows convention. If I slide the program to a side, or corner, it should automatically size to that part of the screen. In Windows 11, if I hover over the maximise/restore button, it should offer me standard Windows layout patterns.

**Comment by RobinWhitfield** [comment]
+1 for this.

The lack of window snapping features is definitely an issue, especially with larger and widescreen moinitors where people regularly use a portion of the screen.

The interface *can* be resized, so its implementation would not fundamentally cause problems there.

**Comment by YifanWuBambu** [comment]
It is fixed in the latest version.
