### ISSUE TITLE
Manually set Bridging Angle

### ISSUE THREAD

**Issue by cmspooner** [bambulab/BambuStudio#340]
In PrusaSlicer there is an option to change the angle of bridges. This is useful when I embed rectangular magnets in my prints. the default angle sometimes goes the longer direction; when I'd rather them go the shorter direction. I also use the setting with modifiers to handle the situation where I have two magnets in different directions.

**Comment by wirlybird** [comment]
This is also available in Simplify 3D and can be essential.

**Comment by SaltWei** [comment]
Will be included in next release about changing the angle of external bridge manually

**Comment by wirlybird** [comment]
Thank you!  Great to hear!

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
