### ISSUE TITLE
从makerworld下载的项目，打印时无法修改任务名称。

### ISSUE THREAD

**Issue by chenminjx** [bambulab/BambuStudio#3401]
### Bambu Studio Version

所有版本

### Where is the application from?

Bambu Lab Official website

### OS version

win11

### Additional system information

此bug与硬件系统无关。

### Printer

p1s、x1c

### How to reproduce

打开从makerworld下载的项目，发送打印任务时无法修改任务名称。

### Actual results

从makerworld下载的项目，发送打印任务时无法修改任务名称，或者说修改了也无效，上传到打印机后的任务名称都是makerworld项目作者上传时填写的模型名称。这就导致项目有多盘打印需求时无法通过任务名称来分辨。
![05455de4ffd156133076512c2a9d6a3](https://github.com/bambulab/BambuStudio/assets/88026756/a064d7d3-d7c5-47d6-95a0-37e50c261699)

### Expected results

无

### Project file & Debug log uploads

无

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
@chenminjx 
是的，因为如果你的模型文件来自商城，我们将始终显示模型在商城中的信息。
