### ISSUE TITLE
Filament loading buttons cutoff

### ISSUE THREAD

**Issue by joshspires** [bambulab/BambuStudio#3402]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 23H2 Build 22635.3061

### Additional system information

Framework Laptop 13
- i5-1340P
- 16GB RAM

### Printer

Bambu Lab P1S

### How to reproduce

1. Open BambuStudio
2. Go to device tab
3. Look at the filament control section

### Actual results

The buttons overflow the width of the section, cutting a small section off. This happens regardless of the window size.
![Screenshot 2024-01-18 175656](https://github.com/bambulab/BambuStudio/assets/24408714/c4c9fb9d-4cb9-4be7-bd77-3e8f26c4083f)

### Expected results

The buttons shouldn't go over the allowed width of the section. 

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bam-winterfell** [comment]
hi@joshspires
It is indeed a bug, and we will fix it in the future. Thank you for your feedback.

**Comment by joshspires** [comment]
This looks to have been fixed in the latest release.
