### ISSUE TITLE
Bambu Studio not connecting to server.

### ISSUE THREAD

**Issue by JalalSayed1** [bambulab/BambuStudio#3420]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 22.04.3 LTS

### Printer

Bambu Lab X1C

### How to reproduce

1. Open the Bambu Studio.
2. Go to device.
3. In the left side, it says failed to connect to the server.

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/92950538/ee2ce560-1dea-475a-9b65-763301b0e37e)

### Expected results

Access the printer.

### Project file & Debug log uploads

[debug_Fri_Jan_19_10_35_49_137393.log.zip](https://github.com/bambulab/BambuStudio/files/13988111/debug_Fri_Jan_19_10_35_49_137393.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by StoneLiBambu** [comment]
Hi,
The server may be unstable and you can check service status on https://status.bambulab.com/history?page=2

Thanks!

Stone Li
