### ISSUE TITLE
Change Colors and Forms

### ISSUE THREAD

**Issue by daluro** [bambulab/BambuStudio#3427]
### Bambu Studio Version

v01.08.04.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1 Series

### How to reproduce

<img width="170" alt="screenshot_20240119_145320" src="https://github.com/bambulab/BambuStudio/assets/77620319/e4b5fc20-a1a8-4e56-bf2b-495b391f84f0">

If you click on "Höhenreichweite" and do some Changes, you are dont 
you will then no longer be able to make other settings. you can only change the colours via "Numbers". you cannot do anything with the mouse. you can click but nothing happens

### Actual results

nothing happens

### Expected results

you can change the tools

### Project file & Debug log uploads

/nV

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
![提供日志](https://github.com/bambulab/BambuStudio/assets/132528822/036ea4f5-4e53-40f4-8f6a-3e5f3ac2c93c)
Hello, can you provide some logs according to this operation according this gif. If you could record a video of this issue, it would be even more convenient for us to solve this problem. thanks

**Comment by Haidiye00** [comment]
Please download and use the latest version. If there are still any issues, please use pictures or screenshots to describe your ideas. Thank you

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
