### ISSUE TITLE
Error after Update on the PC running Windows 11--Fatal Error, exception catches invalid string position

### ISSUE THREAD

**Issue by Craigphi** [bambulab/BambuStudio#3428]
### Bambu Studio Version

v01.01.04.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X!C

### How to reproduce

I downloaded the new update.  I cannot open Bambu Studio. I get the error message: Fatal Error, exception catches invalid string position. I have installed it a second time and get the same error. So I cannot open Bambu Studio now after the update. 

### Actual results

Fatal Error, exception catches invalid string position.

### Expected results

I expect Bambu Stuiio to open

### Project file & Debug log uploads

No file to attach

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
this is very likely caused by the config file corrupted
could you give a snapshot of folder?
![image](https://github.com/bambulab/BambuStudio/assets/106916061/a621ef54-edda-4e5f-82cf-3b1edd94dd92)

and please try following steps:
1. close bambustudio
2. remove C:\Users\user.name\AppData\Roaming\BambuStudio\system
and try again
if still fails
3.  try to backup and then remove C:\Users\user.name\AppData\Roaming\BambuStudio\BambuStudio.conf
then try again

**Comment by Craigphi** [comment]
Thank you for your reply. I solved the problem by uninstalling the app via Windows add-remove programs and deleting all user files. Then I reinstalled BambuStudio and it works again. Thanks again,Craig Phillips Sent from my iPhoneOn Jan 21, 2024, at 7:50 PM, Lane.Wei ***@***.***> wrote:﻿
this is very likely caused by the config file corrupted
could you give a snapshot of folder?
image.png (view on web)
and please try following steps:

close bambustudio
remove C:\Users\user.name\AppData\Roaming\BambuStudio\system
and try again
if still fails
try to backup and then remove C:\Users\user.name\AppData\Roaming\BambuStudio\BambuStudio.conf
then try again

**Comment by lanewei120** [comment]
Glad to see this issue solved

**Comment by MangoPies** [comment]
Thank you for the help. Had the same issue. The last step to delete bambustudio.conf was the fix

**Comment by GetUpdate** [comment]
Thank you deleting the .conf solved it ! 
Whish you all the best !
Kind Regards GetUpdate

PS: I first try a uninstall and reinstall but this doesn't fix it

**Comment by danelliottvt-jpg** [comment]
> this is very likely caused by the config file corrupted could you give a snapshot of folder? ![image](https://github.com/bambulab/BambuStudio/assets/106916061/a621ef54-edda-4e5f-82cf-3b1edd94dd92)
> 
> and please try following steps:
> 
> 1. close bambustudio
> 2. remove C:\Users\user.name\AppData\Roaming\BambuStudio\system
>    and try again
>    if still fails
> 3. try to backup and then remove C:\Users\user.name\AppData\Roaming\BambuStudio\BambuStudio.conf
>    then try again

I followed the above advice: deleted the "system" folder, deleted the BambuStudio.conf file. 
Relaunch Bambu Studio, it runs me through the initial setup steps of selecting devices and materials to use, links to my bambu account. 

Runs fine in this one instance.

but if I quit Bambu and relaunch it, the same error repeats. When it writes the new config file, it embeds the same error. (though the path to \downloads is correct.)
I'd like to not keep rebuilding my app.......

**Comment by 3dcreationsbyiceman-ops** [comment]
Thanks alot!! it worked.  Shortcut = press "window key + R.....type in "%appdata%"
