### ISSUE TITLE
Printing multiple items as one object

### ISSUE THREAD

**Issue by Mikebau5** [bambulab/BambuStudio#3431]
For printing multiple small items in different colors there is no option to print multiple objects as 'one' object before switching filament.

I'd like to see an option to select items to print per layer (let's say the 8 ducks) before switching to the blue card holder items (and print them together per layer as if it were one object). This helps to prevent a huge filament waste

![image](https://github.com/bambulab/BambuStudio/assets/17548309/d6999ffb-f8da-4e32-a3d9-ec6dc55daa3e)

![image](https://github.com/bambulab/BambuStudio/assets/17548309/d9af9ee3-0eec-4d6a-abad-e81f13bfc81b)

**Comment by MadMax389** [comment]
Does it work if you assemble all the ducks into one object?

**Comment by Mikebau5** [comment]
> Does it work if you assemble all the ducks into one object?

How does one achieve this exactly. I couldn't find this option in Bambu Studio, either that or I'm blind

**Comment by MadMax389** [comment]
Select them all, r-click, assemble.

**Comment by Mikebau5** [comment]
Okay Epic, that worked exactly as I hoped!
