### ISSUE TITLE
no video feed in bambu studio - "Missing BambuSource component registered for media playing! please reinstall bambu studio or seek after sales support"

### ISSUE THREAD

**Issue by ryanmcgoldrick47** [bambulab/BambuStudio#344]
Tried uninstalling and reinstalling, tried older and latest version of software.

Trying to view the video feed of printer that is at home from an install of Bambustudio on my work laptop at work.

bambu handy on iOS works with video feed, and bambu studio at home works with video feel but not on my work laptop.

Windows 10
Dell precision 7560 laptop

**Comment by ryanmcgoldrick47** [comment]
![image](https://user-images.githubusercontent.com/37097252/193170573-a588e7f4-6b1e-47b6-ab65-efdd55910ffc.png)

**Comment by bambu123** [comment]
Maybe BambuSource.dll is blocked by overly sensitive antivirus software.

Here is the FAQ about the details.
https://wiki.bambulab.com/en/software/bambu-studio/faq/live-view

**Comment by ryanmcgoldrick47** [comment]
@bambu123 
I went to the IT admin, we turned off all anti virus software for 4 hours unintalled app, reinstalled app. Same error message appears, I checked the Appdata Plugins folder for Bambusource.dll and the file is indeed there, I also checked the security permissions and it has full permissions for everything. so can confirm it is not antivirus software as also checked event logs for antivirus and nothing came up before we disabled it.

**Comment by ryanmcgoldrick47** [comment]
![image](https://user-images.githubusercontent.com/37097252/193189130-bd8e8833-e7d9-44c1-b186-f15a4e44b5d4.png)

![image](https://user-images.githubusercontent.com/37097252/193189183-9929f186-83aa-4b06-bb58-0526a2a1fc0d.png)

**Comment by bambu123** [comment]
Please check the registry. Open Power shell or cmd.exe, and execute the following scripts:

REG QUERY HKEY_CLASSES_ROOT\bambu
REG QUERY "HKEY_CLASSES_ROOT\CLSID\{233E64FB-2041-4A6C-AFAB-FF9BCF83E7AA}\InProcServer32"

**Comment by bambu123** [comment]
Make sure not to install BambuStudio with the Administrator account, and use it with another Windows user account.

**Comment by ryanmcgoldrick47** [comment]
> xecute the following scripts:
> 
> REG QUERY HKEY_CLASSES_ROOT\bambu

![image](https://user-images.githubusercontent.com/37097252/193211070-e7e77b4d-985f-4410-829e-e7599b1efb57.png)

**Comment by ryanmcgoldrick47** [comment]
> Make sure not to install BambuStudio with the Administrator account, and use it with another Windows user account.

everything you install on work computers require administrator to install, we cannot install without them logging in for elevated permissions

**Comment by ryanmcgoldrick47** [comment]
@bambu123 
![image](https://user-images.githubusercontent.com/37097252/193442014-1cdbae53-061e-4f8d-800f-6dc472995a59.png)

**Comment by ryanmcgoldrick47** [comment]
![image](https://user-images.githubusercontent.com/37097252/193442039-3a5ffb20-8e75-4b35-9832-7306f5f68d77.png)
@bambu123 haven't tried running powershell or cmd as admin yet as need to be back in office infront of IT so they can login as admin to try
but doing it myself thats what I get.

**Comment by bambu123** [comment]
The error code says to have none permission to register the dll. it is because something block it. maybe anti-virsus or some secure strategy.

**Comment by ChrisG-hub** [comment]
Just run the installer with administrator rights.
![image](https://user-images.githubusercontent.com/74129531/193444120-b811fd75-7fdf-4f24-8adb-fd740c8faa8a.png)

**Comment by ryanmcgoldrick47** [comment]
@ChrisG-hub thanks for the suggestion but we already tried doing this and same error happens

**Comment by ChrisG-hub** [comment]
Well, i would use an old fashion elevated command prompt to try to register the dll.
%systemroot%\SysWoW64\regsvr32 %APPDATA%\BambuStudio\plugins\BambuSource.dll 
or 
use the 32-bit version of Regsvr32 to register a 32-bit DLL on a 64-bit version of Windows If you receive an error when registering a 32-bit DLL on a 64-bit version of Windows, follow these steps:

Open an elevated command prompt.
Copy or move the **BambuSource.dll** to the %systemroot%\SysWoW64 folder.
%systemroot%\SysWoW64\\regsvr32 **BambuSource.dll**
Info:
The 64-bit version is %systemroot%\System32\regsvr32.exe.
The 32-bit version is %systemroot%\SysWoW64\regsvr32.exe

**Comment by Pmant** [comment]
Same issue here but with the portable (zip) version. On first start it installs the networking plugin which is working fine but the video plugin does not work.

**Comment by ryanmcgoldrick47** [comment]
@ChrisG-hub Tried all of the steps you suggested above but nothing changes, still same error in bambu studio, and I get this when entering that top code you wrote, even after moving the .dll manually into both the 64 and 32 bit version. 
![image](https://user-images.githubusercontent.com/37097252/193701872-ecd7cd00-b3a2-4d58-83e4-4a22a3be88e7.png)

**Comment by bambu123** [comment]
> ![image](https://user-images.githubusercontent.com/37097252/193442039-3a5ffb20-8e75-4b35-9832-7306f5f68d77.png) @bambu123 haven't tried running powershell or cmd as admin yet as need to be back in office infront of IT so they can login as admin to try but doing it myself thats what I get.

The power shell can't expand %APPDATA%.

**Comment by bambu123** [comment]
> @ChrisG-hub Tried all of the steps you suggested above but nothing changes, still same error in bambu studio, and I get this when entering that top code you wrote, even after moving the .dll manually into both the 64 and 32 bit version. ![image](https://user-images.githubusercontent.com/37097252/193701872-ecd7cd00-b3a2-4d58-83e4-4a22a3be88e7.png)

No, do not register BambuSource.dll with the 32 bits regsvr32. It is 64 bits binary.

**Comment by bambu123** [comment]
Secure strategies must have blocked the register.

**Comment by bambu123** [comment]
> Same issue here but with the portable (zip) version. On first start it installs the networking plugin which is working fine but the video plugin does not work.

The BambuStudio installer will register BambuSource for video playing. If you use the zip package of BambuSource, you should register BambuSource using regsvr32 in cmd.exe. Also, you need to install the fonts and the edge runtime.

**Comment by bambu123** [comment]
A new version of Bambu Studio will retry register BambuSource. You can try it to see what happens.

**Comment by bambu123** [comment]
@ryanmcgoldrick47 please help try the new version of Bambu Studio.

**Comment by bambu123** [comment]
@ryanmcgoldrick47 Have the problem been solved?

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
