### ISSUE TITLE
Sync AMS Issue

### ISSUE THREAD

**Issue by Aquapura4** [bambulab/BambuStudio#3451]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Mac Sonoma 14.2.1

### Additional system information

M2 Chip

### Printer

Bambu A1 Mini

### How to reproduce

Preconditions
1. Have AMS
2. Add filament so that:

Slot 1 = Generic PLA
Slot 2 = Generic PETG
Slot 3 = Generic PLA
Slot 4 = Generic PLA

Start 
1. Click on the filament 'sync' or 'resync'

### Actual results

Software will sync with 5 filaments which is wrong. 

When trying to send to the printer even though all the filaments are the same. The printer will not allow the PETG to be selected. 

### Expected results

Should sync with correct filaments
Should allow selection of PETG when all filaments are the same. 

### Project file & Debug log uploads

[CubeBUG TEST.3mf.zip](https://github.com/bambulab/BambuStudio/files/14000450/CubeBUG.TEST.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Aquapura4** [comment]
This could also be firmware related because i can't print with PETG when selecting it with the printer either

**Comment by bam-winterfell** [comment]
hi@Aquapura4 
The first question : After you click the sync button，external materials will also be synchronized to the prepare page, so the fifth material is external materials,
![image](https://github.com/bambulab/BambuStudio/assets/142556838/61842551-c62f-4e90-b3dc-1f8c91f3a966)
![image](https://github.com/bambulab/BambuStudio/assets/142556838/2396af12-fe0d-40e6-afc1-a0a3b3cb4ee7)

The second question is that the printer will not allow the PETG to be selected. Would you please record a video to recreate the situation when the problem occurred?

**Comment by bam-winterfell** [comment]
hi@Aquapura4 
If your problem is not resolved, please create a new issue.
