### ISSUE TITLE
Calibration 

### ISSUE THREAD

**Issue by quiricro** [bambulab/BambuStudio#3452]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MAC OS 14.2.1

### Printer

Bambu Lab X1 Carbon

### How to reproduce

Start Calibration

### Actual results

Homing of the Z-axis failed (0300 4000 185620)

### Expected results

The calibration should be completed

### Project file & Debug log uploads

Archiv.zip

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@quiricro  Could you upload your log files?

**Comment by zhimin-zeng-bambulab** [comment]
@quiricro 
Is the calibration you clicked on the device page? Could you take a screenshot to indicate the location?
In addition, could you also upload the logs?

**Comment by quiricro** [comment]
Hi

Thank you for your feedback and sorry for the late reply.
The message is the same when starting the calibration directly on the device or via the software.
I have noticed that at the start of printing, after cleaning the print head, some filament is still running and pulling threads. In the front area it does not seem to interfere with the calibration, while in the rear area (at the cleaning position) the print head is slightly lifted by the filament.
Today the calibration went through on the 4th attempt.
I hope that the correct LOG file is attached.

Sincerely

Roberto

Von: zhimin-zeng-bambulab ***@***.***>
Datum: Donnerstag, 1. Februar 2024 um 10:56
An: bambulab/BambuStudio ***@***.***>
Cc: quiricro ***@***.***>, Mention ***@***.***>
Betreff: Re: [bambulab/BambuStudio] Calibration (Issue #3452)

@quiricro<https://github.com/quiricro>
Is the calibration you clicked on the device page? Could you take a screenshot to indicate the location?
In addition, could you also upload the logs?

**Comment by zhimin-zeng-bambulab** [comment]
@quiricro ![image](https://github.com/bambulab/BambuStudio/assets/120697589/c27447e3-3faa-4d90-9fb4-a4fc3eaf1eef)
Is the calibration clicked here on Studio?

**Comment by zhimin-zeng-bambulab** [comment]
@quiricro  Could you confirm whether you clicked on this calibration. And could you upload logs when you encounter problems?

**Comment by quiricro** [comment]
Good evening
I just wanted to let you know that the problem has been solved after the printer was repositioned.
It seems that the previous base was not stable enough.

The printer has been working without any problems since then

Thank you for your efforts
Kind regards

Von: zhimin-zeng-bambulab ***@***.***>
Datum: Mittwoch, 21. Februar 2024 um 03:18
An: bambulab/BambuStudio ***@***.***>
Cc: quiricro ***@***.***>, Mention ***@***.***>
Betreff: Re: [bambulab/BambuStudio] Calibration (Issue #3452)

@quiricro<https://github.com/quiricro> Could you confirm whether you clicked on this calibration. And could you upload logs when you encounter problems?

**Comment by zengzm1212** [comment]
Closed due to inability to reproduce

**Comment by zhimin-zeng-bambulab** [comment]
Closed due to inability to reproduce
