### ISSUE TITLE
brim - object space

### ISSUE THREAD

**Issue by 3rdSt** [bambulab/BambuStudio#3458]
I downloaded the software on a new laptop and the brim-object gap is no longer an option on the "others" tab.   Will it return??

**Comment by LJKraus** [comment]
Brim-object gap is  still available in Studio 1.8.4.51.

Did you enable the "Advance" Process menus?
![image](https://github.com/bambulab/BambuStudio/assets/139707784/811aef19-1a41-4747-889e-6ca230563db3)

**Comment by 3rdSt** [comment]
Nope.  Totally forgot about that option.   Did it and it’s there now.    Thanks Have an amazing day! www.thirdststudio.comOn Jan 22, 2024, at 8:36 AM, LJKraus ***@***.***> wrote:﻿
Brim-object gap is  still available in Studio 1.8.4.51.
Did you enable the "Advance" Process menus?
image.png (view on web)
