### ISSUE TITLE
Unable to change flushing volume on Flatpak version of Bambu Studio

### ISSUE THREAD

**Issue by AeroBliss** [bambulab/BambuStudio#3467]
### Bambu Studio Version

1.8.4.51 for both the Flatpak and AppImage tested

### Where is the application from?

Built from source by yourself or others

### OS version

Linux Mint 21.3 Cinnamon

### Printer

Bambu Lab P1S

### How to reproduce

1. Install Flatpak version of Bambu Studio on Linux Mint
2. Open [this profile](https://makerworld.com/en/models/112380#profileId-129738) inside Bambu Studio
3. Click on "Flushing volumes" under the Filament menu
4. Blank window appears

### Actual results

When running BambuStudio Flatpak
![Screenshot from 2024-01-23 23-56-34](https://github.com/bambulab/BambuStudio/assets/84479813/86905e87-c509-46f3-a5bd-a904e342b709)

### Expected results

When running "BambuStudio_linux_ubuntu_v01.08.04.51_20240117.AppImage"
![Screenshot from 2024-01-23 23-59-57](https://github.com/bambulab/BambuStudio/assets/84479813/ea37b473-8b77-4027-ba0a-306b8079ccab)

### Project file & Debug log uploads

Project File: 
[Project.zip](https://github.com/bambulab/BambuStudio/files/14033838/Project.zip)

Log File: 
[Log.zip](https://github.com/bambulab/BambuStudio/files/14033841/Log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by hadess** [comment]
Known issue, likely a wxWidgets problem:
https://github.com/flathub/com.bambulab.BambuStudio/issues/1

**Comment by hadess** [comment]
There will be a test build in https://github.com/flathub/com.bambulab.BambuStudio/pull/12 shortly

**Comment by AeroBliss** [comment]
https://github.com/flathub/com.bambulab.BambuStudio/pull/12 fixes issue. Closing.
