### ISSUE TITLE
Google Login Broken - API Error

### ISSUE THREAD

**Issue by sightlessace** [bambulab/BambuStudio#3474]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 14.2.1

### Additional system information

2023 Mac Mini, M2 Proc, 8GB RAM

### Printer

Bambu X1C

### How to reproduce

1. Go to 'Home' tab
2. Click 'Login/Register'
3. Select Google Login

### Actual results

Browser opens to go to the authentication process, but then times out. 
![Screenshot 2024-01-24 at 6 53 15 PM](https://github.com/bambulab/BambuStudio/assets/33377345/180b6afe-6ca6-47f0-a66a-76b3a2eb1789)

### Expected results

Successful Login, Google Auth prompt.

### Project file & Debug log uploads

Ran network test, all pass except HTTP Service which says it requires you to be logged in. 

Output - 

Wed Jan 24 19:02:12:start_test_sequence
Wed Jan 24 19:02:12:test bing start…
Wed Jan 24 19:02:12:[test_bing]: url=http://www.bing.com/
Wed Jan 24 19:02:12:test bing ip resolved = 104.117.244.88
Wed Jan 24 19:02:12:test bing ok
Wed Jan 24 19:02:12:test bambulab start…
Wed Jan 24 19:02:12:[test_bambulab]: url=https://api.bambulab.com/v1/iot-service/api/slicer/resource?name=slicer&version=01.08.04.51&guide_version=00.00.00.01
Wed Jan 24 19:02:12:test bambulab ip resolved = 104.18.2.216
Wed Jan 24 19:02:12:test bambulab ok
Wed Jan 24 19:02:12:test storage start…
Wed Jan 24 19:02:12:[test_oss]: url=http://upload-file.bambulab.com
Wed Jan 24 19:02:13:test storage ok
Wed Jan 24 19:02:13:test storage upgrade start…
Wed Jan 24 19:02:13:[test_oss_upgrade]: url=http://upgrade-file.bambulab.com
Wed Jan 24 19:02:14:test storage upgrade ok
Wed Jan 24 19:02:14:test storage download start…
Wed Jan 24 19:02:14:[test_oss_download]: url=https://api.bambulab.com/v1/iot-service/api/slicer/resource?slicer/plugins/cloud=01.08.04.00
Wed Jan 24 19:02:14:downloading 10%
Wed Jan 24 19:02:14:downloading 20%
Wed Jan 24 19:02:14:downloading 30%
Wed Jan 24 19:02:14:downloading 40%
Wed Jan 24 19:02:14:downloading 50%
Wed Jan 24 19:02:15:downloading 60%
Wed Jan 24 19:02:15:downloading 70%
Wed Jan 24 19:02:15:downloading 80%
Wed Jan 24 19:02:15:downloading 90%
Wed Jan 24 19:02:15:downloading 100%
Wed Jan 24 19:02:15:test storage download ok
Wed Jan 24 19:02:15:test plugin download start…
Wed Jan 24 19:02:15:[test_plugin_download]: downloadurl=https://public-cdn.bambulab.com/upgrade/studio/plugins/01.08.04.03/7e4b636804/mac_01.08.04.03.zip
Wed Jan 24 19:02:15:downloading 5%
Wed Jan 24 19:02:15:downloading 10%
Wed Jan 24 19:02:15:downloading 15%
Wed Jan 24 19:02:15:downloading 20%
Wed Jan 24 19:02:15:downloading 25%
Wed Jan 24 19:02:15:downloading 30%
Wed Jan 24 19:02:15:downloading 35%
Wed Jan 24 19:02:15:downloading 40%
Wed Jan 24 19:02:15:downloading 45%
Wed Jan 24 19:02:15:downloading 50%
Wed Jan 24 19:02:15:downloading 55%
Wed Jan 24 19:02:15:downloading 60%
Wed Jan 24 19:02:15:downloading 65%
Wed Jan 24 19:02:15:downloading 70%
Wed Jan 24 19:02:15:downloading 75%
Wed Jan 24 19:02:15:downloading 80%
Wed Jan 24 19:02:15:downloading 85%
Wed Jan 24 19:02:15:downloading 90%
Wed Jan 24 19:02:15:downloading 95%
Wed Jan 24 19:02:15:downloading 100%
Wed Jan 24 19:02:15:test plugin download ok
Wed Jan 24 19:02:15:end_test_sequence

![Screenshot 2024-01-24 at 6 56 08 PM](https://github.com/bambulab/BambuStudio/assets/33377345/4b02ffaf-2b02-4c4e-89ac-9c283c441bdb)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by StoneLiBambu** [comment]
I tried the lastest version and login successfully.
https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.58


Thanks!
Stone Li
