### ISSUE TITLE
The Layer height limits are not correctly defined in the Bambu Lab A1 0.2 nozzle preset.

### ISSUE THREAD

**Issue by amzaldua** [bambulab/BambuStudio#3475]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Mac OS Sonoma 14.2.1

### Additional system information

Apple M1 Macbook

### Printer

Bambu Lab A1

### How to reproduce

Go to "Bambu Lab A1 0.2 nozzle preset/Extruder/Layer height limits" and check the MAX and MIN values.

### Actual results

It shows the same values as the Bambu Lab A1 0.4 nozzle:
0.08 for the MIN
0.28 for the MAX

### Expected results

0.04 for the MIN
0.14 for the MAX

### Project file & Debug log uploads

<img width="584" alt="Captura de pantalla 2024-01-25 a las 1 31 01" src="https://github.com/bambulab/BambuStudio/assets/116205677/b57f74e9-c7d6-494e-a2eb-86c98a5a043c">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
why it should be from 0.04 to 0.14?

**Comment by amzaldua** [comment]
Because these values are the same as those defined in all other models of Bambu Lab for a 0.2 nozzle.

**Comment by QingZhangBambu** [comment]
@XunZhangBambu check this please

**Comment by XunZhangBambu** [comment]
@amzaldua  Thanks. Will fix it soon.
