### ISSUE TITLE
Build Plate not showing the Build plate info, all build plates info blacked out

### ISSUE THREAD

**Issue by NDW89** [bambulab/BambuStudio#3484]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 

### Printer

X1 Carbon

### How to reproduce

No reproducing see photo, all build plate selected they are blacked out.  When I first installed software 3 months ago it worked then after a few upgrades the build plates started blacking out like you see in the photos.   I have tried to uninstall and reinstall, install over and nothing changes.
![build plates missing info](https://github.com/bambulab/BambuStudio/assets/157831584/4871695c-8b0a-4acd-bfc0-998ccde2fc69)

### Actual results

build plates  info is blacked out on all build plates selected

### Expected results

build plates  info is blacked out on all build plates selected

### Project file & Debug log uploads

[Build Plate Issue.zip](https://github.com/bambulab/BambuStudio/files/14067738/Build.Plate.Issue.zip)
3mf files attached

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
This issue has been fixed, please wait for v1.9 version
