### ISSUE TITLE
Slicing Options

### ISSUE THREAD

**Issue by Bobdainstigator** [bambulab/BambuStudio#349]
Can you please update bambu Labs studio to allow the Even Odd slicing option that has been available in Prusa since 2.4

I would like to be able to print 3d Lab print files but am not able to do so without the even odd slicing option.

https://help.prusa3d.com/ja/article/slicing-mode_301501

Thank you for your assistance.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
