### ISSUE TITLE
Inconsistent behaviour with support on bridges

### ISSUE THREAD

**Issue by chopsywa** [bambulab/BambuStudio#35]
It seems that the "Max bridge length only works sometimes.

If I start a new model, set to 0.24mm Draft @BBL X1C and turn on support, I can load a model and supports will be spaced 20mm apart on bridges (20mm is the default value).

If I then change to
 any other quality level (lower, or higher) I get solid supports across a bridge. Further I cannot then switch back to .24mm. I have to restart the program to get it to work on my bridge.
![20mmspreadbridge](https://user-images.githubusercontent.com/109642777/179893918-8f32f422-754a-4dc0-b235-704968272142.png)
![solidfillbridge](https://user-images.githubusercontent.com/109642777/179893909-e00f26d7-8790-41fa-a150-c38948a5e3b2.png)

**Comment by tangketan** [comment]
Hi! We'll release a new version soon, in which the behavior of "Max bridge length" is redesigned. This bug could not be repeated in this new version. Try out! And please let us know for any further issue.

**Comment by chopsywa** [comment]
I have installed 10.1.0.13 and the behavior is consistent now. Thanks.
