### ISSUE TITLE
Rewind of fillament to AMS cause jam

### ISSUE THREAD

**Issue by Ghuru42** [bambulab/BambuStudio#3505]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Ventura 13.2.1

### Additional system information

Apple MacBook air M1

### Printer

Bambu Lab X1 Carbon

### How to reproduce

During printing the machine sometimes unload the filament from the printhead and returns it all the way to the AMS.
Sometimes this causes the filament to feed under it self as the spool is not rotiating fast enough.

I also had an instasans where the this happend just as the filament ran out on the spool, but the end has not yet pased into the feeder, making for a spagetti tangle inside the AMS where the filament made a knot on it self.

Why does the machine do this rewind of the filament during print? Is it actually needed???

### Actual results

Filament get tangle under it self on the spool
Filament becomes spagetti maze inside AMS
Filament stuck and the printer halts.

### Expected results

Dont do the rewind during print.

### Project file & Debug log uploads

Same with all projects.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by pichen2021** [comment]
Hi @Ghuru42 
This may be an AMS synchronization abnormality issue, could you please open a ticket in our [support page](https://bambulab.com/en/my/support/tickets) and upload the log for futher analysis. 
Thanks
