### ISSUE TITLE
拓竹丧尽天良，修改默认参数而不通知！

### ISSUE THREAD

**Issue by bsx1990** [bambulab/BambuStudio#3509]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

all

### Printer

A1 mini

### How to reproduce

拓竹将 A1 mini 默认的象脚补偿从原来的`0.15`修改成了`0`，而且没有任何通知用户这一改动的地方！

---
# 事故介绍
之前一直使用老版本的软件切片，用默认的0.15的象脚补偿没有问题，之后就一直习惯了直接拖拽模型，点击切片单盘，然后直接打印。

前几天脑子抽了，更新了拓竹的新版本，然后依旧是拖拽模型，点击切片单盘，然后直接打印。

但是，拓竹修改了默认的象脚补偿，从0.15改成了0！！！ 修改的提交链接：https://github.com/bambulab/BambuStudio/commit/e6d2c532d023f31d59d5b0da61a5fb1edb9d9772
修改的原因居然是他们自己测试了一下没事！！！！！！

之后跟拓竹客服的沟通更是令人寒心！！！拓竹的技术部分信口雌黄、敷衍消费者、谎话连篇！！！
---
# 沟通经历
我是需要打印好几十套的类似华容道的装配玩具，这种玩具对于配合度有较高的要求。所以我特意在模型里面留了0.1mm的收缩量，就是为了保证可以完美装配。去年10月份到11月份的时候，用默认参数打印了六十多套，一直都没什么问题。上周有客户复购，于是又打算重新打印三十多套。

因为之前的切片会提示X轴松动，需要自己修改GCode，所以这次看到版本更新，以为过去了这么久了，应该修复了这个问题就更新了一下版本。然后在版本更新之后，并没有任何的默认参数修改的提示，于是我依旧把模型拖进去，直接打印了。

直到三十多套的零件都快打印完成之后，我检查零件准备组装发货的时候，才发现零件居然有象脚！！！然后检查软件设置，发现默认值已经从0.15改成了0！！！

当时恍惚间，我以为我记错了之前拓竹的默认值，于是在wiki上搜索了一下，wiki链接：https://wiki.bambulab.com/zh/software/bambu-studio/parameter/elephant-foot **截止到2024年1月29日，拓竹官网上关于象脚补偿的页面，默认值写的还是0.15！（拓竹在我反馈了这个问题之后，在2024年1月30号上午10点26分的时候，更新了官网页面，去掉了默认值这一项。）**

然后第一时间联系了拓竹在京东的客服：
1. 反馈这个问题之后，客服表示咨询了技术，**技术反馈 A1 mini 的默认值一直都是0！**
2. 我表示官网上面的wiki上面写的是默认值0.15，并且拍照发给了客服。
3. 客服再次和技术确认，技术表示官网的wiki用的是x1的机器的
4. 在我准备自行查找一个个版本进行对比，表示技术在撒谎的时候，技术又改口：去年12月份是0，现在也是0
5. 在准备查找版本的时候，发现了GitHub的repo，之前都不知道这个软件是开源的
6. 作为一个程序员，对GitHub还是蛮熟悉的，于是快速定位到了是谁改的：https://github.com/bambulab/BambuStudio/commit/e6d2c532d023f31d59d5b0da61a5fb1edb9d9772 ，令我绷不住的点来了，这个提交没有Jira在跟踪，而且修改的原因仅仅是因为程序员自测感觉没有肉眼可见的象脚，于是就提交了这个修改，并且被review了，而且merge了。这里面可以吐槽的点太多了，我们等会继续说。
7. 我将搜索到的代码提交的照片给到了客服，告诉他反馈给技术，确实是他们修改了。客服表示反馈一下
8. 客服的反馈一直杳无踪迹，在我第二天（2024年1月30日）继续追问的时候，客服给了我在线技术的聊天网址，让我跟在线技术聊
9. 跟在线技术反馈了拓竹私自修改默认参数的问题之后，在线技术反馈之后，回复说，技术测试了没问题就自己改了。模型有问题用户需要自行调整，并表示我没有及时的给他们反馈这个问题！
10. 在线技术的态度让我决定公开这个问题，让社区评判私自修改默认参数，并且压根不通知用户的行为是否合理。
11. 跟京东客服反馈了在线技术的沟通结果。京东客服表示反馈一下我的问题，让我等一下。
12. 下午，京东客服表示可以赔偿我一卷耗材。我表示我打印花了8个色，花了一周的时间，你一卷耗材你觉得合适吗？连我废掉的耗材都不够
13. 之后，京东客服继续联系我，说最高补偿2卷耗材。我问京东客服，这2卷耗材是你们承认私自修改默认参数导致我的损失的赔偿吗？客服表示2卷耗材是补偿我的耗材消耗的，但是技术反馈还没有回复。
14. 我表示不能接受这种睁着眼说瞎话的事，客服说技术和研发有自己的事要做，技术说会和研发确认。
15. 2024年1月30号，晚上22:56，京东客服给我回复，“上一次改11月初的版本有改过，您应该是几个月没更新过软件，中间都迭代了至少快10个版本了。  改过参数≠您打印出问题的原因   我们这边测试a1 mini就是不需要象脚补偿的”

---
# 槽点
1. 拓竹工程师提交代码时没有完整的测试流程
> 这一点相当致命！务必请拓竹的研发部门提起警示！
- 按照提交来看，仅仅是工程师自己测试了一下，在他的参数设置、环境、机器和耗材上，没有发现问题，这就代表所有的都不会有问题了吗？
- 提交代码的工程师测试了多少种耗材？
- 是在热床温度为多少的时候测试的？
- 测试过不同的热床温度的时候的表现吗？
- 测试过不同的环境温度和环境湿度对这个打印效果的影响吗？
- 他可以确保所有批次的机器都用这个参数没有问题吗？
2. 修改代码的时候不过脑子
众所周知，象脚补偿是一个非常重要，而且对首层影响比较大的一个参数。我们可以将默认的设置为0，也可以将默认的参数设置为0.15，那为什么我们在最初的时候选择的是0.15？ A1 mini面向的群体大部分是刚接触或者都没有接触过3D打印的小白，对他们来说，你觉得0.15的象脚补偿和0哪一个的适用面更广呢？哪一个是更不容易引起问题的呢？修改成0这种，更像是脑子抽了，工作极度不饱和带来的负优化
3. 拓竹技术支持信口雌黄
先是说 A1 mini 一直是0，然后改成12月份之后是0，然后偷偷修改官网wiki的说明，然后最后还是死不承认自己改过。再到最后，承认了，但是甩锅给用户。
> 拓竹技术，已经将信任完全打碎了，烂成了拓竹满地的贞操

---
# 结语
A1 mini 仅仅是因为我有一个想法，想做个玩具才接触到3D打印机的，然后恰好，它的售价和媒体上的众多好评引起了我的注意。所以我才买了A1 mini。

大部分的时间还是挺开心的，看着自己的想法，通过模型，变成了实体。而且我本身也不是做建模的，一点点学习建模，并用A1 mini尝试，也挺有成就感的。大部分的时间 A1 mini 虽然不算完美，但整体也还算省心。中间也有过小插曲，买来没几个星期，就出现了裹头，直接把散热风扇都干坏了。

这次之所以这么气愤，是两个原因：
1. 修改默认参数，而且是非常重要的默认参数，这是一个会改变用户看到的打印结果的行为，这是非常值得警惕的，但是拓竹处理的这么草率！辜负了我之前对拓竹的信任！
2. 拓竹技术支持多次甩锅给用户，比如责怪用户没有及时反馈。你是用户他爹是吗？买你家产品是我自己活该是吗？而且技术信口雌黄，始终撒谎，比如说A1 mini一直是0，还偷偷修改官网wiki。拓竹技术支持完全无法取信于消费者，而且还丧失了一个消费者。当然，拓竹也看不上我。

曾经，还想把我自己设计的玩具，看看能不能跟拓竹合作，幻想也可以成为拓竹新品发布时的一个用户场景的展示。现在看来，就拓竹这态度，我呸！

### Actual results

拓竹甩锅用户

### Expected results

拓竹给个解释

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by SaltWei** [comment]
请售后同事直接跟进，把打印件照片/3mf等必要信息都要来，再联系研发同事分析问题。
装配需求本身对精度要求极高，不同的机器，材料，温度等都会有很大影响。
另外即便是有象脚导致装配问题，也可能有很多别的非一致性的因素，如热床温度，调平，喷嘴磨损等等。毕竟之前同样有用户也反馈象脚在他们的环境并不明显，加了象脚补偿反而造成首层细节丢失。
因此这些参数都无法固定，对于装配场景，需要用户根据实际情况先打印必要的测试块，按需调整象脚补偿,xy补偿等补刀参数。
如果你发现你的打印件象脚很严重，请把打印件照片/3mf文件/机器log/使用的耗材等信息通过工单系统提交上来，这样分析原因。

感谢理解！

**Comment by bsx1990** [comment]
> 这个提交让我想起来了前几年antd hohoho的灾难

不一样，至少人家是第一时间大大方方的承认是自己代码留的彩蛋。拓竹之前一直不承认他们改过默认参数，直到我把实锤甩到他们脸上。然后还偷偷修改了官网wiki

这件事，也万幸我偶然发现了这个repo，不然，作为一个普通消费者，当拓竹咬死自己没改的时候，又能怎么办呢？

**Comment by jerrykkkkk** [comment]
很早之前支撑的默认页改过，导致打印失败，回退切片软件版本后 才正常，后反馈给拓竹，在下一版本就改回来了，现在不敢随意升级软件，而且你更新软件后 建议先打印一次 测试没问题 再批量生产

**Comment by lianghongkey** [comment]
公司做大了就有各种管理难题，最终成功的公司，肯定是各方面管理都比较优秀的。
从我和拓竹客服的沟通来说，其实不咋地，不专业，不负责任。
是时候用回voron2.4了，直到另外一家眼光更长远的公司出现。
