### ISSUE TITLE
Copy&Paste objects shuffles the order of object's modifiers and parts.

### ISSUE THREAD

**Issue by M-A-B007** [bambulab/BambuStudio#3513]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

WIN 10 Enterprise (ver 22H2)

### Additional system information

CPU:12th Gen Intel(R) Core(TM) i9-12950HX   2.30 GHz
RAM:64GB

### Printer

BambuLab X1C

### How to reproduce

1. Have an object with parts and/or modifiers.
2. Multiply that object on the plate by Copy & Paste.

### Actual results

![Capture-BambuMixedOrder](https://github.com/bambulab/BambuStudio/assets/41743716/320e7623-4c74-4b1b-b1ca-08df18d4143f)
The order of the copied part's sub-parts and modifiers is different than for the original object.

The slicer processes the modifier before it processes the main object now. It causes the modifiers to have no effect on the generated g-code.

### Expected results

Copy&Paste action does not change the order of the object's sub-parts and modifiers.

### Project file & Debug log uploads

[vetrani-kovovamrizka-zatisknuta.zip](https://github.com/bambulab/BambuStudio/files/14113236/vetrani-kovovamrizka-zatisknuta.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by MadMax389** [comment]
I can confirm this behavior. It plays havoc with the clipping order. Quite a pain to rearrange all the copies. PLEASE, PLEASE, PLEASE implement instancing like Prusa Slicer.

**Comment by Haidiye00** [comment]
Hello, I have used your project and software version, but it has not been reproduced. Can you record a video to explain your issue? Thank you

**Comment by MadMax389** [comment]
It is simple to reproduce. Add a cube primitive to the plate and then add a disc part (like a mouse ear)
![image](https://github.com/bambulab/BambuStudio/assets/96731892/4dfcc5c5-0ebc-4fbb-a710-6114d3dad3d1)

When I slice it, the mouse ear has a higher clipping priority and will print inside the cube.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/4670ebbf-2ba4-4ff5-b91c-8dc9c120c2a6)

But I want the mouse ear to print outside the cube, so change the clipping order by rearranging the parts on the object screen.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/ea728a72-e921-433a-a71a-6d4b838e38fe)

Now copy or clone this assembly. The clipping order reverts back to the original clipping order.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/cf764362-4f9b-42ae-8907-d23cb1aae03e)

This is really inconvenient when creating multiple copies of an object where I've changed the clipping order. You have to go to each model and rearrange them again. PLEASE, we are begging for instancing where changing something on one model propagates that change to all instances of that model (like Prusa Slicer). Thank you.

**Comment by Haidiye00** [comment]
Thank you for reproducing this issue. We will find a way to solve it

**Comment by Haidiye00** [comment]
![noproblem](https://github.com/bambulab/BambuStudio/assets/132528822/822f9609-47aa-4e7a-8eb3-0b68da475601)
I used our internal version 20240219 and there is no such issue. Please wait for version V1.9. Thank you

**Comment by Haidiye00** [comment]
This issue has been fixed. Please download and use the latest version.
