### ISSUE TITLE
Android Bambu Handy Video Stream

### ISSUE THREAD

**Issue by JoshuaM89** [bambulab/BambuStudio#3514]
### Bambu Studio Version

2.5.0

### Where is the application from?

Bambu Lab Official website

### OS version

Andriod 14 - One UI Version 6.0 

### Printer

X1C

### How to reproduce

Open BambuHandy
Switch app view without closing app
Come back after 2-3 minutes on any other app
Click on video play

### Actual results

The screen will remain blank and will not show anything until you close the app and reopen it.
![Screenshot_20240131_104832_Bambu Handy](https://github.com/bambulab/BambuStudio/assets/158314431/cae674d6-8bb8-498c-8c5a-ee04768add9e)

### Expected results

The video should start without needing to close the app and reopen it.

### Project file & Debug log uploads

Not applicable, from the app.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by pepsiliu** [comment]
To better track the issue about Handy, Please visit [Bambu Handy Issue](https://github.com/bambulab/Bambu-Handy/issues)
