### ISSUE TITLE
Separation of 2 objects with different colors

### ISSUE THREAD

**Issue by jebsimmons** [bambulab/BambuStudio#3517]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS

### Additional system information

AppleM1
16GB RAM
MacOS Sonoma 14.2.1

### Printer

Bambu X1C or P1S

### How to reproduce

Insert 1 object. 
Insert 2nd Object- 1mm in height
Set the color for Object 1 to one color (Bambu matte Olive Green)
Set the color for Object 2 to a darker color (Bambu matte Black)
Center both objects
Assemble the two objects
Slice Plate

### Actual results

The software only recognizes object 1 and will not slice object 2.

### Expected results

It should slice the two objects and recognize that there are 2. This works on the Windows Version. 

### Project file & Debug log uploads

[SLICING 2 OBJECTS.3mf.zip](https://github.com/bambulab/BambuStudio/files/14124509/SLICING.2.OBJECTS.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by jebsimmons** [comment]
What it should look like: 

<img width="1764" alt="Screenshot 2024-02-01 at 6 20 46 AM" src="https://github.com/bambulab/BambuStudio/assets/3419822/70b06771-e2f7-40ec-99ac-6449935f5008">

What it looks like after slicing:


<img width="1764" alt="Screenshot 2024-02-01 at 6 20 36 AM" src="https://github.com/bambulab/BambuStudio/assets/3419822/e3fe9217-be8e-4301-a8cd-695fe70e486b">

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/c497eec3-76c4-436b-838c-67bf00147d80)

Because these two components have overlapping parts, We give priority to displaying the parts later in the object list.
If you want to display the black part, you can drag "part_2" behind "stl" in the object list, as show in FIG.

**Comment by zhimin-zeng-bambulab** [comment]
@jebsimmons  Did the above method solve your problem?

**Comment by zhimin-zeng-bambulab** [comment]
@jebsimmons We introduced this function in the third point of the release note of version V1.7.4 and gave a simple example.
