### ISSUE TITLE
Lost videofeed after network drops

### ISSUE THREAD

**Issue by mctazman** [bambulab/BambuStudio#3541]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 14.3 (23D56)

### Printer

X1 carbon, firmware 01.07.00.00

### How to reproduce

I had some network problems, which made me power cycle the AP where my X1 is connected to. After the network comes back online, I can not get any video feed. No matter the device, software, or OS. After a power cycle, the video feed works perfectly.

It seems to me, that the video feed has some network binding that doesnt get reset when the machine loses its connection. Probably a token in cache, if I should hazard a guess

This is the second time I experienced this problem. Last time was on an older firmware version.

### Actual results

The software keeps loading, until it times out, starts loading the feed again, repeat.

### Expected results

Preferably, check for network drops & re-initialize the video feed if possible.

### Project file & Debug log uploads

[Archief.zip](https://github.com/bambulab/BambuStudio/files/14168594/Archief.zip)
[Speaker mount.3mf.zip](https://github.com/bambulab/BambuStudio/files/14168596/Speaker.mount.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by bambu123** [comment]
We recently released a web plugin 01.08.04.04 related to this issue. Have you upgraded?

**Comment by bambu123** [comment]
> We recently released a network plugin 01.08.04.04 related to this issue. Have you upgraded?

**Comment by mctazman** [comment]
I think I've upgraded. I got the message & clicked "ok", is there a way to check? I upgraded before the issue started, so restarting Studio did not fix it.

**Comment by bambu123** [comment]
The printer may need some time to restore its network connection.
Could you help provide the Studio logs?
Also, please tell me the approximate time when the problem occurred.

**Comment by bambu123** [comment]
> The printer had hours, and no feed returned. The logs are in the Archief.zip file, in the original post. I don't know the time, it was morning. If I were to guess, I'd say around 6-ish. But truly have no idea.

I think it should be a problem with the printer. The printer has an occasional crash problem which may be fixed in the coming version 1.8.
However, To figure out the problem
Could you help to create a ticket and upload the log (https://wiki.bambulab.com/en/x1/troubleshooting/upload-log).
Please tell me the ticket number, after you create the ticket.

**Comment by mctazman** [comment]
Thanks for your quick reply. The ticker number is: US240206361001

**Comment by bambu123** [comment]
> Thanks for your quick reply. The ticker number is: US240206361001

OK. Our printer team will check it.

**Comment by bambu123** [comment]
@mctazman 
From our printer team:
Same As https://github.com/bambulab/BambuStudio/issues/3199#issuecomment-1909439238.

**Comment by mctazman** [comment]
Cheers, very clear. Thanks for the quick reply & work.
