### ISSUE TITLE
BUG - Bambu studio 1.2.0.9 does not show toolhead runout sensor activity but the LCD display and Bambu Handy do.

### ISSUE THREAD

**Issue by LarryVand** [bambulab/BambuStudio#355]
Bambu studio 1.2.0.9 does not show when filament is in the toolhead runout sensor but the LCD display and Bambu Handy do.
![20221001-231142](https://user-images.githubusercontent.com/69426512/193440638-ec533915-8b29-4ce3-a61b-b12219a0c0d7.png)
![20221001-231150](https://user-images.githubusercontent.com/69426512/193440646-ebed86cc-e80c-4557-acfd-f37fa00c4a4c.png)
![20221001-231136](https://user-images.githubusercontent.com/69426512/193440656-2ad58ef6-ca07-466f-93f3-59ec4ec30784.png)

**Comment by YifanWuBambu** [comment]
Fixed in v.1.3.0.12.
