### ISSUE TITLE
Default printer and filament

### ISSUE THREAD

**Issue by mbillros** [bambulab/BambuStudio#3556]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

mac big sur 11.7.10

### Printer

p1s combo

### How to reproduce

only defult maschine in printer setting, only crealite cr-6 shows not bambu lab p1s, all filament is gone cant shows nothing, all was working befor now its gone, have reinstall bambu studios many time nothing helps

### Actual results

nothing

### Expected results

i dont understand

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/14201899/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by XunZhangBambu** [comment]
@mbillros  Hi, i didn't reproduce your issue. The log you provided is network logs and i cannot see your operations in the log. Did you select P1S on the printer page？ A log like this may help
![image](https://github.com/bambulab/BambuStudio/assets/139755545/ec8adf34-3ebc-40a4-af8b-5208af33d6a9)

**Comment by XunZhangBambu** [comment]
No responese for a long time, i think it can be closed now
