### ISSUE TITLE
[Feature Request] Option to manually stack objects on build plate

### ISSUE THREAD

**Issue by Frontier314** [bambulab/BambuStudio#357]
Ability to turn on/off the automatic object placement on build plate.
This would allow us to manually stack objects together for multi-material prints.

**Comment by ChrisG-hub** [comment]
Snap and lock at layer height.

**Comment by coat64** [comment]
Right click on object > add part > load... The loaded part can be stacked on the original. Set X and Y to 0 to align the centers (or don't) and the Z to your value.

**Comment by YifanWuBambu** [comment]
@Frontier314 
One method is as what @coat64  said.
Another method is selecting all objects that you want to stack and right-click and choose "Assemble". All object will be assemble to a big object and each object is considered as a part of that object.

Then, you may move/rotate each part individually. There are two ways to select a part.
1. Alt + Left click
2. Select a part in the object list on the sidebar
![image](https://user-images.githubusercontent.com/110661856/193743320-a58bae7f-6e5a-4701-879f-ffcc39a03d47.png)

**Comment by Frontier314** [comment]
@YifanWuBambu, @coat64 Thank you very much for the suggestions.
What I did until now was stack the objects on PS and then export the STL to Bambu Studio, which it was somewhat inconvinient.

**Comment by YifanWuBambu** [comment]
@Frontier314 
You are welcome.

If you stack STLs on PS also in this way, you can save it as a 3mf in PS, then import the 3mf to Bambu Studio. The stacking relationship will be kept.
![image](https://user-images.githubusercontent.com/110661856/194766930-eff154a4-7c58-4b8d-ba86-275329b08d17.png)
