### ISSUE TITLE
Impossible to select layer menu with mac trackpad

### ISSUE THREAD

**Issue by IanVS** [bambulab/BambuStudio#3578]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 14.0

### Printer

Bambu Lab P1P

### How to reproduce

Using a laptop with a trackpad, slice a build plate, then try to add a filament change at a particular layer by dragging the layer slider, then right clicking with a two-finger tap.  Each time I try it, the layer changes to one a few lower, and the menu does not open.  This seems to be because I can two-finger scroll the layers up and down (not very useful), and putting down my second finger triggers that scroll behavior.

### Actual results

The layer I am viewing changes.

### Expected results

The layer context menu opens to allow me to add a filament change at layer.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by amzaldua** [comment]
[https://github.com/bambulab/BambuStudio/issues/3450](url)

**Comment by IanVS** [comment]
Thanks!
