### ISSUE TITLE
[BUG] From the settings search drop-down menu, clicking on first item has no effect

### ISSUE THREAD

**Issue by reify3d** [bambulab/BambuStudio#358]
Problem: In the settings search drop-down menu, search for a term such as "width" or "vase". A list of candidates will be returned and populate the drop-down menu. Click on the first item, and it has no effect. Clicking on the second result, and the tab panel will update to the correct item.

What I expected: clicking on the first item will bring me to the correct setting in the appropriate tab panel.

What actually happened: clicking on the first item has no effect.

![CleanShot 2022-10-03 at 07 25 57](https://user-images.githubusercontent.com/109889103/193481036-1e5eb1d5-2f31-4148-830b-e2c037722897.gif)

Software and hardware version: BambuStudio 1.2.0.9 on macOS 12.6 (21G115) running x86_64.

**Comment by YifanWuBambu** [comment]
Fixed in v.1.3.0.12.
