### ISSUE TITLE
Remove internal bridge support thickness and port better solution from Orca or Prusa

### ISSUE THREAD

**Issue by radekkpl** [bambulab/BambuStudio#3588]
When printing features that lies above infill, internal bridge are printed few layers ahead the feature.
But the speed of printing (in the air) can make a problem acoring to printing cornes in the air.

Both Orca and Prusa has solution, that bottom layer of the feature are expanded to touch infill lines.
It solve the problem, that no corner or end of the line lies at air.

First layer of internal bridge
![AirPrint01](https://github.com/bambulab/BambuStudio/assets/12301139/c0147f96-d26e-468f-a72b-cbd76c1edd80)

Internal bridge is not used, instead layer is snapped to infill
![AirPrint02](https://github.com/bambulab/BambuStudio/assets/12301139/45cf07b8-964f-4fc9-b904-49d6de514211)

**Comment by XunZhangBambu** [comment]
@radekkpl  We have switched to the algorithm used by prusa in latest version
