### ISSUE TITLE
[Feature Request] Make ensure_vertical_shell_thickness and more quality parameter user configurable

### ISSUE THREAD

**Issue by mrcg** [bambulab/BambuStudio#359]
Please add ensure_vertical_shell_thickness parameter to expert settings.
This is very essential parameter to eleminate unneeded solid infill which can dramatically reduce overall print time and also improve print quality.
Beside this i would like to have much more PrusaPrinter parameter available in expert settings. Especially all quality related parameters.

Quality related parameters available in PrusaPrinter to be also made available in Bambu Studio (user configurable):

ensure_vertical_shell_thickness
extra_perimeters
avoid_crossing_perimeters
avoid_crossing_perimeters_max_detour
detect_thin_walls
thick_bridges
overhangs

Attached screenshots are demonstrating the impact by enabling/disabling the ensure_vertial_shell_thickness parameter:
It's really very essential to have this parameters user configurable.

![ensure_vertial_shell_thickness_TRUE](https://user-images.githubusercontent.com/4404991/193676433-839a098e-7aa7-44c4-a471-e4947946cd70.jpg)

![ensure_vertial_shell_thickness_FALSE](https://user-images.githubusercontent.com/4404991/193677424-cc6e8ea6-2500-4465-ac96-b2d7835c65f4.jpg)

**Comment by tokamac** [comment]
"Avoid Crossing Perimeters" is a duplicate of #106
"Detect thin walls" is already in BambuStudio.
"Overhangs" settings are already in BambuStudio, unless you meant a different thing?
I don't know for the others, I think you're right and most of them are not implemented.

**Comment by mrcg** [comment]
I have listed all quality related parameters which are bundled in PrusaSlicer in in listed parameter package.
The idea was to reduce effort on implementing this important parameters and avoid asking for each individual parameter seperately. The most important and missing parameter is "ensure_vertical_shell_thickness" but also other parameters should be made available to be user configurable. 

![quality_related_prusaslicer_settings](https://user-images.githubusercontent.com/4404991/193910547-6d61467f-129a-4c3b-8fff-f415e7f131f9.png)

**Comment by tokamac** [comment]
I concur with **Ensure vertical shell thickness**. I have a problem on my X1-Carbon currently because it is ON by default in BambuStudio and it cannot be disabled. I have already enough perimeters (three) on my model, thanks. The toolhead makes unnecessaryaditional weird movements to add this extra 4th inner perimeter, resulting in adding 4 hours to the print time!

**Comment by SaltWei** [comment]
Ensure vertical shell thickness has been added. Please wait for next release

**Comment by mrcg** [comment]
> ![image](https://user-images.githubusercontent.com/110660407/204493303-d89c172d-bad7-463e-9f17-637a56ff4264.png)

Thanks for reply. If most important parameter "ensure vertical shell thickness" will come in next release i am happy.
The other two left our are not very important.
Looking forward to the next update which then will allow to create pretty clean perimeters for optimized fast printing.

**Comment by mrcg** [comment]
FRQ closed now because feature meanwhile implemented.
Thanks to Bambulab team for implementation.
