### ISSUE TITLE
[Feature Request] Edit machine limits in Bambu Slicer to decrease ringing and get proper pressure advance tuning

### ISSUE THREAD

**Issue by Argolein** [bambulab/BambuStudio#360]
Right now it is not possible to edit the machine limits in Bambu Slicer. The options are greyed out. 
If you want to do so you have to edit it via .json file at the moment.

**Comment by YifanWuBambu** [comment]
Hi @Argolein ,
Why do you want to edit the machine limits? We gray them out because the default values are consistant with the physical design of Bambu printers.

**Comment by Argolein** [comment]
@YifanWuBambu 

Hello,
to answer this it would normally mean open one or two another issues on GitHub because there are two problems I'm going do describe.
**Short answer:** to improved print quality. Lower the effect of ringing and have sharp corners (pressure advance).

**Long answer:**
I've also opened a support ticket in the app but it's more comfortable to post it here. 
Trouble ID: US220930300002

**The problem:**
At default - acceleration 10000 mm/s -printed objects show severe ringing. Support checked my logs and said that vibration compensation is working but is not showing the effect it should. My printer is sitting on a heavy brick stone and I recalibrated it several times.
I let also other user on the discord confirm this as they showed me their prints which also showed ringing:
![IMG_3478](https://user-images.githubusercontent.com/52103738/193768485-5c29e539-0be0-479b-ac4c-df57d55bce11.jpg)

It was suggested to me from the support to lower acceleration. I did that and the ringing became better. 
Result of the print by lowering acceleration from 10000 mm/s to 7500 mm/s:
![IMG_3485](https://user-images.githubusercontent.com/52103738/193768746-460ac7dd-0c3c-4562-83d2-62110c7b5ff4.jpg)

But by lowering acceleration the edges began to showed bulging which indicates pressure advance is set too low.
I'm always using Flow calibration before every print and I let also others on discord confirm the issue:
![IMG_3487](https://user-images.githubusercontent.com/52103738/193769111-afbd57dc-6a45-4750-9164-acb9c61898f3.jpg)

My theory was that the Flow calibration which does also calibrate pressure advance is not using the acceleration I'm using to print. So if you set your printing acceleration to 7500 mm/s in BambuSlicer the printer would not use these values for the calibration. I've checked the generated gcode file and the M204 gcode with the used printing acceleration (you set in Bambu Slicer) is used **after** the calibration. I've only found a M204 before the calibration which is using the machine limits. 

To check my theory I've lowered the acceleration (and also jerk) to 7500 mm/s and 5 mm/s (jerk). You have to do this in the .json files as the limits are locked within Bambu Slicer.

The result is less ringing and sharp corners:
![IMG_3504](https://user-images.githubusercontent.com/52103738/193769712-5b4e9f2d-5ea1-45dc-b823-27282d3df28e.jpg)

**To sum the issues up:**
- vibration compensation is not effective or is not showing the results as it should be
- flow and pressure advance calibration is not using the printing acceleration you set in Bambu Slicer
- machine limits are locked in Bambu Slicer which kind of solve the two issues above

**Comment by tapir** [comment]
Wow this is really good detective work. Will try also. +1

**Comment by Argolein** [comment]
@tapir 
For you and those who want to try this: Don't forget to use the same acceleration for machine limits (.json file) and printing acceleration in Bambu Slicer. 

How I see it:
Acceleration set in machine limits is used for pressure advance calibration and the set printing acceleration in Bambu Slicer is used for the actual print. So those two values need to be identical. 

I get fairly good results since then. Ringing is not 100% gone but far better. Maybe vibration compensation will be improved in the future.

**Comment by tapir** [comment]
We're talking about fdm_machine_common.json in user directory right? And where do you see this options greyed out? I couldn't ding them in UI.

**Comment by SaltWei** [comment]
The machine limit is just used to show max value of Bambu printer, not the real used acceleration when printing.
The printing acceleration is in speed setting page of process preset.
We will set printing acceleration before printing calibration line, but keep the limits read-only for Bambu Lab printer.

**Comment by SaltWei** [comment]
In additional, for third party printer, we will make the options editable in UI.

Patch has been merged. Please wait the next release which also include setting printing acceleration before printing calibration line

**Comment by SaltWei** [comment]
Setting printing acceleration before printing calibration line，done.

**Comment by SaltWei** [comment]
Already included in latest release. Close
