### ISSUE TITLE
cut operation

### ISSUE THREAD

**Issue by 3dfixer** [bambulab/BambuStudio#3601]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Printer

p1s

### How to reproduce

load model
it contains pockets for magnets
slice
pockets still there
perform cut on model
slice and pockets disappear
perform same process on prusaslicer and it works

### Actual results

pockets disappear 

### Expected results

pockets remain

### Project file & Debug log uploads

[top case (1).gcode.zip](https://github.com/bambulab/BambuStudio/files/14315429/top.case.1.gcode.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
I'm very sorry, I didn't understand the problem you described. Could you please provide a more detailed description, record a video, or take a screenshot to explain the problem you found? Thank you

**Comment by Maximus-CZ** [comment]
@Haidiye00 
Not OP but encountered the same issue:
I have this model (pic 1).
Near the top, there is internal space for magnets (pic 2)
For testing, before I print whole model, I want to print just that piece. So in Bambu I cut the model (remove everything underneath) (pic 3)
But after cut (and slicing) the internal hole just gets filled with sparse infill, and the wall that holds the magnet is deleted completely (pic 4)
![image](https://github.com/bambulab/BambuStudio/assets/5832592/711379ba-09a5-4e61-bc1f-537438c9b5b6)
![image](https://github.com/bambulab/BambuStudio/assets/5832592/12848b81-e83a-4571-9e6c-977736da3d93)
![image](https://github.com/bambulab/BambuStudio/assets/5832592/44f02ea4-21c9-42e1-959b-b08aa0fc6333)
![image](https://github.com/bambulab/BambuStudio/assets/5832592/12e10232-05e1-44a1-8d3a-d2b8986b8e7b)

**Comment by Haidiye00** [comment]
Can you provide the model file? Thank you

**Comment by Maximus-CZ** [comment]
@Haidiye00 
The model I tried:
https://files.printables.com/media/prints/16623/stls/1973987_b23590d9-5cbd-468b-ac08-416fd03d220a/resource-box-4x2.stl

If that link doesnt work then its 
**Resource Box (4x2).stl**
https://www.printables.com/model/16623-terraforming-mars-storage-solution-insert/files
![image](https://github.com/bambulab/BambuStudio/assets/5832592/c8b9b7cc-5246-4a5f-af79-e14c09a5e496)

**Comment by Haidiye00** [comment]
I have fixed this issue, please wait for version V1.9. Thank you for your discovery and support~
