### ISSUE TITLE
BambuStudio Access Violation error on i9 14900k

### ISSUE THREAD

**Issue by rd400** [bambulab/BambuStudio#3610]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 (latest)

### Additional system information

Intel i9 14900k
32gb RAM

### Printer

P1S

### How to reproduce

1. Open complex model
2. Click Slice

### Actual results

Program crashes with 'Access Violation'. It appears that Bambu Studio cannot handle the E-Cores on the 14900k.  If you go into task manager-->Details-->bambu-studio-->Set Affinity-->Select only CPUs 0-7. No more crashing. BambuStudio will still handle basic slicing, but nothing complex until you turn off E-cores [8-31]. Sometimes it completely blue-screens, or the computer hard locks and must be powered down.

I'm not a programmer, so unclear exact reason why this workaround is successful. 
![image](https://github.com/bambulab/BambuStudio/assets/103457224/1632914e-11e8-4a57-aff5-effce8c2861a)

### Expected results

Program should slice without crashing.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/14320699/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by lanewei120** [comment]
the same issue as https://github.com/bambulab/BambuStudio/issues/3318

**Comment by QingZhangBambu** [comment]
@rd400 maybe you can do some CPU tests. Some users change the CPU, all problem be solved. https://community.intel.com/t5/Processors/i9-13900K-very-frequent-crashes-Windows-11-with-apps-games-and/m-p/1528789/highlight/true
https://github.com/bambulab/BambuStudio/issues/3354

**Comment by Cypher87** [comment]
I have the same issue with the i9-14900k. Whenever I slice a complex object it crashes. Mostly during generation of supports. Using compatibily mode "Windows 8" it works fine.

I tested my CPU with cinebench r23 and no issues there. Also tested my memory, tried XMP on/off. Everything else is running perfectly on this system.

 I analyzed a crashdump and it comes back with:

    KEY_VALUES_STRING: 1
    Key  : AV.Fault
    Value: Read

    Key  : Analysis.CPU.mSec
    Value: 1718

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 8134

    Key  : Analysis.Init.CPU.mSec
    Value: 406

    Key  : Analysis.Init.Elapsed.mSec
    Value: 19449

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 348

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 369

    Key  : Timeline.Process.Start.DeltaSec
    Value: 9

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Timestamp
    Value: 2022-05-06T12:50:00Z

    Key  : WER.OS.Version
    Value: 10.0.22621.1

    Key  : WER.Process.Version
    Value: 1.0.0.0


    FILE_IN_CAB:  WER.cf38a9f5-3590-4db2-8b0f-95624388d784.tmp.mdmp

    NTGLOBALFLAG:  0

    PROCESS_BAM_CURRENT_THROTTLED: 0

    PROCESS_BAM_PREVIOUS_THROTTLED: 0

    APPLICATION_VERIFIER_FLAGS:  0

    CONTEXT:  (.ecxr)
    rax=0000000000000000 rbx=0000021065db9f40 rcx=00000000ffffffff
    rdx=0000000000000000 rsi=0000009ab1ff4570 rdi=0000000000000000
    rip=00007ffe15c2d4e5 rsp=0000009ab1ff4340 rbp=0000000000bb0f2d
     r8=0000021065db9f40  r9=0000021040780e10 r10=0000021040782b20
    r11=0000021040780df0 r12=0000000000000000 r13=0000009ab1ff4950
    r14=0000000000bb0f2d r15=0000000000000000
    iopl=0         nv up ei pl zr na po nc
    cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
    BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1e5555:
    00007ffe`15c2d4e5 394d3c          cmp     dword ptr [rbp+3Ch],ecx ss:00000000`00bb0f69=????????
    Resetting default scope

    EXCEPTION_RECORD:  (.exr -1)
    ExceptionAddress: 00007ffe15c2d4e5 (BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x00000000001e5555)
    ExceptionCode: c0000005 (Access violation)
    ExceptionFlags: 00000000
    NumberParameters: 2
    Parameter[0]: 0000000000000000
    Parameter[1]: 0000000000bb0f69
    Attempt to read from address 0000000000bb0f69

    PROCESS_NAME:  bambu-studio.exe

    READ_ADDRESS:  0000000000bb0f69 

    ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

    EXCEPTION_CODE_STR:  c0000005

    EXCEPTION_PARAMETER1:  0000000000000000

    EXCEPTION_PARAMETER2:  0000000000bb0f69

    STACK_TEXT:  
    0000009a`b1ff4340 00007ffe`15c34987     : 00000210`652ee4e0 00007ffe`15c3135f 00000210`65db9f40 00000000`00000000 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1e5555
    0000009a`b1ff43c0 00007ffe`15c2fad7     : 00000000`00000000 0000009a`b1ff4570 00000000`00bb0f2d 0000009a`b1ff4760 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1ec9f7
    0000009a`b1ff4450 00007ffe`15c2f177     : 0000009a`b1ff4570 00000000`00000000 0000009a`b1ff4570 00000000`00000000 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1e7b47
    0000009a`b1ff44a0 00007ffe`15c2f2f3     : 0000009a`b1ff4578 0000009a`b1ff4780 0000009a`00000000 0000009a`b1ff4701 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1e71e7
    0000009a`b1ff4520 00007ffe`15c5e04f     : 00000210`192e02b0 00000000`00000040 0000009a`b1ff4a48 00000000`00000040 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x1e7363
    0000009a`b1ff4700 00007ffe`15c506ab     : 00000210`3f5961e0 0000009a`b1ff4a48 00000000`00000000 00000210`3f5961e0 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x2160bf
    0000009a`b1ff4920 00007ffe`15c5da81     : 00000210`5f073f08 0000009a`b1ff4b80 0000009a`b1ff4b18 00007ffe`15d56b00 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x20871b
    0000009a`b1ff49b0 00007ffe`15e7c7c0     : 00000210`5f073f08 0000009a`b1ff4e60 00000210`61ceb170 0000009a`b1ff4e60 : BambuStudio!cereal::detail::StaticObject<cereal::detail::bind_to_archives<Slic3r::DynamicPrintConfig,cereal::detail::`anonymous namespace'::polymorphic_binding_tag> >::instantiate+0x215af1
    0000009a`b1ff4a80 00007ffe`15e6d88b     : 0000009a`b1ff4e48 00000000`00000003 0000009a`b1ff4e49 00000000`00000000 : BambuStudio!BRepExtrema_SelfIntersection::`default constructor closure'+0x1d7a60
    0000009a`b1ff4df0 00007ffe`15e69c1f     : 00000000`00000003 0000009a`00000000 00000210`37651980 00000210`363f5000 : BambuStudio!BRepExtrema_SelfIntersection::`default constructor closure'+0x1c8b2b
    0000009a`b1ff4eb0 00007ffe`15e7da95     : 00000210`37651a00 00000000`00000000 00000210`37651a00 00000210`363f5000 : BambuStudio!BRepExtrema_SelfIntersection::`default constructor closure'+0x1c4ebf
    0000009a`b1ff5010 00007ffe`158d39c0     : 00000210`2a378300 00000210`2a1d0100 00000000`00000000 0000009a`b1ff5180 : BambuStudio!BRepExtrema_SelfIntersection::`default constructor closure'+0x1d8d35
    0000009a`b1ff5060 00007ffe`158cefe2     : 00000210`3f3c5480 00000210`2a1d0101 0000009a`b1ff5180 00000000`00001f01 : BambuStudio+0x939c0
    0000009a`b1ff5160 00007ffe`158da33c     : 00000210`2a1d0100 00000000`00000000 00000210`2a1d0100 00000000`00000000 : BambuStudio+0x8efe2
    0000009a`b1ff51c0 00007ffe`158e1807     : 00000210`236a8370 00000000`00000000 00000210`2a1d0100 00000210`2a2fa800 : BambuStudio+0x9a33c
    0000009a`b1ff5200 00007ffe`158e16cb     : 00000000`00000000 00000000`00000024 00000210`236a8370 00000000`00000000 : BambuStudio+0xa1807
    0000009a`b1ff5240 00007ffe`db299363     : 00000210`236a8370 00000000`00000000 00000000`00000000 00000000`00000000 : BambuStudio+0xa16cb
    0000009a`b1fff9a0 00007ffe`dd18257d     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ucrtbase!thread_start<unsigned int (__cdecl*)(void *),1>+0x93
    0000009a`b1fff9d0 00007ffe`ddb0aa58     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x1d
    0000009a`b1fffa00 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x28


    SYMBOL_NAME:  BambuStudio+1e5555

    MODULE_NAME: BambuStudio

    IMAGE_NAME:  BambuStudio.dll

    STACK_COMMAND:  ~27s; .ecxr ; kb

    FAILURE_BUCKET_ID:  INVALID_POINTER_READ_c0000005_BambuStudio.dll!Unknown

    OS_VERSION:  10.0.22621.1

    BUILDLAB_STR:  ni_release

    OSPLATFORM_TYPE:  x64

    OSNAME:  Windows 10

    FAILURE_ID_HASH:  {d803ad0a-677a-62e0-ddef-19ff7e155517}

**Comment by rd400** [comment]
Update: I installed a brand new i9-14900k and my Bambu Studio slicing problems disappeared. Not clear if it's a bad CPU or bad thermal paste. My error was hardware related.

**Comment by Arcaine10** [comment]
Good morning,
I may have found a solution without having to change the affinity each time. You have to download Intel extreme tuning utility, go to advanced tuning and set performance active-core tuning to 54. Since then I have had no more problems.
![image](https://github.com/bambulab/BambuStudio/assets/163099480/2bfabf5d-a728-42aa-b15b-38a3b9aa4ef5)
