### ISSUE TITLE
Auto-calculation of flushing volume not performed when syncing or resyncing filaments from AMS

### ISSUE THREAD

**Issue by tedtieken** [bambulab/BambuStudio#3612]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Win 11

### Printer

X1, P1

### How to reproduce

1. Open bambu studio 
2. In Filament Section set colors that are different from current AMS (e.g. 1 to black, 2 to white  if the AMS has 1. red and 2. blue)
3. In Filament Section, Click flushing volumes and click re-calculate
4. In Filament Section, click synchronize button then Sync or Resync
5. Re-open flushing volumes

### Actual results

Flushing volumes stay with the number calculated in step 3 above.

### Expected results

If Resync is clicked in step 4, flushing volumes should re-calculate based on the colors in the AMS

### Project file & Debug log uploads

Project file not relevant.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MklBambu** [comment]
Thanks for reporting this issue. This issue has been fixed in a new version. Please try again using the new version.
https://github.com/bambulab/BambuStudio/releases/tag/v01.08.04.51
