### ISSUE TITLE
Mouse ear brims, PLEASE!

### ISSUE THREAD

**Issue by Sengfeng** [bambulab/BambuStudio#3618]
For those models that lift at the edges, mouse ears would be a very welcome addition.

**Comment by Schokobecher** [comment]
This feature exists as a Brim Type option within OrcaSlicer, so it should be fairly easy to back port

**Comment by MadMax389** [comment]
A simplified version already exists in Studio. Add a disc part.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/9c711fd5-34c2-44d0-bdad-1a45c342397d)

**Comment by ChrisXenon** [comment]
> A simplified version already exists in Studio. Add a disc part. ![image](https://private-user-images.githubusercontent.com/96731892/306061058-9c711fd5-34c2-44d0-bdad-1a45c342397d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzkzNzAsIm5iZiI6MTcxNTg3OTA3MCwicGF0aCI6Ii85NjczMTg5Mi8zMDYwNjEwNTgtOWM3MTFmZDUtMzRjMi00NGQwLWJkYWQtMWE0NWMzNDIzOTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE3MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNzIzYTY1NGRkNDAwZGE5MDgzYmY1YjRlMjEyYjBlYTQ0ZGUzOWUwMTA3N2RhMjcyYzk1NjEyMDA4ZGEzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3LZF8o4sXHmlhjHlAdSau0f23oy2R2rJ7Eoq_gh1FSA)

Yes, but that's a very poor substitute for the real thing. I want to print 8 rectangular parts. Every corner will lift without brims. Full brims waste a lot of time and filament. Manually adding 32 circles is ridiculous.

**Comment by aallen88** [comment]
Why is this still not part of BS?

I just recently got my first Bambu printer & was befuddled when I couldn't do this. I hadn't needed to until today. It's clearly been asked for and it's obviously possible. What's the hold up?

**Comment by MackBambu** [comment]
Brim ear has been added.
