### ISSUE TITLE
[FR] Add Wipe Inside At Start of External Perimeter

### ISSUE THREAD

**Issue by ChaosBlades** [bambulab/BambuStudio#362]
Screenshot from SuperSlicer.
![Screenshot from 2022-10-03 23-56-01](https://user-images.githubusercontent.com/7530545/193731005-e82617cb-855f-465a-a240-84a4e52a86d6.png)
This should fix this problem. The only solution I have found due to the limitations of Studio at current is to disable all part cooling which obviously produces other issues. Even then the Z seam isn't great but still a massive improvement. This is a fairly common problem in my experience specifically with PETG.
![IMG_20221003_235804](https://user-images.githubusercontent.com/7530545/193731466-8309334a-1282-4832-bcb4-1b2943b7f612.jpg)
Here is the gcode from SuperSlicer with this feature enabled. The blue is the detraction.
![Screenshot from 2022-10-04 00-04-24](https://user-images.githubusercontent.com/7530545/193731891-18cc088b-7f8c-4a74-92bb-6188e9a023d7.png)

**Comment by QingZhangBambu** [comment]
I enable the setting in super slicer(2.4.58.5 edition, released on Sep 24), and print it in the Bambu X1 Carbon machine.

travel path when the wipe inside at start and end open enabled
![at start](https://user-images.githubusercontent.com/112676417/202945275-dc60c7fa-4038-4a67-a579-54100c5ed094.png)

print result in Bambu's machine, the seam is still very large
![seam](https://user-images.githubusercontent.com/112676417/202945663-e3e4a573-ef26-40d6-bdd9-fbf37c565c4a.jpg)

if wipe inside at the start enable, and wipe at the end off, the seam would be better but it has extra filament at the start of the perimeter, also, the connection part would be weak.
 path
![wipe](https://user-images.githubusercontent.com/112676417/202946374-af234314-8859-4fd1-93ba-8e3f616bbc5d.png)
print result
![print](https://user-images.githubusercontent.com/112676417/202946490-ff49036c-7084-49b9-8785-d6baca60d7f2.jpg)

so, the wipe at the start will not be added to Bambu Studio, but we will try to modify the end wipe path to make the seam better. Thank you for the advice. It is helpful.

**Comment by ChaosBlades** [comment]
@QingZhangBambu The point of this setting isn't to close the seam. It is to give the melted filament something to grab onto so it is not drug away from the seam. If you don't have an issue with the filament getting drug away from the steam like in my example then this setting is of no use to you.

If you want to close the gap then you would lower the Z Steam gap setting. Like I said, that isn't what this setting does.

**Comment by QingZhangBambu** [comment]
sorry for the misunderstanding. I will check the z seam.

**Comment by ChaosBlades** [comment]
If you want to try and reproduce this issue here is the 3MF. You would want to print this in PETG as it likes to stick to the nozzle. However my issue may be specific to my brands blend of PETG.
[1U Modular Drawer 12x6.zip](https://github.com/bambulab/BambuStudio/files/10053189/1U.Modular.Drawer.12x6.zip)

**Comment by QingZhangBambu** [comment]
I use bambu's PETG. and the seam is not as bad as yours.
![image](https://user-images.githubusercontent.com/112676417/216924779-3a83091f-af15-4e5a-bc58-2c08e06d1341.png)

**Comment by QingZhangBambu** [comment]
though the gap is big, but the nozzle haven't wipe extra filament to near place.

**Comment by QingZhangBambu** [comment]
your issue could not be reproduced. So close the issue.
