### ISSUE TITLE
Changing BBL plate SVG does not update in Bambu Studio

### ISSUE THREAD

**Issue by ptsao88** [bambulab/BambuStudio#3634]
### Bambu Studio Version

1.8.2.56

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambulab X1C

### How to reproduce

Go to C: Program Files --> Bambu Studio --> resources --> profiles --> BBL
Replace "bbl-3dp-logo.svg" with a custom SVG
Refresh and restart Bambu Studio

### Actual results

There is no change to the displayed plate. If I do this on the "Prusa" profile and replace "mk3.svg", it works as intended. See image below.

![Prusa 2](https://github.com/bambulab/BambuStudio/assets/62680638/b5582ceb-f89b-4012-8dc6-dcfde5b5b101)

### Expected results

I expect this to work the same as when replacing "mk3.svg" on the Prusa profile.
Perhaps there is a different SVG file that I should be replacing or modifying to add custom changes to the shown plates in Bambu Studio?

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ptsao88** [comment]
I also noticed that this feature that's available in Prusa Slicer does not work.

In Bambu Studio all the buttons are disabled and greyed out.

![image](https://github.com/bambulab/BambuStudio/assets/62680638/6dc9f301-ed51-40aa-a98b-ecf3113807d5)

**Comment by ptsao88** [comment]
The texture feature shows up if I create a copy of an existing printer profile. However, it doesn't seem to do anything after uploading a file.

If I create a new printer profile totally from scratch this works...but is not ideal.

![image](https://github.com/bambulab/BambuStudio/assets/62680638/6bc486b5-85ef-44c6-8c42-5c645ef69da3)
![image](https://github.com/bambulab/BambuStudio/assets/62680638/2f30d3e1-6d8b-4767-8f56-b2d3618de189)

**Comment by Haidiye00** [comment]
Bambu's official printer does not support importing SVG hot bed patterns, only third-party printers can support importing SVG hot bed patterns

**Comment by ptsao88** [comment]
That's unfortunate. I am creating customized build plates with logos in specific areas. Importing the SVG into Bambu Studio would help me align printed parts onto specific areas of the build plate to match up with the logos.

**Comment by Haidiye00** [comment]
Can you draw some diagrams to illustrate your application scenario? We will evaluate and consider whether to develop it. Thank you

**Comment by ptsao88** [comment]
Hi @Haidiye00 - see this video for what I would like to be able to do: https://youtu.be/TEeMEJMefow?si=dATzBYxxgM5LSls6&t=58

This would let users line up prints exactly to where they want on customized PEI plates that I am making. See example picture below.

![Blacklabel3D](https://github.com/bambulab/BambuStudio/assets/62680638/f0a40622-2c14-4e72-b83e-d335b837a0ea)

**Comment by Haidiye00** [comment]
Understood, we will evaluate and consider whether to develop it soon. Thank you

**Comment by ptsao88** [comment]
Great - thank you!

**Comment by Haidiye00** [comment]
Hello, can you provide your SVG? Thank you

**Comment by emberprototypes** [comment]
Here is an example.

If we can import this into Bambu Studio then it will make lining up parts to the artwork easier for our custom plates that imprint logos onto the first layer.

![Bambulab+Plate_V1_out](https://github.com/bambulab/BambuStudio/assets/126627300/1cf9416e-cecd-4752-8422-066955dd68cb)

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/87eaa865-dbc1-4504-9122-eefc93715e6c) I have achieved an effect, and it would be even better if you could provide some SVGs to facilitate our internal testing

**Comment by emberprototypes** [comment]
> ![image](https://private-user-images.githubusercontent.com/132528822/342544365-87eaa865-dbc1-4504-9122-eefc93715e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODEwNzYsIm5iZiI6MTcxOTI4MDc3NiwicGF0aCI6Ii8xMzI1Mjg4MjIvMzQyNTQ0MzY1LTg3ZWFhODY1LWRiYzEtNDUwNC05MTIyLWVlZmM5MzcxNWU2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMTU5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGM5OWZiMzkyZmEwZTEzNTFhNDc3OGFjYjE5Y2ZhOGVkZDViMDk5ZGY3ZWYxMzEzYzRkZDA5YTVmMzZiMGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.twFYG4oFELfPycvY2YzytLzwmIzV3b3_bkOWez58cjs) I have achieved an effect, and it would be even better if you could provide some SVGs to facilitate our internal testing

Did the SVG in the previous response not work? I can provide more if needed

**Comment by Haidiye00** [comment]
If possible, could you please provide some? Thank you

**Comment by emberprototypes** [comment]
> Here is an example.
> 
> If we can load these types of SVGs into Bambu Studio as the plate texture then it will make lining up parts to the artwork easier for our custom plates that imprint logos onto the first layer.
> 
> ![Bambulab+Plate_V1_out](https://private-user-images.githubusercontent.com/126627300/342433480-1cf9416e-cecd-4752-8422-066955dd68cb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODEzNjEsIm5iZiI6MTcxOTI4MTA2MSwicGF0aCI6Ii8xMjY2MjczMDAvMzQyNDMzNDgwLTFjZjk0MTZlLWNlY2QtNDc1Mi04NDIyLTA2Njk1NWRkNjhjYi5zdmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMjA0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjhlMTQzYThhNGJlN2NmZGRjNWUwZTM2YzI1NjUxZmQxM2ZkODZiYzYyZmJmNWE3NDJjMDIzM2EzNTYwZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jFCeMP0MfGxHcw2gszia0A7rOxDVpbWJ69erDM8fAKo)

I attached one in this reply...

**Comment by Haidiye00** [comment]
Can you provide the original files

**Comment by emberprototypes** [comment]
![Example 1](https://github.com/bambulab/BambuStudio/assets/126627300/a2c306f4-827a-4695-b4d3-ac97531f8334)
![Example 2](https://github.com/bambulab/BambuStudio/assets/126627300/2286789f-05b1-40de-b3c7-0fbebf596d8e)
![Example 3](https://github.com/bambulab/BambuStudio/assets/126627300/b5ca0efd-582b-4a23-b723-dbf16bf542a5)
![Example 4](https://github.com/bambulab/BambuStudio/assets/126627300/fea52c34-257b-4a62-9532-9a4bc5328bd2)
![Example 5](https://github.com/bambulab/BambuStudio/assets/126627300/134b27e3-03f9-4140-b362-b685ea362ae6)

See attached for examples.

**Comment by emberprototypes** [comment]
> Can you provide the original files

You should be able to just right click --> save as SVG.

**Comment by Haidiye00** [comment]
![img_v3_02c6_b1ab7e46-cc0f-426f-8c57-a17ff1c4d18g](https://github.com/bambulab/BambuStudio/assets/132528822/c940ca94-30c1-4960-96f9-e6664dd89f23)
I have tested your file and the effect is as shown above. I suggest that your file does not have a black background, as the second size does not seem to match exactly.

**Comment by emberprototypes** [comment]
Are you sure that the SVG is not being scaled funny when you load it as a texture?

You can see that the SVG should have the correct dimensions for the plate.

Also - if you load the SVG into Bambu Studio, you can see it converts it to a 3D model that is the correct size.

![Screenshot 2024-06-24 212524](https://github.com/bambulab/BambuStudio/assets/126627300/1deadf95-6ef5-40b8-8c65-c065874d06dc)
![image](https://github.com/bambulab/BambuStudio/assets/126627300/d7130e76-43d6-4e71-a924-3b236ad6a6ee)

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/aceb1836-642c-48f4-90f0-693bcf654073)
The problem has been resolved. Take a look at the effect.

**Comment by emberprototypes** [comment]
Yes this is perfect!!! Will this be on the next Bambu Studio release? 😀

**Comment by Haidiye00** [comment]
yes

**Comment by emberprototypes** [comment]
Amazing thank you so much!

**Comment by Haidiye00** [comment]
You're welcome, but the next version may take quite some time. Perhaps in about a quarter~

**Comment by emberprototypes** [comment]
Ok no problem! I'm hoping the next version also comes with filament specific XY shrinkage compensation 😬

Thank you for your hard work.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~

**Comment by emberprototypes** [comment]
Amazing thank you @Haidiye00 !
