### ISSUE TITLE
P1P打印直播流点击播放按钮，重复弹出需重新注册BambuSource的错误窗口

### ISSUE THREAD

**Issue by countree103103** [bambulab/BambuStudio#3643]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 专业工作站版

### Printer

Bambu Lab P1P

### How to reproduce

点击播放按钮出现
![image](https://github.com/bambulab/BambuStudio/assets/52630500/e3e78732-2306-4c6d-8708-3ad617c802b6)
点击Yes后，出现
![image](https://github.com/bambulab/BambuStudio/assets/52630500/e9d3dd9c-c700-4fe4-a882-d7897245922f)

### Actual results

在上述过程后，点击播放按钮任无法播放。再次点击播放按钮会重复出现上述情况。
错误信息为
![image](https://github.com/bambulab/BambuStudio/assets/52630500/9cb9006f-26ae-4259-bb03-1505cab18a7b)

### Expected results

直播流正常播放。

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/14395083/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
可能注册被杀毒软件干扰了。参照wiki 手动注册。检查注册表。 https://wiki.bambulab.com/en/software/bambu-studio/faq/live-view

**Comment by bambu123** [comment]
@countree103103 请问你是否解决了问题。

**Comment by countree103103** [comment]
> @countree103103 请问你是否解决了问题。

我尝试了wiki里的手动导入reg，没有解决。
以下是reg内容：

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\CLSID\{233E64FB-2041-4A6C-AFAB-FF9BCF83E7AA}]
@="BambuSource Filter"

[HKEY_CURRENT_USER\Software\Classes\CLSID\{233E64FB-2041-4A6C-AFAB-FF9BCF83E7AA}\InprocServer32]
@="C:\\Users\\71766.ChenZY-Win11\\AppData\\Roaming\\BambuStudio\\plugins\\BambuSource.dll"
"ThreadingModel"="Both"

**Comment by bambu123** [comment]
还有另一个注册项目，再试试

https://wiki.bambulab.com/software/bambu-studio/live-view/bambu.reg

**Comment by countree103103** [comment]
> 还有另一个注册项目，再试试
> 
> https://wiki.bambulab.com/software/bambu-studio/live-view/bambu.reg

注册了这个reg之后可以加载视频流了。
之前的wiki里没有这个bambu.reg的说明，可以加一下说明。
