### ISSUE TITLE
No warning given when generated tree support intersects

### ISSUE THREAD

**Issue by ptbsare** [bambulab/BambuStudio#366]
![Screen Shot 2022-10-04 at 21 01 33](https://user-images.githubusercontent.com/3147576/193826703-97e61691-eec2-4654-9419-5c3e39c4e1bc.png)
![Screen Shot 2022-10-04 at 21 00 36](https://user-images.githubusercontent.com/3147576/193826827-e7b3996b-767c-4014-91e0-ad725180a422.png)

**Comment by ptbsare** [comment]
The tree support of individual objects are generated separately, which intersect when objects are closely orranged by the automatic placement system.  NO warnings are given.
And I think that the tree support should be generated wholly when there are multiple objects, not separately, which can avoid this problem.

**Comment by tangketan** [comment]
We have warnings of all gcode paths conflicts now.
Generating tree supports of all objects conflicts with "skipping objects".
