### ISSUE TITLE
Export STLs

### ISSUE THREAD

**Issue by ZiggyHentze** [bambulab/BambuStudio#3661]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu P1P

### How to reproduce

1. Cut model into 12 parts with dowels
2. Export each as STL parts
3. Open in other software (ZBrush in my case, 3D viewer and MeshMixer) and the holes for Dowels are missing?

### Actual results

Holes just gone?

### Expected results

I need to print over multiple printers as the job is to huge - "Print Farm" via friends with printers

### Project file & Debug log uploads

Should be clear than to still send the models too

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ZiggyHentze** [comment]
The dowels export but the parts after exporting to STL and then re importing into Studio are all missing same as other programs?
![holes missing](https://github.com/bambulab/BambuStudio/assets/130473738/435d4314-b97d-47e8-ba57-3e1b26417e03)

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/80929586-25d9-45a2-a23d-b5c28a680e7f)
This issue has been fixed, please wait for version 1.9.Thank you for your discovery and support
