### ISSUE TITLE
Very small text on flow calibration 

### ISSUE THREAD

**Issue by SteveAtSmartersoft** [bambulab/BambuStudio#3674]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10

### Printer

X1c

### How to reproduce

Go to Calibration
Run it
See the text on success

### Actual results

The text is very tiny quite often. (as per the screenshot)  But not always.
![Screenshot_589](https://github.com/bambulab/BambuStudio/assets/143579566/f46467ce-742c-44fd-974d-58e4513a8923)

### Expected results

Larger font

### Project file & Debug log uploads

No project

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Thanks for reporting this issue, we will also try to reproduce this issue.

**Comment by SteveAtSmartersoft** [comment]
It does not happen every time, but I've seen it 3-4 times now.  Like every 3rd time or so.

Best regards
___________________________________________
Steve Horvath
Principal Consultant

SmarterSoft
Level 17, Angel Place,
123 Pitt St Sydney NSW 2000

e: ***@***.******@***.***>
w: www.smartersoft.com.au<http://www.smartersoft.com.au/>

SmarterSoft is a registered trading name of Areanet Pty. Ltd.

We acknowledge the Traditional Owners and Custodians of the lands on which we work and pay our respects to Indigenous Elders past, present and emerging.

**Comment by LiZ-Li-BBL** [comment]
Hi,
please use the latest release, we've fixed this issue. https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.66.
