### ISSUE TITLE
MacOS Text not showing correctly

### ISSUE THREAD

**Issue by WNTLtd** [bambulab/BambuStudio#3677]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Monterey V12.7.2

### Printer

Bambu Lab X1C

### How to reproduce

Generating Text on the surface of my model - and some letters are backwards and or vertical!

### Actual results

<img width="521" alt="Screenshot 2024-03-04 at 16 50 34" src="https://github.com/bambulab/BambuStudio/assets/52933483/0b37a296-4a49-4b56-bc77-4146fe717da6">

### Expected results

The text should be written as entered.

### Project file & Debug log uploads

[logs.zip](https://github.com/bambulab/BambuStudio/files/14484739/logs.zip)
[Export for BLabs.3mf.zip](https://github.com/bambulab/BambuStudio/files/14484741/Export.for.BLabs.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Thanks for reporting this issue, we will investigate the cause of this problem.

**Comment by Haidiye00** [comment]
Hello, can I record a video or GIF? Thank you

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
