### ISSUE TITLE
Feature Request: preview tab - pause at layer - tied to current build plate only

### ISSUE THREAD

**Issue by dereknheiley** [bambulab/BambuStudio#369]
Currently if you set a pause at a certain layer on the preview tab it affects all build plates.
But, i use multiple build plates to hold different parts, thus the layer pause is specific to that one part and build plate.

It would be great if you could specify, control, or otherwise limit a layer pause while printing to only some models or build plates. Ideally independent layer pauses for each build plate.

**Comment by SaltWei** [comment]
Already included in v1.5.0 Public beta
