### ISSUE TITLE
X1C Not Printing Studio Designed GCODE as pictured in Studio

### ISSUE THREAD

**Issue by kamland** [bambulab/BambuStudio#3699]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Sonoma 14.2.1 (23C71)

### Printer

Bambu Lab X1 C

### How to reproduce

Load project file to Studio
Generate code
Send to printer and print

### Actual results

![DogInCup_Screenshot 2024-03-09 at 10 10 06 PM](https://github.com/bambulab/BambuStudio/assets/25156926/1678dad8-8dd4-4c34-9750-5a95dd3173b5)
[DogInCup.heic.pdf](https://github.com/bambulab/BambuStudio/files/14550734/DogInCup.heic.pdf)

### Expected results

Should print as pictured in Studio.

### Project file & Debug log uploads

[Archive.zip](https://github.com/bambulab/BambuStudio/files/14550724/Archive.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/bdc15479-229f-483f-b4b9-28c079fb23f4)
the flush volume was set to 0, need to be set to 1

**Comment by EricDimitri** [comment]
> ![image](https://private-user-images.githubusercontent.com/112676417/311572800-bdc15479-229f-483f-b4b9-28c079fb23f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTA3NDgsIm5iZiI6MTcxMDYxMDQ0OCwicGF0aCI6Ii8xMTI2NzY0MTcvMzExNTcyODAwLWJkYzE1NDc5LTIyOWYtNDgzZi1iNGI5LTI4YzA3OWZiMjNmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNzM0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDIyYzcxNGMxMTVlMzk0Mzk4MzNiZjY1NTU4M2FiZjEyMTUyNmYwZGEyYzJiN2ViN2U0OTgwOTMzMWIzZjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XcP6d3pYLdPwSUHmcIrl5pLO3DG0PlMd_8gbWR0Hvn0) the flush volume was set to 0, need to be set to 1

Just for me to know, where is that window? I never saw it. Thanks!!

**Comment by QingZhangBambu** [comment]
@EricDimitri click here
![image](https://github.com/bambulab/BambuStudio/assets/112676417/0419d64b-2843-45b6-b373-9e546977d5d5)

**Comment by EricDimitri** [comment]
> @EricDimitri click here ![image](https://private-user-images.githubusercontent.com/112676417/313589637-0419d64b-2843-45b6-b373-9e546977d5d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjQwNzIsIm5iZiI6MTcxMDc2Mzc3MiwicGF0aCI6Ii8xMTI2NzY0MTcvMzEzNTg5NjM3LTA0MTlkNjRiLTI4NDMtNDViNi1iMzczLTllNTQ2OTc3ZDVkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMjA5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjAxN2ZiYzI2MjI0MWU0NGY2MTU3ZDhmYmRiNDQ2MTU5YTlkOTAwNjVmYjljOTQ4MjA3ZmQwZDU0MjUwYWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KPiHD8X6FzLnTM6sPjdMjA0i0NgW3MmQpqnJZ-PyG1c)

And how are those calculated? Because I am not using Bambu filaments (those dont reach my country) so I see in that window that volumes are different, depending on colour? Or how does it work?

**Comment by QingZhangBambu** [comment]
@EricDimitri sorry to reply so late, I missed your email.
 Yes, the flush volumes depend on color. We do tests of Bambu filaments to get these data. 
you can modify the data on the flush window and watch the flush process on the printer. If the filament is clean, then the data is fine.
