### ISSUE TITLE
Mac: Logfiles in Applications Folder

### ISSUE THREAD

**Issue by woswasi67** [bambulab/BambuStudio#372]
I have in my program folder 3 logfiles (log_avapi.txt, log_global.txt, log_iotc.txt) which are probably generated by BambuStudio. I can delete them, but when I start BambuStudio they are created again.

Is it possible to put them somewhere else please?

(macOS 12.6)

**Comment by kiliankoe** [comment]
Combined those files are >17GB on my end... 🙈

**Comment by bambu123** [comment]
This a bug with the old version, please install the recent version of BambuStudio. You can delete these files without any issue.

**Comment by woswasi67** [comment]
It is the latest version (1.2.0.9) which makes the problem

lg, Christian

**Comment by talesh** [comment]
My recommendation would be to use best practices for putting the log files in the correct locations in Mac OS. Hopefully using that would make it usable but also they'll be rotated cleanly. 

https://stackoverflow.com/questions/70638430/which-directory-is-the-best-for-saving-logs

**Comment by bambu123** [comment]
Sorry. It is in the latest plugin. The Studio does not auto-update plugins, please remove the plugins in the plugins directory and restart studio.

The plugin's directory is located the same as the configuration directory which you can jump to from the menu "Help > Show Configuration Folder".

**Comment by woswasi67** [comment]
Ok, thank you!

lg, Christian

**Comment by brunic** [comment]
When will the Bambu Studio delete these log files? I got these three files and the log_global.txt has 12GB+ size.

**Comment by YifanWuBambu** [comment]
Optimized in v1.3.0.12.
