### ISSUE TITLE
Unable to open calibration dropdown on second material

### ISSUE THREAD

**Issue by ThePieMonster** [bambulab/BambuStudio#3727]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C

### How to reproduce

Unable to open calibration dropdown on second material. 

As seen in the first image, there are two calibrations there were made.

The second material dropdown will not open to allow me to select this.

![image](https://github.com/bambulab/BambuStudio/assets/11359134/a9da8d51-5e41-4226-90cf-4cba46938e9c)
![image](https://github.com/bambulab/BambuStudio/assets/11359134/e458d136-288d-4c60-9393-c22697c3d685)
![image](https://github.com/bambulab/BambuStudio/assets/11359134/43769d76-f6b7-400e-a524-20163d94dc27)

### Actual results

No results

### Expected results

Dropdown works

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
Because the PA k value is related to the material, the k value calibrated from PLA Basic material can only be used for PLA Basic material and cannot be used for the PLA Metal material. Are your PA profiles both calibrated from PLA Basic material?

**Comment by ThePieMonster** [comment]
> Because the PA k value is related to the material, the k value calibrated from PLA Basic material can only be used for PLA Basic material and cannot be used for the PLA Metal material. _Are your PA profiles both calibrated from PLA Basic material?_

Check the images again.

There is a k profile for basic and a k profile for metal. 1 for each.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/2860a6d7-4921-4279-9856-40294d731ea5)

Could you confirm that the filament presets you selected when sending calibration are correct? If you are sure it is correct, could you upload your log file at that time.

**Comment by ThePieMonster** [comment]
I have since changed out filaments types quite a bit. Not able to reproduce this at the moment.

**Comment by zhimin-zeng-bambulab** [comment]
Close as unable to reproduce.
If you encounter this problem again later, you could upload the the log file and record the preset information selected at that time. Thanks!
