### ISSUE TITLE
Layer Times in Preview are showing wrong color and do not match legend color values 🪲

### ISSUE THREAD

**Issue by odysoftware** [bambulab/BambuStudio#3741]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C

### How to reproduce

Go to Preview and Look at Layer Times visualization. You will see that the color's shown will not match the numbers for the layer times.

You can see an example in below's comment.

It shows 62s layer time, but the visualization color magenta indicates around about 4s (as seen from the legend info)! It should be colored yellow to green to be in the 60s+ range.

### Actual results

Layer times visualization color matches wrong layer times values in legend.

### Expected results

Color in layer times matching the correct legend color with the correct value.

### Project file & Debug log uploads

not needed.

**Comment by odysoftware** [comment]
Added example 3MF file -> [test layer times.zip](https://github.com/bambulab/BambuStudio/files/14663676/test.layer.times.zip)
![Screenshot 2024-03-20 092437](https://github.com/bambulab/BambuStudio/assets/35902048/a8aea922-5a9b-4d17-a883-dd31f0500378)

**Comment by Haidiye00** [comment]
I have identified the cause and resolved it. Thank you for discovering the bug
![ljU4G9E6Ws](https://github.com/bambulab/BambuStudio/assets/132528822/4b4a4ce1-adb7-4c92-bbfb-66b47366e3f2)

**Comment by odysoftware** [comment]
Thanks a lot 👍
