### ISSUE TITLE
PCTG support

### ISSUE THREAD

**Issue by auriotim** [bambulab/BambuStudio#3747]
Please develop/provide filament settings for PCTG filaments by 3DXTECH, Fibrology, Essential

**Comment by XunZhangBambu** [comment]
@auriotim 
We have added profiles for PCTG. You will see it in next version

**Comment by XunZhangBambu** [comment]
@auriotim 
We have previously released a material package, which includes Generic PCTG.
![image](https://github.com/bambulab/BambuStudio/assets/139755545/f04701f5-02af-45d5-b8f2-418a452a0f3a)
