### ISSUE TITLE
[BUG: Transform/rotate Arrows too small on OSX] BUG: Transform/rotate Arrows too small on OSX

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#3753]
Hey all - any chance we can get a fix for the arrows being to small on OSX in Bambu Studio? On PC they’re nice and big and easy to grab, but on OSX, they’re only a few pixels across on a high DPI monitor so they’re REALLY small.

**Comment by kertgartner** [comment]
<img width="1309" alt="Screen Shot 2024-03-22 at 5 19 20 PM" src="https://github.com/bambulab/BambuStudio/assets/60412716/6cad15a1-7a79-4b59-80c2-9ef967601bbd">
Here's a screenshot that illustrates this issue. A fix would be very welcome, thank you.

**Comment by Haidiye00** [comment]
![a0af0108-9269-4c3a-beab-fe10a704a3e2](https://github.com/bambulab/BambuStudio/assets/132528822/a22d176e-1d9d-4aeb-b639-58950c66a2e2)
look this

**Comment by kertgartner** [comment]
Yes, I understand this, but the triangular 'grabbers' are very small on OSX compared to windows. when using a high dpi monitor they're VERY hard to grab. Can the size of the triangular grabbers be increased?

**Comment by Haidiye00** [comment]
May I ask, what is the resolution of your OSX computer

**Comment by kertgartner** [comment]
I'm using an Apple Studio Display, and the resolution is 5120 x 2880.

**Comment by suchabadperson** [comment]
I wrote about this one year ago... #1336

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~The size of the gripper is in the preference settings.
