### ISSUE TITLE
[UX] 1.9.0 Beta - UI Button and Text off-screen macOS

### ISSUE THREAD

**Issue by TinyMito** [bambulab/BambuStudio#3767]
### Bambu Studio Version

1.9.0 Beta

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 14

### Additional system information

M1 Pro

### Printer

P1S

### How to reproduce

Go to Device tab and look at the AMS box control. The text and buttons are off-screen or outside the application boundary. This bug existed in previous releases for a long time.

OrcaSlicer did not have this issue.

### Actual results

![20240325_002025](https://github.com/bambulab/BambuStudio/assets/75095713/60c76411-c4b3-48e7-8b28-8980cedda929)

### Expected results

This is in OrcaSlicer releases

![20240325_002026](https://github.com/bambulab/BambuStudio/assets/75095713/92108ce6-668a-4d12-a41e-89e48489a289)

### Project file & Debug log uploads

not available.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
@TinyMito 
Due to the length of the translation, there was an error in the UI display. We will fix this issue.
