### ISSUE TITLE
Feature Request: Ability to set wall loops to zero

### ISSUE THREAD

**Issue by Gossamer42** [bambulab/BambuStudio#377]
Prusa Slicer and SuperSlicer both have the ability to set the perimeters (wall loops) to zero.  Bambu Studio does not allow this, and will change the value to 1 when you input zero.

An example of why this is needed is the Vector Finesse printed headphones.  Several of the printed parts require there be no walls for proper audio functionality of the part.  I cannot print these parts on my X1 because of this.

**Comment by SaltWei** [comment]
Done in code.
