### ISSUE TITLE
invert colors

### ISSUE THREAD

**Issue by valentiy75** [bambulab/BambuStudio#3780]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro 23h2

### Additional system information

AMD Ryzen 7 4700U with Radeon Graphics 2.00 Ghz
16 gb  ram

### Printer

Bambu Lab P1S

### How to reproduce

In the cut preview, everything looks correct, but it prints in inversion those layers where a different filament color occurs
![PXL_20240327_015326251](https://github.com/bambulab/BambuStudio/assets/45722685/f341e2a8-6045-4bda-90ae-3e23aea44da5)
![PXL_20240327_015329193](https://github.com/bambulab/BambuStudio/assets/45722685/47219c22-073a-4925-871b-e84b8f1ee6bf)
![PXL_20240327_015335704](https://github.com/bambulab/BambuStudio/assets/45722685/ac2ac9b7-f5d7-486a-84a8-c36cee3cf826)
![PXL_20240327_015416836](https://github.com/bambulab/BambuStudio/assets/45722685/caa9e923-5d5f-4c80-81ee-8dbec6a15eea)
![PXL_20240327_015432433](https://github.com/bambulab/BambuStudio/assets/45722685/37d5e022-2851-4be0-bff1-f00762a98e13)
![PXL_20240327_020545528](https://github.com/bambulab/BambuStudio/assets/45722685/7b44b31e-05f4-4d8b-8517-e47d35e8c132)
![PXL_20240327_020551512](https://github.com/bambulab/BambuStudio/assets/45722685/a5d16d3a-1cae-4d90-b7db-245428aaf26a)

### Actual results

I want black letters on a white background. But I get an inversion precisely in those layers where a different color is applied. The remaining layers are printed as they appear in the preview.

### Expected results

I expect to see the result as I see in the slicer preview.
[Motorola 3.zip](https://github.com/bambulab/BambuStudio/files/14766746/Motorola.3.zip)

### Project file & Debug log uploads

[Motorola 3.zip](https://github.com/bambulab/BambuStudio/files/14766761/Motorola.3.zip)
[Motorola 3 full.zip](https://github.com/bambulab/BambuStudio/files/14766782/Motorola.3.full.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by valentiy75** [comment]
![photo_2024-03-26_19-35-51](https://github.com/bambulab/BambuStudio/assets/45722685/01ccdcff-2ae0-45fa-858f-ae5ec98b094f)

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/01987f3e-149a-40fb-8cc0-33dd3dea7e9f)
Because your flushing volume is set incorrectly, you could click "Recalculate" to get the correct flush volume.
