### ISSUE TITLE
1.9.0 Beta - Behavior of added parts / negative parts coordinates 

### ISSUE THREAD

**Issue by suchabadperson** [bambulab/BambuStudio#3782]
### Bambu Studio Version

1.9.0.60

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 17.4.1

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. Open Bambu Studio beta version 1.9.0.60
2. Import a model with multiple parts or add a new part to an existing model
3. Select the added part
4. Use the Move tool to reposition the part

### Actual results

When adding a part to a model in the beta version of Bambu Studio and using the Move tool, the origin point for the part's movement is set to the corner of the build plate instead of the center of the main object, which was the behavior in previous versions.
<img width="1540" alt="SCR-20240327-nsak" src="https://github.com/bambulab/BambuStudio/assets/65729856/745d1017-56a9-4e48-abec-389633124ff7">

### Expected results

The origin point should be set to the center of the main object.
<img width="1496" alt="SCR-20240327-nsge" src="https://github.com/bambulab/BambuStudio/assets/65729856/597c91a6-9d07-463e-b6e2-8016f97d7276">

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
Can you provide the 3mf project? Thank you

**Comment by Haidiye00** [comment]
Why do I feel like there's no problem? Isn't your generic-clue at the world origin?

**Comment by suchabadperson** [comment]
> Why do I feel like there's no problem? Isn't your generic-clue at the world origin?

Please see the screenshots above, where you can see the difference between version 1.8.3.89 and the current beta.

Until now, when you added a part to an object (or the object had different parts), its center of coordinates was the parent. Now the center of the added part is the origin of the printer (the lower left part).

**Comment by Haidiye00** [comment]
Could you please record a GIF animation? Thank you, you can use ScreenToGif software

**Comment by Haidiye00** [comment]
We will add an object coordinate system in the future, which should be the same as your idea. Stay tuned

**Comment by suchabadperson** [comment]
> Could you please record a GIF animation? Thank you, you can use ScreenToGif software

Behavior in beta release:
![beta](https://github.com/bambulab/BambuStudio/assets/65729856/8ff545d5-7e02-4b80-91d0-10ed614ce33b)

In 1.8.3.89:
![old](https://github.com/bambulab/BambuStudio/assets/65729856/5b123fd2-c828-4793-9ad9-cc9453facffc)

**Comment by suchabadperson** [comment]
Issue still present in 1.90 beta2.

**Comment by Haidiye00** [comment]
Sorry, the code is still under development

**Comment by suchabadperson** [comment]
Issue still present in 1.9.1 Public Official release.

**Comment by Haidiye00** [comment]
![img_v3_02al_0a427ed6-442c-4321-8b9b-efc7f511d46g](https://github.com/bambulab/BambuStudio/assets/132528822/c3ec91eb-6f21-46bd-b9bf-3a238c0a4cee)
Sorry for keeping you waiting. This feature has been developed and is currently in beta testing. The next version will be released. Stay tuned.

**Comment by ReneZeidler** [comment]
> This feature has been developed and is currently in internal testing. The next version will be released. Stay tuned.

1.9.2 has been released last week and this feature isn't included. Is this still being worked on?

**Comment by Haidiye00** [comment]
Sorry, it doesn't include

**Comment by suchabadperson** [comment]
The same issue is present in 1.9.4. This doesn't occur in OrcaSlicer (where the center of coordinates for an added part aligns with the main object) or in Bambu Studio versions before 1.9.0.

**Comment by Haidiye00** [comment]
Sorry, this feature is still in beta testing, please wait~

**Comment by suchabadperson** [comment]
Object coordinates appear to have been added in the latest v01.10.00.74 - 1.10.0 Public Beta. Well done!”

**Comment by Haidiye00** [comment]
Thank you, we will continue to work hard~
