### ISSUE TITLE
Buttons on 'Prepare' screen are invisible

### ISSUE THREAD

**Issue by lesserevil** [bambulab/BambuStudio#3792]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

VirtualBox VM running on Ubuntu 22.04

### Printer

X1C

### How to reproduce

Open app, go to 'preview' screen, 

### Actual results

No buttons along the top. If I mouse over where the buttons should be, I can see the tooltips, and I can click on them but I can't see them.

### Expected results

Buttons visible

### Project file & Debug log uploads

Happens on all projects, even empty ones.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
we have linux versions, could you try linux version instead of the windows version on virtual box?

**Comment by lesserevil** [comment]
Moved to the linux version, no longer having the issue.
