### ISSUE TITLE
1.9.0 Beta - Increased filament consumption / filament changes

### ISSUE THREAD

**Issue by TeDsWeb** [bambulab/BambuStudio#3808]
### Bambu Studio Version

1.9.0 Beta

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Additional system information

CPU: 8th Intel i7 8750h
Memory: 32 GB
Display Card: Nvidia 1050Ti MaxQ

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. Activate support interface with Bambu Lab Support for PLA
2. Enable support (tree (auto)) on build plate only
3. Slice the build plate

### Actual results

![new_filament_usage](https://github.com/bambulab/BambuStudio/assets/12954732/e4ff81ce-bba7-4f9f-835f-a509d85967a6)
Filament consumption and filament change times have increased by 19 changes compared to the old filament behavior.

### Expected results

![old_filament_usage](https://github.com/bambulab/BambuStudio/assets/12954732/5b05d3b4-17a1-4272-bace-6a452f8f47c1)
The focus of filament changes should be on reducing waste as much as possible rather than increasing it.

### Project file & Debug log uploads

I regret to say that I cannot share the project file publicly. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
could you share the settings you are using?
what are the printer/filaments/process configs you using
@TeDsWeb

**Comment by TeDsWeb** [comment]
Sure, I used the following settings
Printer profile: Bambu Lab X1 Carbon 0.4 nozzle
Global print profile: 0.20mm default
and the recommended settings for Bambu Support For PLA as support interface

Filaments:
1. Bambu Support For PLA (white)
2. Bambu PLA Matte PLA (ivory white)
3. Bambu PLA Basic (black)
4. Bambu PLA Basic (silver)

[Demo Config.zip](https://github.com/bambulab/BambuStudio/files/14833639/Demo.Config.zip)
I removed the real model because I'm not allowed to make it public, but this project file contains all the other settings and filaments I used.

**Comment by TeDsWeb** [comment]
If the config doesn't help, I could also send you the model and config in another way, as long as it is not public. 
@lanewei120

**Comment by lanewei120** [comment]
> If the config doesn't help, I could also send you the model and config in another way, as long as it is not public. @lanewei120

thanks, @XunZhangBambu will contact you

**Comment by XunZhangBambu** [comment]
@TeDsWeb  Could you please send the model and config to me? My email is xun.zhang@bambulab.com. Thanks

**Comment by TeDsWeb** [comment]
Hi @XunZhangBambu, did the model and config I sent you already help you figure out what's going wrong?

**Comment by XunZhangBambu** [comment]
@TeDsWeb  Yes. Thanks for you model. We have identified the differences. For the model ,the support has a little bit difference so it intruduces more filament change.
