### ISSUE TITLE
Top layer setting has No effect

### ISSUE THREAD

**Issue by TwoMinus** [bambulab/BambuStudio#3824]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

BAMBU X1C

### How to reproduce

1. Open bambu studio
2. Load any 3D model or add primitive
3. Under Strength -> Top shell layers -> Set to any number i.e 1
4. Slice model 
5. The the top layers setting gets omitted and 5 layers are printed

![image](https://github.com/bambulab/BambuStudio/assets/78313705/1007ab9b-8034-433a-93c4-b92062188f0c)

Please fix ASAP as this is a major issue.

### Actual results

The top layer setting you just set gets ommited and intead the model is sliced with 5 top layers.

![Untitled](https://github.com/bambulab/BambuStudio/assets/78313705/0e5bae55-896f-46ef-9112-fa7cb6182673)

### Expected results

The slicer should add the correct number of top layers

### Project file & Debug log uploads

[Cube_error_top layers.zip](https://github.com/bambulab/BambuStudio/files/14883628/Cube_error_top.layers.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/88779481-8a79-41f1-8ffa-5d8f7ac8a475)
Set shell thickness to be 0
