### ISSUE TITLE
Bambu studio unhandled unknown exception

### ISSUE THREAD

**Issue by sparky148** [bambulab/BambuStudio#3825]
### Bambu Studio Version

v01.08.04.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Additional system information

CPU: intel i9 9900k RAM:16gb 3200mhz ddr4 GPU: Nvidia 3080

### Printer

Bambu x1c 

### How to reproduce

Open ASUS GPU Tweak II and then bambu studio

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/79156274/02c6556a-20c6-4448-b8a1-74a3e9b70133)

### Expected results

bambu studio opens as usual

### Project file & Debug log uploads

[debug_Fri_Apr_05_13_13_04_32316.log](https://github.com/bambulab/BambuStudio/files/14885276/debug_Fri_Apr_05_13_13_04_32316.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by sparky148** [comment]
I think I've found the issue it seems to be an incompatibility with ASUS GPU tweak II

**Comment by lanewei120** [comment]
Glad to hear that

so how do you find the root cause, and how to solve it?

**Comment by sparky148** [comment]
I just saw in the logs that it was somehow hooking into asus gpu tweak so I closed gpu tweak and bambu studio opened as usual

**Comment by lanewei120** [comment]
thanks~
