### ISSUE TITLE
Make the desiccant meter larger and/or include in the help popup

### ISSUE THREAD

**Issue by DanTup** [bambulab/BambuStudio#3827]
This has been looked at before in https://github.com/bambulab/BambuStudio/issues/1120. It was re-raised in https://github.com/bambulab/BambuStudio/issues/2678 but that was closed as a dupe (although I can't find any activate issues, the original one was closed long before).

I still feel like this icon is too small to read, and when you click on it you get a help popup that shows a static image (which is a little misleading, but also a missed opportunity to show a larger version of the graphic IMO).

It seems like there is plenty of space to make this a bit larger and more readable:

![image](https://github.com/bambulab/BambuStudio/assets/1078012/2000d92c-cd88-4a80-ab1b-e81ae006c858)

And if not, maybe it could be shown bigger in the help popup?

![image](https://github.com/bambulab/BambuStudio/assets/1078012/7c07c279-01a9-49a4-a482-e13219371b75)

**Comment by RicVilla78** [comment]
in the beta there is now a drop with a number which even small is easy to read.

![image](https://github.com/bambulab/BambuStudio/assets/53941830/161c3dfb-77db-4952-8405-7b6a27ed4294)

**Comment by DanTup** [comment]
Oh that looks much better (although I wonder why the second value to indicate how good it thinks the remaining desiccant is has been removed?).
