### ISSUE TITLE
Control Parts Cooling Fans by Layer

### ISSUE THREAD

**Issue by wirlybird** [bambulab/BambuStudio#383]
Would Like the ability to set the parts cooling fan speed on a per layer basis.
This can be very useful with materials such as ABS where you might want cooling only at a specific point.

**Comment by SaltWei** [comment]
> This can be very useful with materials such as ABS where you might want cooling only at a specific point.

For this case, you can close cooling of ABS at filament setting first.
![image](https://user-images.githubusercontent.com/110660407/222383108-31944970-cb08-4631-81c4-7db052d20597.png)
And then inset M106 S[fan_speed] at certain layer. Value is from 0 to 255.
![image](https://user-images.githubusercontent.com/110660407/222383348-b5134f96-e2c7-4e58-b560-c601a51a43ab.png)
![image](https://user-images.githubusercontent.com/110660407/222383393-ca963908-6202-453f-9cb9-f656290580d9.png)
