### ISSUE TITLE
Filament Experimental Option Not Visible

### ISSUE THREAD

**Issue by talmax1124** [bambulab/BambuStudio#3851]
### Bambu Studio Version

Beta 1.9.0.69

### Where is the application from?

Bambu Lab github releases

### OS version

MacOS Sonoma 14.3.1

### Printer

Bambu Labs P1S

### How to reproduce

1. Choose Filament
2. Setting Overides
3. Retraction [Experimental] is not present

### Actual results

Once I follow the steps from the Beta Release on Github, it shows the Experimental for the Printer but not the Filament. 

<img width="505" alt="Screenshot 2024-04-09 at 2 43 43 AM" src="https://github.com/bambulab/BambuStudio/assets/61528430/81d47598-88d3-48fe-af11-5a0c3bbad51c">

### Expected results

Show the Retraction Experimental Option for Filament as shown in Beta Release

### Project file & Debug log uploads

<img width="505" alt="Screenshot 2024-04-09 at 2 43 43 AM" src="https://github.com/bambulab/BambuStudio/assets/61528430/e6a60bc0-b118-4d8b-ab39-142e8466cc6e">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by XunZhangBambu** [comment]
@talmax1124 
Currently only X1 and X1C support this feature in filament params
![image](https://github.com/bambulab/BambuStudio/assets/139755545/8bba6184-f8ad-42bd-b0f5-817948a988bd)
