### ISSUE TITLE
Auto-Orient Not Auto Orienting

### ISSUE THREAD

**Issue by jebsimmons** [bambulab/BambuStudio#3855]
### Bambu Studio Version

1.9.0.69

### Where is the application from?

Bambu Lab github releases

### OS version

14.4.1 (23E224)

### Printer

X1C

### How to reproduce

1. Import .stl
2. Press Auto-Orient Button
3. See that it doesn't Auto Orient

### Actual results

No action is taken on the object.

### Expected results

For the object to flip to the best orientation. 

### Project file & Debug log uploads

<img width="632" alt="Screenshot 2024-04-09 at 4 55 26 AM" src="https://github.com/bambulab/BambuStudio/assets/3419822/bbd3a078-3f7e-43e7-8a99-3fb70e264b36">

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by tangketan** [comment]
The object's orientation is already the best according to the algorithm. Of course, algorithms can make mistakes. You may share the model to help us improve.

**Comment by jebsimmons** [comment]
> The object's orientation is already the best according to the algorithm. Of course, algorithms can make mistakes. You may share the model to help us improve.

I can't share the model- it's IP. This in the image is a lid- the top is flat an in the current production release it lays the flat side on the bottom. In this beta release it does not. @capsel22 can confirm this is happening with multiple models. The algorithm is not choosing the optimal print layout.

**Comment by jebsimmons** [comment]
Seems to be fixed in that latest Public Beta 1.9.1.58
