### ISSUE TITLE
Beta 1.9.0 beta 2 - Error "Voronoi cell doesn't contain a sourcepoint"

### ISSUE THREAD

**Issue by 3dprintandpaint** [bambulab/BambuStudio#3859]
### Bambu Studio Version

1.9.0.69

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Additional system information

AMD Ryzen 7 3700X 8-Core Processor, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)
B450 TOMAHAWK MAX (MS-7C02)
AMD Radeon RX 5700 XT

### Printer

X1C

### How to reproduce

Trying to slice the following multicoloured model from Cults3d https://cults3d.com/en/3d-model/home/holy-quin

Error is reported within seconds of slicing and the file cannot be printed.  Does not happen in Orca.

### Actual results

![Screenshot 2024-04-10 064209](https://github.com/bambulab/BambuStudio/assets/113126939/a8ad16dd-c5be-45dc-9af4-c30a4ea2be63)

### Expected results

Expect model to slice.

### Project file & Debug log uploads

Project is too big to upload, even zipped.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@3dprintandpaint could you upload this 3mf to another place
or includes it in email sending to lane.wei@bambulab.com

thanks

**Comment by 3dprintandpaint** [comment]
Email sent 👍

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.01.56, you can have a try.
