### ISSUE TITLE
Use last color for next layer

### ISSUE THREAD

**Issue by Dan203** [bambulab/BambuStudio#3863]
When doing a multicolor print the slicer should be smart enough to use the last color from the previous layer as the first color for the next layer to save a color change and purge. Right now it seems to always cycle through the colors in order regardless of which colors are used on a given layer. If you used the last color from the previous layer as the first color on the next layer it would save quite a few purges. Bonus points if it could be planned out so that the last color used was always a color needed for the next layer even if the next layer has fewer colors than the previous one.

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/90809e2e-c3da-4430-aa36-58863e9980c2)
![image](https://github.com/bambulab/BambuStudio/assets/110660407/59412919-0faf-439a-a5a5-107380e1670c)
Seems to be ok as your suggestion with the latest version

**Comment by Dan203** [comment]
Hmmm... I sat there and watched it print and saw it not do this. I was using the latest release version, not the beta though, so maybe this is a recent addition?

My model had a prime tower, could that affect it? I can't read G-Code so I'm not exactly sure what you're pointing out in your screenshots.

**Comment by SaltWei** [comment]
> My model had a prime tower, could that affect it? I can't read G-Code so I'm not exactly sure what you're pointing out in your screenshots.

We also use the latest release version, and seems to be OK as well. Could you share your 3mf as zip file so we can help to check the color order?

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/f359955a-3c87-4006-9b1a-8b72592a2ad0)
@Dan203  Have you specified the printing order of all layers here?
Or could you share your 3mf file so that we can better analyze the problem?

**Comment by Dan203** [comment]
I just tested with the latest beta and it is working correctly, so either this has already been fixed or I was wrong and it wasn’t working the way I thought. 

Anyway sorry for the bad report, please close.

**Comment by SaltWei** [comment]
Thank you very much!
