### ISSUE TITLE
Unwanted extrusion

### ISSUE THREAD

**Issue by mdkendall** [bambulab/BambuStudio#3868]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

CPU: i7 4770, Memory: 16GB, GPU: GTX 1660 Super

### Printer

Bambulab A1

### How to reproduce

1. Open attached project
2. Click "Slice plate"
3. On Preview tab, observe huge unwanted extrusion diagonally across layer 66.

### Actual results

![image](https://github.com/bambulab/BambuStudio/assets/667844/4e3c6aac-a32c-4f95-9fac-373af2b596a0)

A large amount of unwanted filament was extruded here, resulting in a print failure.

### Expected results

No unwanted extrusion

### Project file & Debug log uploads

[Press Tool v4.zip](https://github.com/bambulab/BambuStudio/files/14951513/Press.Tool.v4.zip)
[debug_Thu_Apr_11_14_31_15_11532.log.zip](https://github.com/bambulab/BambuStudio/files/14951514/debug_Thu_Apr_11_14_31_15_11532.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.00.70, you can have a try.
