### ISSUE TITLE
Top layer is printed in the air with Gyroid in fill pattern.

### ISSUE THREAD

**Issue by Panda631** [bambulab/BambuStudio#3871]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Win11

### Printer

X1C & 2xAMS

### How to reproduce

Create a model with Gyroid infill pattern or download this model from maker world (e.g. plate 5)
https://makerworld.com/en/models/105669#profileId-112806
After slicing, look at layer 207. The base for the square holes are printed into the air and results in problems.

![grafik](https://github.com/bambulab/BambuStudio/assets/138193590/4a7cd429-de9f-4c7d-b867-2a722c7613b8)

### Actual results

The printed part is quite uneven and has mechanical problems

### Expected results

A reliable support structure should be built for that.

### Project file & Debug log uploads

3mf file is online available

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by dragon-eyes-bbl** [comment]
hi @Panda631  could you try again in the latest 1.9.1 beta4 to see if it has been fixed? I cannot reproduce it with the latest release. 
From layer 207 to 210, i didnt find this layer. 
Let me know how is it. Thanks!

![image](https://github.com/bambulab/BambuStudio/assets/141289617/e5251b93-50cb-416f-bb91-2b501f930e62)

**Comment by dragon-eyes-bbl** [comment]
Close as inactive. Please reopen if the problem presist in the new release.  Thanks
