### ISSUE TITLE
Changing Filament With Height Range Modifier Does Not Work On Assemblies

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#3876]
### Bambu Studio Version

1.9.0.7

### Where is the application from?

Bambu Lab github releases

### OS version

Win 11

### Additional system information

10th Gen Core i5 32GB

### Printer

Slicer - All Printers

### How to reproduce

Sometimes I use a height range modifier to change colors at certain layers. This feature works fine on models that are not assemblies. (It worked in v1.7 but not 1.8). If two models are assembled together, all modifiers in the height range seem to work EXCEPT the color change. To reproduce this problem:
1) Add a cube and a cylinder primitive to the plate.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/837b3e21-4fbc-47f7-aabb-8597e0b37bd0)
2) Confirm that the height range modifier works the cube. I set a color change and infill change from 5mm to 10mm
![image](https://github.com/bambulab/BambuStudio/assets/96731892/25d61688-84ff-431b-acc6-69ae454aa8a9)
3) Now assemble the cube to the cylinder and confirm that the height range modifier applies to the entire assembly
![image](https://github.com/bambulab/BambuStudio/assets/96731892/6fde674f-18da-45fc-a7b7-30a57fe8fb10)

### Actual results

Notice that the infill=0 modification applies to both object, but the color change does not
![image](https://github.com/bambulab/BambuStudio/assets/96731892/9a7b2aec-ada9-4184-9acf-1bff5addb87a)

### Expected results

Expected that the color change would apply to both objects just like the infill modifier. 

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.01.66, please have a try.

**Comment by MadMax389** [comment]
Confirmed fixed, thank you.
