### ISSUE TITLE
Critical Slicer Bug: Quality > Precision > Arc fitting

### ISSUE THREAD

**Issue by etkaar** [bambulab/BambuStudio#3886]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu P1S

### How to reproduce

Use the profile "0.20mm Strength @BBL X1C" and slice the object in "FaultyPrintSkadisBox.zip". Please it into the middle of the plate.

### Actual results

The option "arc fitting" will lead the nozzle to do that:

![image](https://github.com/bambulab/BambuStudio/assets/40885610/dd39b510-e73c-495d-b193-a9c0459233d5)

In real life that looks like. It can destroy the printer:

![image](https://github.com/bambulab/BambuStudio/assets/40885610/6b5f3878-85b9-418a-86e6-8f4135f08c38)

See also this video: https://www.youtube.com/watch?v=3uOYAfzQhCI
See also this forum thread: https://forum.bambulab.com/t/print-dramatically-failed-never-seen-before/70144

### Expected results

See above.

### Project file & Debug log uploads

[FaultyPrintSkadisBox.zip](https://github.com/bambulab/BambuStudio/files/14972525/FaultyPrintSkadisBox.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.00.70, you can have a try.
