### ISSUE TITLE
Bambu Studio Crashing When Slicing

### ISSUE THREAD

**Issue by docshiv** [bambulab/BambuStudio#3899]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro Version 22H2

### Additional system information

Processor: Intel(R) Core(TM) i7-14700K 3.40 GHz
Installed RAM: 32.0 GB (31.8 GB usable)
System type: 64-bit operating system, x64-based processor
Video Card: NVIDIA GeForce RTX 4060 Ti

### Printer

Bambu Lab X1 Carbon

### How to reproduce

Import model "main helmet (textured) wing separated Wolverine D3 helmet Do3D.stl" File is 
Click "Slice plate"

### Actual results

Bambu Studio crashes at 25%. It says it's generating walls. 
![BambuStudio_Crashing](https://github.com/bambulab/BambuStudio/assets/167266309/bb483b5b-ee89-4cd6-b18e-b331d75cadad)

### Expected results

The model should be sliced and ready to print.

### Project file & Debug log uploads

[bambu-studio.exe.14520.dmp](https://github.com/bambulab/BambuStudio/files/15004694/bambu-studio.exe.14520.dmp)
[crash_Tue_Apr_16_21_14_41_0_done.log](https://github.com/bambulab/BambuStudio/files/15004696/crash_Tue_Apr_16_21_14_41_0_done.log)
[bambu-studio.exe.30756.dmp](https://github.com/bambulab/BambuStudio/files/15004697/bambu-studio.exe.30756.dmp)
[crash_Tue_Apr_16_21_12_23_0_done.log](https://github.com/bambulab/BambuStudio/files/15004698/crash_Tue_Apr_16_21_12_23_0_done.log)
[main helmet (plain) wing separated Wolverine D3 helmet Do3D.zip](https://github.com/bambulab/BambuStudio/files/15004689/main.helmet.plain.wing.separated.Wolverine.D3.helmet.Do3D.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/d30d8b0d-aba6-4c04-bfd2-b61bbdf92fc3)
The la'test version [1.9.0.70](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.70) seems to be OK. Could you have a try?

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/fcac37da-16b0-4de3-a8c9-7fe5e01521e0) hi, it seams that it crashed on clipper lib. if you rotate the model, will the model be sliced successfully? if you update the old version or latest version works? and you may try this method to seem if it works. #3318

**Comment by ozgur640** [comment]
Try setting process affinity to 4 cores in task manager for bambustudio.exe, this helped me.

**Comment by QingZhangBambu** [comment]
@ozgur640, as this method works, you may want to do a CPU test and install a new CPU

**Comment by ozgur640** [comment]
> @ozgur640, as this method works, you may need to do a CPU test and install a new CPU

Hi thanks for the reply, My processor is i9 13900k and quite new. Some older programs (rocksmith etc) cant handle too many cpu cores, thats why i play with affinity if it crashes. May be its related to prusaslicer (which bambustudio is based on), my operating system (Win10) or my gpu (gtx1070).
Best Regards..
