### ISSUE TITLE
[Feature request] local rst camera feed stream

### ISSUE THREAD

**Issue by DutchDevelop** [bambulab/BambuStudio#39]
With local controll being priortized,
I would like to see aubility to get the camera feed by going to the printer's ip,
this would allow us to still see whats going on in the printer even if the access to the outside world gets cut.

**Comment by wuyifanfancy** [comment]
This feature is in our plan and will be implement in future release.

**Comment by Fire-** [comment]
@wuyifanfancy could you provide an ETA for this? With the addition of the Go Live feature, it's fairly disappointing that video does not work at all when the printer is in LAN mode.

**Comment by SaltWei** [comment]
https://github.com/bambulab/BambuStudio/issues/1536
