### ISSUE TITLE
模型完整但切片规划的走线路线是破碎的

### ISSUE THREAD

**Issue by maamzhe** [bambulab/BambuStudio#3905]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows11

### Additional system information

cpu：amd radeon 7735h
memory：32g
display card：nvidia 4060 laptop

### Printer

x1c   p1s

### How to reproduce

模型是完整的，但是切片后的走线路径会有缺失，打印出来也是缺失了部分模型。已经自动修复了飞流形边。
![image](https://github.com/bambulab/BambuStudio/assets/128833147/580079cb-b7d6-4a99-9fdd-f8fb95f08ccb)
![image](https://github.com/bambulab/BambuStudio/assets/128833147/6061bd70-0358-43aa-b081-11d525c5f139)

### Actual results

切片后的走线路径会有缺失，打印出来也是缺失了部分模型

### Expected results

不知道是我的操作问题，还是软件bug？或者是模型有什么问题？

### Project file & Debug log uploads

[log - 副本.zip](https://github.com/bambulab/BambuStudio/files/15024844/log.-.zip)
[试试封檐板.zip](https://github.com/bambulab/BambuStudio/files/15024849/default.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
太薄的模型切出来可能实际打印质量也一般，可以先打印试试。最好还是适当增厚一点
