### ISSUE TITLE
Slicer Bug - Major artifacts due to color layer height.

### ISSUE THREAD

**Issue by Brappineau** [bambulab/BambuStudio#3918]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 x64

### Additional system information

Ryzen 7 2700X
Asus Tuff V2 3070 OC edition
64GB Ram

### Printer

P1S

### How to reproduce

File itself was inspected and clean
File appears clean in preview window, but causes artifacts after slicing.

### Actual results

![slicing artifact 2](https://github.com/bambulab/BambuStudio/assets/109556141/01e48264-2002-4cfc-9a7d-13b7fb59f12a)

### Expected results

here is 2 images. 
1: expected results in preview pane
2: shows artifacts after slicing the plate

![slicing artifact](https://github.com/bambulab/BambuStudio/assets/109556141/297516f8-e209-48e6-89f9-a5cc8e35fa98)

### Project file & Debug log uploads

[example of artifacting - bug.zip](https://github.com/bambulab/BambuStudio/files/15048471/example.of.artifacting.-.bug.zip)
[color artifact - slicer bug.zip](https://github.com/bambulab/BambuStudio/files/15048479/color.artifact.-.slicer.bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@Brappineau  It has been fixed, you can have a try on the latest version v01.09.00.70
