### ISSUE TITLE
Z motion loud noise after print

### ISSUE THREAD

**Issue by parksddd** [bambulab/BambuStudio#393]
On X1 non-carbon when the print completes the Z motors produce an extremely loud noise while lowering the bed.
It seems to be after an update that reduced the power to the z-motor.

Please consider increasing the power to the motor to reduce this noise.

**Comment by RobinWhitfield** [comment]
This has been discussed a little bit on the Discord. It seems some specific printers slip z-steps with the new lower motor current value.

Raising it back to 0.45 or so resolves the issue.

**Comment by parksddd** [comment]
Yes. It would be nice if Bambu fixed it in the code for the default profiles.

**Comment by RobinWhitfield** [comment]
The presumption is that it was done in order to further reduce the potential for damage when lowering the bed, so lowering the speed the bed descends at might be a suitable alternative option to raising the current again.

**Comment by ZzzGin** [comment]
@RobinWhitfield , is there a Discord channel? Is it public (for all printer purchasers)?

**Comment by RobinWhitfield** [comment]
> @RobinWhitfield , is there a Discord channel? Is it public (for all printer purchasers)?
https://discord.com/invite/Jmby9N4t8E

**Comment by YifanWuBambu** [comment]
Fixed in v.1.3.0.12.
