### ISSUE TITLE
Not uploading from Makerworld web site.

### ISSUE THREAD

**Issue by MaximusStalsky** [bambulab/BambuStudio#3947]
### Bambu Studio Version

1.9.0.70

### Where is the application from?

Bambu Lab github releases

### OS version

win 11

### Additional system information

5800x3d. 4080, 32gb ram, water cooled

### Printer

Bambu Lab x1 carbon ams

### How to reproduce

Just try to open any print from makerworld web site in bambu studio 

### Actual results

Nothing show up in the slicer.

### Expected results

The model should show up in the slicer

### Project file & Debug log uploads

[fail.zip](https://github.com/bambulab/BambuStudio/files/15097714/fail.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by walterwongbbl** [comment]
@MaximusStalsky 
![image](https://github.com/bambulab/BambuStudio/assets/120699126/90d33b27-cb79-4a73-accb-f6b87b12a62b)
I have loaded your 3mf file, which does not contain any model data. Where did I get this file from.

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/ff25e356-c6b0-4cfa-a1d0-e24c1f929122)
Too small 3mf and can not open

Wait for response for a long time. Close.

Reopen if still has this problem
