### ISSUE TITLE
MacOS client crashes when i click print

### ISSUE THREAD

**Issue by bterps** [bambulab/BambuStudio#3954]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Sonoma 14.4.1

### Additional system information

Macbook Pro 2019
2.3 GHz 8-Core Intel Core i9
AMD Radeon Pro 5500M 4 GB
Intel UHD Graphics 630 1536 MB
16 GB 2667 MHz DDR4

### Printer

Bambu Lab X1 w/ AMS

### How to reproduce

The last 2 prints i've prepared it, sliced it, then when i click "Print Plate" it sends the info to the printer but the program crashes

### Actual results

Program crashes

### Expected results

Program doesn't crash and goes to device screen

### Project file & Debug log uploads

[makita.3mf.zip](https://github.com/bambulab/BambuStudio/files/15124860/makita.3mf.zip)
[logs.zip](https://github.com/bambulab/BambuStudio/files/15124888/logs.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @bterps 
Please try again using version 1.9.1 or 1.9.2
