### ISSUE TITLE
model is completely messed up when I run slice plate

### ISSUE THREAD

**Issue by mikevanoostende** [bambulab/BambuStudio#3959]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

mac os

### Printer

X1

### How to reproduce

upload stl file, doesn't matter which quality, then when i select "slice plate" the model is completely ruined 
I did not even have to print it, problem is with the software.

![Schermafbeelding 2024-04-26 om 17 21 54](https://github.com/bambulab/BambuStudio/assets/3439472/7b7551bf-85cb-4818-bade-59219a2dba58)
![Schermafbeelding 2024-04-26 om 17 22 45](https://github.com/bambulab/BambuStudio/assets/3439472/a18ab65d-2abe-414d-98ef-82ba0d8ff947)
![Schermafbeelding 2024-04-26 om 17 22 54](https://github.com/bambulab/BambuStudio/assets/3439472/f037b078-76cc-4057-9fd7-1c3e0d70b99e)
![Schermafbeelding 2024-04-26 om 17 23 03](https://github.com/bambulab/BambuStudio/assets/3439472/94bacee9-66ba-4af8-a622-00f3442e3d7d)

### Actual results

This used to work fine with other versions of bambulab...

### Expected results

proper slicing

### Project file & Debug log uploads

[tubes_18-12-23.STL.zip](https://github.com/bambulab/BambuStudio/files/15132469/tubes_18-12-23.STL.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by mikevanoostende** [comment]
Dear, 

I've done a restart of the software, and now it works again, not sure what happend the first time, so i guess.. you can close this .

**Comment by lanewei120** [comment]
thanks for doing this

let's reopen it after it can be reproduced
