### ISSUE TITLE
Typo in tooltip: Internal solid infill pattern

### ISSUE THREAD

**Issue by patridge** [bambulab/BambuStudio#3961]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

N/A

### Printer

Bambu Lab A1 mini

### How to reproduce

Hover the **Internal solid infill pattern** value field until the tooltip shows up.

The word "narrow" will be misspelled as "nattow". Possibly a result of one of these two lines:
* https://github.com/bambulab/BambuStudio/blob/cfb273c84a229af86a3b926dd51baa779de93f9b/src/libslic3r/PrintConfig.cpp#L1179
* https://github.com/bambulab/BambuStudio/blob/cfb273c84a229af86a3b926dd51baa779de93f9b/bbl/i18n/BambuStudio.pot#L7974

### Actual results

Tooltip text: "Line pattern of internal solid infill. if the detect nattow internal solid infill be enabled, the concentric pattern will be used for the small area."

### Expected results

Tooltip text: "Line pattern of internal solid infill. if the detect narrow internal solid infill be enabled, the concentric pattern will be used for the small area."

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by murongguao** [comment]
Thank you very much for your question, it will be fixed.

**Comment by andypiper** [comment]
Confirmed here as well, came to report the same thing, noticed today.

<img width="384" alt="Screenshot 2024-05-07 at 15 08 53" src="https://github.com/bambulab/BambuStudio/assets/552452/3e4ee5d0-db9c-4aa4-9ed3-ee3b2a77f603">

**Comment by DanBao-Bambu** [comment]
@andypiper Your requirements have been recorded.
