### ISSUE TITLE
Generic BOVH

### ISSUE THREAD

**Issue by laakvandetim** [bambulab/BambuStudio#3969]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1 +AMS

### How to reproduce

Material selection BOVH is not available in the slicer software. Generic BOVH option only exist in the printer after selecting that option. this creates an issue when printing from the slicer, AMS will not update in the slicer as that BOVH material dont exist.

### Actual results

error

### Expected results

Add Generic BOVH to the slicer material config 

### Project file & Debug log uploads

I dont know

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by XunZhangBambu** [comment]
@laakvandetim
We have previously released a configuration package, which includes Generic BVOH. You can try again after installing the material package
![image](https://github.com/bambulab/BambuStudio/assets/139755545/9f12d845-ce09-49e3-8530-9378635cc603)
