### ISSUE TITLE
[Feature Request] Looking for Profiles & Presets for 0.6mm nozzle

### ISSUE THREAD

**Issue by lord-x-type** [bambulab/BambuStudio#397]
Hi there,
i was looking for some profiles/presets for a .6mm nozzle. As i looked in the slicer  i recognized there is only 1 Profile for .3mm layer hight.
Would it be possible to publish some more presets for like at the .4mm nozzle from draft to super fine?

This would be grate!
Best regards

**Comment by YifanWuBambu** [comment]
![image](https://user-images.githubusercontent.com/110661856/194760621-fe4889c6-693f-4d05-a174-1970ef9f9285.png)

Please update to 1.2.0.9.

**Comment by lord-x-type** [comment]
Sorry for reopening.. but this did not solve the problem.
![grafik](https://user-images.githubusercontent.com/36933443/194767959-495b4a92-612a-4512-bc0e-259e45b6ddd1.png)
i am using the latest source, had added the 0.6mm nozzle but still have only the 0.3mm layer hight profile when selecting the .6mm nozzle preset..
![grafik](https://user-images.githubusercontent.com/36933443/194768073-79be2921-f968-4f68-8c76-f3457364e5a5.png)
what am i doing wrong?
is there a way to get other ones?
