### ISSUE TITLE
Setting Top Z Distance with Tree Hybrid creates missing layers 

### ISSUE THREAD

**Issue by AJZein** [bambulab/BambuStudio#3982]
### Bambu Studio Version

01.09.01.58

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

Bambu Lab P1P

### How to reproduce

Slice the included .3mf file. Look around layers 78 and 294 to see the mentioned missing layers. Reset Top Z distance or uncheck Independent Support Layer Height and slicing returns to normal.

### Actual results

The missing layers caused the model to split at those points. Below are images of the missing layers in the sliced model and the (full) printed model
![Capture](https://github.com/bambulab/BambuStudio/assets/45639168/4466821e-6e1e-4be3-8417-2b3c572801a6)
![Capture2](https://github.com/bambulab/BambuStudio/assets/45639168/393987ea-db42-4dd5-9961-eb40e128cc7a)
![20240430_125421](https://github.com/bambulab/BambuStudio/assets/45639168/712cd499-3d3a-4922-920f-a56206126e85)

### Expected results

No missing layers created when slicing

### Project file & Debug log uploads

[tree_support_lines_test.zip](https://github.com/bambulab/BambuStudio/files/15163101/tree_support_lines_test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
Thanks for reporting the issue. We'll fix it soon.

**Comment by AJZein** [comment]
Confirmed fixed in version 1.9.2.57
