### ISSUE TITLE
Change "Combinate" to "Combine"

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#4000]
### Bambu Studio Version

1.9.1.58

### Where is the application from?

Bambu Lab github releases

### OS version

Win11

### Additional system information

10th Gen Core i5

### Printer

Slicer - All Printers

### How to reproduce

The word "Combinate", in English, is a noun meaning the result of a combination. A verb like "Assemble" (as it was previously), "Combine", or "Group" would be more appropriate in the context menu in the slicer. Minor issue, I know, but "combinate" doesn't make sense in this context.
![image](https://github.com/bambulab/BambuStudio/assets/96731892/f2a88278-1315-4c8f-bb39-723b3dd234c9)

### Actual results

NA

### Expected results

NA

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
Hello, after our internal discussion, we plan to use the same word as prusaSlicer for the word "combine": Merge.
This issue will be resolved in the upcoming OTA version~

**Comment by scotta316** [comment]
"Merge" sounds permanent, like a Boolean union. Assemble makes more sense, as there will still be individual parts.

**Comment by Haidiye00** [comment]
It's a bit, but we still refer to the term prusa

**Comment by Haidiye00** [comment]
This issue has been fixed. Please use the latest version. Thank you
