### ISSUE TITLE
Unwanted skirts when printing By Object

### ISSUE THREAD

**Issue by scotta316** [bambulab/BambuStudio#4002]
### Bambu Studio Version

Beta version 1.9.1.58

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab P1S Combo

### How to reproduce

- Go to the Preview tab
- Put more than one object on the plate
- Under Process, Global, Others, set Print sequence to "By Object." 
- Set Skirt loops to 1
- Slice plate
- Set Skirt loops to 0
- Slice plate again

### Actual results

On all objects but the first to be printed, the skirt loop remains after skirt loops is set to 0.

**Skirt loop enabled:**
![image](https://github.com/bambulab/BambuStudio/assets/161268157/987991ed-61d4-47cd-8888-37d6e7b08c7b)

**Skirt loop disabled:**
![image](https://github.com/bambulab/BambuStudio/assets/161268157/cd2ee5fe-679b-422a-9e84-691c9f25dc73)

**Nothing extra is enabled under Objects mode:**
![image](https://github.com/bambulab/BambuStudio/assets/161268157/af86caba-d1b7-49d5-a90b-7652e421eb7c)

### Expected results

All skirts should be removed when Skirt loops is set to 0.

### Project file & Debug log uploads

[uhltimateOTFKnifeSkirt.zip](https://github.com/bambulab/BambuStudio/files/15210704/uhltimateOTFKnifeSkirt.zip)
[debug_Sat_May_04_03_42_03_32660.log.zip](https://github.com/bambulab/BambuStudio/files/15210713/debug_Sat_May_04_03_42_03_32660.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@scotta316  It has been fixed in v01.09.02.57, please have a try.
