### ISSUE TITLE
Bed Adhesion

### ISSUE THREAD

**Issue by iamjameshannam** [bambulab/BambuStudio#4007]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS 14.4.1 (23E224)

### Printer

P1S

### How to reproduce

Printing using Generic PLA

### Actual results

Latest update has rendered the printing useless. The PLA or any material used no loner adheres to the print bed. Worked before applying the update, now nothing sticks.

Have chaged temp, speed, layer height, raft.

### Expected results

Expected to be like before the update, adhering to the bed.

### Project file & Debug log uploads

[Filament presets.zip](https://github.com/bambulab/BambuStudio/files/15224260/Filament.presets.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by SaltWei** [comment]
Not slicer issue and can not reproduce as well. Please raise ticket to custom service and custom service team will help to find the root cause. https://wiki.bambulab.com/zh/p1/troubleshooting/how-to-upload-log.

Please let us known if has any other issue. Thank you very much!
