### ISSUE TITLE
Bambu Stuber Slicer Scale arrows not correct

### ISSUE THREAD

**Issue by PoliticWatch** [bambulab/BambuStudio#4017]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 PRO

### Printer

Bambu X1 Combo

### How to reproduce

1. Click Object on Plate to resize
2. Click Scale Icon on top menu
3. Arrows on object do not match up when changing % vs actual size
![Scale Percent arrows](https://github.com/bambulab/BambuStudio/assets/169217701/9226e1c4-9aa4-4144-86cc-db49adae5830)
![Scale size arrows](https://github.com/bambulab/BambuStudio/assets/169217701/7e700263-b55d-45bb-9a52-85aee8799b79)

### Actual results

You will notice that the arrows for Y and Z point in different directions.  That is Y % and SIZE will point in different directions.  Same for the Z % and Size.

### Expected results

Expect that the arrows would point in the correct axis

### Project file & Debug log uploads

Any file

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by PoliticWatch** [comment]
That is % and Size for each of Y and Z axis point in different direction.  Z is the example in pictures.

**Comment by Haidiye00** [comment]
Hello, I just noticed that the latest version of V1.9 does not have this issue. Can you confirm it?

**Comment by PoliticWatch** [comment]
Checking for updates, it says I have the latest version.

Do I need to manually download somewhere?

- John

**Comment by Haidiye00** [comment]
Of course ,you can also download from https://github.com/bambulab/BambuStudio

**Comment by PoliticWatch** [comment]
I did not see a Windows Executable file.  Seems I will need to learn how to compile.  Will look this week end.

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/a068a123-a232-4bd6-9143-75440cb1fb78)
https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.58

**Comment by Haidiye00** [comment]
This issue has been fixed. Please use the latest version. Thank you

**Comment by PoliticWatch** [comment]
Thank you.  Downloaded…
