### ISSUE TITLE
Cant set filament multiplier less than 1 

### ISSUE THREAD

**Issue by VAdimTop25** [bambulab/BambuStudio#4020]
### Bambu Studio Version

1.9.1.58

### Where is the application from?

Bambu Lab github releases

### OS version

win11

### Printer

X1-C

### How to reproduce

if its less than 1, i cant reset it 

![image](https://github.com/bambulab/BambuStudio/assets/114261226/6b76a3fe-1630-40f5-8e6e-e83a2688c984)

### Actual results

cant use number less than 1 (like 0,5)

### Expected results

i cant use it :D 

### Project file & Debug log uploads

![image](https://github.com/bambulab/BambuStudio/assets/114261226/34c91347-7610-47b2-af0b-57565478b9ad)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MklBambu** [comment]
Thank you for reporting this issue. We have discovered this bug and will fix it in the next version. Before that, you can use English for operation.

**Comment by VAdimTop25** [comment]
I found out that its not pissible to set anything expect 1,2 and 3 ( like 2,5 / 1,5)

**Comment by MklBambu** [comment]
Hi, the new version has been released. You can try it out and verify if any issues still exist.
https://github.com/bambulab/BambuStudio/releases/

**Comment by VAdimTop25** [comment]
now its work
