### ISSUE TITLE
Add Object and Part coordinates to the part manipulation - As in Prusaslicer

### ISSUE THREAD

**Issue by GuyH77** [bambulab/BambuStudio#4024]
With multi part prints now common the ability to accurate move objects/parts is needed. BambuStudio only offers world coordinates which is extremely limiting. 

Please consider adding Object and Part coordinates to allow precise movement and positioning.  This is in Prusaslicer if you need an example. thanks

![image](https://github.com/bambulab/BambuStudio/assets/106596720/aeb2d848-7034-4755-9420-51efbb9d6660)

**Comment by Haidiye00** [comment]
We have already considered and developed it. Thank you for your suggestion

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
