### ISSUE TITLE
Text position reset upon edit

### ISSUE THREAD

**Issue by GuyH77** [bambulab/BambuStudio#4025]
### Bambu Studio Version

1.9.1.58

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 pro

### Printer

Bambu Lab X1C 0.4 nozzle

### How to reproduce

Add text to an object. Use the positioning handle to roughly place the correct location. Modify the text using the move command, to position accurately. Edit text, change text. The position resets based on the placement handle.

**Create Text**
![image](https://github.com/bambulab/BambuStudio/assets/106596720/f50e1912-1ec5-4bb0-bf76-106974180e7c)

**Position Text**
![image](https://github.com/bambulab/BambuStudio/assets/106596720/480d7c76-a90b-4ded-a614-0dbb3c51e42e)

**Edit Text**
![image](https://github.com/bambulab/BambuStudio/assets/106596720/0ea3fc29-2d05-4a91-a471-173a7a849287)

### Actual results

The text position resets upon text edit. The text tool doesn't allow precise placement so we use the move tool to position where we want. Upon edit the position is reset and we have to move the text again. Very frustrating. 

### Expected results

Text should persist and remain in the place we move it to. The location handle should only be to select the location surface and approximate position. 

### Project file & Debug log uploads

[TEXT_POSITION_TEST.zip](https://github.com/bambulab/BambuStudio/files/15265762/TEXT_POSITION_TEST.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
hello,the problem has been identified and is currently being resolved

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
