### ISSUE TITLE
multi colored filament breaking upon slicing

### ISSUE THREAD

**Issue by mryeeterson** [bambulab/BambuStudio#4027]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

win11

### Additional system information

cpu: amd ryzen 8 5950X 16 core
4x 16gb 3.6 ghz ram
gpu: nvidia rtx 3090

### Printer

Bambu Lab X1-Carbon

### How to reproduce

color something
slice
SOMETIMES breaks on layers

### Actual results

not sliced
![image](https://github.com/bambulab/BambuStudio/assets/104118156/3a5ff20b-45f6-4cb0-8af8-c8ec8391d2a3)

sliced
![image](https://github.com/bambulab/BambuStudio/assets/104118156/66cf3ae4-918b-4928-8d2e-43a6401f3b9a)

### Expected results

solid colors that dont glitch/break
only works on that area

### Project file & Debug log uploads

3mf file
[michael.zip](https://github.com/bambulab/BambuStudio/files/15269364/michael.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.01.58, you can have a try
