### ISSUE TITLE
alphabetize flow dynamics/k-value 

### ISSUE THREAD

**Issue by dekrug29** [bambulab/BambuStudio#4029]
Please alphabetize the flow dynamic results. It would make searching for values a lot quicker. Filament profiles are alphabetize, you should include this as well. 
<img width="1440" alt="Screenshot 2024-05-10 at 11 19 17 AM" src="https://github.com/bambulab/BambuStudio/assets/169482406/63cc7a09-2e74-42e9-aa88-7cb8536c1efc">

**Comment by ttt888zzz** [comment]
HI,[dekrug29](https://github.com/dekrug29):
Please try updating the latest version 1.9.4.
https://bambulab.com/en/download/studio.
