### ISSUE TITLE
Login screen is black when Bambu Studio Turkish language is selected

### ISSUE THREAD

**Issue by fatih5228** [bambulab/BambuStudio#4038]
### Bambu Studio Version

Bambu Studio 1.9.1.58

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 11

### Additional system information

i7 gen 7, Nvidia GTX 1050,  24GB ram

### Printer

Bambulab X1 Carbon Combo

### How to reproduce

Login screen black
![Ekran görüntüsü 2024-05-12 024928](https://github.com/bambulab/BambuStudio/assets/129884244/27f38428-908b-4ed8-a9fd-6fd7ca02c52d)

### Actual results

You can switch to other languages and log in. Then there is no problem when switching languages

### Expected results

Can you fix the problem?

### Project file & Debug log uploads

[debug_Sun_May_12_02_33_01_26304.log.zip](https://github.com/bambulab/BambuStudio/files/15284585/debug_Sun_May_12_02_33_01_26304.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by StoneLiBambu** [comment]
Hi,
 Our cloud configuration did not take effect, please try again.

Thanks!

Stone Li
