### ISSUE TITLE
Erroneous paths in vase mode

### ISSUE THREAD

**Issue by dibunker** [bambulab/BambuStudio#4056]
### Bambu Studio Version

1.9.1

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

CPU: AMD Ryzen 9 3950X
Memory: 128GB
GPU: EVGA GeForce RTX 2080 Super

### Printer

Bambu Lab X1C

### How to reproduce

1. Go to https://makerworld.com/en/models/460194#profileId-368625
2. Open the "with base" print profile in Bambu Studio v1.9.1 Official Release
3. Slice plate 3 (

### Actual results

On several layers, there are erroneous G1 moves

For example, on layer 49 of plate 3:
![image](https://github.com/bambulab/BambuStudio/assets/46041241/bf72c20c-684a-412a-9d51-1e65073570ef)

### Expected results

Correct/Expected path of layer 49 of plate 3 in v1.8.4.51 of Bambu Studio:

![image](https://github.com/bambulab/BambuStudio/assets/46041241/c6fda1e0-99f4-4105-988d-5b1e3b58572e)

Orca Slicer v2.0.0 also generates the correct path:

![image](https://github.com/bambulab/BambuStudio/assets/46041241/e85cb993-a2a7-4bbd-a422-74995492557e)

### Project file & Debug log uploads

[sierpinski_pyramid_with_base.zip](https://github.com/bambulab/BambuStudio/files/15299144/sierpinski_pyramid_with_base.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/15299167/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/ecb14078-2454-4d3f-ad8a-456cc3114acb)
discontinuous wall cause that, you can close slow down overhang speed to get continuous wall. 
![image](https://github.com/bambulab/BambuStudio/assets/112676417/eee19f21-291d-4757-9186-7398b38a2b09)

**Comment by QingZhangBambu** [comment]
or you can rotate a bit the model, the result wull be right.

**Comment by QingZhangBambu** [comment]
it has been fixed and will release in the next version. please wait.

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
