### ISSUE TITLE
failed boss placement

### ISSUE THREAD

**Issue by twilkers1976** [bambulab/BambuStudio#4064]
### Bambu Studio Version

1.8.4.51

### Where is the application from?

Bambu Lab Official website

### OS version

win 11

### Printer

X1C

### How to reproduce

attempt to relocate boss in z dimension failed.  it just jumps back to base plate.  see attached 3mf file

### Actual results

boss jumps back to baseplate instead of staying in desired locatoin.

### Expected results

expect boss to stay in z dimension where it is released.

### Project file & Debug log uploads

[2024_5_14Wilkerson boss placement failure.pdf](https://github.com/bambulab/BambuStudio/files/15305749/2024_5_14Wilkerson.boss.placement.failure.pdf)
[2024_5_14_wilkerson_Inner_Left 140 percent with boss.zip](https://github.com/bambulab/BambuStudio/files/15305764/2024_5_14_wilkerson_Inner_Left.140.percent.with.boss.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Hello, could you record a video to explain your issue? Thank you

**Comment by Haidiye00** [comment]
Do you still need to solve it, or have you already solved it yourself? If not resolved, please record a GIF or video. Thank you

**Comment by twilkers1976** [comment]
ResolvedSent from Tim's iPhoneOn May 20, 2024, at 3:46 AM, Haidiye00 ***@***.***> wrote:﻿
Do you still need to solve it, or have you already solved it yourself? If not resolved, please record a GIF or video. Thank you
