### ISSUE TITLE
Can't export as STL with latest BambuStudio 1.9.x

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#4065]
### Bambu Studio Version

1.9.1

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Sonoma 14.4.1

### Additional system information

M1Ultra

### Printer

P1P

### How to reproduce

1. Open .3MF
2. Select MORE THAN ONE .STL
3. Right click -> Export as one STL
4. Give a name and save.

### Actual results

Nothing is saved.

### Expected results

A .STL containing the selected STLs saved as ONE STL.

(Works fine if you just select ONE stl)

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
Sorry, the issue has been found. You can use the right-click “merge” operation to export  one STL, import multiple objects into an STL, it will be fixed in the next version

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/f4be041a-4327-496d-8245-1205c47575a5)
Also, entering through this entrance, this function is normal.
