### ISSUE TITLE
[FEATURE] Pause printing for removing calibration print for large prints

### ISSUE THREAD

**Issue by Kraminator** [bambulab/BambuStudio#407]
It would be great, if a print would print over the calibration print, if the printer would go in pause so the calibration print can be removed before the actual print starts.

**Comment by SaltWei** [comment]
Already finished. Please wait for next release.
User can add pause at layer 1.  And printer will pause after printing calibration line, before printing model first layer.

**Comment by Kraminator** [comment]
Great, thank you!

[Reto Kramer](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1ritfm)	[1ritfm]
Best regards

Reto Kramer
(239) 248-6315

On October 10, 2022 at 4:09 GMT, SaltWei ***@***.***> wrote:

Already finished. Please wait for next release.
User can add pause at layer 1. And printer will pause after printing calibration line, before printing model first layer.
