### ISSUE TITLE
Bambu Studio Very Slow

### ISSUE THREAD

**Issue by Canadian-Gamer** [bambulab/BambuStudio#4070]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

I dont have that info at hand. where do i find it

### Printer

P1S

### How to reproduce

Slice a hueforge file. 

### Actual results

Very slow, errors about floating regions, this all started last night after the update 

### Expected results

Faster slicing. upload to makerworld successfull

### Project file & Debug log uploads

[Dallas Cowboys NFL 3MF.zip](https://github.com/bambulab/BambuStudio/files/15314501/Dallas.Cowboys.NFL.3MF.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
can you slice it successfully on PC?

**Comment by Canadian-Gamer** [comment]
Yes I can.  I sliced it and printed it. I can send you a picture of the printed copy.
________________________________

**Comment by QingZhangBambu** [comment]
so just upload to MW failed?

**Comment by QingZhangBambu** [comment]
Does it cost hours to slice it on PC?

**Comment by Canadian-Gamer** [comment]
I don’t know what you mean by cost hours.

It takes longer than it did before the update to Bambu studio yesterday.  It seems like all my Hueforges take longer to slice since the update, and I had been uploading one a day at least to Makerworld for about 3 months now
________________________________

**Comment by Canadian-Gamer** [comment]
Yes in this instance just the upload to makerworld is failing.  It is saying the slicing time exceeds the limit
________________________________

**Comment by QingZhangBambu** [comment]
OK, I will talk to the concerned staff about that.

**Comment by QingZhangBambu** [comment]
they said that it did have problems last night,  but already fixed it now. Could you try it again?

**Comment by Canadian-Gamer** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/169855791/81f87e0e-a8a9-4190-bcdd-c8cac2822209)

Yah it still won't upload, it is timing out, this isn't my longest or most detailed design, as a matter of fact my printing history shows that it only took 7.3 hours so I'm surprised this one is giving me the issue

**Comment by QingZhangBambu** [comment]
@Canadian-Gamer Hi, it can upload to MW now, the bug had been fixed. I've confirmed that.
