### ISSUE TITLE
Crashing after new update on Windows 11

### ISSUE THREAD

**Issue by jmp7624** [bambulab/BambuStudio#4074]
### Bambu Studio Version

1.09.01.66

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 11

### Additional system information

CPU: AMD Ryzen 7800X3D
RAM: 32GB 6400Mhz Trident Z5 RGB DDR5
GPU: XFX RX 7900XTX

### Printer

P1S

### How to reproduce

Launching Bambu Studio

I have uninstalled and deleted all the files using revo uninstaller. I have downloaded the program from github and bambu's website, made sure windows and netframwork were up to date, restarted the computer, disabled my adblock on my router since sometimes it can cause issues with internal browsers, tried with a VPN in case the adblocker didnt completely remove itself, and I have searched all over the internet looking for hep but thing that shows up is the Mac issue. 

I do have OrcaSlicer and QIDI slicer installed but never had an issue with the previous version. 

### Actual results

Program loads up to a white screen with the normal toolbar at the top and then closes after a couple of seconds. 
![2024-05-14-20-14-53](https://github.com/bambulab/BambuStudio/assets/73203609/365b34ff-1684-403c-8d3a-8d7e77a96ab0)

### Expected results

Open normally and allow me to print.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/15315196/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by MadMaxDP** [comment]
Same issue here, near identical PC setup.

**Comment by jmp7624** [comment]
> Same issue here, near identical PC setup.

I think it has to do with AMD GPUs for some reason. I was looking at the log files and I was getting this error, "2024-05-14 20:15:04.323949[Thread 0x000005f4]:Can't create HDC by CreateCompatibleDC(NULL)." After pasting this into ChatGPT, it said the error meant there was a problem with creating a HDC in the Windows Graphics Device Interface or (GDI). My GPU driver is on the latest version too. Not sure why and update would break this when that previous version was fine and OrcaSlicer is fine. But I'm not a dev lol

**Comment by wj0nes** [comment]
Im having the same issue, my hardware is i9 with 4070ti

**Comment by jmp7624** [comment]
> Im having the same issue, my hardware is i9 with 4070ti

Well I guess my theory is wrong about it being related to AMD GPU's. May just be an external GPU altogether. Most people are using integrated graphics. But my friend has a 3060 ti and he didn't say he had any issues with the update.

**Comment by demonics420** [comment]
I'm also getting this exact same crash But I'm on Win 10, I tried deleting all the old files even in all appdata places with no luck. So I went back to the last version 1.8.4 with no issues

Specs are 
CPU: AMD 7 5800x
RAM: 32gb G.Skill 3200mhz ram 
GPU: Gigabyte RTX 3070
MOBO: Gigabyte B550 Aorus Pro
OS: Win 10
If you want my logs as well, just ask.

**Comment by jmp7624** [comment]
> I'm also getting this exact same crash But I'm on Win 10, I tried deleting all the old files even in all appdata places with no luck. So I went back to the last version 1.8.4 with no issues
> 
> Specs are CPU: AMD 7 5800x RAM: 32gb G.Skill 3200mhz ram GPU: Gigabyte RTX 3070 MOBO: Gigabyte B550 Aorus Pro OS: Win 10 If you want my logs as well, just ask.

Yeah I tried deleting everything too. I just OrcaSlicer the most anyway but I liked that they added the makerworld site in the new version

**Comment by bambu123** [comment]
@demonics420 @jmp7624 

Can you help me try the previous beta versions?
Using a zip package, no installation is required.

[1.9.1 Public Beta 4](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.58)
https://github.com/bambulab/BambuStudio/releases/download/v01.09.01.58/Bambu_Studio_win-v01.09.01.58-20240425203636.zip
[1.9.0 Public Beta 3](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.70)
https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.70/Bambu_Studio_win-v01.09.00.70-20240410162052.zip
[1.9.0 Public Beta 2](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.69)
https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.69/Bambu_Studio_win-v01.09.00.69-20240408205831.zip
[1.9.0 Public Beta](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.60)
https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.60/Bambu_Studio_win-v01.09.00.60-20240325213406.zip

**Comment by demonics420** [comment]
> Can you help me try the previous beta versions? Using a zip package, no installation is required.

@bambu123 I tried Beta 4 first and it failed but Beta 3 works so something within the change between those two..

**Comment by Haidiye00** [comment]
> > Can you help me try the previous beta versions? Using a zip package, no installation is required.
> 
> @bambu123 I tried Beta 4 first and it failed but Beta 3 works so something within the change between those two..

Can you provide beta3 log,thanks

**Comment by demonics420** [comment]
[log.zip](https://github.com/bambulab/BambuStudio/files/15329000/log.zip)

@Haidiye00 I just put both logs and crash in there but labeled them for you just in case. 
Thanks for looking into it!

**Comment by jmp7624** [comment]
> @demonics420 @jmp7624
> 
> Can you help me try the previous beta versions? Using a zip package, no installation is required.
> 
> [1.9.1 Public Beta 4](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.01.58) https://github.com/bambulab/BambuStudio/releases/download/v01.09.01.58/Bambu_Studio_win-v01.09.01.58-20240425203636.zip [1.9.0 Public Beta 3](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.70) https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.70/Bambu_Studio_win-v01.09.00.70-20240410162052.zip [1.9.0 Public Beta 2](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.69) https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.69/Bambu_Studio_win-v01.09.00.69-20240408205831.zip [1.9.0 Public Beta](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.00.60) https://github.com/bambulab/BambuStudio/releases/download/v01.09.00.60/Bambu_Studio_win-v01.09.00.60-20240325213406.zip

Beta 3 worked for me but beta 4 failed as well. I didn't find the logs to upload running the portable version but since they were uploaded already, maybe you dont need mine?

**Comment by Haidiye00** [comment]
Thank you for providing the log. We have basically identified the issue and are currently working on resolving it

**Comment by jmp7624** [comment]
Awesome, thats really quick!

**Comment by lanewei120** [comment]
@jmp7624 
could you help to try this image? https://www.dropbox.com/scl/fi/qeoxh3hfuk36hkadw2ufq/Bambu_Studio_win_public-v01.09.01.67-20240516173854.exe?rlkey=zgmquspcoyrlyd30ean8s2kns&st=5do8vjad&dl=0

if still crash, please help to send us the log.

**Comment by demonics420** [comment]
@lanewei120 That new version seems to be working just fine for me!! Thank you for the updated version!!

**Comment by jmp7624** [comment]
> @jmp7624 could you help to try this image? [studio 1.9.1.67](https://www.dropbox.com/scl/fi/qeoxh3hfuk36hkadw2ufq/Bambu_Studio_win_public-v01.09.01.67-20240516173854.exe?rlkey=zgmquspcoyrlyd30ean8s2kns&st=5do8vjad&dl=0)
> 
> if still crash, please help to send us the log.

That one does load. It did take a while to fully load into the slicer though. It was stuck on a white screen for a 20-22 seconds. Not a big deal but if I clicked on the program, windows would say it wasnt responding. After if fully loaded I haven't gotten any not responding errors so far. It also didn't install my filament profiles or custom printer profile I had for the P1S. I thought that was kind of odd because I though it was saved to my account since when I log into OrcaSlicer and make any changes to the profiles, Bambu Studio would pick up the changes immediately. I think I can import them but not sure if its normal or not since I completely deleted all the Bambu data when I was uninstalling the old version.  Here are the log files in case you still want to look at them. 
[log.zip](https://github.com/bambulab/BambuStudio/files/15339910/log.zip)

**Comment by demonics420** [comment]
@jmp7624 Your Filament profiles and other stuff like that were in the appdata/roaming/BambuStudio/user if you backed them up before deleting or if they in recycle bin just put them back in place. The first load took me a good 30 secs also, but now its loading fine.

**Comment by jmp7624** [comment]
@demonics420 Thanks for that! It did load them under the custom filament profile but not the standard profile. Not a big deal though, I use the custom one anyway cause I changed some settings to utilize the full build volume. Hopefully the profiles will still sync back and forth between Orca, I like using both. I tried to export my profiles from Orca but Bambu wouldn't read it cause it wasn't a config file. As for the speed issue, It took me longer the first time but its still taking about 20 seconds to load. It probably has to do with my adblocker. That seems to cause some issues with certain things.

**Comment by TaylorN15** [comment]
> @jmp7624 could you help to try this image? [studio 1.9.1.67](https://www.dropbox.com/scl/fi/qeoxh3hfuk36hkadw2ufq/Bambu_Studio_win_public-v01.09.01.67-20240516173854.exe?rlkey=zgmquspcoyrlyd30ean8s2kns&st=5do8vjad&dl=0)
> 
> if still crash, please help to send us the log.

I was having the same issue and this version resolved it for me also.

**Comment by ZeroTwo3** [comment]
> @jmp7624 could you help to try this image? [studio 1.9.1.67](https://www.dropbox.com/scl/fi/qeoxh3hfuk36hkadw2ufq/Bambu_Studio_win_public-v01.09.01.67-20240516173854.exe?rlkey=zgmquspcoyrlyd30ean8s2kns&st=5do8vjad&dl=0)
> 
> if still crash, please help to send us the log.

I was also having the same issue, and using this version has fixed it.

**Comment by zhimin-zeng-bambulab** [comment]
> That one does load. It did take a while to fully load into the slicer though. It was stuck on a white screen for a 20-22 seconds. Not a big deal but if I clicked on the program, windows would say it wasnt responding. After if fully loaded I haven't gotten any not responding errors so far. It also didn't install my filament profiles or custom printer profile I had for the P1S. I thought that was kind of odd because I though it was saved to my account since when I log into OrcaSlicer and make any changes to the profiles, Bambu Studio would pick up the changes immediately. I think I can import them but not sure if its normal or not since I completely deleted all the Bambu data when I was uninstalling the old version. Here are the log files in case you still want to look at them. [log.zip](https://github.com/bambulab/BambuStudio/files/15339910/log.zip)


@jmp7624  We have optimized the font loading speed. You can try this version to verify whether the problems you encountered are fixed.

https://www.dropbox.com/scl/fi/gwxq9cded6x58vl3k6b8s/Bambu_Studio_win_public-v01.09.01.67-20240529104732.exe?rlkey=jjgsaey1is43bhf3ru1n1nom4&st=8o0ypdd1&dl=0

**Comment by demonics420** [comment]
@zhimin-zeng-bambulab Wow that one does load a lot faster for me after the first initial launch!!! Keep up the great work over there really appreciate it!

**Comment by TaylorN15** [comment]
> @jmp7624 We have optimized the font loading speed. You can try this version to verify whether the problems you encountered are fixed.
> 
> https://www.dropbox.com/scl/fi/gwxq9cded6x58vl3k6b8s/Bambu_Studio_win_public-v01.09.01.67-20240529104732.exe?rlkey=jjgsaey1is43bhf3ru1n1nom4&st=8o0ypdd1&dl=0

This one shows as "Internal" version? Is that intentional? I had to set up my account/preferences again...

**Comment by lanewei120** [comment]
> > @jmp7624 We have optimized the font loading speed. You can try this version to verify whether the problems you encountered are fixed.
> > https://www.dropbox.com/scl/fi/gwxq9cded6x58vl3k6b8s/Bambu_Studio_win_public-v01.09.01.67-20240529104732.exe?rlkey=jjgsaey1is43bhf3ru1n1nom4&st=8o0ypdd1&dl=0
> 
> This one shows as "Internal" version? Is that intentional? I had to set up my account/preferences again...

internal version uses a seperate directory, we will release a formal version with this fix later

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v01.09.02.57, please have a try.
