### ISSUE TITLE
[Feature] Ability to paint an STL, just like Mosaic Canvas offers

### ISSUE THREAD

**Issue by Kraminator** [bambulab/BambuStudio#408]
Paint tools, so you can customize your 3D models for multi-color printing like Canvas by Mosaic offers.

**Comment by randyre** [comment]
Maybe expand on that request. There are Already paint tools included and they work better than canvas in my opinion.

**Comment by Kraminator** [comment]
My apologies, all this time I was not even aware of this feature because I didn't add the colors first. Its amazing!
