### ISSUE TITLE
Stacking objects is no longer possible. as the right click menu item "Assemble" is missing

### ISSUE THREAD

**Issue by christopher-lambe** [bambulab/BambuStudio#4084]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10

### Printer

P1S

### How to reproduce

https://wiki.bambulab.com/en/software/bambu-studio/stacking-objects

^^ Wiki method of stacking objects (changing the Z coordinate) does not work with version 1.9.1.66

https://wiki.bambulab.com/en/software/bambu-studio/release/release-note-1-9-1
 
^^ The release notes do not mention that the right click menu option is gone.

### Actual results

No right click menu item "Assemble" appears

![image](https://github.com/bambulab/BambuStudio/assets/68110886/58f6c9d0-eb7e-4dca-bfd1-891f41ad4e81)

### Expected results

Right click menu item "Assemble" should appear

### Project file & Debug log uploads

[Cylinder.zip](https://github.com/bambulab/BambuStudio/files/15330421/Cylinder.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by MadMax389** [comment]
The name was changed from Assemble to Merge. Function is the same.

**Comment by christopher-lambe** [comment]
Thanks guys. I will close the issue. MadMax389 is correct and it works for me now with "Merge"
