### ISSUE TITLE
Rotation bug when rotating a Z or Y mirrored part

### ISSUE THREAD

**Issue by PanamonCreel** [bambulab/BambuStudio#4088]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

WIN10

### Printer

P1S

### How to reproduce

1. Mirror a part on the plate on Z or Y axis
2. Rotate the Mirrored part on any axis, observe part flipping along the axis it was mirrored on initially
3. Rotate the Mirrored part again on any axis, observe part flipping again along the axis it was mirrored on initially 

### Actual results

Part will flip along the initial mirrored axis with each rotation increment no matter which rotation axis was used. So if mirrored along Z it will flip the part along the Z axis when rotated. If mirrored along Y the part will flip along Y when rotated.  When mirrored along X the part will not flip when rotated (as it should be)

### Expected results

a mirrored part should not flip around with each rotation operation.

### Project file & Debug log uploads

[RotationBugExample.zip](https://github.com/bambulab/BambuStudio/files/15336660/RotationBugExample.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Can you record a gif to describe your problem? Thank you

**Comment by PanamonCreel** [comment]
Certainly can do that
![RotationBug191166_2](https://github.com/bambulab/BambuStudio/assets/157646534/b4704eb7-9004-40de-a610-0402cb07a58c)

**Comment by PanamonCreel** [comment]
Rotation bug still exists with version 1.9.2.57

**Comment by Haidiye00** [comment]
Thank you for your GIF. We will investigate the cause as soon as possible

**Comment by jedthe3rd** [comment]
Just got my X1C today and I ran into this issue. I am on 1.9.3.50

**Comment by Haidiye00** [comment]
The problem has been identified and is currently being tested

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
