### ISSUE TITLE
Support Brims Not working

### ISSUE THREAD

**Issue by DarthVeronica** [bambulab/BambuStudio#4093]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

windows 11

### Printer

P1S

### How to reproduce

Added tree supports and i will usually expand the brim. It will not allow me to tree support brim width

### Actual results

the brim stay on the default size

### Expected results

the brim should be wider..

### Project file & Debug log uploads

this is happening on all files not just one. i have tried multiple files. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tangketan** [comment]
duplicate with #4066
