### ISSUE TITLE
Slicing Failing with Latest Studio using Bambu Filament; long_retractions_when_cut not a variable

### ISSUE THREAD

**Issue by RPINerd** [bambulab/BambuStudio#4098]
### Bambu Studio Version

1.9.0.60

### Where is the application from?

Bambu Lab github releases

### OS version

Linux Fedora Build

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1- Set object to use official Bambu Labs filament
2- Click `Slice plate`

### Actual results

Error message pops up:
![Screenshot_20240517_220839](https://github.com/bambulab/BambuStudio/assets/1577654/2451860a-4e9c-49d8-a83d-02f8107adab7)

However the custom G-code has never been changed and it doesn't even have 18 lines:
![Screenshot_20240517_220920](https://github.com/bambulab/BambuStudio/assets/1577654/a62389b0-3b76-43c3-a844-11dbfa1abff1)
And it ONLY happens with Bambu Filament, but again, this error line does not appear in the filament profiles

### Expected results

The file slices

### Project file & Debug log uploads

Error happens on any project, any object, any settings as long as an official Bambu Filament is chosen

There are no log files being generated since updating to 1.9

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
the latest is fine, could you download version 1.9.66? and if the latest version is still not work please upload your 3mf

**Comment by RPINerd** [comment]
Looks like that was the issue, odd that the repo didn't recognize a new version when installing from git.. anyways, thanks for your help!
