### ISSUE TITLE
Feature request: Right click option

### ISSUE THREAD

**Issue by ChrisG-hub** [bambulab/BambuStudio#41]
Feature request: Right click option in the sliced window to add a 'gcode' in the model, similar to the 'pause' option witch is available now.

**Comment by wuyifanfancy** [comment]
Hi @ChrisG-hub ,
Can you describes the specific senario in which you use this feature?

**Comment by ChrisG-hub** [comment]
Sure,Sure,
This is an option in Prusaslicer in sliced view where you can add this function similar to the option already in Bambu slicer 'add pause'.
This is useful for adding gcode that could change temp or other gcode functions.
Here is the screenshot in Prusaslicer where you can find that function.
![image](https://user-images.githubusercontent.com/74129531/180432838-5ca30e0c-3ae5-4225-9eee-091598af3cc7.png)

**Comment by wuyifanfancy** [comment]
Thanks for the response. We will consider this feature in future release.

**Comment by th3fallen** [comment]
+1 on this would be realllllly useful

**Comment by YifanWuBambu** [comment]
@ChrisG-hub @th3fallen  We will add this feature in recent release

**Comment by YifanWuBambu** [comment]
Please update to v1.3.0.12.
