### ISSUE TITLE
Chamber fan at 100% while leveling (since update)

### ISSUE THREAD

**Issue by Kimonokosch** [bambulab/BambuStudio#4105]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

P1S

### How to reproduce

Perform bed leveling or filament purge.

### Actual results

Chamber fan speed goes to 100% when bed leveling or filament purge starts. (also when standard leveling before print runs)

### Expected results

Chamber fan should stay off or low before printing.

### Project file & Debug log uploads

No file from today there.
Problem appeared directly after updating Bambu Studio.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ValeriaMomo** [comment]
i have the same issue

**Comment by DanTup** [comment]
There's an existing issue about this at https://github.com/bambulab/BambuStudio/issues/4054

I was prompted with a "configuration update" that has reverted that change and it no longer does this.

**Comment by pmoliterni** [comment]
@DanTup I was not prompted with any "configuration update". Is there a specific procedure to follow ? Thank you.

**Comment by DanTup** [comment]
Unfortunately I don't know... I was prompted with another app update (from .66 -> .67) and after installing it I started another print (but did not get the config update), and then when I opened another project, that's when it popped up saying there was a config update.

You could try clicking Help -> Check for Updates but I don't know if the configuration updates are checked there or only the app (nor do I know if the .67 update was required before the configuration update appeared).

**Comment by pmoliterni** [comment]
@DanTup I've tried. It says that I have the last version 1.9.66.

**Comment by SaltWei** [comment]
> @DanTup I've tried. It says that I have the last version 1.9.66.

Please pay attention to the right bottom corner of studio after it being launched.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/10ad0d8e-a0ee-4d19-9591-3990e5b7f683)

**Comment by pmoliterni** [comment]
It appeared, thank you.

**Comment by SaltWei** [comment]
> It appeared, thank you.

You are welcome :)
