### ISSUE TITLE
Nozzle change

### ISSUE THREAD

**Issue by BenBokeh** [bambulab/BambuStudio#4110]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 pro

### Additional system information

12900K 48GB ram RTX4080

### Printer

P1P

### How to reproduce

After the latest update (BambuStudio) i have to change the nozzle diameter manualy. In the previous version the software can with a popup that the nozzle has been changed, and you could confirm that, en the software took over the changed nozzle. After the update to 1.9.1.66 thats changed, and im not happy about that. 
Please change it back to what is was. Now I have to walk to the printer every time to change it manually

### Actual results

There is no solution for now.

### Expected results

I like to see that is changes back the way it was, so the software detect the change and apply this after i confirm it. 

### Project file & Debug log uploads

There is no file for this isseu. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by walterwongbbl** [comment]
Hi. @BenBokeh 
I apologize for the late reply. The reason we are doing this is that we hope to reduce the deterioration of the printing effect caused by the mismatch of the nozzle diameter.
