### ISSUE TITLE
Scale orientation locked to part orientation on import

### ISSUE THREAD

**Issue by mitaccio** [bambulab/BambuStudio#4118]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1C

### How to reproduce

1- Import part
2- Rotate part
3- Scale part 90 degrees so that the top becomes the side
4- Part scale will remain associated with orientation on import.

### Actual results

  In my case the Y axis now will change its height in the Z axis.

### Expected results

The scale orientation should remain locked with the orientation of the printer.  X should always change the X axis, Y should change the Y axis, etc..  In the photos I imported a file, chose to lay on face, then change the scale.  To showcase the issue I did 200%.
![Holo No Orientation Correction](https://github.com/bambulab/BambuStudio/assets/25374302/ccbfe519-7937-45cd-94a6-a4cd064aa152)
![Holo Reoriented for Scaling](https://github.com/bambulab/BambuStudio/assets/25374302/75058949-4147-4aff-8ccc-fc5fc0349413)
![Holo Scale 200% Z Axis](https://github.com/bambulab/BambuStudio/assets/25374302/4b486faf-6a5b-4c98-a42a-e21072fe14b2)

### Project file & Debug log uploads

[Scale issue.zip](https://github.com/bambulab/BambuStudio/files/15370784/Scale.issue.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/b8f5647d-fc33-4ea1-8834-bc64c47c764e)
![image](https://github.com/bambulab/BambuStudio/assets/132528822/b8d17ac4-4ae0-4afe-9063-4509f6bd0869)
Our scaling uses a local coordinate system, so this issue arises. We will increase the scaling of the global coordinate system in the future. You can currently export an stl first and then import it to solve this problem.
