### ISSUE TITLE
Negative Thickness Get App Crashing

### ISSUE THREAD

**Issue by hechay** [bambulab/BambuStudio#4122]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab P1S

### How to reproduce

1. Click on Object
2. Select the Object
3. Choose the Text Shape button
4. Choose the negative thickness
5. Get result by app crashing

### Actual results

App will be crashing when I choose the negative text thickness ( like -1, -2.. etc )

### Expected results

We should check the negative value.

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/15374830/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by hechay** [comment]
Hope this bug will be fixed in next version. Just an if-else when get input the text field. Thanks.

**Comment by zhimin-zeng-bambulab** [comment]
It will be fixed in next version

**Comment by zhimin-zeng-bambulab** [comment]
@hechay  It has been fixed in v01.09.02.57, please have a try
