### ISSUE TITLE
Only for test

### ISSUE THREAD

**Issue by hechuan949494** [bambulab/BambuStudio#4127]
### Bambu Studio Version

test

### Where is the application from?

Bambu Lab Official website

### OS version

test

### Additional system information

test

### Printer

test

### How to reproduce

test

### Actual results

test

### Expected results

test

### Project file & Debug log uploads

test

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by hechuan949494** [comment]
Please upload log through Handy APP,and give us your ticket number

**Comment by hechuan949494** [comment]
Please upload log through Handy APP,and give us your ticket number***Upload log files through Bambu Handy***
     Log files from the P1 series printer can be uploaded via Bambu Handy over the network, similar to the X1 series, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to Me → Support Tickets → Choose the ticket for log upload and proceed with the operation.

**Comment by hechuan949494** [comment]
**Please upload log through Handy APP,and give us your ticket number**
***Upload log files through Bambu Handy***
     Log files from the P1 series printer can be uploaded via Bambu Handy over the network, similar to the X1 series, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to Me → Support Tickets → Choose the ticket for log upload and proceed with the operation.

**Comment by hechuan949494** [comment]
**Please upload log through Handy APP,and give us your ticket number**
***
***Upload log files through Bambu Handy***
     Log files from the Bambu printer can be uploaded via Bambu Handy over the network, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to **Me** → **Support Tickets** → Choose the ticket for log upload and proceed with the operation.

**Comment by hechuan949494** [comment]
**Please upload log through Handy APP, and give us your ticket number**
***
***Upload log files through Bambu Handy***
     Log files from the Bambu printer can be uploaded via Bambu Handy over the network, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to **Me** → **Support Tickets** → Choose the ticket for log upload and proceed with the operation.
     ![app_support_ticket](https://wiki.bambulab.com/p1/troubleshooting/upload-log/app_support_ticket.png)

**Comment by gaolegao-lx** [comment]
**Please upload log through Handy APP, and give us your ticket number**
***
***Upload log files through Bambu Handy***
     Log files from the Bambu printer can be uploaded via Bambu Handy over the network, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to **Me** → **Support Tickets** → Choose the ticket for log upload and proceed with the operation.
     ![app_support_ticket](https://wiki.bambulab.com/p1/troubleshooting/upload-log/app_support_ticket.png)
