### ISSUE TITLE
Seam Paiting: View: Keep horizontal always selected

### ISSUE THREAD

**Issue by jrkalf** [bambulab/BambuStudio#4129]
### Bambu Studio Version

1.9.1.67

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS

### Additional system information

M1 architecture

### Printer

Not applicable?

### How to reproduce

When I'm in the Prepare screen and I select an object to put a seam paint on:
1. select model
2. select seam painting option
3. click "Vertical" (because I want to draw a vertical line)

See that it automagically selects "View: keep horizontal". 

### Actual results

Well I explained it above.
The **View: keep horizontal** tickbox does some odd behaviour to the view and orientation of the model on screen. Also the model rotation behaviour is severely different from normal model rotation in the normal prepare screen.

### Expected results

The expected result is that I don't want a feature to mess with my model orientation.

When I click the **vertical** tickbox in seam painting. I expect the **view: keep horizontal** tickbox to remain switched off and only be switched on when actively selected.

### Project file & Debug log uploads

Not applicable?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
ok

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
