### ISSUE TITLE
Feature request/bug: Stop fans when print is cancelled.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#413]
When a print is stopped manually (due to a failure etc.) any fans that were on appear to remain on as the machine end G-code that normally turns them off does not run.

Please can these fans also turn off when a print is stopped.

People have reported stopping a print remotely due to a failure, and then coming back to the printer over a day later (when if successful the print would have finished) to find the fans still running.

**Comment by SaltWei** [comment]
Has been handled in latest firmware
