### ISSUE TITLE
Bambu Studio Assembly View no longer allows individual object selection.

### ISSUE THREAD

**Issue by macrom** [bambulab/BambuStudio#4133]
### Bambu Studio Version

1.09.01.67

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS Sonoma 14.4.1

### Printer

X1c

### How to reproduce

1. Create an STEP with two objects, one stacked on the other. For example a 20mm cube and a 10mm cube stacked on top of the 20mm cube.
2. Load STEP into Bambu Studio (v1.09.01.67) as a new project. This appears to be a Bambu Studio version issue.
3. Select the STEP object then select Assembly View icon (top right beneath menu bar). Both cubes are hightlighted in yellow.

### Actual results

4. Try selecting the 20mm cube image with your mouse. The 10MM cube image is also automatically selected. Try selecting the 10mm cube image to see the same corresponding results with the 20mm cube image. 
5. Now try steps 3 and 4 with Bambu Studio v1.07.07.89 or earlier versions. You will be able to select the individual objects WITHOUT selecting from object list on the left side of the screen.

### Expected results

6. I am unable to select individual component images for coloring and must use the Objects list on the left side.

Note: My multi-color designs generated via FreeCad have numerous interlaced components (Part, Body, Object). In the earlier Bambu Studio version I was able to select and set color for each object image with the mouse. At times I have used up to 16 colors to produce some special works. It appears the current version (1.09.01.67) requires you to select from the object list on the side. How can I restore the previous selection capability in the current version? 

### Project file & Debug log uploads

[Test BS v1.09.01.67 Assembly Bug.zip](https://github.com/bambulab/BambuStudio/files/15395569/Test.BS.v1.09.01.67.Assembly.Bug.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MadMax389** [comment]
I don't recall ever being able to select one component of the assembly by clicking the object on the plate in previous versions. It always selects all components of the assembly. Is there an issue with selecting the component from the object screen? You can still assign colors to each individual object by typing the slot number of the desired color.

**Comment by Haidiye00** [comment]
Hello, can you record a GIF or a video? Thank you

**Comment by macrom** [comment]
Recorded Assembly changes in both versions (1.7.7.89 and 1.9.1.67). All earlier versions I have used are the same. It is only in this latest version 1.9.1.67 that the problem occurs.

[Test BS v1.09.01.67 Assembly Bug - 1.9.1.67.mov.zip](https://github.com/bambulab/BambuStudio/files/15398076/Test.BS.v1.09.01.67.Assembly.Bug.-.1.9.1.67.mov.zip)
[Test BS v1.09.01.67 Assembly Bug - 1.7.7.89.mov.zip](https://github.com/bambulab/BambuStudio/files/15398077/Test.BS.v1.09.01.67.Assembly.Bug.-.1.7.7.89.mov.zip)

**Comment by macrom** [comment]
This issue is NOT closed. Apparently I clicked on the incorrect comment button.

**Comment by MadMax389** [comment]
I see what you mean now. I rarely use the assembly view, but can see the advantage of using it by separating the parts with explosion and only using your mouse to assign colors. I confirmed the ability to select objects separately in v1.8.4.51 (Win 11) and not being able to select them separately in v 1.9.1.66 (Win 11).

**Comment by Haidiye00** [comment]
Hello, we have modified the selection strategy in the latest version. We will discuss internally whether to add an option.

**Comment by macrom** [comment]
Some input for your decisioning. When you have 10, 15, or more objects in a complex design, the ability to explode the design and individually tag an object for coloring is a huge timesaver. While the same task can be completed by using a text list off to the side of the screen, the immediacy of a tap object - tap color is much more friendly and intuitive than scrolling down a list to find an object and then selecting the color. Even a good object naming system takes more time/effort to scroll and select object than see object and tap, especially when setting the same color for several disparate objects.

For me it is worth keeping the older version with a quick selection ability than upgrading and spending extra time in the selection process. 

BTW, why have an explode design ability if not to select the individual objects?

**Comment by Haidiye00** [comment]
![img_v3_02bc_65272f2e-53fd-4cd2-bef5-2ab12fb8b11g](https://github.com/bambulab/BambuStudio/assets/132528822/43f2ba1c-d5d6-4bd4-8b74-076a800bb642)
Hello, after our internal discussion, we have added an operation prompt to resolve the issue

**Comment by macrom** [comment]
Thank you for the work around. However, for easy of use AND consistency, wouldn't it make more sense to have the object selection pressing the ALT key (1 time) and then selecting color vs. holding down the ALT key, then selecting individual parts and then color part (my latest object has 45 parts requiring individual selection with the ALT key). E.g. reverse the selection process. The change then becomes the NEW feature of holding down the ALT key for selection of object vs. part.

Good example is a multicolor beachball with 12 ordered slices where AMS 1 is blue, 2 is green, and 3 is white. Click on each blue slice with one hand and your other hand is on #1 key. Do that 4 times and then repeat with colors 2 and 3. With the ALT key selecting the part, you must either a) move the mouse to the ball slice and then to the color legend at the top of the screen each time while holding down the ALT key or move your hand to click on the #1 key and then move your hand back to the ALT key for part selection. If you think the beachball scenario I just described is not realistic, take a look at the opening frame in video 1.9.1.67 and find the second recently opened image (St. Pete City 1b1a-v5b Settings.3mf). 

Additionally, the original process worked very well and was conducive to those who needed the explosion / selection capability. If we are "adding capability" why would you not "add" the alt key for selecting all parts with one click (i.e. entire part) as a NEW functionality?

**Comment by Haidiye00** [comment]
I don't quite understand what you mean, could you please describe it again. You can use some screenshots or GIFs, etc. to illustrate

**Comment by macrom** [comment]
I’ve heard it said that a picture is worth a thousand words. In this case the picture is an exploded view of the second image in the Test BS v1.09.01.67 Assembly Bug - 1.9.1.67 video. You can easily see the numerous parts, each highlighted by the selection yellow. The questions to ask yourself are a) how would I make everything one color and how long would that take, and b) if everything will be different colors how would I do that and how long would it take? Imagine coloring the Neuschwanstein Castle and having to make sure you are holding down the Alt key for each part and run the risk of having the entire castle change to the last color selected. How much rework?

My request is simple - return the settings back to where in they were in March before someone decided to make changes to the Explosion Ratio selection. Simply select a part and color the part. No making sure you hold down an additional key each time a part is selected.

![Test BS v1 09 03 50 Assembly Bug - Part Selection](https://github.com/bambulab/BambuStudio/assets/8341154/aeeb4303-56f9-49d6-b4c1-2763f80df1ed)

**Comment by macrom** [comment]
Haidiye00 – Can you help me understand why the team decided an extra keystroke is needed each time when coloring several parts of one object vs. one extra keystroke when coloring the entire object? I ask because the software required fewer keystrokes through March, 2024. And then it all changed. Now you can spend 5 min getting all the parts colored correctly only to wipe out the entire effort by not holding down the ALT key. There is no undo when you color an object; for example, color 12 parts and then accidently color the entire object and you must start over. I would appreciate if you would help me understand.

**Comment by Haidiye00** [comment]
Sorry, after discussion, we will add a checkbox to switch to the previous state.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
