### ISSUE TITLE
1.9.1.67 - Force saving .gcode.3mf does NOT work always on MacOS Somona 14.x

### ISSUE THREAD

**Issue by bolsoncerrado** [bambulab/BambuStudio#4134]
### Bambu Studio Version

1.9.1.67

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS Sonoma 14.4.1

### Additional system information

M1Ultra

### Printer

X1C

### How to reproduce

1. Work on a 3mf project
2. Slice
3. Export gcode
4. Click on existing name on the file name list (no extension is assigned  yet, CORRECT!)

### Actual results

5. System reports the .3mf is gonna be overwritten!

### Expected results

5. Saves as .gcode.3mf instead!

### Project file & Debug log uploads

https://github.com/bambulab/BambuStudio/issues/3375

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by bolsoncerrado** [comment]
<img width="939" alt="Captura de pantalla 2024-05-22 a las 10 30 29" src="https://github.com/bambulab/BambuStudio/assets/10992914/d50c5f57-0eb3-448d-9bf0-a12da9a9f80b">

**Comment by bambu123** [comment]
It's not a very serious problem. Saving as .3mf doesn't affect reopening. It will be improved in subsequent versions.

**Comment by bolsoncerrado** [comment]
The "non serious problem" is the fact you overwrite the project file with just the gcode file, ruining the source of the whole project... :(

**Comment by bolsoncerrado** [comment]
You sneakedly patched this in 1.9.4 but it is still buggy at least in MacOS version.

When "exporting plate gcode", by default the system adds .gcode.3mf:

<img width="188" alt="Captura de pantalla 2024-08-30 a las 12 04 22" src="https://github.com/user-attachments/assets/9643bcbf-7ce7-4e3b-8788-d65d418a87a3">


If you click OK to save as is, it is added TWICE!

<img width="245" alt="Captura de pantalla 2024-08-30 a las 12 03 57" src="https://github.com/user-attachments/assets/fbecd595-7a33-44ef-a3ad-9090738a3279">

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~

**Comment by bolsoncerrado** [comment]
@Haidiye00 apparently you've now removed the "Overwrite warning" when clicking an existing file to save it with the same name. This was not the behaviour of past versions and can render to unwanted overwrites. Perhaps making it a user selectable setting?

**Comment by Haidiye00** [comment]
Sorry, if you want to save another copy, please modify the file name

**Comment by bolsoncerrado** [comment]
LOL but you can't fix a bug and generate another! What the....!?
