### ISSUE TITLE
Paint issue

### ISSUE THREAD

**Issue by seanmcguire413** [bambulab/BambuStudio#4138]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

Intel Core i5 7th gen

### Printer

X1C + 2 AMS

### How to reproduce

https://makerworld.com/en/models/221464
and slice using x1c I am using a profile with long retraction saved.
when on the preview page the ' in It's is all white but when it is sliced the ' is mostly brown from the base filament.  This wall is impossible to fix all painting options will not fix this.

### Actual results

the ' is brown and should be white. when on the preview tab and when printing.  it isn't white on the screenshot from makerworld so it might be a new bug.

### Expected results

the ' should not be brown

### Project file & Debug log uploads

[new+zelda+art+v24.zip](https://github.com/bambulab/BambuStudio/files/15406517/new%2Bzelda%2Bart%2Bv24.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
@seanmcguire413  Could you describe your problem in more detail with screenshots?

**Comment by seanmcguire413** [comment]
@zhimin-zeng-bambulab 
prepare tab the ' is all white
![image](https://github.com/bambulab/BambuStudio/assets/17932532/8637f281-7d5d-4a51-bb80-158c0ed856f8)
after slicing the ' is brown because of the default color of the design.
![image](https://github.com/bambulab/BambuStudio/assets/17932532/2641271a-370a-48d5-8ac6-f098a2481c48)

**Comment by seanmcguire413** [comment]
no matter what I do to pain the ' it will always be brown

**Comment by zhimin-zeng-bambulab** [comment]
@seanmcguire413  Thank you for your patient explanation!

**Comment by zhimin-zeng-bambulab** [comment]
@seanmcguire413  It has been fixed in v01.09.02.57, please have a try

**Comment by seanmcguire413** [comment]
Confirmed fixed! Thank you so much!
