### ISSUE TITLE
Merge Objects - slicing step

### ISSUE THREAD

**Issue by soldino71** [bambulab/BambuStudio#4143]
### Bambu Studio Version

1.9.1.76

### Where is the application from?

Bambu Lab Official website

### OS version

Sonoma 14.4.1

### Additional system information

MacBook Air M2, 8 GB

### Printer

Bambu A1

### How to reproduce

1 - import 2 STL files (logo and  a rectangle shape)
2 - Color each object using the paint tool.
3 - Ensure both objects are “Lay on Face,” 
4 - merge/assemble them.

### Actual results

Slicing the Plate raises the logo about 2-3 layers above the plate, hiding it, and showing only the card on the first layer (no details are available)

### Expected results

logo should be clearly visible in the first layer

Please consider this process worked fine till I updated the Bambu Studio, one week ago
[BAmbu issue.zip](https://github.com/bambulab/BambuStudio/files/15414000/BAmbu.issue.zip)
[log.zip](https://github.com/bambulab/BambuStudio/files/15414074/log.zip)

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/15414077/log.zip)
[BAmbu issue.zip](https://github.com/bambulab/BambuStudio/files/15414078/BAmbu.issue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/0c3ef44c-85cb-46f2-a2a6-9a633179eedb)
@soldino71  When two parts have different colors and overlap, we give priority to displaying the color later in the object list.

You can drag the blue part behind the white part in the object list

**Comment by soldino71** [comment]
Thank you very much: it works

Paolo
