### ISSUE TITLE
BambuStudio crashes when adding text with thickness under 1

### ISSUE THREAD

**Issue by NVNDO** [bambulab/BambuStudio#4151]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

P1S

### How to reproduce

1. Import an object
2. Place text on top of a surface
3. Reduce Thickness to 0. something

### Actual results

It freezes and then needs to be restarted. 

first time crashed (not dosumented)

2nd attempt. 
Thickness 0 = ...
![Screenshot (680)](https://github.com/bambulab/BambuStudio/assets/73851760/f4cdccc5-561b-476f-a295-17ed5d0116d7)
Adding a (.) = Crash
![Screenshot (681)](https://github.com/bambulab/BambuStudio/assets/73851760/7e7e6f2e-ea69-4464-8a5a-d9d7f8b67ba1)

3rd attempt:
Thickness 2.0 = OK
![Screenshot (683)](https://github.com/bambulab/BambuStudio/assets/73851760/8c00ed36-c266-4a68-b165-3d0c0f5056cc)
Thickness 1.0 = OK
![Screenshot (684)](https://github.com/bambulab/BambuStudio/assets/73851760/1a838a6d-1ceb-4d7e-b77b-35f40b005414)
Thickness 0. = Crash
![Screenshot (686)](https://github.com/bambulab/BambuStudio/assets/73851760/a48c4cba-2639-4384-8022-46792e60fba1)

### Expected results

Thickness should be reduced to given value (and not crash)

### Project file & Debug log uploads

[Freeze Log.zip](https://github.com/bambulab/BambuStudio/files/15443489/Freeze.Log.zip)
[Project File.zip](https://github.com/bambulab/BambuStudio/files/15443491/Project.File.zip)

### Checklist of files to include

- [x] Log file
- [x] Project file

**Comment by MackBambu** [comment]
Wrong input limit.
I will fix this issue, thanks for your report.
