### ISSUE TITLE
[Bug] [Issue] Support Blocker in Paint in Support not working

### ISSUE THREAD

**Issue by YyAoMmIi** [bambulab/BambuStudio#417]
When support painting, right click = support blocker, aka Support should not appear there. This is not functioning as intended

See the hole in the foot has paint in support blocker
![image](https://user-images.githubusercontent.com/58763731/194987681-a7b39a52-93d2-4f11-9a81-a5a1de8614a5.png)
Yet
Preview shows support there
![image](https://user-images.githubusercontent.com/58763731/194987773-44a73785-27ed-4e46-893e-ef10982d28a5.png)

Different model
https://www.printables.com/model/292343-silica-dry-box-for-bambulab-ams
![image](https://user-images.githubusercontent.com/58763731/194988763-8abb4599-a6a6-40bf-a396-a3c719a083ef.png)
See how only 1 section has support, rest has support blockers.
![image](https://user-images.githubusercontent.com/58763731/194988180-dee1e593-e153-4b50-8660-02e6f10a8bf7.png)
Using Normal(auto), clearly get support at where support blockers is.
![image](https://user-images.githubusercontent.com/58763731/194988305-799d6a6d-c9e8-4fe4-bb54-3a57f1a46d0a.png)
Same issue for Hybrid(auto)
![image](https://user-images.githubusercontent.com/58763731/194988827-3127bd9b-f96d-4f52-be8b-6b5ceaaee3c8.png)
Issue for Normal, no auto. Normal to my knowledge, should only apply support where it is painted
![image](https://user-images.githubusercontent.com/58763731/194988972-f8dbd737-50a8-4a46-8ff7-ccae89219249.png)
Tree Support kinda worked, but get something weird there.

**Comment by MusangKingBambulab** [comment]
Hi, @YyAoMmIi , hope you are still enjoying 3D printing. As for this issue, you mentioned last month, has been solved by adding a new config called "Support xy expansion" and it will come out with the next release. We open an extra setting for users to adjust the overhang area so that in this case, you can shrink the normal support span the way you like. For this dry box model, I only block the beneath overhang plane inside the box and set "Base pattern spacing" and "Support xy expansion" with 2mm and -1.5, respectively under Normal support mode. The result is quite close to what you want. (see below figs). We are always hearing your valuable suggestions. 
![drybox_solution](https://user-images.githubusercontent.com/116701250/204232592-634f141d-e70a-4d71-ba17-3d44f8067b00.png)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.

**Comment by ptsao88** [comment]
@YifanWuBambu @MusangKingBambulab I tried this today on 1.4.0.17 and it did not work.

Can you confirm this got included into v1.4 properly?

See my comment here: https://github.com/bambulab/BambuStudio/issues/437?fbclid=IwAR38W8ZkFsNLMgG-VhANLTSN5B8kJkkUD34kqpequlTZptL7QAgovL8RICs?fbclid=IwAR38W8ZkFsNLMgG-VhANLTSN5B8kJkkUD34kqpequlTZptL7QAgovL8RICs#issuecomment-1374921395

**Comment by MusangKingBambulab** [comment]
Hi, @ptsao88, we did integrate this feature into the current release, and please check below. Three parameters I changed are for your reference with this model.
![image](https://user-images.githubusercontent.com/116701250/211228480-0bfa13d0-f18e-4080-9795-84a329bc4601.png)

**Comment by ptsao88** [comment]
Hi @MusangKingBambulab - this still isn't working as I expect. See below comments.

If I import the model and there are NO support blockers painted, then I can see the Normal Support Expansion shrinking as expected.

![image](https://user-images.githubusercontent.com/62680638/211378627-d1167a0a-2337-4bce-8f28-56f63e15b680.png)
![image](https://user-images.githubusercontent.com/62680638/211378691-a7b9d291-41bb-494a-9db3-421123c1f379.png)
![image](https://user-images.githubusercontent.com/62680638/211378717-13caa849-24d2-44ca-8791-be5148f23aef.png)
![image](https://user-images.githubusercontent.com/62680638/211378750-88339228-9d15-4873-bf7f-1064440f51b7.png)
![image](https://user-images.githubusercontent.com/62680638/211378778-8e0e94b7-777d-4594-9fb7-fd50e3500987.png)

However, once I paint blockers/enablers, this no longer works as expected...also the support blockers are still not working properly and there are still supports being generated where the model is painted red. This is the same whether normal (auto) or normal (manual) is chosen, and whether or not the "Don't Support Bridges" is checked or not.

![image](https://user-images.githubusercontent.com/62680638/211379082-0714b248-023d-46dd-b050-ea0ee27a2ab8.png)
![image](https://user-images.githubusercontent.com/62680638/211379148-f37ff339-e167-4931-83d4-021c88547b5a.png)
![image](https://user-images.githubusercontent.com/62680638/211379181-c031d2a4-d1f7-4e5a-88d6-c26b9f9b86b6.png)
![image](https://user-images.githubusercontent.com/62680638/211379218-90f85ef2-b01b-44a6-83b5-d2f01f61745c.png)

**Comment by MusangKingBambulab** [comment]
@ptsao88 Got it. Don't worry, I will continue to follow this issue. Maybe the snug mode is alternative choice for us.

**Comment by ptsao88** [comment]
@MusangKingBambulab possibly...although I would like to see the support enforcer and blocker actually work properly (eg. a blocker will prevent supports from being generated on that surface).

If there was a way to delete supports after generation, that would also be useful.

It's also confusing that changing the "Base Pattern Spacing" causes the support generation to change so much.  I would expect that "Base Pattern Spacing" should be equivalent to "Support infill" in other slicers...which would just change the infill percent in the support area. However, you can see that by changing "Base Pattern Spacing", you sometimes end up with dramatically different supports generated (eg. supports in the small bridge areas even though "Don't support bridges" is enabled.

I would recommend looking at how Ideamaker from Raise3D generates and manipulates supports. From my experience it's been the easiest and most intuitive way to generate and modify supports.

![image](https://user-images.githubusercontent.com/62680638/211443365-74f4e30c-281e-4205-9cac-11cd3c942829.png)
![image](https://user-images.githubusercontent.com/62680638/211443412-2cf07b71-4808-4cb2-87ea-91fd25c974b6.png)
![image](https://user-images.githubusercontent.com/62680638/211443427-aff46cad-148e-4207-8403-e35f33fc2774.png)
![image](https://user-images.githubusercontent.com/62680638/211443458-c7c0042e-22cd-409e-ad2e-d53f46a4b20d.png)

**Comment by MusangKingBambulab** [comment]
@ptsao88 Thanks for your constructive suggestion. Editable support no matter what tree or normal mode will be a higher-level using experience and we will consider it, although there is still a long way to reach. Thanks again.
