### ISSUE TITLE
使用别人的3mf文件，如果打印机和我本身的一致，在不更改打印机类型的情况下，修改打印参数，切片结果中层高不会改变

### ISSUE THREAD

**Issue by zhibuchen** [bambulab/BambuStudio#4171]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

windows10

### Printer

P1S

### How to reproduce

1.打开3mf文件
2.更改为使用自己的打印预设参数，petg-eco 0.2
3.切片

### Actual results

切片结果里，预览层高和原文件设置的一致，依旧是0.16

### Expected results

本应该切片结果中，预览层高本应是0.2

### Project file & Debug log uploads

[log.zip](https://github.com/bambulab/BambuStudio/files/15481794/log.zip)
[Apple+Watch+Charging+Stand+Flat+Bottom+BBL+v3.zip](https://github.com/bambulab/BambuStudio/files/15481797/Apple%2BWatch%2BCharging%2BStand%2BFlat%2BBottom%2BBBL%2Bv3.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
看看是不是设置了对象参数

**Comment by zhibuchen** [comment]
> 看看是不是设置了对象参数

原文件已经上传了，并没有设置对象参数，只要把打印机类型从p1s更改为其他任意一个，层高参数才会正确生效

**Comment by QingZhangBambu** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/112676417/89985e5d-f050-4284-bc3f-4dec4f5c1a2b)
这里使用了可变层高调整了层高，请重置

**Comment by zhibuchen** [comment]
> ![image](https://private-user-images.githubusercontent.com/112676417/335504268-89985e5d-f050-4284-bc3f-4dec4f5c1a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA4NzEsIm5iZiI6MTcxNzE1MDU3MSwicGF0aCI6Ii8xMTI2NzY0MTcvMzM1NTA0MjY4LTg5OTg1ZTVkLWYwNTAtNDI4NC1iYzNmLTRkZWM0ZjVjMWEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxMDE2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzE0MjgxOTRiZmYwZmE0ZDZiODYzOTQ1NzZmM2ExNmQ5ODlhMTlhMWUyMGExMjgxYTA3MTM4Nzg3YmZlNzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pq8W9qCKT3HuWdsbbUMnrcSpdHeoEb1CzUSN3VcbdBE)这里使用了可变层高调整了层高，请重置

非常感谢，是我的问题，没有注意到可变层高

**Comment by QingZhangBambu** [comment]
@zhibuchen 我们会改善图标的显示，使得用户能清晰注意到可变层高被应用在模型上。您报的bug非常宝贵，感谢您的提单。
