### ISSUE TITLE
File Sliced changes 

### ISSUE THREAD

**Issue by csolomon79** [bambulab/BambuStudio#4181]
### Bambu Studio Version

184.51

### Where is the application from?

Bambu Lab Official website

### OS version

14.4.1 (23E224) MACOS

### Additional system information

M2 MacBook Air 16GB 512GB

### Printer

Bambu X1C

### How to reproduce

I have tried every painted option, even by part and object but even though the visual prepare looks perfect when it slices it fills in the QR code area and never produces the actual depth parts

### Actual results

black filed in 

### Expected results

QR code physical aspects 

### Project file & Debug log uploads

[Archive.zip](https://github.com/user-attachments/files/15506668/Archive.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/a8e09949-5926-4dfe-a289-a1681a97ad43)
@csolomon79  You need to fix this model first
