### ISSUE TITLE
Text tool types text backwards (not mirrored, but letters in backwards order

### ISSUE THREAD

**Issue by DanDanBogBog** [bambulab/BambuStudio#4198]
### Bambu Studio Version

1.9.1.67

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sonoma Version 14.5

### Additional system information

M1 Max chip

### Printer

P1S Selected

### How to reproduce

Unsure how to recreate, I suspect it's because the model had been mirrored. Object mirrored back along X-Axis did not fit it

### Actual results

<img width="893" alt="Screenshot 2024-06-03 at 12 08 51 AM" src="https://github.com/bambulab/BambuStudio/assets/57776275/1f6dc5d6-dc0c-41ff-9d89-4f560cab5f58">

Notice I had to type the text in reverse to get it to show up correctly

### Expected results

text works properly

### Project file & Debug log uploads

[Door Toppers - Text Bug.3mf.zip](https://github.com/user-attachments/files/15529488/Door.Toppers.-.Text.Bug.3mf.zip)

No log file required

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
Hello, the issue is currently under review

**Comment by Haidiye00** [comment]
I don't quite understand what you mean. Could you please describe your needs again.You can use some screenshots or GIFs, etc. to illustrate

**Comment by RiverCrossDiorama** [comment]
Hello,
The problem still randomly appears on the latest 2 versions, including the 1.9.4.60
The text I try to type appears backwards when hovering over the object.
![Backward text](https://github.com/user-attachments/assets/4c899ee3-bd08-46b0-9f88-4d51cc4e5cf9)

**Comment by Haidiye00** [comment]
Hello, the issue is currently under review

**Comment by Haidiye00** [comment]
ok

**Comment by tendeiro** [comment]
This issue is still happening in version 1.9.7.52, on Windows, when I have over >=12 plates.

**Comment by Haidiye00** [comment]
Sorry, the resolved code has not been merged yet. Please wait

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~

**Comment by HeadBoffin** [comment]
Seems this is still an issue in 2026 with version 2.5.0.66 - so many other random minor UI issues plus this - why produce world class hardware commanded by high school quality software - shame on you

**Comment by homergonerson** [comment]
Still happening, April 15, 2026.

**Comment by IpslWon** [comment]
Still an issue July 25th, 2026
v2.7.1.62
Windows OS

**Comment by Haidiye00** [comment]
https://github.com/bambulab/BambuStudio/releases/tag/v02.08.04.57
Hello, please update to the latest version
