### ISSUE TITLE
[BUG] Auto-orientation of flat disc not flat on build plate

### ISSUE THREAD

**Issue by Kraminator** [bambulab/BambuStudio#421]
I imported a flat disc (stand) object and pressed Auto-orient. It looks like it would be flat in the build plate, but when I slice it, it does not take part of the disc; somehow, half of it gets pushed as 2nd layer only, which will cause a failed print unless you use support. Clicking on manual flat turning and choosing the surface, the disc orients correctly and can be printed.

I currently have 2 models that do this, so it seems the auto-orientation is not doing a flat lay.

<img width="835" alt="Screen Shot 2022-10-11 at 3 33 06 PM" src="https://user-images.githubusercontent.com/115417168/195182507-39b34c9c-478f-4a2c-9e41-0a9b580dab17.png">
<img width="637" alt="Screen Shot 2022-10-11 at 3 32 14 PM" src="https://user-images.githubusercontent.com/115417168/195182510-cdc8605c-1ab5-4d13-8423-bb3b4324f0b6.png">
<img width="460" alt="Screen Shot 2022-10-11 at 3 31 55 PM" src="https://user-images.githubusercontent.com/115417168/195182513-2681030a-5fc5-4188-85bd-cd513c5585fd.png">
<img width="657" alt="Screen Shot 2022-10-11 at 3 30 48 PM" src="https://user-images.githubusercontent.com/115417168/195182518-89c662d2-218d-454d-9f18-e8e1653b6f66.png">

**Comment by tangketan** [comment]
Would you please share the model?

**Comment by Kraminator** [comment]
Sorry, I can't due to the license - but it is both of the round bases of this download:
https://www.cgtrader.com/3d-print-models/miniatures/figurines/jack-skellington-and-zero-the-nightmare-before-christmas

**Comment by ResiduaLiu** [comment]
There are some bugs in the auto orienation process. Some are already fixed. Please check it again in the next release.

**Comment by SaltWei** [comment]
Please check in V1.5.0 Public beta
