### ISSUE TITLE
亞太地區中文版無法使用布爾運算功能

### ISSUE THREAD

**Issue by 1121stevenwang** [bambulab/BambuStudio#4212]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Additional system information

<img width="422" alt="image" src="https://github.com/bambulab/BambuStudio/assets/171681925/3c1b9c1e-f89e-493f-a950-9157b0b92924">

### Printer

x1c   p1s   a1

### How to reproduce

亞太地區中文版無法使用不爾運算功能，下載軟體選亞太地區切英文後切中文，軟體變成中文後無法正常使用布爾運算，少了交集、差集

### Actual results

<img width="1280" alt="image" src="https://github.com/bambulab/BambuStudio/assets/171681925/8d31537d-6aca-440d-93c2-55fdb139f1ed">

### Expected results

能正常使用

### Project file & Debug log uploads

<img width="1280" alt="image" src="https://github.com/bambulab/BambuStudio/assets/171681925/1144affe-d434-418d-ad0a-ccc5e44296b7">

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SaltWei** [comment]
看起来问题是中文字符没显示出来。
![image](https://github.com/bambulab/BambuStudio/assets/110660407/24800914-7a51-4c9d-8114-ebdf567ad0f8)

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/13753740-ede2-4f23-993f-8c2a9e3b0c0d)
你好，想问一下，你的这个界面显示正常吗

**Comment by 1121stevenwang** [comment]
![SmartSelect_20240605_123610_Chrome](https://github.com/bambulab/BambuStudio/assets/171681925/c9ce7f4a-053c-46fe-a986-778e1bfc5201)
It displays fine and I can use the cutting function
![SmartSelect_20240605_123619_Chrome](https://github.com/bambulab/BambuStudio/assets/171681925/041bd3f4-70f3-4495-bb77-d94190f9e41a)
Boolean functions cannot

I have tried it, it is also in the Asia-Pacific region. If you switch to English, you can use Bollinger.

**Comment by 1121stevenwang** [comment]
![SmartSelect_20240605_124413_Chrome](https://github.com/bambulab/BambuStudio/assets/171681925/b4fe788c-fa01-4bd4-8118-73e3c5dec861)
Just switch to English and you can use it.
The unavailability I mentioned earlier is not only that the button is not displayed, but also that I cannot click the button to use the intersection and difference functions.

**Comment by Haidiye00** [comment]
https://www.dropbox.com/scl/fi/8my0l9zb7mzlabx9o3n38/Bambu_Studio_win_public-v01.09.02.54-20240605172311.exe?rlkey=bft2xdwg9lmos84a8vzuqdrcu&st=54gfzuis&dl=0
can you try this?thanks

**Comment by tojo17** [comment]
![image](https://github.com/user-attachments/assets/8b726dab-6d0c-435a-b993-d9be5d58d752)
这边也有完全一样的问题，切割功能正常

**Comment by fahaaaxiki** [comment]
Hi，we can't reproduce this issue locally，can you help to update to the latest version [1.9.7.52 Public Official](https://github.com/bambulab/BambuStudio/releases/tag/v01.09.07.52) and check if the problem solved？

**Comment by 1121stevenwang** [comment]
還是無法使用，我電腦是使用繁體中文的，我猜是抓不到字?

**Comment by fahaaaxiki** [comment]
> 還是無法使用，我電腦是使用繁體中文的，我猜是抓不到字?

我在我的电脑上也装了繁体字体，但是软件上有显示成功，很感谢您的帮忙，我再让我们的开发查看一下这个问题
![image](https://github.com/user-attachments/assets/3d4662e2-45d7-4c1b-a67a-4c181c36cfe5)

**Comment by tojo17** [comment]
我大概找到原因了，我的系统是日文的同样显示不出，但把非 unicode 程序的显示语言改成简体中文就可以显示了（中文新加坡一样可以，应该是编码问题），改回日文就无法显示。麻烦修复一下，感谢。

![image](https://github.com/user-attachments/assets/90a79228-25a0-4886-95b5-88c9799f1d8d)
![image](https://github.com/user-attachments/assets/88d02378-eb18-47a9-864d-a9abe9194f8c)

**Comment by 1121stevenwang** [comment]
如果可以，希望能有更詳細的中文說明或範例

**Comment by tojo17** [comment]
@1121stevenwang 
简单贴了中文在上面，我不确定中文版系统这里具体是什么，但意思应该差不多，更改系统地区为简体应该就可以了，但这只是 workaround，因为改了这个会引起其他的程式乱码，还是需要拓竹解决这个问题。

![image](https://github.com/user-attachments/assets/408bbd7b-be28-417a-be3e-c8bd581d3a2f)

**Comment by 1121stevenwang** [comment]
感謝 成功了

**Comment by tojo17** [comment]
请问为啥 close 了，这个问题还是没有解决啊

**Comment by Haidiye00** [comment]
Could you please test the 1.10beta version? Thank you~

**Comment by tojo17** [comment]
@Haidiye00 Hi, I tried the latest [1.10.0 Public Beta](https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.74), but no luck, under Japanese region set the text on buttons still could not be displayed.
![image](https://github.com/user-attachments/assets/64ee2500-f459-4d61-8b36-523fdcf31f9e)

**Comment by fahaaaxiki** [comment]
> @Haidiye00 Hi, I tried the latest [1.10.0 Public Beta](https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.74), but no luck, under Japanese region set the text on buttons still could not be displayed. ![image](https://private-user-images.githubusercontent.com/5460009/377136270-64ee2500-f459-4d61-8b36-523fdcf31f9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjc3MTksIm5iZiI6MTczMzM2NzQxOSwicGF0aCI6Ii81NDYwMDA5LzM3NzEzNjI3MC02NGVlMjUwMC1mNDU5LTRkNjEtOGIzNi01MjNmZGNmMzFmOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMDI1NjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTlmMDM0NWUzMzljNTg4YmJjY2E4YTExZTAyNmFkM2FhODYwMDFkZDdmYzk1MWM3MDM4ODdkMjE1ZmJhYWI0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FdSa8TnES2KctNPLqBQUTPFACcUBqun6fHF8Y0Ywlgg)

我们在1.10的正式版本[1.10.1 Public Release](https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50)上再次尝试修复了此问题，可以使用这个版本帮忙确认一下是否正常了吗

**Comment by tojo17** [comment]
@fahaaaxiki 
刚刚确认到这个版本里已经正常了，感谢跟进修复！

![image](https://github.com/user-attachments/assets/0de9ea93-33a5-4d8c-a5a7-8ec7abd9a052)

**Comment by Haidiye00** [comment]
Hello, thank you for your reply. This is good news~
