### ISSUE TITLE
Scaling a part in X scales it in Z after rotating (version 1.9)

### ISSUE THREAD

**Issue by emberprototypes** [bambulab/BambuStudio#4213]
### Bambu Studio Version

1.9

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

X1C

### How to reproduce

See my Twitter post here: https://x.com/emberprototypes/status/1797859883183640670

- Import a part into Bambu studio
- Rotate it by laying a different face flat
- Unclick "uniform scaling" and try to scale in X and Y
- Version 1.9 will scale incorrectly

![image](https://github.com/bambulab/BambuStudio/assets/126627300/7f156a32-1db5-4840-a177-f8a0f984a73e)
![image](https://github.com/bambulab/BambuStudio/assets/126627300/1010fbb5-c397-4260-aad4-e55e2d6b061b)

If you revert to 1.8.4 it scales as expected. I believe all previous versions worked this way.
This is important because I scale parts manually to accommodate for XY shrinkage for materials like ABS and PC.
See this issue for the need for shrinkage compensation: https://github.com/bambulab/BambuStudio/issues/2769

![image](https://github.com/bambulab/BambuStudio/assets/126627300/fde11ed3-7490-4a75-85c4-5c330e8e7a1e)

### Actual results

Part is scaled incorrectly.

### Expected results

Part should global scale in X and Y appropriately.

### Project file & Debug log uploads

N/A - should work with any STL.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/1e58795d-03cf-4a34-8b7d-26febd5fb249)
Hello, our scaling tool defaults to using the local coordinate system, which is the xyz direction of the local coordinate system. We will launch a scaling tool for the world coordinate system later, please stay tuned.

**Comment by emberprototypes** [comment]
This is not how it worked in previous versions though - if you try it on 1.8.4 and below, scaling values always applied to the world coordinate system, not the local coordinate system of the part.

**Comment by Haidiye00** [comment]
It used to be wrong

**Comment by emberprototypes** [comment]
I see. Was this in the release notes? This caused issues on my end because I was using the scaling function to compensate for shrinkage and because its behavior suddenly changed, I encountered lots of parts out of tolerance.

Please add a global scaling function in the future (or more importantly...implement the filament type shrinkage compensation).

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
