### ISSUE TITLE
Can't Dismiss / Ignore Bambu Handy Errors

### ISSUE THREAD

**Issue by ChrisPirillo** [bambulab/BambuStudio#423]
![Screenshot_20221011-154446_Bambu Handy](https://user-images.githubusercontent.com/59216/195212140-6dfc33a5-5362-4d52-bf94-e23889ecd516.jpg)

While you can ignore messages on the actual printer console, you can't ignore messages that come up as overlays atop the video feed.

**Comment by SaltWei** [comment]
Move this ticket to the right place.
