### ISSUE TITLE
Loading of model file failed (for step file, stl file loads ok)

### ISSUE THREAD

**Issue by gitterman** [bambulab/BambuStudio#4235]
### Bambu Studio Version

1.9.1.66

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 pro

### Additional system information

N.A.

### Printer

Bambulab P1S with AMS

### How to reproduce

Just try to import the attached .step file and see the error.
Loading the .step file other applications (e.g. freeCAD, online CAD viewers) does work without problems
[kabeltrommelKappe.zip](https://github.com/user-attachments/files/15740661/kabeltrommelKappe.zip)

### Actual results

Loading the attached .step file fails with "Loading of a model file failed." "The file does not contain any geometry data".
If I load the same model as .stl file it loads ok.

### Expected results

correctly import the .step file

### Project file & Debug log uploads

Cannot create project as importing the model file fails.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MackBambu** [comment]
It's a shell model, and it performs mesh which produces no-manifold edges. We need to consider whether we want to convert the shell.
![image](https://github.com/bambulab/BambuStudio/assets/169036319/8d2c0175-fffc-4dfc-88ca-3179c3287fe1)

![image](https://github.com/bambulab/BambuStudio/assets/169036319/c097b5de-0477-4128-96c1-8910b4f35d4d)
