### ISSUE TITLE
3D Connection Menu

### ISSUE THREAD

**Issue by Jgelwix** [bambulab/BambuStudio#4238]
### Bambu Studio Version

1.9.1.67

### Where is the application from?

Bambu Lab Official website

### OS version

14.5 (23F79)

### Printer

X1

### How to reproduce

Command+M for 3D Connection Settings - Never been able to use this as this shortcut is the Mac global shortcut for minimize. It would be great to see this fixed, or even better, the ability to customize/change keyboard shortcuts. Thanks in advance!

### Actual results

Window is minimized

### Expected results

3D Connection Menu

### Project file & Debug log uploads

N/A - This is a keyboard shortcut issue.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/0abceb44-3512-41ff-829c-dfcf86be251d)
Can you try this shortcut button? Thank you

**Comment by Jgelwix** [comment]
Unfortunately, this also minimizes the window.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
