### ISSUE TITLE
Adjusting position of connected parts doesn’t work.

### ISSUE THREAD

**Issue by SxeyChick** [bambulab/BambuStudio#4251]
### Bambu Studio Version

1.9.1

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

P1S

### How to reproduce

Import a part connected to a part on the plate. Then try to move it by inputting numbers. 

https://github.com/bambulab/BambuStudio/assets/115029650/64554e31-d7ac-4eb3-905a-086588d888e6

### Actual results

It’ll move around completely randomly. Same thing happens if you try to rotate it, it rotates at random intervals. 

### Expected results

It should move to the location you input. 

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
We are already upgrading the translation tool internally and in beta testing. Stay tuned

**Comment by SxeyChick** [comment]
> We are already upgrading the translation tool internally and in beta testing. Stay tuned

Cool. Though you guys just released an update and didn't fix this. Very disappointing. It's literally unusable. And that sounds like in exaggerating, but no. If you can't define the position of parts, the entire feature of combining two parts it's completely unusable.

**Comment by Haidiye00** [comment]
![img_v3_02bo_37f3545e-6711-4c4d-bf13-8a5c7975805g](https://github.com/bambulab/BambuStudio/assets/132528822/d9233def-e773-40b3-9c75-41e1962e638c)
Sorry, the external version is not yet available, but the internal version has indeed been developed and is being tested. Version 1.10 is definitely usable. Stay tuned.

**Comment by SxeyChick** [comment]
> ![img_v3_02bo_37f3545e-6711-4c4d-bf13-8a5c7975805g](https://github.com/bambulab/BambuStudio/assets/132528822/d9233def-e773-40b3-9c75-41e1962e638c)
> 
> Sorry, the external version is not yet available, but the internal version has indeed been developed and is being tested. Version 1.10 is definitely usable. Stay tuned.

I'll just continue to keep most my projects on hold...

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
