### ISSUE TITLE
Fuzzy skin prints same noise profile on consecutive layers

### ISSUE THREAD

**Issue by SeaRyanC** [bambulab/BambuStudio#4253]
### Bambu Studio Version

1.9.1.67

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

Intel i7-12700K

### Printer

Bambu X1 Carbon

### How to reproduce

* Load the attached STL file
* Choose Advanced -> Fuzzy Skin -> Contour Only
* Slice plate
* Pan the camera around a bit

### Actual results

Here's a view in the slicer showing the same noise pattern persisting over multiple layers
![image](https://github.com/bambulab/BambuStudio/assets/15153256/301731ba-c742-474e-9203-3bf14e4062e4)

This isn't a software artifact; the actual print also has this defect. This is a different slice that shows the same defect. Note that the repeated section occurs in a different section of the part.
![image](https://github.com/bambulab/BambuStudio/assets/15153256/50cce0cc-a855-4e98-9388-98b77d0ae2df)

### Expected results

There should not be observable repetition of the fuzzy noise pattern

### Project file & Debug log uploads

Attached
[fuzz.zip](https://github.com/user-attachments/files/15757322/fuzz.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by SeaRyanC** [comment]
This can be repro'd with a regular cube primitive. Scale it up vertically and apply fuzzy skin. It takes a few tries and can hard to spot, but there are definitely sometimes repeated layer sequences

Here you can see three identical layers near the top, separated by a bit. Lower, the same _sequence_ of repetitions occurs three times in the same cube

![image](https://github.com/bambulab/BambuStudio/assets/15153256/476165c3-89af-43c6-b940-2f69386305c3)

**Comment by QingZhangBambu** [comment]
@SeaRyanC Great, you do a good job!

**Comment by QingZhangBambu** [comment]
@SeaRyanC Hi, it had been merged, and will be release on the next version. nice work!

**Comment by ttt888zzz** [comment]
HI，[SeaRyanC](https://github.com/SeaRyanC)  Please try updating the latest version 1.9.4.
https://bambulab.com/en/download/studio

**Comment by HDHristov** [comment]
I'm having the same repeating patterns issue with Bambu Studio 1.10.2.64 when using arachne.
Works ok when using classic wall generator.
