### ISSUE TITLE
Changed code signature in macOS version 1.9.2?

### ISSUE THREAD

**Issue by suschizu** [bambulab/BambuStudio#4264]
### Bambu Studio Version

1.9.2

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 13.6

### Printer

Bambu Lab

### How to reproduce

codesign -dv --verbose=4 /Path/To/Application.app

### Actual results

FOUND 'Shanghai Lunkuo Technology Co., Ltd (T3UBR9Y3B2)'

### Expected results

EXPECTED 'Shenzhen Tuozhu Technology Co., Ltd (F4SKHPXDD9)' but 

### Project file & Debug log uploads

<img width="612" alt="Screenshot 2024-06-11 at 23 20 04" src="https://github.com/bambulab/BambuStudio/assets/16004333/2441cc6b-37b8-4a39-8da9-df0489b6e58a">

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@suschizu yes, we switched to the new signature "Shanghai Lunko..."
which is a subsidiary of “Shenzhen TuoZhu..."

**Comment by suschizu** [comment]
thanks for the fast clarification!

**Comment by JeremyLaurenson** [comment]
This should be reopened. My Mac will no longer run Bambu Studio properly as a result of this. There needs to be a help article on how to fix because most Mac users will do the right thing and get locked out of the app as a result of it being flagged as changed.

**Comment by lanewei120** [comment]
> This should be reopened. This change will cause an urgent issue for just _about all Mac users on a recent MacOS load_. If you do the default thing which is not to trust the change (Which most users should do) the app will no longer run properly on the Mac. My Mac will no longer run Bambu Studio properly as a result of this.
> 
> There needs to be a help article on how to fix because most Mac users will do the right thing and get locked out of the app as a result of it being flagged as changed.

could you give a video to show us the detailed issue?
we have not met any issues when switch to this signature
