### ISSUE TITLE
Support Interface not generating when using tree supports

### ISSUE THREAD

**Issue by TomDoesCars** [bambulab/BambuStudio#4318]
### Bambu Studio Version

1.9.2.57

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Ryzen 7 3700x, RTX4060Ti, 32gb DDR4

### Printer

P1S

### How to reproduce

Open a model, slice using tree supports.

### Actual results

The tree supports do not generate any kind of support interface, other than a line directly on top of the trees. No settings changes seem to impact this. Normal supports work as they have in all the previous releases I have used.
![image](https://github.com/bambulab/BambuStudio/assets/123526911/64336388-cdd0-48d5-8bf8-bf1a665455ac)
![image](https://github.com/bambulab/BambuStudio/assets/123526911/88c8f691-db05-49c8-9051-c3bb9592875a)
![image](https://github.com/bambulab/BambuStudio/assets/123526911/9a16b2b7-8179-49dd-b110-12e33653e7f9)

### Expected results

Support interface should generate.

### Project file & Debug log uploads

[Part.zip](https://github.com/user-attachments/files/15884911/Part.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by AJZein** [comment]
This happens with 'Tree Organic' support style only I've noticed but not sure if its intentional or not. The 'Default' option is defaulting to 'Tree Organic' in this case

**Comment by OwainJ** [comment]
I'm seeing the same thing, since the last update, where `Tree(auto)` with `Default` / `Tree Organic` style doesn't generate the interfaces properly:
![image](https://github.com/bambulab/BambuStudio/assets/17008780/4bc7e74d-704c-4f79-9cf5-1dd5c329fa62)
![image](https://github.com/bambulab/BambuStudio/assets/17008780/515ad2e8-fa11-410d-a5b4-6ef6c238d502)
![image](https://github.com/bambulab/BambuStudio/assets/17008780/0d9b04b4-a478-4031-87e8-5070974f6884)

**Comment by tangketan** [comment]
@OwainJ  set the "max bridge length" to 0 will fix your issue. We'll change the default behavior in the next version.

**Comment by ttt888zzz** [comment]
Please try updating the latest version 1.9.4.
https://bambulab.com/en/download/studio

**Comment by Zabinator** [comment]
Hi I just found this thread. I am on the latest version and this still seems to be an issue.

**Comment by Thilenios** [comment]
I can also confirm that I am not getting any support interfaces unless I manually paint support locations.

![Image](https://github.com/user-attachments/assets/33a63455-f066-4dc6-8963-2ba1fdd69758)

**Comment by Frixon21** [comment]
Yep, this is still happening on latest version, its honestly insane how long this has been going on with no fix
