### ISSUE TITLE
Filament Preset

### ISSUE THREAD

**Issue by marcoroessner** [bambulab/BambuStudio#4320]
### Bambu Studio Version

1.9.2.57

### Where is the application from?

Bambu Lab Official website

### OS version

Win10

### Additional system information

[system.txt](https://github.com/user-attachments/files/15888386/system.txt)

### Printer

A1, A1 Mini

### How to reproduce

open Bambu slicer
choose filament custom filament
choose edit filament
click +add preset
software crash.

### Actual results

crash

### Expected results

I have new printer A1 mini. Want to get the "old" presets working for my new printer.
Wanted to add presets,
It is way to complicated to copy filament presets from one to an other printer. Now I have to create new presets for both printers but I have already  well tuned presets for A1. Now I have to write down all the values to manualy create the "same" presets for the new A1 Mini Printer. 
I tohght bambu is for beginner. No! still tooo complicated.

### Project file & Debug log uploads

[BBM06FBremsAlle-K-215F12.zip](https://github.com/user-attachments/files/15888480/BBM06FBremsAlle-K-215F12.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by DanBao-Bambu** [comment]
Please provide me with the log at the time of your operation, for reference: https://https://wiki.bambulab.com/en/x1/troubleshooting/bambu -studio-log
Program crashes, please provide me with a dump file, reference: https://wiki.bambulab.com/en/bambu-studio/troubleshoot/crash-freeze-issue
If possible, please provide the preset for the Filament you are editing, which is located in the user folder at the same level as the log folder. You can search for the Filament name or enter user/userid/filler/base to find it

**Comment by DanBao-Bambu** [comment]
The reason has been found, and users should not be able to see project presets in custom Filament.

**Comment by ttt888zzz** [comment]
HI,[marcoroessner](https://github.com/marcoroessner):
Please try updating the latest version 1.9.4.
https://bambulab.com/en/download/studio.
