### ISSUE TITLE
1) Dowel holes goes missing after exporting to STL, 2) dowel holes do not line up after repair/fixing the model

### ISSUE THREAD

**Issue by jchau57** [bambulab/BambuStudio#4344]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Home

### Additional system information

![image 1](https://github.com/bambulab/BambuStudio/assets/36485092/7d93c980-3fd4-4f3f-ad41-b19cc9aba626)
![image 2](https://github.com/bambulab/BambuStudio/assets/36485092/1b8fb2c4-549a-457b-b19f-3f96aa180d4e)

### Printer

Bambu Labs P1S

### How to reproduce

1. Imported the model below
2. Created a cut with dowel connectors along vertical centerline of the model
3. Model is cut with the dowel holes but there are non-manifold edge errors (see image 1, 14 non-manifold edges errors in bottom right)
4. If I fix/repair the model, the errors go away but the model has shifted and the dowel holes do not line up anymore (see image 2)
5. If I export the model as a STL file the dowel holes are not shown at all (see image 3)
6. I am unable to do a boolean mesh and there is no option to assemble the holes to the model

Here is a link to the model I am working with:
https://www.printables.com/model/148007-star-trek-bird-of-prey/files

### Actual results

See above

### Expected results

I created the dowel holes along the vertical centerline of the model.  I expect the dowel holes to stay there when fixing the model.  I also expect the dowel holes to show up when I export the model to STL

### Project file & Debug log uploads

[bird_of_prey.zip](https://github.com/user-attachments/files/15930665/bird_of_prey.zip)
[debug_Fri_Jun_21_09_52_41_2584.log.zip](https://github.com/user-attachments/files/15930680/debug_Fri_Jun_21_09_52_41_2584.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by jchau57** [comment]
[bird_of_prey.zip](https://github.com/user-attachments/files/15941982/bird_of_prey.zip)

**Comment by jchau57** [comment]
Please see updated bird_of_prey.zip file.

**Comment by Haidiye00** [comment]
Hello, can you provide the original stl model？thanks

**Comment by jchau57** [comment]
[Uploading bird_of_prey original.zip…]()
Here's the original stl model.

**Comment by jchau57** [comment]
[Uploading bird_of_prey original.zip…]()
Hello, here is the original stl file of the model.

**Comment by jchau57** [comment]
[bird_of_prey original.zip](https://github.com/user-attachments/files/15965314/bird_of_prey.original.zip)

**Comment by jchau57** [comment]
Hello, here is the original stl model file.

**Comment by Haidiye00** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/132528822/04f4c84d-3eb2-4998-9bb0-d4bb20aa5a07)
Hello, I did not reproduce your question. Can you record the operation process of a GIF? thank you

**Comment by jchau57** [comment]
Ok, I reproduced my problem step by step.
1) I created a vertical cut with 2 dowel connectors.  Attached is the model file and a screenshot after the cut.  As you can see the front portion of the model has 12 non-manifold edges error.
![bird of prey 01](https://github.com/bambulab/BambuStudio/assets/36485092/5197880e-7135-4386-a9e2-36f03d5ca7ba)
[bird_of_prey 01.zip](https://github.com/user-attachments/files/16023366/bird_of_prey.01.zip)

**Comment by jchau57** [comment]
2. Here a screenshot and model file after I perform a repair of the non-manifold edges.  As you can see the dowel holes are not lined up anymore.
![bird of prey 01A](https://github.com/bambulab/BambuStudio/assets/36485092/feb9f0c1-5076-4c56-9aeb-6d6ff02bf9be)
[bird_of_prey 01A.zip](https://github.com/user-attachments/files/16023396/bird_of_prey.01A.zip)

**Comment by jchau57** [comment]
3) Since I could not get the dowel holes to line up, the other thing I tried was to export it to STL before repairing the non-manifold edges.  However, the result is the dowel holes are missing.  Here is the screenshot and STL file.
![bird of prey 02](https://github.com/bambulab/BambuStudio/assets/36485092/ad9f9e60-129c-45ba-a481-ad95b128c9a3)
[bird_of_prey 02.zip](https://github.com/user-attachments/files/16023421/bird_of_prey.02.zip)

**Comment by jchau57** [comment]
Is there any update to this reported problem?  I've provided as much detail as I can already.  It's over 1 month.

**Comment by Haidiye00** [comment]
![img_v3_02fl_ee8644d4-b0d3-47b2-8854-60da403a417g](https://github.com/user-attachments/assets/a884409d-e068-46b7-8cdd-c9efe4feefbd)
I noticed that after cutting, an object was suspended in the air. How was this done?

**Comment by jchau57** [comment]
I don't know.  That was the result after I cut the model.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
