### ISSUE TITLE
Windows APP and printer not in sync

### ISSUE THREAD

**Issue by somedesa** [bambulab/BambuStudio#4355]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

win 11

### Additional system information

Gamer system, 64 gigs of ram, 129k cpu, 3080-ti win 11

### Printer

p1p

### How to reproduce

no idea

### Actual results

Win Software shows lane three of P1P/AMS in use.  P1P is using lane 4.  Layer 1 was the correct lane (3), I left and came back and it switched to AMS lane 4.  I shut down the pc software and restarted and went to device tab and still shows lane 3 printing on the device (only one printer here) while on the actual device  (P1P) lane 4 is in use.

### Expected results

correct lane shown and in use? printer firmware updated yesterday

### Project file & Debug log uploads

![pulse-image-1719076102830](https://github.com/bambulab/BambuStudio/assets/54824211/24473a00-df8d-4a78-aca2-03863bc40ca0)
![pulse-image-1719076089035](https://github.com/bambulab/BambuStudio/assets/54824211/d134ec2c-9249-429b-adfb-c5ae4d6fde6f)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by somedesa** [comment]
as second image shows, pc app thinks lane 4 is empty while is in use on P1P

**Comment by somedesa** [comment]
[organizer slim.zip](https://github.com/user-attachments/files/15937564/organizer.slim.zip)
project file

**Comment by walterwongbbl** [comment]
Hi  @somedesa 
Can the Studio recover normally after the printer is restarted? If the display is still in error, can you provide the Studio's LOG file?
