### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by whiiiskyy** [bambulab/BambuStudio#436]
All the softwares (PC/mobile) should have dark mode option.

Many people use dark mode everywhere, BS with its ultra white colour, blinds you. This should be an easy to add feature.

**Comment by YifanWuBambu** [comment]
Dark mode is in our schedule and will be in recent release.

**Comment by whiiiskyy** [comment]
> Dark mode is in our schedule and will be in recent release.

Thank you 🙌
