### ISSUE TITLE
Bambu Studio crashing when clicking "Preview" tab after cloning object

### ISSUE THREAD

**Issue by rrowhe4d** [bambulab/BambuStudio#4365]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro - Version: 10.0.22631

### Additional system information

CPU: i9-13900K 
RAM: 64GB / 6400 MHz / DDR5
GPU: Nvidia RTX 4090

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1) Right click on initial object to be printed and click "clone"
2) Select number of clones you want, ex.: 59 (total = 60)
3) Click "Preview" tab
4) Wait for crash as it loads all of the different objects to preview

### Actual results

Bambu Studio just closes itself and needs to be restarted. Sometimes there is an error message along the lines of "access violation, restart the program." Single object preview works fine, only happens when I try to clone more than 2 objects at a single time. Am able to manually clone the same object multiple times, but this would mean having to click clone and enter value 59 different times.

### Expected results

After cloning the files and clicking preview, the program should work without crashing and be able to print all of the duplicate objects.

### Project file & Debug log uploads

[Bambu Crash.zip](https://github.com/user-attachments/files/15949973/Bambu.Crash.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by rrowhe4d** [comment]
User @QingZhangBambu linked to [this](https://github.com/bambulab/BambuStudio/issues/3318) solution which seems like a feasible workaround to the problem.

**Comment by evlas1013** [comment]
Having this issue any time the Preview tab is opened. Even if no model is loaded. Adjusting Affinity did nothing.

i7-7700, Windows10

v1.10.1.50
