### ISSUE TITLE
Support Generation XY Expansion Issue

### ISSUE THREAD

**Issue by ptsao88** [bambulab/BambuStudio#437]
With default settings, Bambu studio seems to expand supports in the XY direction (see first picture).  This results in undesirable supports generation in some locations (see second picture).  In this model specifically, supports that touch the build plate, and also some supports internally.

Furthermore, these additional supports that are generated from the expansion do not respect any previously defined support blocker areas.  Whether or not I paint the model with blockers does not prevent the extra supports from being created.

Setting the "Base Pattern Spacing" value to 0 eliminates this unwanted XY expansion...however, it also means that support infill becomes 100% (ie. a solid support block), which is also undesirable.  See third and fourth pictures.

**Ideally these changes would be made to Bambu Studio:**

**1. **Allow the user to specify XY expansion separate from "Base Pattern Spacing" (also known as support infill %)****
**2. **For any expanded supports generated, respect previously defined support blocker areas****

![image](https://user-images.githubusercontent.com/62680638/195995725-a391f2f8-f23b-4230-a768-62993f731271.png)
<img width="961" alt="image" src="https://user-images.githubusercontent.com/62680638/195996130-804811c9-f89c-4752-aa55-2ad819138942.png">
![image](https://user-images.githubusercontent.com/62680638/195995891-99e518c7-f4f4-4f5a-be9a-f80368d0ff50.png)
![image](https://user-images.githubusercontent.com/62680638/195995902-64758522-3519-499c-910e-ef0cdab0bd97.png)

**Comment by YifanWuBambu** [comment]
@ptsao88 
Thanks for your suggestion. We have added this in our plan list.

**Comment by ptsao88** [comment]
Great, thanks @YifanWuBambu !

**Comment by BATEMAN87** [comment]
Bambu, please fix

**Comment by YifanWuBambu** [comment]
This will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.

**Comment by ptsao88** [comment]
Thank you for implementing this!

www.philiptsao.com

**Comment by ptsao88** [comment]
@YifanWuBambu I had a chance to test this today...it doesn't look like "Normal support expansion" is working properly. Setting the number to a negative value does nothing and the supports look the same. It is not being shrunk but it IS being expanded properly.

![image](https://user-images.githubusercontent.com/62680638/211217714-7d0f34e9-1450-47e3-b69a-9bdf75fdb100.png)
![image](https://user-images.githubusercontent.com/62680638/211217726-db4e20d2-20ab-4c65-ba7b-5e83d0ea2e80.png)
![image](https://user-images.githubusercontent.com/62680638/211217736-50caac49-3613-451e-9759-dc0e5e1f393e.png)

**Comment by ptsao88** [comment]
I'm still finding that support generation and expansion in Bambu Studio is severely lacking, especially for engineering parts with overhangs. The current implementation might be good for simple parts, or non-functional prints but it has issues for our work that IdeaMaker solves easily. See below.

This is with standard support settings. It creates very thin tall support structures that are very likely to fail and mess up the remaining print.
![image](https://user-images.githubusercontent.com/62680638/225138031-ae5c3ce5-9044-42d2-83da-bb2d02e604d6.png)

Changing the XY expansion to shrink helps a little but is not really ideal because it shrinks away too much of the supports.
![image](https://user-images.githubusercontent.com/62680638/225138205-af1e919f-2a78-45cc-a20f-ec2061c5d34d.png)
![image](https://user-images.githubusercontent.com/62680638/225138290-3255cbdd-2cb6-4e65-9779-0d04df0b1d47.png)

Setting "Base Pattern Spacing" to 0 results in the ideal support placement. However, this also means that support infill is 100% which is very undesirable.
![image](https://user-images.githubusercontent.com/62680638/225138414-cbb7644b-ba8f-43eb-bc12-02643b21dcaf.png)
![image](https://user-images.githubusercontent.com/62680638/225138717-161c6983-162e-442a-8707-9e4ac384da54.png)

I would like to request the following:
- A way to generate supports with the same placement as when using "Base Pattern Spacing" = 0
- A way to modify the infill % when support placement is equivalent to "Base Pattern Spacing" = 0

**Comment by MusangKingBambulab** [comment]
Hi, @ptsao88. Our current version of BambuStudio provides snug mode under Normal Support which may eliminate your concerns.
![image](https://user-images.githubusercontent.com/116701250/225175876-137edf4e-8bcc-4385-9aff-0c108f7062b4.png)

**Comment by ptsao88** [comment]
Hi @MusangKingBambulab - PERFECT! This does exactly what I want, thank you so much!

**Comment by MusangKingBambulab** [comment]
> Hi @MusangKingBambulab - PERFECT! This does exactly what I want, thank you so much!

Good to hear that. Enjoy!
