### ISSUE TITLE
Importing into Bambu Studio and white dots show up on the model and print.  See it with Hueforge files

### ISSUE THREAD

**Issue by thestig24** [bambulab/BambuStudio#4447]
### Bambu Studio Version

1.9.3.50 

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 14.5 

### Additional system information

MacBook Pro. apple silicon
same issue happens on Windows11 based system with Bambu Studio 

### Printer

Bambu X1 Carbon

### How to reproduce

Go to https://makerworld.com/en/models/124375?from=search#profileId-134268 
or go to any of these cars https://makerworld.com/en/@HunterABCZ
Load directly into Bambu studio and printer 
slice and in areas where should be black for example has bunch of white dots that shouldn't be there

### Actual results

<img width="799" alt="Screenshot 2024-07-06 at 11 48 42 AM" src="https://github.com/bambulab/BambuStudio/assets/54722646/d9e879b7-a1b1-4353-8030-2b099adafc83">
<img width="389" alt="Screenshot 2024-07-06 at 11 51 19 AM" src="https://github.com/bambulab/BambuStudio/assets/54722646/5c18ca22-6829-40bd-97a5-eaa65d94be7c">
<img width="162" alt="Screenshot 2024-07-06 at 11 50 10 AM" src="https://github.com/bambulab/BambuStudio/assets/54722646/747a4a72-7ccd-4df2-b62b-0c34584e5f64">
<img width="662" alt="Screenshot 2024-07-06 at 11 49 48 AM" src="https://github.com/bambulab/BambuStudio/assets/54722646/0f5614a8-3ed0-40d3-9034-c2a883dfc5ce">

See these pictures of file before and after pull into Bambu Studio.  sometimes get a flag of unsupported areas. Also get warning of many triangles. Tried windows version of Bambu Studio with same results of white dots showing up 

### Expected results

Print should look like the example model 

### Project file & Debug log uploads

[Stormtrooper_Front_200x113(2)postbambu.3mf.zip](https://github.com/user-attachments/files/16117059/Stormtrooper_Front_200x113.2.postbambu.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/169250342/c474e3d2-4abe-4295-91c7-4fb30847b28d)
