### ISSUE TITLE
Flush into infill does not change the infill amount in Bambu Studio or the exported gcode

### ISSUE THREAD

**Issue by JesperKrogPoulsen** [bambulab/BambuStudio#4457]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

 I wanted to make a test. I started a new project with standard Bambu settings, 0.28mm layer height. Add a cube using the "Add primitive" function, used the color painting to make the top another color about 50 % up. Sliced the project and the total flushing is reported as 0.23g. Turned on the "Flush into infill" setting, resliced. still 0.23g flush. Set infill to 75%, same result. Added 30 more cubes by cloning the object. Same result. What am I missing? Shouldn't the flush amount go down when it is allowed to flush into infill between the 2 colors? 

### Actual results

Flush amount does not change. I exported two gcode files with and without the flush into infill setting. The only diffference is, that the setting is enabled. All printer movement gcode is the same.

Diff of the two gcode files:
```
@@ -45,7 +45,6 @@
 ; detect_narrow_internal_solid_infill = 1
 ; detect_overhang_wall = 1
 ; detect_thin_wall = 0
-; different_settings_to_system = flush_into_infill;;;;;
 ; draft_shield = disabled
 ; during_print_exhaust_fan_speed = 70,70,70,70
 ; elefant_foot_compensation = 0.15
@@ -92,7 +91,7 @@
 ; filename_format = {input_filename_base}_{filament_type[0]}_{print_time}.gcode
 ; filter_out_gap_fill = 0
 ; first_layer_print_sequence = 0
-; flush_into_infill = 1
+; flush_into_infill = 0
 ; flush_into_objects = 0
 ; flush_into_support = 1
 ; flush_multiplier = 1
```

### Expected results

I was expecting the amount of flushed filament to go down and the gcode commands for the printer to have some changes to reflect this.

### Project file & Debug log uploads

[FlushTest.zip](https://github.com/user-attachments/files/16133303/FlushTest.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by XunZhangBambu** [comment]
@JesperKrogPoulsen 
I guess you are using this model for testing. In this model,enabling "flush into infill" does not indeed affect the final amount of flush. Flush only occurred when changing filament, and it can be observed that no matter how many models there are, filament change only happened once, that is, from black to yellow."
![image](https://github.com/user-attachments/assets/bd533e5c-4318-4d47-adff-30d9d1523c2d)

Use models like this,and you will see the difference
![image](https://github.com/user-attachments/assets/2520f5bc-782d-459f-a6aa-7ad29fb14303)
![image](https://github.com/user-attachments/assets/d71b1611-a9f9-4f34-ae04-9d2c3350822a)
