### ISSUE TITLE
Wrong filament type loaded

### ISSUE THREAD

**Issue by geo-luki** [bambulab/BambuStudio#4458]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro

### Printer

P1S

### How to reproduce

I am preparing the files for printing, I have a PA6-GF filament location in AMS and it is also set for printing. But AMS does load PA6-GF correctly, but then in the view in AMS settings there is only **PA-GF**. So when I send the prepared file via LAN to the SD card in the printer and want to start printing via BambuHandy, I can't because I get an error about an incompatible filament.

### Actual results

![1](https://github.com/bambulab/BambuStudio/assets/154881238/273abe91-80e2-4cc2-bdeb-40645c4130ba)
![2](https://github.com/bambulab/BambuStudio/assets/154881238/daa2b93e-4fee-41d7-8ce8-9dfafc6e61ad)
![3](https://github.com/bambulab/BambuStudio/assets/154881238/2ec0fa6e-20b1-4240-80c3-c542f5cbf755)
![Screenshot_20240708-203843](https://github.com/bambulab/BambuStudio/assets/154881238/22e19683-3b86-4223-92f2-0e1caf049d01)
![Screenshot_20240708-203849](https://github.com/bambulab/BambuStudio/assets/154881238/40ceae10-c258-4208-9150-c0549f128f4b)

### Expected results

Of course I restarted the computer, the printer and even tried to put the spool in another slot. But nothing that would help.

### Project file & Debug log uploads

[Bez názvu.zip](https://github.com/user-attachments/files/16133388/Bez.nazvu.zip)
[log.zip](https://github.com/user-attachments/files/16133390/log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
see：https://github.com/bambulab/Bambu-Handy/issues/205

**Comment by LibaoBambu** [comment]
@geo-luki Please reinstall the App. If the issue persists, let me know.
