### ISSUE TITLE
Nozzle Temperature Problem

### ISSUE THREAD

**Issue by miguel27410** [bambulab/BambuStudio#4467]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

MACOS

### Additional system information

Chip: Apple M1 Pro
Memory: 16 Gb
MacOS Sonoma version 14.5

### Printer

Bambu Lab X1C

### How to reproduce

Send to print

### Actual results

the printer not print anything
![Cutter](https://github.com/bambulab/BambuStudio/assets/165703906/b2f086e1-759c-435c-a907-ee0f7289b43d)

### Expected results

It suppose to print 

### Project file & Debug log uploads

[bambulab-top-glass-riser-4-cob-led-remix-with-led-shield-model_files.zip](https://github.com/user-attachments/files/16159456/bambulab-top-glass-riser-4-cob-led-remix-with-led-shield-model_files.zip)
[debug_Mon_Jul_08_12_29_27_51570.log.zip](https://github.com/user-attachments/files/16159517/debug_Mon_Jul_08_12_29_27_51570.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by LibaoBambu** [comment]
@miguel27410 @ttt888zzz Please refer to the wiki for problem-solving: [https://bambulab.com/en-eu/my/support/tickets](https://wiki.bambulab.com/en/x1/troubleshooting/cutter-stuck). If you need more professional guidance, please create a ticket [https://bambulab.com/en-eu/my/support/tickets](https://bambulab.com/en-eu/my/support/tickets)
