### ISSUE TITLE
Height range modifier disabling multi color model - Regression since 1.9.2 versions

### ISSUE THREAD

**Issue by edog1973** [bambulab/BambuStudio#4469]
### Bambu Studio Version

1.9.2.57 and 1.9.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 22.04

### Printer

Bambulab X1 Carbon

### How to reproduce

Please see attached 3MF file.  This project has two STLs combined to make a multicolor object.  The base object is white and the text on the bottom is black.  It also has a height range modifier used to color the bottom 1mm of the base silver.  Since version 1.9.2 the text on the bottom layer is missing when sliced.

### Actual results

These screen captures were taken using version 1.9.2.57.  The issue is seen in 1.9.3.50 also

Looking at the bottom of the model in Prepair the text is shown.
![image](https://github.com/bambulab/BambuStudio/assets/5891504/d7ec5525-a664-4e58-ac49-a7c7db03d1e5)

After slicing, in Preview, the text is missing.  There are three circle artifacts highlighted by the green arrows.  The Filament list also only shows two colors, silver and white, highlighted by the green box.
![image](https://github.com/bambulab/BambuStudio/assets/5891504/d266a414-e8e4-432b-af33-fb94d9be375c)

### Expected results

These screen captures were taken using version 1.9.1.58

Preview mode shows the text properly rendered. Filament list shows all three colors as expected.  
![image](https://github.com/bambulab/BambuStudio/assets/5891504/a3d0db7a-b561-40e7-9732-e9df0576c10d)

### Project file & Debug log uploads

[Bambu Bug Report.zip](https://github.com/user-attachments/files/16164819/Bambu.Bug.Report.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/user-attachments/assets/4df90a9d-0228-4339-bcda-cca4ee86a050)

@edog1973  The previous behavior also had problems in some scenes, and the priority of the height_range filament should be higher.
In this question, you can avoid this problem by painting color as shown in FIG.
