### ISSUE TITLE
STL no longer imported as assembly

### ISSUE THREAD

**Issue by cutmoney** [bambulab/BambuStudio#4472]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

macOS 14.5

### Additional system information

Macbook Pro M2 Max

### Printer

P1P and A1

### How to reproduce

1. Import
2. Choose STL
3. Used to bring up a message asking if you wanted to import as a group/assembly, now that no longer exists. You have to manually assemble after import.

### Actual results

Imports objects as multiple bodies.

### Expected results

Option to import as assembly as was previously the case.

### Project file & Debug log uploads

Applies to all projects and STL files.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye01** [comment]
Can you provide the STL file? Thank you

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/fbb0a419-a575-4b3a-bcae-6b42298bbf94)
I tested it and there were no issues

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~

**Comment by Haidiye01** [comment]
ok,i have received your letter ,thank you!
