### ISSUE TITLE
Android Bambu Handy Video Not Working (Celluar Data/ 4G)

### ISSUE THREAD

**Issue by sickerin** [bambulab/BambuStudio#448]
When using **celluar data/ 4G** video playback doesn't seem to be working for bambu handy app. It keeps loading forever. I can control ams/ temperature etc. Video works when using wifi.
Device: Android 11 (Nothing Phone).
App Version: 1.0.5

Can devs or someone else do a quick test?

**Comment by Allram** [comment]
Works fine for me with Nothing phone both on Wifi and cellular/4G/5G
Android 12.
Nothing OS 1.1.4
Bambu Handy 1.0.5

**Comment by pepsiliu** [comment]
> When using **celluar data/ 4G** video playback doesn't seem to be working for bambu handy app. It keeps loading forever. I can control ams/ temperature etc. Video works when using wifi. Device: Android 11 (Nothing Phone). App Version: 1.0.5
>
It's a knowed bug on the Printer. Reboot the printer for a chance to recover it, if your Wi-Fi works fine.

**Comment by SaltWei** [comment]
Since this is not slicer issue. Close
https://github.com/bambulab/Bambu-Handy is used to report app issues.
