### ISSUE TITLE
Reduce filament waste by flushing to inner parts of model

### ISSUE THREAD

**Issue by AlexFromNL** [bambulab/BambuStudio#4513]
When using the AMS there is quite a lot of filament waste for multi color (or material) prints. By allowing the slicer to 'flush' the filament on parts where bleeding does not matter, the waste could be drastically reduced. 

For instance have a setting to use the flush filament for the infill parts after a 2 mm outer layer. 

Or allow selection of objects which do not care about bleed. Like some inner parts of a multi part model.

**Comment by adamfilip** [comment]
it can already flush into Infill, how is this different?

**Comment by AlexFromNL** [comment]
Sorry. I did not know / see that. I did see however a lot of video's with remarks about a relative lot of waste. Will close this.
