### ISSUE TITLE
Why can't you change the Price tag for the System Profile to make it the default for that filament type

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#452]
![Screen Shot 2022-10-18 at 10 40 18 AM](https://user-images.githubusercontent.com/48887257/196486954-6b660d2a-331c-419d-8ddf-b9f4855beaad.png)

**Comment by YifanWuBambu** [comment]
The system profiles are designed as read-only, strictly provided by Bambu Lab officially.
If you want to change it, it is suggested to rename it and save as a user preset.

**Comment by RobinWhitfield** [comment]
@YifanWuBambu, should this not be closed as #wontfix if the answer is that it's not going to change?

Might I suggest as a compromise for the built in filament profiles that they have zero cost associated with them? At least then it's not giving a somewhat incorrect value when slicing, rather no value at all.

**Comment by Benderrodrigu3z** [comment]
That’s probably a better solution. A 0 cost I mean

Sincerely,
Shane F

**Comment by YifanWuBambu** [comment]
This is included in v1.4.

**Comment by invisibleninja06** [comment]
What exactly was included in 1.4? 

I still see costs for say the Bambu filaments which is not accurate and only way around this currently is to create custom user profiles of each Bambu filament, seem incredibly tedious. 

Would be really nice to have a user override for the Bambu filaments.

Pretty much every other parameter I can get behind having read only but the price varies by country so unless its made to update to match the cost by country (which would be neat but probably a major pain) an override for price would suffice.

**Comment by Benderrodrigu3z** [comment]
You can manually edit it if you go find the plist file on Mac at least, but then the next update overwrites itSincerely,Shane FSent from my iPhone13On Jul 6, 2023, at 12:58 AM, Aaron Tringle ***@***.***> wrote:﻿
What exactly was included in 1.4?
I still see costs for say the Bambu filaments which is not accurate and only way around this currently is to create custom user profiles of each Bambu filament, seem incredibly tedious.
Would be really nice to have a user override for the Bambu filaments.
Pretty much every other parameter I can get behind having read only but the price varies by country so unless its made to update to match the cost by country (which would be neat but probably a major pain) an override for price would suffice.

**Comment by programbo** [comment]
Auto-updating prices for filament price changes in the user's region would be fantastic, but allowing Bambu filaments to have user editable prices would be a reasonable alternative.

**Comment by Benderrodrigu3z** [comment]
Just create your own profile and change the numberSincerely,Shane FSent from my iPhone13On Jan 24, 2024, at 2:52 AM, Daniel Römer ***@***.***> wrote:﻿
The price should not be bound to the filament default profile. Even not on Bambu filament. Since it varies from where you buy it.
Secondly it does not take into consideration of where you live. So for me with SEK it shows a cost of 20!?  I guess thats Eur or USD. I would though be glad to buy filament to that price :)
So i would recomend to remove the price from the locked default profile and make that user editable. Would be nice instead of having to maintain or copy/build your own.
