### ISSUE TITLE
[Issue] Textured PEI Plate Bed Type is using the values of High Temp Plate instead

### ISSUE THREAD

**Issue by YyAoMmIi** [bambulab/BambuStudio#454]
![image](https://user-images.githubusercontent.com/58763731/196506422-a489271e-9702-49fa-86ad-95f3295c07ac.png)
I had set the bed type to textured PEI, and added my own values to textured PEI [60 1st layer, 50 other layers]

However, when printing, the bed goes to 45C

this lead me to believe that while textured PEI is selected, it uses the values of high temp plate instead.

**Comment by lanewei120** [comment]
Could you try the newest version?

we fixed a issue about it

**Comment by YyAoMmIi** [comment]
I just started a print where textured was 65, high temp is 55. plate
selected is textured. resulting 1st layer bed temp is 55.

**Comment by YyAoMmIi** [comment]
Hum, it is working now, so i guess issue is fixed.

**Comment by lanewei120** [comment]
thanks, So I close this issue~
