### ISSUE TITLE
Projects become locked to MakerWorld projects and cannot be unlinked

### ISSUE THREAD

**Issue by t0nyz0** [bambulab/BambuStudio#4546]
I printed something from MakerWorld and when it finished I deleted the STL out of BambuStudio. 
I then imported some other STLs in and started another project only to realize hours later that the Project tab is still tied to a the Makerworld print. **If the project tab is locked to a MakersWorld project then BambuStudio should not allow you to import other STLs**. This is a terrible bug, I wasted at least 2 hours just on this one instance. Since you cant clear what project its locked to you have to literally start all over again with a fresh BambuStudio instance. 

AT MINIMUM: When using "Export to Generic 3MF" it should strip all project information. I have 10+ plate projects that I worked on that are FOREVER tied to MakerWorld projects that should not be and I never linked to, but I will never be able to "unlink" them because of the limitations you have built into this software. 

IN SUMMARY: We simply need a way to **UNLINK** the projects in the project tab. As simple as that. 
This could be a "Clear project information" button. 
This could be a  "Remove MakerWorld project link" button.
**Even if you delete all associated Makerworld project STL files, the project tab is still linked! Thats a bug.** 

![Screenshot 2024-07-26 at 3 43 37 PM](https://github.com/user-attachments/assets/bd773b08-e94d-4f9a-af5d-d6acde62acfc)
![Screenshot 2024-07-26 at 3 44 12 PM](https://github.com/user-attachments/assets/876aad86-86cc-41c2-9dce-88881d93389c)

@bambu123 I dont think you guys are understanding the issue. We dont need to edit a lot of stuff. We need to remove the link between online MakerWord projects and the BambuStudio project that we are currently working on. Its often not correct and tied to old projects that are no longer pulled up.

_Originally posted by @t0nyz0 in https://github.com/bambulab/BambuStudio/issues/2111#issuecomment-2253473234_

**Comment by t0nyz0** [comment]
After a few hours of testing I figured out that you can open a new Project and import in 3MF files that are associated with MakerWorld projects and it will remove the link. This is a hack to work around the problem. It still requires you to fix the plate layouts but it does mean I can get around it. I'll mark this as closed but if you guys would add a "UNLINK" or "CLEAR"  in the Project tab that would save me a lot of trouble.

**Comment by KriyenKP** [comment]
Don't think you should have closed this. Even creating a new project doesn't let me unlink the embedded one.
