### ISSUE TITLE
Filament change in slicer, no opportunity to select slots in AMS

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#455]
When you do a filament-change in the vertical slider of the slicer, you can only select 1 slot in the AMS before print. Not a big problem but inconsistent with other multicolor prints. version 1.02.00.09

**Comment by YifanWuBambu** [comment]
Hi @coat64 ,
This is the filament index in current project, not the AMS slot.
![image](https://user-images.githubusercontent.com/110661856/196625560-3e81fc40-807e-466c-b1cd-66c45badbd79.png)

It will finally be mapped to AMS slot when sending a print job.
![image](https://user-images.githubusercontent.com/110661856/196625734-816f18c8-b0c3-4020-bd37-cb09673dd64e.png)

**Comment by coat64** [comment]
You are right, it works. No idea what I was doing when posting. I had multiple filaments loaded in the slicer and in the AMS. Maybe the not enough corresponding types.

**Comment by YifanWuBambu** [comment]
@coat64 
Okay. I will close the ticket first.
If you meet other problem, please create a new one ：）
