### ISSUE TITLE
Can't enter value in manual k-value calibration

### ISSUE THREAD

**Issue by Zydnar** [bambulab/BambuStudio#4555]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab A1

### How to reproduce

1. Go to Calibration tab
2. Perform Flow Dynamics manual test
3. Try to enter k value either using `.` (doesn't work but it's in screenshots at wiki) as at official Wiki or `,` (this works)
4. Click Finish button

### Actual results

![2024-07-30 15_26_54-Window](https://github.com/user-attachments/assets/5d3123ab-08bf-4b69-a7ba-ed2948405825)
![2024-07-30 15_27_21-Window](https://github.com/user-attachments/assets/64b0c382-74e6-4ae8-a225-c7254a85ebf9)

### Expected results

Value in format from screenshot at official Wiki should work - see: https://wiki.bambulab.com/software/bambu-studio/calibration/pa_save_auto_results.jpg for reference.

### Project file & Debug log uploads

[test.zip](https://github.com/user-attachments/files/16428855/test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by zhimin-zeng-bambulab** [comment]
What is the language of your operating system?
And is the language of your Studio is set to English?

**Comment by Zydnar** [comment]
@zhimin-zeng-bambulab You're suggesting number separator in settings there affects slicer? It could be - I changed default setting there to work with Fullcontrol XYZ macros https://fullcontrolgcode.com/download I'll confirm it and post an update...
