### ISSUE TITLE
Filament change does not affect subsequent slices.

### ISSUE THREAD

**Issue by Enteleform** [bambulab/BambuStudio#4562]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab A1

### How to reproduce

- Slice Plate
- Change Filament Type
- Slice Plate

### Actual results

The post-filament-change slice restarts, immediately jumping to 80% progress.  The new parameters expected to be applied from the filament change are not present in the resulting slice.

In order to get the new filament settings to apply, a new preset must be temporarily selected.  After switching back to the desired preset, the new filament settings will then be applied to the next slice.

### Expected results

The The post-filament-change slice will correctly apply the new filament settings, without requiring that the preset be changed.

### Project file & Debug log uploads

[Logs.zip](https://github.com/user-attachments/files/16441777/Logs.zip)
[Project.zip](https://github.com/user-attachments/files/16441778/Project.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
@Enteleform could you explain how to change the filament type and provide the screenshot? i need to reproduce it.
are you just change the filament on ams list? or you just 
![image](https://github.com/user-attachments/assets/5ceabe0b-f5f2-4bab-b181-a1b9404a81de)

**Comment by Enteleform** [comment]
> @Enteleform could you explain how to change the filament type and provide the screenshot? i need to reproduce it. are you just change the filament on ams list? or you just change the filament on system list?

System presets only, as shown in your second screenshot.  I do not have AMS presets, as the printer I'm using is at my makerspace.  I prepare the sliced file on my home machine using system presets, and then take it to the makerspace on an SD card.

**Comment by QingZhangBambu** [comment]
@Enteleform sorry for delay.  which parameters do not work, could you upload some screen shot.

**Comment by Enteleform** [comment]
I can't troubleshoot this at the moment, but I'll reopen it if I run into the issue again.
