### ISSUE TITLE
Bambu Studio and A1 won't print two-color thin lettering

### ISSUE THREAD

**Issue by gerfnitauthor** [bambulab/BambuStudio#4570]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 13.6.7

### Additional system information

Apple M2 Ultra, 64G RAM, Apple Studio Display

### Printer

A1

### How to reproduce

1. Load model 2. Use Bambu Labs Color Painting to make the numbers black on a white base. 3. Print model shows only white filament required. 

### Actual results

A1 only prints white. Black letters are ignored.

### Expected results

White base should print, then a filament change to black via AMS, then black numbers should print.

### Project file & Debug log uploads

[Archive.zip](https://github.com/user-attachments/files/16464218/Archive.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
@gerfnitauthor sorry, the letters is too small to print.
