### ISSUE TITLE
Items "joined" in Blender cannot received supports...

### ISSUE THREAD

**Issue by OriginalSyn5150** [bambulab/BambuStudio#4574]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Mac Sonoma 14.5

### Additional system information

M3 Ultra chip

### Printer

Bambu A1

### How to reproduce

When in Blender using the "join" or "command + J" to form a single entity for multiple small parts then exporting to an STL, for some reason 
<img width="1293" alt="Screenshot 2024-08-02 at 12 25 23 PM" src="https://github.com/user-attachments/assets/75f96049-59f6-4996-b1b3-eb7f57d0eda3">

### Actual results

Some items may require supports, when you use the join in Blender the slicer does not render everything.  You can see the difference in these screenshots

<img width="652" alt="Screenshot 2024-08-02 at 12 28 06 PM" src="https://github.com/user-attachments/assets/1d10d63b-6352-476a-9af7-06dbe593332a">
<img width="753" alt="Screenshot 2024-08-02 at 12 28 26 PM" src="https://github.com/user-attachments/assets/c1fa3c64-8d16-4283-9b32-7fd3c53f1a80">

### Expected results

I am not an expert in 3D software, but my expectation would be that the slicer does not see them as "different". He is a screenshot in Blender (4.1)
<img width="968" alt="Screenshot 2024-08-02 at 12 30 10 PM" src="https://github.com/user-attachments/assets/952f5110-1714-433e-bb6d-c36b5e373687">

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/16474584/log.zip)
[STC-127.3mf.zip](https://github.com/user-attachments/files/16474585/STC-127.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
The normal vector of the facets in your STL model is not facing outward, which can be fixed by right clicking. Or you can check how Blender software exports the correct STL file.
![Uploading image.png…]()

**Comment by Haidiye00** [comment]
hello,you can use https://www.formware.co/onlinestlrepair this web to repair model.
