### ISSUE TITLE
Normalize OS X UI 

### ISSUE THREAD

**Issue by schreiaj** [bambulab/BambuStudio#46]
Menus are in an abnormal location when compared to other applications - using standard operating system paradigms would lower the learning curve.

**Comment by RobinWhitfield** [comment]
Should be merged with #47

**Comment by wuyifanfancy** [comment]
Thanks for the suggestion. We will optimize the UI for maxOS recently.

**Comment by YifanWuBambu** [comment]
The latest version optimized UI for OS X.
