### ISSUE TITLE
Cut Remove Option

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#461]
So we can add and changes colors but recant say highlight a part or tell one part to not print, for example, there is a way to color this apple logo but no way to make it as a cutout without using say 15 small shapes, we need the ability to say don't print this or skip over this section

![Screen Shot 2022-10-19 at 1 36 22 PM](https://user-images.githubusercontent.com/48887257/196776121-978ebd85-448d-4fb4-a0ae-cfa4468385ed.png)
![Screen Shot 2022-10-19 at 1 36 07 PM](https://user-images.githubusercontent.com/48887257/196776172-547a3c58-1d3c-4a24-bc4e-92a32b2752cd.png)

**Comment by YifanWuBambu** [comment]
This is supported. Please check this wiki page.
https://wiki.bambulab.com/en/software/bambu-studio/subtract-a-part
