### ISSUE TITLE
Even/Odd settings

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#465]
Trying to print a 3DLabs radio control plane, and the slicer just won't recognize most of the internal structure, it hollows out the object. PrusiaSlicer had a setting in the perimeter tab that is called even/odd to fix this. Can we look at implementing it in BambuStudio?

These are the recommended settings for PrusiaSlicer
**Layers and Perimeters**
Bottom solid layers: 0
Top solid layers: 0
External perimeters first: true
Layer height: 0.25 mm (0.30 mm for LW)
Perimeters: 1
Thick bridges: true
Perimeter Generator: Classic (not Arachne) since v2.5
 

**Advanced**
Default extrusion width: 0.42 mm
First layer: 0.44 mm
Perimeters: 0
External perimeters: 0
Bridge flow ratio: 0.8
Infill/perimeters overlap: 0%
Slice gap closing radius: 0
Slicing Mode: Even/Odd

**Comment by randyre** [comment]
Merge this request with https://github.com/bambulab/BambuStudio/issues/92#issue-1327280755

**Comment by SaltWei** [comment]
Could you share one 3mf of prusa project for us to compare the slicing result?

**Comment by randyre** [comment]
https://3dlabprint.com/faq/prusaslicer/
[w1.3mf.zip](https://github.com/bambulab/BambuStudio/files/9998076/w1.3mf.zip)
[2115282_Stearman_PT17_test_parts.zip](https://github.com/bambulab/BambuStudio/files/9998077/2115282_Stearman_PT17_test_parts.zip)

**Comment by randyre** [comment]
Here's a test piece provided by the designer.
[PolyLight LW-PLA Generic 200mm.zip](https://github.com/bambulab/BambuStudio/files/10007702/PolyLight.LW-PLA.Generic.200mm.zip)

**Comment by randyre** [comment]
@SaltWei Any updates on this?

**Comment by SaltWei** [comment]
Already added in internal version. Will be published soon! Thank you very much for suggestion!

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
