### ISSUE TITLE
Speeds for overhang walls not used

### ISSUE THREAD

**Issue by Apulo** [bambulab/BambuStudio#4654]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10/11

### Printer

Bambu Lab X1 Series/P1P

### How to reproduce

These are the current speed settings I used for the test. I set bridge speed to an insanely high value to highlight the issue.
![settings](https://github.com/user-attachments/assets/4fd47abd-aba5-4902-9e5f-d91c28227319)

As you can see, after slicing the outer walls of the model are correctly identified as overhang walls.
![line type](https://github.com/user-attachments/assets/6c99989e-cb6e-4df1-866c-9ed98f307f5a)

However, the slicer is printing those walls at the bridge speed, not the defined overhang speeds.
![speed](https://github.com/user-attachments/assets/fa931902-9081-42d5-885e-821665193eab)

### Actual results

Overhang walls are printed as bridges, not overhangs

### Expected results

When a wall is identified as an overhang wall, they should be printed using the "Slow Down for Overhangs" settings, not printed as a bridge.

### Project file & Debug log uploads

[scandic_plate_overhang_test.zip](https://github.com/user-attachments/files/16664561/scandic_plate_overhang_test.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
@Apulo exactly, I am improving it.

**Comment by Apulo** [comment]
Great to hear! Thanks for responding so quickly.

**Comment by tietz-r** [comment]
Hi,
i have the same issue.
I noticed that this bug appears if you enable support, even if no support will be generated.
If support is disabled, it behaves as intended.
I hope this will help

**Comment by QingZhangBambu** [comment]
@Apulo @tietz-r both bugs i have fixed. you can download the latest version to check

**Comment by QingZhangBambu** [comment]
![image](https://github.com/user-attachments/assets/66d8f8ab-73da-4572-a599-f54dae569b08)
![image](https://github.com/user-attachments/assets/a1067795-869f-4cdc-9877-48b6bbc6bde5)
