### ISSUE TITLE
Online Models 404 error

### ISSUE THREAD

**Issue by KoProGnosis** [bambulab/BambuStudio#4657]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1 Carbon

### How to reproduce

1. Use the Bambu Studio Application in a PC with Greek region
2. Go to Home page
3. Click in a model in "Online Model" category

### Actual results

An error 404 occurs. The page cannot be found. It seams like the program tries to open the webpage in Greek, but the is not a Greek version so the problem occurs. 
For example this is a URL that the app creates:
[](https://makerworld.com/en/el/studio/webview?from=bambustudio&modelid=596767)
If we remove the **'/el'** from the URL, like this:
[](https://makerworld.com/en/studio/webview?from=bambustudio&modelid=596767)
the page loads fine. 

### Expected results

The URL generator should not change the URL to unsupported languages.  

### Project file & Debug log uploads

There is not such file for this error. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
HI [KoProGnosis](https://github.com/KoProGnosis):
Could you please provide a video ,we will check it

**Comment by KoProGnosis** [comment]
![bambu-studio_BKoFhsmi4t](https://github.com/user-attachments/assets/7e3d518d-dc75-4b7e-9514-af62e292b426)
The video was above 10mb so I hope this gif helps.

**Comment by ttt888zzz** [comment]
HI [KoProGnosis](https://github.com/KoProGnosis):
the region is Europe，right？

![image](https://github.com/user-attachments/assets/24a70ae4-1ae3-4dbc-a34d-3f3aace7dae8)
![image](https://github.com/user-attachments/assets/1332ab4b-d5c9-4009-b08c-500850e35359)

**Comment by KoProGnosis** [comment]
![bambu-studio_N9pdPOYyGZ](https://github.com/user-attachments/assets/ef086b17-4734-4bae-a038-c14c0507c7b2)
The video was above 10mb so I hope the gif will do the job.

**Comment by KoProGnosis** [comment]
Hello @ttt888zzz, the language setting was undefined, I changed it to English and now it works.  The Region was already set to Europe. Thank you for your time and the solution!

**Comment by KoProGnosis** [comment]
Thank you!

**Comment by KoProGnosis** [comment]
Fixed.

**Comment by ttt888zzz** [comment]
I’m happy to help

**Comment by Deepcuts** [comment]
December 2024 and same issue. Language undefined gives 404 everywhere.
Thanks to https://github.com/bambulab/BambuStudio/issues/4657#issuecomment-2301779129 I fixed it, but it owuld be nice if Bambu Studiu got fixed instead.
