### ISSUE TITLE
The color doesn't match my paint

### ISSUE THREAD

**Issue by landofbosses** [bambulab/BambuStudio#4659]
### Bambu Studio Version

01.06.01.00

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11, version 23H2

### Additional system information

![problem 1](https://github.com/user-attachments/assets/1aaaddb3-3d68-4f4a-b7ee-d0b2d5e90262)
![problem 2](https://github.com/user-attachments/assets/d90800e2-802c-4e00-b4c8-e520b8ad0d7e)

### Printer

bambu p1s 

### How to reproduce

paint your 3d print and print

### Actual results

look at pics

### Expected results

the painted print in the slicer

### Project file & Debug log uploads

![problem 2](https://github.com/user-attachments/assets/54db8dfe-2820-480f-aca9-866ebc18660a)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
HI [landofbosses](https://github.com/landofbosses)：
Could you provide the source file，we will check it

**Comment by landofbosses** [comment]
Thank you for the response. I figured out the problem. For some reason the
filament flush went to zero
