### ISSUE TITLE
Slicer Treating Overhangs as Bridges

### ISSUE THREAD

**Issue by CS-Account** [bambulab/BambuStudio#4667]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab github releases

### OS version

NA

### Additional system information

NA

### Printer

All

### How to reproduce

https://youtu.be/HcSOz-Lsxgg?si=ewtu1FRl8s-wOHfh&t=134

This exact point of this video demonstrates and explains the problem. This has apparently been fixed already in Prusa slicer, but the fix has not been brought over.

### Actual results

Shown in video

### Expected results

The overhang should be treated as an overhang.

### Project file & Debug log uploads

NA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jedthe3rd** [comment]
I noticed this issue when I was tuning my overhang parameters on my X1C that arrived this week.

**Comment by MartinChan3** [comment]
@CS-Account I believe this question is same with  #4654

**Comment by CS-Account** [comment]
@MartinChan3 I believe both things are caused by the same underlying bug yes. Both mean that overhangs look worse in BBS vs Prusa slicer which I believe fixed this some time ago, as the section of the video I linked shows. I think the dates in the video could help track down which exact changes fixed the problem.

**Comment by CS-Account** [comment]
Duplicate of #4654

**Comment by MartinChan3** [comment]
@CS-Account The new version has been released and the question seems can be solved with new options, try it my friend!
