### ISSUE TITLE
Color slicing is incorrect 

### ISSUE THREAD

**Issue by GCRVL** [bambulab/BambuStudio#4672]
### Bambu Studio Version

1.9.3.50

### Where is the application from?

Bambu Lab Official website

### OS version

Linux Mint 21.3

### Printer

P1S

### How to reproduce

Slice a complex color model

### Actual results

Color is printed where no color should be.

![1](https://github.com/user-attachments/assets/2b13bd85-8f4b-46e5-acbd-471c15ba4797)
![2](https://github.com/user-attachments/assets/db7659bc-2b6b-4dff-825a-587b103d24cd)
![3](https://github.com/user-attachments/assets/778a63d2-551d-4d5f-8d08-c0f4b06d6042)
![5](https://github.com/user-attachments/assets/a69b1fa4-c4f4-4adc-b522-7d5b66ec607f)

### Expected results

Color should be printed only where needed.

### Project file & Debug log uploads

[broken_slicing.3mf.zip](https://github.com/user-attachments/files/16732677/broken_slicing.3mf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by GCRVL** [comment]
For clarity, the screenshots show top layers that are white in the model, but are sliced being blue.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/user-attachments/assets/b4149c40-d8b6-4c0b-9a01-9cc4a190cc81)
It may cause some slicing errors, when there are non-manifold edges in the model.
