### ISSUE TITLE
ams not sinking

### ISSUE THREAD

**Issue by Keving1950** [bambulab/BambuStudio#4695]
### Bambu Studio Version

1.9.4.60

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Additional system information

12 gen intel

### Printer

A1

### How to reproduce

1 add new filament
2 shows up on device tab
3 syn or resync in prepare tab not updated, restarted Studio and printer will not update prepare tab, print tab shows correct filament position
![Screenshot 2024-08-27 192956](https://github.com/user-attachments/assets/bd47c12b-1073-425d-b7f6-750dad3e5e08)
![Screenshot 2024-08-27 191638](https://github.com/user-attachments/assets/7eb8ac76-768c-4f54-b476-997f82d08313)
![Screenshot 2024-08-27 191457](https://github.com/user-attachments/assets/6736e820-ab6c-47d6-bcf0-d216a8159e1b)

### Actual results

even wrong if left overnight

### Expected results

want prepare tab to update

### Project file & Debug log uploads

any file
![Uploading Screenshot 2024-08-27 191638.png…]()

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by DanBao-Bambu** [comment]
May I ask if you have clicked the button and performed a resync. Also, please note that if multi device management is enabled, the sync mechanism will not take effect.

**Comment by Keving1950** [comment]
seems to have fixed itself, I I think when I have A1 and Mini connected at
the same time may be cause
Kevin Guest
0412874400

**Comment by DanBao-Bambu** [comment]
Thank you for your reply. This question will be closed, and please feel free to ask any further questions.
