### ISSUE TITLE
Bambu vs Bambu Lab filament 

### ISSUE THREAD

**Issue by TinyMito** [bambulab/BambuStudio#4698]
### Bambu Studio Version

1.9.4.60

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

macOS

### Printer

X1C, P1S

### How to reproduce

1. Updated filament profile for PPA and PPS
2. Might be a typo vendor name - you see **Bambu Lab** and **Bambu**

### Actual results

![Screenshot-August-YF6CKR3B](https://github.com/user-attachments/assets/9d0ca08e-ec27-4a8f-8ef9-25cecea3b327)

### Expected results

n/a

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by QingZhangBambu** [comment]
the latest version had fix that, thanks for reporting that bug @TinyMito
