### ISSUE TITLE
macOS UI Optimisation

### ISSUE THREAD

**Issue by Gio76** [bambulab/BambuStudio#47]
**BambuStudio version:** Version 01.01.00.13

**Operating system and version:** macOS Monterey 12.5

**Issue:**
The macOS version of BambuStudio does not seem to be following the Apple Guidelines for window management. Apps for macOS should have the 3 buttons to minimise the window and most importantly to toggle the full-screen mode (see below example from another app, fully optimised for macOS):

- <img width="261" alt="image" src="https://user-images.githubusercontent.com/26906928/180586676-cd24a6d5-f011-4394-ba13-8d074d92972e.png">

- Furthermore, the Menu of the application should reside in the top bar like this:
- <img width="575" alt="image" src="https://user-images.githubusercontent.com/26906928/180586781-7712ed8c-92c1-4d9b-92a1-452013df03c5.png">

- and not like this:
- <img width="633" alt="image" src="https://user-images.githubusercontent.com/26906928/180586866-dee43852-991b-44fc-a5af-98b9d4a206e7.png">

- Some of the icons need to be adjusted since they are in very low resolution and on Retina displays this becomes evident when compared to high res icons.
- <img width="1047" alt="image" src="https://user-images.githubusercontent.com/26906928/180587188-77d63b90-5320-400c-862b-2a418875a565.png">

**Comment by jpasqua** [comment]
In general the UI looks as though it is using a cross-platform porting layer rather than macOS-native controls. This should be rectified over time. It ought to be as native as PrusaSlicer/SuperSlicer.

**Comment by RobinWhitfield** [comment]
Should be merged with #46

**Comment by wuyifanfancy** [comment]
Thanks for the suggestions. We will optimize the UI for macOS recently.

**Comment by Gio76** [comment]
Issues fixed in v1.1.1.1. Thank you for the excellent work @wuyifanfancy
