### ISSUE TITLE
[Feature Request] Nozzle Wipe Button

### ISSUE THREAD

**Issue by Draakul69** [bambulab/BambuStudio#470]
Please add a button into bambu studio and bambu handy to clean with nozzle with the cutter tool outside of a print. This would be useful as sometimes there's a buildup of filament on the nozzle tip that could affect auto bed levelling.

**Comment by RobinWhitfield** [comment]
Immediately before ABL, the nozzle cools down, wipes, and then moves to the exposed steel bit of the bed before cooling down to 140C and slowly rubbing any excess material completely off the tip of the nozzle.

Therefore I am struggling to understand how another option for a wipe would help in this instance.

Can you clarify the issue you're actually having, or is this a theoretical concern?

**Comment by Draakul69** [comment]
I am closing this as I have realised the wipe is executed after resuming a paused print
