### ISSUE TITLE
Allow stacking in Bambu Studio

### ISSUE THREAD

**Issue by ptsao88** [bambulab/BambuStudio#471]
Currently Bambu Studio does not allow moving a part up in the Z axis.  It will always snap back to the build plate.

There are some scenarios where it may be useful to stack parts and have interface supports between them.

For example, printing many short flat parts.  Normally this would require swapping build plates every hour or two, but if the ability to stack is available, one could build more parts on one build, increasing productivity.

Thanks!

**Comment by YifanWuBambu** [comment]
@ptsao88 
You can merge several objects as a whole one. Then each original object becomes a part of the result object.
It is allowed t
![stack_objects](https://user-images.githubusercontent.com/110661856/197098888-02ee3716-6858-46d4-8b61-cfb26fdfaaa9.gif)
o stack parts inside the object.

**Comment by ptsao88** [comment]
Perfect thank you @YifanWuBambu!  You support team was not aware of this.  Cheers.
