### ISSUE TITLE
Cant select the face while using Lay on face  command

### ISSUE THREAD

**Issue by ronenst1** [bambulab/BambuStudio#4721]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Additional system information

CPU: Intel(R) Core(TM) i5-4570S CPU@2.90GHz
Intel RAM: 24GB
System Type 64Bit operating system x64-Based processor
Display Card: Nvidia GeForce GT730

### Printer

Bambu Lab X1C Combo

### How to reproduce

I create a simple cylinder in Solidworks with a diameter of 2 mm.
save as STL and import to the Bambu Studio.
While trying to lay it on the printing surface by using the "Lay on Face" command i did not get the face of the cylinder to select.
Finally i did it with rotate  by 90 deg.

### Actual results

I could not get the cylinder face with the "Lay on Face" command so i use Rotate insted

### Expected results

Could not select the cylinder face

### Project file & Debug log uploads

[Portable+phone+holder.zip](https://github.com/user-attachments/files/16817933/Portable%2Bphone%2Bholder.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Thank you for discovering the issue. We have identified the cause and thank you

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
