### ISSUE TITLE
Video stops

### ISSUE THREAD

**Issue by tomt47** [bambulab/BambuStudio#4728]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 pro

### Printer

Bambu X1 Carbon

### How to reproduce

Start video under device tab after a few minutes video shuts off. Can restart but video only stays on for a few minutes.

### Actual results

Video shuts offf

### Expected results

Hopefully you can patch this

### Project file & Debug log uploads

[debug_network_Thu_Aug_29_22_58_23.log.zip](https://github.com/user-attachments/files/16826165/debug_network_Thu_Aug_29_22_58_23.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
https://github.com/bambulab/BambuStudio/issues/4690
This could be beneficial for you.

**Comment by ttt888zzz** [comment]
1.Please download the latest version and visit the website，https://bambulab.cn/zh-cn/download/studio
2.Update 【References】setting，according the photo
![img_v3_02fi_e0cdfdac-479a-4057-8660-6dd6f18a36ag](https://github.com/user-attachments/assets/e446cc7c-efaf-4f69-81ad-b4b1b973152c)
https://github.com/bambulab/BambuStudio/releases
