### ISSUE TITLE
Wall Splits

### ISSUE THREAD

**Issue by topheryorks** [bambulab/BambuStudio#4729]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS 14.6.1

### Additional system information

Apple M1 Pro
16GB ram

### Printer

Bambu P1P

### How to reproduce

slice file using .12mm Fine @BBL P1P preset with Arachne wall generator.
print file on Bambu Lab P1P
cookie cutter file is having wall splits

### Actual results

We are a cookie cutter company and have been using the same .12mm Fine @BBL P1P setting (with Arachne wall generation) since January of 2024.  Great results each time.  

After the recent Bambu Studio update we have been having wall splits.

I notice the new presence of gap infill on our slices which didn't used to appear.  
<img width="1840" alt="Screenshot 2024-08-31 at 6 57 23 PM" src="https://github.com/user-attachments/assets/825f90aa-803f-4115-a01c-e8e98f9cecc3">

### Expected results

Cutter file printed without wall splits.

### Project file & Debug log uploads

[debug_network_Sat_Aug_31_16_48_14.log.enc.zip](https://github.com/user-attachments/files/16826304/debug_network_Sat_Aug_31_16_48_14.log.enc.zip)
[BambuStudio.conf.zip](https://github.com/user-attachments/files/168263
[Cute Chubby Cat 3.75.stl.zip](https://github.com/user-attachments/files/16826307/Cute.Chubby.Cat.3.75.stl.zip)
05/BambuStudio.conf.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by topheryorks** [comment]
[Archive.zip](https://github.com/user-attachments/files/16838093/Archive.zip)
 attaching the first two files with problems after the upgrade to 1.9.5.51

**Comment by QingZhangBambu** [comment]
@topheryorks hi, the file you send use classic mode, so it had gap. the arachne mode looks fine.
![image](https://github.com/user-attachments/assets/2753da8c-37cf-49cc-bfef-bb370087e977)
![image](https://github.com/user-attachments/assets/f3173ce2-2fb2-4747-a018-04f59c7dd51b)

**Comment by topheryorks** [comment]
Thanks.  The most recent Bambu studio update fixed the problem (1.9.7.52)
