### ISSUE TITLE
No image in troubleshooting 0300_0A00_0001_0002

### ISSUE THREAD

**Issue by OmiCron07** [bambulab/BambuStudio#473]
It should have images in the wiki, but does not: https://wiki.bambulab.com/en/x1/troubleshooting/hmscode/0300_0A00_0001_0002

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/f5056f02-6206-4b29-b8e7-e60606d13a67)
Do you mean these pictures?

**Comment by SaltWei** [comment]
Close this issue. Reopen if has new update
