### ISSUE TITLE
Updated Software Version

### ISSUE THREAD

**Issue by Infinity-Papa-Joe-9mm** [bambulab/BambuStudio#4735]
### Bambu Studio Version

1.9.4.60

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Version 22H2 (OS BUILD 22621.4037

### Printer

Bambu Lab P1S

### How to reproduce

![Screenshot (337)](https://github.com/user-attachments/assets/f9121f5c-3c06-473f-a134-7b90f21adb12)

### Actual results

Ever since updating to the newest version, I continue to get ERROR: .......................  NON-Manifold edges on models. Before I never got those. I went back and tried some older prints that I did with no problem, now I get the error

### Expected results

Ability to print files

### Project file & Debug log uploads

[20-Painted Stock_1972_Chevrolet_Corvette_ZR1_1.zip](https://github.com/user-attachments/files/16829286/20-Painted.Stock_1972_Chevrolet_Corvette_ZR1_1.zip)

### Checklist of files to include

- [ ] Log file
- [x] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/b3558b44-e057-4f6c-9c10-5be4ac418e46)
Hello, the non manifold error function has always been available. If you are a Windows user, you can right-click to find the repair function and fix it first.

**Comment by Infinity-Papa-Joe-9mm** [comment]
I did try to right click and utilize the "FIX" option. The screen came up with the repair but would never complete the repair Thanks, Papa Joe Team Infinity On Sep 3, 2024, at 4:34 AM, Haidiye00 ***@***.***> wrote: image.png (view on web) Hello, the non manifold error function has always been available. If you are a Windows user, you can right-click to find the repair function and fix it first. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you authored the thread. Message ID: ***@***.***>

**Comment by Haidiye00** [comment]
Hello, you can ignore it for now. We have checked your model and feel that the quality of the triangular facets in your model is not high. Could you please check where it was made and see if there is any room for improvement. We have checked that it does not affect printing.

![img_v3_02ff_9ae432ab-01bc-441f-8086-e837f78a214g](https://github.com/user-attachments/assets/bd0da36c-4711-4821-9aec-ef21f096ef65)
and red lines is non manifold edges
![img_v3_02ff_85b49433-9d10-4f14-9050-a6125157734g](https://github.com/user-attachments/assets/8a98eb17-119a-4caf-9c23-498f0581dd3c)
