### ISSUE TITLE
arrange all objects broken

### ISSUE THREAD

**Issue by theastadler** [bambulab/BambuStudio#474]
![image](https://user-images.githubusercontent.com/72948786/197063272-75ed59ec-f583-4da4-b3c4-320b7138e1ce.png)
![image](https://user-images.githubusercontent.com/72948786/197063299-bd339266-c5dc-40fe-bbd4-1d88130a2ab0.png)

Since the most recent update, when using the "arrange all objects" function, some items are placed on top of each other.

**Comment by manch1n** [comment]
@theastadler Could you please share the source file to help us debug it?

**Comment by OmiCron07** [comment]
Totally broken for me:

![image](https://user-images.githubusercontent.com/31325575/197260861-dcecb55b-85d0-47df-82f0-0ed2486121ee.png)

[Gizo the Spider.zip](https://github.com/bambulab/BambuStudio/files/9841395/Gizo.the.Spider.zip)

**Comment by tangketan** [comment]
@OmiCron07 Sorry that I can't reproduce the bug. It's OK on my side. Version is the same as yours, 1.2.0.9.
![image](https://user-images.githubusercontent.com/13730459/198915314-78d2dc31-52cb-4010-873a-0c0fb160752c.png)

**Comment by OmiCron07** [comment]
I can reproduce the problem with the included file and the version '01.03.00.12'. I even have another project with the same problem:

![image](https://user-images.githubusercontent.com/31325575/199338682-f49a0aa1-7568-48af-bb9e-cf7d05f64bf9.png)
![image](https://user-images.githubusercontent.com/31325575/199338716-524a0e39-79d8-4aa5-8cfa-25697251d548.png)

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
