### ISSUE TITLE
overhang wall before the overhang bridge when slice

### ISSUE THREAD

**Issue by CanvasQAQ** [bambulab/BambuStudio#4741]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows11

### Additional system information

![image](https://github.com/user-attachments/assets/ce8dc9df-a3bb-4734-86e7-05e4472453d3)
![image](https://github.com/user-attachments/assets/194cec70-8705-470a-b47f-b8b5c2532dc0)

You can see that the hole location creates an overhanging wall before the bridge, which will directly gen - spaghetti .
The  model is https://makerworld.com.cn/zh/models/225710#profileId-150556
The gcode is as file
[gridfinity_miniwrench set bambu profile(3).gcode.zip](https://github.com/user-attachments/files/16839675/gridfinity_miniwrench.set.bambu.profile.3.gcode.zip)

### Printer

A1

### How to reproduce

As the gcode file/proj file, no need re-print, just review the slicer gcode you will find the issue.

### Actual results

spaghetti

### Expected results

normal print

### Project file & Debug log uploads

[gridfinity_miniwrench.zip](https://github.com/user-attachments/files/16839686/gridfinity_miniwrench.zip)

No log , just as the slicer screenshot

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
@CanvasQAQ yep, it is an improvement point. but a bit trick to fix. I will add it to our feature list

**Comment by QingZhangBambu** [comment]
@CanvasQAQ sorry, it needs support. the bridge and wall will fail no matter which is printed first.

**Comment by MartinChan3** [comment]
@CanvasQAQ I think you should open the 'Use Support' option to solve this question...

**Comment by CanvasQAQ** [comment]
Hi all, 

Thanks.
When I find that gen-spaghetti  then I add support and re-print, it have been print successed now.
I'm just curious that I have been prompted to open the option when this type overhanging wall appeared before (maybe 2weeks ago). But when sliced this model, I didn't get any warning. Of course, the main reason for this failure was that I didn’t check this model carefully.

Anyway, thank you very much.

BRs,
Canvas
