### ISSUE TITLE
Vertical stripes on fuzzy skin in Bambu studio ver1.09.05.51

### ISSUE THREAD

**Issue by supuri** [bambulab/BambuStudio#4746]
### Bambu Studio Version

1.09.05.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows10

### Printer

P1S and A1 mini

### How to reproduce

Fuzzy skin>Contour.
Maybe just selecting a fuzzy skin will happen with any of them.

It seems to me that this symptom is more likely to appear in geometries that use "sweeps" on CAD.

### Actual results

![1 09 05 51](https://github.com/user-attachments/assets/50a7974f-0cef-47f8-b7f9-99bea1d8206f)
![DSC1090551](https://github.com/user-attachments/assets/0627b82e-0dda-4c0f-ae13-c5a1456e8f7d)

Vertical stripes are already present in the preview stage of Bambu Studio.

### Expected results

![1 09 03 50](https://github.com/user-attachments/assets/c6f993e1-7197-4ef8-af14-2cc40960db8c)
![DSC1090350](https://github.com/user-attachments/assets/22618ea1-3ac6-4e74-bcc9-685250985462)

Ver 1.09.03.50 did not include vertical stripes. I would like to see it return to this state.

### Project file & Debug log uploads

Just screenshots and pics.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
HI  [supuri](https://github.com/supuri)：
Could you please provide the source file,we will check it.

**Comment by supuri** [comment]
[Test1.gcode.zip](https://github.com/user-attachments/files/16843397/Test1.gcode.zip)

Here it is, it sliced in Ver 1.09.05.51. Stripes appear.

**Comment by vahurvilta** [comment]
I have exact same problem after updating.

**Comment by huangdun** [comment]
Also seeing this strange line on my print when fuzzy skin is used.

**Comment by ttt888zzz** [comment]
Thank you for your feedback. We will update this feature in the next release soon

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
