### ISSUE TITLE
Ironing does not work when used as a modifier

### ISSUE THREAD

**Issue by OmiCron07** [bambulab/BambuStudio#475]
Used a modifier to iron a part and it does not print the layer on which it does the ironing.

![image](https://user-images.githubusercontent.com/31325575/197088852-1423df3b-8970-4a91-b30a-4f958aa09535.png)

There is the project file: https://filetransfer.io/data-package/Rljajrdf#link

I tried to print it and it ironed in the air.

**Comment by OmiCron07** [comment]
Even with a simple project with a cube:

![image](https://user-images.githubusercontent.com/31325575/197095045-ece4f1b7-2bb7-480b-bc3c-e4301c5a3a04.png)

**Comment by OmiCron07** [comment]
Found out that the bug is only in the latest version (01.03.00.12).

**Comment by SaltWei** [comment]
Choosing monotonic pattern for top surface can be a workaround

**Comment by SaltWei** [comment]
Fixed patch will be included in next version.

**Comment by YifanWuBambu** [comment]
This is fixed in v1.4.
