### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by wmbtwarrior** [bambulab/BambuStudio#4755]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11

### Printer

bambu X1C

### How to reproduce

1. load in a model.
2.  change orientation of model using lay on face function
3. scale item up by 1 of the XYZ coordinates and turn uniform scaling off to see problem

### Actual results

Using the above example say you want to scale an item to be taller, and when you import it, it is laying on its side, so you flip to face on the flat surface then scale just the Z. you will notice that its not the expected results as it does not get taller on the Z but it gets wider on the Y axis. i noticed this with the last update as well before i updated this week. 

### Expected results

taking a object and flipping it onto a flat surface should change the information around the scaling and when i go to make the item taller on the Z axis it makes the item taller and then scales X and Y properly when uniformed

### Project file & Debug log uploads

[Rotation object doesnt change the Y and Z axis for scaling.zip](https://github.com/user-attachments/files/16873588/Rotation.object.doesnt.change.the.Y.and.Z.axis.for.scaling.zip)
[
[debug_network_Tue_Sep_03_19_46_43.log.zip](https://github.com/user-attachments/files/16873603/debug_network_Tue_Sep_03_19_46_43.log.zip)
](url)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
The issue of inconsistent coordinates and expected scaling direction has been fixed and is currently undergoing internal testing. Please wait
