### ISSUE TITLE
Settings By Layer Height [Feature Request]

### ISSUE THREAD

**Issue by rwoldberg** [bambulab/BambuStudio#476]
I would like the ability to change the settings based on layer height.  At least one other slicer that I have used has this feature and there are times when it is extremely useful.  One example is when there is a section of a part that you want solid infill but not the rest.

**Comment by YifanWuBambu** [comment]
@rwoldberg 
Please try the cubic modifier, which could also do the same thing.

**Comment by rwoldberg** [comment]
That works, and I see how it is more flexible than just settings by layer height, but it is not as easy either.

**Comment by psiberfunk** [comment]
The cubic modifier is definitely less intuitive but more flexible.  Since Bambu strives to be approachable, however, it would be good to have a by-layer-height thing.. particularly because in some cases people may want to change properties gradually over layer height for cosmetic reasons.

**Comment by halofx** [comment]
YES!!! Please implement Height Range Modifiers, as in Prusa Slicer. I desperately miss this function. There are several differences between height ranges and block modifiers. First is clutter, adding all those blocks to the screen can clutter up the view, and make it difficult to make additional changes. Second is precision, It is much easier to target the exact layers where changes should happen with a height range, than blocks. Specially considering that the block values are relative to the base model, so the math can be much more complex, and counter intuitive.

**Comment by liftbag** [comment]
> YES!!! Please implement Height Range Modifiers, as in Prusa Slicer. I desperately miss this function. There are several differences between height ranges and block modifiers. First is clutter, adding all those blocks to the screen can clutter up the view, and make it difficult to make additional changes. Second is precision, It is much easier to target the exact layers where changes should happen with a height range, than blocks. Specially considering that the block values are relative to the base model, so the math can be much more complex, and counter intuitive.

I totally agree with you.

**Comment by psy0rz** [comment]
closed in 1.6.0

**Comment by mduft** [comment]
Closed as complete means this feature exists...? How can I use it?

**Comment by SaltWei** [comment]
> Closed as complete means this feature exists...? How can I use it?

![image](https://github.com/bambulab/BambuStudio/assets/110660407/52faf45e-b045-4277-9738-ec1e610bfc54)
![image](https://github.com/bambulab/BambuStudio/assets/110660407/6cded138-f7b1-44e1-9bf0-ef0c99858501)

**Comment by mduft** [comment]
That is... perfect! Thanks :)
