### ISSUE TITLE
Coordinates inside assembly are set to world coordinates instead of object coordinates.

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#4775]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

AMD Ryzen 5700G
64 GB
Internal graphics

### Printer

X1C

### How to reproduce

add a cube to a model, and select the cube in the assembly for moving.

### Actual results

The coordinates presented are the "world" coordinates instead of the local coordinates relative to the assembly.

### Expected results

You should see (as it was) the relative coordinates to the assembly.
Sticking to the world coordinates can be very crippling if you want to do more complicated editing within Bambu Studio. Especially aligning multiple parts is a pain now.

Can not find a setting where you can change this (new?) behavior.

### Project file & Debug log uploads

[example110.zip](https://github.com/user-attachments/files/16919852/example110.zip)
[debug_Sat_Sep_07_02_05_26_13936.log.0.zip](https://github.com/user-attachments/files/16919853/debug_Sat_Sep_07_02_05_26_13936.log.0.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by coat64** [comment]
In Orca slicer the difference between world- and object coordinates is still intact.

![example111](https://github.com/user-attachments/assets/6c421377-f1de-4712-b94a-46809b1a0720)

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/2854d20b-0c5c-40b9-a199-846fdc63187a)
We have noticed this issue and the internal version has been resolved. Please stay tuned for the new version~
