### ISSUE TITLE
disabling supports by body instead of painting the keep outs

### ISSUE THREAD

**Issue by anandijain** [bambulab/BambuStudio#4776]
i know that i can do support painting and there is a fill button, but it is a bit slow when there are many faces and objects.

is there a way to just select an entire body and prevent any supports from being generated on it?

that would make life a lot easier when doing prints where only a few objects need supports 

thanks

**Comment by TheUnknownDan** [comment]
Can't you go from Global to object params and just untick the Supports on the object you don't want them on?

**Comment by anandijain** [comment]
🤦 can't believe I missed that! thanks @TheUnknownDan
