### ISSUE TITLE
Should offer a switch for user to decide instead of directly close the camer

### ISSUE THREAD

**Issue by RuioWolf** [bambulab/BambuStudio#4777]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10 22h2

### Printer

X1C

### How to reproduce

commit https://github.com/bambulab/BambuStudio/commit/e3a7ad05487e9517730e8f9d7d5613ce9f28c20e introduce `stop liveview long time no input`.

### Actual results

the camera closes after 900s of idle.

### Expected results

I think it should offer a switch for user to choose whether close the camera after a certain time, instead of directly close it.

### Project file & Debug log uploads

no log needed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
the same issue #4690

**Comment by ttt888zzz** [comment]
HI[KedziePanda](https://github.com/KedziePanda)、[mupke475](https://github.com/mupke475): 
1.Please download the latest version and visit the website，https://bambulab.cn/zh-cn/download/studio
2.Update 【References】setting，according the photo
![img_v3_02fi_e0cdfdac-479a-4057-8660-6dd6f18a36ag](https://github.com/user-attachments/assets/e446cc7c-efaf-4f69-81ad-b4b1b973152c)
https://github.com/bambulab/BambuStudio/releases
