### ISSUE TITLE
Natural scrolling media on a Mac

### ISSUE THREAD

**Issue by maxmax3** [bambulab/BambuStudio#479]
I'm missing natural scrolling on the Mac version, e.g. scrolling media (time lapse videos).
Natural scrolling: moving the content of a page – rather than moving the scroll bar.

**Comment by YifanWuBambu** [comment]
@maxmax3 
Thanks for the suggestion. We will optimize it in the next release.

**Comment by bambu123** [comment]
Thank you for your feedback. It's a bug. We'll fix it next version.

**Comment by YifanWuBambu** [comment]
This is fixed in v1.4.
