### ISSUE TITLE
Can't download Network Plug-in on MacOS

### ISSUE THREAD

**Issue by NalinKamboj** [bambulab/BambuStudio#4794]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sequoia 15.0

### Additional system information

MacBook Pro M1 14 inch

### Printer

Bambu Lab A1 Mini

### How to reproduce

1. Open BambuStudio
2. Click Install Network Plugin

### Actual results

Failed to download the plug-in. Please check your firewall settings and vpn software, check and retry

### Expected results

Plugin should install

### Project file & Debug log uploads

Not available

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
Yesterday, Bambulab cloud service migrate from California to Oregon at yesterday. A system anomaly occurred between 17:08 and 20:36, and causing access problems. Please access cloud service working status at [status.bambulab.com](http://status.bambulab.com/)。
Please try again. We are very sorry for the inconvenience。

**Comment by twf3238** [comment]
iMac 24-inch, M1, 2021, MacOS Sonoma 14.1.2
Bambu Studio 1.9.5.51

Bambu Studio works without issue when launched from the main user session (that was used to install Bambu Studio). This issue occurs when using another session. Note: No issue reported from status.bambulab.com.

How to reproduce : Launch Bambu Studio from a user session that did not installed Bambu Studio, then click Login/register.
Actual results: popup window "Bambu Network plug-in not detected. Click here to download it". When message is clicked, new po-up window "Failed to download plug-in. Please check your firewall settings and vpn software, check and retry."

**Comment by ttt888zzz** [comment]
[twf3238](https://github.com/twf3238)：This wiki may be helpful， https://wiki.bambulab.com/en/software/bambu-studio/failed-to-get-network-plugin.

**Comment by twf3238** [comment]
> [twf3238](https://github.com/twf3238)：This wiki may be helpful， https://wiki.bambulab.com/en/software/bambu-studio/failed-to-get-network-plugin.

Thx t8z. 

I struggled for a while but probably found the cause of all this : the VPN was automatically connecting on the main session and probably does not disconnect (or not harmlessly) when switching to another user. 

So, checking that VPN is disabled on all users could also be a recommandation on this wiki page. 

Saying this, thanks again for the support.

**Comment by twf3238** [comment]
Oups sorry… I didn’t read far enough. Everything is said already. Appologize.
