### ISSUE TITLE
Problem with AMS Lite detection by Bambu Lab A1 Mini printer

### ISSUE THREAD

**Issue by ChickChickenKFC** [bambulab/BambuStudio#4796]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab A1 mini Combo

### How to reproduce

When the printer is turned on but does not print, remove the cable from the AMS lite

### Actual results

I have a problem with my Bambu Lab A1 Mini printer, which stopped detecting AMS Lite after accidentally disconnecting it. I have already tried several solutions, but unfortunately the printer still does not recognize AMS. Here are the details of the problem:

Printer model: Bambu Lab A1 Mini
AMS Lite works properly - mechanically and in terms of connections, but the printer does not detect it.
I tried restarting both the printer and AMS Lite, checked cable connections, ports and updated the printer firmware, but to no avail.
I made sure the cable was fully functional and the ports were clean.
The printer does not show any AMS-related errors, but there is no option to manually detect this device.
ams pulls in the filament normally and 4 white LEDs light up
I would like to ask for help in solving the problem or for advice on further steps I can take.
![457144477_1538165420126251_910654321294522729_n](https://github.com/user-attachments/assets/0b8a8ec0-95ec-4515-a43a-3b8f88739b32)

![454487132_2111982325998798_7822464626402596810_n](https://github.com/user-attachments/assets/c0006689-0e39-411d-a05c-0f47e377fc8c)

### Expected results

The printer does not detect AMS

### Project file & Debug log uploads

[Uploading debug_Tue_Sep_10_15_23_28_2956.log.0.zip…]()

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ChickChickenKFC** [comment]
I forgot to add that I'm new to printers and I'm not very good at writing on forums, so if you have any questions, feel free to write.

**Comment by gaolegao-lx** [comment]
**Please upload log through Handy APP, and give us your ticket number**
***
***Upload log files through Bambu Handy***
     Log files from the Bambu printer can be uploaded via Bambu Handy over the network, with an upload speed of around 150 kbps under optimal network conditions.
     When uploading logs, you have the option to select a specific time frame, allowing you to reduce the volume of logs transmitted and shorten the upload duration.
     To upload files, go to **Me** → **Support Tickets** → Choose the ticket for log upload and proceed with the operation.
     ![app_support_ticket](https://wiki.bambulab.com/p1/troubleshooting/upload-log/app_support_ticket.png)

**Comment by TWhynot** [comment]
Having the same issue. What was the fix?
