### ISSUE TITLE
Cannot set coordinates

### ISSUE THREAD

**Issue by stefek47** [bambulab/BambuStudio#4805]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab A1 mini

### How to reproduce

1. Add object,
2. Add negative part
3. Set negative part X coordinates 
4. Set negative part Y coordinates

### Actual results

When I set the Y or Z coordinates, it moves in different direction and the set coordinates doesn't change.
When I use the move options, arrows are in wrong places.

### Expected results

Object should move to set coodinates.

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/16978492/log.zip)
[adapter.zip](https://github.com/user-attachments/files/16978494/adapter.zip)
![2024-09-11 19_57_56-adapter wewnętrzny - BambuStudio](https://github.com/user-attachments/assets/e4ee6cf3-4f81-4cda-9b74-7c023f3b5d28)
![2024-09-11 19_57_26-adapter wewnętrzny - BambuStudio](https://github.com/user-attachments/assets/5ba62773-0cb0-4a62-833f-bbdb79d653d2)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Hello, can you provide 3mf? Thank you~

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/6446ace1-563f-407d-bd2a-6797d1d08940)
We have added a local coordinate system in the internal version, please wait for the next version

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
