### ISSUE TITLE
Camera Feed Stops

### ISSUE THREAD

**Issue by MasterMatthew** [bambulab/BambuStudio#4811]
### Bambu Studio Version

1.9.5.5.1

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Labs X1C

### How to reproduce

Step 1: Open Studio
Step 2: Slice
Step 3 Send to pronter
step 4: Watch Live view

### Actual results

while watching the printer feed, after 15 mins or so the camera screen goes black and there is a message that says : 
 temporarily closed because there is no operating for a long time

### Expected results

be able to use the camera to monitor prints

### Project file & Debug log uploads

[debug_Fri_Aug_16_19_23_53_5804.log.zip](https://github.com/user-attachments/files/16988741/debug_Fri_Aug_16_19_23_53_5804.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
The same issue https://github.com/bambulab/BambuStudio/issues/4690

**Comment by tinman31k** [comment]
Any idea when the next update will be?  It would be great if it is soon so that the camera issue would be fixed.

**Comment by MasterMatthew** [comment]
My work around. I installed older version of studio, wasn't having any trouble with it. So when it asked me to update, I selected 'Skip This Release'.

**Comment by ttt888zzz** [comment]
HI [MasterMatthew](https://github.com/MasterMatthew)、[attochron](https://github.com/attochron)、[tinman31k](https://github.com/tinman31k)：The internal version has added a new configuration to control the automatic camera stop, and we will update this feature in the next version soon

**Comment by MasterMatthew** [comment]
> HI [MasterMatthew](https://github.com/MasterMatthew)、[attochron](https://github.com/attochron)、[tinman31k](https://github.com/tinman31k)：The internal version has added a new configuration to control the automatic camera stop, and we will update this feature in the next version soon

Awesome! Looking forward to it. Much appreciated.
Thank you and tell the team thank you!

**Comment by ttt888zzz** [comment]
HI[KedziePanda](https://github.com/KedziePanda)、[mupke475](https://github.com/mupke475): 
1.Please download the latest version and visit the website，https://bambulab.cn/zh-cn/download/studio
2.Update 【References】setting，according the photo
![img_v3_02fi_e0cdfdac-479a-4057-8660-6dd6f18a36ag](https://github.com/user-attachments/assets/e446cc7c-efaf-4f69-81ad-b4b1b973152c)
https://github.com/bambulab/BambuStudio/releases
