### ISSUE TITLE
Can't print multi-object / multi-material due to large temperature difference error

### ISSUE THREAD

**Issue by OmiCron07** [bambulab/BambuStudio#482]
If we print by object different materials (e.g. PETG and PLA), I would think that the error message blocking us is irrelevant.

![image](https://user-images.githubusercontent.com/31325575/197285911-67d1f943-edba-401d-935e-d181d501b54a.png)

I understand that by layer, this may cause a problem, but printing by object, is it really a blocker?

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
