### ISSUE TITLE
Using the Fuzzy Shell option will create patterned textures on the surface.

### ISSUE THREAD

**Issue by ANicksn** [bambulab/BambuStudio#4825]
### Bambu Studio Version

1.9.5.51

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lan X1C

### How to reproduce

1) Go to the "other" tab
2) enable the "fuzzy skin" mode
3) leave the default settings
4) start printing

### Actual results

After updating to the latest version, vertical stripes began to appear on the surface, i.e. the fuzzy shell became less random (apparently the fix in version 1.9.4 no longer works and repeating patterns appear again).
![photo_2024-09-16_13-27-28](https://github.com/user-attachments/assets/207a1ac6-8744-4a71-80fc-e0c666cda27d)

### Expected results

Expected to get a random fuzzy surface, as it was before update 1.9.5.51
![photo_2024-08-25_20-22-52](https://github.com/user-attachments/assets/d24128d8-d407-4b1d-a639-83e8b2533d69)

### Project file & Debug log uploads

[Абажур_новый.zip](https://github.com/user-attachments/files/17011043/_.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
Thank you for your feedback. The internal version has been fixed and we will fix it in the next version.

**Comment by ttt888zzz** [comment]
HI [ANicksn](https://github.com/ANicksn)：Please download the latest version, as the issue has been fixed.

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
