### ISSUE TITLE
If AMS is connected there is no Unload button.

### ISSUE THREAD

**Issue by Superbobo75** [bambulab/BambuStudio#483]
If AMS is connected there is no Unload button in case filament is loaded via the side spool even though the display indicates it is Loading filament. And the system knows it is not from the AMS.
If I disconnect the cable from the AMS, the Unload button shows back up.

![Photo 21 10 2022 20 03 28](https://user-images.githubusercontent.com/12749410/197292290-aec8c56b-b451-4120-92eb-bf5a8d1b8ef8.jpg)
![Photo 21 10 2022 20 06 54](https://user-images.githubusercontent.com/12749410/197292297-ab122fc1-7c58-46a7-b7c8-fbffbc5b106d.jpg)

**Comment by YifanWuBambu** [comment]
@Superbobo75 
When AMS is connected, please go to AMS page to load/unload.

**Comment by Superbobo75** [comment]
But since the new Bambu/AMS firmware, there is no need to disconnect the cable to print from the AMS or the side spool. When I have AMS connected but I don't Loading filament from AMS but side spool, there is no Unload button on either screen. 
![image](https://user-images.githubusercontent.com/12749410/197328568-02a0f81a-a68d-44c6-97c0-e760e54b3441.png)


There is an indication of loaded filament on the first screen, but on the AMS screen all filaments are unloaded. This means that filament is loaded from the side spool. Despite this, there is no Unload button on either screen.

![Photo 22 10 2022 10 07 22](https://user-images.githubusercontent.com/12749410/197328523-3e1d4f10-07e3-4565-a288-2e5803c7a16a.jpg)
![Photo 22 10 2022 10 07 15](https://user-images.githubusercontent.com/12749410/197328529-05261ab9-3fd9-4ade-a9f9-f0aa4a73bd25.jpg)

**Comment by YifanWuBambu** [comment]
Oh, you are right, We should keep the unload icon. Thanks for reporting the issue.

**Comment by Superbobo75** [comment]
Probably one of the most commented bugs at the moment and I posted this here back in October. Is there any way you can move this forward in terms of a solution?

**Comment by SaltWei** [comment]
The latest printer firmware has handled this issue. Please update and try.

Studio will also handle this issue in next release version.

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
