### ISSUE TITLE
still issue with arachne and line width in latest version only

### ISSUE THREAD

**Issue by pzirnik** [bambulab/BambuStudio#4832]
### Bambu Studio Version

v01.09.05.51

### Where is the application from?

Bambu Lab github releases

### OS version

openSUSE Leap 15.5

### Printer

Bambu Lab X1C

### How to reproduce

use arachne wall generator as in attached project file

### Actual results

some lines created with arachne do have to big line width, which is visible in slicer preview already and also on printed part
as seen in attached bad-linewidth.png

### Expected results

same as arachne works with version v01.09.03.50 as seen in attached good-linewidth.png

### Project file & Debug log uploads

[projectfile.zip](https://github.com/user-attachments/files/17040641/projectfile.zip)
![bad-linewidth](https://github.com/user-attachments/assets/21e3f5d2-2c72-49e0-a5c2-11d7fd2bbe53)
![good-linewidth](https://github.com/user-attachments/assets/4ac07bf7-3198-4d8b-8d57-2277f02b324d)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by pzirnik** [comment]
picture from printed part
![bad-linewidth-printed](https://github.com/user-attachments/assets/0c18186f-6143-4e1a-a92b-996531a119cc)

**Comment by ttt888zzz** [comment]
HI [pzirnik](https://github.com/pzirnik)：The internal version has been fixed , and we will update this feature in the next version soon.

**Comment by pzirnik** [comment]
Great and thanks.
