### ISSUE TITLE
Wall and Infill print order.  Add   Inner/Infill/Outer

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#484]
Seems that this one order is missing.    Inner/Infill/Outer

**Comment by YifanWuBambu** [comment]
Hi @randyre ,
In what senario do you need this order?

**Comment by randyre** [comment]
I had a large domed shape that I was printing, but it needed the infill to rest on for the outer layer, So wanted to print the inner first. Infill first was not sticking reliably, so wanted to give it at least one wall and it needed to be the inner since the outer needed the infill for support.  It is not a big deal as it is reasonably rare to need this.

**Comment by YifanWuBambu** [comment]
"so wanted to give it at least one wall and it needed to be the inner since the outer needed the infill for support"
Could you share the model file to us?

**Comment by randyre** [comment]
[BD5 Fuse.zip](https://github.com/bambulab/BambuStudio/files/9998089/BD5.Fuse.zip)
