### ISSUE TITLE
Feature Request. Traditional Timelapse user customized setting

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#485]
Is there a way you could change traditional timelapse to have an input toggle to make the last (x) number of layers set as smooth so that the printhead is not sitting above the print when the video ends?  

Or if that's too much work could we at least move the printhead to the home position before the very last frame is shot?

**Comment by YifanWuBambu** [comment]
@randyre 
We will provide the following 3 types:
1. traditional timelapse
2. smooth timelapse without prime tower
3. smooth timelapse with prime tower

Maybe you can use the 3rd option.
