### ISSUE TITLE
Format error (overlapping of output fields) in the display (window) of the estimated printing time for several printing plates.

### ISSUE THREAD

**Issue by Ringo-092024** [bambulab/BambuStudio#4864]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 10 Pro / Version 22H

### Additional system information

Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz   3.70 GHz 
64 GB RAM
512 GB SSD (C:)
NVIDIA GeForce GTX 780
Monitor 27" (2560x1440)

### Printer

Bambu Lab X1C

### How to reproduce

1. Open File "V-Spooler+1.0+-+Bambu.3mf" , source Maker World (https://makerworld.com/de/models/98832#profileId-105442)
2. then Preview 
3. Slice all printing plates
4. display all printing times all printing plate as overview of all printing plates in separate small window

![01--Error--wohlfahrt2003@web de-BambuLab-Version 1 19 7 52--Formaterror](https://github.com/user-attachments/assets/26813660-12da-4a3f-bf81-d78317d6e7f2) 

### Actual results

Everything below is without errors.

### Expected results

Reformatting the output window.

![02--Solution--wohlfahrt2003@web de-BambuLab-Version 1 19 7 52--Formaterror](https://github.com/user-attachments/assets/ec030ca5-dd76-4d7d-b020-87c983346429)

### Project file & Debug log uploads

V-Spooler+1.0+-+Bambu.3mf (40MB)
(Error-Message: File size too big: 25 MB are allowed, 37 MB were attempted to upload.V-Spooler+1.0+-+Bambu.zip (37MB))
[Upload-project-file-(V-Spooler+1.0+-+Bambu.3mf)-is-not-possible.txt](https://github.com/user-attachments/files/17084408/Upload-project-file-.V-Spooler%2B1.0%2B-%2BBambu.3mf.-is-not-possible.txt)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Ringo-092024** [comment]
Best regards from Germany!

**Comment by Ringo-092024** [comment]
Best regards from Germany!

**Comment by LiZ-Li-BBL** [comment]
We will fix it soon

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website at https://github.com/bambulab/BambuStudio/releases， and try again.
