### ISSUE TITLE
Move tool places object at random heights

### ISSUE THREAD

**Issue by owocowyy** [bambulab/BambuStudio#4868]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 Pro

### Printer

P1S

### How to reproduce

1. Open 3MF file I attached
2. Try to place the "keyrambit" object flat with the plate (so they are touching each other) using the Move tool.
3. When you input 0 at the "Z" axis the object goes very deep beyond the plate and the actual "Z" becomes -23.44.
4. Now input 23.44 as the new "Z" and then the object goes very heigh (93.76 mm)

I encountered the same behaviour when using modifiers or just wanting to flip the object by 180 degrees (so I can get the texture from the build plate at the "front" of the model). When I flip the object and then want to place it flat with the bed using the move tool, "Z" axis starts behaving differently then before the flip operation.

### Actual results

The object appears at random heights

### Expected results

The object should be placed exactly at the height specified in the "Z" axis field

### Project file & Debug log uploads

[z_axis_bug.3mf.zip](https://github.com/user-attachments/files/17089812/z_axis_bug.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/2926a83e-c381-4d60-878c-e3e672507244)
We have upgraded the translation tool in our internal version. Please wait for the next version. Thank you~

**Comment by DevHyfes** [comment]
Hi Friends, I do not think your feature to select the coordinate system fixes this issue. Let me describe the behavior I am seeing. 

![image](https://github.com/user-attachments/assets/8eb04e05-7d84-4256-90a1-f95041ef9ab1)

Notice that the current coordinates are X:83.59, Y130.18, Z17.66. I click in the "Z" field, and enter "0.00" and the object does not drop to the plate. Instead it shows this: 

![image](https://github.com/user-attachments/assets/82ca3c8f-e0eb-46bf-8fce-e1149434d269)

The Z position has not changed to 0, it has doubled to 35.32

Maybe this upgrade fixes that problem, but I just wanted to be clear on the issue that I am having and that I think the Original Reporter was having.

**Comment by DevHyfes** [comment]
playing around with this more, I can see that the dialogue box honors my selection for X value- if I enter 0, it will move the piece to 0, and the field will update to 0.00. But if I try the same with Y and Z, I get the same doubling behavior.

**Comment by Haidiye00** [comment]
![哈哈0](https://github.com/user-attachments/assets/981181f1-c893-4148-91b3-4bbacbc7cf8e)
this is my test result

**Comment by DevHyfes** [comment]
Hi @Haidiye00 - In case it matters, the item that was not behaving correctly is a MODIFIER for the main part. It is also an SVG that I imported and flattened. Otherwise, I don't really know what to tell you. I just loaded up again, imported the file, and tried moving it by entering 0 into the Z field and hitting enter...it goes to a random space. TODAY the behavior is, if I enter 0 into the Y field, the Z field doubles, and if I enter 0 into the Z field, the Y field doubles. I am able to work around it by Centering the modifier but I cannot do precision placements, which is annoying.

**Comment by Haidiye00** [comment]
Sorry，at present, there should exist a bug in your version, which can be resolved by manually dragging the arrow. Please wait for the new version to upgrade this feature.

**Comment by DevHyfes** [comment]
Thanks for the update!

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
