### ISSUE TITLE
Color Painting Tool - Cannot Unselect Height Range

### ISSUE THREAD

**Issue by Wingeddonkey** [bambulab/BambuStudio#4871]
### Bambu Studio Version

1.9.2.57

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro, 22H2

### Printer

Bambu Carbon X1

### How to reproduce

Press N
Ensure dropdown menu overlaps printed object
Select Height Range
Select Fill tool (Unable)

### Actual results

When the dropdown menu for paint, overlaps the object to be painted, the menu is not treated as the highest clickable action. Rather the height tool remains priority. 
Unless you move the object around so the menu doesnt overlap the painted object, you cannot unselect the height tool. 

### Expected results

Ability to select new tool option or paint color.

### Project file & Debug log uploads

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
We have identified and fixed this issue in our internal version. Thank you for your discovery~

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
