### ISSUE TITLE
404 for Calibration Tutorial on Non-Bambu printers

### ISSUE THREAD

**Issue by jonathanweinberg** [bambulab/BambuStudio#4872]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

CPU: 3900x
RAM: 64GB DDR4
GPU: EVGA 3090

### Printer

Creality CR-10 (any non-Bambu printer it seems)

### How to reproduce

1. Open Bambu Slicer
2. When on a "Prepare" stage observe the Calibration button:
![image](https://github.com/user-attachments/assets/c1e9209f-b564-4e66-98ef-9897fb0a87a2)
3. Click "Tutorial" choice.
![image](https://github.com/user-attachments/assets/fbec7fae-c4ba-47a1-8ac1-667fe5eb9f23)
4. Should open your default browser and bring you to: `https://wiki.bambulab.com/en/bambu-studio/Calibration` which is a dead end.

### Actual results

Should lead to a valid page versus what is show in this picture.

![image](https://github.com/user-attachments/assets/16a9803a-9885-433a-b1ce-9102712015b2)

### Expected results

Should lead to a real page. Or the option should be eliminated.

I would note that Bambu Slicer has been the gateway to me considering buying actual Bambu printers, so it's support for other models has been appreciated.

### Project file & Debug log uploads

N/A
[debug_Sun_Sep_22_14_31_47_63668.log - Copy.zip](https://github.com/user-attachments/files/17090880/debug_Sun_Sep_22_14_31_47_63668.log.-.Copy.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
Thanks for your feedback, it has been fixed. Please try again
