### ISSUE TITLE
Incorrect calculation of filament usage

### ISSUE THREAD

**Issue by kenni** [bambulab/BambuStudio#4873]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Additional system information

N/A

### Printer

Bambu Lab P1S

### How to reproduce

1. Slice all plates and look at the pop-up window.

### Actual results

The calculation of "Support filament total" is incorrect, it is just a copy of the "Model filament total", as seen in the picture below. This means that the total of everything also is wrong.

<img width="279" alt="image" src="https://github.com/user-attachments/assets/6284079d-d76d-4ed7-bdd6-e7680dacced1">

### Expected results

The Support filament total should have been 11.88g+1.14g+0.83g = 13.85g.

### Project file & Debug log uploads

Sorry, but I do not have permission to share the 3D models. If you cannot replicate the issue, I will see if I can replicate it myself with a non-sensitive 3D model. EDIT: Actually, you have already replicated the issue yourself, just look at the screenshot in your 1.9.7 release notes:

<img width="373" alt="image" src="https://github.com/user-attachments/assets/56c2169d-837c-4d35-beca-62d2465b9867">

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
Please visit the website at https://github.com/bambulab/BambuStudio/releases and try again.
