### ISSUE TITLE
Slicer issue

### ISSUE THREAD

**Issue by Ambu121** [bambulab/BambuStudio#4876]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Home Version 23H2 build 22631.4169 Windows Feature Experience Pack 1000.22700.1034.0

### Additional system information

Prozessor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installierter RAM	16,0 GB (15,9 GB verwendbar)
GPU RTX 3070 mobile
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

### Printer

Bambu Lab P1S with AMS

### How to reproduce

1. select default 0.2 mm profile
2. slice file
3. at layer 20 4mm crossing line through object

### Actual results

![prepare_view](https://github.com/user-attachments/assets/e2ac38c3-d3ef-4236-b39c-7ac9a24fcecb)
![preview_1](https://github.com/user-attachments/assets/64da7c9e-f23e-463d-805d-a6a203d12774)
![preview_2_gcode](https://github.com/user-attachments/assets/53b61515-7a1b-4b76-9a02-b7767ba4b2d9)

### Expected results

no crossing line through object :)

### Project file & Debug log uploads

[project_files.zip](https://github.com/user-attachments/files/17094056/project_files.zip)
[log_files.zip](https://github.com/user-attachments/files/17094076/log_files.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by QingZhangBambu** [comment]
![image](https://github.com/user-attachments/assets/b6a59354-2b57-484d-9b69-37f238f84b8e)
@Ambu121 it had been fixed , and will release in next version. please waiting

**Comment by Ambu121** [comment]
@QingZhangBambu Thank you !

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
