### ISSUE TITLE
UI, modal window in Home/Recently Opened Files, "ok" instead of "yes" or "ja" (german)

### ISSUE THREAD

**Issue by maxmax3** [bambulab/BambuStudio#488]
Clicking on a missing file opens up a modal window with a yes-button (ja-button in german).
Here you should read a ok (instead of "yes" or "ja" (german)).

![Bildschirmfoto 2022-10-22 um 07 42 30](https://user-images.githubusercontent.com/93734796/197322853-ff2a63ac-f389-4414-b952-ceefb096cdee.png)

**Comment by YifanWuBambu** [comment]
This is fixed in v1.4.
