### ISSUE TITLE
支撑统计不准确

### ISSUE THREAD

**Issue by TinCivil** [bambulab/BambuStudio#4881]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win10

### Additional system information

CPU: Intel i5-12400
内存:16GB
GPU: Intel Graphics 730

### Printer

P1S

### How to reproduce

1.点击预览
2.点击所有打印板统计
3.即可发现支撑统计的重量和耗材长度不准确

### Actual results

![20240924094312](https://github.com/user-attachments/assets/dbe29623-8b72-4eb0-b1da-99287233f3f2)

### Expected results

![20240924100748](https://github.com/user-attachments/assets/6b3f7a34-31e5-4348-8e31-74b9d2ca68a8)

### Project file & Debug log uploads

[Uploading 1.zip…]()

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by LiZ-Li-BBL** [comment]
我们已经修复此问题，请等待下个版本

**Comment by LiZ-Li-BBL** [comment]
#4879

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
Please visit the website at https://github.com/bambulab/BambuStudio/releases and try again.
