### ISSUE TITLE
Missbehavior when cutting parts

### ISSUE THREAD

**Issue by Sectorchan** [bambulab/BambuStudio#4882]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Win 10

### Additional system information

Ryzen 7 5800x3d
32GB RAM
RTX 4080

### Printer

A1

### How to reproduce

![image](https://github.com/user-attachments/assets/c7973730-efdf-4f91-9891-ef7eb0f77890)
This object shall be cutted 1mm above the plate (Since multiple object can not be cutted at a single time)
![image](https://github.com/user-attachments/assets/7fcc08f1-58d3-412e-9165-abbf74705a38)
I dont need the blue part. Then I press Perform cut.
![image](https://github.com/user-attachments/assets/d7ec7a75-77f1-4b3d-8061-4207f910ce50)
Now the Part is below the other object, this shoulnt happpen.

### Actual results

See above

### Expected results

I expect that the part is not moved.
OrcaSlicer behaves like that:
![image](https://github.com/user-attachments/assets/94f4328d-f3a4-4ddc-8797-813fd9cd07c1)
![image](https://github.com/user-attachments/assets/18b4d986-3cbd-4f92-867f-2a6d8e517419)
![image](https://github.com/user-attachments/assets/d26aefaf-8728-4e11-af10-b126d3b5cf4e)

### Project file & Debug log uploads

[object.zip](https://github.com/user-attachments/files/17113184/object.zip)
[debug_Mon_Sep_23_15_52_16_15100.log.zip](https://github.com/user-attachments/files/17113224/debug_Mon_Sep_23_15_52_16_15100.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
Hello, could you please record a GIF? Thank you? Facilitate us to reproduce the problem and solve it

**Comment by Sectorchan** [comment]
![orca](https://github.com/user-attachments/assets/8fc2ac4a-2aa0-43da-bc34-3304c553fb5a)
This is from Orcaslicer

![bambu2](https://github.com/user-attachments/assets/5951c43f-e0da-4c9f-bf5e-e72f4ce3eddc)
This is from Bambu

**Comment by Haidiye00** [comment]
can i get your 3mf?

**Comment by Haidiye00** [comment]
I understand, thank you

**Comment by Sectorchan** [comment]
Glad I could help!

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/c2d4f447-6e2f-473e-8a43-e311858a924d)
Thank you, we will make improvements. At present, you can hook the cut to parts and then delete the parts you don't want without changing their position.

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
