### ISSUE TITLE
UI, german localization, “preferences“ 

### ISSUE THREAD

**Issue by maxmax3** [bambulab/BambuStudio#489]
In german you should read "Einstellungen …" rather than “Vorlieben".

![Bildschirmfoto 2022-10-22 um 07 56 52](https://user-images.githubusercontent.com/93734796/197323096-9e28072a-d653-4f7e-aa73-321db20f36b0.png)

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
