### ISSUE TITLE
Bambu Studio not downloading and opening the project from Online Model section

### ISSUE THREAD

**Issue by ripjojon** [bambulab/BambuStudio#4892]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Edition	Windows 11 Pro Version	23H2 Installed on	‎05-‎Apr-‎23 OS build	22631.4169 Experience	Windows Feature Experience Pack 1000.22700.1034.0

### Additional system information

Device name	SCAR-G16
Processor	13th Gen Intel(R) Core(TM) i9-13980HX   2.20 GHz
Installed RAM	32.0 GB (31.6 GB usable)

System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

### Printer

Bambu Lab A1

### How to reproduce

1. Click on Online Models
2. Select a model (Led Lamp 001)
3. Select Print Profile (in my case A1)
4. Select a variant (ex. Type A)
5. Click on Download and Open
6. 
![image](https://github.com/user-attachments/assets/9f447977-f7c3-4a84-9fc1-5ea77e36e15e)

7. Login window appears showing my user name already logged in the Bambu Studio
8. Two options are shown "Continue to Bambu Studio" and "Log Out"
9. Click on "Continue to Bambu Studio"
![image](https://github.com/user-attachments/assets/498b1a58-e0fc-4517-b850-67e595993081)

11. A pop-up window appears with "Syncronization" with following message:

_Do you want to synchronize your personal data from Bambu Cloud? 
It contains the following information:
1. The Process presets
2. The Filament presets
3. The Printer presets__

12. Two options are shown "Yes" and "No"
13. Click on "Yes"
14. 
![image](https://github.com/user-attachments/assets/e290e63e-0c23-4f70-a331-267a0dc1f53a)

15. Nothing is happening. Pop-up window disappears and you are returned to initial window.
16. 
![image](https://github.com/user-attachments/assets/9bde1162-f902-40c7-83f6-d55d3ac7d664)

### Actual results

All process decribed above.

### Expected results

Model should be opened in Bambu Studio

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/17130722/log.zip)

### Checklist of files to include

- [x] Log file
- [ ] Project file

**Comment by ripjojon** [comment]
Just a short update.
The same Issue is occurring no matter what model I choose.

**Comment by ttt888zzz** [comment]
HI [ripjojon](https://github.com/ripjojon)：Please have a try according the following steps.
![image](https://github.com/user-attachments/assets/f07c3ef4-1592-483a-a1c7-1d4f6c2811c3)
![image](https://github.com/user-attachments/assets/32516ebd-3a50-4b0e-8abc-c0f7e27a2d25)

**Comment by ripjojon** [comment]
Hi @ttt888zzz ,

After implementing your proposed solution issue seems to be resolved.
It also happened a few times randomly after checking that option, but 90% of tries it works and the login window does not appear.

Thank you,
Ionut
