### ISSUE TITLE
Random Access violation when slicing

### ISSUE THREAD

**Issue by TennisRunner** [bambulab/BambuStudio#4898]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

p1p

### How to reproduce

Load model, slice.
Maybe change the support top z distance to 0.0 and 0.2.
Its inconsistent. 

### Actual results

Access violation crash. Sometimes crashes with no error message at all. 

[capture-9_25_2024 7-52 PM.webm](https://github.com/user-attachments/assets/0a6128e0-6bde-4a60-9008-3dff119b3715)

### Expected results

Shouldn't crash.

### Project file & Debug log uploads

[rounded-mid-floater.zip](https://github.com/user-attachments/files/17140064/rounded-mid-floater.zip)
Not including dump file since it contains too much personal info.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by DRA6N** [comment]
I had the same issue happening. Had to roll back to previous version, ultimately switched to Orca and never looked back.

**Comment by QingZhangBambu** [comment]
@TennisRunner it had been fixed, and will released in next version, please waiting
![image](https://github.com/user-attachments/assets/d575c640-0eb7-49cb-9ee2-ed89e91370df)

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
