### ISSUE TITLE
UI, window "unsaved changes", text overflow in german version

### ISSUE THREAD

**Issue by maxmax3** [bambulab/BambuStudio#490]
In the window "Closing application: unsaved changes" there's text missing / overflow in the german version, see second line. 

![Bildschirmfoto 2022-10-22 um 07 56 11](https://user-images.githubusercontent.com/93734796/197323236-ca1d2d34-4fe7-4dbd-800c-8d77ceb99af7.png)

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
