### ISSUE TITLE
Support for ABS will recognize as ABS

### ISSUE THREAD

**Issue by QuokeCola** [bambulab/BambuStudio#4900]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 10

### Printer

Bambu X1C

### How to reproduce

1. Load bambu support for ABS in AMS.
2. Go to support and enable support.
3. When choosing filament for supports, the material selection for bambu support for ABS turns to ABS.
![image](https://github.com/user-attachments/assets/6af8fec9-e2ce-4af4-95af-6c4586a8c152)
1. 在AMS中安装ABS支撑耗材的料盘
2. 进入支撑界面，在耗材选择界面，支撑耗材显示为ABS而不是Sup.ABS (PLA支撑耗材显示正常)
3. 切片之后，支撑耗材也被识别为ABS耗材。

### Actual results

This file is printable from bambu studio since it treat the ABS and support for ABS as one material.
![image](https://github.com/user-attachments/assets/e791cf74-f9cf-4664-95f0-a76e91b2f994)

But it cannot be printed again through the x1c screen, since AMS is able to correctly recognize the support for ABS filament, and X1C treat ABS and support for ABS as two different material.

切片之后，支撑耗材也被识别为ABS耗材。
在Bambu Studio中，由于bambustudio觉得sup.ABS为ABS，在打印界面可以选择slot3中的支撑耗材打印进行打印。
然而在X1C触控屏界面，由于AMS不觉得sup.ABS和ABS是同一种材料，不可选择slot3中的耗材进行打印。

### Expected results

Bambulab is able to treat the support for PLA correctly. In material selection interface, the filament is treated as Sup.PLA

![image](https://github.com/user-attachments/assets/7dea7c1a-f031-44c8-8811-f30748a7705a)

Support for ABS should have similar behavior, in bambu studio it should be treated correctly as Sup.ABS but not ABS.

ABS支撑耗材应该与PLA支撑耗材一样，在bambustudio中被正确识别。

### Project file & Debug log uploads

[astranaut.zip](https://github.com/user-attachments/files/17143021/astranaut.zip)

### Checklist of files to include

- [x] Log file
- [X] Project file

**Comment by XunZhangBambu** [comment]
@QuokeCola  Thanks for the feedback. Will fix the issue soon

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.

**Comment by lumbduck** [comment]
I still have this issue on the latest release in May 2025. Support for ABS is not accessible from the X1C screen, where it believes that ABS has been designated. Workaround is to use 3rd party support material so that the AMS doesn't recognize it, but I would love to have this working correctly
