### ISSUE TITLE
Total suppport filament is wrong

### ISSUE THREAD

**Issue by zmindless** [bambulab/BambuStudio#4906]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu X1C

### How to reproduce

not sure, try using 12 plates and slice all, used 3 materials

### Actual results

![image](https://github.com/user-attachments/assets/0d1bf0ca-1d5c-49ec-acb2-fd783e492f6b)
support total is just copy/paste from model total

### Expected results

support total is actual total of all support listed above

### Project file & Debug log uploads

[Issue.zip](https://github.com/user-attachments/files/17163121/Issue.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by LiZ-Li-BBL** [comment]
Same as https://github.com/bambulab/BambuStudio/issues/4879

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
Please visit the website at https://github.com/bambulab/BambuStudio/releases and try again.
