### ISSUE TITLE
bambu studio 生成树形支撑后出现路径冲突且未报错

### ISSUE THREAD

**Issue by ORNAU** [bambulab/BambuStudio#4907]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Printer

A1

### How to reproduce

1、放置两个相近的模型
2、选中其中一个生成树形支撑

### Actual results

支撑有可能生成在另一个模型的内部，且没有任何警告或提示
![屏幕截图 2024-09-27 211939](https://github.com/user-attachments/assets/bf42665b-432c-42d8-8eaa-e5ce3ec32e8c)
![MVIMG_20240927_211022](https://github.com/user-attachments/assets/1238a83d-e007-45ef-a1b6-21058df72773)

### Expected results

切片软件本应生成不与其他模型重叠的支撑，或者生成后检测路径冲突以提示操作者进行修改

### Project file & Debug log uploads

[generated files with wrong support_2024_09_27.zip](https://github.com/user-attachments/files/17164800/generated.files.with.wrong.support_2024_09_27.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
路径冲突检查没检查出来，估计是阈值问题，这个case里重叠的很少。我尝试调一下阈值。

**Comment by tangketan** [comment]
2.0版本里已经支持了可变层高对象的冲突检测
