### ISSUE TITLE
Slicing issue (.stl attached)

### ISSUE THREAD

**Issue by daibaron** [bambulab/BambuStudio#4908]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 pro

### Printer

X1C + AMS

### How to reproduce

stl is attached

### Actual results

not slicing

### Expected results

to be printed 

### Project file & Debug log uploads

[123.zip](https://github.com/user-attachments/files/17165023/123.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
Please try the following steps，https://wiki.bambulab.com/en/bambu-studio/troubleshoot/win-crash-when-slicing
