### ISSUE TITLE
Added Anycubic i3 Mega

### ISSUE THREAD

**Issue by goldjunge91** [bambulab/BambuStudio#491]
Hi guys 
i like the slicer but i have a Anycubic i3 Mega with klipper and some mods so for this i create all files for my printer but start with a copy of the ender 3 so for this people that want Add Anycubic i provide the base settings to implement and a little Workaround.
I added as Hotend stock V6 if you need i can upload V5
i create a repo for my custom Profiles. https://github.com/goldjunge91/BambuStudio_Custom_printer
[anycubic_i3mega_configs.zip](https://github.com/bambulab/BambuStudio/files/9844070/anycubic_i3mega_configs.zip)
_**(i install BambuStudio standard windows folder: "C:\Program Files\Bambu Studio"**_
**Importend Directorys:**
_...\Bambu Studio\resources\profiles_
_...\Bambu Studio\resources\web\image\printer_
for Troubleshot
_...\AppData\Roaming\BambuStudio\system_
### How To:
1. Unzip the files in a new folder.
2. Copy the folder "**Anycubic**" & the File "**Anycubic.json**"  to "**C:\Program Files\Bambu Studio\resources\profiles**" (if you have like me the standard windows folder you can use my string)
3. Copy "**Anycubic I3Mega_cover.png**" to "**C:\Program Files\Bambu Studio\resources\web\image\printer**"
4. finished.

### Troubleshoot 
If you have any trouble to open after this BambuStudio then follower this;
1. go to "**C:\Users\"your username"\AppData\Roaming\BambuStudio\system**"
or
Click Start, go to Run, type in **%appdata%**, and press Enter
Press Win+R, type in %appdata%, and press Enter
(copy from: https://superuser.com/a/1039202 )
_you have to find Appdata/Roming folder._
2.then Remove Anycubic folder and Anycubic.json
3.Done run BambuStudio

in Case you want to make changes to the printer settings 
Print area: Anycubic I3Mega 0.4 nozzle.json search "printable area":[ her you can change your size 
Machine settings: fdm_Anycubic_common.json

**Comment by SaltWei** [comment]
Thanks for suggestions. Already included in latest version.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/3d617520-799e-4dc4-945d-dd9e2824bd90)
Thank you again for good suggestions!
