### ISSUE TITLE
材料统计bug

### ISSUE THREAD

**Issue by clan4456** [bambulab/BambuStudio#4911]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases

### OS version

win11

### Printer

P1SC

### How to reproduce

1、切片所有盘
2、统计材料结果出错，支撑用料总计出错。
![image](https://github.com/user-attachments/assets/cf85dc9d-9174-4384-a158-463024a8411b)

### Actual results

![image](https://github.com/user-attachments/assets/cf85dc9d-9174-4384-a158-463024a8411b)

### Expected results

支撑用料总计应为99.83g

### Project file & Debug log uploads

[可达鸭组装图.zip](https://github.com/user-attachments/files/17173759/default.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by LiZ-Li-BBL** [comment]
已修复此问题 https://github.com/bambulab/BambuStudio/issues/4879

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
Please visit the website at https://github.com/bambulab/BambuStudio/releases and try again.
