### ISSUE TITLE
Live View: Player is Malfunctioning. Please reinstall the system player [2:2]

### ISSUE THREAD

**Issue by Mr-121** [bambulab/BambuStudio#4919]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 15.0

### Additional system information

Intel CPU

### Printer

X1C

### How to reproduce

Just updated the Bambu Lab Studio

### Actual results

Live view on Studio not working but works on Handy.

### Expected results

Live view should still work on Mac.

### Project file & Debug log uploads

<img width="1538" alt="Screenshot 2024-09-30 at 6 24 31 pm" src="https://github.com/user-attachments/assets/b060f2f2-5de6-4bf0-885a-db5a9647b7e3">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by jebabi** [comment]
This is because you havn't allowed Bambu Studio access to your local network.
After updating to MacOS 15.0 it probably asked you the first time launching Bambu Studio. 

You can fix this by:
System Setting -> Privacy & Security -> Local Network

**Comment by Mr-121** [comment]
You are right! Thanks!

**Comment by Mr-121** [comment]
Maybe you guys can improve the error code to be more clear in next update. Thank you!

**Comment by peteramelang** [comment]
Did not help. I have also deleted everything from Application Support and reinstalled BambuStudio and the network driver.

I can watch the video feed or access the SD card from my Mac.
No issues with access through the mobile app.

**Comment by IOIO72** [comment]
It doesn't work on one of my Macs as well.
Both have version 1.10.1.50 installed.
Both are running macOS Sequoia 15.2.
On both machines BambuLab has access to the local network.

It runs on my M1 Mac Mini.
It doesn't run on my M2 MacBook Pro 2023.

**Comment by 3driffs** [comment]
Ditto here, and it is enabled.

**Comment by andypiper** [comment]
On 15.2 if I disable the default macOS firewall, the camera works - I can access it in the Preview in Bambu Studio (although Go Live is not working). If I enable the firewall, it shows this error about the camera malfunctioning.

**Comment by garglebutt** [comment]
Same issue.

**Comment by DrMaRV** [comment]
It's 100% macOS internal firewall, a have the same issue. As I've disabled macOS firewall in network settings the camera stream worked instantly.
My system:
iMac late 2017
macOS 15.2
BambuLab Studio 1.10.1.50

**Comment by garglebutt** [comment]
So Bambu Studio needs to add code to seek appropriate permissions. Not hard to do given every other piece of software I have seems to manage.

**Comment by bobg2023** [comment]
This ticket is closed I think a new one needs to be created. My firewall is permitting all inbound traffic to bambustudio. Perhaps the video stream is a different process?

**Comment by andypiper** [comment]
I wondered the same thing (the stream being a different process). I added all of the Bambu processes/binaries to the firewall allowlist and it did not help, and I cannot tell from the logs what the issue is here.

**Comment by bobg2023** [comment]
I just got some weird response from bambu support telling me to enable webstorm which is a programming IDE in local network access permissions.  I don’t even have that installed, what on earth does that have to do with the live view

**Comment by martin2149** [comment]
I have a support ticket open for this issue as well, Apple M2 pro, Sequoia 15.2. 
It was working as expected and suddenly stopped, I can view camera on iPhone with no issue

**Comment by dmrolyat** [comment]
I have same problem. Disabling firewall immediately resolves the camera problem

**Comment by pranasziaukas** [comment]
Same here, the camera only works if the macOS Firewall is disabled, which I'm not willing to do.

**Comment by bobg2023** [comment]
> Same here, the camera only works if the macOS Firewall is disabled, which I'm not willing to do.

If you haven't yet please raise a ticket with bambu labs support.

**Comment by FlyMarc2** [comment]
> Same here, the camera only works if the macOS Firewall is disabled, which I'm not willing to do.

Same thing for the access to the MicroSD Card. (MacBook Pro 2018 (intel) and MAC OS Sequoia 15.2)

Made a support ticket. I hope they will solve the problem soon!

**Comment by c0desurfer** [comment]
Why is this closed? This issue still persists.

**Comment by bobg2023** [comment]
> Why is this closed? This issue still persists.

Because someone said turning off the firewall fiixes it and someone with little intelligence thought that was an appropriate fix

**Comment by c0desurfer** [comment]
At least this one is open and it's the same issue.
https://github.com/bambulab/BambuStudio/issues/5642

**Comment by Kpoole4u** [comment]
I lost video as well and now have it back....! 

I went into System Settings / Privacy & Security / Local Network. I turned off BambuStudio and then immediately back on. It is now working. I am using macOS Sequoia 15.1.1

**Comment by bobg2023** [comment]
I've tried turning it off an on again more than once and it doesn't fix it

**Comment by IOIO72** [comment]
@Mr-121 I think, this issue should be re-opened.

**Comment by c0desurfer** [comment]
> I lost video as well and now have it back....!
> 
> I went into System Settings / Privacy & Security / Local Network. I turned off BambuStudio and then immediately back on. It is now working. I am using macOS Sequoia 15.1.1

Yes, but after updating to 15.2 (24C101) this doesn't work anymore.

**Comment by kocour** [comment]
I can confirm that the same problem is on MBA M3 with 15.2 (24C101). Turning off integrated firewall will temporary fix the problem, but it's not solution at all, just absolutely terrible workaround. Obviously the problem is in the application itself and it should be updated for compatibility with 15.2

**Comment by guinnberg** [comment]
Something odd is happening here. Yesterday it wasn't working as usual, I accidentally opened a second instance of Bambu Studio and kept working for the whole day. Now today I opened Bambu Studio again and no matter what I do, it doesn't work

**Comment by just-mitchin** [comment]
Having the same problem after updating to 15.2 on a MBP M3. The only thing that works is to turn off the firewall. No issues on my iPhone app or Windows based PC.

**Comment by bobg2023** [comment]
> Having the same problem after updating to 15.2 on a MBP M3. The only thing that works is to turn off the firewall. No issues on my iPhone app or Windows based PC.

Make sure you raise a support request with Bambu if you haven’t

**Comment by FlyMarc2** [comment]
I have received another reply from Bambulab: 

> Hello,
> We apologize for the unpleasant experience. Could you please also disable any VPN or content filter you are using to see if there is any progress? There are reports that the Little Snitch filter may be causing this issue
> ![Bild 12 01 25 um 11 14](https://github.com/user-attachments/assets/e950c8c4-b1be-465b-b3bc-3ce2033af423)
> Please feel free to contact us if you have any further questions.
> Best regards,
> Bambu Lab Customer Support
> 

It worked for me. Instead of Little Snitch, I have Trip Mode. After deactivating it, I had access to the live image and the SD card again. This is not a permanent solution either, but it is definitely better than switching off the firewall.
<img width="813" alt="Bildschirmfoto 2025-01-12 um 10 35 04" src="https://github.com/user-attachments/assets/2d89863b-c288-4764-9eea-da0dd81a11c9" />

**Comment by just-mitchin** [comment]
> I have received another reply from Bambulab:
> 
> > Hello,
> > We apologize for the unpleasant experience. Could you please also disable any VPN or content filter you are using to see if there is any progress? There are reports that the Little Snitch filter may be causing this issue
> > ![Bild 12 01 25 um 11 14](https://private-user-images.githubusercontent.com/128502701/402347835-e950c8c4-b1be-465b-b3bc-3ce2033af423.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MDk3NTYsIm5iZiI6MTczNjcwOTQ1NiwicGF0aCI6Ii8xMjg1MDI3MDEvNDAyMzQ3ODM1LWU5NTBjOGM0LWIxYmUtNDY1Yi1iM2JjLTNjZTIwMzNhZjQyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxOTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWJhMjE1YzIyNjY2NGFjYjRlMjdmZGU4YjMxYmYyOGJlMDk2NGRiYWExYzc4ZDUwZGZmZTkwNmM1YjNhYmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cXVFFvhgxkVVwaQLFO6OODYjRA9TCSFwd_2lRqmI9Wo)
> > Please feel free to contact us if you have any further questions.
> > Best regards,
> > Bambu Lab Customer Support
> 
> It worked for me. Instead of Little Snitch, I have Trip Mode. After deactivating it, I had access to the live image and the SD card again. This is not a permanent solution either, but it is definitely better than switching off the firewall. <img alt="Bildschirmfoto 2025-01-12 um 10 35 04" width="813" src="https://private-user-images.githubusercontent.com/128502701/402348143-2d89863b-c288-4764-9eea-da0dd81a11c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MDk3NTYsIm5iZiI6MTczNjcwOTQ1NiwicGF0aCI6Ii8xMjg1MDI3MDEvNDAyMzQ4MTQzLTJkODk4NjNiLWMyODgtNDc2NC05ZWVhLWRhMGRkODFhMTFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQxOTE3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDIxYmIxZmRhZThmNDNlOTdmM2M4YzdlYmVlZGM1Y2EzNzBhMzI3NTQ1YzFlNjEzNzdhZGMyZjkwNGZmZDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xBNSRaEBZHXLyQFNHGUblOitLWCM0tzDE2kEsSNUpkY">

Thanks! This worked for me. I have a Cisco VPN  installed and it now works with it being disabled.

**Comment by IOIO72** [comment]
> I have received another reply from Bambulab:
> 
> > Hello,
> > We apologize for the unpleasant experience. Could you please also disable any VPN or content filter you are using to see if there is any progress? There are reports that the Little Snitch filter may be causing this issue
> > ![Bild 12 01 25 um 11 14](https://private-user-images.githubusercontent.com/128502701/402347835-e950c8c4-b1be-465b-b3bc-3ce2033af423.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NzY2MTAsIm5iZiI6MTczNjc3NjMxMCwicGF0aCI6Ii8xMjg1MDI3MDEvNDAyMzQ3ODM1LWU5NTBjOGM0LWIxYmUtNDY1Yi1iM2JjLTNjZTIwMzNhZjQyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxMzUxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmViYzU0ZGQyYzdmOGYyZTFmZTAyNGE4MGU4N2I3YjMwODg2NWJiOTBhYzc0YmQ3OGNmNTE5MzUzYjMyMDZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fINGWOx3EXYAMwIrY_TPfhn7n1wx5WwdTMbp_hhopz0)
> > Please feel free to contact us if you have any further questions.
> > Best regards,
> > Bambu Lab Customer Support
> 
> It worked for me. Instead of Little Snitch, I have Trip Mode. After deactivating it, I had access to the live image and the SD card again. This is not a permanent solution either, but it is definitely better than switching off the firewall. <img alt="Bildschirmfoto 2025-01-12 um 10 35 04" width="813" src="https://private-user-images.githubusercontent.com/128502701/402348143-2d89863b-c288-4764-9eea-da0dd81a11c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NzY2MTAsIm5iZiI6MTczNjc3NjMxMCwicGF0aCI6Ii8xMjg1MDI3MDEvNDAyMzQ4MTQzLTJkODk4NjNiLWMyODgtNDc2NC05ZWVhLWRhMGRkODFhMTFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxMzUxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTNmZTlmN2M1NWY5MmMyYjIwZmE2ZjIzNDZhMDY3MmRlNGE3MTkwN2ZjNDEwNzkwZjAzYTY4ZjJkY2UzYmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ve-kwgKwIFt6j-Y_muGCC98KXkfHRBxk61Os9WWES3k">

That was it! I had the TripMode filter active, even though the TripMode app was deleted.

**Comment by garglebutt** [comment]
This is resolved with MacOS 15.3.
