### ISSUE TITLE
Weight for print incorrect

### ISSUE THREAD

**Issue by kianj2005** [bambulab/BambuStudio#4922]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu lab A1

### How to reproduce

1. Add two items that need support 
2. Set two different colours for each
3. Add them to different plates (one colour per plate)
4

### Actual results

After slicing, in the all plates stats you can see the support weight and the model weight are exactly the same, but if you go into the individual plate they're different
![Screenshot 2024-09-30 203535](https://github.com/user-attachments/assets/cf7aa98a-f459-4a0e-8d43-92e82afa8584)

### Expected results

They should be different total weight

### Project file & Debug log uploads

[Untitled.zip](https://github.com/user-attachments/files/17195705/Untitled.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
