### ISSUE TITLE
Split to Object results in a reorientation of the objects

### ISSUE THREAD

**Issue by Sectorchan** [bambulab/BambuStudio#4923]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

A1

### How to reproduce

See the attached GIF

### Actual results

The font "Kurve1 30°" drops from the initial layer into the body below.
See attached GIF

### Expected results

Stay in the same position on top of the body. As an embossed text.

### Project file & Debug log uploads

[embossed text.zip](https://github.com/user-attachments/files/17205559/embossed.text.zip)
[embossed text.zip](https://github.com/user-attachments/files/17205584/embossed.text.zip)
[debug_Tue_Oct_01_12_23_52_18168.log.zip](https://github.com/user-attachments/files/17205602/debug_Tue_Oct_01_12_23_52_18168.log.zip)
![bambu3](https://github.com/user-attachments/assets/152e7370-dc79-4b13-b366-0f774ea8322c)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/d4193f16-825b-47a2-b4ec-90681a05f7f5)
I think it is ok as the split object must be dropped onto the disk. This is the effect of me moving the largest object away.
