### ISSUE TITLE
Wrong plate numbering in Preview Tab

### ISSUE THREAD

**Issue by StephanEhlert** [bambulab/BambuStudio#4925]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

X1C

### How to reproduce

- In Bambu Studio create a project with more than on plate.
- Select Slice All 
- On the left side are all sliced plates visible starting with plate 1.....XX
- The List where you can see how long every plate needs for printig is starting with plate 0 instead of 1 
the list is going from 0....XX 

### Actual results

![Screenshot Bambu](https://github.com/user-attachments/assets/6ec818c8-a2d1-4a56-97be-562476c39c40)
![Screenshot Bambu](https://github.com/user-attachments/assets/6b451495-29ea-4a83-a88a-bdbed95187dc)

### Expected results

Start countig with identical numbers

### Project file & Debug log uploads

[Generator.zip](https://github.com/user-attachments/files/17213186/Generator.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
