### ISSUE TITLE
ASA-CF not recognised by AMS properly

### ISSUE THREAD

**Issue by MechInnovation** [bambulab/BambuStudio#4927]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

Try and load Bambu Lab ASA-CF in the AMS. 

### Actual results

The AMS goes through it's usual routine of loading the filament and then briefly displays (about 7 seconds) ASA-CF correctly, but then the user interface in the printer goes back to a blank slot as if it doesn't know what is loaded.

https://github.com/user-attachments/assets/a189b020-9c91-4efd-b51e-e4558c8ee8e5

### Expected results

It should show the material as normal. 

Also there is no profile in the materials within Studio for the ASA-CF. There seems to be very little information online about ASA-CF and now it makes me very nervous about using it.

I've created a Project file and log file because I can't submit a support ticket without it but they are relevant at this stage because I can't get past the material loading stage. I have also tried loading the filament directly being fed from a spool drier (not via the AMS) and although I can select ASA-CF it again only shows it for a few seconds and then says it doesn't know what it is.

What's going on?

### Project file & Debug log uploads

[debug_Wed_Oct_02_10_11_02_56240.log.zip](https://github.com/user-attachments/files/17227544/debug_Wed_Oct_02_10_11_02_56240.log.zip)
[Bambu Cube.zip](https://github.com/user-attachments/files/17227550/Bambu.Cube.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MechInnovation** [comment]
Please can you sort this out? It makes it look like you want to supply the material but then it's not supported by the ecosystem. I'm very happy to purchase only Bambu filaments, but they need support.

**Comment by SiliciumMan** [comment]
Please navigate to the "Update Configuration" section to ensure your settings are up-to-date. Whenever new materials are released, we will push updates, so if you don't update, you'll be prompted the next time you open the app.

![image](https://github.com/user-attachments/assets/ae2c3b54-4240-46f8-a1aa-0b0515272553)

Making sure your configuration is current will allow you to access the latest features and capabilities. Please take a moment to review and update your settings as needed.
============================
I asked the same question with Bambu customer service. This is their answer.
I checked update, the software is newest. And the ASA-CF profile is not availble in github just now. But it really has a configuration  update in the right below corner.
I click it and get the update. Now it works!

**Comment by MechInnovation** [comment]
Thanks for your reply. I have the latest version of Studio (on PC). Both my X1C and AMS appear to be on the latest version, but I don't get the 'Configuration can update now' box popping up like you have shown in your image. How do I get that? Any help would be very much welcomed :-). I've only had the print for 2 weeks and love it, but this has got me a bit stuck.

**Comment by MechInnovation** [comment]
> Please navigate to the "Update Configuration" section to ensure your settings are up-to-date. Whenever new materials are released, we will push updates, so if you don't update, you'll be prompted the next time you open the app.
> 
> ![image](https://private-user-images.githubusercontent.com/59803970/373528131-ae2c3b54-4240-46f8-a1aa-0b0515272553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDY1ODAsIm5iZiI6MTcyODMwNjI4MCwicGF0aCI6Ii81OTgwMzk3MC8zNzM1MjgxMzEtYWUyYzNiNTQtNDI0MC00NmY4LWExYWEtMGIwNTE1MjcyNTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEzMDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNGQ0YjA3NmUwN2RhODg3MGQ5YWY2NTEyY2IxZWE3ZjU1ODNiOTE0OGY4ZGJlZDM5NzgzZjY2ZDI4Y2EzMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ggR9v4PZr7ZPRUfM5F2DZzly-y4LghQ0hi9w8PruHv8)
> 
> # Making sure your configuration is current will allow you to access the latest features and capabilities. Please take a moment to review and update your settings as needed.
> I asked the same question with Bambu customer service. This is their answer. I checked update, the software is newest. And the ASA-CF profile is not availble in github just now. But it really has a configuration update in the right below corner. I click it and get the update. Now it works!

Mine is working now but I had to reinstall BS and the printer firmware.

**Comment by XunZhangBambu** [comment]
@MechInnovation  Hello,has your issue been resolved ? To ensure filament recognition, you need to make sure that both the studio and the printer have received the new materials package.

**Comment by MechInnovation** [comment]
Yes this has been solved now. I u installed everything and the reinstalled.


Kind regards


Simon


Simon Stone

MechInnovation Limited

7 Enright Close

Leamington Spa

Warwickshire

CV32 6SQ



Mob: +44 (0) 7919 533515



***@***.******@***.***>

www.mechscan.co.uk<http://www.mechscan.co.uk/>

________________________________
