### ISSUE TITLE
Incorrect calculation of total support used in the All Plates Stats tab with multiple plate prints.

### ISSUE THREAD

**Issue by musicalatv** [bambulab/BambuStudio#4946]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Version 23H2

### Additional system information

13th Gen Intel(R) Core(TM) i7-1355U   1.70 GHz
16.0 GB (15.7 GB usable)
64-bit operating system, x64-based processor

### Printer

Bambu X1C

### How to reproduce

See Photo, the support is showing the amount of filament used in the model instead of adding up the amount of support.

![Incorrect calculations of support used](https://github.com/user-attachments/assets/ad37998a-1694-4f0b-b092-ff3614c590a2)

### Actual results

It shows that it needs 11,851g filament for support.

![Incorrect calculations of support used 2](https://github.com/user-attachments/assets/a1235725-e4ab-4ffe-8194-0787241eace2)

### Expected results

It should show about 770g of filament for support instead of 11,851g it shows in the attached print screen.

![Incorrect calculations of support used 2](https://github.com/user-attachments/assets/6590443b-7c8c-4d31-88e0-4995eb8eb22b)

### Project file & Debug log uploads

The zipped project file it too big to include. Zipped it is still 49.1 MB.

![Zipped Project File](https://github.com/user-attachments/assets/400c9d05-a29f-4ee4-a334-742d9569747e)

![Printscreen of project](https://github.com/user-attachments/assets/93e1bdd2-fa2e-4538-a29a-05e17fb01726)

[debug_Fri_Oct_04_22_54_11_62804.log.zip](https://github.com/user-attachments/files/17267581/debug_Fri_Oct_04_22_54_11_62804.log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
