### ISSUE TITLE
CLI: Scaling below 1 doesn't work in CLI 

### ISSUE THREAD

**Issue by uSyzex** [bambulab/BambuStudio#4954]
### Bambu Studio Version

1.9.4.60

### Where is the application from?

Bambu Lab github releases

### OS version

Debian 12

### Printer

X1C

### How to reproduce

Scaling issue has been mostly fixed thanks to @lanewei120 in https://github.com/bambulab/BambuStudio/issues/4628 but it seems there's still some issue persisting. 

When slicing using a value above 1, it works perfectly:
./Bambu_Studio_ubuntu-20.04_PR-4684.AppImage --scale 1.3 --slice 01  --allow-newer-file --outputdir /home/**/Downloads/project_test.3mf --debug 5

But when slicing with a value under 1, it fails no matter the size of the model:
./Bambu_Studio_ubuntu-20.04_PR-4684.AppImage --scale 0.9 --slice 01  --allow-newer-file --outputdir /home/**/Downloads/project_test.3mf --debug 5

### Actual results

[actual.log](https://github.com/user-attachments/files/17279050/actual.log)

See output logs for the scaling at 0.9

### Expected results

[expected.log](https://github.com/user-attachments/files/17279074/expected.log)

See output logs for the scaling at 1.3

### Project file & Debug log uploads

[project_test.zip](https://github.com/user-attachments/files/17279111/project_test.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by uSyzex** [comment]
Additional details:

When scaling and exporting, everything seems to be fine on the model except when you scale up and the model doesn't sit on the bed anymore but this can be fixed with an option.

Works
./Bambu_Studio_ubuntu-20.04_PR-4684.AppImage --scale 1.3 --ensure-on-bed --export-3mf exported.3mf  --allow-newer-file --outputdir /home/hkz/Downloads/orca  project_test.3mf --debug 5

Also works
./Bambu_Studio_ubuntu-20.04_PR-4684.AppImage --scale 0.9 --ensure-on-bed --export-3mf exported.3mf  --allow-newer-file --outputdir /home/hkz/Downloads/orca  project_test.3mf --debug 5

Both exported 3MF can be sliced using the interface and CLI without any issue. 

Works
./Bambu_Studio_ubuntu-20.04_PR-4684.AppImage --slice 01 --ensure-on-bed --export-3mf exported.3mf  --allow-newer-file --outputdir /home/hkz/Downloads/orca  project_test.3mf --debug 5

So the issue seems to be related to how the model is passed processed when going from scaling to slicing in the CLI.

**Comment by lanewei120** [comment]
yes, you need to add "--ensure-on-bed" when scaling below 1, which will cause it not on bed

**Comment by uSyzex** [comment]
> yes, you need to add "--ensure-on-bed" when scaling below 1, which will cause it not on bed

Thank you for your answer, I thought I did test to scale below one / slice / ensure on bed but it seems I didn't, it's working like a charm! 

Thank you again !
