### ISSUE TITLE
The x offset shifts one filament change

### ISSUE THREAD

**Issue by alphastrem** [bambulab/BambuStudio#4960]
### Bambu Studio Version

1.9.7.50

### Where is the application from?

Bambu Lab Official website

### OS version

Mac OS 15.0 (24A335)

### Additional system information

Apple M2 Max 32GB Ram 

### Printer

A1

### How to reproduce

When I print any of my items even a standard cylinder that's split at 50% to change filament colour on my AMS there is a 1mm x Axis shift - this happens on every print no matter the design

### Actual results

once the filament change happens the upper layers shift across on the x axis.
![IMG_0374](https://github.com/user-attachments/assets/cffa3740-1bc4-4385-83de-79211b3a1f43)
![IMG_0373](https://github.com/user-attachments/assets/3576847a-e24b-4eca-b5c3-f0410c99d33e)

### Expected results

for the prints to sit completely flush like they did a few weeks ago. The printer has not move, been damaged, no changes at all. only thing different is the firmware changes

### Project file & Debug log uploads

[Shower-Clamb.3mf.zip](https://github.com/user-attachments/files/17298542/Shower-Clamb.3mf.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by XunZhangBambu** [comment]
@alphastrem  Please use the latest version. This is a known issue in version 1.9.7.50
