### ISSUE TITLE
Reload STL resets location and orientation

### ISSUE THREAD

**Issue by replaysMike** [bambulab/BambuStudio#4969]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu Lab X1 Carbon

### How to reproduce

This was previously reported as fixed/cannot reproduce in issue #910 but it does indeed still occur, as of version 1.9.7.52 - requesting this gets reopened. The reason its an issue is it doesn't reorient all the modifiers and support enforcers so now they are all in the wrong location/orientation.

I should note this doesn't always happen, I'm not sure what causes it to occur. STL's are edited/generated from Blender, with no change in units, orientation or scale.

Before reload:
![image](https://github.com/user-attachments/assets/dcbe48b0-31f2-40c0-9333-6ed2cc6226d7)

After reload:
![image](https://github.com/user-attachments/assets/da5fb4c4-257d-4a9a-b10d-009e14b2202f)

### Actual results

Orientation is flipped on reload

### Expected results

No change in orientation or location

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/17319904/log.zip)
[TopShelf-Right.zip](https://github.com/user-attachments/files/17319905/TopShelf-Right.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by replaysMike** [comment]
Worth noting, closing and re-opening Bambu Studio caused the issue to go away. I was able to reload the model and it kept its orientation this time. So definitely a bug here

**Comment by Haidiye00** [comment]
Can you provide the original STL file and record the process of reproducing it? Thank you

**Comment by replaysMike** [comment]
> Can you provide the original STL file and record a gif for the process of reproducing it? Thank you

I was able to reproduce it again, here's the gif & files.

![BambuStudio_bug-ezgif com-optimize](https://github.com/user-attachments/assets/db6a3921-8690-4ee3-9e18-cb6899278e43)

[STLFiles.zip](https://github.com/user-attachments/files/17422911/STLFiles.zip)
* Zip contains the project file, previous model, and replacement model (though it's not the model, restarting Bambu Studio fixes the problem)

**Comment by Haidiye00** [comment]
![哈哈0](https://github.com/user-attachments/assets/0e26d3d8-eb22-4910-9349-a592487e93d1)
Thank you for your discovery. We have identified the issue. thank you

**Comment by Haidiye00** [comment]
Hello, 1.10 beta2 has been released. Please download and use it. Thank you~
