### ISSUE TITLE
Flathub verification

### ISSUE THREAD

**Issue by secretmango** [bambulab/BambuStudio#4975]
![image](https://github.com/user-attachments/assets/afa73520-6aeb-4f0b-bf0d-314733864af6)

Reading your README, I understood that you build the Flatpak, which is great!

Could you do a Flathub verification process, to remove that dangerous sign? There are also people using the `subset=verified` Flathub repo, which would only then get your app displayed.

The docs on how to do verification [are here](https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified) and it looks like simply some app author needs contributor rights to the [Flathub Github repo](https://github.com/flathub/com.bambulab.BambuStudio) which is maintained by @hadess it seems, so this should work.

**Comment by hadess** [comment]
> The docs on how to do verification [are here](https://docs.flathub.org/docs/for-app-authors/verification#im-publishing-an-app-on-flathub-how-do-i-get-it-verified) and it looks like simply some app author needs contributor rights to the [Flathub Github repo](https://github.com/flathub/com.bambulab.BambuStudio) which is maintained by @hadess it seems, so this should work.

Both @lanewei120 and @MackBambu already have access to the Flathub repo. I provided them with the information about verification back in January. Hopefully some work will be done on this soon, it's such a shame to miss out on verification when all the authorisations are already here.

**Comment by MackBambu** [comment]
![image](https://github.com/user-attachments/assets/41367d49-0775-42b5-a490-58c8af136797)
The verification has just been completed
