### ISSUE TITLE
Wrong Filament Usage

### ISSUE THREAD

**Issue by Parceval4482** [bambulab/BambuStudio#4976]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

P1P

### How to reproduce

I have several printing plates in the Bambustudio and in the preview tab on the All Plates Stats the total amount of filament used is not correct. 2 pieces are there. Filament 1 is support filament and filament 2 is for the print object. 

In the total amount required section, the same amount is shown for the supports as for the model.

In my case: 
Total 
Model: 367.99g and 121.42m 
Supports: 367.99g and 121.42m

Supports filament 1 + 2:
added together by me: 10.32g+36.3g = 46.62g <<< That should actually be in Total.

This also results in a total filament requirement of 845.58g and not 414.61g

Translated with DeepL.com (free version)

### Actual results

![image](https://github.com/user-attachments/assets/d6ec3b82-fae4-4856-8a99-3a75f48979dd)
![image](https://github.com/user-attachments/assets/d97a5219-b9a7-4e86-9f3d-2e246276aac7)

### Expected results

Correct Filament usage

### Project file & Debug log uploads

[Stargate first Parts Plate 5-8.zip](https://github.com/user-attachments/files/17331797/Stargate.first.Parts.Plate.5-8.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
I'm Sorry.The value of the support material is not displayed correctly, the internal version has been fixed. A new version will be released in the near future.

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
 Please visit the website  at https://github.com/bambulab/BambuStudio/releases and try again.
