### ISSUE TITLE
slicing defect

### ISSUE THREAD

**Issue by koob7** [bambulab/BambuStudio#5007]
### Bambu Studio Version

1.9.7.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Additional system information

Ryzen 5 4600h
rtx2060
16gb ram
lenovo legion 5

### Printer

A1 standard

### How to reproduce

Slicing object from my google drive folder object has some struggle string. They are not a part of stl file. I tried with different slicing preset and effect is still same. Please follow the link to get stl file and screen shots with problem. https://drive.google.com/drive/folders/107qepqyJLgxjc0FJ1j0UhfgfMx6v1d_c?usp=sharing

### Actual results

![Zrzut ekranu 2024-10-15 210401](https://github.com/user-attachments/assets/a962ebe6-7cac-4445-ab03-9b19c5c3946c)
![Zrzut ekranu 2024-10-15 210034](https://github.com/user-attachments/assets/3669618e-805d-47a7-afb7-d2d2bdfce8f7)

### Expected results

there should not be this extra string
![Zrzut ekranu 2024-10-15 210105](https://github.com/user-attachments/assets/8fd7353f-36f6-4e5d-af4f-3730d36942cc)

### Project file & Debug log uploads

[Bryła1.zip](https://github.com/user-attachments/files/17383344/Bryla1.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
1.Visit website: https://github.com/bambulab/BambuStudio/releases
2.Choose one of the following installation packages to install.
![image](https://github.com/user-attachments/assets/5d092ccd-4887-41fe-a72d-afca5365ef0c)
3.Try again.

**Comment by QingZhangBambu** [comment]
the latest version has fixed that, please try it.
