### ISSUE TITLE
Slicer error on AMS multi-color part, dependent on part orientation

### ISSUE THREAD

**Issue by OlegTheMighty** [bambulab/BambuStudio#501]
I posted this in the Discord server and someone suggested that I add it here.
I printed these jeep toys in PLA which worked great, except that 18 of the 20 parts had some blue lines through the gray windows. All 18 parts were rotated the same direction. The other two were rotated 90 degrees and did not have the error.
Painting was done with the bucket tool. I tried repainting the parts and found the same error persisted. Rotating the parts by five degrees appears to have removed the issue.
![Jeep without error](https://user-images.githubusercontent.com/116514803/197408902-63f19df4-50f0-4732-8047-75b8c95c6b66.jpg)
![Jeep with Error](https://user-images.githubusercontent.com/116514803/197408905-5850f4a0-e968-4727-841a-aed7381cf9cc.jpg)
[Jeep Bodies Color with error.zip](https://github.com/bambulab/BambuStudio/files/9847239/Jeep.Bodies.Color.with.error.zip)

**Comment by OlegTheMighty** [comment]
Here's another example. similar part, but depending on rotation, the first-layer is divided differently. the bottom is supposed to be blue, and then grey on the front 
![image](https://user-images.githubusercontent.com/116514803/198909344-d3f9a7fa-1101-496d-9a48-2a00e076f920.png)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
