### ISSUE TITLE
Calculation error when slicing all discs

### ISSUE THREAD

**Issue by Guenni1975** [bambulab/BambuStudio#5031]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

A1

### How to reproduce

1. Multiple panels with multiple colors and supports
3. overall view: weight of model and props is the same

### Actual results

An incorrect calculation result is output. Apparently, the same value is used for model and supports!

### Expected results

The correct value for the model and supports should be set and calculated!
![Screenshot 2024-10-18 150804](https://github.com/user-attachments/assets/413639a2-12b7-4082-8d15-9ce38b9e8eba)

### Project file & Debug log uploads

No special file, the error always occurs!

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by ttt888zzz** [comment]
Please update the newest version. https://github.com/bambulab/BambuStudio/releases.Download and install any one of the available packages.
![image](https://github.com/user-attachments/assets/3080afa4-6237-4668-a285-5091c32384b9)
