### ISSUE TITLE
1.10.0 beta build failure

### ISSUE THREAD

**Issue by fr3ak2402** [bambulab/BambuStudio#5034]
### Bambu Studio Version

master branch

### Where is the application from?

Built from source by yourself or others

### OS version

Windows 11

### Printer

n/A

### How to reproduce

I have followed all the steps from the BambuStudio compilation documentation.
https://github.com/bambulab/BambuStudio/wiki/Windows-Compile-Guide

I have cloned the branch master from the BambuStudio repository.

I have also installed all the programs and tools to set up the development environment as described.

Building or compiling the deps also worked without any problems

When compiling the slicer, a problem occurs when I enter the following command and execute it.

cmake .. -G "Visual Studio 16 2019" -DBBL_RELEASE_TO_PUBLIC=1 -DCMAKE_PREFIX_PATH="D:/work/Projects/BambuStudio_dep/usr/local" -DCMAKE_INSTALL_PREFIX="../install_dir" -DCMAKE_BUILD_TYPE=Release -DWIN10SDK_PATH="C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0"

### Actual results

<img width="868" alt="Screenshot 2024-10-18 190735" src="https://github.com/user-attachments/assets/dca77607-fc02-4bd0-a3d0-09023b0e4627">

### Expected results

it builds

### Project file & Debug log uploads

n/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Sebazzz** [comment]
Also running into this issue. I resolved this by placing extracting [a pre-build version](https://stackoverflow.com/a/1711338) into the BambuStudio_deps directory, however there seem to be further compatiblity issues with Visual Studio 2022.

**Comment by fr3ak2402** [comment]
@Sebazzz Thanks for the quick answer.

Did you unpack the pre-built libs directly into the BambuLab_deps folder or into a subdirectory like usr/local?

I am currently compiling everything with VS2019, as I also had problems with VS2022. Somehow building OpenSSL under VS2022 never worked because of not enough environment memory.

**Comment by Sebazzz** [comment]
> I am currently compiling everything with VS2019, as I also had problems with VS2022. Somehow building OpenSSL under VS2022 never worked because of not enough environment memory.

I actually had no problems with that, but at some point I run into linking errors with curl: 

```
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_init [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_free [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_addpart [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_name [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_filename [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_type [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_data [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_mime_filedata [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_formadd [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_formfree [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_escape [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_unescape [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_free [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(OctoPrint.obj) : error LNK2001: unresolved external symbol curl_free [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_global_init [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_global_cleanup [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_slist_append [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_slist_free_all [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_strerror [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_init [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_setopt [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_perform [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_cleanup [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(Http.obj) : error LNK2001: unresolved external symbol curl_easy_getinfo [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(OctoPrint.obj) : error LNK2001: unresolved external symbol curl_url [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(OctoPrint.obj) : error LNK2001: unresolved external symbol curl_url_cleanup [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(OctoPrint.obj) : error LNK2001: unresolved external symbol curl_url_get [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
libslic3r_gui.lib(OctoPrint.obj) : error LNK2001: unresolved external symbol curl_url_set [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
P:\Dev\BambuStudio\build\src\Release\BambuStudio.dll : fatal error LNK1120: 27 unresolved externals [P:\Dev\BambuStudio\build\src\BambuStudio.vcxproj]
```

**Comment by lanewei120** [comment]
we need to install pkg-config for windows building now

just updated it to the wiki :
pkg-config from [sourceforge](https://sourceforge.net/projects/pkgconfiglite/files/latest/download)

**Comment by fr3ak2402** [comment]
@lanewei120 Thank you for your answer. 

I still don't know where to install the pkg-config. 
I downloaded the zip and there is no installer in there, but a folder. 
Where do I have to copy the files?

**Comment by fr3ak2402** [comment]
I got it right.
Just had to copy the files of the folder from pkg-config into the respective folder of the deps
