### ISSUE TITLE
Painted "Brim Ears" are ignored when cloning objects

### ISSUE THREAD

**Issue by bzzzbzzzzz** [bambulab/BambuStudio#5048]
### Bambu Studio Version

v01.10.00.74

### Where is the application from?

Bambu Lab github releases

### OS version

macOS 15 24A5309e

### Printer

Bambu Lab X1C

### How to reproduce

- [paint Brim Ears](https://github.com/bambulab/BambuStudio/issues/1393)
- select "painted" in Process -> Other -> Brim Type
- right click an object and select "Clone"

### Actual results

no painted brim ears on the cloned object

<img width="339" alt="Screenshot 2024-10-20 at 16 25 48" src="https://github.com/user-attachments/assets/0085eab4-3af8-4113-957e-77c6df6008e8">

### Expected results

painted brim ears on the cloned object

### Project file & Debug log uploads

[box-opener_temp.3mf.zip](https://github.com/user-attachments/files/17450641/box-opener_temp.3mf.zip)
[Archive.zip](https://github.com/user-attachments/files/17450646/Archive.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MackBambu** [comment]
Confirmed the issue, thanks for reporting

**Comment by MackBambu** [comment]
Fixed
