### ISSUE TITLE
[Feature request] allow command line usage (CLI)

### ISSUE THREAD

**Issue by Project-J2** [bambulab/BambuStudio#505]
We would like to automate gcode generation. Is it possible to implement the command line interface (CLI) function like in PrusaSlicer
([Command Line Usage](https://manual.slic3r.org/advanced/command-line)) ?

**Comment by lanewei120** [comment]
currently CLI is still supprted,
however the params have been changed lots. 

we will give a short guide soon and refine them in next release

**Comment by lanewei120** [comment]
the CLI guide is published at [BambuStudio's Wiki](https://github.com/bambulab/BambuStudio/wiki/Command-Line-Usage)
BambuStudio v1.4 already support it

**Comment by Project-J2** [comment]
Hi,
Thanks for the info, however I can't use it on Windows.
I guess on Windows i need another executable like PrusaSlicer : "prusa-slicer.exe" for the version with HMI and "prusa-slicer-console.exe" for the console version?

**Comment by lanewei120** [comment]
> Hi, Thanks for the info, however I can't use it on Windows. I guess on Windows i need another executable like PrusaSlicer : "prusa-slicer.exe" for the version with HMI and "prusa-slicer-console.exe" for the console version?

oops, just found I forgot to reply this
sorry for this.

on windows, you can run bambu-studio.exe also
I have confirmed that it can run on the git bash, 
however, it seems it can not run in windows 'cmd shell'

**Comment by lanewei120** [comment]
![image](https://user-images.githubusercontent.com/106916061/211742858-1378693f-164f-4952-8872-b8d95b4f3f2e.png)
