### ISSUE TITLE
具有多个盘的文件全部切片后，时间预估总览中的盘号出现错误

### ISSUE THREAD

**Issue by ORNAU** [bambulab/BambuStudio#5055]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows10

### Printer

A1

### How to reproduce

1.打开具有多个盘的文件
2.将多个盘全部进行切片
3.查看总体预览

### Actual results

时间预估中的盘号是从0开始的，并未与实际盘号对应
![image](https://github.com/user-attachments/assets/8b3f6997-d7d6-487d-971e-91f4b66e9215)

### Expected results

应当从1开始，与实际盘号对应

### Project file & Debug log uploads

[全部切片后，时间预览的盘号出现错误_2024-10-21.zip](https://github.com/user-attachments/files/17455424/_2024-10-21.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
请更新刀最新版本 V10，下载地址：https://github.com/bambulab/BambuStudio/releases
