### ISSUE TITLE
Aft Right Purge Line Missing

### ISSUE THREAD

**Issue by mltriebe** [bambulab/BambuStudio#5064]
### Bambu Studio Version

v01.10.00.74

### Where is the application from?

Bambu Lab Official website, Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab X1C

### How to reproduce

Slice an object with the .4 nozzle selected and there is no purge line.  The purge line is there for the .2 and .6 profiles.

### Actual results

![Screenshot 2024-10-22 175622](https://github.com/user-attachments/assets/99fb41ab-efdb-4eaa-a8dc-5ebd75e50bc2)

### Expected results

![Screenshot 2024-10-22 175314](https://github.com/user-attachments/assets/8a9643cf-48d6-4854-9005-89f2d0172f17)

### Project file & Debug log uploads

[Uploading thread (v4).zip…]()

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/4f3a8e5e-689f-4ef3-87a1-57f4243cd2af)
there is no problem~

**Comment by Haidiye00** [comment]
Hello, can you record a GIF? Thank you

**Comment by ttt888zzz** [comment]
Thank you for your feedback.It's not a bug. 
This is the wiper print line defined in start gcode, and the position of this line in start gcode has changed, and it's in line with the calibration line.

**Comment by mltriebe** [comment]
Only on the .4 nozzle profile?  That seems odd.

**Comment by mltriebe** [comment]
> ![image](https://private-user-images.githubusercontent.com/132528822/379067990-4f3a8e5e-689f-4ef3-87a1-57f4243cd2af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTIyNjAsIm5iZiI6MTcyOTY1MTk2MCwicGF0aCI6Ii8xMzI1Mjg4MjIvMzc5MDY3OTkwLTRmM2E4ZTVlLTY4OWYtNGVmMy04N2ExLTU3ZjQyNDNjZDJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMjUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzQwOTQwOTc3MDQ1N2YxZmNmMmZkNTgxZjAyYmFlNjA4N2Y1NWEzMjIxODlkNTg0OGY3NDE3YmY5OTUyNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oqEgvYqsZlKNdCqh9Y4aYoG7uQIeGYOqX9g9Qcsbv78) there is no problem~

It works with the .2 nozzle you have selected.  Try the .4 nozzle.

**Comment by ttt888zzz** [comment]
![image](https://github.com/user-attachments/assets/10560a34-71a2-423c-a66e-01904422f3e4)
The imge and 3mf file cannot be downloaded，Could you pls upload the 3mf file  and the img with the  .4 nozzle? thank you

**Comment by mltriebe** [comment]
[thread (v4).zip](https://github.com/user-attachments/files/17484663/thread.v4.zip)
![Screenshot 2024-10-22 175622](https://github.com/user-attachments/assets/bc2d748f-c2e4-483c-ab6d-b1d74c194096)

The zip file should be the 3mf.

**Comment by MartinChan3** [comment]
[1.10 beta2](https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.81) has solved this problem.

**Comment by danielo515** [comment]
I was not sure what the technical term was for this, and I found nothing in the last release notes. Too bad you guys decided something this obvious is not worth mentioning.
To be honest, this line was annoying to remove and felt redundant, glad you removed it, but it was worth mentioning for sure
