### ISSUE TITLE
wrong calculation of filament for multi-plate print

### ISSUE THREAD

**Issue by fisherman-be** [bambulab/BambuStudio#5071]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 22H2

### Printer

Bambu Lab X1C

### How to reproduce

1. In a multi-material project with supports and multiple objects spread over multiple print plates, open "Preview"
2. Press the Button in the upper left corner to slice all plates
3. The dialog showing the filament weight and time estimation opens.

### Actual results

This dialog shows the wrong sum for supports. It appears to be the same amount of filament as for the model itself. See yellow mark in the screenshot.

![bambu studio](https://github.com/user-attachments/assets/cd0a2ff1-00d6-4262-ad75-1ea0fafd32c9)

### Expected results

correct calculation of the required amount of filament

### Project file & Debug log uploads

[Bolter+40k_error.zip](https://github.com/user-attachments/files/17510605/Bolter%2B40k_error.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
The latest version has been fixed.
Please visit the website at https://github.com/bambulab/BambuStudio/releases and try again
