### ISSUE TITLE
Some of the support structure is added in mid air

### ISSUE THREAD

**Issue by SDwarfs** [bambulab/BambuStudio#5079]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro

### Printer

Bambu Lab A1 mini

### How to reproduce

1. Load the attached *.3MF file
2. Hit "slice plate"

### Actual results

The preview shows 4 triangle-shaped parts of the generated support (light green) which are in mid air.

![Support-Structure-Bug](https://github.com/user-attachments/assets/7639d33d-09f5-46b9-84dd-cf195f89d6e1)

### Expected results

The whole support structure should be a connected structure, that must be below any (supported) part of the 3D model, never above it. 

### Project file & Debug log uploads

[BambuStudio-SupportStructure-Bug.zip](https://github.com/user-attachments/files/17528222/BambuStudio-SupportStructure-Bug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by tangketan** [comment]
It's not a bug. The supports are on the top of interface layers, not in air. You de-selected the support interface from the display color scheme.
![image](https://github.com/user-attachments/assets/26d3ae77-06d2-4d03-b354-ba4bab8efac4)
