### ISSUE TITLE
fedora kde spin 560 drivers do not work 3d zone

### ISSUE THREAD

**Issue by VictorMolokanov** [bambulab/BambuStudio#5089]
### Bambu Studio Version

1.9.7.7.52 Public Official

### Where is the application from?

Built from source by yourself or others

### OS version

Fedora 40 Kde spin

### Additional system information

Відомості про комп’ютер:
Виробник: ASUSTeK COMPUTER INC.
Модель: M5A97 LE R2.0
Форм-фактор: настільний ПК
Сенсорне введення не виявлено
Відомості про процесор:
Виробник процесора: AuthenticAMD
Бренд процесора: AMD FX(tm)-8350 Eight-Core Processor
Сімейство процесора: 0x15
Модель процесора: 0x2
Степінг процесора: 0x0
Тип процесора: 0x0
Частота: 4000 МГц
Логічних процесорів: 8
Фізичних процесорів: 8
Hyper-Threading: Не підтримується
FCMOV: Підтримується
SSE2: Підтримується
SSE3: Підтримується
SSSE3: Підтримується
SSE4a: Підтримується
SSE41: Підтримується
SSE42: Підтримується
AES: Підтримується
AVX: Підтримується
AVX2: Не підтримується
AVX512F: Не підтримується
AVX512PF: Не підтримується
AVX512ER: Не підтримується
AVX512CD: Не підтримується
AVX512VNNI: Не підтримується
SHA: Не підтримується
CMPXCHG16B: Підтримується
LAHF/SAHF: Підтримується
PrefetchW: Не підтримується
Версія операційної системи:
"Fedora Linux 40 (KDE Plasma)" (64 біт)
Назва ядра: Linux
Версія ядра: 6.11.4-201.fc40.x86_64
Виробник X-сервера: The X.Org Foundation
Версія X-сервера: 12401003
Менеджер вікон X Window System: KWin
Версія середовища виконання Steam: steam-runtime_0.20240806.97925
Відеокарта:
Драйвер: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
Версія драйвера: 4.6.0 NVIDIA 560.35.03
Версія OpenGL: 4.6
Глибина кольору робочого столу: 24 біт/піксель
Частота оновлення екрана: 59 Гц
Ідентифікатор виробника: 0x10de
Ідентифікатор пристрою: 0x1c03
Версій не виявлено
Кількість моніторів: 2
Число логічних відеокарт: 1
Роздільна здатність головного екрана: 2560 x 1080
Роздільна здатність робочого столу: 4480 x 1200
Розмір головного екрана: 31.42" x 13.15" (34.06" diag), 79.8cm x 33.4cm (86.5cm diag)
Головна відеопам’ять: 6144 МБ
Звукова плата:
Аудіопристрій: USB Mixer
Пам’ять:
ОЗП: 15885 МБ
Обладнання ВР:
Шолом ВР: не виявлено
Інше:
Мова інтерфейсу: Українська
МОВА: uk_UA.UTF-8
Загальний обсяг вільного місця на жорсткому диску: 835965 МБ
Найбільший обсяг вільного місця на жорсткому диску: 455283 МБ
Місце на диску:
Кількість SSD: 1
Розміри SSD: 1000G
Кількість жорстких дисків: 0
Кількість знімних дисків: 0

### Printer

P1 S

### How to reproduce

just open with 560 nvidia drivers on fedora kde spin

### Actual results

nothing just nothing

### Expected results

working 3d windows

### Project file & Debug log uploads

emmm nofile

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MackBambu** [comment]
This is a known issue; try downgrading the driver to version 555.
https://github.com/bambulab/BambuStudio/issues/4669
