### ISSUE TITLE
I made this white but slicer says black but preview says white

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#510]
![Screen Shot 2022-10-24 at 3 16 48 PM](https://user-images.githubusercontent.com/48887257/197620963-a0720916-1861-4fa1-9b46-1853a26c54d3.png)
[Zelda_Keychain.3mf.zip](https://github.com/bambulab/BambuStudio/files/9855075/Zelda_Keychain.3mf.zip)

**Comment by murrlyn99** [comment]
I had this issue recently as well. Painted model surface on build plate side of print is correct before and after painting in Bambu studio in prepare tab but after being sliced, some areas of print change color only on build plate face and print that way shown only in preview tab however prepare menu still shows correct painting.

**Comment by zhimin-zeng-bambulab** [comment]
The latest version has fixed this problem(e.g. v1.8.4), you can have a try.
