### ISSUE TITLE
No grid neither piece displayed when open BambuStudio

### ISSUE THREAD

**Issue by ronki2304** [bambulab/BambuStudio#5107]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 24.10

### Additional system information

**Display card** : Nvidia 3060

### Printer

Bambu P1S

### How to reproduce

Install a fresh version of ubuntu 24.10, 
on additionnal driver please check that the version 560 is selected
open bambus studio not grid is displayed in the prepare tab or preview tab
![image](https://github.com/user-attachments/assets/57bdf2a2-53c7-4e5d-b110-9e07dc5fdc97)
![image](https://github.com/user-attachments/assets/a1af1c8c-53cb-42bc-8d0d-13b06a927e0d)

### Actual results

The screen is blank

### Expected results

the screen must represent at least a grid

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/17563083/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by MackBambu** [comment]
This is a known issue; try downgrading the driver to version 555.
https://github.com/bambulab/BambuStudio/issues/4669

**Comment by ronki2304** [comment]
OK thank you any ETA?

**Comment by MackBambu** [comment]
> OK thank you any ETA?

Not yet, still working hard to find the cause of the problem.

**Comment by ronki2304** [comment]
OK if you need some help I can test for you

**Comment by MackBambu** [comment]
@ronki2304 
Are you using X11 or Wayland? I tested the 560 driver, and everything works fine in the X11, but after switching to wayland, it fails to load the kernel.

**Comment by ronki2304** [comment]
I am usine wayland

**Comment by agirnob** [comment]
I use flatpak version of bambulab.
While using bambulab under wayland I have the same issue but not under x11.
When I start a x11 server within wayland
"Xwayland -retro -noreset :12" and start bambulab with this server display still have the same issue.

**Comment by ronki2304** [comment]
Yes but now Wayland is globally adopted by all distros might be interesting to fully support it

Regards,

Jeremy RONK

**Comment by agirnob** [comment]
@ronki2304 this issue don't seem to apply ton the nividia driver version 565.57.01.
If you try to update your system/drivers it may help.
Right now it works for me.
I am using endavourOS with kde.

Happy printing!

Regards,
Agirnob

**Comment by MackBambu** [comment]
merge issue : https://github.com/bambulab/BambuStudio/issues/4669
