### ISSUE TITLE
Total filament usage not being calculated correctly in summary when models use support

### ISSUE THREAD

**Issue by ChristOfFear** [bambulab/BambuStudio#5112]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

windows 10

### Printer

Bambulab P1P

### How to reproduce

1. Have a multi plate project where at least one plate uses supports 
2. slice all plates
3. look at each individual plates filament usage, especially the summary for support and model usage
4. look at the summary page for all plates

Result:
The summary page will show the total model filament for support instead of support usage making the overall total be way too large

### Actual results

The summary lists the model filament usage instead of the actual support filament usage making the total inaccurate

Looking at each  plate should lead to this
**Plate 1**
model filament 120,84g
support filament 15,01g
![Plate 1](https://github.com/user-attachments/assets/7388fea6-10ba-4dd2-8d24-d8bd74e3f79c)
**Plate 2**
model filament 28,09g
support filament 0g
![plate 2](https://github.com/user-attachments/assets/c6eacb10-e6b4-4fce-9bdd-dd60d069856f)
**Summary**
model filament 148,93g
support filament 148,93g
![summary](https://github.com/user-attachments/assets/ea34297b-e474-4ddb-b4ad-7741c366bd58)

### Expected results

Support usage should show actual support usage, in the example above that would be 15,01 making the total to
148,93+15,01+0,01=163,95g

### Project file & Debug log uploads

example .3mf used in for testing and log file:
[lithophane error calcuation.zip](https://github.com/user-attachments/files/17577268/lithophane.error.calcuation.zip)
[log file.zip](https://github.com/user-attachments/files/17577266/log.file.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
the same issue [#4933](https://github.com/bambulab/BambuStudio/issues/4933)
Please update the newest version，https://github.com/bambulab/BambuStudio/releases
