### ISSUE TITLE
Plate numbers don't match in Preview tab

### ISSUE THREAD

**Issue by DroidSlicer** [bambulab/BambuStudio#5113]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Home version

### Printer

Bambu Lab X1C

### How to reproduce

When slicing multiple plates in one project, the plate numbers on the time estimations list do not match the plate numbers on the left. I've circled it below in red. 

![Screenshot 2024-10-30 164942](https://github.com/user-attachments/assets/da1e5c6c-4492-41d8-a65b-3e6912658819)

### Actual results

The build plate numbers do not match between the time estimations list and the column where you can select each build plate. 
![Screenshot 2024-10-30 164942](https://github.com/user-attachments/assets/8df510cb-c21d-4d8d-bc56-df7dfb1c820e)

### Expected results

It would be nice to have the time estimation plate numbers changed so when looking at the time estimations, they match up to the plate numbers on the left. Thanks in advance!!!

### Project file & Debug log uploads

[Panel C.zip](https://github.com/user-attachments/files/17579482/Panel.C.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by ttt888zzz** [comment]
the same issue https://github.com/bambulab/BambuStudio/issues/5055
Please update the newest version，https://github.com/bambulab/BambuStudio/releases
