### ISSUE TITLE
Unsaved changes pop-up dialog window

### ISSUE THREAD

**Issue by asoderberg** [bambulab/BambuStudio#512]
This and similar pop-up dialogs are not clear as to what will be done by selecting either of the options.
In this screen-shot case: Which sets of values will be Saved or Discarded? It is not clear 
Please be explicit in the action being taken. 
Are we Saving or Discarding the New values or the Old values?????
I suggest changing the buttons to read: 
Discard [value type]  Save [value type]

<img width="515" alt="Screenshot 2022-10-25 at 10 33 20 AM" src="https://user-images.githubusercontent.com/1242619/197843194-e3fedd04-9fd2-4e82-9017-6adb500b8bd0.png">

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
