### ISSUE TITLE
Application closes shortly after an error message appears from the printer

### ISSUE THREAD

**Issue by DesterCalibra** [bambulab/BambuStudio#5125]
### Bambu Studio Version

1.10.0.74

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11 24H2

### Additional system information

CPU: AMD Ryzen 5950X
MB: MSI X570 Tomahawk WIFI
GPU: Gigabyte RTX 4080 Super
RAM: 128 GB (4x32) DDR4
SSD: 2TB NVMe (Kingston)

### Printer

Bambu Lab X1C

### How to reproduce

Open Bambu Studio
Device tab, live view is on
When an error message appears mid print (such as failed to pull filament out of the extruder, etc), the application closes shortly after without any error messages.
It is totally irrelevant if a project file is loaded or not, monitoring is enough.

### Actual results

I cannot give screenshot. The application closes without any messages, crash information, etc.

### Expected results

The application should not crash or close.

### Project file & Debug log uploads

There are no current log files. There were crashes even today, but my latest log files are created at 19th October.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by fahaaaxiki** [comment]
Can you use Beta2(https://github.com/bambulab/BambuStudio/releases/tag/v01.10.00.81) to test it? I have tried it with my X1C and A1, no problem happened and I hope that will help you.
