### ISSUE TITLE
[Bug] 'Export Sliced File' drop-down menu in the UI is unreachable on Mac

### ISSUE THREAD

**Issue by tokamac** [bambulab/BambuStudio#517]
BambuStudio 01.03.00.12
macOS Ventura 13.0
MacBook Air M1

The top right button `Print` in BambuStudio, that sends the sliced file to the printer OTA, has also a drop-down menu to choose either `Print` or `Export Sliced File` to write a .gcode file onto an SD card that can then be inserted into the printer.

However on my Mac, this submenu `Export Sliced File` is _unreachable_ because although opening, _it always closes before the mouse cursor can roll over it_. The solution of traditional menus to press and hold the button of the mouse/trackpad does not work because the BS devs have chosen a "MouseUp" event to make the drop-down menu appear (the menu is displayed when the mouse button is released) instead of an "MouseDown" event (the menu is displayed when the mouse button is pressed).

A workaround currently is to export the sliced file with the File menu in the main menubar handled by the OS (this works)
Please fix this not critical but somewhat annoying UI glitch, which I think has been introduced in BambuStudio 1.3

<img width="177" alt="Export_Sliced_File" src="https://user-images.githubusercontent.com/3685009/198001686-6d66dbb4-2cb3-4fc5-9f05-3cf2e0a605b0.png">

Subsidiary question: What is the difference between the G-code file generated by `Export Sliced File…` vs `Export G-code…` in the `File → Export` menu of BambuStudio? Why two G-code files? Is the later a "generic" G-code for other printers, stripped of the X1's specific features?

**Comment by YifanWuBambu** [comment]
Subsidiary question: What is the difference between the G-code file generated by Export Sliced File… vs Export G-code… in the File → Export menu of BambuStudio? Why two G-code files? Is the later a "generic" G-code for other printers, stripped of the X1's specific features?

@tokamac 
Export Sliced File - it exports a .gcode.3mf file, which not only contains .gcode file, but also contains the thumbnails, slicing info (especially useful in AMS slot mapping)
Export G-code - just .gcode file, no thumbnails and do not allow to assign AMS slot for each filament in multi-material printing

**Comment by mvieleers** [comment]
I have the same issue BambuStudio 01.03.01.01 on MacOS Venture 13.0.1 on MacBook Pro M1 Max

Steps to reproduce:
add an stl to the buildplate
Press "Slice" in top right
The Select the dropdown on the "Print" button
The dropdown opens and shortly shows 2 options:  Print and Export Sliced File. 
As soon as you move the mouse over the dropdown menu it immediately disappears making it impossible to press "Export Sliced File"

<img width="308" alt="Scherm­afbeelding 2022-12-08 om 09 11 21" src="https://user-images.githubusercontent.com/10944296/206393655-7bbeb6b1-3937-431b-ac57-f91d7e99e796.png">

**Comment by Naiki92** [comment]
v1.4.0.18 - The problem appears again. MacOS Ventura 13.1
