### ISSUE TITLE
Camera stream stops working after one second

### ISSUE THREAD

**Issue by TheElbinho** [bambulab/BambuStudio#5172]
### Bambu Studio Version

1.9.7.52 (Flatpak)

### Where is the application from?

Bambu Lab github releases

### OS version

Universal Blue aurora-surface

### Additional system information

Surface Pro 5

### Printer

X1C

### How to reproduce

1. Open Bambu Studio
2. Go to device tab
3. Add printer (LAN mode)
4. Start Camera Stream

### Actual results

Video is displayed for 1 second, then freezes

### Expected results

continuous streaming

### Project file & Debug log uploads

This is the GStreamer log output. I don't know how to process any of this, because GStreamer will always be black magic to me
[bambulog.txt](https://github.com/user-attachments/files/17689542/bambulog.txt)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by bambu123** [comment]
Can you help try the latest beta version 1.10?

**Comment by bambu123** [comment]
Not yet.

AppImage?
https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.81/Bambu_Studio_linux_fedora-v01.10.00.81.AppImage

**Comment by TheElbinho** [comment]
I can in fact confirm that the camera stream just works in version 1.10.1.5
