### ISSUE TITLE
Support Slicer Issue - Irregular/Jagged tree support with Archane slicer (can be triggered by any setting change e.g. `Initial Layer Expansion`)

### ISSUE THREAD

**Issue by CraigHutchinson** [bambulab/BambuStudio#5177]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11

### Printer

Bambu A1

### How to reproduce

1. Using Archane Slicer
2. Increase the 'Initial Layer Expansion' (Also could be other changes that cause this as it isn't specific to this setting)
3. Slice model and observe the Tree support slices
4. Repeat step 2>3 and supports incrementally degrade!

### Actual results

After changing the expansion a couple of times from 2.0 > 3.0 > 4.0 we see the support tree is 'jagged' and there are lots of irregular slicing lines which causes supports to fail mid-print as far as I can tell. i.e. The layers are not stacked ontop of each other due to this issue!
![image](https://github.com/user-attachments/assets/6a49df44-550a-44c5-9ace-a4fe211c5d87)
![image](https://github.com/user-attachments/assets/510b1e4b-dead-4fd4-ba1d-82a6c3a27dc3)

### Expected results

Issue can be resolved by toggling back to 'Classic'<>`Archane` and issue corrects/goes-away...
![image](https://github.com/user-attachments/assets/dfe06ec8-fa6c-4b4e-86a4-3f06684d2b09)
![image](https://github.com/user-attachments/assets/b40920ff-4e58-4da9-9ce1-2efc77096b0f)

### Project file & Debug log uploads

[2024_11_11_TreeSupportSlice_Issue_Testa di Drago_B.zip](https://github.com/user-attachments/files/17700392/2024_11_11_TreeSupportSlice_Issue_Testa.di.Drago_B.zip)
[2024-11-11 log.zip](https://github.com/user-attachments/files/17700434/2024-11-11.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by tangketan** [comment]
Please wait for the next new release and see if the problem exists.

**Comment by tangketan** [comment]
@CraigHutchinson Hi, the new version has been released. Did you try it?

**Comment by CraigHutchinson** [comment]
There is very little - almost nothing - of 'Support Interface' being generated for supports but I don't know if thsta a bug or it isn't expected? I can open a new bug if you see this as one.

I'm happy to say the jagged support  issue is resolved.

**Comment by CraigHutchinson** [comment]
I would confirm this appears fixed in v1.10 and I have not seen this issue since.
