### ISSUE TITLE
Step import graphic is confusing

### ISSUE THREAD

**Issue by LJKraus** [bambulab/BambuStudio#5193]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/e4d62387-ba7f-4224-b44b-0c6108bcb3f9)
This graphic is confusing because it shows smoother curves on the RIGHT to indicate smoother curves. The sliding controls actually have to move LEFT in order to increase triangle count and produce smoother curves.

**Describe the solution you'd like**
Reverse the graphic, or reverse the sliders.

**Describe alternatives you've considered**
Show a real time preview of the model as the sliders are moved.  That's surely a lot more work, so a change in the graphic would probably be a quicker fix.

**Additional context**
Studio 1.10.0.89 on Win 11

**Comment by MackBambu** [comment]
Okay, I will return the image arrow.
