### ISSUE TITLE
missing slicing parameters

### ISSUE THREAD

**Issue by jon-bondy** [bambulab/BambuStudio#520]
Many of the slicing parameters that are visible in PrusaSlicer are not visible in Bambu Studio, even in Advanced mode.  For example, I cannot find a way to adjust retraction in Bambu Studio.  Can you provide a way for us to see all of the parameters please?

**Comment by SaltWei** [comment]
We are not absolutely same with prusa.
For retraction, you can change in machine settings or override in filament setting.

If you have new setting request, just list the user scene and we will evaluate then. Thanks for suggestions!

**Comment by SaltWei** [comment]
Retraction can be changed in machine settings or override in filament setting.

Close
