### ISSUE TITLE
Bambu Studio crashes on STEP import

### ISSUE THREAD

**Issue by SorenTheSwede** [bambulab/BambuStudio#5208]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 Pro OS version 19045.5073

### Printer

Bambu Lab P1s

### How to reproduce

A. With Bambu Studio closed,
1. Right-click on STEP-file and click on 'Open with Bambu Studio.'
2. Step mesh parameter settings dialog starts.
3. Pick any parameter and click ok = crash
4. Skip the parameters = crash

B. With Bambu Studio open,
1. Got to 'File' and click on 'Import 3M/STL...' 
2. Choose file.
3. Step mesh parameter settings dialog starts.
4. Pick any parameter and click ok = crash
5. Skip the parameters = crash

C. With Bambu Studio open,
1.  Go to 'Settings"
2. Unclick 'Show the step mesh parameter settings dialog."
3.  Close settings
4. Repeat B.1. above = crash
5. Close and restart Bambu Studio 
6. Repeat B.1. above = crash
7. Repeat A.1. above = crash

### Actual results

![Namnlös](https://github.com/user-attachments/assets/b69d820c-9332-4ad6-b1e9-c63ddc56a040)

### Expected results

The step file should be imported and able to print.

### Project file & Debug log uploads

[Project file and logs.zip](https://github.com/user-attachments/files/17722529/Project.file.and.logs.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg
