### ISSUE TITLE
Reload from disk does not work anymore for step files

### ISSUE THREAD

**Issue by benjaminkott** [bambulab/BambuStudio#5209]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

1. Load a step file
2. Change original step file
3. Reload from disk

### Actual results

Model is not updated

### Expected results

Model is updated as before

### Project file & Debug log uploads

.

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MrDB42** [comment]
Confirm bug.

**Comment by MackBambu** [comment]
confirm

**Comment by rashuge** [comment]
Confirm

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

**Comment by jonatkins** [comment]
I had the same issue. That new build (1.10.0.94) has fixed it for me.
