### ISSUE TITLE
SE CIERRA BAMBU STUDIO

### ISSUE THREAD

**Issue by ALBERTOBARRAGAN1983** [bambulab/BambuStudio#5218]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

MACOS MONTEREY 12.7.6

### Printer

P1S

### How to reproduce

1- ABRO EL PROGRAMA BAMBU STUDIO
2- CREO NUEVO PROYECTO
3- AÑADO ARCHIVO FORMATO STEP
4- SE ABRE UNA VENTANA DE step file import parametro
<img width="809" alt="Captura de Pantalla 2024-11-12 a las 22 57 06" src="https://github.com/user-attachments/assets/c79da964-1758-4116-9d67-c7b60bd75566">
s
5- SE CIERRA AUTOMÁTICAMENTE EL PROGRAMA DANDO ERROR
6- REPITO EL PROCESO INDICADO Y SIGUE HACIENDO LO MISMO

### Actual results

[Piezas cables ordenador.zip](https://github.com/user-attachments/files/17724001/Piezas.cables.ordenador.zip)

### Expected results

Lo que se espera es que no se cierre el programa 

### Project file & Debug log uploads

A
[Piezas cables ordenador.zip](https://github.com/user-attachments/files/17724000/Piezas.cables.ordenador.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
please see https://github.com/bambulab/BambuStudio/issues/5186

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

**Comment by MackBambu** [comment]
fixed
https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
