### ISSUE TITLE
Ошибка в программе, сбой при попытке добавить файл STEP/STL.

### ISSUE THREAD

**Issue by Dimitr-Sibiryak** [bambulab/BambuStudio#5222]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

windows 11 pro

### Additional system information

AMD Ryzen 9 7940HS w/ Radeon 780M Graphics 4.00 GHz, 

### Printer

Bambulab x1C

### How to reproduce

1. Add - 2. Ctrl+I - 3 (1). Chande parameters "Linear deflection" or "Angle deflection" - 4. press "Ok" - Unknown Exception/escape
3 (2). if no chaging - nothin happen wen press "Ok".

### Actual results

Error when trying to add a STEP/STL file: a new menu "STEP Import Options" appears. If you don’t change the options, the menu doesn’t respond to the "OK" button. If you change the options, an "Unknown Exception" error occurs, and the program closes.

### Expected results

SHOULD THE FILE BE UPLOADED FOR PRINTING, IS IT NOT CLEAR WITHOUT A DESCRIPTION???

### Project file & Debug log uploads

I can’t load the project file because Bambu Studio crashes when trying to load it. The project simply doesn’t exist; try it yourself. I’ll send the file in an archive, but there are no log files or project file records.
[Border AMG7200.zip](https://github.com/user-attachments/files/17726909/Border.AMG7200.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Dimitr-Sibiryak** [comment]
Why did I update the program…
Two old sayings:
The best is the enemy of the good. Don’t make things “better” for me; just leave them “good.”

**Comment by MartinChan3** [comment]
The question is mentioned in #5186 , you can switch language to English to solve this problem temporarily.

**Comment by zanuda2raza** [comment]
Смените язык на En и все заработает.

**Comment by Dimitr-Sibiryak** [comment]
А я не хочу менять язык на английский.

**Comment by zanuda2raza** [comment]
Тогда придется откатиться на 1.9.7 и ждать когда 1.10 починят. На macOS она вообще нерабочая

**Comment by Dimitr-Sibiryak** [comment]
Прикольно.
Так я в чате смотрю, там и немцы, и итальянцы, и французы с этим же сталкиваются, им тоже на английский переключаться? - особенно итальянцы с французами любят английский😂😂😂🤣🤣🤣

Дмитрий
________________________________
От: zanuda2raza ***@***.***>
Отправлено: Wednesday, November 13, 2024 10:00:07 AM
Кому: bambulab/BambuStudio ***@***.***>
Копия: Dimitr-Sibiryak ***@***.***>; Author ***@***.***>
Тема: Re: [bambulab/BambuStudio] Ошибка в программе, сбой при попытке добавить файл STEP/STL. (Issue #5222)


Тогда придется откатиться на 1.9.7 и ждать когда 1.10 починят. На macOS она вообще нерабочая

**Comment by zanuda2raza** [comment]
Да, и китайцам тоже. Но в этот раз они как-то накосячили сильно.

**Comment by Dimitr-Sibiryak** [comment]
А вот и таблетка:
Я переключился обратно в русский, поднял линейную интерполяцию до значения 0,4, угловую до 0,2 и вуаля – он прожевал в русскоязычном интерфейсе файл STEP с русскими буквами в имени, и больше ошибок пока не возникало, несколько раз выгружал и загружал студио и без ошибок пока.

Походу во время компиляции у них кто-то на клаве уснул и соплями в значениях движков этих параметров ввёл недопустимый диапазон.

Кто бы им подсказал, где покопать…

**Comment by Dimitr-Sibiryak** [comment]
Могу видео прислать, перешлите китайцам, пусть поржут.

Серебряков Д.В.
________________________________
От: zanuda2raza ***@***.***>
Отправлено: Wednesday, November 13, 2024 10:07:54 AM
Кому: bambulab/BambuStudio ***@***.***>
Копия: Dimitr-Sibiryak ***@***.***>; Author ***@***.***>
Тема: Re: [bambulab/BambuStudio] Ошибка в программе, сбой при попытке добавить файл STEP/STL. (Issue #5222)


Да, и китайцам тоже. Но в этот раз они как-то накосячили сильно.

**Comment by zanuda2raza** [comment]
у меня на компьютере с 2-мя Xeon Gold и 256 оперативки все разу идеально крутится, но оно жрет 45 ГБ оперы в этот момент. А на маке все колом встает. Они все видео просят на https://wiki.bambulab.com/en/x1/troubleshooting/upload-log и делать тикет

**Comment by zanuda2raza** [comment]
Причем, что забавно, оно все равно работает лучше, чем Picaso-вские поделки....

**Comment by Dimitr-Sibiryak** [comment]
Да, работает мьудио хорошо, но у меня ещё и креалити к1макс, и тут еитайцы отоичились и в наборе филаментов при выборе креалити указали только рпа, петг, абс и ещё пару каких-то, и не добавить.
Приходится по сути такой же оркаслайсер грузить для работы с креалити.

________________________________
От: zanuda2raza ***@***.***>
Отправлено: Wednesday, November 13, 2024 10:31:00 AM
Кому: bambulab/BambuStudio ***@***.***>
Копия: Dimitr-Sibiryak ***@***.***>; Author ***@***.***>
Тема: Re: [bambulab/BambuStudio] Ошибка в программе, сбой при попытке добавить файл STEP/STL. (Issue #5222)


Причем, что забавно, оно все равно работает лучше, чем Picaso-вские поделки....

**Comment by zanuda2raza** [comment]
Ну тут хотя бы выбор есть, а то с системой профилей в полигоне часов 6 разбирался.... а потом еще и выяснилось, что по умолчанию они сохраняются в формате для S1 принтеров и S2 их не читает...

**Comment by Dimitr-Sibiryak** [comment]
Да какой там выбор, даже сраного силк пла нет, не говоря о всяких поликарбонатах, которыми иногда приходится баловаться...

________________________________
От: zanuda2raza ***@***.***>
Отправлено: Wednesday, November 13, 2024 10:51:22 AM
Кому: bambulab/BambuStudio ***@***.***>
Копия: Dimitr-Sibiryak ***@***.***>; Author ***@***.***>
Тема: Re: [bambulab/BambuStudio] Ошибка в программе, сбой при попытке добавить файл STEP/STL. (Issue #5222)


Ну тут хотя бы выбор есть, а то с системой профилей в полигоне часов 6 разбирался.... а потом еще и выяснилось, что по умолчанию они сохраняются в формате для S1 принтеров и S2 их не читает...

**Comment by Dimitr-Sibiryak** [comment]
Thanks!

Серебряков Д.В.
________________________________
От: Martin Chan ***@***.***>
Отправлено: Thursday, November 14, 2024 6:31:47 PM
Кому: bambulab/BambuStudio ***@***.***>
Копия: Dimitr-Sibiryak ***@***.***>; Author ***@***.***>
Тема: Re: [bambulab/BambuStudio] Ошибка в программе, сбой при попытке добавить файл STEP/STL. (Issue #5222)


It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

―

**Comment by zanuda2raza** [comment]
Видео, проверю) спасибо

**Comment by MackBambu** [comment]
fixed
https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
