### ISSUE TITLE
Messed up UI and explanation in a misc panel regarding STEP file import

### ISSUE THREAD

**Issue by altimac** [bambulab/BambuStudio#5227]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

macOS Sequoia 15.0.1

### Additional system information

Macbook Pro M3 Max

### Printer

P1S

### How to reproduce

Import  the attached STEP file
get this window appearing:
<img width="872" alt="Screenshot 2024-11-13 at 10 59 57" src="https://github.com/user-attachments/assets/edf85a70-647b-4fc6-ac44-565e961203e1">

### Actual results

The UI and explanation in this window are all messed up 

The exemple with the 2 circles are not aligned with any of the text and explanation, making the idea not comprehensible.

### Expected results

Just look at the attached screenshot and you should notice UI is wrong.

### Project file & Debug log uploads

[patère leucate.step.zip](https://github.com/user-attachments/files/17730519/patere.leucate.step.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by MackBambu** [comment]
confirm

**Comment by Stevelsch** [comment]
I dont even get the messed up graphics just a forever loading screen when importing STEP.

If I skip this page i get this issue
https://github.com/bambulab/BambuStudio/issues/5261

**Comment by MackBambu** [comment]
fixed
https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
