### ISSUE TITLE
[SLICER FEATURE] Readable output 3mf file name

### ISSUE THREAD

**Issue by H4kunaM4tata** [bambulab/BambuStudio#523]
When exporting the 3mf file, it generates a weird untitled file:

![image](https://user-images.githubusercontent.com/35049512/198290148-356e44de-07df-4b63-8e82-78c88ab5a69c.png)

When exporting it via g-code, you can have the output format like PrusaSlicer:

`{input_filename_base}_{layer_height}mm_{filament_type[0]}_{print_time}_{round(total_weight)}g.gcode`

![image](https://user-images.githubusercontent.com/35049512/198449150-d1ab4db1-fe62-436e-995e-afbde9a3b850.png)

That outputs the file as `fastbenchy_0.32mm_ASA_30m9s_10g.gcode`
 It is so much better and organized, while looking a folder with dozens of g-code, you can easily identify the file by its material, how long it will take and the amount of filament needed

![image](https://user-images.githubusercontent.com/35049512/198290823-7887bc4b-b231-4284-b0d9-711a678b421f.png)

Not a folder full of `Untitled_plate_1.gcode.3mf` files.

![image](https://user-images.githubusercontent.com/35049512/198291774-7e5062a8-d007-499c-9246-d5d94a937a68.png)

Thank you

**Comment by H4kunaM4tata** [comment]
SoftFever has implemented this change.
I am closing this.

**Comment by FoldZero** [comment]
the setting is missing from latest\current release
![image](https://github.com/bambulab/BambuStudio/assets/12484386/c79af64c-a5a6-4f4a-991d-ff1f61d31972)
