### ISSUE TITLE
Ralentissement de Bambu studio

### ISSUE THREAD

**Issue by CyriusWhit** [bambulab/BambuStudio#5247]
### Bambu Studio Version

01.10.00.89

### Where is the application from?

Bambu Lab Official website

### OS version

Mac os Sequoia 15.1 (24B83)

### Additional system information

Processeur: 3,8 GHz Intel Core i7 8 cœurs
Graphique : AMD Radeon Pro 5500 XT 8 Go
Memoir: 8 Go 2667 MHz DDR4

### Printer

X1c

### How to reproduce

Ralentissement important du logiciel quand un model stp ou 3mf  est ouvert.
Ce phénomène est présent depuis la mise a jour.

### Actual results

Une attente qui vas de quelques secondes a plusieurs dizaines de secondes.

### Expected results

Un résultat que avant.

### Project file & Debug log uploads

[debug_Fri_Nov_01_14_44_16_583.log.0.zip](https://github.com/user-attachments/files/17739786/debug_Fri_Nov_01_14_44_16_583.log.0.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by HO44-PROJECT** [comment]
cas similaire corrigé avec la 1.10.1.50: 
https://github.com/bambulab/BambuStudio/issues/5194
