### ISSUE TITLE
mac端容易卡死

### ISSUE THREAD

**Issue by zeng89** [bambulab/BambuStudio#5255]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

MacOS 14.6.1

### Printer

X1Carbon

### How to reproduce

下载好复杂模型后点击切片

### Actual results

然后就卡死，导致程序无响应

### Expected results

可以正常打印

### Project file & Debug log uploads

无

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
Hello, I'm very sorry for the inconvenience caused to you. Excuse me, is it a multi plate project? We found that single plate projects do not work.

**Comment by pridi** [comment]
> Hello, I'm very sorry for the inconvenience caused to you. Excuse me, is it a multi plate project? We found that single plate projects do not work.

Hello, yes, it is a multi plate project. I can confirm that by **using only one plate** I do not have the problem. Hope the problem with multi plate project will be fixed soon!

**Comment by zeng89** [comment]
> I have the same issue!

1.10.0.89 will be ok，you can try this

**Comment by zeng89** [comment]
> Hello, I'm very sorry for the inconvenience caused to you. Excuse me, is it a multi plate project? We found that single plate projects do not work.

you can try version  1.10.0.89

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

**Comment by pridi** [comment]
> It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon! Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

Thank you very much! It's working perfectly
