### ISSUE TITLE
Bambu Printer Order Under Device Tab is not in alphabetical order - its random?

### ISSUE THREAD

**Issue by rhys100** [bambulab/BambuStudio#526]
![image](https://user-images.githubusercontent.com/8174496/198417428-15054d09-a3aa-40e7-8fda-dd1b8cf2f4f5.png)

Noted that under print menu however it is in order

![image](https://user-images.githubusercontent.com/8174496/198417500-9a018df9-231d-4a8c-8b10-9817e3aa7729.png)

**Comment by YifanWuBambu** [comment]
We will order the devices according to their names in recent release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
