### ISSUE TITLE
Bambu-Studio 

### ISSUE THREAD

**Issue by Hoelenmensch** [bambulab/BambuStudio#5268]
### Bambu Studio Version

1.10.0.89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10 / 11

### Additional system information

AMD Ryzen 7 5700U with Radeon Graphics            1.80 GHz
16,0 GB (15,4 GB verwendbar)
64-Bit-Betriebssystem, x64-basierter Prozessor
Windows 11 Home

### Printer

X1C / P1s

### How to reproduce

1. Datei importieren
2. ausgewählte step - datei import
3.  Parameters setzen
4. okay drücken

![bambu fehler](https://github.com/user-attachments/assets/47ae6c71-e478-4a82-999f-e8170242b5fe)

### Actual results

Das bambu - Studio bricht ab
![bambu fehler](https://github.com/user-attachments/assets/1b35e421-b594-4a26-964c-3b091b20ded2)

### Expected results

es sollte die ausgewählte step - datei geöfnnet werden.
was nicht möglich ist
![bambu fehler](https://github.com/user-attachments/assets/26d36057-c596-4d4c-b196-0bdae89a8715)

### Project file & Debug log uploads

[connection.zip](https://github.com/user-attachments/files/17754442/connection.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Hoelenmensch** [comment]
in der version 1.09.0752
hat alles geklapt

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg

**Comment by MackBambu** [comment]
fixed
https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
