### ISSUE TITLE
[Bug] print cancelled from front panel generates mysterious "[0300 400C]" warning on windows app

### ISSUE THREAD

**Issue by bani6809** [bambulab/BambuStudio#527]
cancel a print from the x1 front panel, it generates a mysterious "[0300 400C]" warning on the windows app.

![0300 400c](https://user-images.githubusercontent.com/43738861/198499936-647b8dea-8185-4dad-87c4-6bf494077e2f.png)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
