### ISSUE TITLE
[Bug] black filament objects impossible to see in prepare

### ISSUE THREAD

**Issue by bani6809** [bambulab/BambuStudio#528]
it's impossible to see black filament objects in prepare
![prepare black](https://user-images.githubusercontent.com/43738861/198500571-fc362cba-a257-4ccd-9bd3-7f2bc79ecae4.png)

**Comment by lanewei120** [comment]
Hello

thanks for reporting this issue
1. what is your studio version?
2. Could you give a full picture of your studio with the plate included?
3. could you give the information of your graphics card and the driver version?

**Comment by RobinWhitfield** [comment]
@bani6809, this looks more like a graphical glitch displaying the bed surface than an issue with part colour (see #199 for that one).

it should look more like this:
![image](https://user-images.githubusercontent.com/63362209/198720327-6e4f1d52-74df-4047-9927-28b795dc11c4.png)

**Comment by Benderrodrigu3z** [comment]
best answer is tell the slicer that's that AMS slot is Gray filament, now you can see and print that slot
