### ISSUE TITLE
Problém z importem STEP 

### ISSUE THREAD

**Issue by winwinzionmarko** [bambulab/BambuStudio#5281]
### Bambu Studio Version

1.10.0. 89

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Additional system information

When importing STEP files, the new dalog field asks you to define refinement sliders. By dragging one slider, the software counts infinitely. Touching the second slider will cause the software to crash instantly. Error prompt: Unknown exception unhandled; Quit the application. This happens regardless of the file size or the specified specification you choose

### Printer

X1 carbon

### How to reproduce

. 

### Actual results

Zavře program 

### Expected results

![IMG_20241113_075457](https://github.com/user-attachments/assets/6c2c9a91-8869-469b-9386-5e48f7a0f77b)
![IMG_20241113_075544](https://github.com/user-attachments/assets/f4f1aa60-035b-44c0-a788-8374ef20f78f)

### Project file & Debug log uploads

Ujg

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by MartinChan3** [comment]
It seems that Studio has released a temporary package to provide an interim solution for those experiencing issues on Mac (Intel chip), STEP import crashes, and missing temperature displays. Hopefully, they will release the actual hotfix soon!
Windows：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_win_public-v01.10.00.94-20241114223322.exe
Mac：https://github.com/bambulab/BambuStudio/releases/download/v01.10.00.89/Bambu_Studio_mac-v01.10.00.94-20241114223322.dmg
