### ISSUE TITLE
App Crashes while turning video on

### ISSUE THREAD

**Issue by WonderMr** [bambulab/BambuStudio#5284]
### Bambu Studio Version

1.9.7.52

### Where is the application from?

Bambu Lab github releases (Bambu_Studio_linux_fedora.AppImage)

### OS version

Arch Linux Rolling Release

### Printer

A1 mini

### How to reproduce

1. Start Bambu Studio App
2. Go to Devices
3. Press green play button

### Actual results

App hangs and then crashes

### Expected results

Video playing in working Bambu Studio app

### Project file & Debug log uploads

[log.tar.gz](https://github.com/user-attachments/files/17774126/log.tar.gz)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by lanewei120** [comment]
@WonderMr could you try  the newest version https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50

**Comment by WonderMr** [comment]
> @WonderMr could you try the newest version https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
It fails to run at all
Log and strace log attached
[strace_output.txt](https://github.com/user-attachments/files/17798559/strace_output.txt)
[debug_Mon_Nov_18_14_10_27_354922.log.0.txt](https://github.com/user-attachments/files/17798598/debug_Mon_Nov_18_14_10_27_354922.log.0.txt)

**Comment by lanewei120** [comment]
> > @WonderMr could you try the newest version https://github.com/bambulab/BambuStudio/releases/tag/v01.10.01.50
> 
> It fails to run at all Log and strace log attached [strace_output.txt](https://github.com/user-attachments/files/17798559/strace_output.txt) [debug_Mon_Nov_18_14_10_27_354922.log.0.txt](https://github.com/user-attachments/files/17798598/debug_Mon_Nov_18_14_10_27_354922.log.0.txt)

which app image are you using?
fedora or ubuntu?
how about the ubuntu images?

and do you mean bambu-studio crashed after bootup?

**Comment by lanewei120** [comment]
is it possible for you to use gdb to run?
$gdb xxxx.appImage
>run
after it crashes
>bt
paste the callstack here

**Comment by WonderMr** [comment]
hmm, if i run directly from console `/opt/bambustudio-bin/bin/bambu-studio`, it works fine. Video, also, works fine you!

if using .desktop file with same file path it crashes. Nevertheless, it's not an issue, which this case related.
I would like to confirm that the problem has been resolved. Thank you very much.

**Comment by WonderMr** [comment]
Thank you
