### ISSUE TITLE
[Bug] Mysterious [0700 8006] warning in bambu studio

### ISSUE THREAD

**Issue by bani6809** [bambulab/BambuStudio#533]
bambu studio shows mysterious [0700 8006] warning with no explanation.

![image](https://user-images.githubusercontent.com/43738861/198828873-b85a425d-6da1-40dc-9018-c83be04901b0.png)

**Comment by StoneLiBambulab** [comment]
the error is "Failed to feed the filament into the toolhead. Please check whether the filament or the spool is stuck. After troubleshooting, click the retry button."

we will fix the bug.

Stone Li

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
