### ISSUE TITLE
Brim must take precedence over supports

### ISSUE THREAD

**Issue by nnobuddy** [bambulab/BambuStudio#5333]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

Bambu Lab X1C

### How to reproduce

1. Prepare, Support Painting => paint supports.
![Brim3](https://github.com/user-attachments/assets/e5d19f28-0406-4f9f-b723-2170e65fa5b6)

2. Prepare/Preview, Support => set parameters.
![Brim4](https://github.com/user-attachments/assets/690d984e-6923-43de-b5bb-1f3d207ccdcf)

3. Prepare/Preview, Bed adhesion => set parameters.
![Brim5](https://github.com/user-attachments/assets/ab460726-a3c2-4354-99b0-2e96c75250bd)

### Actual results

See the gaps between the object and the support on the first layer. The gap between the object and the support is much bigger then the gap between the object and the brim.
![Brim5](https://github.com/user-attachments/assets/301ae2ba-18b5-48fe-9b40-b473b48c8819)

Print fails with Plate Type = Smooth PEI Plate / Hi Temp Plate (noname), even if the plate is cleaned with isopropyl alcohol. 
![Brim6](https://github.com/user-attachments/assets/a7f10f17-2cfe-4ecc-9f0b-d06ad0203be3)
![Brim7](https://github.com/user-attachments/assets/006cc2dd-a57c-41a7-a0a4-f171d545970d)

### Expected results

Print should not fail.

Print does not fail with Textured PEI Plate. Unfortunately, the bottom surface of the object is not smooth.

### Project file & Debug log uploads

[Prsten04-17-18-19_2.zip](https://github.com/user-attachments/files/17807250/Prsten04-17-18-19_2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by JohnSmithCYM** [comment]
It seems that you should use 'Support first layer gap' to get what you want.
![image](https://github.com/user-attachments/assets/0cb3ae0a-672c-45aa-b0ab-244d2ead2e5b)

**Comment by nnobuddy** [comment]
Thank you very much for your help.

Print fails either way (on higher Z value). Unfortunately, I can't use glue to increase adhesion. I'm going to investigate the thing... :-)

**Comment by JohnSmithCYM** [comment]
Do you know bambu has just released a new plate, I bought one and use it with studio, it sticks a lot.(I have to say even it sticks too much because I can't remove some parts from it easily lol)

**Comment by JohnSmithCYM** [comment]
The ShiningStar plate is a 3rd-party plate but it looks good :heart: ,maybe it could produce a good bottom surface.Good luck with your print.
