### ISSUE TITLE
Bambu printer missing from bambu studio

### ISSUE THREAD

**Issue by Zeds34** [bambulab/BambuStudio#5336]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 11 Pro 23H2

### Additional system information

AMD Ryzen 9 7950X 16-Core Processor 4.50 GHz, 64 g ram, video card RX7700XT 12 Go.

### Printer

X1C 2x AMS

### How to reproduce

This morning when opening Bambu Studio a message says to update the models and my X1C has disappeared from bambu studio, I am looking to add a printer there is no printer in the bambu lab brand selection.

![001](https://github.com/user-attachments/assets/e9961bc3-1a7b-42bd-bf50-706c7637dc77)

### Actual results

The Bambu Lab brand has disappeared from the printer selection.

![001](https://github.com/user-attachments/assets/5922ceed-98df-4a00-9e76-51103542a512)
![002](https://github.com/user-attachments/assets/c19240e1-f238-4f99-9ca9-00a5f48429c9)
![003](https://github.com/user-attachments/assets/7c50b3ac-0908-4b94-995c-edc52fb71c13)
![004](https://github.com/user-attachments/assets/e87f37f4-8bae-434b-8d8b-592cdaa61b78)
![005](https://github.com/user-attachments/assets/da909f33-8056-46f1-841b-d5e8d11cc8fd)
![006](https://github.com/user-attachments/assets/0ac122f6-522b-47d0-aae7-e34b9bb15699)
![007](https://github.com/user-attachments/assets/4c14f47b-0203-4dc3-9b3b-b649cf96491d)
![008](https://github.com/user-attachments/assets/c53211bd-4b30-4157-ac9e-ce5d121d4971)

### Expected results

Bambu brand printers should be displayed in printer additions. Bambu Lab should be there.

### Project file & Debug log uploads

![009](https://github.com/user-attachments/assets/48d95d36-2172-4cf8-8363-81d64763a2d7)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Lex74M** [comment]
I have the same issue and cannot set up a printer as my bambu lab p1s is no longer in the list of printer options.....
Help

**Comment by tommyboy180** [comment]
I'm unable to replicate. 

https://github.com/user-attachments/assets/d1f62b3c-eab4-42fb-a644-611edfe499ca

**Comment by ttt888zzz** [comment]
HI [Zeds34](https://github.com/Zeds34)、 [Lex74M](https://github.com/Lex74M)：Please try uninstalling and reinstalling BambuStudio
 Download the latest installation package, please visit：https://bambulab.cn/zh-cn/download/studio

**Comment by Zeds34** [comment]
I reset and everything came back. Thanks for the support.
