### ISSUE TITLE
Feature Request: Cancle on a per Object basis

### ISSUE THREAD

**Issue by TMeeib** [bambulab/BambuStudio#534]
It would be great to be able to cancle individual objects on a single build plate. If you encounter adhesion problems for one object but not the others you have only 2 bad choices right now:
1. Cancle the print and take the filament loss on all the objects you printed so far
2. Let everything run and lose more filament on the failed object and reprint it later

It would be great to be able to cancle a single object and let the rest of the print finish as intended. I am not sure how easy it is to change the G-Code and remove an item without re-slicing or if it is even possible but I think it would be a really useful feature.

Example attached:
In this case I would like to cancle the object on the left and let the one on the right finish.
![image](https://user-images.githubusercontent.com/112700033/198831660-ca2f641a-e23b-4695-84cd-05e2b494b34e.png)

**Comment by SaltWei** [comment]
This has be supported in latest studio and latest X1C firmware. Enjoy!
