### ISSUE TITLE
[Bug] Support Filament Selection not working to select the proper filament

### ISSUE THREAD

**Issue by psiberfunk** [bambulab/BambuStudio#536]
When I'm trying to tell Bambu Slicer to use a specific filament for support structures, it seems to ignore the setting!

![image](https://user-images.githubusercontent.com/19777571/198838391-11bba2df-e6ba-452a-9923-7bd2db52b4b3.png)

**Comment by psiberfunk** [comment]
[ProblemSupportColor.zip](https://github.com/bambulab/BambuStudio/files/9893923/ProblemSupportColor.zip)

**Comment by SaltWei** [comment]
Close for not bug
