### ISSUE TITLE
P1S camera stuck at "Initializing..." after BStudio update 1.10.1.50

### ISSUE THREAD

**Issue by RaphTronic** [bambulab/BambuStudio#5367]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows 10

### Printer

P1S firmware 1.05.02.00

### How to reproduce

Slice model, send to printer, click on the video start button.

### Actual results

Camera window displays the BL logo but no camera feed. Status reported is "Initializing..." (pic attached)

![bambu studio 1 10 1 50 failing camera screenshot](https://github.com/user-attachments/assets/f77ac2b2-d943-4386-8eb6-2aeaf327c425)

### Expected results

Camera should display a feed like before with BStudio 1.9.1.66

### Project file & Debug log uploads

[debug_Thu_Nov_21_16_59_15_7024.log.zip](https://github.com/user-attachments/files/17853808/debug_Thu_Nov_21_16_59_15_7024.log.zip)

### Checklist of files to include

- [X] Log file
- [x] Project file

**Comment by kevlees** [comment]
mine is not connecting either to the camera live view with that same update!!

**Comment by AwakeProphet** [comment]
Hi every one,

Same problem here.

Log file attached below.
[debug_network_Tue_Nov_26_09_35_03.log.zip](https://github.com/user-attachments/files/17916535/debug_network_Tue_Nov_26_09_35_03.log.zip)

**Comment by cbserickson** [comment]
Same. Works from the iPhone app though.

**Comment by RaphTronic** [comment]
UPDATE: after reverting back to 1.9.1.66 the camera started working again.

**Comment by Arjenlodder** [comment]
Same problem here

**Comment by bambu123** [comment]
Please upgrade printer firmware.

**Comment by RaphTronic** [comment]
That worked !
Upgraded printer firmware from 01.05 to 01.07 and the camera now works with BS1.10
Will close the issue now.
Thanks.
