### ISSUE TITLE
Zooming out on latest update

### ISSUE THREAD

**Issue by mlcrabill** [bambulab/BambuStudio#5377]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab Official website

### OS version

Windows Enterprise 11

### Printer

Bambu Lab P1S

### How to reproduce

When I open Bambu Lab Studio and go to prepare - the build plate zooms way out. i can't move items and view it up close to be able to edit the items 

### Actual results

I try to zoom in and it automatically zooms out

### Expected results

I should be able to see the build plate up close

### Project file & Debug log uploads

na 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by tommyboy180** [comment]
Works fine. This isn't a bug. 

https://github.com/user-attachments/assets/3572bb60-c29c-4e34-bfe0-8a1f4c6b8a51

**Comment by mlcrabill** [comment]
Okay. Thank you for sharing. It’s bugging on mine (hence the request for support) and didn’t do that until I installed the updated. Michelle Crabill571-235-8342On Nov 23, 2024, at 10:19 AM, Tom Schaefer ***@***.***> wrote:﻿
Works fine. This isn't a bug.
https://github.com/user-attachments/assets/3572bb60-c29c-4e34-bfe0-8a1f4c6b8a51

**Comment by mlcrabill** [comment]
It wasn’t working after the update so I uninstalled the software and reinstalled it and now it’s working fine. Michelle Crabill571-235-8342On Nov 25, 2024, at 3:47 AM, Haidiye00 ***@***.***> wrote:﻿
Hello, can you download ScreenToGif software and record a GIF of the operation video and upload it? Thank you

**Comment by Haidiye00** [comment]
Okay, thank you
