### ISSUE TITLE
Feature Request - Add Arachne slicing function.

### ISSUE THREAD

**Issue by RobinWhitfield** [bambulab/BambuStudio#54]
As per the title.

PrusaSlicer 2.5 Alpha now has the Arachne slicing function - it would be great to have this implemented in Bambu Studio soon too.

**Comment by wuyifanfancy** [comment]
Will add this feature in recent release.

**Comment by moebis** [comment]
@wuyifanfancy when you say "recent release" do you mean 01.01.01.01 version released a couple of days ago has Arachne now? I didn't see it in the release notes.

**Comment by psiberfunk** [comment]
SuperSlicer also now adding this .

**Comment by hutje** [comment]
Would be a really valuable feature for printing with 0.6mm nozzle when printing with filaments that would otherwise clog the 0.4mm nozzle.

**Comment by danielclasen** [comment]
@hutje yeah, plus omitting those nasty gap fills between two walls that are just a hair apart the risk of a clog is even more reduced

**Comment by psiberfunk** [comment]
Yea, the 3D printing world has quickly all decided that Arachne is pretty awesome with relatively few downsides.  Cura really knocked it out of the park with this feature.

**Comment by RobinWhitfield** [comment]
This has been added, but I'm leaving the request open as it's only been added for specific slicing tasks.

I wholly expect additional Arachne in the future.

**Comment by psiberfunk** [comment]
> This has been added, but I'm leaving the request open as it's only been added for specific slicing tasks.
> 
> I wholly expect additional Arachne in the future.

Where has this been added ?

**Comment by RobinWhitfield** [comment]
You may have missed it, but 1.2.0.4 was released as a binary before they discovered a selection of bugs and removed it again.

I'm sure it'll be back again soon.

**Comment by psiberfunk** [comment]
But to my other questions : how is this a partial implementation of Arachne?

**Comment by RobinWhitfield** [comment]
I'm by no means an expert but I believe right now it's being used to avoid gap infill, but not perimeters. I think PrusaSlicer is almost the other way around, not using it for gap fill, but using it for perimeters

**Comment by SaltWei** [comment]
Arachne has confliction with overhang slowing down and overhang cooling feature of BambuStudio, so we can't apply it for wall at the moment.
When arachne is applied to walls, the line width of wall may be various rather than fixed. And then it's difficult to calculate how much percentage of width of the wall extrusion line is unsupported.

We are still trying to fix this confliction.

**Comment by psiberfunk** [comment]
You might look at Superslicer which has Arachne AND custom settings for overhangs

**Comment by Lesani** [comment]
would be important for objects containing letters...
Sliced with Prusaslicer 2.5.0 (alpha3)
![image](https://user-images.githubusercontent.com/5182104/204805714-9917334e-7ece-4b22-8fb2-e3c4fe53acd5.png)

Sliced with Bambu Studio 01.03.01.01
![image](https://user-images.githubusercontent.com/5182104/204805537-fc4653c3-8059-485e-bf49-b5dc0c03c845.png)

**Comment by Photogad** [comment]
Yesss,full Arachne! 🕷️

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
