### ISSUE TITLE
(BUG) Rotate object- Y and Z swap values and locations

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#541]
I rotated this object, made is smaller by cutting it then moved it into position, it was then not tall enough so I changed the Z value only to find that the object got larger on the Y access, and when I change the Y access the Z gets Larger, notice the colors for Z and Y have changed, Z is blue, its in the correct locations for moving the object and for rotation but when you switch so the scale menu the values are mismatched from the orientation of the object

![Screen Shot 2022-10-30 at 11 55 36 PM](https://user-images.githubusercontent.com/48887257/198934116-0ac935bd-fe55-4029-9f6e-abd04fad5fc7.png)

**Comment by zhimin-zeng-bambulab** [comment]
We plan to improve coordinate system in the future,  Thanks!

**Comment by Haidiye00** [comment]
The new version 1.10beta has been released. Please download and use~
