### ISSUE TITLE
Inconsistent results when Slicing - Some feature show, others don't.

### ISSUE THREAD

**Issue by NVNDO** [bambulab/BambuStudio#5411]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab github releases

### OS version

Windows 10

### Printer

Bambulabs P1S

### How to reproduce

Import files into different BambuStudio windows (put them side by side) - Slice and lower the layer-bar until reaching the 1st layer. 

Although both parts are similar in size, height, and have a 0.8mm wide forms (bodies) located at their bottom, the frame in the Hexagon shape will not be printed - meanwhile the frame, circle and dot do print in the square. 
![Screenshot (1335)](https://github.com/user-attachments/assets/04014d2e-c859-4a50-acc1-84d00cefef5e)
![Screenshot (1336)](https://github.com/user-attachments/assets/f9fae0aa-89de-4a2e-899e-c3cd63ef10c9)

### Actual results

![Screenshot (1337)](https://github.com/user-attachments/assets/f20fedd2-e5be-468d-974a-8e5972ba7afb)

- The Square shows its bottom line, ring and dot
- The Hexagon does not.

Why?!

### Expected results

- If the Square show its bottom line, ring and dot 
- The Hexagon should do the same

PD: Usually I make a cutout if a line, ring, dot or whatever should be present in the first layer, BUT the design requires not doing so, therefore I tried if layering bodies would actually work, and it does - but ONLY with certain designs. So something is off here. It should either never work or not, but not be totally random.

### Project file & Debug log uploads

[First line not showing.zip](https://github.com/user-attachments/files/17925263/First.line.not.showing.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by Nikonguy60** [comment]
When I upload a picture from hue forge to print and I have selected my colours, after slicing the only colour it shows it black and not the rest

**Comment by Nikonguy60** [comment]
That was not helpful

**Comment by NVNDO** [comment]
It's because you did not change the color in objects (see screenshots). When posting here I assume people know how to use the slicer. I don't wanna be rude, but if you can not help, pls don't comment. Cheers

**Comment by Nikonguy60** [comment]
Well just for the record I do know how to use the soccer and I did change
the colours. I think you were rude and I don’t appreciate that. There are
nicer ways of messaging people. Thank you very much!!

**Comment by zhimin-zeng-bambulab** [comment]
When multiple parts are coplanar on the same plane, we will give priority to the color of the part listed later in the object list. For the example in the picture, you can drag the black part below the orange part in the object list.
![image](https://github.com/user-attachments/assets/a6e1a8f5-b18d-42a6-9018-27e81dbb0b35)

**Comment by Nikonguy60** [comment]
Ok, thanks.

**Comment by NVNDO** [comment]
@zhimin-zeng-bambulab Oh wow... That is an unexpected & easy solution - I would probably have never tried that. Thank you so much!! 👍😊
