### ISSUE TITLE
Colored .obj file could not set total number of colors when imported

### ISSUE THREAD

**Issue by imadcat** [bambulab/BambuStudio#5417]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab Official website

### OS version

mac OS

### Printer

Bambu lab X1C

### How to reproduce

1. open an colored .obj file 
2. In the color selection pop up dialog window, click the input box next to "Specify number of colors:"
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/c354e8da-32fc-42a2-8462-d9b674748b65">

### Actual results

3. The default number "1" can not be edited

### Expected results

The default number "1" should be able to change

### Project file & Debug log uploads

[Flying_Panda_Joy_1127074645 colored.obj.zip](https://github.com/user-attachments/files/17932132/Flying_Panda_Joy_1127074645.colored.obj.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/4c6d5225-e19e-45f6-88f6-9fc8c2595e7d)
Hello, can you provide this MTL file

**Comment by imadcat** [comment]
> ![image](https://private-user-images.githubusercontent.com/132528822/390609928-4c6d5225-e19e-45f6-88f6-9fc8c2595e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTE5MzAsIm5iZiI6MTczMjgxMTYzMCwicGF0aCI6Ii8xMzI1Mjg4MjIvMzkwNjA5OTI4LTRjNmQ1MjI1LWUxOWUtNDVmNi04OGY2LTlmYzhjMjU5NWU3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxNjMzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGMzNjhjMTBkMjE2NDUzNjVmZDVmOThhOWMyMTY2MWM0ZGJmNzZjMDBiYTU2MTg1OWFjMWFlYTFkZjA2Mjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FKDPADqfFq0nUlPTZCyIu2I3E8-C4f7HkViIHf8y3ek) Hello, can you provide this MTL file

[Flying_Panda_Joy_1127074645 colored.mtl.zip](https://github.com/user-attachments/files/17950574/Flying_Panda_Joy_1127074645.colored.mtl.zip)

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/bdd805f5-4e0d-4456-a9e6-6bc68647c362)
Hello, there is only one material available here, so only one color can be modified, not multiple colors. If you want to modify multiple colors, first ensure that the original obj has multiple materials. You can also use other third-party software such as Blender or Mesh Lab to see if they can display multiple colors.

**Comment by Haidiye00** [comment]
![image](https://github.com/user-attachments/assets/70ffe80f-f70f-44ef-a9db-e5fccc74bdeb)
![image](https://github.com/user-attachments/assets/39d5ae0b-f72a-4d79-9cb9-5628feada95c)
Hello, this is a simple example, thank you~
