### ISSUE TITLE
3D feild / render area not showing?

### ISSUE THREAD

**Issue by nyan-star1** [bambulab/BambuStudio#5490]
### Bambu Studio Version

1.10.1.50

### Where is the application from?

Bambu Lab github releases

### OS version

Ubuntu 24.04

### Printer

Bambu Lab P1S

### How to reproduce

1. Open Studio
2,Open new project
3.Check prepare and preview

### Actual results

![image](https://github.com/user-attachments/assets/25cb178f-9080-470c-a8f3-edff22ee42b6)
![image](https://github.com/user-attachments/assets/a71cdaf9-db2c-4574-a55d-1c347102f7b7)

### Expected results

The 3D feild is missing, even after a reinstall of the software, both flatpack and github

### Project file & Debug log uploads

[log.zip](https://github.com/user-attachments/files/18050205/log.zip)

### Checklist of files to include

- [X] Log file
- [ ] Project file

**Comment by nyan-star1** [comment]
(bambu-studio:9358): Gtk-CRITICAL **: 00:43:39.818: gtk_cell_layout_get_cells: assertion 'GTK_IS_CELL_LAYOUT (cell_layout)' failed


Keeps displaying this in the terminal, unsure how to fix it.

**Comment by nyan-star1** [comment]
Issue was from being on Wayland without realizing, my bad.

**Comment by Luky109** [comment]
i have the same issiue

**Comment by Luky109** [comment]
![Snímek obrazovky 2025-01-01 132423](https://github.com/user-attachments/assets/9b7c7912-8b94-4fa3-b4a6-6a58e6888fa2)

**Comment by Luky109** [comment]
can you please tell me how do you fix it??

**Comment by nyan-star1** [comment]
> can you please tell me how do you fix it??
> 
> 

Yes! So! I was on Wayland, you need to use directX, when youre logging in you choose not to use Wayland, and it is fixed.

**Comment by Luky109** [comment]
What is directX

Dne st 1. 1. 2025 13:50 uživatel Nyan ***@***.***> napsal:

**Comment by Luky109** [comment]
I installed directx but i dont see it installed on my pc

**Comment by nyan-star1** [comment]
Give me a minute, need to formulate myself.

**Comment by nyan-star1** [comment]
Sorry, i mispoke, its X11, not DirectX, uninstall that.

X11 is a diffrent renderer.

What you need to do is, shut off your computer, when you log in, before clicking on your user theres a button in the bottom right, where you pick X11
