### ISSUE TITLE
Step Files crash BambuStudio on import

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#551]
[FL_X1_top lift.STEP.zip](https://github.com/bambulab/BambuStudio/files/9922648/FL_X1_top.lift.STEP.zip)

**Comment by SaltWei** [comment]
Can't reproduce this issue on the latest release version. My importing operation is shown as gif.
![can_not_reproduce](https://user-images.githubusercontent.com/110660407/199656016-eddd87d7-72e9-4544-b67e-1f9879abd857.gif)

**Comment by SaltWei** [comment]
What version or platform do you use? Mac or windows platform. My PC platform is windows.

**Comment by Benderrodrigu3z** [comment]
macOS Catalina 10.15.7
MacBook Pro 2012
16gb 1600 mhz ddr3
12tb ssd storage
2.6 ghz quad core intel core i7

**Comment by Benderrodrigu3z** [comment]
Please try the Zip file, the author has since fixed it on the site and removed the step files

**Comment by SaltWei** [comment]
Thank you very much for sharing!

Can't reproduce this issue on the mac computer I find.
![screenshot-20221110-172243](https://user-images.githubusercontent.com/110660407/201051502-f446ab2c-ca7f-4741-be3b-8189efe40756.png)
Is it possible to update the system of you mac? Since it's really hard for me to find a 2012 MacBook.

**Comment by SaltWei** [comment]
OK. Thnaks for response! I will try to find a 2012 to reproduce again.

**Comment by Benderrodrigu3z** [comment]
I have the same crash, I had to have someone else convert the file for me however fusion 360 can also convert it

Sincerely,
Shane F

**Comment by SaltWei** [comment]
Fixed patch has been merged. Please wait for the next release version.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
