### ISSUE TITLE
(BUG) Different Type SLICE Filament

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#552]
In Order to Print from AMS slot 4 in ASA slot ONE Must be ASA as well, it CAN'T be PLA even if Im not using it, even if there is no filament in it, it doesn't care was in 2 or 3 but 1 must be TOLD its the same type on Slice

![Screen Shot 2022-11-02 at 11 09 17 PM](https://user-images.githubusercontent.com/48887257/199646087-52320ccd-f9df-4b29-b5f1-ed74a5b1ff6e.png)
![Screen Shot 2022-11-02 at 11 09 02 PM](https://user-images.githubusercontent.com/48887257/199646091-33648da2-38ba-4288-beef-79777e2ad283.png)

**Comment by SaltWei** [comment]
A known issue when add negative part. Will be fixed in next release

**Comment by Benderrodrigu3z** [comment]
sounds good thanks, closing this
