### ISSUE TITLE
Slicing Problem?

### ISSUE THREAD

**Issue by theogott** [bambulab/BambuStudio#553]
I have a 7 MB File where the slicing seems not to work properly. 
Who can i send it to?

**Comment by Benderrodrigu3z** [comment]
upload a photo or gif of the issue here, if its an stl step or 3mf zip the file then drag it onto the Write screen, when you hit comment it will show it, if you want to see how it looks the preview screen will show you

**Comment by theogott** [comment]
[Uploading Slicing-Problem.zip…]()
Please take a look, it.
I can choose normal or hybrid support but the result is not satisfying.

**Comment by YifanWuBambu** [comment]
@theogott 
Seems it is not a solid model.
![image](https://user-images.githubusercontent.com/110661856/200222121-30eb98e1-8fc4-4677-a542-fb69849822b4.png)

**Comment by theogott** [comment]
Its directly out o the 3D Scanner. But .. it should slice somehow.
Whatever it is, it should slice and print ... not?

**Comment by YifanWuBambu** [comment]
The generated mesh is not a solid mesh, which is required by the slicer.

**Comment by theogott** [comment]
Ok, then the Slicer should make it solid or help he user to understand what he is doing wrong. 
How can it be made "solid"?
Is it a big deal? 
Can the slice offer me "Shall i make this to a solid mesh"?
And I click "Yes please"?
Most users probably do not know the difference, and this is just "Out of the scanner".
So Scanner -> 3D-Printer = 3D Copier
I believe that should work somehow.

**Comment by YifanWuBambu** [comment]
We can do some research of how to support this kind of mesh, but it may not be solved in recent release.

For now, it is suggested to check whether the scanner vendor has provided such a tool.

**Comment by theogott** [comment]
Ok, so a closed Mesh is currently needed to be able to slice things.
On long run anything should
a) be possible to slice
or
b) I need a clear error message that tell me what to do.
Maybe on the short run that is possible?
Does the slicer Know what the problem is?
Can he tell me "This mesh needs to be filled" or something?

**Comment by SaltWei** [comment]
> Maybe on the short run that is possible?

Hard to do this, should be handled from the source of mesh.
