### ISSUE TITLE
[BUG] Printer warnings/errors not displayed correctly in BS

### ISSUE THREAD

**Issue by cdsmakestuff** [bambulab/BambuStudio#558]
![Error Reporting Bug](https://user-images.githubusercontent.com/91162358/199819452-892b93a0-197e-45cb-b3f0-48ad79947486.jpg)
Bambu Studio fails to show actual error/warning message in Studio popup.

**Comment by Benderrodrigu3z** [comment]
there is no info here as to what you did before hand, hard to know what happened

**Comment by candre23** [comment]
> there is no info here as to what you did before hand, hard to know what happened

That's the problem - this happens whether you "do anything" or not.   I've had similar (maybe the same?) weird errors pop up at random times during a print.  Sometimes the printer stops printing, sometimes it doesn't.  It should never be throwing an error with no context, but that's exactly what it's doing.

**Comment by StoneLiBambulab** [comment]
Hi @cdsmakestuff  and @candre23,

Could you help to upload the studio log for me. here is the guide to get the studio log

https://wiki.bambulab.com/en/x1/troubleshooting/bambu-studio-log

Thanks!

Stone Li

**Comment by candre23** [comment]
Here's all the recent logs.

[log.zip](https://github.com/bambulab/BambuStudio/files/9986000/log.zip)

**Comment by StoneLiBambulab** [comment]
Hi @candre23 ,
    The language code is not set correctly. I will fix it in next release. You can try to switch to another language and switch back to your language. 

Thanks!

Stone Li

**Comment by debren27** [comment]
I've had this same problem for a while. Finally decided to look into it. Thanks for the easy fix!

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
