### ISSUE TITLE
[BUG SLICER] Slicer keeps deleting user preset

### ISSUE THREAD

**Issue by H4kunaM4tata** [bambulab/BambuStudio#559]
From time to time when opening the slicer, the user preset is gone:

![image](https://user-images.githubusercontent.com/35049512/199882898-7b8d3f6d-b46a-4028-ad6f-eed9cb3d429b.png)

![image](https://user-images.githubusercontent.com/35049512/199882917-af2fe3ba-41db-450c-9ffe-8146de9addcc.png)

![image](https://user-images.githubusercontent.com/35049512/199886972-6d434662-33e1-419b-be5d-beaf7210e01e.png)

Fix: Manually copy the files over from default to my user profile

![image](https://user-images.githubusercontent.com/35049512/199883023-377977fb-fd70-44ad-ba7e-58cd9c0b6fd5.png)

![image](https://user-images.githubusercontent.com/35049512/199887055-d0734c9a-7e64-4750-b4a5-8d042741ed9f.png)

Restart the slicer:

![image](https://user-images.githubusercontent.com/35049512/199883117-e2672fce-91e6-493b-b439-c84fa9ecdf19.png)

![image](https://user-images.githubusercontent.com/35049512/199883140-9f4c4722-f53b-45ed-9f24-35b5feb0a789.png)

This cannot be right?!?

**Comment by Benderrodrigu3z** [comment]
I feel that however there is a Save button to save the current settings, its to the right of that drop down in the last photo, see the Floppy Drive, that's there save button next to the Magnifying glass.
If you have the printer on and you told it what filament and color is in which slot when you hit the dropdown for filament it will display those options but they won't be filled in so you have to hit + 4 times then select them each individually, I get your pain its the same on the MacOS version. Just trying to help, perhaps your info with this will help them fix this bug.

**Comment by H4kunaM4tata** [comment]
> I feel that however there is a Save button to save the current settings, its to the right of that drop down in the last photo, see the Floppy Drive, that's there save button next to the Magnifying glass.

I actually noticed after opening this ticket that my preset is incomplete. There are profiles missing, changes that I had to hunt down screenshots to set them again.

Atm, after every change I do, I copy the user folder as backup.

For what it is worth, I do not have cloud sync enabled, I don't like cloud stuff and local management is a must, but it seems like it get lost somewhere and just deletes your profile.

Somebody mentioned that the fact I have a folder called 11xxxx means my slicer is logged which is true. 
On that same note, logging out from the profile will use the default profile and in theory no more issues but that also means you cannot access the camera anymore and because the camera isn't a true network camera, you cannot access it via RTSP with VLC for example.

**Comment by lanewei120** [comment]
Hello @H4kunaM4tata 

thanks for reporting this issue

could you upload the user presets to us for a check?
also please help to upload your logs when these preset are deleted

thanks

**Comment by H4kunaM4tata** [comment]
@lanewei120 could you please let me know where to find the log??

This is not a printer issue, it is a slicer one and I couldn't find a log option.

At the moment I am not logged but slicer still saves the presets under a folder with my Bambu Lab account id. 
If I delete it, it should use the default one but instead it recreates my user folder without the presets.
I have no cloud sync enable so that couldn't be the issue either.

I believe that is the problem.

Thank you

**Comment by lanewei120** [comment]
the user presets folder of me:
![image](https://user-images.githubusercontent.com/106916061/201065101-e6dea50e-632a-4910-860c-628fbdb1196e.png)

the log folder of me:
C:\Users\lane.wei\AppData\Roaming\BambuStudio\log

there are some .info files under your presets folder
it includes some state of syncing
so I need these files besides the logs to have a check

thanks

**Comment by lanewei120** [comment]
@H4kunaM4tata hello
are these issues still there?
could you help to upload the logs and presets for us to have a debug?

**Comment by H4kunaM4tata** [comment]
> @H4kunaM4tata hello
> are these issues still there?
> could you help to upload the logs and presets for us to have a debug?

@lanewei120 sorry for the lack of reply. I'll backup my presets first before logging back in and testing this again ASAP.

**Comment by H4kunaM4tata** [comment]
@lanewei120 
The problem seems to be the slicer getting lost when cloud syncing is disabled.

![image](https://user-images.githubusercontent.com/35049512/202886593-7d869ab6-f0b4-4779-8c12-21a25afc01b4.png)

This is how my profile looks like when I am logged. 
It creates a folder with an ID and any change is saved there.

![image](https://user-images.githubusercontent.com/35049512/202886640-61c42fd0-5743-4d12-8609-f5c0df636cf2.png)

When I logout, my user folder is deleted, the default folder is then set as default

Once I log back in:

- it creates my user folder back, an empty folder since I have no cloud sync enabled, that is expected
- it uses whatever presets the default profile has
- any new change is them saved in my user folder from now

My user presets is gone, once I log back in.

![image](https://user-images.githubusercontent.com/35049512/202886888-85893fd3-f9cd-4c52-9911-bf536f69cd06.png)

If you logout, any preset change gets deleted.

The slicer should not delete the user folder preset once you have logged out or at least ask if you wanna keep it or delete it.
It just deletes the folder on its own.

To avoid this behavior, do not login:

![image](https://user-images.githubusercontent.com/35049512/202886983-e0f31caf-52b9-43e2-8176-4ac4135f3116.png)

Restore the backup I started doing to the default profile: ( I started doing a backup every time I change anything to avoid getting my presets deleted )

![image](https://user-images.githubusercontent.com/35049512/202887004-4f2102d4-fed4-42af-8fe9-53506cec1c95.png)

All presets are back:

![image](https://user-images.githubusercontent.com/35049512/202887054-b4a4b280-64e3-4b44-9128-140f52d38322.png)

For security reasons, the logs were edited.
I am not sure how I feel about log keeping both ID and token in plain text.
I am not logging in again, all the logs were deleted.
No application should ever log those piece of information, it is a security issues.

[log.zip](https://github.com/bambulab/BambuStudio/files/10048935/log.zip)

**Comment by StoneLiBambulab** [comment]
Hi @H4kunaM4tata ,
 i will fix it in next release and remove the token from logging file.

Thanks!

**Comment by H4kunaM4tata** [comment]
> Hi @H4kunaM4tata ,
>  i will fix it in next release and remove the token from logging file.
> 
> Thanks!
> 
> 

Thank you for that, I'm closing this ticket.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
