### ISSUE TITLE
Jagged edges and missing layers in 1.03

### ISSUE THREAD

**Issue by kebabskal** [bambulab/BambuStudio#560]
![image](https://user-images.githubusercontent.com/2920473/199910985-00b0fbaf-7710-4e33-bfbf-287d13b870c1.png)

Edges have random jaggy shifts and sometimes appears as if a layer is missing.
It looks like some layers are randomly shifted in the z-direction.
It seems to happen with any of the standard settings.

**Steps to reproduce:**

1. Add primitive cube
2. Rotate cube 10 degrees around the X axis
3. Click Slice
4. Observe the error

**Comment by SaltWei** [comment]
Thank you very much for reporting issue to us!

Could you share a 3MF file for us to reproduce?

**Comment by kebabskal** [comment]
Tried reinstalling the same version that this used to happen on, but can't seem to replicate anymore. Very strange.
It was consistently happening when I posted the issue.

Closing since I can't replicate.

Thanks!
