### ISSUE TITLE
2nd Camera Upgrade Option Add-on

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#575]
Please add a camera splitter cable along with a second camera for top down viewing to the website as a buyable option, might only be able to view one camera at a time but that's way with a swipe or a button to switch screens

**Comment by YifanWuBambu** [comment]
Hi @Benderrodrigu3z ,
For hardware requirements, please move to https://forum.bambulab.com/ for better support. Thanks!

**Comment by Benderrodrigu3z** [comment]
Moved to
https://forum.bambulab.com/t/2nd-camera-upgrade-option-add-on/899
Feel free to heart over there after making your username
