### ISSUE TITLE
[UI] Replace error codes with words

### ISSUE THREAD

**Issue by Scarfmeister** [bambulab/BambuStudio#577]
If there is an error code, I should be able to tell what the error is from the slicer. It's great that the dialog box pops up, but I have no idea what the issue is until I go to the printer. It would be great if there was a hyperlink to the Wiki page for that error like when you scan the QR code on the printer, even if the page currently isn't completed.

We should also be able to press continue from the dialog box if it's something like spaghetti detection and was a false positive (basically anything that wouldn't require user interaction at the printer).

**Comment by YifanWuBambu** [comment]
@Scarfmeister 
Could you take a screenshot of the code that does not go along with a text explanation?
This may be a bug.

**Comment by Scarfmeister** [comment]
![0C008002](https://user-images.githubusercontent.com/115429218/201451008-75ad5cc1-0048-47d6-8886-faae0bcad5de.png)
![0300400C](https://user-images.githubusercontent.com/115429218/201451009-d4696602-4e19-4624-a690-8f13069ffa1a.png)
![03008001](https://user-images.githubusercontent.com/115429218/201451010-5fc7e1a3-120f-4f82-8ec5-6dbb061af89c.png)
![03008003](https://user-images.githubusercontent.com/115429218/201451011-fd23bc0d-d323-4e11-bb0e-3d000254ec83.png)
![03008005](https://user-images.githubusercontent.com/115429218/201451012-fbc903a3-a5ce-47bb-bc89-1a8ce0093a79.png)

Sorry it took so long, had to get a print job that would produce error codes.

**Comment by YifanWuBambu** [comment]
Thanks a lot! We will fix it in the next release.

**Comment by StoneLiBambulab** [comment]
Hi Scarfmeister,
    Could you please help to upload the studio log. thanks!

Export studio log as following:
https://wiki.bambulab.com/en/x1/troubleshooting/bambu-studio-log

Stone Li

**Comment by Scarfmeister** [comment]
[Log_Files.zip](https://github.com/bambulab/BambuStudio/files/10032815/Log_Files.zip)
Here's log files from the 4th to this morning.

**Comment by Scarfmeister** [comment]
[BambuStudio.zip](https://github.com/bambulab/BambuStudio/files/10052109/BambuStudio.zip)

**Comment by StoneLiBambulab** [comment]
Hi @Scarfmeister，

    The language code is not set correctly. I will fix it in next release. You can try to switch to another language and switch back to your language.

Thanks!

Stone Li
