### ISSUE TITLE
[Feature] Allow materials on a build plate if never touching the plate

### ISSUE THREAD

**Issue by Scarfmeister** [bambulab/BambuStudio#579]
If printing with a material for a support interface on the Engineering Plate, the slicer says it is not compatible, but it is never touching the build plate during the print. If the temps are close enough to the other material(s) being printed, it should be allowed.

**Comment by YifanWuBambu** [comment]
@Scarfmeister 
We are considering this feature. Thanks for the suggestion.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
