### ISSUE TITLE
Keep top surfaces out of sparse infill volumes

### ISSUE THREAD

**Issue by Your-Saviour** [bambulab/BambuStudio#580]
I am not sure whether this is a feature or a bug. If it is a feature it would be nice to have a toggle as it can affect part quality, this will make more sense later.

**Problem**
This all started when I was trying to print this part
![image](https://user-images.githubusercontent.com/36687013/200226198-0d5cabd1-3629-4282-97cc-7ee52d1dba33.png)

As you can see, it has a raised bezel and a large recessed area.

Upon taking  it out of the printer I noticed this distant line
![317AAF0D-4CA3-4CD6-8C9E-A29E0837A73C](https://user-images.githubusercontent.com/36687013/200226368-ce1b8b23-046d-4e2c-a317-95d52faa3f27.jpg)

I've done my best to take a photo of it but it's more pronounced in person (Can provide more photos), it looks exactly like a slight layer shift and that's originally what I thought it is.

**Cause**
During slicing Bambu slicer is putting a top surface throughout the entire recess including under where the bezel needs to go.
![image](https://user-images.githubusercontent.com/36687013/200227099-9f9a56c7-1fea-4b52-ae77-f26a43f7d826.png)
See how the top surface is being printed directly underneath the infill for the bezel. This is creating a noticeable line in the final product.

This is a recreation just using simple shapes and a negative part.
![image](https://user-images.githubusercontent.com/36687013/200227803-b111aaab-472f-4a03-9b62-6e41cae10cd2.png)
The top surface is printed larger than what it needs to be.  This could be a setting that I have missed but I have asked around the discord already and no one can find anything. 

This is what I think it should look like
![image1](https://user-images.githubusercontent.com/36687013/200227240-76a37df4-bad3-4c8d-975c-b93b25680d2b.png)
This is sliced in Cura using the standard Ender 3 0.16 profile. As you can see there is no yellow top layer printed underneath the bezel.

Can provide a .3MF file upon request it just won't let me upload it. However, it should be easy to reproduce.

Talking a guess this is done for part strength, It would be nice to have the option to set how much extra top surface is printed as this does affect print quantity on certain parts.

**Comment by SaltWei** [comment]
Could you share the model for us to reproduce?
Thank you for reporting issue for improvement!

**Comment by Your-Saviour** [comment]
Here you go! :)
[this-is-broken.zip](https://github.com/bambulab/BambuStudio/files/9948645/this-is-broken.zip)

**Comment by Your-Saviour** [comment]
Sorry didn't mean to close this

**Comment by Your-Saviour** [comment]
It doesnt seem to let me reopen this, I don't know why the default is to close it if I comment lmao

**Comment by SaltWei** [comment]
> The top surface is printed larger than what it needs to be

Yes. This is same with prusa, and we guess the purpose is avoiding the situation that internal bridge has no anchor.
Cura indeed has better line handling which can make internal bridge be anchored well, without enlarge the area too much. And we will learn from it.

But anyway, this is not the root cause of this issue. The rootcause is 25% infill/wall overlap. When print fastly, the two walls are not cooled enough, and be squeezed when print infill, expecially when print solid infill.
1 Reducing infill/wall overlap, but this may cause reverse pulling and gap between infill and wall.
2 Printed slowly. I reduced inner wall, outer wall and internal solid speed speed to be 100 mm/s.
Printed with my X1C. The final model looks better now.

![20221108-092210](https://user-images.githubusercontent.com/110660407/200450796-fed996bf-ddde-42c4-993e-2293b2364aaf.jpg)

**Comment by Your-Saviour** [comment]
Thank you for your time looking at this issue, 
I hope something good eventually comes from it.

**Comment by SaltWei** [comment]
Cura is without the expansion of top surface, but also has other side effect. See the floating small solid infill inside sparse infill.
![image](https://user-images.githubusercontent.com/110660407/202173005-970c0e5d-b2c9-4990-ab69-1188e879f24b.png)
Prusa also has same with issue. But with the expansion, it's higher possibility to be printed successfully.
This is a model shown below.
![image](https://user-images.githubusercontent.com/110660407/202173264-d9d5597d-2bff-4b36-8d1d-fcfa3d3ce941.png)
Interesting issue and will keep on it.

**Comment by Your-Saviour** [comment]
Thanks for continuing to look at this, appreciate you and the team's effort! :)
