### ISSUE TITLE
Please Allow hiding (Toggle) of Model name boxes

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#583]
@YifanWuBambu 

The new version of studio now shows the model name in a box in front of the model, and all the model parts in multi-part models have these boxes which completely cover the model and are impossible to work with.

Please provide a toggle on the right side, or a button inside preferences to turn this on and off.

**Comment by randyre** [comment]
**Are we going to address this?** I don't know why the labels even were a feature, it wasn't in the previous versions and I've not found a ticket asking for them.  They are just all sorts of in the way. I can't be the only one that finds this unacceptable. Does BL even use its own slicer?  I can hardly use it, especially for small parts, as it completely covers the part.

**Comment by KD7LRJ** [comment]
In Prusa Slicer its hotkey is "E". This doesn't work in BS, but I wish it would. The feature is nice (sometimes) when trying to identify parts on a build plate. I can see how it would be unusable with lots of parts and no way to turn it off. I wasn't able to find anything in the UI to turn it on/off in BS.

![image](https://user-images.githubusercontent.com/2763408/201488692-960bb346-29cf-4c7a-91c1-5c17310b99f0.png)

**Comment by Merlwynd** [comment]
Agree this should have a toggle off. I would never use it as typically and familiar with all the parts I print.

**Comment by randyre** [comment]
@KD7LRJ @Merlwynd
Whew, thanks, thought I was going crazy and was the only one that thought these got in the way.

**Comment by YifanWuBambu** [comment]
Will be optimized as not auto-show the label when switching to by-object sequence in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
