### ISSUE TITLE
"Normal"="No Support"?

### ISSUE THREAD

**Issue by theogott** [bambulab/BambuStudio#584]
![2022-11-08 12_34_45-](https://user-images.githubusercontent.com/68653812/200559198-8271e84e-a53f-4f8a-8a7a-9ea23d5df411.jpg)

![2022-11-08 11_49_57-](https://user-images.githubusercontent.com/68653812/200559772-d119b2b1-0c16-417f-a10a-560d4bb8b67f.jpg)

Both pictures show the same Model.
The only difference is the setting of Support to "Normal".
Is it Ok, that in this case no support at all is generated?
Maybe the translation is wrong and "Normal" should be "No Support" ?

Please also see these horizontal lines in the Slice. 
Why are they there?

**Comment by YifanWuBambu** [comment]
For "normal" type, support will be generated only at the place where is painted in "Support Painting" tool by users.
![image](https://user-images.githubusercontent.com/110661856/200569595-2877e22d-4381-447f-a2ee-c41cb9e5d4ef.png)
![image](https://user-images.githubusercontent.com/110661856/200570058-5d518257-b8fb-492f-bfea-e26735521488.png)
![image](https://user-images.githubusercontent.com/110661856/200570109-07b12935-b36c-4639-b3db-61ce19bb975e.png)

**Comment by theogott** [comment]
Thank you for the explanation, in this case i would suggest that the Spelling "Normal" and "Tree" is misleading.
Maybe you can add "User Normal" and "User Tree" to make clear that this is the setting for "User Generated Support".

Secondly could you take a look on these significant horizontal lines in the Slicing?
Where do they come from?
![image](https://user-images.githubusercontent.com/68653812/200656859-c80f1fa6-651e-482d-80c9-dd558ec3ac7e.png)
![image](https://user-images.githubusercontent.com/68653812/200656909-93690a3f-149e-4b15-8914-e38e7a2bb128.png)
![image](https://user-images.githubusercontent.com/68653812/200656967-2053d364-6736-41cc-982c-eb8100a03af6.png)

**Comment by YifanWuBambu** [comment]
@theogott 
Thanks for the suggestion. Maybe we will change it to
1. Normal(auto)
2. Tree(auto)
3. Normal(manual)
4. Tree(manual)

For the slicing issue, could you share your model with us?

**Comment by theogott** [comment]
Hallo Yifan Wu,
thanks for your fast and kind response.


I will like to share this nice chinese dragon model with you, but it has 138 MB so i can not attach it here, 
You can download it from WeTransfer for the next few days using this Link:
[WeTransfer-Link](https://wetransfer.com/downloads/7927c93ef837db85809144bdde56e0b120221109071815/0301895f5356d9fff5ff5f398e6968ea20221109071856/774ac2 )

Now let me share the real printout and the picture in the slicer.

![image](https://user-images.githubusercontent.com/68653812/200761313-b41fc671-e4d2-4c40-af0f-1f7aae905f11.png)

![image](https://user-images.githubusercontent.com/68653812/200761833-a4aa3d44-8b5c-4fe5-902c-128f1e188e92.png)

**Comment by YifanWuBambu** [comment]
Thanks. We will fix it in the next release.

**Comment by YifanWuBambu** [comment]
We will check it.

**Comment by theogott** [comment]
Thank you Yifan Wu, if you have written it down, you can close the case here.

**Comment by YifanWuBambu** [comment]
@tangketan will close it after it has been fixed.

**Comment by tangketan** [comment]
The option names have been changed.
Another risk in this project is the normal support used. Since normal support won't grow its horizontal span, too tall support is very risky. I would suggest you to use hybrid(auto) or tree(auto).
![image](https://user-images.githubusercontent.com/13730459/201601224-d1ba4279-5cb9-4654-be20-a38abafd0a44.png)

**Comment by theogott** [comment]
Could you remove the Lines in the support?
If a support thickness of 1 line is to small for large supports, maybe you can print the lower part with multiple lines and the upper part with 1 Line?
