### ISSUE TITLE
Allow Model To "Sink" Into Build Plate Without Resetting To First Contact Point

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#585]
In Prusa Slicer, I can lower the model below the print surface and then slice it. I do this sometimes to make sure that there is a flat 1st layer. The workaround is to use the cut feature which works well on a single-color model. However, if you cut a painted muti-color model, the slicer will remove all of the painting requiring the user to repaint. This can be time consuming. This becomes especially useful when importing previously painted models from PS.

**Comment by bolsoncerrado** [comment]
I do use that feature too in my "other" slicer (S3D) so this would be great to have indeed!

**Comment by MadMax389** [comment]
I used to LOVE S3D. Alas, no updates since 2019.

**Comment by RobinWhitfield** [comment]
So the alternate fix here is to enable cutting without losing painting?

**Comment by MadMax389** [comment]
Yes, or cut the model before painting. In Prusa Slicer you can drag the model below the plate and slice/print it.

![image](https://user-images.githubusercontent.com/96731892/200842353-6372ac76-a28b-480a-9302-27e9286d94c1.png)
![image](https://user-images.githubusercontent.com/96731892/200842466-3c85c9cc-5a0b-407c-8938-fb0dc8493d54.png)

**Comment by bolsoncerrado** [comment]
+1
