### ISSUE TITLE
RAM LEAK on New Version 01.03.00.25 and past versions FOUND

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#586]
Read Below
![Screen Shot 2022-11-07 at 12 15 00 AM](https://user-images.githubusercontent.com/48887257/200603935-02a3c57f-ae1f-4d23-9e83-3e705a5d839c.png)
![Screen Shot 2022-11-07 at 12 15 56 AM](https://user-images.githubusercontent.com/48887257/200603944-40c9c2d5-7788-4d59-a122-baaec46448f6.png)

MacBook Pro 2012 Catalina 10.15.7
16gb ram
When it froze force quit closed the app but the dock icon was still lit and in the dock saying it was still running.
It was not in System Monitor unless its running under a hidden name.
I opened up the DMG file and tried a fresh app, it opened, but I still had the background one running taking all of my memory.
I then ran sudo rm -rf /Users/home/Desktop/BambuStudio\ 01.03.00.12.app which deleted the app but it stayed running.
I then had to reboot and it hasn't done it with the new one since.

The stl was 2 colors and was part of the lid I was running as a test print because the colors kept half coloring on the screen, I remade the object and the app crashed. I'll remake it and save the 3mf

[271645-pocket-screwdriver-kit-d3798da6-9c41-4584-8d4f-002473fd2da3.pdf](https://github.com/bambulab/BambuStudio/files/9962611/271645-pocket-screwdriver-kit-d3798da6-9c41-4584-8d4f-002473fd2da3.pdf)

I just installed and tested the 3mf on the new version of 01.03.00.25 and found it to stop and ramp up the fans at 60% sliced

[RAM Leak.3mf.zip](https://github.com/bambulab/BambuStudio/files/9962698/RAM.Leak.3mf.zip)

**Comment by Benderrodrigu3z** [comment]
AMS
PLA Red slot 1
PLA Blue slot 2
Support W in slot 4

**Comment by Benderrodrigu3z** [comment]
someone else in the discord confirmed there MacBook also had issues with this file

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
