### ISSUE TITLE
[BUG / 01.01.00.14 / Win] Failed to launch 01.01.00.14

### ISSUE THREAD

**Issue by FireworkGC** [bambulab/BambuStudio#59]
最新版软件打开，加载配置界面关闭，软件界面还没加载完就闪退了，win10 @lanewei120 @wuyifanfancy

**Comment by lanewei120** [comment]
您好，请问这个问题重现的概率如何？@[FireworkGC](https://github.com/FireworkGC)

**Comment by FireworkGC** [comment]
@lanewei120 问题一直有，没有一次成功打开过软件

**Comment by FireworkGC** [comment]
启用了WMP就解决了，我之前装了但没有启用 @
