### ISSUE TITLE
[Feature Request] Chamber Temp Alarm when Printing PLA

### ISSUE THREAD

**Issue by tamag0chii** [bambulab/BambuStudio#592]
An enclosed printer is very useful because it minimizes dust accumulation in the fans. The dust accumulation in the fans degrade it faster and will result in heatcreep faster.

Bambulabs X1 is great because it is enclosed. But when printing with PLA using Textured PEI Plates the Bed Temp usually is at a higher temperature and it might increase chamber temp to more than 45Celsius which softens PLA.

Alarm when Chamber Temp either executes:
- alarm in handy app
- or; as an option pauses print until chamber temp goes down?

**Comment by YifanWuBambu** [comment]
@tamag0chii 
We will add a warning if bed temp exceeds 55 C for PLA before sending a print job.

**Comment by bani6809** [comment]
warning should be for chamber temp, not bed temp.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
