### ISSUE TITLE
'n' exceeds maximum supported size when using Support <. 0.2 layer height

### ISSUE THREAD

**Issue by ThoughtfulDev** [bambulab/BambuStudio#6]
Hey,

i compiled from source for M1 Mac from the following commit: 1555904beffef41195003f184dec0af46b308eee
  If i slice a STL and set the Layer height anything smaller than 0.2 and use Auto supports i get the following error:

![image](https://user-images.githubusercontent.com/23433433/179271605-62fd02ef-206d-4bea-9b77-b88551847813.png)

Setting Layer height at 0.2 or bigger lets me slice the file.

Any Idea?

**Comment by wuyifanfancy** [comment]
Hi @ThoughtfulDev ,
Could you share the 3mf or stl file? Thanks!

**Comment by ThoughtfulDev** [comment]
Its from https://www.thingiverse.com/thing:4916008 (left_bottom_e3_board_v49.stl)
Attached as a zip file since github doesnt support stls.

Keep in mind i did compile this for the commit mentioned in the initial post. didnt test it yet with the current version.
[left_bottom_e3_board_v49.stl.zip](https://github.com/bambulab/BambuStudio/files/9168327/left_bottom_e3_board_v49.stl.zip)

**Comment by wuyifanfancy** [comment]
@ThoughtfulDev 
I have tested the STL on Mac with the formal release Bambu Studio v1.1.0.13. It works well.
Please update to this version and try again.
![origin_img_v2_0a7b19bd-3360-4b60-9932-a72f8dc1a31g](https://user-images.githubusercontent.com/73487021/180483113-8c0815b2-09cd-433c-8498-2e85b32267ef.png)

**Comment by ThoughtfulDev** [comment]
@wuyifanfancy Yes it works with the newest release version. Thanks!
