### ISSUE TITLE
[Feature Request] Show current layer number

### ISSUE THREAD

**Issue by TheCableGuy99** [bambulab/BambuStudio#604]
Can you add the current layer number and total number of layers in addition to the percentage of the print completed and time remaining?

**Comment by Benderrodrigu3z** [comment]
+1 for this

**Comment by YifanWuBambu** [comment]
This is in our plan and will included in recent release.

**Comment by TheCableGuy99** [comment]
please put it on the mobile app as well :) thanks!

**Comment by TheCableGuy99** [comment]
This wasn't added as promised?

**Comment by Benderrodrigu3z** [comment]
It could be a printer firmware updateSincerely,Shane FSent from my iPhone13On Dec 15, 2022, at 6:53 PM, TheCableGuy99 ***@***.***> wrote:﻿
This wasn't added as promised?

**Comment by TheCableGuy99** [comment]
> It could be a printer firmware updateSincerely,Shane FSent from my iPhone13On Dec 15, 2022, at 6:53 PM, TheCableGuy99 ***@***.***> wrote:﻿ This wasn't added as promised? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Well it certainly needs writing into the slicer, but yeah it could possibly need a firmware update for the API as well.

**Comment by spuiuk** [comment]
I noticed that this feature has been added in v1.4.2. Point 3
https://github.com/bambulab/BambuStudio/releases/

However it mentions X1/X1C and will rely on a future firmware update. I use a P1P and would like to see this feature included there too.

**Comment by timothyzalusky** [comment]
[https://wiki.bambulab.com/en/x1/manual/X1-X1C-AMS-firmware-release-history Added support for displaying the current layer number/total number of layers during printing](https://wiki.bambulab.com/en/x1/manual/X1-X1C-AMS-firmware-release-history)

Issue can be closed
