### ISSUE TITLE
Ability to set acceleration by feature type 

### ISSUE THREAD

**Issue by DKS-18** [bambulab/BambuStudio#613]
I have noticed that lowering the acceleration improves the print quality of external perimeters.

I believe it would be beneficial to have acceleration for perimeters as a separate setting from the rest of the printing moves on a given layer. that way high acceleration can be used for infill etc to reduce print time. and a lower acceleration can be used to reduce the chance of ringing

**Comment by YifanWuBambu** [comment]
@DKS-18
This feature will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
