### ISSUE TITLE
Feature request: add chamber temp to bambu handy app

### ISSUE THREAD

**Issue by Armoth1** [bambulab/BambuStudio#619]

**Comment by YifanWuBambu** [comment]
@Armoth1 
X1/X1C do not have a sensor that aims to detect the chamber temperature, so we cannot get a relative accurate value.

**Comment by KD7LRJ** [comment]
This is the display of the chamber temp from Bambu Studio. I'm not sure why my browser thinks the value is editable though.

![image](https://user-images.githubusercontent.com/2763408/201824588-d75360ab-381b-4172-a509-61f2e6a24649.png)

It is also available in the Handy app when I tap on the "Printer" icon. It is displayed in blue in my Android version.

**Comment by YifanWuBambu** [comment]
This is the display of the chamber temp from Bambu Studio. 
>> This is an approx value. I will sync with the app team for this requirement.

Why my browser thinks the value is editable though
>> Actually, it should be readonly. I reproduced the issue and it will be fixed in the next release.

**Comment by Armoth1** [comment]
So the chamber temperature value shown on the printer screen is fake?! How
can you show a value on the printer then if there is no sensor?

**Comment by Armoth1** [comment]
Ok thank you

**Comment by SaltWei** [comment]
Since this is not slicer issue. Close.
Please turn to https://github.com/bambulab/Bambu-Handy to report app feature request.
