### ISSUE TITLE
[Feature] Color paint: Height Range - Allow user to specify exact height range or exact layer

### ISSUE THREAD

**Issue by candre23** [bambulab/BambuStudio#620]
The height range feature would be a lot more useful if the user could type in an exact range in mm, or an exact range in absolute layers.  Many existing models are designed and provided with instructions for specific layer changes, and supporting these types of prints would be ideal.  Especially when the existing color engine is very janky - which it is.

Specifically, I'm requesting that text boxes be added to the height range window where a user could type in for example "layers 3 through 4" or "height 10mm through 10.5mm".

**Comment by YifanWuBambu** [comment]
@candre23 
It was added to our plan list. Thanks for your suggestion.

**Comment by Majestic7979** [comment]
@YifanWuBambu Is this going to be included, roughly how long?

**Comment by YifanWuBambu** [comment]
@zhimin-zeng-bambulab 
Please help handle this request.

**Comment by YifanWuBambu** [comment]
Hi @Majestic7979 ,

We added height range first. It may be used as an alternative tool for specifying color for a specific height range for now.
![image](https://github.com/bambulab/BambuStudio/assets/110661856/82b08916-ceca-4115-8fb3-b82386bfa6dc)

![image](https://github.com/bambulab/BambuStudio/assets/110661856/48e819e2-6cbb-4c52-8b2f-de367da0c507)

**Comment by Majestic7979** [comment]
Thank you for responding, and it's great that we have that but I really need something more visual in the 3D viewer rather than the settings table.

**Comment by zhimin-zeng-bambulab** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/120697589/6af37de4-b7be-4add-b598-f516f6ebebf4)
The latest version(v01.09.03.50) already includes this feature.
