### ISSUE TITLE
Skirt and Calibration Configureable Layer Count For Easy Removal

### ISSUE THREAD

**Issue by chrishilbert** [bambulab/BambuStudio#627]
Please add ability to set the skirt height - 2 or 3 layers - so it can come off the plate easier.  Also would be nice to have similar feature for the calibration strips so they come off easier - print some extra material after calibration is complete so they come off easy.

**Comment by SaltWei** [comment]
> Please add ability to set the skirt height - 2 or 3 layers - so it can come off the plate easier

Thank you very much for suggestions.
![image](https://github.com/bambulab/BambuStudio/assets/110660407/551386b4-b649-49d8-aaf4-caff0d722770)
