### ISSUE TITLE
Reduce Seam visibillity and better alignment

### ISSUE THREAD

**Issue by Itebayo** [bambulab/BambuStudio#633]
One issue I have with the slicer are the very visible and sometimes not properly aligned seams. It would be awesome if you could get them to the visibility level that you get from Cura sliced objects.

As a little printfarm owner of decorative items I would love to see this improve.

**Comment by AbeFM** [comment]
You mean when you check the "seam" box in the preview, you feel the white dots are too small?

**Comment by Itebayo** [comment]
no that is fine. I mean on the printed out product, the seam is a lot more visible. 3d prints that were sliced with other slicers are less visible, especally on round objects. Looking at the percision of the printer they should look way better.

Try printing out two bowl-shapes. One sliced with bambu studio and one with Cura. The difference will be easy to see.

**Comment by AbeFM** [comment]
Oh yeah, I totally agree. The seams stand out on Bambu prints more than other printers. Perhaps a "wipe" move, or just an end-of-loop overlap like infill gets.

**Comment by QingZhangBambu** [comment]
speed of Bambu's printer is much faster than others. So the filament may accumulate in the seam. We will try to improve it by adjusting travel paths or others.

**Comment by Itebayo** [comment]
I understand what you mean, but even if you set the speed and acceleration very low (e.g. Ender 3 level) the seams look way worse than they should. 
I have already posted some settings that seem to help in issue #1247.

Furthermore the machine should be able to produce even better seams if the alignment on round objects is actually straight, this is an issue that has been there for several patches.

You guys are still doing great work! I can't wait what will come out next, I am rooting for you!

**Comment by QingZhangBambu** [comment]
@Itebayo we've added "Seam gap" and "wipe speed" parameters in out latest version. you can edit these parameters in develop mode. We hope that would be helpful.
![image](https://github.com/bambulab/BambuStudio/assets/112676417/384368a3-1193-41c4-913c-51da34554206)
