### ISSUE TITLE
[Feature request] Thumbnail generation angle

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#635]
Change the angle that the uploaded thumbnails are viewed from to 45 degrees. At the moment they are straight on and it's hard to see what the object is on the LCD. Having them at an angle would make it much easier.

**Comment by YifanWuBambu** [comment]
@BambuLabDiscord 
Could you share a example? Thanks!

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/348e32e5-6e28-433c-8238-c3678ae0a98b)
Thank you very much for suggestions!
