### ISSUE TITLE
UI scaling is inconsistent on multiple displays

### ISSUE THREAD

**Issue by dotysan** [bambulab/BambuStudio#639]
I have 2 displays in Windows 10.

Primary is 3840 x 2160 (Recommended) scaled to 200% (from recommended 250%).

Second is 3840 x 2160 (Recommended) scaled to 125% (from recommended 150%).

When in primary display it looks normal.
![image](https://user-images.githubusercontent.com/5060170/202008057-8ebfecc8-a492-4ae4-a7e7-5d4345097716.png)

But not in second display.
![image](https://user-images.githubusercontent.com/5060170/202008098-a3a32108-b437-4a2d-afe2-c55849dc0dfa.png)

Notice how the section name/headers are chopped and misaligned.

**Comment by dotysan** [comment]
This is easily reproducible by moving the Bambu Labs window between displays.

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please let us known if still exist.
Thanks!
