### ISSUE TITLE
feature request: keypress in multicolor "paint" mode to spin/pan

### ISSUE THREAD

**Issue by iandouglas** [bambulab/BambuStudio#64]
If I'm zoomed in to paint very fine details, it'd be nice to have a CTRL/ALT key press with the drag to pan/spin etc. Click to hold CTRL with a mouse drag to spin, and hold down ALT with drag to pan, etc.

Currently I have to zoom out to spin/pan while clicking on the white background of the image, then zoom back in is kind of a pain

**Comment by wuyifanfancy** [comment]
Hi @iandouglas , similar feature is supported.
CTRL+mouse left button drag - spin
mouse middle button drag - pan
