### ISSUE TITLE
Support blocker feature

### ISSUE THREAD

**Issue by ETS5** [bambulab/BambuStudio#643]
Would like to be able to select a support blocker and click where I need it vs having it load on the bed somewhere and then move it to the spot I need. It would be nice to just select it from the top menu. and click on the part where I need it. Also can you do something with the top menu and have like a customizable version where I can add my most used buttons on a second row?

**Comment by YifanWuBambu** [comment]
@ETS5 
Please use support painting feature for manual support.
You can paint where you want to enforce or block support generation.

![image](https://user-images.githubusercontent.com/110661856/202396279-4662daf6-a962-473b-9f88-91ffa65ea5e9.png)
![image](https://user-images.githubusercontent.com/110661856/202396387-a82b92b6-6091-43cc-9589-1e7f6393f581.png)
