### ISSUE TITLE
[Infill pattern] 

### ISSUE THREAD

**Issue by hutje** [bambulab/BambuStudio#654]
Support for:
Archimedean chords - Top, bottom and sparse infill.
![image](https://user-images.githubusercontent.com/15308350/202449068-ccfd0739-3c77-48c1-b614-f188d19f11c1.png)
Octagram spiral - Top, bottom and sparse infill.
![image](https://user-images.githubusercontent.com/15308350/202449089-9199967d-34de-48db-b23a-6ce3d4b4fa0d.png)

**Comment by SaltWei** [comment]
Please wait for the next release. Thanks!

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
