### ISSUE TITLE
[Feature Request] Smooth timelapse without purgeblock

### ISSUE THREAD

**Issue by TheCableGuy99** [bambulab/BambuStudio#655]
I'm not sure if there's something I'm missing but why does it need to build a tower/purge block when doing a smooth timelapse?

Why can it not just move to a position, take a pic and continue printing? It does this in Octolapse (An octoprint plugin for timelapses).

Can this be considered? 

Thanks.

**Comment by YifanWuBambu** [comment]
It will be allowed in the next release. However, the melted filament may drop from the nozzle and be left on the outer surface of the model if there is no wipe tower.

**Comment by TheCableGuy99** [comment]
I see now why it's needed, maybe wipe it on the filament bin wiper? Not sure if that would work? p.s. I think the bin wiper needs just a little work. Quite often you'll find filament doesn't always end up in the bin. Not a huge issue but if it can be worked on to make it more reliable then great :)

**Comment by YifanWuBambu** [comment]
The bin wiper may not work well enough.
If some filament drop from nozzle, that means the nozzle may have some empty area inside. This may cause lack of extrusion at the beginning of model after each photo for the timelapse.

**Comment by TheCableGuy99** [comment]
Fair enough, you guys are the experts so i'll leave it to whatever you decide is best. I just couldn't understand why a purge tower was being used but I get it now.

**Comment by YifanWuBambu** [comment]
You can watch the details of the purge tower. There are some defects on the apperance, caused by the above problems that I describes. If no wipe tower, these defects may go to the model.

**Comment by TheCableGuy99** [comment]
I think we should close this as a bad idea then.

**Comment by YifanWuBambu** [comment]
Glad to discuss with you : )

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
