### ISSUE TITLE
[Feature Request] Font preview

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#657]
it is hard to find fonts and no previews means you dont know what it looks like. although so far everything looks exactly the same right now. 

also to be able to type in the font you want since list is not alphabetical and moves quickly.

**Comment by YifanWuBambu** [comment]
Yes. We are optimizing this to provide a font preview in 3D text list.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
