### ISSUE TITLE
[Feature Request] Upload sliced model to Folder or SD Card via Bambu Studio

### ISSUE THREAD

**Issue by neogenix** [bambulab/BambuStudio#658]
Hi, 

It'd be wonderful to be able to slice and upload to a destination (folder, or SD Card) without printing. This is similar to #651 (and probably has parts of #590) which is mostly around a queue system (which I would also love fwiw). I would love to be able to slice things and upload them to my printer as I'm going along instead of attempting to upload an individual, or hauling the SD card around. 

Bonus points if you could slice all build plates in a project, and upload them all to a folder / project?

**Comment by Merlwynd** [comment]
+1 ...at least for the first part of the above request...

**Comment by terryrobison** [comment]
On my tool changer printer, I slice and upload all parts to be printed to the printer.   Then I can print each component from the printer or network.  With the Bambu, I have to slice each part, print, slice then print.  Slicing them and copying the files to a TINY card is not a good solution.  Why didn't they make this a USB if they wanted you to slice and carry jobs to the printer?

**Comment by YifanWuBambu** [comment]
@neogenix 
This will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.

**Comment by Merlwynd** [comment]
When trying to load a print to printer SD card, I keep getting the message that the printer must be part of the same LAN network as the slicer. The printer and slicer are part of my home wifi network....why do I get this message?

**Comment by YifanWuBambu** [comment]
@Merlwynd 
Like stated in the release note, please use this feature with printer upated to v1.3 (comming soon).

**Comment by Buujakka99** [comment]
I have version 01.03.00.00 on my printer. When I want to send a file to the SD card, the message always comes up: Send to Printer failed. How can I fix the problem?
