### ISSUE TITLE
Feature request: Simplified picking of AMS slot when printing single-material

### ISSUE THREAD

**Issue by PaulTheSimon** [bambulab/BambuStudio#66]
If I print a single-material thing where I want to use the material sat in the 4'th AMS slot, I would currently have to add 3 new materials to my project, and manually paint the object(s) in the material I want.

To streamline printing of single-material prints, why not allow a simple AMS slot override at the "send" screen?
![amsOVERRIDE](https://user-images.githubusercontent.com/38134728/180665995-63b4971f-7304-4ea4-9868-edb7cdb87b33.png)

**Comment by Sirwill1968** [comment]
I'd totally love to see this feature too.

**Comment by wuyifanfancy** [comment]
Bambu Studio already support this feature. But it also requires the firmware update, which will be released soon.

**Comment by wuyifanfancy** [comment]
@Sirwill1968 
The printer firmware v1.0.0.0 has been released. Please update the firmware and use the feature.
![image](https://user-images.githubusercontent.com/73487021/180940922-3142c4fd-f1ae-4b72-9a09-c2434b0a4720.png)
