### ISSUE TITLE
part cooling fan not turning on after set layer

### ISSUE THREAD

**Issue by gRIMMIE1981** [bambulab/BambuStudio#665]
my part cooling fan is not turning on after the set layer.  is there a bug of some sort when using the ams?  I set the fan in the generic pla for what i am using

**Comment by SaltWei** [comment]
Please provide 3MF file for analyzing

**Comment by gRIMMIE1981** [comment]
I'm all set with this thank you



Tom J



-------- Original message --------
From: SaltWei ***@***.***>
Date: 11/22/22 9:04 PM (GMT-05:00)
To: bambulab/BambuStudio ***@***.***>
Cc: gRIMMIE1981 ***@***.***>, Author ***@***.***>
Subject: Re: [bambulab/BambuStudio] part cooling fan not turning on after set layer (Issue #665)


Please provide 3MF file for analyzing

**Comment by SaltWei** [comment]
Not understand.
Already has no issue now?

**Comment by gRIMMIE1981** [comment]
I figured the part cooling fan out. but my extruder is dead and I am waiting to see what and when they are shipping parts



Tom J



-------- Original message --------
From: SaltWei ***@***.***>
Date: 11/25/22 5:02 AM (GMT-05:00)
To: bambulab/BambuStudio ***@***.***>
Cc: gRIMMIE1981 ***@***.***>, Author ***@***.***>
Subject: Re: [bambulab/BambuStudio] part cooling fan not turning on after set layer (Issue #665)


Not understand.
Already has no issue now?

**Comment by SaltWei** [comment]
I have checked with my printer and everything is OK. So this should not be issue about Studio.
So close.
Thank you for reporting issue and suggestions for us to keep improvement!

**Comment by SaltWei** [comment]
By the way, for issue about printer, you can report on App. 
https://wiki.bambulab.com/en/x1/troubleshooting/upload-log
