### ISSUE TITLE
Z hieght not working in slicer

### ISSUE THREAD

**Issue by PowerChaos** [bambulab/BambuStudio#67]
hey all
this is just a smal bug report of the slicer
when you import a multi file and want to move a file in the Z plane ( above bed , Z offset of +30 for example ) then it fails

this makes it impossible to adjust the wrong offsets , or to use multi color that need to be adjusted/moved a little bit to match up

can you check this please
Thank you
Greetings from PowerChaos

**Comment by wuyifanfancy** [comment]
@PowerChaos 
Please try these steps and check whether it solves the issue.
![image](https://user-images.githubusercontent.com/73487021/180682848-b805072a-95e6-406f-bddd-1cd79c14e8b2.png)

**Comment by PowerChaos** [comment]
ok thank you
making a assembly of the print ( group ) then it works 
this was my test file ( 3MF ) and seems it was just differend objects instead a single object
but when imported to prusa slicer it is a assembly object . from there the confusion
[CraneTruckV5.zip](https://github.com/bambulab/BambuStudio/files/9177541/CraneTruckV5.zip)

Greetings from PowerChaos

**Comment by wuyifanfancy** [comment]
Bambu Studio and PrusaSlicer use different 3mf structure.
So the 3mf created in PrusaSlicer is currently not supported in Bambu Studio.

We have added this compatibility task to our recent plan.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/220538842-441c4421-d813-4e6f-8ac0-0fbc9e7e9f17.png)
