### ISSUE TITLE
Timelapse misspelling

### ISSUE THREAD

**Issue by 18107** [bambulab/BambuStudio#677]
When printing with timelapse turned on, the word "Timelapse" is spelt as "Timelapes" on the printer screen 

![PXL_20221120_012826540](https://user-images.githubusercontent.com/7885724/202878511-c96c83fa-834c-4157-9e42-6a25d84df11b.jpg)

**Comment by YifanWuBambu** [comment]
@18107 
It will be fixed in the next release. Thanks!
