### ISSUE TITLE
ISSUE: Add text tool font list contains multiple separate alphabetized lists

### ISSUE THREAD

**Issue by olithraz** [bambulab/BambuStudio#681]
Confusing title, not sure a better way to word it so look at this gif:

![bambufonts](https://user-images.githubusercontent.com/1173900/202923890-7d525335-b297-4f96-9859-8ef5cd2e93f2.gif)

There are 4 separate groups of fonts A-Z. There does not appear to be any reason for them to be in separate groups and it would be a lot easier to find a specific font if it was a single alphabetic list.

**Comment by YifanWuBambu** [comment]
@olithraz 
Thanks. We will fix it in the next version.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
