### ISSUE TITLE
Resizing only in one direction is not possible

### ISSUE THREAD

**Issue by Obicom** [bambulab/BambuStudio#685]
I worked long time with the Prusa slicer and there I was able to resize e.g. support blocker cube only in one direction (left or right / top or down) with pressing and hold CTRL button. I miss this function on Bambulab Studio slicer or did I have overseen something?

**Comment by YifanWuBambu** [comment]
@Obicom 
You can resize in one direction by simply dragging the "cubic grabber" in the middle of lines.
![image](https://user-images.githubusercontent.com/110661856/203456781-932a7980-9905-4279-8c9e-228b4f329fe2.png)

**Comment by Obicom** [comment]
@YifanWuBambu maybe a missunderstanding. If I do as shown bei you with the green cubic grabber in the front and pull it to me the front and the back site grows. Same with left and right. What I want is thar if I pull the green cubic grabber in the front in my direction that only the front grows but not the back site. In Prusa slicer it is possible with holding the CTRL key and select on of the cubic grabbers. The second one it then hidden (in the back). Please try it out.

**Comment by YifanWuBambu** [comment]
Thanks for the explanation. We will add it in recent releases.

**Comment by SaltWei** [comment]
Available in v1.5.0 Public beta

**Comment by chiwon575** [comment]
good afternoon i am still facing this issue.  is there any way to resolve it.  every time i click on any cubic grabber it stretches the model in both directions.   i have tried with ctrl and alt  shift etc with no success

**Comment by bitfrickler** [comment]
Press CTRL while dragging.

**Comment by vanowm** [comment]
> Press CTRL while dragging.

IMHO this should be the opposite, CTRL = resize from the center...

anyway, thanks, at least there is that now.

**Comment by vanowm** [comment]
Actually, even with CTRL, when dragging the corner, it makes the opposite corner gray, like indicating it will be stationary, but it still resized from the center.
