### ISSUE TITLE
Feature request: user setting for how close to auto arrange parts

### ISSUE THREAD

**Issue by iandouglas** [bambulab/BambuStudio#686]
I haven't seen this mentioned before, but would love a way to specify how close or far apart I want the slicer to auto-place items on the bed.

Right now Bambu Studio seems too careful and it's too nice items onto a second plate when there's clearly enough room to place items.

I would love a setting that specifies a minimum/maximum separation of parts, like "minimum of 5mm, maximum of 10mm"

**Comment by aridShrub** [comment]
> I haven't seen this mentioned before, but would love a way to specify how close or far apart I want the slicer to auto-place items on the bed.
> 
> 
> 
> Right now Bambu Studio seems too careful and it's too nice items onto a second plate when there's clearly enough room to place items.
> 
> 
> 
> I would love a setting that specifies a minimum/maximum separation of parts, like "minimum of 5mm, maximum of 10mm"

This already exists, the value is set in the dialog box which appears when you do "auto-place" ; the value you set is remembered until you alter it.

Pruslicer auto-place has the same thing.
