### ISSUE TITLE
Feature request: add keyboard shortcuts for painting tools

### ISSUE THREAD

**Issue by iandouglas** [bambulab/BambuStudio#687]
I love that I can hit numbers to quickly select a filament color when painting things.

I'd also love to have keyboard shortcuts like "f" for fill, "t" for triangle, "s" for sphere, "c" for circle etc

(I know these shortcuts might conflict with other shortcuts but I feel that once you're in a tool, the shortcut keys should be based on the tool you're in.)

**Comment by SaltWei** [comment]
Available in v1.5.0 Public beta
