### ISSUE TITLE
Feature Request: Helper Disc

### ISSUE THREAD

**Issue by MadMax389** [bambulab/BambuStudio#689]
Prusa slicer has a feature that allows you to add a small disc that acts like a localized brim to add surface area to select parts of the model. In Bambu Studio, you can add a cylinder primitive with a height of .2mm, but you need to assemble it to the model. The disc then becomes part of the model instead of a detachable brim.

**In PS you can see that the disc is printed around the edge of the box making it easy to remove**

![image](https://user-images.githubusercontent.com/96731892/203093458-fd9afd55-226d-430e-8ea3-f85db370b317.png)

**In Bambu Studio, the disc becomes part of the model and must be cut away.**

![image](https://user-images.githubusercontent.com/96731892/203094159-7036c649-1f6f-4a9a-a782-19585e8f5b8d.png)

**Comment by SaltWei** [comment]
Thanks for suggestions! And we will investigate this feature or issue.

**Comment by SaltWei** [comment]
> Prusa slicer has a feature that allows you to add a small disc that acts like a localized brim to add surface area to select parts of the model.

Could you share one prusa 3MF about this feature to us？ We don't clear how to add disc on prusa.

**Comment by MadMax389** [comment]
Dear SaltWei,

 

I have attached a Prusa .3mf showing the example. The process is a little complex, but very useful when needed. I had found a description of the procedure in Prusa help (or forum), but I can’t seem to find it now. The process is as follows:

 

Make sure that “clip multi-part objects” is selected

 



 

Add the helper disc as a part from the gallery or other user-created file.

 





 

Once the part is added and placed, make sure the helper disc is the first item in the assembly by dragging the helper disc above the hollow cube. I believe this determines the slicing order when “clip multi-part objects” is enabled.

 



 



 

Then set the perimeters of the helper disc to a high value

 



 

When sliced, it preserves the outline of the cube inside the disc making it easy to remove, much like a brim. 

I tried to recreate these steps in Bambu Studio, but there is no way to adjust the print order in the assembly (and maybe it doesn’t make a difference without the clip multi-part objects function).

 



 

Best Regards,

Danny Milla

**Comment by kritoke** [comment]
There is another concept that is called a sprue brim ear that is even more handy. It is a very very short line that connects an edge to one of the brim ears.  This video talks about it a little, https://youtube.com/watch?v=MCcFMDv_4eo

**Comment by MadMax389** [comment]
@kritoke Great idea! Just create a small disc with the sprue attached as an stl and then add as a part as needed. I'll try that next time I need to use a helper disc.

**Comment by SaltWei** [comment]
@MadMax389 Does the feature2 and feature3 which can used for manual brim ear in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.04.52 match your requirement？

**Comment by MadMax389** [comment]
@SaltWei Yes, it is perfect! Targeted, multi-layer brims of any similar material is a great feature. The ability to sort the clipping order helps my workflow tremendously. Thank you to you and the BL development team for incorporating customer feedback into the product. Not enough companies engage their customers this way. Bravo! Please close the issue at your convenience.

**Comment by SaltWei** [comment]
We will keep improving! Thank you very much！
