### ISSUE TITLE
[Issue] Corruption of saved project file with multiple plates

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#691]
Issue:
-	Unable to open a saved project file which I created with 3 specific parts on separate plates

To Recreate
1)	Download the following 3 files from https://www.printables.com/model/105764-mitten-boot-dryer-for-floor-vent-no-supports/files 
  a)	Robaogn_VentDryer_TubeSupport_8X.3mf
  b)	Robagon3D_VentDryer_DryerTube_8X.3mf
  c)	Robagon3D_VentDryer_14in_x_6in_Base_Half.3mf
2)	Open a fresh copy of Bambu Studio
3)	Import each file onto a new plate
4)	Save as a new project file
5)	Open the project file
6)	Get error messages:
  “Loading of a model file failed.”
  “The file does not contain any geometry data.”

Bambu Studio Version: 01.03.00.25 and at least one version earlier

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
