### ISSUE TITLE
[Issue] When sending different components of the same model from Fusion 360 to Bambu Studio, Bambu Studio opens up a new instance for each component instead of loading all the components onto the same plate on the already opened BS

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#693]
Sending models from Fusion 360 to a slicer can be done by the following steps: File -> 3D Print -> Send to 3D Print Utility -> Print Utility -> Custom -> Application -> Bambu Studio. Following these steps opens up the Bambu Studio (BS), and loads the model. If a model has only one component, this works fine. However, if a model has 2 or more components, there is a problem: sending the first component opens up the BS and loads the component onto a plate, as expected. [now the problem:] Sending another component opens up a new instance of BS, when it should load the additional component onto the same plate on the already opened BS. These different components of the same model are now in different BS instances and are not on the same plate. There are also error messages showing up as each new instance of BS opening up. This issue is more likely on the BS's end since sending multiple-component models from Fusion 360 to Cura doesn't have this problem.

**Comment by bambu123** [comment]
Same AS #645
