### ISSUE TITLE
[Bug] "Only one wall on top surfaces" glitches under certain conditions and does not do gap infill. 

### ISSUE THREAD

**Issue by psiberfunk** [bambulab/BambuStudio#694]
Under the proper conditions, it seems that gap infill doesn't get put in where it should be when "only one wall on top surfaces" is checked.  In this example, you can see the top layer of these hexes has walls, but no gap infill.  Project file attached for debugging.  I think this is potentially a result of the partial arachne implementation / merge where a code logic error was made.  Hopefully easy to fix, as it has a marked negative impact on print quality when triggered.

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/19777571/203217282-f29fefc1-598e-4c07-93a4-fd4976a8535b.png">

[Bambu_Lab_Reusable_Spool_Holder_Remix_Four.3mf.zip](https://github.com/bambulab/BambuStudio/files/10063358/Bambu_Lab_Reusable_Spool_Holder_Remix_Four.3mf.zip)

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
