### ISSUE TITLE
Slicer window does not maximise to full 3440x1440 resolution (windows 10)

### ISSUE THREAD

**Issue by kvnper** [bambulab/BambuStudio#7]
**OS:** 
Windows 10 64-bit

**Issue:**
When using two monitors, one being a resolution of 2560x1440 and the other being 3440x1440, and having the smaller monitor (2560x1440) set as the main display, the slicer window does not maximise to full size 3440x1440 resolution on that monitor. Instead, the slicer window only maximises to 2560x1440, the resolution of the other monitor.

**Comment by wuyifanfancy** [comment]
We will fix it in recent release.

**Comment by YifanWuBambu** [comment]
@kvnper 
The fix is in the latest version. Please download and try it.
