### ISSUE TITLE
BambuStudio is using cleartext HTTP for uploading to the cloud

### ISSUE THREAD

**Issue by rkarlsba** [bambulab/BambuStudio#701]
Seems data upload to the cloud, 47.254.187.182 in my case, is done over HTTP, no HTTPS, no encryption, just cleartext all the way. This is a *serious* security flaw and should be addressed immediately!

**Comment by YifanWuBambu** [comment]
Hi @rkarlsba 
Thanks a lot for your information. We are trying our best to improve the security.
For details, please refer to
https://blog.bambulab.com/answering-network-security-concerns/

**Comment by SaltWei** [comment]
@lanewei120 Had this issue be handled already? If yes, then we can close this ticket

**Comment by lanewei120** [comment]
already changed to https long time ago
