### ISSUE TITLE
Impossible to select correct font

### ISSUE THREAD

**Issue by rkarlsba** [bambulab/BambuStudio#710]
When choosing a font in the Text shape tool, you only get a small pulldown and now way to search for a named font. Also, there's no font preview. Since all fonts on the system are shown, this is a *lot*. On my mac, I probabaly have 100+ fonts, but I have only installed five or six of those. The rest is in there by default or was pulled in with some other software. I guess this could be remedied by adding a search box in the top of the pulldown, or perhaps something new with previews enabled.

**Comment by YifanWuBambu** [comment]
Font preview will be included in the next release.
