### ISSUE TITLE
Auto arrange puts large objects partially outside of the plate even if they fit in build area

### ISSUE THREAD

**Issue by c2h5oh** [bambulab/BambuStudio#715]
**Describe the bug**
If you put a large object with size close to the entire X or Y of build plate auto arrange will put it mostly outside of the build plate. The attached file is an extreme example for the sake of being easily reproducible, but I believe I've seen it for objects with X or Y larger than 90% of print area.

**To Reproduce**
1. Add [Gridfinity Magnet Light Baseplate 3x6.zip](https://github.com/bambulab/BambuStudio/files/10097203/Gridfinity.Magnet.Light.Baseplate.3x6.zip) to build plate (it's 252mm wide)
2. Click on Arrange All Objects
3. Click Arrange

**Expected behavior**
Automatic arranging should work correctly.

**Screenshots**
I can do one better - here's the video
https://user-images.githubusercontent.com/446070/204112703-cd977d79-e179-4ddb-b738-1486f690d387.mp4

**Desktop (please complete the following information):**
 - Windows
 - 1.3.1.1, but it was also present in at least one release before that (I haven't used earlier ones)

**Comment by alexzogh** [comment]
Yes, very annoying bug. I've just reverted to manually placing everything

**Comment by manch1n** [comment]
@c2h5oh cause spacing feature will inflate object before auto arrangement. So disable brim and lower spacing could solove this problem
![image](https://user-images.githubusercontent.com/38675531/205200407-36dbe428-c390-4022-85ff-6e3078844095.png)

**Comment by c2h5oh** [comment]
@manch1n thanks for the workaround, but it doesn't change the fact it should be fixed as a bug.

**Comment by tangketan** [comment]
@c2h5oh It's not a bug, but rather a feature request: when there is only one object, arranging spacing should automatically set to 0
I'll try to add it in.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
