### ISSUE TITLE
Feature Request: Allow edit of print sequence by object

### ISSUE THREAD

**Issue by JPotter73** [bambulab/BambuStudio#717]
It would be nice to change the order of the print sequence when printing by object.

For instance: If I'm printing 3 objects and I know that one is more risky than the others, I may like to put that one last. If it fails, I would still potentially get the two other prints.

**Comment by JPotter73** [comment]
Case in point: there are 3 objects in this print and I was worried the 2nd may fail. I'm quite sure the 3rd would print.

Now I'll start a print for the last two objects, but maybe not since I don't have control over which will print 1st
![image](https://user-images.githubusercontent.com/113537959/204123671-7eead2e0-8ed6-4218-af0b-60a2562cdbe5.png)

**Comment by YifanWuBambu** [comment]
It will be included in the next release.

**Comment by YifanWuBambu** [comment]
This is included in v1.4.
