### ISSUE TITLE
Auto arrange will incorrectly split print into multiple plates

### ISSUE THREAD

**Issue by c2h5oh** [bambulab/BambuStudio#718]
**Describe the bug**
If several larger objects are added to the plate auto arrange function will split them into multiple plates, even if they easily fit on one plate, even leaving calibration areas clear

**To Reproduce**
1. Add all 3 to plate: [Downloads.zip](https://github.com/bambulab/BambuStudio/files/10098148/Downloads.zip)
2. Click on arrange all objects
3. Click on arrange - settings don't matter

**Expected behavior**
Arrange uses minimum number of plates to arrange objects

**Screenshots**
Video of this happening: 
https://user-images.githubusercontent.com/446070/204132428-22bd0a84-1b28-4318-aa87-da2bb10aad82.mp4

Screenshot demonstrating those objects easily fit on plate:
![bambu-studio](https://user-images.githubusercontent.com/446070/204132457-860921b4-fa43-409a-b8b1-ca338dd1de59.PNG)

**Desktop (please complete the following information):**
- Windows, Linux
- 1.3.1.1, but it was also present in at least one release before that (I haven't used earlier ones)

**Comment by tangketan** [comment]
Our next release has solved this problem. The following is the arranging result:
![image](https://user-images.githubusercontent.com/13730459/205430565-a4616017-df19-45b2-a1dd-ed4aec3f6457.png)

**Comment by c2h5oh** [comment]
@tangketan Thank you.
