### ISSUE TITLE
[*Feature Request*] ask for timelapse on send to printer window

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#723]
i like timelapse for all my prints, but bambu profile do not have it enabled by default. i would like to see a checkbox asking if I want to enable timelapse, on the send to printer window (the window that asks for flow calibration, AMS, and bed leveling). Doesn't make sense to have timelapse feature mixed in with print quality settings!

**Comment by SaltWei** [comment]
This is what the studio does now. Thanks
