### ISSUE TITLE
Detect narrow internal solid infill

### ISSUE THREAD

**Issue by whiskeywagon** [bambulab/BambuStudio#725]
Narrow internal solid layer detection is always on and and some cases causes the pattern to show up on the top layer, which is not ideal.

Solution: Add "Detect narrow internal solid infill" box so you can enable or disable it.

**Comment by SaltWei** [comment]
Could you share one model or case for us to test and debug? Thanks you very much!

**Comment by whiskeywagon** [comment]
Sure! I added some pictures too in the zip file. So what I mean is that the layer before top layer overlaps a little bit in the middle and so tranforms it to the top layer.

[Model.zip](https://github.com/bambulab/BambuStudio/files/10104562/Model.zip)

**Comment by SaltWei** [comment]
My printing is better than yours.
![img_v2_14c61f5c-7492-4599-9598-7ce06e04e8bg](https://user-images.githubusercontent.com/110660407/204438912-7fedcdb8-cd35-419b-af4c-e3e4150d50f6.jpg)

We guess maybe have relationship with the printer. Could you follow thi guide to clean the xy axis and re-print again to check whether be improved?
https://wiki.bambulab.com/en/x1/troubleshooting/abnormal-xy-axis-resistance

**Comment by whiskeywagon** [comment]
I printed two. Upper one is printed "_Detect narrow internal solid infill_" disabled, below is the normal one.
XY axis cleaned with IPA, both prints all default speed settings (standard 0.2, general PLA), PLA (good quality) 220C/55C, textured plate.
![20221129_163759](https://user-images.githubusercontent.com/119295511/204560772-87f4502e-08b7-4a78-9f78-f64db6519912.jpg)

So you can see that the upper print looks better :)

**Comment by SaltWei** [comment]
OK. Please wait for next release, and we will open the option.

**Comment by whiskeywagon** [comment]
Great!
