### ISSUE TITLE
Update of Studio loses login information

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#726]
Have a valid logged in instance of studio installed. Then update to newer version and you have to login again as if it's a new install.

Expected behavior is it should actually upgrade the install, not just remember some settings.

Login information should remain persistent on an "update "

**Comment by c2h5oh** [comment]
Confirmed - update logged me out too.

**Comment by cheshire76** [comment]
The need for signing in again likely has to do with the change from HTTP to HTTPS. [https://blog.bambulab.com/answering-network-security-concerns/](url)

**Comment by StoneLiBambulab** [comment]
Due to the security upgrade, the user needs to log in again. I am very sorry that the inadequacy in security has affected the user experience.

Stone Li

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released.
