### ISSUE TITLE
3DConnexion CTRL+M Options

### ISSUE THREAD

**Issue by brandonraineri** [bambulab/BambuStudio#73]
Please add the 3DConnection CTRL+M options like in Prusa Slicer.  Defaults are too slow and I like to swap my axes.

![CTRL+M](https://user-images.githubusercontent.com/109975882/180815761-703638a1-6d80-49d7-807b-c49c086adba8.PNG)

**Comment by wuyifanfancy** [comment]
It has been added to our plan. We will schedule for this feature.

**Comment by YifanWuBambu** [comment]
@brandonraineri 
It is added in v1.2.
