### ISSUE TITLE
"Small perimeters" speed setting (like PrusaSlicer)

### ISSUE THREAD

**Issue by barrettj** [bambulab/BambuStudio#735]
**Is your feature request related to a problem? Please describe.**
I would like a setting to control the speed when printing small perimeters

**Describe the solution you'd like**
A "Small perimeters" speed setting, like PrusaSlicer has (Under Speed for print moves)

This setting is super important for several models that we print and sell.  It's especially important with how fast the X1 is by default.

**Comment by ppamment** [comment]
@barrettj FYI this is already available in SoftFever fork of Bambu Studio if you need it while you wait for it to make it into the official slicer: 

https://github.com/SoftFever/BambuStudio-SoftFever

**Comment by barrettj** [comment]
> @barrettj FYI this is already available in SoftFever fork of Bambu Studio if you need it while you wait for it to make it into the official slicer:
> 
> https://github.com/SoftFever/BambuStudio-SoftFever

I’ve indeed been using that the past week and my project has been printing flawlessly (and how I was certain this was the feature I needed after trying several other things) - thanks though!

**Comment by SaltWei** [comment]
@QingZhangBambu Please evaluate this feature request

**Comment by QingZhangBambu** [comment]
we've opened the "seam gap" and "wipe speed" parameters on our latest version.

**Comment by man55** [comment]
Very useful feature, please add it.

**Comment by QingZhangBambu** [comment]
it will be added in the next version.

**Comment by XunZhangBambu** [comment]
It has been added in 1.8 version
