### ISSUE TITLE
Text pop ups error - not displaying in the right format

### ISSUE THREAD

**Issue by TheRhion** [bambulab/BambuStudio#74]
The pop ups in the build area screen are not displaying correcting as the font seems to be messed up as seen on the pictures.
This is using Bambu Studio Windows version on Windows 11 in English . 

![WhatsApp Image 2022-07-25 at 6 11 31 PM (1)](https://user-images.githubusercontent.com/93004212/180836057-3f348a79-1185-491e-bff8-5165b7fa1ed4.jpeg)
![WhatsApp Image 2022-07-25 at 6 11 31 PM](https://user-images.githubusercontent.com/93004212/180836058-40d02ea0-8a2f-477a-9e39-fb1713dbacfc.jpeg)
![WhatsApp Image 2022-07-25 at 6 11 32 PM (1)](https://user-images.githubusercontent.com/93004212/180836061-1e90abfa-8261-4168-82d5-c8ec107000c7.jpeg)
![WhatsApp Image 2022-07-25 at 6 11 32 PM](https://user-images.githubusercontent.com/93004212/180836062-89c93862-b62c-475d-a1c3-0a3eb2836e6b.jpeg)

**Comment by wuyifanfancy** [comment]
Hi @TheRhion , we tested this issue on several computers, but did not reproduce it.
Could you help provide the following information?

1. Display settings
![Uploading origin_img_v2_1f3ca0ef-bf25-42b8-86a9-67286c57089g.jpg…]()

2. Your Operating System language

**Comment by TheRhion** [comment]
Hi thanks for this I have adjusted the settings on the display and its working now.
My recommended setting was at the scale of 300% so changed it to 250% and its working now.

![Screenshot 2022-07-26 140242](https://user-images.githubusercontent.com/93004212/181013856-55ab0c19-ffeb-4e10-b339-89dda889dbda.jpg)
![Screenshot 2022-07-26 140916](https://user-images.githubusercontent.com/93004212/181013861-7f2d3946-1e75-4acd-932a-a51b6f52583c.jpg)
![Screenshot 2022-07-26 141011](https://user-images.githubusercontent.com/93004212/181013865-00db1a4b-ebc5-4928-b64e-ffcef4005fb7.jpg)
