### ISSUE TITLE
Alternative Tree Supports.

### ISSUE THREAD

**Issue by wirlybird** [bambulab/BambuStudio#748]
Hi, I find tree supports can be very good for certain types of models.  However, the tree supports in Bambu Studio are more trouble than helpful at times.  They tend to engulf the model in a cocoon with hard to remove supports.

I use the tree supports in Flashforges Flashprint a lot and find them to be very good.
Although the Flashprint supports look similar to resin style supports they are for filament (FDM) printing.

I have attached two pictures.  One is of the Flashprint tree supports and the other is the Bambu Studio tree supports.
The same model was used at the same size for both pictures.
As you can imagine the BambuStudio tree supports would be quite difficult to remove on this model without breaking parts of the model.

![1](https://user-images.githubusercontent.com/25409320/205115174-5cb5f8b9-c1eb-4dfa-bb3e-72fab2630ff3.png)
![2](https://user-images.githubusercontent.com/25409320/205115190-5848a1ae-6d2b-4ede-883f-929d57d8b4df.png)

**Comment by tangketan** [comment]
Hi @wirlybird , now we have Tree Slim style for tree support. Have you tried that? Is that good enough for you?

**Comment by wirlybird** [comment]
Hi,

I’ve only tried them a little bit so I can’t really report on them!  Thank you though.
