### ISSUE TITLE
Bambu Labs Logo on build plate overlaps GCODE preview

### ISSUE THREAD

**Issue by psiberfunk** [bambulab/BambuStudio#75]
When previewing GCODE, it appears the Bambu lab logo gfx on the build plate obscures lines .  In these included screenshots it is obscuring the brim lines under it
![Screenshot 2022-07-25 213125](https://user-images.githubusercontent.com/19777571/180903202-03d570f4-8eb9-4cf0-8698-20e82fc0f756.png)
![Screenshot 2022-07-25 212949](https://user-images.githubusercontent.com/19777571/180903206-cba1d31e-f521-40ef-8141-011f55cd229c.png)
.

**Comment by YifanWuBambu** [comment]
Fixed in the latest version.
