### ISSUE TITLE
Can not print very simple object

### ISSUE THREAD

**Issue by theogott** [bambulab/BambuStudio#754]
**Describe the bug**
This is a very Simple Object. I tried to print it with different Settings, with PLA or PETG and always run into Issues, see picture.
I also tried to print it with 50% - also did not work.

**3mf File for This Bug**
I have attached the sliced file in a zip-file.

**To Reproduce**
Simply try to print this file.

**Expected behavior**
See Pictures below. I guess it will never work with the PEI Plate, but it also does not work with the cold Plate, and it should work.
Because this is not a difficult Object.

![DSC03188](https://user-images.githubusercontent.com/68653812/205376213-c63244d6-2c07-4a0b-a2c1-e4e2f2259c0a.JPG)

**Screenshots**
![DSC03189](https://user-images.githubusercontent.com/68653812/205376113-bbd202af-c54d-4409-8955-0fad88b9fbfc.JPG)

![DSC03191](https://user-images.githubusercontent.com/68653812/205376134-eeeaf064-08ed-42c0-aa34-2a005a6f988d.JPG)

![DSC03190](https://user-images.githubusercontent.com/68653812/205376125-14fd7e4f-d8c7-426e-af78-b380e7254322.JPG)

**Desktop (please comple
[TREX 2v2.zip](https://github.com/bambulab/BambuStudio/files/10143965/TREX.2v2.zip)
te the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by SaltWei** [comment]
Thank you very much to report issue to make slicer keep improved!
But we can't reproduce this issue. And this doesn't seem to be slicer issue.
Please follow this guide to report issue to printer team to analyse.
https://wiki.bambulab.com/en/x1/troubleshooting/upload-log

**Comment by SaltWei** [comment]
By the way, is other model printed well by your printer?

**Comment by theogott** [comment]
Its strange. I have now switched to red PLA and printing this:
And it works fine.
![image](https://user-images.githubusercontent.com/68653812/205431680-e78223bd-b496-4826-8f8f-699e25c01dad.png)
![image](https://user-images.githubusercontent.com/68653812/205431693-efa82426-dcf3-43ef-9b2f-9b11d6049bcb.png)

**Comment by theogott** [comment]
If you can print the otehr model, then please close the case. It must be a Printer issue (maybe with the Nozzle or the Filament ?) in this case.

**Comment by SaltWei** [comment]
We printed the 3MF you shared in zip and look fine. PLA and PETG is used both.
![img_v2_aeabc86f-23c8-47d5-8ba4-b23ac7f898cg](https://user-images.githubusercontent.com/110660407/205431979-fdbc681b-d917-467c-9c96-03da970abc22.png)

What brand of PLA and PETG did you use?

**Comment by theogott** [comment]
The Problem "Cerprise" PETG ... got possibly too much moisture?
Because it worked very well before.

![DSC03194](https://user-images.githubusercontent.com/68653812/205432796-291a418a-de03-4ee3-a5ce-6e04e1440217.JPG)

I will try to dry it and try again.

**Comment by SaltWei** [comment]
> The Problem "Cerprise" PETG ... got possibly too much moisture?
> Because it worked very well before.

We used polylite PETG and have never used this brand.
Will order and try.
From my personal experience, different filament may have some difference, but should not be so large. Usually, limiting the volumetric speed of filament setting can improve.

**Comment by theogott** [comment]
I will give it a try. Thanks for your support. 
We can close this case.
