### ISSUE TITLE
Linux Support!

### ISSUE THREAD

**Issue by iplayfast** [bambulab/BambuStudio#758]
The software is based off of the PrusaSlicer which supports Linux. 
There are a fair number of users that use desktop Linux specifically for slicing and 3d printing tasks. 
You should support it in your releases.

**Comment by deftdawg** [comment]
Duplicate of #12

**Comment by lanewei120** [comment]
first linux version on ubuntu has been released, 
and now we can build linux version by ourselves following the guide https://github.com/bambulab/BambuStudio/wiki/Linux-Compile-Guide
