### ISSUE TITLE
Problem "spaghetti detector" gcode in 3th party printer

### ISSUE THREAD

**Issue by m4R-T1n** [bambulab/BambuStudio#761]
i set up an 3th party printer to bambu studio but after on printstart it prints mid air.
when i look in the gcode there is a section for the spaghetti detector.
if i remove this part it prints normal.
so is it possible to remove it for non bambu printers or can i disable it somewhere?

thx

**Comment by SaltWei** [comment]
it's now hardcoded in code. We will remove it

**Comment by QingZhangBambu** [comment]
We've added the function. you can get that in version 1.5
