### ISSUE TITLE
"Unload Filament" option does not reappear when de-selecting "Enable AMS"

### ISSUE THREAD

**Issue by Merlwynd** [bambulab/BambuStudio#766]
When AMS is connected, the "Unload Filament" button on the printer screen will understandably disappear in order to prevent misuse. However, when the AMS is disabled by de-selecting the "Enable AMS" button in the UI or Bambu Studio, the "Unload Filament" option does not reappear on the printer screen. You have to actually disconnect the AMS electrically in order for the "Unload Filament" button to reappear.  
It seems counterproductive to have a button that disables the AMS when sending a print (meaning you are using external filament) and then you still have to disconnect the AMS electrically to get the "Unload Filament" option button to reappear on the printer screen. The "Unload Filament" option should reappear automatically when the enable AMS button is unchecked....otherwise the "Enable AMS" button has no real purpose... 

**Expected behavior**
When unchecking the "Enable AMS" option (say in Bambu Studio when sending a print), this means external filament is loaded and being used...which in turn should cause the "Unload Filament" option to reappear on the printer screen so the external filament can be properly unloaded.....in any scenario, the external filament would have to be unloaded before the next use of the AMS.

**Comment by StoneLiBambulab** [comment]
Hi @Merlwynd ,
"Unload Filament" will always shown in next version.

Thanks!

Stone Li

**Comment by Merlwynd** [comment]
Great...thank you.
