### ISSUE TITLE
Add ability to program AMS from PC

### ISSUE THREAD

**Issue by AbeFM** [bambulab/BambuStudio#768]
**Is your feature request related to a problem? Please describe.**
The touch screen can be a little slow, it would be nice to be able to set a filament type/color from BS

**Describe the solution you'd like**
be able to set a filament type/color from BS

**Describe alternatives you've considered**
Getting up, walking to machine, changing it there

**Additional context**

**Comment by c2h5oh** [comment]
You can already do this. Bambu Studio -> Device tab -> right hand side:

![Capture](https://user-images.githubusercontent.com/446070/205523715-569d0743-8a28-40c4-a5b4-c20d08deb205.PNG)

**Comment by AbeFM** [comment]
I just came here to add that. Thanks for the catch.

**Comment by AbeFM** [comment]
Do'oh! I'd seen that a bunch of times and never clicked on it.

Er, thanks!
