### ISSUE TITLE
[Feature Request] Disable z-hop above specified height. 

### ISSUE THREAD

**Issue by brandonraineri** [bambulab/BambuStudio#77]
Instead of completely disabling z-hop so we can utilize the full 256^3 build area in the workaround discussed in the wiki, make it where it is only disabled above a user specified height (ex input: 255mm) so we can utilize this function for 99% of the print.

**Comment by SaltWei** [comment]
@BambooBugFixer Please add this next version

**Comment by BambooBugFixer** [comment]
All right.

**Comment by BambooBugFixer** [comment]
This feature will be available in a future version pretty soon.

**Comment by GuzziRaz** [comment]
Now that we have this implemented (even in stable), please bump the machine settings for Printable Height to 256 in all profiles. There's no reason not to - it just unnecessarily adds to uneducated "reddit truths" that "Bambu's can't use their advertised print volume".
