### ISSUE TITLE
Edit Template for issue reporting

### ISSUE THREAD

**Issue by AbeFM** [bambulab/BambuStudio#770]
Perhaps consider editing the template to include tags so the instructions stand out from the response, and leave room to input info. Something like this:
```
**Is your feature request related to a problem? Please describe:**
<!--_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_-->



**Describe the solution you'd like:**
<!--_A clear and concise description of what you want to happen._-->



**Describe alternatives you've considered:**
<!--_A clear and concise description of any alternative solutions or features you've considered._-->



**Additional context:**
<!--_Add any other context or screenshots about the feature request here._-->



```
I left comment and italic in case you prefer one, though it's fine as is. For the curious, it displays as such:

**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by SaltWei** [comment]
Thank you very much for suggestions! Hope current template can be used easily.
Please reopen this issue if has some new suggestions.
