### ISSUE TITLE
bug: large temperature difference error preventing slicing when only using one filament (but synced to AMS)

### ISSUE THREAD

**Issue by tsdexter** [bambulab/BambuStudio#771]
**Describe the bug**
I have my filaments synced to the AMS which has 3 PLA and 1 PETG. When I add a model and set all of it and its support to 1 filament (petg) it won't allow me to slice the model due to 

![image](https://user-images.githubusercontent.com/4126987/205543423-abe61e2d-ceb7-4a3c-84f5-751ea6b29b81.png)

**To Reproduce**
1. load some PLA and PETG into AMS
2. synced filaments in Studio to AMS
3. Load in a file and set all of its filament/supports to use the same filament

**Expected behavior**
If I am only trying to print 1 type of filament, regardless of what is loaded in the AMS or the synced filament slots it should let me slice possibly related or fixed alongside #482 

**Desktop (please complete the following information):**
 - OS: Mac
 -BambuStudio 01.03.01.01

**Comment by zengzm1212** [comment]
I can't reproduce your problem，Could you provide your 3mf file, thanks!

**Comment by zhimin-zeng-bambulab** [comment]
@tsdexter  Could you reproduce this problem with the latest version?

**Comment by tsdexter** [comment]
> @tsdexter Could you reproduce this problem with the latest version?

I will try to reproduce in the latest slicer when I get a chance... In the meantime, I worked around it by not "syncing to ams" only only having the one filament configured in the project, rather than all 4 from the AMS.

**Comment by zhimin-zeng-bambulab** [comment]
@tsdexter  Hello, have you tried to reproduce this problem with the latest version? Is this problem still exist?

**Comment by zhimin-zeng-bambulab** [comment]
@tsdexter  Can you reproduce this problem? 
Best wishes, Thanks!

**Comment by SaltWei** [comment]
Since no update of this "unrepeatable" issue. Close at the moment.
Reopen if has new update.
