### ISSUE TITLE
Printing logos has many gaps in first layer

### ISSUE THREAD

**Issue by jadflat** [bambulab/BambuStudio#775]
![master system logo](https://user-images.githubusercontent.com/3272531/205852953-34a83053-da6f-45ea-bbd6-3a788b77227c.png)

when printing this logo it's full of gaps.

see comparison with Super slicer on the right

**Comment by randyre** [comment]
This is most likely related to #54 

I think we all are waiting for this implementation of the Arachne engine.

**Comment by SaltWei** [comment]
Arachne has been included in latest 1.4 version. Could you share the 3MF for us to check？
![image](https://user-images.githubusercontent.com/110660407/208042374-cfc8719a-61fb-4db2-975d-96077d4f6a8d.png)

**Comment by jadflat** [comment]
Hi,

Here you go.

Thank you

**Comment by SaltWei** [comment]
Sorry, I can't see a zip file compressed from 3MF file. Miss when uploading?

**Comment by jadflat** [comment]
Hi,

Maybe gmail blocked it.

I'll try again

**Comment by SaltWei** [comment]
OK. Could you use the latest version and use arachne to check whether be improved?
If yes, we will close this ticket.
