### ISSUE TITLE
How much RAM do you have on your machine?

### ISSUE THREAD

**Issue by WZ9V** [bambulab/BambuStudio#779]
How much RAM do you have on your machine?

_Originally posted by @sigxcpu76 in https://github.com/bambulab/BambuStudio/issues/12#issuecomment-1337970754_
      
16GB Linux Mint 21 Cinnamon

**Comment by deftdawg** [comment]
I was able to build in a Virtualbox with 12GB of RAM running nixOS (the same config with only 4GB failed), my guess is you'll need 8GB to 10GB of FREE mem to build...  so if you have anything other than a DE running you might want to close it or reboot to get the free memory cleaned up.

**Comment by WZ9V** [comment]
Thanks for the help.  This fixed official but I noticed the softfever version fails at the copy step in the container file.  I'll jump over there for that.
