### ISSUE TITLE
[Feature request] Z-seam painting

### ISSUE THREAD

**Issue by reify3d** [bambulab/BambuStudio#79]
While the Z-seam can be set to aligned, it is useful to allow greater control over where the Z-seam should be located for aesthetics and print tolerance. Please consider adding this feature.

**Comment by brandonraineri** [comment]
Also might be nice if we had a straight line option vs. just painting for this.  Sometimes when you hit aligned or rear, it doesnt actually choose a straight line for the seam.

**Comment by wuyifanfancy** [comment]
The seam painting will be added in the next release.

**Comment by YifanWuBambu** [comment]
It is added in the latest version.
