### ISSUE TITLE
[macOS] Unable to build

### ISSUE THREAD

**Issue by GiaPag** [bambulab/BambuStudio#793]
Hi, I'm unable to build on macOS Ventura
``` 
OpenVDB could not be found with the bundled find module.  You can try to
  specify the find module location of your OpenVDB installation with the
  OPENVDB_FIND_MODULE_PATH cache variable.
```
i read and followed your instructions, i also installed openvdb with brew but without success.
Anyone can  help me?
Thanks in advance

**Comment by lanewei120** [comment]
@GiaPag 
1. have you built deps before?
2. if yes, are all the deps built successfully on Ventura?
3. could you attach the whole build logs and commands here
thanks

**Comment by GiaPag** [comment]
@lanewei120 
Hi, yes
Here you go the log..
[deps.txt.zip](https://github.com/bambulab/BambuStudio/files/10193669/deps.txt.zip)
[build_error.txt.zip](https://github.com/bambulab/BambuStudio/files/10193670/build_error.txt.zip)

Thank you

**Comment by lanewei120** [comment]
there is building errors for the deps
![image](https://user-images.githubusercontent.com/106916061/206677465-8fad70a7-6983-4ff2-8f0d-a468c55c06df.png)

it seems the zstd is missed?

**Comment by GiaPag** [comment]
```
giapag: ~ $ ➜ brew install  zstd 
Warning: zstd 1.5.2 is already installed and up-to-date.
To reinstall 1.5.2, run:
  brew reinstall zstd
````

**Comment by GiaPag** [comment]
@lanewei120 
Hi
I building successfully deps using 
`export LIBRARY_PATH=/usr/local/Cellar/zstd/1.5.2/lib/ `
I think -lzstd doesn't work.
After i building BabmbuStudio correctly, the same with cmake abd Xcode command.
