### ISSUE TITLE
Merge in Organic supports from Prusa Slicer 2.6

### ISSUE THREAD

**Issue by deftdawg** [bambulab/BambuStudio#797]
Prusa has unveiled Organic supports which are a much more optimized variant of Tree supports

https://youtu.be/ThiuzonYH10?t=1622

When it becomes available upstream it would be really cool if Bambu Studio could incorporate the tech also.

**Comment by TheHogarthWorkshop** [comment]
+1 These supports are a game changer.

**Comment by psiberfunk** [comment]
Curious if pulling this in is on the roadmap ?  These are tree supports on steroids

**Comment by Klendat** [comment]
Any update on this?

**Comment by eugenmeltis3pg** [comment]
Anything?

**Comment by tangketan** [comment]
We'll merge Organic Supports in the next version.

**Comment by tangketan** [comment]
Official 1.8 has been released. Close this issue.
