### ISSUE TITLE
Issue Exporting on Mac

### ISSUE THREAD

**Issue by Mats3DPrints** [bambulab/BambuStudio#800]
**Describe the bug**
Press the green arrow to change from ‘Print’ to ‘Export’ move the cursor anywhere other than the drop down box and it’s fine, second you enter the two drop down options with the cursor, they both vanish. .

**To Reproduce**
1. Go to 'Bambu Studio on Mac’
2. Click on 'downwards arrow after stl is sliced to export'
3. Move cursor into the two options, Print and Export

**Expected behavior**
The options should now vanish 

**Screenshots**
Video can be found in the Facebook group. 

**Desktop (please complete the following information):**
 - OS: [Mac OS X ]
 - Version [Ventura]

**Comment by SaltWei** [comment]
@walterwongbbl So is this issue be fixed? If yes, please close this ticket
