### ISSUE TITLE
[Feature Request] Add the ability to provide a name for each plate

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#801]
My absolute favorite feature of Bambu Studio is the ability to add multiple plates to a project - it's so incredibly useful! One improvement that I would like to see would be to add a way to provide a name for each plate, maybe in the space beneath them? Sometimes I have parts that are very similar, and it's hard to see at a glance what the difference is, so being able to provide a name would be super useful. Thanks!

**Comment by SaltWei** [comment]
Already supported in latest version。 Close
