### ISSUE TITLE
Unprintable 3MF, slicing freezes at 5%

### ISSUE THREAD

**Issue by Kraminator** [bambulab/BambuStudio#802]
I have a 3MF file with quite a few objects for 2-color printing, but for some reason, it does not slice. Even after 24 hours on my iMac Studio M1, it is not going more than 5%.

I gladly send the file over, however, due to copyrights, I can not just post it on Github. Please send me an email address or other way to send the file to you.

**Comment by SaltWei** [comment]
Thank you very much for reporting issue to us to keep software being improved!
You can send file to email sallt.wei@bambulab.com and we will try to reproduce.

**Comment by theogott** [comment]
Is it [sallt.wei@bambulab.com](mailto:sallt.wei@bambulab.com) or 
[salt.wei@bambulab.com](mailto:sallt.wei@bambulab.com)?

**Comment by SaltWei** [comment]
Sorry. Typo!
Should be salt.wei@bambulab.com

**Comment by theogott** [comment]
For Size reasons, i generally recommend to zip the File and just drag it here into the Field. 
Because Mail only accepts small files.

**Comment by Kraminator** [comment]
Thank you, just sent it.

**Comment by SaltWei** [comment]
The software is stuck in the base software library clipper. Start to investigate.

**Comment by Kraminator** [comment]
Is there any news on this?

**Comment by QingZhangBambu** [comment]
> Is there any news on this?

It is a bug on clipper lib. A small wrong data caused that. a little bit tricky. because it's difficult to catch wrong data. I am working hard on it.

**Comment by QingZhangBambu** [comment]
We've fixed it. You can get it in the next version.

**Comment by Kraminator** [comment]
Great, thank you. When will the new version be released?

[Reto Kramer](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=20oc0u)	[20oc0u]
Best regards

Reto Kramer
www.techwithkramer.com

On April 6, 2023 at 6:41 GMT, QingZhangBambu ***@***.***> wrote:

We've fixed it. You can get it in the next version.

**Comment by QingZhangBambu** [comment]
in a week or two

**Comment by SaltWei** [comment]
https://github.com/bambulab/BambuStudio/releases/tag/v01.06.00.65 has been published
