### ISSUE TITLE
Photo added to Retry/Resume screen and fix the wording

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#807]
So I can’t view the image without hitting retry then play then stop? Can you’ll add a current bed photo with this error? Also there is no resume so retry means resume?
![BA5BC381-3084-477B-9F73-4AD88F6520E5](https://user-images.githubusercontent.com/48887257/206916785-2adb3443-2435-4398-8347-49e1edbee4bf.png)

**Comment by SaltWei** [comment]
This is not slicer issue.
Has report to printer side from where the message is send.
