### ISSUE TITLE
Tree supports base touching model.

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#816]
**Describe the bug**
Tree support base is on the model.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**Expected behavior**
Tree support should never place itself on model but should always originate from build plate and then "branch" over and around model to support the overhang.

**Screenshots**

![2022-12-12 (2)](https://user-images.githubusercontent.com/60475095/207122537-55d38926-586f-42d6-a0e0-eb769b48e9d6.png)
![2022-12-12 (1)](https://user-images.githubusercontent.com/60475095/207122586-00f3aace-2353-4e44-922a-ed4577880553.png)
![2022-12-12](https://user-images.githubusercontent.com/60475095/207122599-99c86a7d-1587-458e-a997-4e8bab8ddced.png)
[Stand.zip](https://github.com/bambulab/BambuStudio/files/10210849/Stand.zip)

**Comment by MusangKingBambulab** [comment]
Hi @randyre , I guess you wanna block those painting areas (hold right mouse click) instread of enforcing them. Moreover, I adjust the branch diameter to 2mm and brach angle to 57 degrees. The slicing result shows below. I also upload modified 3mf for your reference. Just let me know it will help.
![image](https://user-images.githubusercontent.com/116701250/207225036-063c9818-21e8-4a04-88b2-4de2b134c552.png)

**Comment by MusangKingBambulab** [comment]
> @MusangKingBambulab Yes that works, thanks. Normally though tree should not require you to use enforcers, I also tested the same model in Cura and it also lays on the top layers of the model by default.
> 
> Maybe there could be an option for tree supports bases to be normal and only on printbed.
> 
> But it is nice to see that it can be made to do this

Happy to hear your favorable reply and thanks for your suggestion. Ideally, we also wish all the tree supports are rooted on the build plate, but considering their self-support and avoidance, it really hard to cover all the situations, especially complex models with concave features. However, we will never stop moving forward to optimize current tree support to provide a better using experience.
