### ISSUE TITLE
User language cannot be changed

### ISSUE THREAD

**Issue by ZzoyozZ** [bambulab/BambuStudio#82]
My Windows 11 is in German. The German translation in Bambu Studio has many errors, so I would like to change the language to English. But, that seems impossible. I would be ready to improve the German translation, if I knew how to do it.

**Comment by lanewei120** [comment]
you can do it in following steps:
![image](https://user-images.githubusercontent.com/106916061/182056768-a427c129-3850-4424-811c-57153a4dad80.png)
![image](https://user-images.githubusercontent.com/106916061/182057312-0c55b7de-1ff3-47e0-9166-7f6ff5363f6d.png)
