### ISSUE TITLE
Artifacts on print after loading step-file 

### ISSUE THREAD

**Issue by hutje** [bambulab/BambuStudio#825]
**Describe the bug**
Artifacts on the surface after importing STEP-file in BambuStudio

**3mf File for This Bug**
[Strange Artifacts.zip](https://github.com/bambulab/BambuStudio/files/10231121/Strange.Artifacts.zip)

**To Reproduce**
1. Import step-file in BambuStudio
2. To see more clearly, open paint supports
3. Select bucket-tool with 100% smart fill angle
4. Hover over the surface and see the strange artifacts

**Expected behavior**
To compare it with how it should look, I have attached a high quality mesh of the same object.

**Screenshots**
![image](https://user-images.githubusercontent.com/15308350/207699885-99061bc3-e07c-4f2f-91a9-03758eff5768.png)
![image](https://user-images.githubusercontent.com/15308350/207699898-7eb56fc4-481d-4d67-8a9d-1f6fd9d144d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version  BambuStudio V01.03.01.01

**Comment by SaltWei** [comment]
Seems to be bug of Opencascad library. Will investigate further

**Comment by SaltWei** [comment]
This is stepToMesh format conversion issue of OpenCasCad library and not easy to be fixed.

We decided to increase the precision of conversion so this defect can be smaller in visually when in prepare page.
![image](https://user-images.githubusercontent.com/110660407/217690790-a8ff6830-df06-48ea-bb09-641fc2beb98c.png)

By the way, when precision of conversion is increased, the final gcode also can be smooth as arc when arc fitting is enabled. And the defect is also unvisiable in final printing model.

Increasing the precision of conversion will be included in next release.
Thank you very much for suggestions!

**Comment by SaltWei** [comment]
> Increasing the precision of conversion will be included in next release.

V1.5.0 public beta has been released

**Comment by amzaldua** [comment]
Red STL
Yellow STEP

<img width="307" alt="Captura de pantalla 2024-06-03 a las 14 57 02" src="https://github.com/bambulab/BambuStudio/assets/116205677/252da831-28e8-462d-a400-dfada6ae0106">
<img width="337" alt="Captura de pantalla 2024-06-03 a las 14 56 48" src="https://github.com/bambulab/BambuStudio/assets/116205677/f47d7f3b-302e-4fed-bce5-46589b0acba4">
