### ISSUE TITLE
Internal Solid Infill / Ensure vertical thickness

### ISSUE THREAD

**Issue by FlowForm** [bambulab/BambuStudio#836]
The new "ensure vertical thickness" option does not work.  When unticked it's supposed not to make Internal Solid Infill at the sloping walls, but still does. 

This is at 2 walls of 0,6. At 3x walls it doesn't add it. 

Version 1.4.0.17

![Skærmbillede 2022-12-15 212918](https://user-images.githubusercontent.com/84511476/207960616-a0dcc489-0a8a-4c03-a068-bd3d5d21ca11.png)

**Comment by SaltWei** [comment]
Could you please share the 3mf file for us to investigate?

**Comment by FlowForm** [comment]
I have send you a mail with the 3mf :-)

**Comment by SaltWei** [comment]
Sorry, I haven't received it. Did you send to salt.wei@bambulab.com?

**Comment by SaltWei** [comment]
Sorry, I haven't received the 3MF file. So I just use a ball to check but find no issue.
![image](https://user-images.githubusercontent.com/110660407/217408200-5b81eebf-162e-475e-a64b-fd85b7fde432.png)

**Comment by SaltWei** [comment]
Seems no update for a long time. Please let us known if still has issue and we will reopen.
Close at the moment.
