### ISSUE TITLE
Some links to Bambu wiki cannot be opened in the 1.4 release

### ISSUE THREAD

**Issue by attilah** [bambulab/BambuStudio#837]
**Describe the bug**
Open the slicer and click the clickable labels in the property panels, the ones that does not work:
- Top surface pattern
- Bottom surface pattern
- Sparse infill pattern
- Enable support
- Show "Live Video" guide page in camera window (also in dark theme it looks bad)

All the others are working well!

**Expected behavior**
Default browser opens with the given page

**Screenshots**
<img width="257" alt="image" src="https://user-images.githubusercontent.com/230432/207963672-e17dd385-3221-41ad-86a2-52d44ca608cf.png">

<img width="294" alt="image" src="https://user-images.githubusercontent.com/230432/207965150-1cf8e9b3-3088-48d4-a648-cc83da05aeb5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Bambu Studio: 1.4

**Comment by SaltWei** [comment]
Should be fixed on v1.5.0 public beta. Thank you very much!
