### ISSUE TITLE
Some SVG-files don't open correctly

### ISSUE THREAD

**Issue by coat64** [bambulab/BambuStudio#839]
Some SVG-files don't open correctly. An example is added. In this one you can barely see the contours 

 - OS: Windows 11
 - Version 1.0.4.0.17
![Peace_sign](https://user-images.githubusercontent.com/53837649/207983960-f70f6667-6b99-4fa5-8b66-5d7b5555f8d9.svg)

**Comment by zhimin-zeng-bambulab** [comment]
We do not support this kind of svg files yet, and we will improve it in the future. Thank you very much for reporting this issue.

**Comment by zhimin-zeng-bambulab** [comment]
It has been fixed in v1.6 released on github.
