### ISSUE TITLE
[Feature Request / 01.01.00.14 / macOS + ] Can not directly open .3mf file using bambustudio in Finder.

### ISSUE THREAD

**Issue by ptbsare** [bambulab/BambuStudio#84]
Steps to reproduce
1.Open Finder.
2.Right Click on a normal .3mf file.
3.Click 'Open With'
4.Can not select Bambustudio App.(grayed out)
5.The only way to open a .3mf file on macos is opening Bambustudio and clicking the import, which is inconvenient.

**Comment by YifanWuBambu** [comment]
It is fixed in the latest version.
