### ISSUE TITLE
Unable to select items in new slice and print drop down boxes

### ISSUE THREAD

**Issue by FreeManFreeThinker** [bambulab/BambuStudio#842]
**Describe the bug**
I am unable to select any of the options in the new drop-down menus for slice and print. As soon as my cursor is on the drop-down box, it disappears. 

**3mf File for This Bug**
All files

**To Reproduce**
1. Open a file
2. Click on the small arrow pointing downwards next to other slice or print
3. Try and click an option

**Expected behavior**
The drop-down box stays open and the action I click gets performed.

**Screenshots**
![test](https://user-images.githubusercontent.com/92778277/208003339-37273422-a887-45e2-bfbf-990dab72a498.gif)
![test2](https://user-images.githubusercontent.com/92778277/208003350-f0eb9390-533d-457f-940e-586ed8836094.gif)

**Computer Info**
 - macOS
 - Apple Silicon - Ventura 13.1

**Comment by FreeManFreeThinker** [comment]
Fully uninstalling and reinstalling using AppCleaner.app fixed it for me

**Comment by talldonkey** [comment]
I am also encountering this exact issue.
macOS, Apple M1 Pro, Ventura 13.0.1

**Comment by walterwongbbl** [comment]
> Apple Intel Core, Venture 13.0.1. I have the same Issue with 1.4.0.18

Please wait for the next version update.  We have fixed this issue.

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released as well
