### ISSUE TITLE
Mac: Theming is inconsistently applied, text is unreadable.

### ISSUE THREAD

**Issue by Fire-** [bambulab/BambuStudio#844]
> **Describe the bug**
> A clear and concise description of what the bug is.

The dark mode theme ( which was automatically enabled when I updated, and I cannot locate a setting to disable ) is inconsistently applied across the application, resulting in unreadable text in various locations, such as the Prepare tab's Objects list, and various labels in the Prepare and Project tabs. After additional testing, this extends to light mode as well, almost like these elements have their associated theme colors inverted.

> **To Reproduce**
> Steps to reproduce the behavior:

1. Open the app?

> **Expected behavior**
> A clear and concise description of what you expected to happen.

The theming should be applied more consistently across the UI, so that there aren't dark grey text elements on top of even darker grey background elements.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1456217/208011254-70ccf863-70dd-40f8-b63c-7b9ef1bdab34.png">
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1456217/208012090-11871383-d04f-441a-a54e-eec5bd1f2306.png">
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1456217/208011766-e1e73131-86bd-458d-89aa-5bb1a2206f4a.png">
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/1456217/208012103-84f4d91e-5f60-4e05-a2e3-67a020cbd0b8.png">

> **Desktop (please complete the following information):**

 - OS: Mac OS 13.1
 - Version 1.4.0.17

For added context, I've only been able to change the app's theme thus far by changing the entire system theme, which is a fairly undesirable association.

**Comment by walterwongbbl** [comment]
Hi.
Will the other pages do the same.  how about device page?

**Comment by walterwongbbl** [comment]
> > **Describe the bug**
> > A clear and concise description of what the bug is.
> 
> The dark mode theme ( which was automatically enabled when I updated, and I cannot locate a setting to disable ) is inconsistently applied across the application, resulting in unreadable text in various locations, such as the Prepare tab's Objects list, and various labels in the Prepare and Project tabs. After additional testing, this extends to light mode as well, almost like these elements have their associated theme colors inverted.
> 
> > **To Reproduce**
> > Steps to reproduce the behavior:
> 
> 1. Open the app?
> 
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> 
> The theming should be applied more consistently across the UI, so that there aren't dark grey text elements on top of even darker grey background elements.
> 
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> 
> <img alt="image" width="1487" src="https://user-images.githubusercontent.com/1456217/208011254-70ccf863-70dd-40f8-b63c-7b9ef1bdab34.png">
> 
> <img alt="image" width="1487" src="https://user-images.githubusercontent.com/1456217/208012090-11871383-d04f-441a-a54e-eec5bd1f2306.png">
> 
> <img alt="image" width="1487" src="https://user-images.githubusercontent.com/1456217/208011766-e1e73131-86bd-458d-89aa-5bb1a2206f4a.png">
> 
> <img alt="image" width="1487" src="https://user-images.githubusercontent.com/1456217/208012103-84f4d91e-5f60-4e05-a2e3-67a020cbd0b8.png">
> 
> > **Desktop (please complete the following information):**
> 
> * OS: Mac OS 13.1
> * Version 1.4.0.17
> 
> For added context, I've only been able to change the app's theme thus far by changing the entire system theme, which is a fairly undesirable association.

**Comment by walterwongbbl** [comment]
@Fire- 
Hi.
Will the other pages do the same. how about device page?

**Comment by Fire-** [comment]
@walterwongbbl the Device page seems to look fine

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/1456217/208738584-2212ba62-ccb8-4ba9-aff8-04f58562b287.png">

**Comment by walterwongbbl** [comment]
Hi.
Have you changed the font or color of the mac system.

**Comment by Fire-** [comment]
> Hi. Have you changed the font or color of the mac system.

no, they're all default

**Comment by walterwongbbl** [comment]
This will be fix this issue in the next version

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released. Please have a try, thanks

**Comment by Fire-** [comment]
@SaltWei checking in ( apologies for how late this is ) with 1.6.24 it appears that many of the text visibility issues have been corrected, however, many still remain; this ranges from "difficult" to "impossible" in terms of legibility

<img width="417" alt="Screenshot 2023-05-08 at 13 56 17" src="https://user-images.githubusercontent.com/1456217/236933597-bc4e4f97-eb34-4b4f-8e77-a46490861744.png">
<img width="765" alt="Screenshot 2023-05-08 at 13 53 59" src="https://user-images.githubusercontent.com/1456217/236933607-b527bc4b-2ed7-45d7-962a-e3f86c2ce0cf.png">

**Comment by walterwongbbl** [comment]
Hi.
Thank you for your feedback. We will optimize the color of the text in dark mode
