### ISSUE TITLE
[Issue] Dark Mode Inverts Color of Black and White Filaments Under AMS In Device Tab

### ISSUE THREAD

**Issue by hifihedgehog** [bambulab/BambuStudio#849]
This issue occurs in the *Device* tab when dark mode is enabled. Under the AMS filament selection area, if you have either a pure white or black color selected for a filament, a color block (by clicking on the pencil edit icon ✏️) will show up inverted in color, meaning black will show up as white and white will show up as black. Specifically, the problem occurs in the bounded box to the right of *Color* that shows a preview of the color which is showing up as black instead of white (or white instead of black) when in dark mode. As far as I can tell, only black and white colors are impacted. Turning off dark mode fixes this behavior.

Below in the example, you can see that black is shown yet it is a white filament which I have selected. I see the same behavior with the black filament in a different slot as well. I have added italicized subtitles below each screen capture to explain what is going on.

![DC6754CC-0F10-45CE-AECD-49D3898EB8E2](https://user-images.githubusercontent.com/16614343/208029553-1b6117d2-88fb-4632-9f53-35e37daa7fde.jpeg)
*Here you can see a white filament for the C3 AMS slot under the mouse cursor. I go ahead and click on it to edit it.*

![EBE9F957-D2F0-4754-81A8-FED2C1FB4F10](https://user-images.githubusercontent.com/16614343/208028760-9d9fb3ce-0533-4795-b9f9-8f8a28a37170.jpeg)
*Here I have already selected the white filament to edit it. Unexpectedly, in this filament edit dialog box, white is shown as black in the color preview box directly to the right of the line title **Color.** We will click on this color preview box to verify if this is white or black*

![FE54B69C-F61A-4054-924F-896C57B374BD](https://user-images.githubusercontent.com/16614343/208028757-154ba13a-63dc-4e58-81cf-595e79633449.jpeg)
*It is white. Here is where arrived after I have clicked on that color preview box to the right of color. In the pop-up window **Colour**, I see that white is selected, not black.*

**Comment by bambu123** [comment]
@SaltWei Please follow this picture to check if system textColor is modified.
![img_v2_c68f5337-5e1c-421e-91eb-b5d493317c0g](https://user-images.githubusercontent.com/112537880/208055310-2b87d3f9-de70-4189-871d-4b4fba30711f.png)

**Comment by hifihedgehog** [comment]
> @hifihedgehog Please follow this picture to check if system textColor is modified.
> ![img_v2_c68f5337-5e1c-421e-91eb-b5d493317c0g](https://user-images.githubusercontent.com/112537880/208055310-2b87d3f9-de70-4189-871d-4b4fba30711f.png)

I am on **Windows** and not macOS (note the window buttons in the upper righthand corner of the screen). This is what I see here. Color is correct in the Prepare tab. **However**, this is not the problem area. The issue is in the *Device* tab where I had noted earlier.

![0CCE7B45-9162-48E8-8DE2-362698682169](https://user-images.githubusercontent.com/16614343/208108410-22f71ac9-385b-4762-be1f-00b1e26cb1fb.jpeg)
