### ISSUE TITLE
Move Markers not staying in screen borders

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#856]
I should always be able to see the green red and blue arrows, why am I zooming out to where I can no longer see the location of where I need to perfect move it to just so that I can grab the arrow to pull the object

![Screen Shot 2022-12-16 at 9 06 34 AM](https://user-images.githubusercontent.com/48887257/208130303-ad9941e0-bac9-4426-b1f9-321bd31fd2a3.png)

**Comment by Benderrodrigu3z** [comment]
![Screen Shot 2022-12-16 at 10 51 27 AM](https://user-images.githubusercontent.com/48887257/208204309-d090ef85-d949-44fa-840a-adb2b91eabaf.png)

**Comment by lanewei120** [comment]
Hello @Benderrodrigu3z 

thanks for reporting this issue
could you show the detailed steps to reproduce it?

if it is specific to your 3mf, could you also help to upload the 3mf?

**Comment by Benderrodrigu3z** [comment]
it random but its usually after moving an object, its a constant issue on Mac

**Comment by zhimin-zeng-bambulab** [comment]
We are also trying to reproduce this problem but it is not easy, we will keep track of this issue.

**Comment by zhimin-zeng-bambulab** [comment]
Does this problem still exist in the latest version?

**Comment by zhimin-zeng-bambulab** [comment]
The problem cannot be reproduced and there is no response from the user. Close it.
