### ISSUE TITLE
Hide Popups button on Prepare Screen

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#859]
Note Popups keep reappearing after closing them when im trying to edit an object cause there in the way.

![Screen Shot 2022-12-16 at 9 26 02 AM](https://user-images.githubusercontent.com/48887257/208131290-b7f96d50-f2e9-49ec-b28d-5e918c8a060b.png)

**Comment by lanewei120** [comment]
which popup?

the above one or the below one?

the below one will be shown when you select an object, even you close it, it will appear again as soon as the object is selected in the object list

**Comment by Benderrodrigu3z** [comment]
hide all popups button, keep popups suppressed while on the prepare screen

**Comment by SaltWei** [comment]
Won't do, close.
Reopen this issue if has new scene or discussion
