### ISSUE TITLE
Negative Part Purge

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#861]
Converting an object from a Part to Negative Part keeps the color active as a purge color on the Prepare Screen but not the Preview Screen, if its a negative part why is it showing that color in the purge part? Changing it back to a part then changing the color then Negative parting it again fixes it
![Screen Shot 2022-12-16 at 10 24 58 AM](https://user-images.githubusercontent.com/48887257/208144271-99891416-4d83-49b2-b992-636eb3aa53bd.png)
![Screen Shot 2022-12-16 at 10 25 06 AM](https://user-images.githubusercontent.com/48887257/208144287-4a7b6575-e6c9-40e7-92c0-ea7aeffcec6f.png)
![Screen Shot 2022-12-16 at 10 25 10 AM](https://user-images.githubusercontent.com/48887257/208144295-78af1a5c-fb6b-493a-b02e-3a403392a0ce.png)

**Comment by SaltWei** [comment]
Available in v1.5.0 public beta
