### ISSUE TITLE
Cut Breaking Dimensions

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#862]
Cut Breaking its own Dimensions, exiting out of cut then back in for now corrects the bug, ps this was an issue on the last version as well

Why?
![Screen Shot 2022-12-16 at 10 02 09 AM](https://user-images.githubusercontent.com/48887257/208144512-ab314a2d-6153-4ed6-bd9f-7112c8cd242b.png)

Good
![Screen Shot 2022-12-16 at 10 02 24 AM](https://user-images.githubusercontent.com/48887257/208144517-1d289a28-5cd3-459b-b106-7a4486d94b6a.png)

**Comment by zhimin-zeng-bambulab** [comment]
@Benderrodrigu3z  Could you describle your problem in detail, and provide the steps to reproduce the problem? It will help us to solve the problem.

**Comment by zhimin-zeng-bambulab** [comment]
The phenomenon I see is that when exiting out of cut then back in, the cutting surface will be reset to the initial position.

**Comment by Benderrodrigu3z** [comment]
its random is the issue

**Comment by Benderrodrigu3z** [comment]
and is there a way to make the cutting plane white area view larger? to cut a corner I have to rotate it 8 times to even get the white area to touch the print, half the time I rotate the wrong way and its not touching the cutter that I can tell because the plane isnt in view of the object, purhaps it should color the print a slightly off shade as it hits the plane so that rotating it is no longer an issue, pics to come

**Comment by Benderrodrigu3z** [comment]
This should not be the same color for both sides, make one side a darker side and one side a lighter side incase the filament color is white
![Screen Shot 2023-01-04 at 10 42 18 AM](https://user-images.githubusercontent.com/48887257/210605403-9cfc325d-3fcb-4cca-a82f-89775d01c07f.png)

**Comment by Benderrodrigu3z** [comment]
also Edit undo should take it back to the last rotation for the cutting field, that doesn't work, clicking out kills the plane when your still in plane cut view.

**Comment by zhimin-zeng-bambulab** [comment]
We plan to improve the cutting feature in the future, it will take some time.

**Comment by zhimin-zeng-bambulab** [comment]
we have improved the cutting feature, please have a try.

**Comment by zhimin-zeng-bambulab** [comment]
Does this problem still exist in the latest version?

**Comment by zhimin-zeng-bambulab** [comment]
Close as no response
