### ISSUE TITLE
Delete an Object while still slicing doesn't Cancel Slicing

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#863]
We Can now delete an object while Slicing, this is occurring on Mac in this new version which breaks and freezes the BS Slicer because it doesn't stop the slicing process and ends in a crash, sometimes you can save it by clicking stop but that usually takes another 20sec for it to kick back

![Screen Shot 2022-12-16 at 10 13 58 AM](https://user-images.githubusercontent.com/48887257/208144986-095a3a55-d8eb-44b5-9025-fc98f5271bc5.png)

**Comment by lanewei120** [comment]
for mac, there will a crash report if crashed
could you send the crash report to us?

also is it a 100% reproducable issue or not?
and could you help to upload the 3mf here?

**Comment by lanewei120** [comment]
we tried it on the newest version and can not reproduce it

as this is a issue long long again
we close it currently

if still has this issue, please reopen it and provide the crash report

thanks
