### ISSUE TITLE
[BUG] UX:  Unreadable copy in Slicer 1.4.0.17

### ISSUE THREAD

**Issue by psiberfunk** [bambulab/BambuStudio#866]
![image](https://user-images.githubusercontent.com/19777571/208184256-48f1ecd9-1b9d-4175-b202-743a5c4f6aab.png)

There's a text overflow issue on the latest slicer release in the calibration popup window on Windows 11, as shown in the screenshot above.

**Comment by SaltWei** [comment]
fixed in v1.5.0 public beta
