### ISSUE TITLE
Handy: reprint from history not allowing printer choice

### ISSUE THREAD

**Issue by werewolfenn** [bambulab/BambuStudio#868]
**Describe the bug**
After a successful or failed print, I look through jobs in history.  I choose one, and attempt to send to printer, but I only get a single machine listed (i have 3).  I do not get any option to choose a different printer.  I could understand if the job could only get sent to the same machine as before, but that's not the case.  The printer that shows up hasn't been used in a couple of weeks, but it still is the only option.

**To Reproduce**
1. Go to '.Handy app, latest update.'
2. Click on 'User, then My history.'
3. Scroll down to 'any printed job'
4. Click Reprint

**Expected behavior**
I would expect all of my available printers to appear on the Prepare screen. It doesn't (on two different androids)

**Desktop (please complete the following information):**
Android phone using OS ver 10.

**Comment by SaltWei** [comment]
This is not slicer issue, and please turn to https://github.com/bambulab/Bambu-Handy to report APP issues.
Close
