### ISSUE TITLE
[Issue] Camera no longer works.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#870]
Upgraded to the latest version and camera won't play anymore. Keep getting "Stopped [-20000]!" error. However downgrading to the previous version, the camera works again.

**Comment by bani6809** [comment]
I get this error also. Previous version of bambu studio works. Current version of bambu studio gives "Stopped [-20000]!" error.

**Comment by bani6809** [comment]
Seems duplicate of #853

**Comment by LarryVand** [comment]
What platform (Windows or Mac) and what version? On my windows 10 is working fine.

**Comment by SaltWei** [comment]
Should be fixed in v1.5.0 public beta. Please have a check and let us known if still exist.
Thank you very much!
