### ISSUE TITLE
Fuzzy Skin setup

### ISSUE THREAD

**Issue by d3adam** [bambulab/BambuStudio#875]
Hi,
we need access to fuzzy skin setup parameters:
Fuzzy skin point distance and Fuzzy skin thickness.
Default Fuzzy skin is just not right.

**Comment by SaltWei** [comment]
![image](https://user-images.githubusercontent.com/110660407/209268703-ba157c7f-7e96-4f52-96b9-9903a4f9dfc3.png)
Please update to the latest version.
Close this ticket
