### ISSUE TITLE
Parameter Table can no longer switch filament

### ISSUE THREAD

**Issue by kartoffelfighter** [bambulab/BambuStudio#876]
**Describe the bug**
With previous versions, you could switch the used filament via the parameter table. In the latest version, the feature is buggy. Filament switch does no longer get applied

**3mf File for This Bug**
_independent of file_

**To Reproduce**
1. Open .stl
2. Split in half
3. Open parameter table via right-click 
4. Change filament for a part via drop-down
5. Click gets applied, but filament not

**Expected behavior**
Like before, the Slicer should change to the different filament

**Screenshots**
![image](https://user-images.githubusercontent.com/4410112/208259991-475fff6b-af3d-406f-b92c-99a9c1ff2729.png)
![image](https://user-images.githubusercontent.com/4410112/208260129-75ee9ba9-ec16-436c-b7a9-a67f09be8141.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.4.0.17

**Comment by Sirwill1968** [comment]
Confirmed this fails on Windows, but works on Mac OS.

**Comment by SaltWei** [comment]
same with https://github.com/bambulab/BambuStudio/issues/961 and will be fixed in next release

**Comment by kartoffelfighter** [comment]
Updated the Bambu Studio today, works again in Version 1.4.2.13
Thanks!
