### ISSUE TITLE
Will there be custom printer/non network printer options? (Cr10,cr10v2-v3 or any custom printer)

### ISSUE THREAD

**Issue by poolboy97** [bambulab/BambuStudio#878]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Benderrodrigu3z** [comment]
your asking for them to make a Creality machine.... that's a different companies crappy machine, why on earth would they ever want to downgrade themselves like that?

Admin close this for no comments on there own comment field

**Comment by poolboy97** [comment]
Well they have ender as list of printers and like many others (ultimaker, prusa slicer etc.) you can setup non network printers. So i wouldn't thought/think this is completely ignorant question.

**Comment by SaltWei** [comment]
It's open and welcome to add other printer preset. Since this is open source slicer.
But we don't have time to maintain them, and also we don't have all of these printers.
Ender 3 and voron have been now added already.
