### ISSUE TITLE
Negative Parts Have a Color

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#879]
a negative part has a color if you change the type to a part then back to a negative so that you can cut the negative part smaller. 

![Screen Shot 2022-12-17 at 5 31 42 PM](https://user-images.githubusercontent.com/48887257/208269778-60e8b240-40d5-4d8d-be7a-e546250a3ba2.png)

**Comment by Sirwill1968** [comment]
Bug not present on Windows or on Mac Monterey

**Comment by Benderrodrigu3z** [comment]
Mac OS Catalina
10.15.7 cant update any higher

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
