### ISSUE TITLE
V1.4 - Seam and Support Painting Causes Plate to Vanish - Mac

### ISSUE THREAD

**Issue by bonjipoo** [bambulab/BambuStudio#880]
When you toggle seam or support painting tools in Bambu Studio v1.4 the plate disappears on Mac version.

<img width="1252" alt="Screenshot 2022-12-18 at 11 08 45" src="https://user-images.githubusercontent.com/5507101/208295008-e6136e7e-8be2-41fd-8b86-c105f01a4e0c.png">

macOS Big Sur 
MacBook Pro M1

**Comment by lanewei120** [comment]
@bonjipoo 

the plate is not displayed under all of the painting pages
this is the expected behavior

**Comment by bonjipoo** [comment]
@lanewei120 Sorry I do not understand.  Before version 1.4 I could paint a seem now I don't understand where the plate goes.  Please explain.

**Comment by bonjipoo** [comment]
https://user-images.githubusercontent.com/5507101/208756115-cd9c50bb-9b78-4561-a3d5-d3682473c7be.mov

**Comment by lanewei120** [comment]
the plate I said before means the bed-plate
so I missed your meaning

from your video, the object disappears

could you share your 3mf to us for a check

thanks

**Comment by bonjipoo** [comment]
[3dbenchy.3mf.zip](https://github.com/bambulab/BambuStudio/files/10279998/3dbenchy.3mf.zip)


I had to Zip the file.  The model shown in the video above is not publicly available so I have uploaded the 3mf with a benchy.  Same issue with this file.

**Comment by Haidiye01** [comment]
May I ask if this issue still exists with the latest version V1.8 of the software

**Comment by Haidiye00** [comment]
After testing version 1.9, we did not find this issue. If you still have issues, please raise the bug again. Thank you~
