### ISSUE TITLE
V1.4 - Bambu Studio throws "error loading shaders" when opened - Mac

### ISSUE THREAD

**Issue by bonjipoo** [bambulab/BambuStudio#881]
As soon as the application is opened. The error is displayed

<img width="290" alt="Screenshot 2022-12-18 at 11 11 19" src="https://user-images.githubusercontent.com/5507101/208295140-be5bb034-6adc-48f2-b746-f2357f918bd2.png">

macOS Big Sur
MacBook Pro M1

**Comment by lanewei120** [comment]
@bonjipoo 
hello, what is the detailed version number of your machine?
please help to send the log files in /Users/user.name/Library/Application Support/BambuStudio/log here

thanks

**Comment by lgbell** [comment]
Have the same issue- error loading shaders-- BambuLab Studio 1.4.0.18, MacOS BigSur 11.6 MacBook Pro M1 chip- couldn't find the log file according to the listed path to send to support

**Comment by bonjipoo** [comment]
I wasn't able to find the log file requested.

I also wonder if the shader error is the problem bedhind the seam and support painting issue on MacOS BigSur with M1 chip

**Comment by lanewei120** [comment]
hello

@bonjipoo @lgbell 
we have fixed this issue and released the new version v1.4.1
please have a try

thanks
