### ISSUE TITLE
Auto-calc multiplier not working

### ISSUE THREAD

**Issue by mmontminy** [bambulab/BambuStudio#882]
**Describe the bug**
The auto-calc multiplier has changed. I used to regularly use .45 as a multiplier. Now that appears to do nothing. It looks like it might be changing the values but not updating the display. If you use a multiplier that drives the numbers out of range you get an error, but the shown values never change.

Edit: after more testing, the flush volumes appear to update if you change the multiplier before clicking auto-calc for the first time. After that any other changes to the multiplier aren't reflected.

**3mf File for This Bug**
No special file needed.

**To Reproduce**
1. Go to 'Flushing volumes'
2. Click on 'Multiplier', enter a new value other than 1.0
3. Click "Auto-calc'
4. Values don't change/update

**Expected behavior**
When you enter a new multiplier, auto-calc should update the flushing volumes.

**Screenshots**
The default multiplier:
![image](https://user-images.githubusercontent.com/16541357/208297095-18a1ee8c-257d-42ee-95c0-f4d6bd36d8ee.png)
Changing to 0.3 results in:
![image](https://user-images.githubusercontent.com/16541357/208297210-e8d84cfb-8803-46fc-b360-10e1c6cfa5bb.png)
Changing to 0.4 results in:
![image](https://user-images.githubusercontent.com/16541357/208297245-6442e1ba-2cc8-4e11-ab9f-8c4167d6191d.png)
It's doing something, but the values aren't changing...
Increasing the multiplier also doesn't appear to increase the numbers:
![image](https://user-images.githubusercontent.com/16541357/208297317-f3b3f520-6ef7-4c20-a862-03acd016cf9d.png)
![image](https://user-images.githubusercontent.com/16541357/208297347-a1e7bd1a-12e3-4613-9bb8-93b89fc6d0a9.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Studio 1.4.0.17

**Comment by zhimin-zeng-bambulab** [comment]
In general, use 1.0 as multiplier can meet the requirements.  The multiplier is used for additional scaling when the user thinks that the automatically calculated value is too small or too large.

**Comment by mmontminy** [comment]
1.0 is too aggressive. It also doesn’t address the fact that the scaling factor used to work and now doesn’t.

**Comment by zhimin-zeng-bambulab** [comment]
We will optimize the interaction behavior in future version.
