### ISSUE TITLE
New Send feature not working, wrong access code error

### ISSUE THREAD

**Issue by mmontminy** [bambulab/BambuStudio#883]
**Describe the bug**
Trying to use the new Send and Send all fail with an error "wrong access code. Please log out and log in to the printer again".
I've tried re-logging to the printer with no change.

**3mf File for This Bug**
Any file will cause the error.

**To Reproduce**
1. Select "Send" or "Send all" after slicing
2. Click on 'Send....'
3. After a brief progress bar an error is displayed

**Expected behavior**
I expected the file to be uploaded to the printer's storage so it could be printed from the control panel of the printer.

**Screenshots**
![image](https://user-images.githubusercontent.com/16541357/208297720-5876269e-0b19-4a92-a245-77fec373d25a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Studio 1.4.0.17

**Comment by GuyH77** [comment]
I had this, just do as it says and log out and back in on the printer. It sorted it, working fine since.

**Comment by mmontminy** [comment]
> I had this, just do as it says and log out and back in on the printer. It sorted it, working fine since.

I have, several times now. I just tried again and it's the same.

**Comment by FreeManFreeThinker** [comment]
I have this issue as well. macOS 13

**Comment by chrishilbert** [comment]
Also have this issue.

**Comment by Merlwynd** [comment]
There is more than one issue with sending a file to the printer SD card. See comment 982. There have also been comments in various forums. So far Bambu has remained silent.....I wish they would see it as a higher priority...or it least give some guidelines on what to try to fix......

**Comment by walterwongbbl** [comment]
We will try to reproduce this problem. are your printer and studio on the same network?

**Comment by walterwongbbl** [comment]
HI, When wrong access code is prompted again, a LAN connection dialog will pop up, allowing you to manually enter the printer's IP address and access code to connect. （next release version）

**Comment by SaltWei** [comment]
V1.5.0 public beta has been released
