### ISSUE TITLE
Option to select colors in AMS is missing [1.4.0.17]

### ISSUE THREAD

**Issue by ClauMat** [bambulab/BambuStudio#885]
When you use the option to change filament at layer height, and send the model to print, there is no longer the option to select secondary colors from AMS

**Version 1.4.0.17**
![image](https://user-images.githubusercontent.com/120935336/208301603-a0020b6c-85ad-4e51-bf8e-08c204032f48.png)

**Previous version**
![image](https://user-images.githubusercontent.com/120935336/208301388-9700a883-490f-48bc-bfdc-011ebb383ad6.png)

 - OS: Windows

**Comment by StoneLiBambulab** [comment]
Hi @ClauMat ,
I fixed the issue and the hotfix version will be published this week.

Thanks!

Stone Li

**Comment by SaltWei** [comment]
v1.5.0 public beta has been released.
