### ISSUE TITLE
Print head collides with printed object when using 'print sequence: by object'

### ISSUE THREAD

**Issue by kvnper** [bambulab/BambuStudio#886]
BS Version: 1.4.0.17
OS: Windows 10

Brief: Print head collides with printed object when using 'print sequence: by object'.

Description: The print head collides with the first printed object when printing one object at a time.

Project file attached:
[per-object-issue_BS1.4.3mf.zip](https://github.com/bambulab/BambuStudio/files/10253942/per-object-issue_BS1.4.3mf.zip)

Here is a screenshot of the positioning of the objects, showing the collision(?) avoidance area. The object on the right will print first and will be collided with when the second object begins printing.
![image](https://user-images.githubusercontent.com/47488385/208301969-be268885-34d6-4d36-9a28-58dfb9edb4b0.png)

**Comment by nkacena** [comment]
also having this issue. it seems print sequence is inherently flawed in that when it goes to change filaments and then resume a print, the print head does not account for previous object height so its path back to resume printing follows the shortest path and collides with a previous print.

**Comment by SaltWei** [comment]
Please use v1.5.0 Public beta to have a try.
Have fixed the collision issue of changing filemant when printed by object
