### ISSUE TITLE
version 1.4 no send button no klipper selection for ender 3 v2

### ISSUE THREAD

**Issue by Qballjos** [bambulab/BambuStudio#888]
**Describe the bug**
After updating to version 1.4.0.17 no more klipper firmware selection for ender 3 v2, app crash when trying to add physical printer (ipadres), send button disappears 
**3mf File for This Bug**
Not related to slicing

**Screenshots**

<img width="751" alt="Scherm­afbeelding 2022-12-18 om 17 56 17" src="https://user-images.githubusercontent.com/1911646/208310104-8f6d3a7b-956d-45bd-b9ca-06faf90d9609.png">

https://user-images.githubusercontent.com/1911646/208310074-37525241-59bc-4323-8411-b5be7be83cee.mov

**Desktop (please complete the following information):**
 - OS: Macos 
 - Version 13.1

**Comment by lanewei120** [comment]
@Qballjos 

hello
the send function need the firmware support
so for third-party printers
only "Export G-Code file" can be used

thanks

**Comment by Qballjos** [comment]
Well this did work with previous version until they decide to remove the klipper firmware portion for ender 3 v2 again.Op 20 dec. 2022 om 10:52 heeft Lane.Wei ***@***.***> het volgende geschreven:﻿
@Qballjos
hello
the send function need the firmware support
so for third-party printers
only "Export G-Code file" can be used
thanks

**Comment by lanewei120** [comment]
oops, correct my previous comment
the send function is also available on third-party printers which supports remote print

we will check it

also does your ender3's firmware the same with before?

**Comment by Qballjos** [comment]
I have klipper running on my Ender (latest version) This option was available to select in the previous version.Op 21 dec. 2022 om 14:41 heeft Lane.Wei ***@***.***> het volgende geschreven:﻿
oops, correct my previous comment
the send function is also available on third-party printers which supports remote print
we will check it
also does your ender3's firmware the same with before?

**Comment by StoneLiBambulab** [comment]
it is removed by mistake. i will add it back.

Stone Li

**Comment by StoneLiBambulab** [comment]
@Qballjos ,
 Hi, I have fixed the bug and the version will be published next week. The "Send" will be moved in the the print dialog . And the wiki page will be published after reviewed, https://wiki.bambulab.com/en/software/bambu-studio/printing-gcode-though-octoprint 

Thanks!
Stone Li

**Comment by Qballjos** [comment]
Ok the print option works again that's perfect, but the option to select klipper as firmware is still gone...., and the device tap no longer opens the mainsail/fluid page.

**Comment by StoneLiBambulab** [comment]
Hi @Qballjos ,
These commands are not supported by klipper, and it should be skipped and will not affect printing.

Thanks!
Stone Li
