### ISSUE TITLE
[FIRMWARE & SLICER BUG] New firmware does not pause print

### ISSUE THREAD

**Issue by H4kunaM4tata** [bambulab/BambuStudio#898]
5 prints lost, filament lost, not to mention electricity wasted.

Firmware: Latest
Slicer: Old slicer version, cannot run latest slicer on Linux.
Before you say slicer for Linux is working, I suggest you check on this to see that it is broken: https://github.com/bambulab/BambuStudio/issues/12

This pause was working just fine before the firmware update and now it seems to either be incompatible with older slicer version or it is just not working at all.

The printer keep printing like if I had never set the pause.

3MF file attached

![image](https://user-images.githubusercontent.com/35049512/208397097-a1faf088-0071-4114-9a82-baf475affb8d.png)

![image](https://user-images.githubusercontent.com/35049512/208397871-20f758ec-bc4b-4624-9175-9332d59e0f39.png)

[print_with_pause.zip](https://github.com/bambulab/BambuStudio/files/10258204/print_with_pause.zip)

**Comment by H4kunaM4tata** [comment]
I managed to slice the same file with BambuStudio 1.4 to isolate the "you must run latest firmware version" and the printer indeed no longer stops as you expect.
It keeps printing like the pause was never there.

**Comment by H4kunaM4tata** [comment]
Another user tested setting a pause at layer 20 and the printer did not stop.
User is running latest firmware and latest slicer.

Two different environment with the same problem!

**Comment by Brennholz3000** [comment]
Not sure if it is the firmware or the linux version of BambuStudio itself. For myself the pause at hight function works as expected on windows. I'm using the latest version of BS and the firmware is up-to-date.

**Comment by H4kunaM4tata** [comment]
> Not sure if it is the firmware or the linux version of BambuStudio itself. For myself the pause at hight function works as expected on windows. I'm using the latest version of BS and the firmware is up-to-date.

Another user tested and I'm pretty sure he is not on Windows.
Let check that out.
Thanks for the feedback.

**Comment by H4kunaM4tata** [comment]
Indeed, another user tested both Windows and macOS, his printer did not pause either.
3 users, 2 having problems while one seems to be fine. Something is not correct.

I didn't change the process.

**Comment by Brennholz3000** [comment]
> Indeed, another user tested both Windows and macOS, his printer did not pause either. 3 users, 2 having problems while one seems to be fine. Something is not correct.
> 
> I didn't change the process.

Thats pretty awkward. To make sure I updated BS again, just the small update where they fixed the cabin mobel, and sliced another model today, added the pause and printed it. Still worked as expected. Paused the print, I swaped a spool in the ams and resumed the print.

I'm really clueless, why its not working for you. Maybe check for aditional updates for BambuStudio by selecting 'Help' in the top left dropdown and click 'Check for Updates'.
Maybe there is a new subversion that might fix it for you or try reinstalling BS.
Newest version should be v1.4.0.18

**Comment by H4kunaM4tata** [comment]
It isn't just me, there's at least 5 users unable to pause the printer.

Filament wasted because it doesn't pause.

**Comment by lanewei120** [comment]
Hello @H4kunaM4tata 

it seems you have set the print order to "by Object"
![image](https://user-images.githubusercontent.com/106916061/209050407-6df489f7-e387-4c46-8e6d-ee8c3d6be528.png)

"pause print" is not supported when printing "by object"

thanks

**Comment by H4kunaM4tata** [comment]
@lanewei120 that is wild, I don't remember having this before.
5 users making the same mistake would be hilarious.

I'll see if I can get somebody to test, I can't fir the next few hours.

Thank you for checking this :)

**Comment by H4kunaM4tata** [comment]
@lanewei120 that was indeed the root cause but it doesn't explain how this was never an issue before.
More users got the same problem so it wasn't just me.

The slicer should notify or don't allow you to set pause under those circumstances.

Thank you 

![20221222_185335.jpg](https://user-images.githubusercontent.com/35049512/209126876-390b5f14-3f1c-4bae-af70-979c56fd4e4e.jpg)

**Comment by Brennholz3000** [comment]
> "pause print" is not supported when printing "by object"

Good to know. Thank you for clearing things up.

> The slicer should notify or don't allow you to set pause under those circumstances.

Yeah, that would be great. This would help many users running into this problem!
