### ISSUE TITLE
[Bug] I can not change the chamber fan speed on windows BS

### ISSUE THREAD

**Issue by NairoDorian** [bambulab/BambuStudio#904]
On the Windows version of Bambu Studio, I can not set the chamber fan speed.
While on the Handy Android app I can change the chamber fan speed.

When clicking any of the fan icon for the nozzle, aux or chamb, it opens a vertical window where the nozzle and aux box are on top of each other but it seems the chamber setting box would be under but it reach the bottom of the window/screen.

**Comment by zeroemso** [comment]
sounds like an environment problem not a bug that can someone reproduce.

**Comment by NairoDorian** [comment]
I am on a 4K display

**Comment by zeroemso** [comment]
iam talkin about your windows/gfx drivers. answer the questions where you asked for on openening an issue + upload pics.
its more likely you get a response when you give as much as informations about a problem.

**Comment by lanewei120** [comment]
@NairoDorian 
Please give a snapshot of your bugs
also, what is the display ratio on your windows? 100%,150%, or any other values?

**Comment by lanewei120** [comment]
next time to report bug, please follow the bug format
thanks

**Describe the bug**
A clear and concise description of what the bug is.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]
 - Version [e.g. 22]

**Comment by NairoDorian** [comment]
I did not go through the bug format because it appears to be happening no matter the project file.
I thought many more people had the same problems as I've seen on reddit someone had the same issue as me at least

To reproduce: just click on any of the 3 fan icons while connected to the printer, this will open a window with 2 square box on top of each other, controlling the nozzle fan and the aux fan, but the chamber control block seems to be under these 2 but I can not see it because it should be under them.

4K screen on Windows with 250% recommended scale

**Comment by lanewei120** [comment]
@NairoDorian 
could you give a picture of it?

thanks

**Comment by NairoDorian** [comment]
![IMG_20221219_200851](https://user-images.githubusercontent.com/8990554/209086514-199a1bed-9f8e-4823-864c-e92c46317c96.jpg)

**Comment by lanewei120** [comment]
@NairoDorian 
thanks,

please give a full picture of the whole studio

**Comment by NairoDorian** [comment]
![image](https://user-images.githubusercontent.com/8990554/209093323-b37f373d-90df-4ba2-b0fd-496e88aab478.png)

**Comment by NairoDorian** [comment]
![Screenshot 2023-01-03 012005](https://user-images.githubusercontent.com/8990554/210286832-dd454fea-ba68-4454-976b-c49b00bcbde6.png)

As you can see, the numbers to move the Z axis are also bugged.

I have the last drivers for all my hardware, latest Windows10 updated, so no issues from here

Changing the DPI scaling options via Windows helps but the Bambu Studio window is then not in 4K anymore.

**Comment by walterwongbbl** [comment]
This will be fix this issue in the next version.

**Comment by NairoDorian** [comment]
I have downloaded the latest 1.4.2 to ty the fix, it is working now fine with 250% recommended scaling on a 4K display, but as soon as I change to 300% or 225% or 200% I get GUI errors again, also now the extruder buttons and GUI is having problem as well.
I have included many pictures.
![300%Scale+FAN](https://user-images.githubusercontent.com/8990554/213778029-3e2ee2bf-91af-45a4-bed4-a45f8190da69.PNG)
![200%Scale](https://user-images.githubusercontent.com/8990554/213778040-5a23c19d-2e31-46e1-bb06-1b1870c6c3b5.PNG)
![200%Scale+FAN](https://user-images.githubusercontent.com/8990554/213778044-996712d1-3bed-4abd-b4f8-d54a6871ef19.PNG)
![225%Scale](https://user-images.githubusercontent.com/8990554/213778049-6ec33b42-4911-4a17-8f46-faa99d48f0df.PNG)
![225%Scale+FAN](https://user-images.githubusercontent.com/8990554/213778053-524cb245-6e4f-45c4-bc47-9546337a83cf.PNG)
![250%Scale](https://user-images.githubusercontent.com/8990554/213778056-fb013162-bbd7-45b9-ad69-f90abfdd7ed5.PNG)
![250%Scale+FAN](https://user-images.githubusercontent.com/8990554/213778058-eb961107-51d4-46d6-9c1e-a8b03b03daad.PNG)
![300%Scale](https://user-images.githubusercontent.com/8990554/213778061-18a893cb-43a8-41d2-935a-7c910d616cbb.PNG)

**Comment by walterwongbbl** [comment]
we changed the popup position of the window.  This will make the window display complete.    we will optimize the entire fan control window next.

**Comment by NairoDorian** [comment]
What about the Extruder control on the right that looks broken as well ? 
Also at 300% scaling the inside control panel require vertical and horizontal scrolling to see everything, this doesn't look normal

**Comment by walterwongbbl** [comment]
> What about the Extruder control on the right that looks broken as well ? Also at 300% scaling the inside control panel require vertical and horizontal scrolling to see everything, this doesn't look normal

Hi.
Because we didn't optimize studio at 300% scaling, so it will look abnormal.
We will continue to optimize in future versions.
