### ISSUE TITLE
Opening camera feed crashes BambuStudio 1.4.0.17

### ISSUE THREAD

**Issue by Hercules117** [bambulab/BambuStudio#909]
**Describe the bug**
Application opens fine. When attempting to open the device menu, opens fine. Clicking the play button to start the camera feed results in an "endless loop" of thinking, then when attempting to cancel crashes the application. 

**Expected behavior**
Should start the camera feed

**Screenshots**
![1](https://user-images.githubusercontent.com/56689922/208536890-db804775-2758-4224-a9b2-e3172f333f19.PNG)
![2](https://user-images.githubusercontent.com/56689922/208536900-8318eb38-7f3e-46f5-a641-3403991d200a.PNG)
![3](https://user-images.githubusercontent.com/56689922/208536904-12b1d24e-ab66-4bf3-9bff-d24a1f02c8fc.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit 
 - Version 21H2

**Comment by Hercules117** [comment]
Upgraded to 1.4.0.18, same issue.

**Comment by Hercules117** [comment]
Issue is also in two different laptops, with two different printers, (Identical) and also on the mobile app v1.0.6.

**Comment by bambu123** [comment]
We need the minidump to check the problem. 
A minidump can be generated from the windows task manager when the program is hung. 
Tell me which version of Bambu Studio are you using when sending back the minidump.

**Comment by Hercules117** [comment]
The dump file was too big to upload here, 972 MB. Uploaded to dropbox, please let me know if you need me to upload it somewhere else. I'm using 1.4.0.18. 
[https://www.dropbox.com/sh/ca5gkhth8xe2w55/AABsNsuNP-uysNzsbcww78L3a?dl=0](url)

**Comment by bambu123** [comment]
Ok，thank you！

**Comment by Hercules117** [comment]
Also, firmware version of the x1 is 1.03.00.00

**Comment by bambu123** [comment]
Not sure if it is really hung from the minidump.
I need another minidump to confirm.
Please let the not-responding error dialog show before catching the minidump.
Catch another minidump a few seconds later than the first one. Comparing the two states should get more information.

![image](https://user-images.githubusercontent.com/112537880/208915308-62f13a18-fa34-4f03-821c-98a01fc36081.png)

**Comment by Hercules117** [comment]
Okay, I uploaded the second dump file, 10 seconds after the dialog box appeared. My computer upstairs has an older version of studio, it opened the camera just fine. (1.3.0.25) The screenshot was uploaded to the same folder. 
https://www.dropbox.com/sh/ca5gkhth8xe2w55/AABsNsuNP-uysNzsbcww78L3a?dl=0

**Comment by bambu123** [comment]
Maybe this is a known issue with the dua-video-card system.
As mentioned here #244.

**Comment by Hercules117** [comment]
I will say I had this issue on multiple systems, one with dual graphics cards, and one with only intel-integrated graphics. I am also having issues with the iPhone app, the video isn't loading there either after the update.

**Comment by bambu123** [comment]
No, there should not be a crash dialog for the iPhone app. So are you mean the endless loading?

**Comment by Hercules117** [comment]
actually, the iphone app is working now. I'm still having issues with the PC camera feed. Everything else is working. I've also moved to another laptop, same issue.

**Comment by Hercules117** [comment]
*Work Around Discovered* I right forced it to use integrated graphics, but it has to be used each time for the camera feed to run. 
![Capture](https://user-images.githubusercontent.com/56689922/209697942-8eb551e7-6686-4886-a376-d719a9cb0c05.PNG)

**Comment by bambu123** [comment]
You can edit it in the NVIDIA config panel. Then the config is saved by the NVIDIA driver.

**Comment by joshwigginton** [comment]
Having the same issue. Workaround seems to work ok. 
![image](https://user-images.githubusercontent.com/2354924/210270636-77879795-106c-4e85-8cca-c50ff39f63e0.png)

**Comment by bambu123** [comment]
Yes, that's it.

**Comment by robandwend** [comment]
The nvidea control panel change worked for me.
