### ISSUE TITLE
[Bug] During Start GCode, the hotend always goes down to 140°C no matter what

### ISSUE THREAD

**Issue by NairoDorian** [bambulab/BambuStudio#911]
I tried changing the start gcode to change this temperature of cool down before bed leveling during homing toolhead

I thought it matched the line " M104 S140 ; set temp down to heatbed acceptable" but commenting that line is not enough

I modified the start gcode in case I want to skip the Bed Calibration and even if I do not check the box it go down to 140C during start, so I took a look inside the gcode and commented the whole "bed leveling" block and the whole "home after wipe mouth" block as well because they were both responsible for the 140C, it seems even G28 is causing problem in the latest block

Please let use skip this setting down temp to heatbed acceptable when we don't go through the bed leveling sequence
As of right now my quick fix is working

**Comment by NairoDorian** [comment]
We have been looking into this 140C issue and people seem to find my gcode helpful https://www.reddit.com/r/BambuLab/comments/zs4cgt/fastest_start_gcode_improved_default_calibration/

**Comment by SaltWei** [comment]
This is not studio issue and also not a bug.
When run G28, the printer will low the temperature to protect the bed.
If you don't want this behaviour, use "G28 T220" instead and the temperature will keep in 220 degree when run G28.
