### ISSUE TITLE
[ISSUE] Printer turn violent after last firmware

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#922]
Updated to latest firmware and slicer yesterday.  01.03.00.00
Printed PETG and it looked aweful with ringing and bad print in general. Tried another and noticed a more violent printer that was more aggressive on the jerk. specially infill and small items. 
Factory reset the printer and started pla print that turned out normal using a project file I have. Using the same profile I have used for 50 or so figures from flexi factory and Cinderwing.  Then I adjusted some chamfer on the same print that turned out great and next day when I woke up that same print turned out nasty with oval holes instead of rounds. 
Something is really wrong and unstable with either the new firmware, slicer or both.

**Comment by noellypoos** [comment]
Have similar, sounds like it is coming off the rails on some movements, then smooth as silk on others. Printing abs mostly.
