### ISSUE TITLE
[Feature Request] Add more built-in filament presets.

### ISSUE THREAD

**Issue by ptbsare** [bambulab/BambuStudio#93]
People can find the Kexcelled filament presets on the machine whereas there is no Kexcelled filament preset in bambustudio.
Hope that bambustudio can add more built-in filament presets of different manufacturers in recent releases.
![Screenshot_2022-07-28-18-47-48-365_com tencent mobileqq](https://user-images.githubusercontent.com/3147576/182642688-89b8de11-1071-418a-a17f-bc4c0f5f6887.jpg)
![54366c15eb66253e](https://user-images.githubusercontent.com/3147576/182643344-35793ea8-cb06-403f-996a-6f6d4d243e5e.jpg)

**Comment by lanewei120** [comment]
already supported and added customer self-defined filaments
