### ISSUE TITLE
[HIPS is missing from filament profile list in Bambu Slicer and the AMS Material selection.] HIPS is not available for selection as an available filament type on Bambu Slicer or on AMS material selection.

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#936]
Currently, HIPS filament is not supported by Bambu Slicer. As temporary workaround I have been using  Generic ABS which as similar properties. Please add HIPS as a supported filament type.

**Comment by MrBanana02** [comment]
I second this! At an absolute minimum, we should be able to create custom profiles for the AMS since it cant be overridden from the slicer.

**Comment by LunaCodeGirl** [comment]
Third!

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/4262322e-409b-4b05-ac7e-0209faf391aa)
Thank everyone for suggestions!
