### ISSUE TITLE
[Bug - v1.1.0.14] flow bridge value is out of range

### ISSUE THREAD

**Issue by MarcoPiazza83** [bambulab/BambuStudio#94]
I am conducting tests on the bridges.
In the Global -> Quality -> Advanced tab there is an option to change the flow of the bridge.
If I increase it to 1.1 (or otherwise above 1) , bambu studio goes into error.

<img width="414" alt="Schermata 2022-08-04 alle 07 37 18" src="https://user-images.githubusercontent.com/4783556/182895686-47ca7feb-f17e-4db7-9cb6-27d8098fdeb9.png">
<img width="414" alt="Schermata 2022-08-04 alle 07 37 08" src="https://user-images.githubusercontent.com/4783556/182895710-9567717e-73d8-4c55-abb9-3fdad8a77b8c.png">

**Comment by SaltWei** [comment]
Done
