### ISSUE TITLE
Option to change solid infill pattern

### ISSUE THREAD

**Issue by djngnear** [bambulab/BambuStudio#945]
It would be great to port over Superslicer's solid infill pattern settings option. When I select Monotonic for the bottom and Monotonic for the top, the solid infill pattern is Monotonic. However, when I change the top pattern to Monotonic Linear, the solid infill pattern changes to Rectilinear. And that sometimes leaves a poor quality top layer.

![Bambu Lab Rectilinear Screen Shot 1](https://user-images.githubusercontent.com/87901234/209421471-c5148f86-8b22-4eab-aa77-4941123250fb.JPG)

**Comment by SaltWei** [comment]
> And that sometimes leaves a poor quality top layer

Could you share the quality picture for us to debug?

**Comment by SaltWei** [comment]
Same with https://github.com/bambulab/BambuStudio/issues/1019.
Will be included in next release.

**Comment by SaltWei** [comment]
Included in https://github.com/bambulab/BambuStudio/releases/tag/v01.07.00.53
Thank you very much for suggestions!
![image](https://github.com/bambulab/BambuStudio/assets/110660407/4359d592-ba84-43fa-aea0-65a6429d4fe4)
