### ISSUE TITLE
[Issue] Bambu Slicing Bug (layers just get deletet in slicing and will not be printed).

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#952]
Single model Sliced in Prusa and Bambu Slicer. Prusa: No bugs at all, full model has been sliced without any missing layers. BambuStudio: Missing Layers in undefined heights. unable to start a print like this.

**Comment by SaltWei** [comment]
Please share the model for us to debug. Thanks!

**Comment by SaltWei** [comment]
No update for a long time. Close at the moment.
Reopen and continue to check when model comes

**Comment by immenz** [comment]
Hi, maybe I have a similar/the same issue.
I want to print the following printer case: https://www.printables.com/de/model/356301-arc-for-bambu-lab-p1p/files

Slicing looks as following: 
![grafik](https://user-images.githubusercontent.com/5603494/223107822-beeea92e-5524-4c16-af6f-b7e67fd2bb02.png)

I've observed this behaviour with other models, too. Resulting always in failed prints, when I try to print
