### ISSUE TITLE
[Feature Request] allow re-order objects in objects list

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#954]
currently the objects are arranged in the list in the order they are imported, but we should be able to reorder them in the list for multi color printing. if any objects overlap, the slicer puts the top colors first going down the list and unless they are ordered how you want them to print they don't print correctly

**Comment by SaltWei** [comment]
Do you mean one model multi part cases?

**Comment by SaltWei** [comment]
![image](https://github.com/bambulab/BambuStudio/assets/110660407/2c919f18-e8cd-40fa-863d-75c0bb6baf10)
Hope this feature helps
