### ISSUE TITLE
Object/part setting filament change doesn't work any more

### ISSUE THREAD

**Issue by Gridzilla** [bambulab/BambuStudio#961]
**Describe the bug**
Object/part setting filament change doesn't work any more

**3mf File for This Bug**
Any object

**To Reproduce**
1. Go to 'Object/part setting'
2. Click on 'Filament dropdown'
3. Select eg. filament 3
4. The dropdown reverts to filament 1

**Expected behavior**
It is expected to be able to change the filament setting

**Screenshots**
100% reproducible, when using 1 AMS

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.04.0.17 and 1.04.0.18

**Comment by Gridzilla** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/4488015/209640530-0a2ba107-17c8-4285-8d19-498a78ca9ba6.png)

**Comment by c2h5oh** [comment]
Can't repro - I've been printing filament testers for all my filaments for the last day or so and this has worked 100% of the time

**Comment by Gridzilla** [comment]
[2022-12-29 00-16-54.zip](https://github.com/bambulab/BambuStudio/files/10316864/2022-12-29.00-16-54.zip)
Short video demonstrating the issue

**Comment by SaltWei** [comment]
> We have fixed this issue in the next version。

Maybe the next next version?
