### ISSUE TITLE
Send To Printer 'File Name Update Bug'

### ISSUE THREAD

**Issue by NitsuaFox** [bambulab/BambuStudio#966]
when using underscore in name of file it reverts to saving as untitled name plate.

Example.
test_print

Edit, might not be related to '_' at all, seems intermittent for me now. 

eidt2, see info below as to why this is happening.

**Comment by TheCableGuy99** [comment]
I was just about to report that it doesn't name them at all. However, I am using spaces and haven't tried a single word. Clearly an issue as you say though with naming plates and sending to the printer. See attached images...

![IMG_2809](https://user-images.githubusercontent.com/39552752/209775182-be0c0a8a-186c-4cc6-afd7-de62cc948c69.jpeg)
![IMG_2808](https://user-images.githubusercontent.com/39552752/209775186-7020e215-3d6d-4208-9c34-5e9a51ca3a08.jpeg)

**Comment by TheHogarthWorkshop** [comment]
Yeah, I just had a weird one where the project was called Print_Object and I sent it to print, and changed its name to a single word, and it sent the original name with the _ so yeah, it's more than just that - theres something just not right there

**Comment by TheCableGuy99** [comment]
Just to confirm I tried another without spaces or underscores and called it "Lids", it stills set it as "Untitled_plate_1", so not a spacing or underscore issue, it's clearly with naming as a whole.

**Comment by TheHogarthWorkshop** [comment]
> Just to confirm I tried another without spaces or underscores and called it "Lids", it stills set it as "Untitled_plate_1", so not a spacing or underscore issue, it's clearly with naming as a whole.

yes. same here macOS M1

**Comment by TheHogarthWorkshop** [comment]
Okay so I think I narrowed this down to the following..... 

It doesn't update the name field until you click OFF of the edit box. So following editing the name, you need to then click on a blank pice of space so it looses its green border, THEN click on SEND.

Guessing the 'save' button just needs some additional code there to ensure it captures the changed field without user having to make sure to click off it.

**Comment by TheHogarthWorkshop** [comment]
Better now I know, but took me a while to realise, and also isn't intuitive anyway, needs to be like my comment above.

**Comment by TheCableGuy99** [comment]
Hey, I just tested it as I normally press "Enter" and it's looking like mine works as well with this method (I tried with spaces in the name as well). I just clicked in the popup box elsewhere instead of pressing "Enter" and it worked.

That's a good bit of investigative work.... nice one!
