### ISSUE TITLE
Request for adding Frimware Retract

### ISSUE THREAD

**Issue by Eifel-Joe** [bambulab/BambuStudio#969]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to have the possibility to choose between slicer retract and firmware retract (G10/G11).

**Describe alternatives you've considered**
For now i use slicer retract.

**Additional context**
I only have klipperized printers. I love the possibility to change retract settings during print in klipper suing Klippersreen. It would be nice to add this solution in your fork of BambuStudio.

**Comment by SaltWei** [comment]
This is not printer issue @bambu123 . But feature request for Studio of 3-rd printer.
@XunZhangBambu Please handle it.

**Comment by XunZhangBambu** [comment]
In 1.8 beta ,we add this feature
