### ISSUE TITLE
[Feature Request] Allow objects to move below plate plane and only print the parts that are above plate

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#973]
Currently BS doesn't allow any part of an object to move below the plate plane. Allowing objects to go below the plate, like in Cura, will save time in situations such as testing out overhang, or reprinting part of a big model that previously failed at a certain height. In these cases, the lower part of the model doesn't need to be printed.

**Comment by SaltWei** [comment]
Same with https://github.com/bambulab/BambuStudio/issues/585

**Comment by TheHogarthWorkshop** [comment]
This is actually supported in Superslicer,

**Comment by wirlybird** [comment]
This would be a good feature but it should also allow the part to be lifted from the build plate to create a gap.
This allows supports to go under a part when the second or third layer are too close to the build plate for supports.

**Comment by msteele999** [comment]
I would like this as well. I have some models that need to be dropped by 1mm below the plate to make their bases flush on the first layer

**Comment by bolsoncerrado** [comment]
+1

**Comment by SaltWei** [comment]
Has been included in v1.6 public beta
