### ISSUE TITLE
[and can you please add raft air gap to your bambu slicer please and thank you] raft air gap

### ISSUE THREAD

**Issue by BambuLabDiscord** [bambulab/BambuStudio#975]
Separation Distance – This is an important setting that defines the height of the air gap between the raft and your part. Typically, having a gap of at least 0.1mm will help keep the part connected to the raft, while still allowing for easy separation once the print is complete.

The Raft Air Gap setting is simply how large the gap is between the raft and the model itself. The larger this gap is, the easier it is to remove. It basically

**Comment by SaltWei** [comment]
Accept! We have marked this in feature wish list

**Comment by wirlybird** [comment]
I just ask for this also!

**Comment by c2h5oh** [comment]
I would have liked that feature yesterday - I've spent half an hour doing cleanup

**Comment by SaltWei** [comment]
Will be added in next release.

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta
