### ISSUE TITLE
Slicing Negative Parts 2 Bugs found

### ISSUE THREAD

**Issue by Benderrodrigu3z** [bambulab/BambuStudio#976]
This is from https://www.printables.com/model/321749-bambu-lab-ams-hub-remove-button/comments

When you hit slice it shows a print tower because the negative part was once a physical part and has a filament color roll attached to it but its a negative part...

Worse yet if you want to abs the parts or any other material you have to convert the negative part(s) to a part then change the new part to abs then back to a negative part

MacOS 10.15.7
there are other comments on the page describing similar issues

[AMS_Hub_PTFE_Button_V2.3mf.zip](https://github.com/bambulab/BambuStudio/files/10320535/AMS_Hub_PTFE_Button_V2.3mf.zip)

**Comment by SaltWei** [comment]
> AMS_Hub_PTFE_Button_V2.3mf.zip

For this model, the wipe tower is not caused by negative part. It‘s caused by different filament for support.
![image](https://user-images.githubusercontent.com/110660407/210033776-68f19ade-5c69-47e6-9e3c-3d2659aea2cf.png)

**Comment by Benderrodrigu3z** [comment]
you are correct, my bad, didn't realize that one of my profiles still had that selected thanks, I'll tell the uploader

**Comment by Benderrodrigu3z** [comment]
however the negative part is still a thing on going to the other color, I have tested and confirmed it

**Comment by Benderrodrigu3z** [comment]
![Screen Shot 2022-12-30 at 10 01 51 AM](https://user-images.githubusercontent.com/48887257/210089581-b526cace-f2a6-4ac9-bb5d-9ca1a6669a7a.png)
![Screen Shot 2022-12-30 at 10 02 11 AM](https://user-images.githubusercontent.com/48887257/210089587-c8d14a84-754a-4f75-b4c0-ca0ffb8a661d.png)

The Slicer removes the white only after slicing it but it still shows as a tower on the prepare screen, this has confused some users on the Discord and in Printables

**Comment by SaltWei** [comment]
FIx is available in v1.5.0 Public Beta
