### ISSUE TITLE
Not running on either of two windows computers

### ISSUE THREAD

**Issue by melfahn** [bambulab/BambuStudio#98]
I have had no luck installing/running this on two Windows machines, one Windows 11, one Windows 10.  Windows 11 installed fine but won't allow me to login "internal server error". Windows 10 installs (without the network plug-in that the Windows 11 prompted for). However it will not start. Shows splash and then A white UI for a brief moment and then it crashes. Thank you. The log initially showed that it couldn't find the network DLL. I copied out over from the Windows 11 machine, but it didn't make a difference except for the log getting a little further. Thank you

[Windows 10 crashing.zip](https://github.com/bambulab/BambuStudio/files/9273935/Windows.10.crashing.zip)
[Windows 11 not allowing login-internal server error.zip](https://github.com/bambulab/BambuStudio/files/9273944/Windows.11.not.allowing.login-internal.server.error.zip)

**Comment by melfahn** [comment]
the Windows 11 not logging in issue appears to have been temporary. This morning it allowed me to login.

**Comment by FiorenzaPrime** [comment]
I'm having the same issue with the program failing to start on Windows 10. The splash screen appears followed by a blank window, then the application force closes.

![Screenshot 2022-08-07 112600x](https://user-images.githubusercontent.com/110778052/183298993-da2d6564-3e12-463e-b5e5-dea87fc011d4.png)
![Screenshot 2022-08-07 112554x](https://user-images.githubusercontent.com/110778052/183298998-6cc07ada-308d-4176-b6b2-57e5930cfd32.png)
[eventviewer log.txt](https://github.com/bambulab/BambuStudio/files/9277057/eventviewer.log.txt)
[system info DxDiag.txt](https://github.com/bambulab/BambuStudio/files/9277058/system.info.DxDiag.txt)

**Comment by FiorenzaPrime** [comment]
Updated to the newest version 01.01.01.01 and it's working great now.

**Comment by lanewei120** [comment]
@melfahn 
do you still have issue now?

we have fixed a crash issue after splash window
