### ISSUE TITLE
Send to sd card while printer is connected to different LAN

### ISSUE THREAD

**Issue by Ali229** [bambulab/BambuStudio#982]
**Is your feature request related to a problem? Please describe.**
If you have multiple routers, you cannot send to SD card unless you are connected to the same network, you get the error as shown below:
<a href="https://ibb.co/r6zLG79"><img src="https://i.ibb.co/r6zLG79/printer.png" alt="printer" border="0"></a>
Weirdly I am able to send it to the printer without any issues. I think this is a limitation as when sending to SD card it bypasses cloud, however this should not be an issue as all modern device are able to connect to one another as long as they belong to the same network. 
Example:
192.168.0.15 < Bambu IP
192.168.0.100 < IP for the 2nd router
192.168.1.20 < PC IP

**Describe the solution you'd like**
Able to send to SD card while the computer and printer are on different routers but still on same network like other slicers allow. (Sending to my other printers that are on 192.168.0.XXX through octoprint plugins on those slicers)

**Describe alternatives you've considered**
There are no alternatives, I have to wait for each print to end before I can send another one.

**Comment by Merlwynd** [comment]
I can't send a file to the printer SD card even with only one router and one home wifi network. I have no trouble sending files for printing, viewing video, using Bambu Handy app, etc. I just can't send a file to the printer SD card. I get the same message as you got....that they printer and studio both need to be on the same LAN. How can they not be if I only have one router, and one home network? I ensured my computer (Win 10 laptop running Bambu Studio) was on 2.4ghz wifi, I have logged out and back in on both the printer and Bambu Studio. I have turned off my firewall for short time to see if that was blocking things....all with no change. I have tried asking for help on forums but did not get a lot of feedback...so I am extremely frustrated with this function as don't know what else to try.....wish someone could help me further....

**Comment by scutler81** [comment]
Having the same problem. My home network is segmented into different VLANs including one for IOT devices which is the segment the printer is on. From my Windows 10 laptop I can't connect to the printer to SD card even when I try connecting it to the same WiFi network that the printer is on.

**Comment by randyre** [comment]
Having the same issues due to using a Mesh network, all devices are the same IP address range but Studio says I'm not on the same LAN.

**Comment by armmaker** [comment]
I’m having similar issues. I’m connected to my router via Ethernet and the printer is connected to that router’s Wi-Fi network. Printer and computer are both within the same IP address range and I’m getting the same erro as mentioned above that the printer and computer are not on the same LAN.

**Comment by slurpey** [comment]
Same issue here - can send files to print without problem - get the "you have to be on the same LAN" for sending files to SD Card.  I do have a router to a Google Wifi mesh.  I see the live picture in bambu studio.  
![image](https://user-images.githubusercontent.com/10026060/210258738-b97abeee-9ead-4552-b154-b8458e8044ed.png)

As a note - by the nature of 3d printing and "makers", lots of us will be using complex network environments with iot devices, raspberry pi around, mutliple routers, coding etc.  So this will be a frequent need.  Thanks!

**Comment by jup2000** [comment]
Something recently broke, and now I'm getting this error.  It's definitely on the SAME network (192.168.10.xxx).  

Signing in and out, and re-adding the printers no longer work.

**Comment by vbkredeemer** [comment]
> 

Same here. 2 Accesspoints from Ubiquity and a Router from AVM. All meshed up. In beween a coax-bridge. So I am for sure in the same Network as my printer and "Send to SD-Card ist not possible. 192.168.1.*** . Hope this will be fixed. I am used to use klipper and this would be pain in the ... :-) Running up and down with a SD-Card is not longer state of the art.

**Comment by clowrey** [comment]
Same problem here... Both printer and desktop in the same subnet... On Windows.

**Comment by RaySajuuk** [comment]
Got my X1C today, same issue, same or different VLAN.

**Comment by Ali229** [comment]
This is no longer an issue, there is a prompt now that allows you to manually enter IP address of your printer, just make sure you reserve that IP for the printer on your router so it doesn't change! :)

**Comment by proNET-Southtirol** [comment]
sorry, but where ist this "prompt"? I am trying to send over to another subnet, it's not possible.

**Comment by wilg** [comment]
Just bought the printer, cannot get the "send" feature to work at all. All the other connectivity features work, and the printer is definitely on the same network as the computer. Not sure why everything else would work fine except this.

<img width="521" alt="Screenshot 2023-06-07 at 6 24 11 PM" src="https://github.com/bambulab/BambuStudio/assets/54353/9997d568-8f24-479a-aec1-c86e8e4ccf23">

**Comment by slurpey** [comment]
> sorry, but where ist this "prompt"? I am trying to send over to another subnet, it's not possible.

Any news on this?
