### ISSUE TITLE
 Lots of log files in /home/mylogin/.config/BambuStudio/log/

### ISSUE THREAD

**Issue by DSRV2FR** [bambulab/BambuStudio#985]
Hello,

Can you implement the possibility to limit the number of log files in ex: /home/mylogin/.config/BambuStudio/log/

Each time BambuStudio is started, 2 log files are created. Over time, we pollute our system with useless files, except for debugging.

Thanks

**Comment by lanewei120** [comment]
currently max to 30 log files are permitted
we will clean up these old log files automatically at bootup

could you confirm again?

**Comment by DSRV2FR** [comment]
Thanks for your feedback,

indeed, we do not go beyond 30 files. it's reassuring.

Nice work ;)
