### ISSUE TITLE
Uniform scale cannot be de-selected when multiple objects are selected

### ISSUE THREAD

**Issue by randyre** [bambulab/BambuStudio#988]
**Describe the bug**
Uniform scale cannot be de-selected when multiple objects are selected

**To Reproduce**
1. Open a file with multiple objects or clone a single object.
2. Select All
3. Scale
4. Uniform select is grayed out and cannot be de-selected.

**Expected behavior**
Ability to select multiple objects and scale them in only one or two dimensions.

**Comment by randyre** [comment]
May be distantly related to #959

**Comment by zhimin-zeng-bambulab** [comment]
Thanks a lot for your opinion,  we will fix it in the next version.
