### ISSUE TITLE
Ability To Set Z Gap For A Raft.

### ISSUE THREAD

**Issue by wirlybird** [bambulab/BambuStudio#989]
HI,
It would be very helpful to be able to set a Z gap for a raft.
Basically like a Top Z Distance as supports have.
This would allow you to set a gap between the last layer of a raft and the first layer of the print on top of the raft so the print does not fuse to the raft.
As an example in S3D they call it separation distance.

**Comment by SaltWei** [comment]
duplicated with   https://github.com/bambulab/BambuStudio/issues/975

**Comment by SaltWei** [comment]
Available in v1.5.0 Public Beta
