### ISSUE TITLE
Feature Request: Clear or Allow Deleting of Recently Opened Projects

### ISSUE THREAD

**Issue by kritoke** [bambulab/BambuStudio#99]
It would be nice to be able to clear or delete recently opened projects/files, especially if you end up deleting or moving them, it ends up just being filled with projects that says "File is missing."

**Comment by wuyifanfancy** [comment]
We will add this in recent release.

**Comment by SaltWei** [comment]
Deleting recently opened projects/files has been included in latest 1.4 version
